### PR TITLE
Pollen

### PR DESCRIPTION
**Pull request by randal-the-vandal**
This ship is my first work and I am not so bright when it come to this
I been unable to test the thing out duo I gotta go into a whole other rabbit hole thats VCS and BYOND

Why it is good for the game
A small botany ship related to the Syndicate botany faction SUNS the lore of the faction keeps changing.
its size is meant to be somewhere between a medium and small spacecraft.
The last thing I can say its main focus is botany

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
Too many crew for a small ship
You shouldn't have a CMO for a small ship where the focus isn't medical
Why do you have a shaft miner and mining equipment on a botany ship

**Comment by ZephyrTFA** [comment]
And I've reformatted your config json to actually work

**Comment by TypeVar** [comment]
> 

I actually think a shaft miner isn't a terrible idea for a botany ship, especially if botany is being reworked at some point. There needs to be someone designated to collect plants with a plant bag.

**Comment by Latentish** [comment]
A majority of the maptainers have agreed that we don't want this ship, apologies.
If you'd like more guidance and explanation as to why, I'm sure one of us would be happy to help you in the discord as well.

**Pull request closed without merging**
