### PR TITLE
Inteq aesthetic maintenance and additions.

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request

Been awhile, huh?

This PR is just me cleaning up my faction's colors, unifying it, and generally cleaning up my old sprite work + adding new soft suit for Inteq along with drop pouches.

Also updates the Keppie uniform sprites, there's also shoes and gloves but I need to add those in a seperate PR.

I'll add the soft suit and drop pouches to the actual ships in another PR down the line, rn this changes ALOT of sprites.

They're now a much crispier, cleaner chocolatey brown.

## But Halcyon, is there Digitigrade versions?

Yes, actually!

## Birdie versions?

Keppies are done, Vox soon:tm:.

changes below in a screenshot in game:

IRMG nu

## Why It's Good For The Game

Fixin' my faction's aesthetics.

## Changelog

:cl:
imageadd: IRMG clothing has been resprited with a cleaner color palette.
add: an IRMG spacesuit and an alternative drop pouch webbing sprite. currently not in game but will be down the line.
/:cl:

### CODE REVIEW

**Comment by Imaginos16** [comment]
that was fast

**Review by rye-rice — APPROVED** [review]
i love the lizard kissers

unrelated note, i wonder how a timeline of how the various faction sprites evolving over time would look

**Review by MarkSuckerberg — APPROVED** [review]
the dripsters get drippier

**Comment by Ebin-Halcyon** [comment]
Aaaaaaaa

**Pull request closed without merging**
