### PR TITLE
Two anomaly changes

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
These two didn't feel very dangerous.

## Why It's Good For The Game
Anomalies will not be as easy to disarm

## Changelog

:cl:
balance: Static anomalies now deal more brain damage.
balance: heartbeat anomalies now apply radiation burns to better telegraph their hazard.
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
evil

**Comment by Anderson-Cooper** [comment]
> evil

mark are you just going around adding prs to the merge queue

**Comment by MarkSuckerberg** [comment]
that's my job

**Comment by Anderson-Cooper** [comment]
> that's my job

keep up the good work, i have nothing else to do being kept up by the loud as fuck fireworks because freedom day

i will watch your progress with a bag of popcorn

**Pull request merged**
