### PR TITLE
Schmiedeberg-Class Remap

### PR DESCRIPTION
**Pull request by Sun-Soaked**
## About The Pull Request
An initially small thought about adding a bridge GPS to the old schmied that spiraled out of control into a total remap.
Heavily polishes up the shmied, optimizing it for a mercantile medicine-selling, plant growing playstyle.

Adds customized jobroles to better fit the schmied's aesthetic.

**Images:** 
In flight
image

In dock(map file)
image

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
Schmied was nice, now it's even nicer.
First ship with onboard conk tiles(with tetra's blessing)

## Changelog

:cl:
add: Remapped the Schmiedeberg-class Pharmacology ship.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
cool

**Comment by Sinbest** [comment]
Big improvement in my opinion.

**Comment by Recoherent** [comment]
i'll miss the clothing vendors and utter lack of retractor, but this goes hard. is that closet just a more manual CMO one stuff-ways or is it mostly custom?

**Comment by TypeVar** [comment]
image
he is smiling :)

**Review by PrefabQuasar — CHANGES_REQUESTED** [review]
why in the name of god does every pharmacology student spawn with a FULL BOTTLE OF FLOORPILLS, please remove all but one or two bottles of those from the map, they can spawn INSANELY BROKEN CHEMS

**Comment by Zevotech** [comment]
KEEP IT IN KEEP IT IN KEEP IT IN KEEP IT IN KEEP IT IN KEEP IT IN KEEP IT IN

**Comment by Zevotech** [comment]
EAT ALL OF THEM ROUNDSTART

**Comment by PrefabQuasar** [comment]
> KEEP IT IN KEEP IT IN KEEP IT IN KEEP IT IN KEEP IT IN KEEP IT IN KEEP IT IN

ZEVO NO

**Comment by Zevotech** [comment]
> > KEEP IT IN KEEP IT IN KEEP IT IN KEEP IT IN KEEP IT IN KEEP IT IN KEEP IT IN
> 
> ZEVO NO

image
ZEVO YES

**Review by PrefabQuasar — CHANGES_REQUESTED** [review]
additionally, your stairs dont line up spacially, one set of stairs to the bar goes up two levels to get to the bar, and the other goes down two levels to get to the bar, and theres only one set of stairs between the sides of the ship theyre on

**Review by PrefabQuasar — DISMISSED** [review]
this ship lacks a wideband, and could probably use some wall intercoms also you need to do another pass making sure all your wallmounts are rotated properly and not sharing a wall with lights, you've got some unrotated buttons, a couple lights on spots other wallmounts are already on, and an upside down locker on the bridge

**Comment by Ketrai** [comment]
Just make a subtype of floorpills that's not as good and double the bottles c:

**Comment by TypeVar** [comment]
Ship looks great, though I do have a few suggestions.

1. I think putting **dance floor lights under the tables at the bar** again would be nice. On the original Schmiedeberg, I put that there so the atmosphere is more calm less formal.
2. There are 2 chemistry job slots, so **chemistry should account for 2 chemists**. Giving the other chemist a chair of their own so they don't have to sit on each other's lap would be good I think. That, or **you could just have one chemist as well**. The same thing goes for botany, as even with 6 hydroponic trays, I found that one botanist is all that's really needed. Don't wanna have too many cooks spoiling the broth, you know?
3. Bartending by hand requires a lot of table space to organize drinks with. I'd suggest turning **this specific rack into a table** so you can get a sort of work triangle going. 
image

**Comment by TypeVar** [comment]
Also, what guns are actually available on this ship? It runs on uranium, so I think it's perfectly justified to have a ranged weapon to deal with fauna from a distance. And no, the dart gun is not effective against fauna.

**Comment by Recoherent** [comment]
you're not a schmied tester if you ain't done this before [spends half an hour sorting through eight entire bottles of roundstart floorpills]
haven't tested new density yet though! will observe

**Comment by Sun-Soaked** [comment]
I adjusted some stairs so it makes slightly more sense, but perfect spacial mapping would mean fully removing at least one stairwell(war crime) so we can just say the chem room is at a slant or smth

**Comment by Sun-Soaked** [comment]
pr images have been updated

**Comment by Sun-Soaked** [comment]
image
:HOW:

**Comment by Latentish** [comment]
> image :HOW:

Yeah I don't know why this happens.
The grilles in this screenshot are picked u from another ship that had bad grilles. but hte tiling I have no idea.
image
image

**Comment by Latentish** [comment]
Our commits are a bit behind on this one so I'll give a proper review once that gets pushed.

**Comment by Latentish** [comment]
Uptime is tomorrow, I'll test this then.

**Comment by PrefabQuasar** [comment]
sounds like theres still too many bottles of maintpills on here, i'd request that you limit it to a max of one pill bottle, random chem lottery is kinda dumb, and 3 bottles is 15 chances at getting chems that can straight up RR people

**Review by triplezeta — APPROVED** [review]
ok

**Comment by Latentish** [comment]
He is smiling =)
Also marg

**Pull request merged**
