### PR TITLE
Remaps Wasteplanet Pandora Attempt 2 Electric Boogaloo

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Remaps wasteplanet_pandora to not be a tiny box with a one-way entry into a locked room with a pandora. The mysterious duplicate lines have been removed for good this time (I remembered to hit "Sync Changes")
251871247-0c8241c1-58bf-4659-9218-7edbc9cff921
251876112-825e3f5a-4389-4bcd-99cf-49d05e821b4f

## Why It's Good For The Game
A ruin that is just a box with a one way portal into an arena with a dangerous enemy and no loot just ain't right. Hopefully this map can act as an example of what to do with megafauna/elite "boss" ruins.

## Changelog

:cl:
add: Remapped wasteplanet_pandora.dmm
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
failed check isnt even related to the map, god dammit

**Comment by Zevotech** [comment]
if this fails checks i go to sleep. if this passes checks i get icecream then go to sleep.

**Comment by Zevotech** [comment]
# IT PASSES CHECKS

**Comment by spockye** [comment]
Looks good, i'll see if i can get it Testmerged for next uptime

**Comment by Zevotech** [comment]
@goober3 points at this

**Comment by goober3** [comment]
sorry? this is an empty PR. i cannot see a thing

**Pull request merged**
