### PR TITLE
Delta Remap

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request
delta_ingame
delta

Original remap by miniusareas, updated by myself

Remaps the Delta-class Frigate into an explicitly Nanotrasen-themed robotic mining vessel. Features a number of improvements over the old Delta:

- starts with three minebots and AI upgrade cards for them
- comes with an AI core and a BORIS module
- has all necessary equipment to build more mining borgs and Ripleys
- Uses an ore processor setup instead of an ORM
- Various minor improvements to living spaces
- Updated crew list includes a captain, two roboticists, an engineer and three assistants

## Why It's Good For The Game
delta is old, crusty, and needed a remap

## Changelog

:cl:
tweak: Remapped the Delta-class frigate into a robotics-focused mining ship
/:cl:

### CODE REVIEW

**Comment by miniusAreas** [comment]
make sure to give credit to the person who did the original layout for the remap or I niko niko break your PR caps.

**Comment by Apogee-dev** [comment]
> make sure to give credit to the person who did the original layout for the remap or I niko niko break your PR caps.

Whoops. Done and done.

**Comment by moonmage04** [comment]
The stacking machine isn't actually needed as the sheets(or any stackable) stack just by putting them through a conveyor belt. The suit storage spawned empty and some lights were missing when I spawned one in.

**Comment by Apogee-dev** [comment]
> The stacking machine isn't actually needed as the sheets(or any stackable) stack just by putting them through a conveyor belt. The suit storage spawned empty and some lights were missing when I spawned one in.

the stacking machine is there as a form of storage, since you can't tell the ore processor to release specified amounts of materials, it just keeps processing until it runs out of whatever you've told it to process. The SSUs have since been fixed, and the missing lights are intentional.

**Review by PrefabQuasar — CHANGES_REQUESTED** [review]
the stacking and processing machine start unlinked, if it isnt possible to map them in already linked, please place a multitool next to a fluff paper giving instructions on how to link them

**Comment by PrefabQuasar** [comment]
aside from that, once you sort out the integration issues, this is mergeable, the integration issue is probably misplaced pipe somewhere or something along that line

**Review by PrefabQuasar — APPROVED** [review]

**Pull request merged**
