### PR TITLE
Dwarf Rework

### PR DESCRIPTION
**Pull request by Sun-Soaked**
## About The Pull Request
Rebalances and tweaks dwarves:

- Dwarves now gain nutrition when hungry and drunk. They can now subsist entirely off alcohol like the ethanovores they are.

- Dwarven alchohol burn speed has been slightly reduced when below their regen threshold, and considerably increased while above it
- Dwarves now enter a metabolic frenzy when above 400 alchohol(this is the regen threshold), during which their body temp begins to increase, growing higher more quickly based on the amount of alchohol in their system. If it gets too high, they start taking heavy burn damage. Ride the lightning!

- Antihol is now an alchohol-draining toxin when consumed by dwarves- Toxin, a little liver, and rapid alcohol loss, oh my!
A syringe or two of this delivered in pvp will likely prevent a dwarf from regenerating effectively, or it could be used to purge a dwarf back below frenzy level in an emergency.

- Dwarves now take 50% more stamina damage and have 30% longer stuns. Low center of mass + very heavy = poor balance.

- Dwarvish base healing has been greatly reduced to a 0.30 value instead of a 1.25. 

- Drinking high-quality alcohols now provides a small amount of bonus regeneration and have reduced heat gain while in a frenzy.

- Dwarf names have been given a facelift to be less memey.

- Dwarves stop processing alchohol level while they're SSD. You can now go to sleep without dying a horrible, unrevivable death.

- Dwarf cellular regen is now *fifteen times* less effective.

- Dwarf speed mod has gone from 0.5 to 0.6. Amazing.

- there is now a ui indicator for the dwarf alcohol meter

- Dropping to low alcohol is now less comedically lethal and more annoying- tox damage has been heavily reduced, dwarves now take nutriment loss and random blurred vision and stamina loss while at 0 alcohol.

## Why It's Good For The Game
attempts to save our most setting-violating, powergamey race from inevitable removal

## Changelog

:cl:
tweak: Dwarves now enter a metabolic frenzy when above 400 alchohol. This triggers their regen and rapidly increases body temp. When body temp gets too high, they start taking heavy burn damage. Ride the lightning!
tweak: Dwarf alchohol level now rapidly decreases when above 400.
tweak: Dwarf speed is 10% higher.
tweak: better dwarf names.
tweak: Dwarves no longer starve to death while ssd.
tweak: Dwarves now slur their words with much lower intensity while drunk.
balance: Dwarves now gain nutrition when very hungry and drunk. 
balance: Dwarves now take 50% more stamina damage, and have 30% longer stuns
balance: Dwarf regen power greatly reduced.
balance: Dwarf 0-alchohol damage greatly reduced. Instead, they now rapidly lose nutriment, take stam damage, and randomly get blurred vision. Fun!
tweak: alcohol now affects the power of dwarf regen slightly, based on drink quality.
code: adds a stamina mod to species.
/:cl:

### CODE REVIEW

**Comment by Sun-Soaked** [comment]
the dwarf alcohol level ui is in but it's criminal level coderspriting

**Comment by PiperDoots** [comment]
Honestly feel like we should just do away with the whole alcohol thing all together, it never really made any sense as is.

**Comment by Sun-Soaked** [comment]
idk it's fairly handwaivable- 
they metabolize alcohol, alcohol is a fairly high-density chemical energy source
presume that once they have a high enough concentration they enter some kind of fucked high metabolism phase

having them rely on a different unique food source is fun

If we wanted to go with funny accuracy I could make them consume alcohol faster and slowly heat up while in their regen range, due to all the heat their overdriven cells are making

**Comment by PiperDoots** [comment]
IDK tbh, not the biggest fan of dwarves as is. They're supposed to just be genemodded humans. And honestly, from a lore perspective, I can't see people genemodding in a reliance on alcohol for any good reason since it's much more of a detriment than a positive.

**Comment by Sun-Soaked** [comment]
alcohol is probably easier to come by then Actual Food during a nuclear winter
they're presumed to have emerged from Canada during the Bad Times, according to our lore

In any case we should prolly discuss this in loredev rather than these comments

**Comment by Apogee-dev** [comment]
honestly i just wish dwarves could be drunk without slurring everything and turning unintelligible like other species do

**Comment by Sun-Soaked** [comment]
> honestly i just wish dwarves could be drunk without slurring everything and turning unintelligible like other species do

I actually did this and then forgot to add it to the changelog. Dwarf drunk slurring is considerably less intense as of this pr.

**Comment by Sun-Soaked** [comment]
undrafting this now, since it'll likely take some time to finish new dwarf lore in compliance with our existing lore and the mechanics here are pretty much feature-complete

**Comment by ilikesaying** [comment]
what stops dorfs from taking temperature lowering toxins and reagents?

**Comment by Zevotech** [comment]
> what stops dorfs from taking temperature lowering toxins and reagents?

nothing, hopefully. if a dwarf player is smart enough to use leporazine or even just some rhigoxane then they deserve the buffs.

**Comment by Sun-Soaked** [comment]
though I agree with zevo, leporazine and pyroxadone(through temp scaling healing) in particular can completely mitigate overdorf, so I've made them cycle out of dwarves more quickly to compensate

**Pull request merged**
