### PR TITLE
Ashwalkers nerf and yeets the solgov history musuem ruin

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Kills the solgov history musuem ruin at the request of m
Ashwallkers now do not get a respawn, but still can be resucated via tendril. Teamwork?

## Why It's Good For The Game

The ashwalker changes were made after pillars of salt pillars of salt pillars of salt pillars of salt 

## Changelog
:cl:
del: Solgov history musuem
balance: Ashwalkers no longer can respawn. However, they can still be revived via the tendril.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
the idea is nice but I dislike how the medieval aesthetic gets thrown out a lot due to the many modern machines in it

**Comment by ZephyrTFA** [comment]
They seem to have quite a lot of electrical appliances for being medieval.
I'd recommend you change the name to something else.

**Comment by AtlasRules** [comment]
better yet, make it crystalpunk and give all the machines fancy magical snowflaked versions

**Comment by rye-rice** [comment]
removed castle walkers from the pr

**Comment by MarkSuckerberg** [comment]
Just think there should be a little more discussion on this, there's gotta be better ways to go about it than flat-out removing them from random spawn

**Comment by terg-but-ius** [comment]
personally i think the flavor text should just be changed to discourage the whole "hee hoo TDM" thing that some ashies have got going on.

**Comment by super12pl** [comment]
>  the whole "hee hoo TDM" thing that some ashies have got going on.

what the fuck does that mean

**Comment by rye-rice** [comment]
> > the whole "hee hoo TDM" thing that some ashies have got going on.
> 
> what the fuck does that mean

It means ashies that instantly grab spear, and hunt for the mining base to attack
In shiptest's case, it means ashies that instantly rush to the ship, and look for things to be provoked by so they can massacre a crew

**Comment by rye-rice** [comment]
Disabling was removed

**Comment by Valorium-RB** [comment]
What exactly is the reasoning behind removing the SolGov history museum? I thought it was a neat little ruin that gave access to a lot of items but very little ammunition - a good balance, I think. Plus, it's one of like two ways to get more M9C ammo (which is otherwise basically impossible given it's not available from cargo or to be manufactured). If we chuck the ruin, we should look into adding more ways to get extra M9C mags or bullets.

**Comment by rye-rice** [comment]
Tetra was more worried about the lore implications, but I could leave it in if someone wants to rework it

**Pull request merged**
