### PR TITLE
Makes .44 and .45 not the exact same cartridge

### PR DESCRIPTION
**Pull request by generalthrax**
## About The Pull Request

Increases .44 roumain damage to reflect the fact that .44 is a significantly more powerful round than .45

## Why It's Good For The Game

same
martin
chu

## Changelog

:cl:
balance: .44 is no longer near-indistinguishable from the far less powerful .45 caliber, about 5 more force
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
does this not make it as good as 357?

**Comment by generalthrax** [comment]
It's actually a more powerful cartridge than .357, funny enough. I'm not sure if anyone wants a 35 force cartridge though.

**Comment by rye-rice** [comment]
smiles evily

i think apogee wanted 357 to be more powerful than .44 short though, i need to ask though

**Comment by generalthrax** [comment]
I'll wait on Martin and Apogee to see what to do from here. I just thought it seems a little off for a cartridge as powerful as .44.

**Comment by Apogee-dev** [comment]
> It's actually a more powerful cartridge than .357, funny enough. I'm not sure if anyone wants a 35 force cartridge though.

.44 Roumain is _not_ intended to be equivalent to .44 Magnum. It's not a magnum cartridge at all, in fact. It's intended to be something like .44 Special, which was .44 Magnum's parent case - similar to the relationship between .38 Special and .357 Magnum. If we ever add an actual .44 Magnum revolver it would need to be nearly as rare as the ashhand.

**Comment by generalthrax** [comment]
Well there it is

**Comment by Martinpachu** [comment]
liiimbuss companyyyyyyyy

**Pull request closed without merging**
