### PR TITLE
Misfire changes

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
misfires can now go off into any bodypart (you'll shoot your eye out)
Guns can now have a misfire multiplier assigned to them
frontier import guns now misfire more often (I thought this would be funny)

## Why It's Good For The Game
Thought it'd be nice

## Changelog

:cl:
balance: frontier import guns now misfire more often
add: guns can now misfire into your head.
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
if i’m reading the code right RPGs have a multiplier of zero and won’t ever misfire. this is both completely understandable and terribly disappointing

**Comment by Anticept** [comment]
Funny as that would be, there's too many safeties in explosives for that to happen.

So as a solution..... We need more improvised launchers :D

**Comment by Erikafox** [comment]
> if i’m reading the code right RPGs have a multiplier of zero and won’t ever misfire. this is both completely understandable and terribly disappointing

Just the Hammer - it's supposed to be always hot but not trip and blow yourself up hot. (No 'safety" but always ready to go)

**Comment by DIB-DOG** [comment]
> > if i’m reading the code right RPGs have a multiplier of zero and won’t ever misfire. this is both completely understandable and terribly disappointing
> 
> Just the Hammer - it's supposed to be always hot but not trip and blow yourself up hot. (No 'safety" but always ready to go)

We need the RPG-7 shortcoming where you can take off the safety cap from the rocket, then drop it and have it go off. As gun Jesus, Ian McCollum, demonstrates.
https://youtu.be/6QXy2yzoaRI?si=vgYJCUSrRpVoQp_4

**Pull request merged**
