### PR TITLE
Removes printing circuit imprinters

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
see title

## Why It's Good For The Game
pushes us closer to scarcity

## Changelog

:cl:
del: You can no longer print circuit imprinters at circuit imprinters.
/:cl:

### CODE REVIEW

**Comment by goober3** [comment]
yet another erika removal pr......

**Comment by Erikafox** [comment]
I hate fun

**Comment by goober3** [comment]
this shipmin is OUT of control

**Review by rye-rice — APPROVED** [review]
I DEMAND!!! THAT "Bjarl" BE DEMOTED!!! It was the best-

**Comment by zestybastard** [comment]
Congrats everyone! Shiptest is officially dead. I will be logging onto Voidcrew to get my fix of circuit printing RP from here on out; it is clear to me that the goal is simply to strip away mechanics until everyone is completely nuggeted and unable to do anything but roleplay lizard kissing. I remember when we could have such fun rounds as that time a crew dissected a thousand goliath corpses so they could finally use the circuit imprinter to build a chem machine and revive their dead crewmate (instead of calling one of those so-called "medical ships"), but that time is over now. Instead, admins and "maintainers" would have us be helpless babies who can't even fill every ship with research equipment anymore. Not to mention all the characters for whom the circuit printer was an essential gameplay element (such as my lizard static Prints-The-Circuits), who will now simply have to stop existing because the admins hate RP? It's ridiculous. Expect to be further ridiculed in my upcoming Reddit treatise on the matter.

**Comment by rye-rice** [comment]
> Congrats everyone! Shiptest is officially dead. I will be logging onto Voidcrew to get my...

GET BACK TO DISECTING YOU MD MAIN

**Comment by MarkSuckerberg** [comment]
> Congrats everyone! Shiptest is officially dead. I will be logging onto Voidcrew to get my fix of circuit printing RP from here on out; it is clear to me that the goal is simply to strip away mechanics until everyone is completely nuggeted and unable to do anything but roleplay lizard kissing. I remember when we could have such fun rounds as that time a crew dissected a thousand goliath corpses so they could finally use the circuit imprinter to build a chem machine and revive their dead crewmate (instead of calling one of those so-called "medical ships"), but that time is over now. Instead, admins and "maintainers" would have us be helpless babies who can't even fill every ship with research equipment anymore. Not to mention all the characters for whom the circuit printer was an essential gameplay element (such as my lizard static Prints-The-Circuits), who will now simply have to stop existing because the admins hate RP? It's ridiculous. Expect to be further ridiculed in my upcoming Reddit treatise on the matter.

I'm sorry, but you don't have enough LKP (Lizard Kissing Points) to redeem for an opinion on the github. This was your final warning. I will lift your gitban in `37 years` due to the severity of your opinion.

image

**Comment by thgvr** [comment]
shiptest has fallen

**Pull request merged**
