### PR TITLE
Scrapper-B (The Discovery)

### PR DESCRIPTION
**Pull request by Omppusolttu**
## About The Pull Request

This is the PR for the Scrapper-B

## Why It's Good For The Game

New ship 👍 

## Changelog
:cl:
add: The Scrapper-B Exploration Vessel
/:cl:

## Picture
Discovery

### CODE REVIEW

**Comment by HighPrincessErinys** [comment]
I think you should take a note of out retlaw's playbook and just make this scrapper type B. either way looks neat, but you should probably put a different type of wacky raw animal flesh in that backroom just as a minor differentiation.

**Comment by Omppusolttu** [comment]
> I think you should take a note of out retlaw's playbook and just make this scrapper type B. either way looks neat, but you should probably put a different type of wacky raw animal flesh in that backroom just as a minor differentiation.

The names are designed to make their purposes clear, scrapper type B wouldn't really bring along the idea of a science vessel in the slightest, but I shall change it for another animal.

**Comment by HighPrincessErinys** [comment]
> scrapper type B wouldn't really bring along the idea of a science vessel in the slightest

but. thats the entire point of the type B type C stuff. a known and beloved ship chassis gets a little fucked up and different. i know theres only the boyardee rn but i know shes working on riggs and dwayne alt types which change up the ship layout and theming fairly drastically

**Comment by triplezeta** [comment]
the structure and purpose is different enough that I think it warrants a name change

**Pull request merged**
