### PR TITLE
resolves slimegirl trafficking bug

### LINKED ISSUE #364: The roundstart shiptest is broke as fuck?
Issue reported from  Round ID: [296](https://shiptest.ga/stats/rounds/296) (Shiptest)

Reporting client version: 514.1557

image
what

also I spawned a different ship and it wasnt fucked like this, also the roundstart one was a riggs class

### LINKED ISSUE #445: [BUG] Every turf on a ship gets deleted randomly, or better known as the "slimegirl trafficking" bug
## Round ID:
NA
## Testmerges:
NA

## Reproduction:
This bug is very well known, but im putting it here for documentation sake

One of the oldest  and most bizzare bugs to grace this codebase. Randomly, every single turf will get delete on a ship, leaving the machinery and players behind.

The only known triggers are:
Selling a slimeperson on a cargo pad
whenever #364 triggers
Docking at a empty space (#454)

Images:
image
Screenshot_1388
Screenshot_1518

### LINKED ISSUE #454: [BUG] empty space docking massively increases the rate of slimegirl trafficking incidents
## Round ID:

[424](https://shiptest.ga/stats/rounds/424) i think

## Testmerges:

#230
[TEMP] Disable loadout costs by @AsciiSquid
Commit: a7399a3
Last Christmas, I gave you my heart
#313
Overmap Expansion #2 by @retlaw34
Commit: e07969d
But the very next day, you gave it away
#403
Adds Quirk specie-locks, vampire quirk. by @Ms-Mee
Commit: 1786e35
This year, to save me from tears
#344
[not EXTREME not DRAFT] THE LORE DROP PR by @tiramisuapimancer
Commit: ddf565d
I'll give it to someone special
#440
Metis-class by @PrefabQuasar
Commit: 670d675
#380
NTSV Osprey by @Apogee-dev
Commit: a48d386
#450
Swifter's Ship Emporium But Updated by @triplezeta
Commit: ea05619

## Reproduction:

I'm not exactly sure but I have a hunch.

So, Metis class, Denu-Ezts. We docked in empty space. Then I go to aghost for a bit to set up shenanigans. Then we get slimegirl trafficking incidented. Then a pill lands on top of us (and we are now at a sand planet)

What I think happened is that the reserve that we were on was overwritten by the sand planet the pill was attempting to land at.

### LINKED ISSUE #494: [BUG] Landing and Undocking royally screws with atmos (at least on the Shetland)
## Round ID: 
[458](https://shiptest.ga/stats/rounds/458)

## Testmerges:
#230: '[TEMP] Disable loadout costs' by AsciiSquid at commit a7399a3607
#132: 'Readds Explosive Decompression' by MarkSuckerberg at commit 286ea4dbb5
#462: 'Finishes sec rearming, sort of rebances ship sec , Starfury facelift' by retlaw34 at commit 46e2c1c398
#450: 'Swifter's Ship Emporium But Updated' by triplezeta at commit 3e040a06bd
#403: 'Adds Quirk specie-locks, vampire quirk.' by Ms-Mee at commit 80ee4a882b
#344: '[not EXTREME not DRAFT] THE LORE DROP PR' by tiramisuapimancer at commit 157628d269
#464: 'Mining Textures & More: Revival' by MemedHams at commit 669d909437
#467: 'resolves slimegirl trafficking bug' by jupyterkat at commit 169301cc46

## Reproduction:
Step 1: play on the shetland
Step 2: dock on a (non-jungle) planet
Step 3: be bewildered as your ship suddenly has less air and a lot more BZ than normal
Step 4: undock
Step 5: lose a dangerously large amount of air for no reason. (but only sometimes)
EDIT: I HAVE BEEN INFORMED THAT THE LAST PART IS BECAUSE OF AN ADVANCED AIRLOCK CONTROLLER BEING FUCKY.

### PR DESCRIPTION
**Pull request by jupyterkat**
## About The Pull Request

fucking byond breaks out of the entire proc when runtimes are thrown, this delays those runtimes to AFTER the for loop is done for looping 
closes #445
closes #454 
probably closes #364
closes #494 

## Why It's Good For The Game

yes

## Changelog
:cl:
fix: shuttles are less likely to be cut in half by runtimes
/:cl:

### CODE REVIEW

**Comment by HighPrincessErinys** [comment]
HISTORIC: Shiptest Authorities have confirmed that they have busted the intergalactic slimegirl trafficking market, and have arrested more than 73 ringleaders. More at eleven.

**Comment by MarkSuckerberg** [comment]
oh my god

**Comment by terg-but-ius** [comment]
the evil has been defeated

**Comment by jupyterkat** [comment]
expected behaviour now is that turfs that failed to transfer will be left behind, and not half the fucking shuttle

**Comment by TheNeoGamer42** [comment]
:how:

**Comment by rye-rice** [comment]
At long last...

**Comment by ZephyrTFA** [comment]
bruh I didnt even know byond supported C#-esque try catch bullshit

**Review by ZephyrTFA — APPROVED** [review]

**Comment by Nobelium-XVIII** [comment]
> bruh I didnt even know byond supported C#-esque try catch bullshit

Sigma coder grindset

**Pull request merged**
