### PR TITLE
Adds survival knives to the Colossus, Talos and Vaquero.

### PR DESCRIPTION
**Pull request by Martinpachu**
## About The Pull Request
As the name says!
## Why It's Good For The Game

It's kind of fucked only the Valor gets them.
## Changelog

:cl:
add: Survival knives to every inteq ship.
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
show screenshots of where you're adding these and I'll look at merging this.

**Comment by Martinpachu** [comment]
image
image
image

**Review by Latentish — APPROVED** [review]
good

**Comment by Latentish** [comment]
good

**Pull request merged**
