### PR TITLE
removes fugitives and gangs

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
see title

## Why It's Good For The Game
I'm on a crusade. A cruft crusade.

## Changelog

:cl:
del: everything families and gangs except for the stupid waldo outfit I'm getting rid of that later mark my fucking words
/:cl:

### CODE REVIEW

**Comment by goober3** [comment]
dudfe why would you do that gangs and fugitives are literally vital to shiptest gfampleay theyhter my favifrt sgihtest frureatre and t i wi ould i woudk fcry if yoiui trtfemoved them

**Comment by MarkSuckerberg** [comment]
already did this in #2127

**Comment by Erikafox** [comment]
> already did this in #2127

remove the hud icons and get it merged then that pr's like a month old

**Comment by MarkSuckerberg** [comment]
sob

**Comment by ritorizo** [comment]
image

**Comment by tiramisuapimancer** [comment]
leave the waldo outfit its really funny to forcefully waldo people with the select equipment button

**Pull request closed without merging**
