### PR TITLE
Disables the Komodo

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

Makes the Komodo adminspawn. This is a temporary measure until the Komodo's replacement is finished.

## Why It's Good For The Game

the komodo has a downright rancid reputation and is pending a replacement anyway. Putting access to it under admin control helps at least a little, letting admins allow players with a proven record to run it without completely locking it away.

## Changelog

:cl:
balance: Made Komodo aspawn
/:cl:

### CODE REVIEW

**Comment by lectronyx** [comment]
Unless things have drastically changed, Komodo behavior has always been on the same line as Inteq, even having cases where Komodo players would attempt to RP a solution only for Inteq to simply not play along (see the protest event of last month, and how a lack of appropriate in-character behavior caused needless escalation and ultimately derailing an event)

**Comment by MassiveMen** [comment]
> Unless things have drastically changed, Komodo behavior has always been on the same line as Inteq, even having cases where Komodo players would attempt to RP a solution only for Inteq to simply not play along (see the protest event of last month, and how a lack of appropriate in-character behavior caused needless escalation and ultimately derailing an event)

Things have drastically changed

**Comment by lectronyx** [comment]
> > Unless things have drastically changed, Komodo behavior has always been on the same line as Inteq, even having cases where Komodo players would attempt to RP a solution only for Inteq to simply not play along (see the protest event of last month, and how a lack of appropriate in-character behavior caused needless escalation and ultimately derailing an event)
> 
> Things have drastically changed

From all the videos I've seen and PRs I've seen get pushed through, it honestly just looks like admins punching down on players and the players having to find ways to work around it. When you defang a military faction, people are going to either abandon it or try to find ways around the nerfs - it's a really volatile thing.

I believe a lot of this could have been avoided if Komodo balance was handled by people who actually play on it, as opposed to people who know so little that they assume that a set of armor is actually a gun (there's no such thing as an Infiltrator Rifle, they removed _a set of armor from the vault based on the look of the box._)

**Comment by Apogee-dev** [comment]
for my trick, i will remove research, cargo, and ruin loot from the game simultaneously. my reign of tyranny shall be absolute, the balance of shiptest frozen in amber forevermore

**Comment by rye-rice** [comment]
For the record, this was on the shipcut list, so I felt fine about merging this immediately

**Pull request merged**
