### PR TITLE
Adds mining vendor curcuit in universal circuit vendor

### PR DESCRIPTION
**Pull request by Yata9ar4su**
## About The Pull Request
Adds mining vendor circuit to vendor circuit board list for universal vendor circuit. 

## Why It's Good For The Game
Mining vendor now has mor ways to be built

## Changelog

:cl:
add: Mining vendor circuit board in universal circuit board list
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
Nope

**Comment by FalloutFalcon** [comment]
> Nope

To expand on this, the vendor is full of stuff we are already trying to lessen, mainly powerful mining gear which makes it way faster to mine. We are trying to balance our mining around basic pickaxes and lower mineral counts since you dont have to supply an entire station. A similar idea for things that make it easier to kill fauna.

**Comment by Yata9ar4su** [comment]
> > Nope
> 
> To expand on this, the vendor is full of stuff we are already trying to lessen, mainly powerful mining gear which makes it way faster to mine. We are trying to balance our mining around basic pickaxes and lower mineral counts since you dont have to supply an entire station. A similar idea for things that make it easier to kill fauna.

I can kill fauna from red tumors with 2-3 claymors from legion bodies or pirate sabers, find 1-2 krushers on per one frozen planetoid but ok. Got it.

**Comment by FalloutFalcon** [comment]
> > > Nope
> > 
> > 
> > To expand on this, the vendor is full of stuff we are already trying to lessen, mainly powerful mining gear which makes it way faster to mine. We are trying to balance our mining around basic pickaxes and lower mineral counts since you dont have to supply an entire station. A similar idea for things that make it easier to kill fauna.
> 
> I can kill fauna from red tumors with 2-3 claymors from legion bodies or pirate sabers, find 1-2 krushers on per one frozen planetoid but ok. Got it.

i have a pr open 4 that,,,,

**Pull request closed without merging**
