### PR TITLE
Syndicate Cascade Class Genetics Vessel

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request

image

say hello to your New warcrime ship, the Cascade! It was created as a part of (the Terrestrial General Medicine Corps)' attempt to start Research into Genetics. oh... what's this? You are the lucky winner of donk co.(TM)'s surprise giveaway! upon your purchase of (3x Donk pockets), you have received a free carpet and a box of slimy goodies! go forth, and show the world your Genetical horrors!

## Why It's Good For The Game
There are currently no ships that are focused on Genetics, which is the spot this ship will fill. the Cascade comes with a large Biodome full of monkeys, a fully stocked medical bay. everything you need for some relaxing Genetical work and a crate containing everything needed to set up a xenobiology lab

## Changelog
:cl:
add: Adds the Cascade-class Genetics ship
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
(Engl: Terrestrial General Medicine Corps)

I'd recommend putting an R&D server board somewhere on the ship and a note clarifying that it is required to link the DNA consoles to the server in order for genetics to work properly

**Comment by Zevotech** [comment]
this is an exceptionally well designed ship, good job

what are the contents of the bottles next to the syringe gun?

**Comment by spockye** [comment]
> what are the contents of the bottles next to the syringe gun?

just Morphine.  i left it there to deal with the eventual Monkey uprising

**Comment by Zevotech** [comment]
not even a wee bit of sodium thiopental? unfortunate!

**Comment by MusselMain** [comment]
It's very nice looking, and will fit a role we currently lack. however, (WARNING LORE NERD MOMENT=>) Isn't the TGMC a NT subsidiary? but then this vessel is run a syndicate vessel? I'm a little confused by this, but then again I don't know as much Shiptest lore as I do TGMC lore, so maybe I'm mixing the two

**Comment by spockye** [comment]
> It's very nice looking, and will fit a role we currently lack. however, (WARNING LORE NERD MOMENT=>) Isn't the TGMC a NT subsidiary? but then this vessel is run a syndicate vessel? I'm a little confused by this, but then again I don't know as much Shiptest lore as I do TGMC lore, so maybe I'm mixing the two

i don't really know much of ship tests lore, though when deciding on a faction, i used "https://hackmd.io/@shiptest/lore/%2FdjBofH_pQ7KcEvF0n53CTg#The-Naturalienwissenschaftlicher-Studentenverbindungs-Verband"
where they are under the syndicate seemingly. though if its wrong, I'll change it to something else

**Comment by MusselMain** [comment]
Very nice ship, however I want to ask? is there a microwave? I see donk pockets, but no microwave, If I'm wrong let me know, but I just noticed and wanted to make sure it was fixed if it was a issue.

**Comment by triplezeta** [comment]
needs swords

**Comment by spockye** [comment]
> Very nice ship, however I want to ask? is there a microwave? I see donk pockets, but no microwave, If I'm wrong let me know, but I just noticed and wanted to make sure it was fixed if it was a issue.

yes and no. i never ended up getting the space for it, and decided to just limit them to the uncooked ones. 




> needs swords

what kind? i feel like giving them a bunch of energy sword/cap blades would be a bit op

**Comment by triplezeta** [comment]
you would be correct. there isnt really a good "practice sword" that would fit these nerds

**Comment by Valorium-RB** [comment]
> you would be correct. there isnt really a good "practice sword" that would fit these nerds

Why not just some varedited cap blades that deal stamina damage and have higher block chance?

**Comment by triplezeta** [comment]
wouldnt be able to get sheathes for them due to how those work

**Comment by Apogee-dev** [comment]
You should consider using Syndicate and especially NSV-themed outfits and job titles for the remaining jobs, _especially_ the security officer, since the majority of jobs use Nanotrasen outfits by default. I would even trim some jobs out (cargo jobs in particular can be readily sacrificed) to make the ship more specialized into genetics and add assistants to take care of any tasks that aren't covered. Having absolutely no assistant slots is highly unusual in general.

**Comment by Latentish** [comment]
For a ship meant to fit a genetics niche (which is good), it has a couple problems. I think a common problem ships have is just tossing cargo in as a job when it really unbalances the ship. Maybe just scrap the cargo space. In its place you should really expand the genetics lab itself. The space the geneticists sit in to do their funny work is rather small, and only allows for one geneticist to work at a time. I like that the genetics room has a direct access to the monkey room, but I dislike that it's the only way in.
I'd request:
Remove cargo.
Make the genetics room bigger.
Add another genetics station (the pod and console).
Add another door leading into the genetics room.

**Comment by Apogee-dev** [comment]
I’m going to second what SweetBlueSylveon said, overall this ship feels like it’s a bit too good at everything and not specialized enough into its intended niche. I’d nerf most of the non-genetics or medical departments by removing high-grade specialty equipment like the combat wrench and RPD, give cargo and its associated jobs the axe entirely, and just have a couple of pickaxes, ore bags, and manual scanners in the storage bay so the assistants can still dig up fuel when the ship needs it. No PKAs or crushers to start with, they’re somewhat easy to acquire as loot from Legions and the armed secoff can kill fauna that threaten the ship.

Also, make sure you’re using Syndicate space suits and not the nanotrasen presets. Use the “inherit” SSU type and place the syndie soft suits on top, it will scoop them up like a closet as the map initializes.

**Comment by ghost** [comment]
I like how this looks, I wish TG genetics had more crazy things you could make.

**Comment by RuneQuester** [comment]
Why is every cool/well equipped ship Syndicate...
guh...

**Comment by Latentish** [comment]
I really like how how your rooms look, good use of space pretty much all around. But I feel that the overall shape of the ship is too blocky overall. 
Maybe try rearranging the rooms to the sides?

**Comment by Apogee-dev** [comment]
You've got the wrong wall type for a few of the angled walls on the rear half of the ship. They're nukie shuttle walls rather than normal plastitanium walls. If it's a concern about smoothing, they'll still smooth with plastitanium windows but not airlocks. Also, you used nodiag walls on the front left corner of the ship where I think you meant them to be sloped (since the opposite side is sloped).

**Comment by Latentish** [comment]
While I would like to see some better shaping in this shuttle, that is a LOT of work to map. As it is, this meets my expectation for a shuttle. I would just like to know if any problems have arisen during testmerge.

**Comment by Latentish** [comment]
You're going to hate me, but please put the cargo console back on the ship. With the advent of outposts, they're basically a requirement now, and no longer a massive balancing issue.

**Review by rye-rice — CHANGES_REQUESTED** [review]
Use regular catwalks instead of turf catwalks please.

**Review by Latentish — CHANGES_REQUESTED** [review]
-Add a cargo console.
-Use real catwalks instead of turf catwalks

Do that and we can marg, because this works fine otherwise.

**Review by Latentish — APPROVED** [review]
This is a pretty good ship. Made the proper changes. This can be marged.

**Pull request merged**
