### PR TITLE
Update_Appearance Port

### PR DESCRIPTION
**Pull request by Sun-Soaked**
## About The Pull Request
[(original pr)](https://github.com/tgstation/tgstation/pull/55468)
After nine years in development we hope it was worth the wait

I ported this specifically for the signals I'll need for world icons. However, it had a lot of other useful stuff, so I ended up just grabbing (almost) the entire pr.
I tried to grab as few of the superfluous code rewrites as possible to make reviewing a bit easier, but I couldn't help grab stuff like the APC icon code rewrite(the original code was a war crime).

## Why It's Good For The Game

- ports the wrapper proc `update_appearance` for icons, descs, and names, adds `update_desc` and `update_name` subprocs to handle those. Things. without just stuffing them into update_icons like some kind of psychopath

- ports a bunch of signal hooks useful for changing names, descriptions, and icons. I needed these for world_icons which is where this wild ride all started

- ports some `base_icon_state` implementation. Stuff like spear code makes slightly less duplicates(and more sense) now which is nice.
We could definitely implement it more I think but that's a future me problem

- 500 files of immersive vsc-mass-editing action to implement `update_appearance()`(sorry in advance, but not as sorry as I was when manually copy-pasting the custom ones for like 3 straight days)

-"consig" and "comisg" have been taken out behind the codebase and shot. Not 'technically' a bug it just made my head hurt

-My first pr with 0 player facing changes (confetti)

## Changelog

:cl: TemporalOroboros, Memed Hams
code: ports update_appearance, update_name, and update_desc from tg, as well as associated signals
code: a bit of base_icon_state implementation. Can you believe it's been sitting in our code almost unused for like 3 years
code: cleans up some code formatting, mainly around custom icons and overlays
code: fixes the typos in COMSIG_STORAGE_EXITED and COMSIG_STORAGE_ENTERED
/:cl:

### CODE REVIEW

**Comment by Sun-Soaked** [comment]
ignore the world_icon stuff in the first commit, I ended up deciding to pr it separately once this gets in

**Comment by thgvr** [comment]
Jesus christ how horrifying

**Comment by thgvr** [comment]
Test merged in round(s) `1772, 1773, 1774` no noticeable issues or any reported by players

**Review by MarkSuckerberg — APPROVED** [review]
im not reviewing this broski

**Comment by goober3** [comment]
> im not reviewing this broski

i do not have the means to ship something in the github channel. good thing github has a ship react as well

**Comment by Sun-Soaked** [comment]
huh???

**Comment by tmtmtl30** [comment]
signing off on this. you have suffered enough

**Pull request merged**
