### PR TITLE
Rock Ruin: N+S Mining Installation

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
<details><summary>Pictures</summary>
<p>

dreamseeker_xEj59EPTs5
dreamseeker_auitVwi8CV
dreamseeker_scQzFBzfAx
StrongDMM-2024-10-11 15 15 44
StrongDMM-2024-10-11 15 15 45

</p>
</details> 

Adds a new ruin to the rockplanet pool. The N+S Mining Base is a small mining installation that had been built to extract minerals - and then was promptly raided by the Ramzi Clique (ramzi guys are somewhat waiting on #3462. I consider them placeholder right now). The ruin contains a small amount of weaponry, some fluff, and a refinery for your lovely ore mining efforts.

The main gimmick is based around cleaning the base up, getting it somewhat functional, and using the drill to extract ore from the comically good ore veins.  There are platforms with turrets deployed around them (as well as sandbags) to form a defensible position, but unless you can get into the refinery, it'll be somewhat annoying to actually use.

## Why It's Good For The Game
It's gimmicky content!!

## Changelog

:cl:
add: N+S has reported losing contact with one of their rockplanet based mining installations
/:cl:

### CODE REVIEW

**Review by Gristlebee — CHANGES_REQUESTED** [review]
- The holofields under the blastdoors of the refinery building are not anchored and won't work. Use the roundstart subtype.
image
- This blastdoor here is linked to the blastdoor switch at the top of the side of the refinery
image
image
- These conveyers are linked to the conveyer switch outside rather than the interior one switch. Is that intentional?
image
image
- The turrets fire on everyone and the turret control panels do not control the turrets. I'm wondering if this is intentional because the PR body implied these were supposed to help you with the drill. They also don't fire on heads of staff if this is an intended threat.
image
- The decal in the cafeteria here covers the white siding here. 
image
- In the sec office the red line here supposed to curve off into the wall? You had it go directly to the door on the other end. 
image
image



- The ruin could use more enemies and threats for the level of loot. Hades rifles are some of the stronger energy guns in the game right now. The dorms, outdoor walkways and the security building in particular could use some more enemies.

**Comment by Erikafox** [comment]
>     * The ruin could use more enemies and threats for the level of loot. Hades rifles are some of the stronger energy guns in the game right now. The dorms, outdoor walkways and the security building in particular could use some more enemies.

Yeah, I'm waiting on #3462 for that

**Review by Gristlebee — APPROVED** [review]

**Review by Gristlebee — CHANGES_REQUESTED** [review]
Some feedback after testing on live:
---
- Some of the platforms overlay weirdly when there's stuff on the same tiles. 
image
image

- The heater isnt properly linked to distro
image

- The outside hades on the walkway is pretty close to the other one  in the sec office, and relatively easy to grab. Swap it out for a different weapon, or move it into another one of the buildings. Maybe the dorms or the manager's office as a suggestion since they're lacking in things to grab.

**Comment by Erikafox** [comment]
yeag. aware of the overlays. one of the hades should be removed - but if you'd like i can put an energy weapon in the manager's office. 
will fix heater eventually

**Comment by Gristlebee** [comment]
> yeag. aware of the overlays. one of the hades should be removed - but if you'd like i can put an energy weapon in the manager's office. will fix heater eventually

Sounds good to me.

**Comment by Gristlebee** [comment]
Changes look good. 

Move the Hades inside the building, and take one of the eguns inside and put it under the miner corpse instead. It's a major loot item and shouldn't be outside I feel.

image


Once that's done, I'll see about getting this merged.

**Review by Gristlebee — APPROVED** [review]

**Comment by Gristlebee** [comment]
aw dangit

**Pull request merged**
