### PR TITLE
Malta-Class Pirate Mech Carrier!

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request

This pull request adds the Malta-Class Pirate Mech-Carrier and its subship.
The Malta-Class is a decently sized cargo freighter, originally crewed by some independent traders. That is, until some pirates hijacked the ship, and killed the previous crew. It now travels the galaxy, using the old transport pod as a boarding vessel.

This ship isn't currently in a good state. It's heavily lacking in decent medical equipment, it's power supply is low, it doesn't have much in the way of weaponry, it's incredibly slow, and the ship is generally worse for wear. However, for all these shortcomings it has two things that it heavily relies on. The Dark gygax, nicknamed "Vulcan", and it's Sub-shuttle.

## Why It's Good For The Game
we currently only have a single Non-faction pirate ship(not counting the libertita) My goal is to add more pirate ships for admins to play around with! (more coming SOON:TM:)

## Changelog

:cl:
add: Adds the Malta-Class Pirate Mech-Carrier
add: Adds the Malta-Class subshuttle
/:cl:

### CODE REVIEW

**Comment by spockye** [comment]
woops, forgot to name it

**Review by Latentish — DISMISSED** [review]
Needs tags and a description.

**Comment by Addust** [comment]
boobs as the number

you have my seal of approval

**Comment by spockye** [comment]
fixed, and ready for review

**Pull request closed without merging**
