### PR TITLE
Modernizes the Komodo

### LINKED ISSUE #2348: [BUG] The Entirety of the Komodo's Bar
## Testmerges:
[#2213: '(Re) Adds meteor shields' by Bjarl at commit 951e17bb35](https://github.com/Shiptest-SS13/Shiptest/pull/2213)
[#2256: 'Revamps wasteplanet_unhonorable' by Dethstorm at commit cfe47f7351](https://github.com/Shiptest-SS13/Shiptest/pull/2256)
[#2262: 'Cepheus nerfs' by Bjarl at commit 75a4f97d5a](https://github.com/Shiptest-SS13/Shiptest/pull/2262)
[#2272: 'Buildmode & Supply Pod Ports' by thgvr at commit 419326ca61](https://github.com/Shiptest-SS13/Shiptest/pull/2272)
[#2274: 'Anti-Radiation Foam' by Bjarl at commit cdd4dbf553](https://github.com/Shiptest-SS13/Shiptest/pull/2274)
[#2307: 'Adds a voice log to the wideband' by BarteG44 at commit 780707694c](https://github.com/Shiptest-SS13/Shiptest/pull/2307)
[#2316: 'Better metal rod throwing feedback' by retlaw34 at commit c0b1db6bd3](https://github.com/Shiptest-SS13/Shiptest/pull/2316)
[#2321: 'The CentCom-ening: Shiptest Edition' by meemofcourse at commit 33f3edd3be](https://github.com/Shiptest-SS13/Shiptest/pull/2321)
[#1670: 'Heron- Class!' by spockye at commit 37fa1db956](https://github.com/Shiptest-SS13/Shiptest/pull/1670)
[#2250: 'outpost tweaks & fixes: Vengeance ' by goober3 at commit e12ad21ff4](https://github.com/Shiptest-SS13/Shiptest/pull/2250)
[#2345: 'disable ion storms' by thgvr at commit 80534058a8](https://github.com/Shiptest-SS13/Shiptest/pull/2345)

## Reproduction:

When moving the Booze-O-Mat, the impassible hitbox places itself above the actual sprite, while the sprite itself preserves the ability to be interacted with a tile below it. 
Vendor

The two drink dispensers in the bar do not allow themselves to have their maintenance panel opened, nor unbolted with a wrench.
Dispenser

### PR DESCRIPTION
**Pull request by goober3**
## To-do

- [x] Rotate the Komodo
- [x] Armory Nerf
- [x] Medical Nerf 

## About The Pull Request
This PR:

- Fixes various issues with stacked and floating wallmounts on the Komodo.
- Adds a refueling system for the plasma and air tanks.
- Nerfs the power generators.
- Removes the ORM.
- Moves light switches to more convenient locations.
- Removes the NanoMed and re-organises medical slightly.
- Removes the Bulldog, SRM pistol, Syndicate Derringer, and Infiltrator Rifle.
- Adds a Stechkin and 357. Revolver for the Sergeant and Captain, respectively.
- Removes the Security RnD kit.
- Trims the Bartender's locker slightly, including the shotgun, which they had for some reason. 
- Adds a Peacekeeping locker to the armory.
- Removes the engineering vendor.
- Gets a little silly with it.

## Screenshots
666675ed82834ce45b843cf92cdcbe93
image
image

## Changelog

🆑
tweak: The Komodo has been tweaked, including some nerfs and wallmount fixes.
/🆑

### CODE REVIEW

**Comment by goober3** [comment]
oh, look. merge conflicts. i'll fix this tomorrow.

**Comment by thgvr** [comment]
wawa

**Review by Latentish — APPROVED** [review]
Tested this on live, don't see any immediate issues with it. The Komodo is still in this awkward place of being our only Hardsliner ship without proper hardliner representation. Which is to say we need a new hardliner ship. So whenever that happens this will need another pass over. But for not this is good.

**Comment by Latentish** [comment]
Waiting for some more changes before a merge as requested.

**Comment by Latentish** [comment]
Mergathons.

**Pull request merged**
