### PR TITLE
515 Support

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Regexes used:
```
 \.proc/(\w+)
 PROC_REF($1)
 
 ([\w/]+?)/?\.proc/(\w+)
 TYPE_PROC_REF($1, $2)

,\.proc/(\w+)
, PROC_REF($1)

,([\w/]+?)/?\.proc/(\w+)
, TYPE_PROC_REF($1, $2)
```
Taken from yogstation13/Yogstation#18669

## Why It's Good For The Game
We gotta update eventually

## Changelog

:cl:
code: 515 is now supported.
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
thats a lot of files

**Comment by MarkSuckerberg** [comment]
just a spoonful

**Comment by meemofcourse** [comment]
what did op mean by this

**Comment by Anderson-Cooper** [comment]
i have nothing else to do with my day so i will watch the github checks until it's successful 

i believe in you mark

**Comment by Anderson-Cooper** [comment]
i have a good feeling about this one

**Comment by Anderson-Cooper** [comment]
> i have a good feeling about this one

:(

**Pull request merged**
