### PR TITLE
Remaps the Kansatsu-class Scout Courier.

### PR DESCRIPTION
**Pull request by Sadhorizon**
## About The Pull Request
**THE SHIP IS NO LONGER SPAWNABLE FREELY**

**TODO:**
- [x] floors :D
- [x] ship desc
- [x] more missions
- [x] make command bed room not suck
- [x] give IO a privacy switch or whatever
- [x] 22 cargo desc
- [x] gut the disks

Biggest changes:
- **The Kansatsu now gets mission holodisks. Look at Ranger and LP missions to see what I mean.** The idea behind those is that they are gimmicky objectives based around spy stuff because that's cool. Intel gathering and minor theft. Don't want them to be a license to antag either because that's dumb. **I AM IN NEED OF MORE IDEAS. PLEASE GIMME.** 
- It's no longer a 1 tile hell.
- You generally get more gear now.
- The ship is now more flavorful.
- There are now security cameras in every room. Yes, bathroom gets one too.

Thank you @Bjarl for an updated ship description <3

<details><summary>Screenshots:</summary>
<p>

scrnshot1

StrongDMM-2024-09-17 10 39 23

StrongDMM-2024-09-22 10 41 58

</p>
</details> 

## Why It's Good For The Game
Kansatsu definitely needs a refresh.
Maptainers wanted it to be an aspawn.
Also I think the missions are going to be a great addition. Some pre-made gimmicks you can do.

## Changelog

:cl:
tweak: Kansatsu-class Scout Courier has been remapped.
del: Kansatsu-class is now aspawn-only.
del: Removes all the misc mining gear from the Field Agent outfit.
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
Oh, God, you made it a scalene triangle. I’m sorry I just can’t get over how far off-center the nose of this thing is

**Review by Apogee-dev — CHANGES_REQUESTED** [review]
Alright, review time. A lot of this is based on input from Erika, the ship's original mapper, mixed with my own feedback. I didn't include anything I disagree with or feel is out of scope for this review (I'll leave any code-related stuff for later and come back to the lore after the map itself is straightened out). It's a long one, so buckle up.

1. Symmetry. I know the Kansatsu was slightly asymmetric to begin with, but this remap worsens the issue significantly. At least try a bit to get the nose close to the center and not the weird scalene triangle it currently is. With the way the hull is laid out this shouldn't be too hard, you can make it a bit wider in the dorms/bathroom segment to give yourself a little space and shift the bridge and nose back toward the centerline that way.

2. The nose. I'd lengthen the nose by 1 tile and add another table for some more space (maybe make the rearmost windows walls for a little variety and better shape). Add an intercom, a recorder, and a clipboard; make it more of a functional observation post than the current chair-and-binoculars setup. Also replace those curtains with shutters the captain can drop in case the nose gets popped open. It's mostly glass, so that's a valid concern.
Also, remove the rolling table, that thing causes serious bugs and frankly we should just remove it from the code.

3. The bridge and offices. Since you removed the stechkin wall safe, cull it from the code- the item is now completely unused. The bridge's item layout in general is pretty bland, as is the floor. Work in some blood-red floor decals and patterns to spice that up a bit, and add a little more clutter. More tables and more stuff on said tables- it should feel more lived-in than this. Give one of the workstations some wall buttons to mess with for the various controls on the ship. Maybe move the secret documents to a floor or wall safe instead of the plain old filing cabinet (a safe like this would also be a good place for any more interesting items you might want to give them, such as a sleepy pen). Finally the captain's bed being kind of awkwardly shoved in the corner of the bridge, to be blunt, sucks. Either remove it entirely and put him in the normal dorms or find a way to work in a separate room (or at least a space separated from the bridge by windows or curtains), but especially on a bridge this tiny adding the bed like that looks and feels like an afterthought in the worst possible way.

4. Crew quarters. The bathroom is pretty decent, but it could use a button to bolt the door as long as it's a single-occupancy bathroom. The dorms themselves are insufficient. For a ship this size, you need at least two beds. Evening out the ship's symmetry _should_ give you some extra space to work with in this area, so use that for more bed space and/or a captain's cabin, even if it's just a 1 tile nook coming off of the bridge.

5. Hallway. Nix the viewscreen in the hallway; It's not actually necessary (especially on a ship this small) and it's in an awkward spot that will just lead to people standing around in the middle of the hall and getting in the way. I don't know who got the idea in their head that ship viewscreens are a necessity now, but they aren't. Vary your potted plants a bit, you used the same icon for every single one on the ship and it's pretty boring; if you generate icons on the potted plant object you should get a bunch to choose from (or just use the random ones).

6. Cargo layout and decor. Nix the windows from cargo into the hallway- that's the kind of open design that doesn't really make sense on a ship as cramped and supposedly secure as this. The decal and flooring work in cargo is pretty bland- you really could use some kind of greebling underneath your hallway doors, either with decals or a different floor texture (consider one of the tech floors for this, or caution stripes). Move those STAND CLEAR decals out from under the doors- you have a billion of them next to each other which is both visually noisy, hard to read, and obscured by the blast doors . Put them in front of the doors, on the white tiles, where the red will be easier to read anyway, and only use like two of them. The cargo floor in general is also pretty bland and could use some more texture and decal work.

7. Cargo contents. Put simply a lot of this is overgeared or in the wrong place. Holsters should be in the armory, to be distributed along with weapons. Every member of the crew shouldn't be able to grab one at their leisure. Medicine and mining gear are both excessive; Ditch those stimpaks and maybe just give them a bottle of charcoal pills or something instead of a full tox kit. This is a spy ship, not an actual combat ship, it starts off with a bunch of interesting and potent gear anyway, and it doesn't even have a medic slot; medicine is one of those points where it really ought to come up short. As for the mining gear, remove pretty much all of it. The field agents are only miners on technicality, because secoff slots are for agents that actually focus on fighting (if cybersun ever GETS those)- throw some normal pickaxes in there for if they _do_ need to dig, but if they're doing serious excavation for some reason they should have to buy gear for it.

8. Mess hall. The glass table's a bit too fancy for a ship in this style (and it can shatter at the worst possible times). Just use a normal one. The floors are bland again, like on most of the ship. Try some different textures, especially on the north wall under the counters and other machines, and/or mix in some decals. Blood red wouldn't hurt. Replace the full-size fridge with a wall fridge over an empty counter; It helps sell the "space-efficient" style of a ship like this much better and will work just as well. Kill the cleanbots, pretty much no ship has them right now and the kansatsu isn't really fancy enough for those. This ship isn't so big or so likely to generate a mess that those guys would really be necessary (I could see it on a Li Tieguai, but this?)- just make the junior agent clean up.

9. Armory. I'll be real, this thing looks like it was ripped right out of a Gorlex ship. One way to fix that: Give it a front desk. Toss in a filing cabinet to keep records, put a desk+windoor under one shutter with a chair behind it and an airlock underneath the other one. Now you can have someone in the armory issuing and tracking equipment instead of somebody opening the shutters and having a free-for all. Be sure to include a button for the shutters inside the armory. Use those fancy new gun cases for the Stechkins, it'll help with the visual noise. Consider using detective cameras instead of normal ones for better picture capacity, and maybe add some extra gimmicks like those pocket protector spy cameras- now the whole thing's a lot more interesting and opens up some room for other gimmicks.

10. Engineering. Looks _way_ too clean, even for Cybersun, and even taking into account the fact that it's a throughway to the rear airlock. Even when they're working for Cybersun, engineers are gonna be engineers, and their workspace is always going to be a little rougher and messier than the rest of the ship. The double doors are just too open and welcoming for this kind of thing imo. Make it a single door, and the same goes for the airlock- even though it's a 2x2 airlock, I wouldn't use double-wide doors, particularly for a ship this small. It won't kill your away team with its grand total of 2-3 players to exit single file, and you can use the "dead space" caused by switching one set of airlocks with walls to add an oxygen tank dispenser or replace that emergency closet with an SSU holding an emergency suit and tank. Roughen up those floor tiles- something a little more textured than that clean white. Use some tech tiles, maybe even revert to plain old open plating on the area where you currently have dark tiles. Try using more racks and normal tables instead of those kitchen tables- they're pretty out of place back here. Also replace that gas valve with a pump facing northwards, because at the moment it'll just flood the entire ship's waste pipes.

**Review by Apogee-dev — APPROVED** [review]

**Comment by lectronyx** [comment]
> Oh, God, you made it a scalene triangle. I’m sorry I just can’t get over how far off-center the nose of this thing is

Ah, the scalene triangle.

**Comment by Sadhorizon** [comment]
Would love it if some lore person reviewed the holodisks. Want them to be in character/lore accurate.

**Comment by Zevotech** [comment]
Bathroom door is named kansatsu_bathroom ingame.

**Comment by Sadhorizon** [comment]
LOL

**Comment by Ratvarr** [comment]
The bathroom lightswitch... Connects to the rest of the main hall. AND THE BATHROOM DOESENT EVEN HAVE A LIGHT **TO** TURN ON

**Comment by Sadhorizon** [comment]
> AND THE BATHROOM DOESENT EVEN HAVE A LIGHT **TO** TURN ON

It does actually. I'm betting it just broke on spawning in and nobody noticed.

Also, this room is So Damn Tiny, I am _not_ fitting an APC here, so it's staying as the same area I'm afraid.

**Comment by thgvr** [comment]
@shiptest-ss13/maptainers Ancient pr, please decide if it's being merged or not

**Comment by Latentish** [comment]
I'm sorry but I just do not think that we will be accepting this remap. The Kansatsu struggles to have a place in the game, and has a low chance of actually being used by admins. But the primary issue is the shape and layout of the ship, and I don't feel that it is fair of me to say that you'd need to fully redo the ship from scratch on something we're not likely to accept.
I will speak with some of the other maptainers and have a decision for you soon. Apologies for the long wait.

**Comment by Latentish** [comment]
Apologies, but we will not be accepting this PR.

**Pull request closed without merging**
