### PR TITLE
Valor Remap, Minor Inteq Code Tweaks

### PR DESCRIPTION
**Pull request by meemofcourse**
## About The Pull Request
imagen
imagen

* Remaps certain parts of the Valor. The Haste has not been touched apart from a single handrail.
* The Valor now has a Shuttle Pilot, and a Shuttle Corpsman. The Shuttle Pilot gets an office and an outfit.
* The Vanguard basetype was changed to be consistent with the other outfits (e.g. empty subtype instead of being empty by default)

## Why It's Good For The Game
* there was complaints that the valor sucked
* born to map dmm is a fuck 地图 strongdmm 2019 i am maptainer 410,757,864,350 mapping sins

## Changelog

:cl:
balance: Remapped the Valor, with two extra jobs (Shuttle Corpsman, Shuttle Pilot).
code: The Vanguard base outfit starts with gear.
/:cl:

### CODE REVIEW

**Review by Zevotech — APPROVED** [review]
looks good and normal to me

**Comment by Slim-Pickems** [comment]
Shuttle Corpsman ID does not differentiate from regular corpsman. Still says just Corpsman. Unsure if this is intentional or is know and to be fixed later.

**Comment by meemofcourse** [comment]
intentional

**Comment by firebudgy** [comment]
image
Once you see it you can't unsee it. (Duplicated box corner decal)

**Pull request merged**
