### PR TITLE
Adds Moth Hair

### LINKED ISSUE #885: [FEATURE] moth hair
### Additional Info:

It wouldn't be that hard to give moths the ability to have hair, the main thing stopping it being added ATM is that it'd be preferable to force the hair's color to be in the color of the moth's selected fluff, so someone would need to figure out some fresh and fancy way of tying specific color codes to specific fluffs and then having the moth's hair color set to that

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
As title says, lets moths have hair

Mothhair_1
Mothhair_2
Mothhair_3
Mothhair_4
Mothhair_5
Mothhair_6

Random Gen hair looks  a bit weird sometimes but most random gens look a bit scuffed

## Why It's Good For The Game
 closes #885 , more customisation or whatever, I think this makes moths the most customisable race 

## Changelog
:cl:
add: Moth Hair
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
I don't THINK that this will conflict with kapulimbs but to me that's dark magic beyond my comprehension

**Comment by Vexylius** [comment]
It does not make sense, but looks cool
¯\_(ツ)_/¯

**Review by rye-rice — CHANGES_REQUESTED** [review]
Does moth fluff and hair use different colors?

**Comment by ToasterBan** [comment]
>It does not make sense, but looks cool ¯_(ツ)_/¯

something something human mutants something something ask Tori 

> Does moth fluff and hair use different colors?

no,if you want to use fluff colours you can manually choose the colour to match your fluff

**Comment by tiramisuapimancer** [comment]
as moth lorema owner it makes complete sense actually

**Comment by TallDeekus** [comment]
Based Maintainer Moment

**Pull request merged**
