### PR TITLE
Remaps the Colossus's armory

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

colossus_2

Completely redesigns the Colossus's starboard side, adds a Master-at-Arms role to the Colossus, and adds an IRMG Comms Relay to the bridge.

## Why It's Good For The Game

Colossus needed a little love and new IRMG assets need a chance to shine.

## Changelog

:cl:
add: Added a Master-at-Arms to the Colossus
tweak: Redesigned the Colossus's armory
/:cl:

### CODE REVIEW

**Comment by Imaginos16** [comment]
IMRG bros…. We stay winning…..

**Review by Erikafox — APPROVED** [review]

**Review by Latentish — DISMISSED** [review]
image
These two do not open to the master at arms.

Otherwise this looks fine.

**Comment by Martinpachu** [comment]
ths is so fucking real you wouldnt imagene

**Comment by Latentish** [comment]
We'll tm again and if it's good we marge

**Pull request merged**
