### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by CenkTheRaptor**
Signed-off-by: CenkTheRaptor <81775933+CenkTheRaptor@users.noreply.github.com>

## About The Pull Request

Makes the presence of crystal goliaths and turrets a bit more obvious, to lessen (in my opinion) the punishment for exploring the ruin.

image
image

(screenshots may not be as they appear ingame, taken from StrongDMM)

- [X] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

it makes the ruin less lethal for the loot that it gives.

## Changelog

:cl:
add: Added elements to the jungle paradise ruin that make it less lethal for the quality of loot it gives.
:cl:

### CODE REVIEW

**Comment by Ms-Mee** [comment]
Add files via upload

**Comment by Latentish** [comment]
Next time please make a proper commit with a title and description. "Added files via upload" tells us little in the way of what you've done.

**Comment by rye-rice** [comment]
Add files via upload

in more serious terms, crystal legions need to be rebalanced

**Comment by CenkTheRaptor** [comment]
uh woops i didnt notice i added it to the root folder

**Pull request merged**
