### PR TITLE
Nemo-class Spacelife Research Vessel

### PR DESCRIPTION
**Pull request by TypeVar**
## About The Pull Request
Adds a new fauna-hunting focused ship that includes a proper, functional library. It is also powered by a TEG.  It is meant to be loosely based on Jules Verne's Nautilus.

image

## Why It's Good For The Game
There are too few ships with a proper curator job slot, as well as a library. I have not seen a ship that starts with a TEG, and think it would be a unique addition and open up project opportunities for bored engineers and atmos techs. Medbay starts with a single bluespace body bag in order to make bringing bodies back easier for dissection, as this is a fauna research ship. It also comes with spearguns just because it fits too much with the submarine look. 

## Changelog
:cl:
add: Nemo-class Spacelife research Vessel
/:cl:

### CODE REVIEW

**Comment by TallDeekus** [comment]
Ah yes, the Jakobs Hunting Ship (sorry been playing too much BL3)

**Comment by ZephyrTFA** [comment]
The map is still not TGM formatted. If you are using SDMM there is a check box you need to select to save it in TGM format. If you are using DreamMaker you really shouldn't be

**Comment by TypeVar** [comment]
> The map is still not TGM formatted. If you are using SDMM there is a check box you need to select to save it in TGM format. If you are using DreamMaker you really shouldn't be

I have it saved as a TGM, then I also used map merger afterwards. Maybe I'm not doing the VSC part of it right? I have basically no experience with it and I think I may be doing something wrong there

**Comment by SakuraOran** [comment]
more of a suggestion than a bug, but the plasma tank RIGHT next to the window isnt a good idea. ive had a hostile mob bust through the wall and breach the plasma tank immediately after landing on a planet, plasma flooding the entire ship.

**Pull request merged**
