### PR TITLE
fixes unit tests

### PR DESCRIPTION
**Pull request by tmtmtl30**
## About The Pull Request

Currently ships with subshuttles fail unit tests. This wasn't perfectly clear before, because only ships which were enabled for roundstart spawn were tested by unit tests. This PR fixes both.

Make sure the unit tests on this one actually succeed, since I need to ensure the newly-tested ships don't start failing.

## Why It's Good For The Game

better tests are good + makes it OK to merge subshuttle PRs

## Changelog

:cl:
fix: Ship-spawn unit tests have been fixed and expanded.
/:cl:

### CODE REVIEW

**Review by Latentish — APPROVED** [review]
I'd like to tm this to make sure shit doesn't break down, but it looks good. You even went in and fixed the catalogue entries.
I'd prefer if you added a picture of the superpill to your pr, as minor as that is, because you did perform open heart surgery on it live in call so it's enough of a change to show visually.

**Review by MarkSuckerberg — APPROVED** [review]
seems good

**Comment by tmtmtl30** [comment]
sure, here's the new superpill:
image
instead of jumpstarting it with kisses, you pull the lever to push the pills into the supermatter. the emitter has some T4 parts to keep its energy output up (though i'd need to modify it further for it to be self-sustaining). the vodka is there for emotional support

**Comment by MarkSuckerberg** [comment]
oh my god

**Comment by meemofcourse** [comment]
what the fuck

**Pull request merged**
