### PR TITLE
Adds the Solarian Marine Society mascot as a plushie

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
see title
Sprites by INFRARED_BARON.

## Why It's Good For The Game
lore representation

## Changelog

:cl:
add: The Solarian Marine Society has begun mass production of a cute, marketable plushie of their mascot. May be favored by vampires. Sprites by INFRARED_BARON.
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
image

**Comment by Zevotech** [comment]
github how dare you deny me my blahaj spin

**Review by rye-rice — APPROVED** [review]

**Comment by Latentish** [comment]
Could you please add a picture of the plushie?

**Review by Imaginos16 — APPROVED** [review]
The vampires from transylvania will love this one

**Review by MarkSuckerberg — APPROVED** [review]
YES

**Pull request merged**
