### PR TITLE
Adds the "Ethereal dance grenade"

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Port of https://github.com/BeeStation/BeeStation-Hornet/pull/1127

## Why It's Good For The Game

More options for ship defence. Why would anyone use this for defence is beyond anyone
For @triplezeta 

## Changelog
:cl:  PowerfulBacon
add: Ethereal dance grenade. If you find a uplink, you can buy it through there.
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
should just be an innate power of ethereals, absolutely nothing can go wrong with that

**Comment by Valorium-RB** [comment]
Does it play Carameldansen

**Comment by Kapu1178** [comment]
Credit creator in changelog. Just good practice.

**Comment by francinum** [comment]
And just to be sure, you've tested to make sure this doesn't infinite loop?

**Comment by rye-rice** [comment]
It didn't during testing, is it a known bee bug?

**Comment by francinum** [comment]
The whole way this thing is coded is dangerous and for a time on bee they caused an infinite recursive loop.

**Comment by rye-rice** [comment]
@MarkSuckerberg

**Pull request merged**
