### PR TITLE
VSCode DMI editor!!!

### PR DESCRIPTION
**Pull request by Vexylius**
## About The Pull Request

"Ports" https://github.com/tgstation/tgstation/pull/66834

You can get it here:
https://marketplace.visualstudio.com/items?itemName=AnturK.dmi-editor

## Why It's Good For The Game
It does not affect the game, but it (hopefully) will positively affect the people who make it

### CODE REVIEW

**Review by rye-rice — APPROVED** [review]

**Review by triplezeta — APPROVED** [review]

**Comment by Sylphily** [comment]
Merge now or unbased

**Comment by Vexylius** [comment]
I think I'll need some more reviews 🤔

**Review by MarkSuckerberg — APPROVED** [review]
LET'S FUCKING GOOOOOOOOOOOOOOOOOOOOO

**Review by Zevotech — APPROVED** [review]

**Comment by Zevotech** [comment]
MORE

**Comment by ZephyrTFA** [comment]
oh no I've fallen on the merge button before the 24hr period elapsed.

**Pull request merged**
