### PR TITLE
New ruin any percent

### PR DESCRIPTION
**Pull request by Latentish**
## About The Pull Request
This adds two more space ruins on the behalf of Any%.
These would be Lab4071, which is a player spawn chemlab.
image

And Syndicate Battle Sphere, a syndicate uh, circle ship.
image

## Why It's Good For The Game
More Ruins equals more uh. More Ruins.

## Changelog
:cl:phoaly and Any%
add: Added Lab 4071 space ruin.
add: Added Syndicate Battle Sphere space ruin.
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
There seems to be some varedit with a missing quotation somewhere in the lab4071 map. I also need to go over the maps and hunt down wires underneath walls, as I noticed a good handful of that while fixing these up.

**Comment by Latentish** [comment]
Alright that should fix all the problems with these two maps. Given that the remaining checks finish. When they finish passing I'll mark this ready.

**Comment by Latentish** [comment]
Wow ok there's more problems. I'll look into that later.

**Comment by Valorium-RB** [comment]
I like the NT listening post. It's a nice touch and inversion of the normal trope. My only concern is that the Lab map is...well. Player spawns are already MASSIVELY rare. Very few people even "observer main" such that they'd grab the roles as soon as they spawn (or at least before whichever ship that landed there raids it to high heaven, at which point you'd be very much disinclined from bothering considering your equipment has been gutted like a fish). So, if no player takes the role, then the Lab is basically a free full ghettochem setup, armor, syringe guns and combat knives, both types of drink dispenser, an M1911 with spare mags, a jukebox, all vending machine types, multiple generators, an autolathe...you get the picture. Hell, if you do contend with the few enemies there are, you can add a full botany setup, a laser gun, a C4 and several medkits to that list as well. That's easily more loot than 95% of ruins right there, with half the defenses of most of its compatriots. Maybe sprinkling in some more simplemobs in the base itself that may have to be cleaned up? Something of that nature. Both are excellently mapped, and the Battle Sphere will be exquisite to explore and loot.

**Comment by Latentish** [comment]
While Any% is the mapper for this one, I will say that maybe adding forces outside with turrets like any other syndie base might be a good idea!

**Comment by zestybastard** [comment]
> I like the NT listening post. It's a nice touch and inversion of the normal trope. My only concern is that the Lab map is...well. Player spawns are already MASSIVELY rare. Very few people even "observer main" such that they'd grab the roles as soon as they spawn (or at least before whichever ship that landed there raids it to high heaven, at which point you'd be very much disinclined from bothering considering your equipment has been gutted like a fish). So, if no player takes the role, then the Lab is basically a free full ghettochem setup, armor, syringe guns and combat knives, both types of drink dispenser, an M1911 with spare mags, a jukebox, all vending machine types, multiple generators, an autolathe...you get the picture. Hell, if you do contend with the few enemies there are, you can add a full botany setup, a laser gun, a C4 and several medkits to that list as well. That's easily more loot than 95% of ruins right there, with half the defenses of most of its compatriots. Maybe sprinkling in some more simplemobs in the base itself that may have to be cleaned up? Something of that nature. Both are excellently mapped, and the Battle Sphere will be exquisite to explore and loot.

as far as ruin loot goes the chem lab is on the lower end of the spectrum compared to like, zombie station or syndies vs. pirates. combat knives might be a bit strong but they're overtaken by a lot of mining weapons, and a blowgun isnt really good unless you commit to it. compared to the other ghostroles like ashwalker and syndicate lavaland base i think this might be the worst equipped ghostrole yet

**Comment by Ms-Mee** [comment]
> > I like the NT listening post. It's a nice touch and inversion of the normal trope. My only concern is that the Lab map is...well. Player spawns are already MASSIVELY rare. Very few people even "observer main" such that they'd grab the roles as soon as they spawn (or at least before whichever ship that landed there raids it to high heaven, at which point you'd be very much disinclined from bothering considering your equipment has been gutted like a fish). So, if no player takes the role, then the Lab is basically a free full ghettochem setup, armor, syringe guns and combat knives, both types of drink dispenser, an M1911 with spare mags, a jukebox, all vending machine types, multiple generators, an autolathe...you get the picture. Hell, if you do contend with the few enemies there are, you can add a full botany setup, a laser gun, a C4 and several medkits to that list as well. That's easily more loot than 95% of ruins right there, with half the defenses of most of its compatriots. Maybe sprinkling in some more simplemobs in the base itself that may have to be cleaned up? Something of that nature. Both are excellently mapped, and the Battle Sphere will be exquisite to explore and loot.
> 
> as far as ruin loot goes the chem lab is on the lower end of the spectrum compared to like, zombie station or syndies vs. pirates. combat knives might be a bit strong but they're overtaken by a lot of mining weapons, and a blowgun isnt really good unless you commit to it. compared to the other ghostroles like ashwalker and syndicate lavaland base i think this might be the worst equipped ghostrole yet
> 

Beach bums :Idiot:

**Comment by Latentish** [comment]
Bring on the reviews.

**Comment by Latentish** [comment]
Whoever reviews this, please make a note on its balance. As that seems to be the more contended point here.

**Comment by Latentish** [comment]
I'd like to request a review.

**Comment by Latentish** [comment]
Can this please get a review? It's gone stale now.

**Comment by MarkSuckerberg** [comment]
Getting this TM'd if I can, extremely sorry about the wait.

**Comment by Fikou** [comment]
nobody had any objections, assuming this is fine

**Pull request merged**
