### PR TITLE
Removes Miasma

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Removes the gas Miasma as well as any methods to generate it or anything that relys on it. Corpses, gibs and corpseflowers no longer create miasma at all, which is an acknowledged issue that can be dealt with later by more creative people in a feature that is much better implemented.

## Why It's Good For The Game
Because I said so -ZephyrTFA

## Changelog
:cl:
del: Miasma, the stinky corpse gas
del: rot.dm, and corpses/gibs creating miasma
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
OH MY GOD IT PASSED CHECKS FIRST TRY

**Comment by Sylphily** [comment]
an finally i don't have to deal with bodys in the airtanks for the 1000000000000000th time

**Comment by Zevotech** [comment]
actually thats a different PR, this just removes the fart gas

**Comment by Sylphily** [comment]
_no reason to deal with them if they can deal no harm_

**Comment by triplezeta** [comment]
havent noticed issues with this PR so far. May be good to merge?

**Review by MarkSuckerberg — APPROVED** [review]
go to hell

**Pull request merged**
