### PR TITLE
Do Not Abuse Lizards (Ruin Removal)

### PR DESCRIPTION
**Pull request by Cheshify**
## About The Pull Request

Removes the n*zi lizard murder map

## Why It's Good For The Game

cringe map

## Changelog
:cl:
del: Removed gasthelizards.dmm
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
I am not biased in this in any form, how dare you insinuate this.

**Comment by 1glitchycent** [comment]
Orwellian.

**Comment by super12pl** [comment]
This reminds me of a book "1984"

**Comment by TallDeekus** [comment]
Honestly, I'd rather it get replaced with something cool like an evil scientist lab or a research shuttle that is derelict, something that could give a small boost to research for the ship that finds it.

**Comment by Cheshify** [comment]
> Honestly, I'd rather it get replaced with something cool like an evil scientist lab or a research shuttle that is derelict, something that could give a small boost to research for the ship that finds it.

When You Map It >:)

Jokes aside, GTL is a relic of old /tg/, and I have another PR adding a new cool science based ruin

**Comment by TallDeekus** [comment]
> > Honestly, I'd rather it get replaced with something cool like an evil scientist lab or a research shuttle that is derelict, something that could give a small boost to research for the ship that finds it.
> 
> When You Map It >:)
> 
> Jokes aside, GTL is a relic of old /tg/, and I have another PR adding a new cool science based ruin

Based, how do I double upvote.

**Pull request merged**
