### PR TITLE
Saloon rework

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
Expands whitesands_surface_camp_saloon to cover a 30x30 footprint and not be nearly as bad. The previous version had some really glaring design flaws, like holes in the wall for a bar. On a planet with a deadly atmosphere. Yeah. Also all the chairs faced the same direction. 

You can see how it looks. It's not great. 
Here's the new version

dreamseeker_ePSrp5zNFp
Ignore the patches of error, it's purple grass and doesn't display the icon in sdmm for some reason.

The major changes are:
Expanding the building's footprint out to 30x30
Moving the loot behind the building, but locking it behind a shovel of some sort (of which you can go through the ruin to get).
Improving the loot a LITTLE

- [x] The map loads although I still haven't managed to get it to load on the proper planet with the spawning verb 

## Why It's Good For The Game
The old version was kinda bad. Between the clown and mime masks out front. The small footprint, and the free guns (also out front). This solves those issues kinda while making it bigger.

## Changelog

:cl:
add: Camp_Saloon has been expanded, expect frontier luxuries if you find it!
/:cl:

### CODE REVIEW

**Comment by Valorium-RB** [comment]
Looks great! Tells a nice story, much stronger decor, all the enemies won't immediately die without player intervention, all awesome. Only bugbear for me is that the enemy count has been VASTLY increased without much corresponding increase in loot. The original ruin has five enemies, all but one of whom are melee-only, while the new version has 19(!) enemies, including the hilariously lethal Whitesand Soldier. Meanwhile, the loot pool is mostly the same between the two – a riot shotgun with shells, some money, bar dispensers, a musical instrument machine, two derringers if you snoop around a bit – with the only major additions being a lot more cigars and some minor engineering equipment. Nearly quadrupling the enemy count without changing the loot, as well as it being possible to aggro almost all of them in one room, isn't super advisable in my opinion. Maybe stick some novel personal items in the living quarters or something like that? Just to make it a little more worth the ammo.

**Comment by Erikafox** [comment]
I think increasing the loot a bit would be reasonable. I'll put some thought into what might go well with it aside from more guns

**Comment by Latentish** [comment]
Fix merge conflicts and I'll tm this.

**Comment by Erikafox** [comment]
This has been ready for a bit.

**Comment by Latentish** [comment]
MERGING NOWWWWW

**Pull request merged**
