### PR TITLE
(Nanotrasen) Prometheus-Class Plasma Tanker

### PR DESCRIPTION
**Pull request by BBBBAface**
## About The Pull Request

This PR adds a new Nanotrasen ship to the game, A plasma transport vessel with limited facilities but enough plasma to last a large settlement indefinitely.

image

Specs:
Limited to 2 per round
440Ton weight with 6 ion engines
Supports a crew of up to 7, but works best with 3 - 5 Power-management system 
Around 2,500,000 MOL of plasma gas
5,000cr starting cash
Stocked medbay
Extremely limited weaponry
Basic mining gear
Working Exterior / Engine / Bay shutters and holofans
"Robust" atmos setup
Outpost comms console

Pros: 
• You will never run out of plasma gas
• Defribulator and surgical tools
• A cell for troublesome patients
• Engineering protolathe
• Large bay doors and engineering area
• Easily customizable
• Only ship of its kind
• Slot machine!

Cons:
• NO R&D capabilities
• NO Projectile weapons and limited security gear in general (that's a cap gun)
• NO way of actually utilizing the plasma it has stored
• Only 3 hardsuits
• No launchpad or outpost trading console
• Slightly cramped design
• No insulated gloves; you're going to have to drink Rubbernecks

image

image

- [X] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

Currently, no ships are designed to trade gas, leaving the niche unfilled. This is the solution.

This ship would be a decent trading vessel, and because of the defibrillator, it could also make a good emergency response vessel, able to refuel ships and revive the crew. Lack of plasma engines or TEG means the plasma gas is useless on round start. Trading with other players is required due to the lack of research capabilities.

## Changelog

:cl:
Add: the completed ship 
Fixed: errors
Add: 1 fire extinguisher
Replaced: APC console with Computer Frame
Replaced: Roulette with Orion Trail
Rotated: Orion Trail
Add: Outpost Comms Console
Fix: docking port and size of map
Removed: Most of the sec gear (there are now extremely limited weapons on the ship)
Added: Recharger (there is nothing to recharge, this is for decoration)
Replaced: Floor in Engineering
Added: 1 Tile of length to the ship
Added: New posters and trim
Removed: grill under window spawned
Added: minor details
/:cl:

### CODE REVIEW

**Comment by Yellow-Mushroom** [comment]
I still believe it’s extreme amount of plasma combined with its purpose of being a plasma sales ship needs to be addressed. 

It has 2.52 million Mols of plasma (you said you cut it in half so potentially 1.26 million Mols of plasma)

If it’s still 2.52 million, you can fill 1346.4 canisters of plasma, it is 1.26 million, you can fill 673.18 canisters of plasma. I’d estimate the whole frontier goes through 5-15 canisters for a whole five hour round

I know that the plasma economy is still extremely broken due to other ships with TEG’s having upwards of 280,000 Mols (a 2x2 of plasma floors), I think ship should still be balanced for what makes sense in the game and it’s niche, versus waiting for someone (potentially me) to rebalance atmos substance distribution as a whole

**Comment by BBBBAface** [comment]
> I still believe it’s extreme amount of plasma combined with its purpose of being a plasma sales ship needs to be addressed.
> 
> It has 2.52 million Mols of plasma (you said you cut it in half so potentially 1.26 million Mols of plasma)
> 
> If it’s still 2.52 million, you can fill 1346.4 canisters of plasma, it is 1.26 million, you can fill 673.18 canisters of plasma. I’d estimate the whole frontier goes through 5-15 canisters for a whole five hour round
> 
> I know that the plasma economy is still extremely broken due to other ships with TEG’s having upwards of 280,000 Mols (a 2x2 of plasma floors), I think ship should still be balanced for what makes sense in the game and it’s niche, versus waiting for someone (potentially me) to rebalance atmos substance distribution as a whole

I did cut it in half, but a bug I encountered was the massive difference of 70,000 Mol in one tile and 0 Mol in the one next to it, was there were incredibly strong air currents being generated that somehow moved things around outside the tanks. It was reproducible, and since the plasma economy isn't really there yet I don't see this ship being that big of an issue. I can always reduce it in the future, if a big update related to plasma is released. If someone else agrees this is a big issue, I can always make one or two tanks simply spawn empty. Not having the ability to use any of this plasma is important to consider, too.

edit: i want to clarify I was putting engine airless floor next to the engine plasma floor, I wasn't doing any var editing or making new prefabs.

**Comment by BBBBAface** [comment]
I'll empty a tank or two if it's an issue, but gameplay-wise having way more plasma than the entire server uses in a round, or having 3x that amount, isn't too different. And the ship looks aesthetically better with 3 full tanks.

**Comment by TheNeoGamer42** [comment]
prometheus fuel tanker..........
so when can I paint it green and ram it into a fucking station because something something, tech bad

on an actual note, I doubt its really even a proper Thing but if there's a way to convert gas plasma into plasma sheets, you should add it to the ship and make it run off of plasma pacmans instead of uranium ones, but I see one of the main points is you can't even use the plasma gas. Maybe add fire extinguishers to the engineering sections since I see a few of them dotted around in the gambling(?) and laundry rooms, but none near the tanks and engineering, atleast when I looked, but I am also blind sometimes.
Also while neat, the remote APC control console MIGHT be a bit of a wacky overpowered thing if it works the way I think and you can turn off the entire other ship, which would make it an ODDLY decent vessel for messing with other ships if only for that in specific

**Comment by BBBBAface** [comment]
> prometheus fuel tanker.......... so when can I paint it green and ram it into a fucking station because something something, tech bad
> 
> on an actual note, I doubt its really even a proper Thing but if there's a way to convert gas plasma into plasma sheets, you should add it to the ship and make it run off of plasma pacmans instead of uranium ones, but I see one of the main points is you can't even use the plasma gas. Maybe add fire extinguishers to the engineering sections since I see a few of them dotted around in the gambling(?) and laundry rooms, but none near the tanks and engineering, atleast when I looked, but I am also blind sometimes. Also while neat, the remote APC control console MIGHT be a bit of a wacky overpowered thing if it works the way I think and you can turn off the entire other ship, which would make it an ODDLY decent vessel for messing with other ships if only for that in specific

You're right, the APC control console is for the entire Z level not just the ship you're on. I'm removing it because that's kinda op. I thought I checked that earlier, but I guess I missed it, my bad.

I removed the normal, plasma-consuming Pacman because I don't think the ship should use plasma at all, for lore reasons. As far as I know, there's no way to make gas into sheets aside from buying and selling.

There is a fire extinguisher in the engine room, but not the plasma pipe room. I went ahead and added one even though the 2 plasma technicians spawn holding fire extinguishers.

**Review by Latentish — CHANGES_REQUESTED** [review]
- This ship generally needs more detailing work.

- This flooring needs to be something that pipes and wires will show on top of.
image

- Don't leave pipes without ends like this.  A valve without something on one side is kinda bad practice. Make it lead to an injector or something.
image

- You have the space to make sure this isn't a shoilet.
image

- This wiring isn't good. This is terminal to terminal node to node, it's not good. Expand this area down.
image

- As a plasma tanker, you shouldn't have a vast majority of the gear here. A gun or two is basically necessary for almost any ship, but this is waaay overboard.
image

- This wideband should be on a table or wall.
image

- My biggest issue with this is the gameplay loop. They have all this plasma, but nothing to do with it. I get that this is a plasma tanker, but we have no real atmos economy, so there's not much for this ship to do.
image

**Comment by BBBBAface** [comment]
Serious question, what should I put at the end of the plasma tank pipes? injectors would be silly, that means it defaults to jetting all the plasma into space.

A big part of this ship is Roleplay, it's what it was primarily designed around tbh. Another thing is customizability for those who enjoy modifying their ships.

I know there's not much of a "plasma economy", but there have been several instances I've seen where someone who is capable of refilling someone's plasma tanks would've been extremely useful. I'll have this updated tomorrow.

**Comment by Latentish** [comment]
> Serious question, what should I put at the end of the plasma tank pipes? injectors would be silly, that means it defaults to jetting all the plasma into space.

Assumedly you'd put an injector on the other side of the valve for the disposals loop, and a canister port on the other side of the plasma valve.

**Comment by BBBBAface** [comment]
> > Serious question, what should I put at the end of the plasma tank pipes? injectors would be silly, that means it defaults to jetting all the plasma into space.
> 
> Assumedly you'd put an injector on the other side of the valve for the disposals loop, and a canister port on the other side of the plasma valve.

There are 2 plasma valves, one in and one out, so I'l just put canister ports on those. The disposals loop already has an injector on the end, directly above the 2 pipes that end with valves

**Review by Fikou — CHANGES_REQUESTED** [review]
your changelog is completely wrongly written, please inform yourself on how to write the changelog

**Comment by Latentish** [comment]
The maptainers voted that we do not want this ship. Apologies.

**Pull request closed without merging**
