### PR TITLE
Solarian DLC 2: A new job and new goodies!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
This PR adds a few new things for SolGov players to enjoy! First and foremost, a new job is now available:

- The Logistics Deck Officer (Quartermaster Analogue!)
image

This also means a few new outfits are added, including:
- The Solarian Overcoat (pictured above)
- The Solarian Flat Cap (pictured above)
- The Solarian Winter Coat (pictured below)

image

## Why It's Good For The Game
SolGov players gotta keep eatin' good...

## Changelog

:cl: PositiveEntropy
add: New SolGov outfits now exist, including a winter coat!
add: The Logistics Deck Officer is now a possible job for SolGov ships!
/:cl:

### CODE REVIEW

**Review by rye-rice — APPROVED** [review]
my... le paperwork faction... has more drip???

**Review by MarkSuckerberg — APPROVED** [review]
SO good

**Comment by Imaginos16** [comment]
selfmerging evil style

**Comment by thgvr** [comment]
wonder why it failed

**Comment by Imaginos16** [comment]
What the fuck

**Pull request merged**
