### PR TITLE
Removes a single "g" from shiptest.dme

### PR DESCRIPTION
**Pull request by SweptWasTaken**
## About The Pull Request

Git Blame -> https://github.com/shiptest-ss13/Shiptest/pull/170

## Why It's Good For The Game

A single g can change the course of history.

### CODE REVIEW

**Comment by AsciiSquid** [comment]
g

**Comment by ZephyrTFA** [comment]
😕

**Comment by theXDkidoflol** [comment]
game is basically ruined now

worst pr ever

**Comment by Ms-Mee** [comment]
SOUL SUCKER

**Pull request merged**
