### PR TITLE
Fixes rock sprites ingame [WHOOPS]

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Rocks were invisible in game due to a recently merged PR of mine. this is why we testmerge PRs! anyways this should fix them.

Adds flora and rock missing texture sprites to most flora files to prevent something like this from ever happening again.

## Why It's Good For The Game
invisible things that block movement bad yeah. i want to fix my mistakes.

## Changelog

:cl:
fix: Most rocks are now visible again
add: Most flora files now have missing texture sprites to make it easier to spot when something has gone wrong.
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
🥺

**Review by rye-rice — APPROVED** [review]
if this breaks

**Comment by Zevotech** [comment]
if it breaks its partially your fault bestie

**Comment by Zevotech** [comment]
but it shouldnt. right. right. right. right. right.

**Comment by rye-rice** [comment]
ill hold you to your word

**Pull request merged**
