### PR TITLE
Removes Split Personality

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
Removes split personality and associated code

## Why It's Good For The Game
It's not good for how we want the game to be.

## Changelog

:cl:
del: Split Personality brain trauma
/:cl:

### CODE REVIEW

**Comment by ritorizo** [comment]
image

**Comment by Latentish** [comment]
This doesn't appear naturally, and is only used by admins for events. I'd prefer it stayed in.

**Comment by Erikafox** [comment]
It occurs when you get enough brain damage. I made this pr because I saw it happen and had to unfuck someone's connected ckey.

**Comment by Latentish** [comment]
> It occurs when you get enough brain damage. I made this pr because I saw it happen and had to unfuck someone's connected ckey.

Could you make it not happen naturally then. It should be removing the code that connects it to brain damage.

**Comment by Erikafox** [comment]
I'll give that a shot, yeah

**Pull request closed without merging**
