### PR TITLE
Makes Elzouse update body with mutcolor at all and make the hair consistently update

### PR DESCRIPTION
**Pull request by KittyNoodle**
Signed-off-by: KittyNoodle <78111117+KittyNoodle@users.noreply.github.com>

## About The Pull Request

Apparently body update does not include hair, this was resulting in elzuose hair not updating when their mutcolor changes. 

## Why It's Good For The Game

Bug bad, Elzuose good.

## Changelog
:cl:
fix: Makes elzuose hair and body update in general.
/:cl:

### CODE REVIEW

**Comment by Sylphily** [comment]
problem
atm their body doesn't change color either

**Comment by KittyNoodle** [comment]
pain

**Comment by KittyNoodle** [comment]
well the hair is changing color correctly so it probably has something to do with the update icon refactor

**Comment by Sylphily** [comment]
Yea a lot of things been broken because of it kinda wish who ever did it thought about the edge cases

**Comment by KittyNoodle** [comment]
drafting this as its way more complicated then i thought it would be, and i am also working on another project right now

**Pull request closed without merging**
