### PR TITLE
Balaclava Snout Sprites + Elzu Snouts

### PR DESCRIPTION
**Pull request by MemeSnorfer**
## About The Pull Request

Adds sprites for snouted balaclava variations (all sprites by moffball).

Also adds a short snout variant, for Elzuose (coded with the help of @rye-rice). Comes with balaclava sprites for Elzuose as well (sprites also by moffball).

(Top to bottom: Combat Balaclava, Inteq Balaclava, NGR Balaclava, NGR Facemask, Balaclava)
image

## Why It's Good For The Game

Sarathi and Elzuose would no longer have weird clipping while wearing these masks :)

## Changelog

:cl: MemeSnorfer and Moffball
imageadd: Snouted balaclava sprites for both Sarathi and Elzuose
code: Elzuose snout type, for use with mask sprites
/:cl:

### CODE REVIEW

**Review by Apogee-dev — APPROVED** [review]
Looks good. The inclusion of elzu snout sprites are nice- I was noticing (and getting very annoyed by) elzu snout clipping on these very balaclavas just a couple days ago.

**Review by rye-rice — APPROVED** [review]
Thgvr seemed offput by the existence of elzu snout sprites, otherwise the sprites are fine, thanks for fixing my laziness

**Comment by thgvr** [comment]
I don't really like the idea of a precedent of unique Elzuose sprites. 

Is there any specific reason we can't use the small snout version ad the default here? The difference is about one pixel and looks normal I'd say.

The mask is supposed to have a built-in rebreather or some such if that helps make it believable.
image

**Comment by FalloutFalcon** [comment]
Yea i kinda agree with thgvr that its such a small difference to be worth adding variants for other sprites.
At the very least this doesn't require adding small snout for other sprites so the main argument is in like the very minor performance cost or bad inheritance causing missing sprites.

**Comment by MemeSnorfer** [comment]
> I don't really like the idea of a precedent of unique Elzuose sprites.

To clarify, Elzuose mask sprites aren't a precedent for **every** sprite going forwards. Most things look fine on Elzuose, save for the few tight-fitting masks like balaclavas and bandanas (moffball and I are planning on respriting bandanas in the future, which will have Sarathi variants and also require Elzuose variants for it to look good on them).

> Is there any specific reason we can't use the small snout version ad the default here? The difference is about one pixel and looks normal I'd say.
> The mask is supposed to have a built-in rebreather or some such if that helps make it believable.

It just looks silly on humans to use the Elzuose variants. Not to mention, some of these balaclavas don't have built-in rebreathers (and neither do the aforementioned bandanas).

**Review by Imaginos16 — APPROVED** [review]
why they so snout

**Comment by lectronyx** [comment]
snout sprites, my beloved

op is the hero this server needs, but not the one it deserves

will you also be tackling other helmet/mask stuff in the future?

**Pull request merged**
