### PR TITLE
slice bloodbags like on goon

### PR DESCRIPTION
**Pull request by ritorizo**
## About The Pull Request
Allows to slice blood bags with something sharp to access their content the same way you would with a beaker.

## Why It's Good For The Game

Goes in the direction of making ghetto chemistry more prevalent.

## Changelog
:cl:
add: Slice blood bag with anything sharp to access their content.
/:cl:

### CODE REVIEW

**Comment by Ms-Mee** [comment]
Zamn what a changelog

**Comment by ritorizo** [comment]
Sorry github half down were I live today and I had to rewrite my pr comment 2 times.

**Comment by ritorizo** [comment]
image

**Comment by MarkSuckerberg** [comment]
Sorry, I meant to close this ages ago. It's just not something we want, blood bags were intentionally designed to not be accessible like this.

**Pull request closed without merging**
