### PR TITLE
Syndicate and IRMG maid outfits

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
You've waited for it. And here it is, maid outfits for the Syndicate and the IRMG. (+ a new coat for the IRMG)
image
image
Featuring 'tactical' skirts and combat sleeves with insulation against shocks.

## Why It's Good For The Game

People like maid outfits, people like playing the Syndicate. I like the IRMG, I also like maid outfits. What's not to love.

## Changelog
:cl:
imageadd: Syndicate and IRMG maid sprites
/:cl:

### CODE REVIEW

**Comment by Ebin-Halcyon** [comment]
wow i'm dumb and didn't add on the last word to the title.

**Comment by rye-rice** [comment]
the prophesy has come true @YewYew

**Comment by Cenrus** [comment]
dog-hmm

**Comment by Ebin-Halcyon** [comment]
No clue why it's failing. But i'm pretty sure it wasn't related to me.

**Comment by AtlasRules** [comment]
ok i know this is two months old but the kodiak PR fixed syndie maid boxes not having maid outfits, just in case you wonder

**Comment by Ebin-Halcyon** [comment]
> ok i know this is two months old but the kodiak PR fixed syndie maid boxes not having maid outfits, just in case you wonder

That was happening? wtf lol. It worked when I tested it in this pr.

**Pull request merged**
