### PR TITLE
Repaths switchblades under kitchen knifes

### PR DESCRIPTION
**Pull request by Gristlebee**
## About The Pull Request

Repaths the switchblade under the kitchen knife so it isnt snowflaked and has all the intended knife behavior

## Why It's Good For The Game

Consistency and the switchblade is able to properly butcher.

## Changelog

:cl:
code: Switchblades are now pathed under obj/kitchen/knife
imageadd: Switchblade sprites moved from items and weapons.dmi to knife.dmi
/:cl:

### CODE REVIEW

**Review by meemofcourse — CHANGES_REQUESTED** [review]
sorry but if you're doing this it's better to just repath it so it's under /obj/item/kitchen/knife and not a snowflake item

**Comment by Gristlebee** [comment]
fair enough, Ill do that instead

**Comment by Gristlebee** [comment]
would you prefer if I to subtyped it under /obj/item/kitchen/knife or /obj/item/kitchen/knife/combat?

**Comment by meemofcourse** [comment]
just /kitchen/knife should be fine

**Review by meemofcourse — APPROVED** [review]

**Pull request merged**
