### PR TITLE
Shepherd Fixes for real this time

### PR DESCRIPTION
**Pull request by PigeonLord**
## About The Pull Request

Fixed bees being able to open the Shepherd Apiary

Adds more Light Fixtures around the shepherd

Added some farming plots in the apiary so bees can actually make honey

Fixed bees being able to open the Shepherd Apiary

Sorry for fucking up the previous 2 PRs :(

## Changelog

:cl:
add: Adds more Light Switches around the shepherd
add: Added some farming plots in the apiary so bees can actually make honey
fix: Fixed bees being able to open the Shepherd Apiary
/:cl:

### CODE REVIEW

**Review by goober3 — COMMENTED** [review]
c4a3ba53845fe8f1b702bc8084380b59
Floating light switch.

118945bc9ae249a749a0065fa5b174bf
Remove the ORM, please.

a0a53d1107ec6f8e72ce203e71bca732
Cut this list down to just follower hoodies.

c750197b53f9c1d5266a5d6d985d4ee5
Remove the shard, nexus, and null rod. Replace the nexus with a hedge, or something.

652764acffe820daefe332fe430d6f40
Remove this altar or replace it with a fluff version.

9f98ee45e1c92aea447416dde35bf131
Can you replace the trophy rack on the captain's outfit with a regular bag? Remove the heroic beacon from the curator's outfit, as well.

2a53577bbeafa54379694fc677954eac
These guys are all on the same layer as the couch. Change their layer var to 3.1.

3dff85806e91cbb7b0b87d42df05f786-1
They can make do with one pair of insulated gloves.

Good PR, all in all. Thank you for maintaining the Shepherd!

**Comment by PigeonLord** [comment]
Done everything except
>Can you replace the trophy rack on the captain's outfit with a regular bag? Remove the heroic beacon from the curator's outfit, as well.

Because last time I fucked with job code it made the Integration test fail for unknowable reasons

**Review by meemofcourse — APPROVED** [review]
the ship is starting to show its age, but thank you anyways

**Review by Latentish — APPROVED** [review]
looked good in uptime

**Review by goober3 — APPROVED** [review]
yeah

**Pull request merged**
