### PR TITLE
Removes A Lot Of Cruft

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
Removes the following:
Swarmers
Bloodcult
Soulstones
Everything Devils
Meteor Gamemode
Area/shuttle

- [x] Compiles and runs on my local

## Why It's Good For The Game
I'm fairly sure none of this stuff fits regardless of if it works with the game. And area/shuttle is annoying to see in sdmm.

God I hate it when you start pulling one thing out and it's easier to just pull the rest out than to adjust it to work in the event that someone might use it for an event once.

## Changelog

:cl:
code: A large amount of cruft has been deleted.
/:cl:

### CODE REVIEW

**Comment by Imaginos16** [comment]
How did this pass all checks this is psychotic

**Comment by Erikafox** [comment]
i'm actually an evil wizard

**Review by FalloutFalcon — APPROVED** [review]

**Comment by AverageUser67** [comment]
don't remove swarmers, that could be used later on

**Comment by FalloutFalcon** [comment]
> don't remove swarmers, that could be used later on

no they will not.

**Comment by goober3** [comment]
we've spitballed ideas but swarmers won't work for shiptest as is. it'd be better to build something better from the ground-up.

**Comment by rye-rice** [comment]
> don't remove swarmers, that could be used later on

Who the fuck are you

**Comment by goober3** [comment]
> > don't remove swarmers, that could be used later on
> 
> Who the fuck are you

that's AverageUser67 hope this helps

**Comment by thgvr** [comment]
swarmers could be fun as a rare waste biome thing but I don't plan on working on it and I don't think anyone else is

plus swarmers need like. an entire new implementation anyways to be feasible

**Pull request merged**
