### PR TITLE
Corrects some Etheral names to Elzuosa

### LINKED ISSUE #2695: [BUG] Examine text for Elzuosa list body parts as Ethereals still
## Reproduction: Spawn in as an Elzuosa, click health doll, see 
[img]https://i.imgur.com/2MjJdol.png[/img]

### PR DESCRIPTION
**Pull request by FalloutFalcon**
## About The Pull Request

renames some ethereal stuff to be correct
changes a few player facing names but mostly back end
fixes #2695 

## Why It's Good For The Game

reflect proper species name

## Changelog

:cl:
spellcheck: renames some species stuff
/:cl:

### CODE REVIEW

**Comment by Skies-Of-Blue** [comment]
Oh, thank you for taking care of this!! I've been meaning to get around to this for Months now

**Review by rye-rice — DISMISSED** [review]
can you rename the boogie bomb into something else and not make elzu immune to it

**Comment by FalloutFalcon** [comment]
> can you rename the boogie bomb into something else and not make elzu immune to it

What...???

**Comment by thgvr** [comment]
`elzuosa` is plural, `elzuose` is singular btw

**Comment by FalloutFalcon** [comment]
> `elzuosa` is plural, `elzuose` is singular btw

oh..

**Comment by rye-rice** [comment]
> > can you rename the boogie bomb into something else and not make elzu immune to it
> 
> What...???

the Etheral Disco Grenade

**Comment by FalloutFalcon** [comment]
> > > can you rename the boogie bomb into something else and not make elzu immune to it
> > 
> > 
> > What...???
> 
> the Etheral Disco Grenade

ok i found it, why does it need to exist?

**Review by thgvr — APPROVED** [review]
Thanks for this

**Pull request merged**
