### PR TITLE
The Dronetestening

### PR DESCRIPTION
**Pull request by Pockets-byte**
it is time for the machines to rise up and size their piece of the world, in this case it's a small shuttle with limited supplies and  a number of drone shells, for a completely different experience to the normal shiptest, communication barriers and inhernet mistrust shall make working with humans difficult, so these bots are on their own
comes with 1x disposable captain and container for captain 
3x disposable assistants,
2 premade drone shells and several queued up in the dronefab, but limited supplies of everything make rationing a necessity,   as you only have 20 metal and 50 glass spare, 3 picks and scanners, and two kpas, hats are also in limited supply
free RCD, batteries not included
1x RTG infinite powersource

Adds one gimmick-focused ship

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
```
_maps/shuttles/shiptest/dronetest.dmm
ERROR: Non-TGM formatted map detected. Please convert it using Map Merger!
```

**Comment by Pockets-byte** [comment]
> ```
> _maps/shuttles/shiptest/dronetest.dmm
> ERROR: Non-TGM formatted map detected. Please convert it using Map Merger!
> ```

map merger?
Edit: ah, map merger is giving me errors, unsure of how to fix
AttributeError: 'NoneType' object has no attribute 'decode'
edit edit: fixed

**Comment by Pockets-byte** [comment]
I upgraded the RTG, connected the SMESes to the grid, created and added a new drone subtype called capdrone, as a tougher leader caste, and removed the unintented RCD +mats as well as moving the APC for better access inround, as well as adding a few more PKAs thanks to drone's horrific deathrates



Edit: hell. litteral hell

**Comment by Pockets-byte** [comment]
I'll just close this since I don't have a good enough grasp of dreamaker to write anything more advanced than radials, surely an entire map is more advanced.

**Pull request closed without merging**
