### PR TITLE
Updates the syndicate hardsuit with a brand new sprite. 

### PR DESCRIPTION
**Pull request by necromanceranne**
## About The Pull Request

Updates the syndicate hardsuit with a new set of sprites by quin. 

unknown
unknown1
unknown 2

PR done on behalf of quin.

Hi.

## Why It's Good For The Game

"Looks better" - quin

## Changelog
:cl: quin
imageadd: Updates the syndicate hardsuit sprite with a new look.
fix: Fixes the syndicate hardsuits spawning in as the wrong sprite to the current mode.
/:cl:

### CODE REVIEW

**Review by triplezeta — APPROVED** [review]
cool

**Comment by Kapu1178** [comment]
I dont like the removal of the maskless state.

**Comment by Apogee-dev** [comment]
i agree with kapu, the maskless / non-EVA mode was actually a unique mechanic that really made the bloodred feel different. I know you haven't changed that mechanically, but if the combat mode isn't spaceproof it really should look the part so players don't make the mistake of running around in sanic mode and acting confused when they pop like a grape in space

**Review by triplezeta — CHANGES_REQUESTED** [review]
with the concerns brought up this really shouldn't be merged with the removal of the maskless helmet

**Comment by Zevotech** [comment]
plus, the maskless state lets you eat/take pills if you adjust your breathmask underneath it, which is a pretty neat quality of life thing for a combat hardsuit when most other suits have to remove the helmet to eat. 

also, wouldnt this change just make the elite suit THAT much better due to it keeping the maskless state? real.

**Comment by necromanceranne** [comment]
unknown

@triplezeta Hows that? Codes updated to reflect this change as well.

**Review by triplezeta — CHANGES_REQUESTED** [review]
works for me

**Review by triplezeta — APPROVED** [review]
whoops wrong review type

**Comment by Latentish** [comment]
> unknown
> 
> @triplezeta Hows that? Codes updated to reflect this change as well.

I don't know if this is just one single sprite or actually coded in. But if it's just an extra sprite, not everyone is going to be human, qnd the previous model actually disappears and shows what mask you're wearing. I don't really think that's something that should be left behind.

**Comment by Zevotech** [comment]
oh fuck thats a valid concern, is it just a bald human placeholder sprite or?

**Comment by Kapu1178** [comment]
its just using a human placeholder, if you look at the icon diff its transparency.

**Comment by Latentish** [comment]
> its just using a human placeholder, if you look at the icon diff its transparency.

Perfect

**Comment by 1glitchycent** [comment]
What's up thugs. This has my approval, as the guy who did the previous version, for all that's worth. 👍

**Pull request merged**
