### PR TITLE
Cocaine and heroin

### PR DESCRIPTION
**Pull request by linnpap**
## About The Pull Request
image
Adds cocaine, opium, heroin, and all the plants needed to make them.
[LEGALIIIIZE... DRUGS AND MURRDERRRR](https://www.youtube.com/watch?v=1zNG63rf9LQ)

## Why It's Good For The Game
More drugs are always fun. Plus, they add new RP scenarios such as drug dealing and more to the game.

## Changelog
:cl:
add: Added cocaine
add: Added heroin and opium
add: Added coca leaves and opium poppies
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
this is really funny but Why

**Comment by linnpap** [comment]
> this is really funny but Why

why not

**Comment by rye-rice** [comment]
really become space pablo escobar

**Comment by francinum** [comment]
> > this is really funny but Why
> 
> why not

Answering that is very much your problem.

Insufficient justification for addition beyond "Haha drugs are funny"

Really uninterested in referencing IRL narcotics at such a blatant level unless absolutely necessary.

**Comment by linnpap** [comment]
> > > this is really funny but Why
> > 
> > 
> > why not
> 
> Answering that is very much your problem.
> 
> Insufficient justification for addition beyond "Haha drugs are funny"
> 
> Really uninterested in referencing IRL narcotics at such a blatant level unless absolutely necessary.

drugs are funny because they add new rp elements (drug dealing, insane breaking bad scenarios, etc) that previously werent possible.
plus shit like cannabis and morphine is already in the game, so referencing irl cocaine and heroin really isnt that big of a stretch for ss13

**Comment by TheNeoGamer42** [comment]
Cannabis is legal in some places, and morphine is a painkiller that's commonly used in medicine. Pretty much any other drugs featured in ss13 are fictional, and not actually IRL drugs. cocaine and heroin are NOT legal in quite a few places, and I don't know of any places it IS legal in, along with being real world.

**Comment by francinum** [comment]
A single stone thrown is not an excuse to fill the river with more.

**Comment by linnpap** [comment]
> Cannabis is legal in some places, and morphine is a painkiller that's commonly used in medicine. Pretty much any other drugs featured in ss13 are fictional, and not actually IRL drugs. cocaine and heroin are NOT legal in quite a few places, and I don't know of any places it IS legal in, along with being real world.

what does legality have to do with anything
these are illegal, yet highly profitable drugs meant to be sold through rp. i literally cannot see anything bad about adding rp through these

**Comment by Zevotech** [comment]
> i literally cannot see anything bad about adding rp through these

i really hope this is some kind of elaborate joke

**Comment by mcmeiler** [comment]
Can't wait to RP murdering my entire fellow crew because of the cocaine-induced rage I'm currently in.

**Comment by Pidgey-chan** [comment]
> A single stone thrown is not an excuse to fill the river with more.

It's not a stone it's a feature, silly man. Perhaps some of you are ideologically opposed to those but this is an interesting one.

**Comment by TheNeoGamer42** [comment]
Also, is this a port? Who made the sprites?

**Comment by linnpap** [comment]
> Also, is this a port? Who made the sprites?

its a port of a pr I MADE for skyrat with sprites that I MADE

**Comment by francinum** [comment]
Just because you managed to convince Skyrat that it was a good idea doesn't mean it is.

This serves no purpose other than being incredibly jarring and blatant references to real drugs. Weed gets a pass because it's weed. It's the most generic concept of a drug possible, and exists in that capacity as an extremely basic implementation of systems, it doesn't demand an entire new crafting category or special object types.

**Comment by zeratino** [comment]
> Cannabis is legal in some places, and morphine is a painkiller that's commonly used in medicine. Pretty much any other drugs featured in ss13 are fictional, and not actually IRL drugs. cocaine and heroin are NOT legal in quite a few places, and I don't know of any places it IS legal in, along with being real world.

uh uh uh
straight from tg's wiki:

krokodil
meth
aranesp!!! 
you could also pull from the bartender wiki with stuff like moonshine and prune!!!!

oh lmao this got closed

**Comment by mcmeiler** [comment]
(closed pr talk lets go, last reply from me)
> krokodil
> meth
> aranesp!!!
> you could also pull from the bartender wiki with stuff like moonshine and prune!!!!

These are all reagents. This is *literally* simpler than what weed is in-game.

**Comment by TheNeoGamer42** [comment]
also meth gets a pass since its fucking hilarious watching chem explode because the chemist decided to make it for whatever stupid reason

**Comment by Zevotech** [comment]
replace the IRL hard drugs with Skooma and you might get a pass.

**Pull request closed without merging**
