### PR TITLE
Anti-Radiation Foam

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
Buyable foam that destroys radiation emitters, and decontaminates objects very efficiently.

## Why It's Good For The Game
Makes wasteplanet survival less of a hassle when prepared

## Changelog

:cl: Erika Fox
add: Anti-Radiation Foam is now available at the outpost
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
I'm not sure if we use those invisible radiation sources anymore really, and regardless they were invisible so not sure how useful this will be

**Comment by FalloutFalcon** [comment]
could easily be reworked as a general anti rad shield foam

**Comment by FalloutFalcon** [comment]
just as in it still looks like it would be useful regardless of if we have those rad sources. i will properly review later, i skimmed

**Review by FalloutFalcon — APPROVED** [review]
Looks fine, small enough to probally merged without test merge. Unless someone wants to run a wasteplanet only gimmick or something lol

**Pull request merged**
