### PR TITLE
Small Cepheus class fixes

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request
fixes the watertank being a dispenser
moves a comms unit so the suit storage unit doesnt DEVOUR it
thanks to Gorionus#1146 for the report!

## Why It's Good For The Game
errors = bad

## Changelog

:cl:
fix: fixed some things on the Cepheus class
/:cl:

### CODE REVIEW

**Comment by Erikafox** [comment]
do a fire alarm and extinguisher check too

**Review by Erikafox — CHANGES_REQUESTED** [review]
fire alarm and extinguisher check

**Comment by spockye** [comment]
image

**Comment by Erikafox** [comment]
The upper hanger needs a fire alarm

**Comment by spockye** [comment]
image

**Review by Erikafox — APPROVED** [review]

**Pull request merged**
