### PR TITLE
Tartarus-Class Military Carrier

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

Adds the Tartarus-Class Military Carrier, a security ship. Features an armory with guns, security gear, a mech bay and turrets.
image

## Why It's Good For The Game

its a ship to test

## Changelog
:cl:
add: Adds the Tartarus-Class Military Carrier
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
oh i forgot atmos

**Comment by Nobelium-XVIII** [comment]
> oh i forgot atmos

As an atmos main I cry out in pain upon hearing this statement

**Comment by Fikou** [comment]
> > oh i forgot atmos
> 
> As an atmos main I cry out in pain upon hearing this statement

its here now :D

**Comment by Nobelium-XVIII** [comment]
Pics or it didn't happen

**Pull request merged**
