### PR TITLE
Adds a new jungle ruin, 'Old Crashed Interceptor'

### PR DESCRIPTION
**Pull request by Yellow-Mushroom**
## About The Pull Request

This PR adds a new ruin, a crashed Condor-Class (Condor class is not in game).  An overgrown crashed Condor Class, a forgotten remnant of the Corporate Wars. Inspired by this line in the HackMD page on the corporate wars:
image

The ship has no written in-game lore, but is implied to have one to multiple large explosions in the back and throughout the port side that have downed it on the jungle planet sometime 12-20 years ago with its vast amounts of vegetation growing within it. 

Here are some pictures of the ruin in its full:
condor-1
condor-2
condor-3

It looks a bit different than this now, with some new decal layouts and what not, check #1224 for references of new decals

It has some notable loot of the Condor's custom long range beams, a disabler, some armor, a deactivated AI, and a sec hardsuit; other than that it has a large amount of scrap loot that can be salvaged from the ship, such as tech and items, meaning that one or more ships can salvage the ship and there will most likely still be enough for the next ship to come salvage it due to the multi-departmental diversity of salvage loot. 

The loot contains (but I may have missed some items):
-Ion Thrusters x6
-Engine prechargers x7
-SMES Module 
-Pacman Generation
-condor long range beams x2
-welding tanks x3
-deactivated AI
-redemption machine,
-mining drill
-mining scanner
-9mm ammo box
-pairs of combat boots z2
-pairs of gloves x2
-blue suit and ties x2
-Multiple dark blue jumpsuits/jumpskirts
-some cables n handcuffs
-sec records console
-APC control console
-crew monitoring console
-eva suit n helm
-foam tank
-hi-capacity water tank
-RPD 
-light replacer
-deepfrier
-Food processor
-air scrubber
-reagent grinder
-drink shaker
-drinks chem dispenser
-cell charger
-cryopod
-operating console
-surgery bed
-scalpel
-bonesaw
-hemostat
-rolling bed
-box of syringes
abd shit tons of scrap titanium and scrap metal 

## Why It's Good For The Game

This adds another ruin to the game which I think is good for variety, also another jungle ruin thats not just a small building. It also helps build some lore for the corporate wars history. The nature of the ruin I also believe is good due to the variety of equipment that is there, meaning that unlike how much other ruins are, because one crew has already gone in, doesn't mean that the ruin is entirely worthless.

## Changelog
:cl: Myco/Yellow
add: Adds a new jungle ruin, an old crashed interceptor
/:cl:

### CODE REVIEW

**Comment by PiperDoots** [comment]
Could you add an image of it? Bit hard to give comments on a map we can't see.

**Comment by Yellow-Mushroom** [comment]
> Could you add an image of it? Bit hard to give comments on a map we can't see.

Yep aha, had to post it first so I could add the images

**Comment by Cenrus** [comment]
Really quality stuff, good job

**Comment by Yellow-Mushroom** [comment]
Laying in bed realized I forgot to replace real lattices with fake ones, will do that sometime later

**Comment by Zevotech** [comment]
> Laying in bed realized I forgot to replace real lattices with fake ones, will do that sometime later

this reminds me of another jungle ruin with lattice-based issues. the nightmare is unending. im off to fix that but good map op.

**Comment by Fikou** [comment]
why not add the condor as an admin only map?

**Comment by Yellow-Mushroom** [comment]
> why not add the condor as an admin only map?

I’ll probably PR this when I fix the lattice issue

**Comment by Latentish** [comment]
> > why not add the condor as an admin only map?
> 
> I’ll probably PR this when I fix the lattice issue

I heavily encourage it! This is such a high quality ruin. I adore this.

**Comment by Yellow-Mushroom** [comment]
I attempted to replace the lattices with decal lattices but that disallowed them to be walked over, unless there is a solution for that, I think this is the final version for the PR

**Comment by Latentish** [comment]
This looks pretty solid! I'd say we could possibly test merge it by the next uptime.

**Review by Latentish — CHANGES_REQUESTED** [review]
There are a few security wall lockers on the ship. Walllockers cannot be busted open without an EMAG or proper ID card. If you could either add unlocked versions, or just put the loot elsewhere that's fine. 
Somewhat related since I never found out what was in the lockers, this is an interceptor. I'd like to see a weapon or two to claim. A cool gun that's theme appropriate.
-Add a replacement for the lockers
-Make sure there's like 1 or 2 guns somewhere

**Review by Latentish — APPROVED** [review]

**Review by Latentish — APPROVED** [review]
I'd like to merge this. Have you noticed any extra issues that need to be addressed before doing so?

**Comment by Yellow-Mushroom** [comment]
> I'd like to merge this. Have you noticed any extra issues that need to be addressed before doing so?

The only issue ive noticed is that the ruin edge tiles have strange atmos but that’s an issue outside of this PR and I try to account for it with the design of the ruin 😔

**Comment by Latentish** [comment]
> > I'd like to merge this. Have you noticed any extra issues that need to be addressed before doing so?
> 
> The only issue ive noticed is that the ruin edge tiles have strange atmos but that’s an issue outside of this PR and I try to account for it with the design of the ruin 😔

This could easily be an issue with the planet init which is being worked on. Just double check your turfs for weird "initial_gas_mix" values in that area, and if it's all normal, we can merge this.

**Comment by Latentish** [comment]
Bro what's marg with you?
This is good.

**Pull request merged**
