### PR TITLE
The False Prophet

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Adds a new megafauna, still mostly WIP, but I need to make this PR so that people yell at me to get it done.

See discussion #463 for more info!

image
(the laziest and least flattering screenshot possible)
(it's animated and it looks incredible just take my word for it, I'll put better pics later)

Sprites needed:
- [ ] Prophet meat
- [ ] Prophet eyes
- [ ] Prophet spine (crusher trophy)
- [ ] Prophet tail club (raw/cooked)
- [ ] Prophet tail meat roast (raw/cooked)
- [ ] Prophet tail cloak

## Why It's Good For The Game
New, unique megafauna with incredible sprites by @any%#5784! (don't remember your github, sorry)

## Changelog

:cl:
add: The false prophet, a brand new and powerful megafauna with its own diverse loot
/:cl:

### CODE REVIEW

**Comment by zestybastard** [comment]
image

**Comment by TallDeekus** [comment]
POG.

**Comment by ilikesaying** [comment]
poggers
https://github.com/shiptest-ss13/Shiptest/discussions/463

**Comment by Latentish** [comment]
> This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 14 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself

Shut the fuck up.

**Comment by TallDeekus** [comment]
> > This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 14 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself
> 
> Shut the fuck up.

Based, also, first pr tag?

**Comment by Latentish** [comment]
> > > This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ 14 days, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself
> > 
> > 
> > Shut the fuck up.
> 
> Based, also, first pr tag?

Yes we always want to encourage furst PR's like this. Mark Suckerberg seems really promising and I think adding a unique new megafauna is a pretty cool first addition.

**Comment by Ms-Mee** [comment]
I knew marg could become the bestest of all coders

**Comment by ZephyrTFA** [comment]
Closing this until you have time to work on it 😿

**Pull request closed without merging**
