### PR TITLE
remove arnold pizza

### PR DESCRIPTION
**Pull request by Erikafox**
:cl:
del: arnold pizza
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
spite pr detected (it really should go though, good lord)

**Comment by Erikafox** [comment]
i thought you knew every pr i make is driven by a deep seated sense of spite

**Comment by tantspants** [comment]
what is arnold pizza?

**Comment by Erikafox** [comment]
> what is arnold pizza?

reference item that just blows your arms off or gibs you if you put pineapple on it.

**Comment by tantspants** [comment]
> > what is arnold pizza?
> 
> reference item that just blows your arms off or gibs you if you put pineapple on it.

oh that sounds like it deserves to be removed

**Comment by thgvr** [comment]
soulless

**Comment by Maksoplo** [comment]
Another soul removal PR

**Comment by Erikafox** [comment]
please refer to my previous comment about all my development effort being driven by spite

**Comment by Maksoplo** [comment]
> please refer to my previous comment about all my development effort being driven by spite

the best driving force

**Comment by Ratvarr** [comment]
another soul ,sterilized, another  tg refrenced. unused

**Comment by thgvr** [comment]
i hate it here

**Comment by thgvr** [comment]
The reference isn't even funny

**Comment by Maksoplo** [comment]
> The reference isn't even funny

I don't think, it was funny at any point 
It was always just shitty and annoying really

**Comment by Tsar-Salat** [comment]
Damn :(

**Comment by Erikafox** [comment]
who are these people. why are you on a merged spite pr. where am i

**Pull request merged**
