### PR TITLE
Fixes a few ships' TEG setups

### PR DESCRIPTION
**Pull request by SapphicOverload**
## About The Pull Request

Removes the disposals chutes some TEG setups have for you to throw lit welding tools into, and replaces them with proper igniters.

## Why It's Good For The Game

Having a disposals chute to throw lit welding tools into was a stop-gap solution to igniters not working, which was fixed over a year ago in #1675.

## Changelog

:cl:
add: Adds an igniter and button to the TEG of every ship that was missing one
del: Removed the welding tool TEG chute some ships had
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
I don't think the igniters work

**Comment by SapphicOverload** [comment]
> I don't think the igniters work

I fixed them myself over a year ago (#1675) and the last time I played they still work.

**Comment by SapphicOverload** [comment]
Tested the igniter again, still works.

**Comment by Apogee-dev** [comment]
I'd revert the changes on the Shetland specifically. It's deliberately kind of a shitbox with substandard equipment, the chute suits the vibes better.

**Pull request merged**
