### PR TITLE
Integrated Pawsitronic Nyassis

### PR DESCRIPTION
**Pull request by PiperDoots**
## About The Pull Request

Adds the pawsitronic united frame and nyaru screen to IPCs.

## Why It's Good For The Game

More customization is always nice to have.
Also Nyaru.
nyaruspin

## Changelog
:cl:
imageadd: added Pawsitronic United IPC frame
imageadd: added Nyaru screen
/:cl:

### CODE REVIEW

**Comment by Ebin-Halcyon** [comment]
Fastest merge in the west.

**Comment by PiperDoots** [comment]
she deserves it

**Comment by Bokkiewokkie** [comment]
NYARUUUUU

**Review by triplezeta — COMMENTED** [review]
it wants me to review it

**Comment by ZephyrTFA** [comment]
Merge under 24hr? Going in your permanent record

**Comment by PiperDoots** [comment]
> Merge under 24hr? Going in your permanent record

This was VERY important okay

**Pull request merged**
