### PR TITLE
Flanger-Class Shuttle (based off Sidewinder from Elite Dangerous)

### PR DESCRIPTION
**Pull request by mel-byond**
## About The Pull Request

This adds the Flanger-Class Multipurpose Shuttle, a ship based off the Sidewinder MkI from Elite Dangerous [[link to wiki]](https://elite-dangerous.fandom.com/wiki/Sidewinder_MkI)

The idea lorewise is that this is a NTSV vessel by NT's subcompany Northwind Shipping, meant for high priority shipments and shipment bounties.

The gameplay will primarily focus on mission completion, as I haven't seen a ship intended for that. Hence why it's intended to be a small & speedy ship.

**TODO list:**

- [x] ~~Fix Advanced Airlock Controller madness AAAAAA~~
- [ ] Figure out something for mob capture missions, nets?
- [ ] (Optional) Helm console variation that looks like Elite Dangerous's HUD?

## Why It's Good For The Game

deconstruction an autolathe to get your precious titanium back shouldn't be a thing

## Changelog
:cl:
add: Northwind Shipping brings out their high-priority Flanger-Class Shuttles
/:cl:

### CODE REVIEW

**Comment by mel-byond** [comment]
what. I must've fucked up the branch I was working on
E

**Comment by mel-byond** [comment]
can someone remove the TGUI label, I messed this up with my other PR lmao

**Review by Apogee-dev — CHANGES_REQUESTED** [review]
Looks good in general, but there's a few issues that need correction.

1. Please don't stack multiple wall-mounted objects on the same tile wherever possible, especially critical infrastructure like APCs and air alarms. If the ship is damaged and any of these objects are destroyed, the crew would be unable to replace them in their original configuration. This ship has very limited wall space of course but at least make sure APCs, air alarms, the wideband, and the turret controller have their wall completely to themselves.
2. The SSUs placed into the walls are also an illegal mapping technique. Try to just place those over the floor instead. You could probably afford to drop the innermost set of engines to make that happen, this ship is ridiculously fast as it is. If you can't make that work, replace them entirely with wall lockers.
3. Some wallmounted objects (namely intercoms and shutter buttons) don't have the correct dir value for the wall they're mounted on.
4. Catwalks and lattices over space tiles will cause issues when the ship lands. Put plating under the catwalks and replace the lattices with fake lattices over plating.
5. Make sure to include a spare magazine or two with that Commander. You can print ammunition at an autolathe, but not magazines.
6. You misspelled "Surveyor" when listing out the custom jobs, and the surveyor is using an outfit datum intended for independent ships. I'd just stick to the default miner outfit or the one at datum/outfit/job/miner/old that uses the classic miner overalls instead of the explorer suit.
7. You may wish to impose a (generous) ship limit, maybe 3 or 4, just to avoid rounds getting populated with nothing but Flangers. Ship limits are most important on big ships that can soak up a lot of crew, but if you go far enough in the opposite direction with small ships you start getting the Pill Effect.

**Comment by Apogee-dev** [comment]
also, make sure your file names meet naming standards. ship file names should follow a FACTION_SHIPNAME format, so for this it should be nanotrasen_flanger for both files.

**Comment by mel-byond** [comment]
> Looks good in general, but there's a few issues that need correction.

Alright! I will see if I can spend some time working to correct that when I have time (probably not until a couple days)
Thanks a lot for the constructive feedback, I'll put this PR on draft until that feedback is applied

**Comment by Latentish** [comment]
I like this one, I look forward to seeing this again when it's put up for review again.

**Comment by mel-byond** [comment]
Alright the feedback ssssshould be applied now.

**Comment by mel-byond** [comment]
Also added some code that fixes the AAC issue, please be mindful of that and maybe add an according label

**Comment by ZephyrTFA** [comment]
> Also added some code that fixes the AAC issue, please be mindful of that and maybe add an according label

Nope, atomize this

**Comment by mel-byond** [comment]
> > Also added some code that fixes the AAC issue, please be mindful of that and maybe add an according label
> 
> Nope, atomize this

Alright! Atomizing it

**Comment by mel-byond** [comment]
cool. popped the AAC fix under #1276

**Comment by hynet-mel** [comment]
bump, can someone review this for the new changes

**Comment by hynet-mel** [comment]
oops wrong account

**Comment by Fikou** [comment]
you probably wanna delete those comments

**Pull request closed without merging**
