### PR TITLE
Fixes a good chunk of Vox sprites. Removes environmental regulator

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
Oh god the pain. Oh god. The unbearable pain. Why.

Adds a ton of unused vox sprites from Drawsstuff.
Cleans up the files for sprites we don't actually have
Ensures they are pathed correctly, with flags set correctly.
I spent five hours on this in one sitting after being upset at shitty vox mechanics/sprite support again. They're cool and unique and it was sad.
Removes the Environmental Regulator.

## Why It's Good For The Game
1. Vox sprites were incomplete. This completes them a little bit more.
2. The environmental regulator isn't fun. This will remove the regulator and vox needing to use it. It was buggy, poorly made, and just not fun even when it worked correctly. Vox aren't nearly strong enough to be constantly crippled.

## Changelog

:cl:
add: A metric ton of Vox sprites
del: Vox no longer need environmental regulators
/:cl:

### CODE REVIEW

**Comment by TallDeekus** [comment]
The pain may be forever but ao are Vox.

**Comment by RuneQuesteER** [comment]
removing the regulator makes me sad. I actually liked that, made playing Vox feel just a bit more unique

**Comment by thgvr** [comment]
Unfortunately it's not fun or functional. Something will replace it in the future.

**Review by MarkSuckerberg — APPROVED** [review]
guh

**Pull request merged**
