### PR TITLE
Adds my first ship =))))

### PR DESCRIPTION
**Pull request by Latentish**
Redoes the Boyardee =)
## About The Pull Request

The boyardee is old. This is new! New = better =))))
## Changelog

:cl:
add: Adds new boyardee
tweak: tweaks boyardee json
delete: old boyardee map
/:cl:

### CODE REVIEW

**Comment by Erikafox** [comment]
I'm going to gitban you

**Comment by Latentish** [comment]
> I'm going to gitban you

Hm I get your point but have you considered taht you're stupid? It's true! I will NOT @ you in ruinyar4d, the fact that I have to register to use the discord is absolutely outrageous. I'm going to complain about this on reddit.

**Comment by Erikafox** [comment]
we have a redditor I repeat we have a redditor

**Comment by TheNeoGamer42** [comment]
0/10 theres not even any booze on this to get drunk and pilot it into an asteroid storm what the fuck

**Comment by ariever** [comment]
looks good to marge :)

**Comment by meemofcourse** [comment]
man i'm dead

**Comment by spockye** [comment]
You sugk

**Pull request closed without merging**
