### PR TITLE
re:Materials

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request
This redoes:
Metal
Plasteel
Glass
Reinforced Glass
Plasma glass
Reiforced Plasma glass
plastic
brass
paper wall
rods
shuttle glass
plastitaum glass
sandstone
gold
uranium
plasma
silver
snow
titanium
plastitanium

The runite textures were taken from https://github.com/tgstation/tgstation/pull/65617 with permisssion
image

Thank you so much @SomeAngryMiner for getting this project back on it's feet, and @triplezeta as usual
## Why It's Good For The Game

image

## Changelog
:cl: Azlan, AdipemDragon, retlaw34
imageadd: A bunch of stack items, mostly related to materials have been redone.
/:cl:

### CODE REVIEW

**Comment by Boxlta** [comment]
add images showing the new sprites

**Comment by rye-rice** [comment]
later

**Comment by rye-rice** [comment]
ready, @triplezeta

**Comment by francinum** [comment]
Photos.

**Comment by triplezeta** [comment]
oaugh i forgot ot review this 
ill do it later

**Review by triplezeta — CHANGES_REQUESTED** [review]
Plasteel's new texturing is quite strange to me now that I've seen it in-game. Aside from that I have no issues with the PR's other sprites.

**Comment by rye-rice** [comment]
image
plasteel has been redone

**Review by triplezeta — APPROVED** [review]

**Review by ZephyrTFA — CHANGES_REQUESTED** [review]
That is a direct rip of the runite bar from Runescape which violates both their license and EULA.
[https://runescape.wiki/images/Rune_bar.png](url)

**Comment by rye-rice** [comment]
you might need to tell every other codebase about it because im pretty sure tg has it

**Comment by rye-rice** [comment]
rather, we inherited it from tg, and theres likely a lot of forks that have it as well

**Comment by rye-rice** [comment]
runite has been redone to be more generic but more importantly not a rip
image

**Review by ZephyrTFA — APPROVED** [review]

**Comment by ZephyrTFA** [comment]
probably update the image in the PR body

**Comment by rye-rice** [comment]
done

**Comment by rye-rice** [comment]
Runite was updated again 
image ported from a tg pr

**Pull request merged**
