### PR TITLE
No more crusher trophy effects

### PR DESCRIPTION
**Pull request by FalloutFalcon**
## About The Pull Request
removes crusher trophies relevance from crushers. I didn't fully remove them because they are neat for crafting and.. as trophies
atomization of #2848

## Why It's Good For The Game
miner power gamer cruft. Its not really needed when we are trying to balance stuff around guns. Crusher still remains the strongest mostly obtainable melee weapon.

## Changelog

:cl:
del: Trophies can no longer be used in crushers
/:cl:

### CODE REVIEW

**Comment by Sun-Soaked** [comment]
Code looks fine, but I'd kinda want a use for trophies that don't have one if you're keeping them

**Comment by FalloutFalcon** [comment]
> Code looks fine, but I'd kinda want a use for trophies that don't have one if you're keeping them

Crafting recipes, Cool little thropies, and i would like to work them into a bounty system at some point

**Comment by Sun-Soaked** [comment]
> > Code looks fine, but I'd kinda want a use for trophies that don't have one if you're keeping them
> 
> Crafting recipes, Cool little thropies, and i would like to work them into a bounty system at some point

there are some that don't currently have a use, though. I wouldn't leave them accessible, especially to players who currently Expect Them to Do A Specific Thing.

**Comment by FalloutFalcon** [comment]
> > > Code looks fine, but I'd kinda want a use for trophies that don't have one if you're keeping them
> > 
> > 
> > Crafting recipes, Cool little thropies, and i would like to work them into a bounty system at some point
> 
> there are some that don't currently have a use, though. I wouldn't leave them accessible, especially to players who currently Expect Them to Do A Specific Thing.

hgmmmmmmmm fine.

**Review by Sun-Soaked — APPROVED** [review]
looks good now

**Pull request merged**
