### PR TITLE
Ports the Tg maid sprite, to replace the flat one

### PR DESCRIPTION
**Pull request by Sylphily**
## About The Pull Request
Ports https://github.com/tgstation/tgstation/pull/65844
image
## Why It's Good For The Game
Improbement

## Changelog
:cl:
add: Adds new maid uniform sprites to replace the flat ones 
/:cl:

### CODE REVIEW

**Comment by Ebin-Halcyon** [comment]
Makin' waves. 😎

**Comment by Sylphily** [comment]
What the fuck failed

**Comment by rye-rice** [comment]
> Makin' waves. 😎

I await the syndicate maid sprites

**Comment by Sylphily** [comment]
Sydicate maid when?

**Comment by Sylphily** [comment]
why the fuck is it failing!
and why is it not on my side

**Comment by Cenrus** [comment]
priorities

**Comment by Sylphily** [comment]
what are you telling me that making the maid uniform updated isn't a high priority?

**Comment by Cenrus** [comment]
Quite the opposite, I know several people on the server who would wear this. Willingly.

**Comment by Sylphily** [comment]
funny i totally wouldn't be one

**Comment by rye-rice** [comment]
> Quite the opposite, I know several people on the server who would wear this. Willingly.

@zestybastard

**Comment by zestybastard** [comment]
> > Quite the opposite, I know several people on the server who would wear this. Willingly.
> 
> @zestybastard

you will regret this next time you make a gunsprite

**Comment by Ms-Mee** [comment]
> > > Quite the opposite, I know several people on the server who would wear this. Willingly.
> > 
> > @zestybastard
> 
> you will regret this next time you make a gunsprite

You're*

**Comment by Sylphily** [comment]
Now that I think about it I hope the box inside a box isn't used maliciously

**Review by ZephyrTFA — APPROVED** [review]
I mean if /TG/ approved it who are we to judge

**Comment by Martinpachu** [comment]
h hey are you talking about me right now

**Comment by Sylphily** [comment]
I mean they are objectively better sprites period

**Comment by Sylphily** [comment]
> h hey are you talking about me right now

Wait are you judging?

**Comment by Martinpachu** [comment]
> > h hey are you talking about me right now
> 
> Wait are you judging?

No i wear it

**Comment by Sylphily** [comment]
Good

Also I hope it gets merged soon so I can use it

**Comment by Sylphily** [comment]
pain

**Comment by Sylphily** [comment]
its fixed

**Comment by ZephyrTFA** [comment]
You appear to have slightly destroyed your own time line

**Comment by Sylphily** [comment]
every thing is broken

**Comment by Cenrus** [comment]
Goddamn! I hope your housecleaning skills are better than your PR making ones :trollface:

**Comment by Sylphily** [comment]
i fucked up bad ok

**Comment by Sylphily** [comment]
it fucking works now
pls merge before something else breaks

**Comment by Sylphily** [comment]
Fuck not again

**Pull request merged**
