### PR TITLE
Cepheus nerfs

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
removes the cepheus's:
ORM
Circuit imprinter board (it's been replaced with a BASIC board)
Circuit imprinter 
CM-15 shotgun

## Why It's Good For The Game
poorly guided balance

## Changelog

:cl:
balance: The cepheus's starting gear has been nerfed.
/:cl:

### CODE REVIEW

**Comment by Dolth** [comment]
No ORM at all so no mining at all either?

**Comment by Erikafox** [comment]
may be better to leave that out till we get the outpost refinery set up tbh

**Comment by Dolth** [comment]
Can they make mech boards aswell?

**Review by PrefabQuasar — APPROVED** [review]

**Comment by VileBeggar** [comment]
the removed science printer really makes this ship very underwhelming to play. it becomes frustrating to do robotics when one of the necessary parts to do so is not present on your ship. hopefully you change your mind on this but i understand if you desire to keep it this way for whatever reason. EDIT: i've just remembered that the base printer was actually unrestricted (which is yikes). wouldn't be more logical to switch it to a sci-only printer? BASIC doesn't see much use with how little there is to print on it

i personally don’t mind the lost orm, it’s just a bit of qol. the shotgun is a good riddance, though you missed a spare mag in the ammo locker

**Review by spockye — COMMENTED** [review]
put the ORM back, and I'll Merge

**Review by spockye — APPROVED** [review]

**Pull request merged**
