### PR TITLE
Gun Attachments System / Components / Handlers

### PR DESCRIPTION
**Pull request by ZephyrTFA**
## About
Does exactly what the title says, creates and implements a gun attachment system that uses two different components to function.
Attachment Holder and Attachment.

## Why is this a good change
I like it, removes snowflake code, and also makes it much easier to add new attachments in the future.

## Sprites Needed
 - [x] Laser Sight
 - [x] Rail Light
 - [x] Bayonet

## Changelog
:cl:
refactor: Attachments for guns are now fully componentized.
add: Laser Sight: reduces spread on guns
add: Rail Light: the attachment to replace seclites being able to go on guns
add: Bayonet: STABBY STABBY, can expand to have longer range but less damage :)
:/cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
how did you make the framework for this in like a single night

**Comment by ZephyrTFA** [comment]
> 
> 
> how did you make the framework for this in like a single night

I like to consider myself above average for coding.
Also this has been an idea of mine for a while

**Comment by ChungusGamer666** [comment]
> how did you make the framework for this in like a single night

it's just a framework, not that hard to do
seeing this work in practice would be the real problem

**Comment by shiptest-server** [comment]
#### Test Merge Removed

**Comment by shiptest-server** [comment]
#### Test Merge Deployed

##### Server Instance
shiptest

##### Revision
Origin: aabc6f1b144d0c36cf9f9f5d49313c6586ec6706
Pull Request: d8f698ffa12d0b53a0d2f7ac0abf0d7bcd6d8abb
Server: 4a612b6abc77d3aaae270b65dc4c94667e4d6be2

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 293bad3e54aa3f26644d5d871baee9eda36057ca
Pull Request: d8f698ffa12d0b53a0d2f7ac0abf0d7bcd6d8abb
Server: 2c17e761a3dbe846412b0eb5224178d8c7dfc1e4

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: d79659920aec58007df63d3e9b96cb0fe1a16353
Pull Request: d8f698ffa12d0b53a0d2f7ac0abf0d7bcd6d8abb
Server: 72d94bef2620899bd315f660ccb547df14ffc328

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: dd854e7386a7a9a664d6357aab6213b032e1817b
Pull Request: d8f698ffa12d0b53a0d2f7ac0abf0d7bcd6d8abb
Server: d097fa6e32a13458e756307a43c1764f99b243bc

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 4d98cdcea7b4591b94a06237309039f4980217fa
Pull Request: d8f698ffa12d0b53a0d2f7ac0abf0d7bcd6d8abb
Server: 9a29cfa82da92d64f18a8f8bcd69d3ea934be1ac

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: f789e74004b3acb82690d77398848b240a153b6f
Pull Request: d8f698ffa12d0b53a0d2f7ac0abf0d7bcd6d8abb
Server: fec71ade6e716fb63d267abca95b86e22f5eb182

**Comment by shiptest-server** [comment]
#### Test Merge Removed

**Comment by ZephyrTFA** [comment]
its only stale because I'm working on other things, begone you

**Comment by zestybastard** [comment]
finally, the real GAS

**Comment by ZephyrTFA** [comment]
I'll return to work on this at a later date; more important things are being worked on

**Pull request closed without merging**
