### PR TITLE
IPC ears and stomach don't decay

### PR DESCRIPTION
**Pull request by tiramisuapimancer**
## About The Pull Request
wtf buffs ipcs even more, biased staff team

## Why It's Good For The Game
bugfix

## Changelog
:cl:
fix: IPC stomach and ears shouldn't decay while dead now
/:cl:

### CODE REVIEW

**Comment by Recoherent** [comment]
how am i supposed to rp my ipc's battery popping like a really old lithium ion cell you left in something a decade ago now??

**Comment by tiramisuapimancer** [comment]
rp it fool

**Comment by Recoherent** [comment]
i hate rp and ipcs now wtf

**Comment by Vexylius** [comment]
ipc players 🙄

**Pull request merged**
