### PR TITLE
Adds a crafting recipe for meson sunglasses

### PR DESCRIPTION
**Pull request by SapphicOverload**
## About The Pull Request

Adds a crafting recipe for meson sunglasses. Also fixes them not having a sprite because of a typo.

## Why It's Good For The Game

Every other sunglasses HUD can be crafted, so why not meson sunglasses?

## Changelog
:cl:
add: adds crafting recipe for meson sunglasses
fix: fixes meson sunglasses not having a sprite because of a typo
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
real

**Comment by Zevotech** [comment]
indirect buff to miner IPCS for welding protection

**Comment by AtlasRules** [comment]
thanks for reminding me to port a ton of HUDpatches and make em craftable too

good PR, IPC miners stay winning 👍

**Comment by ZephyrTFA** [comment]
This was discussed internally and maintainers appear to loosely agree that meson sunglasses shouldn't exist in the first place, let alone be craftable.

**Pull request closed without merging**
