### PR TITLE
Remaps the Osprey

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request
nanotrasen_osprey2
nanotrasen_osprey2_areas

A full remap of the Osprey, featuring an improved layout and some slight improvements to starting equipment.
The changes are as follows:
- Disposals has been upgraded to a functional deliveries system
- Dedicated AI core
- Improved cargo & sci layout
- Better-equipped kitchen with a central location
- Far larger engineering and atmos spaces with less wasted space in the back of the ship
- A prebuilt telecomms relay tuned to Nanotrasen channels
- Ship now flies the right way

## Why It's Good For The Game
The Osprey was looking pretty sad, aged poorly, and had grown quite unpopular. This should hopefully help fix the issue.

## Changelog

:cl:
tweak: Fully remapped the Osprey
/:cl:

### CODE REVIEW

**Review by Erikafox — COMMENTED** [review]
needs a ghost marker somewhere

image
big firelocks under the doors to the AI chamber. As I understand they have some sort of issue.
image
I'd change these two tiles to engine 
image
and these two to atmos
StrongDMM_v61PseKn9A
minor case of wall object littering that could be fixed by swapping the light fixture and AAC. Also I'm not entirely sure that this airlock set up will 'work' (the vents should also be high volume)
StrongDMM_bfkWu5zVDv
check out the /modern railings. They might look decent here
StrongDMM_WvhguLmjNl
make ONE of these a falsewall.
StrongDMM_mjjyFZiKB9
there are 3 super pacman boards here, they probably only need 2

There is no APC in the atmos / engineering areas
StrongDMM_itT0jByi6T
this upsets me on a visceral level, could it be like... symmetrical.

I think it would be mildly funny if they had an Experimentor board in science.
The AI chamber could do with some blast doors/shutters.
Think about giving some spare job bags/satchels/duffels to the lockers.

**Comment by Erikafox** [comment]
image
also default plating under the bridge doors

**Comment by Apogee-dev** [comment]
Updated in response to review

**Review by spockye — CHANGES_REQUESTED** [review]
image
some overlap here (also light on comms unit :pensive: ) also, please move lockers to +-28!

image
The computers cut off really weirdly. Unless theres a ending piece, please use normal computer sprites. the decalling also looks a tad weird, continuing around with the corner cutting (and the corner tile turning white). The colours also stick out in a bad way imo.

image
the ai hallways could use lights

image
three of these aren't connected to the sci button

image
the disposals buttons could use naming

**Comment by Apogee-dev** [comment]
The map received several commits since the last test, be sure to check the latest commit before you review. That being said...
> wallmount+light

At this point I just fully disregard lights overlapping with wallmounts. It's not practically avoidable half the time, and even when it is the sprites don't actually overlap. We should probably just tweak construction to allow building lights on the same tile as other wallmounted objects so players can rebuild them if they do get fully destroyed. re: the mounts, the overlap is minor and more importantly it's not possible for a player to see it in-game without being a ghost. Besides that, wallmounts are getting resprited soon along with the new walls.
As for the lockers, I'll tweak that in the next commit.
> bridge

The computers are using the correct icon state, the sprites are just configured incorrectly. I didn't want to lump a sprite fix in with a map PR and figured rye would do it separately, but I'll just open a new PR fixing the sprites in a moment. Karl griped about the decals too, but trust me, I tried a bunch of different patterns to get it to look right and this is the best I could manage. I don't have a fix for the white corner tiles either, that's been an issue with diagonal walls for a long time and using full walls would ruin the shaping on the bridge. As for the colors, I think the NT blue looks fine on the grey, but I invite you to find a better color for the bar than the one labeled "bar." Everything I tried either didn't really make sense or was already being used for another room.
> ai hallways

These aren't hallways, they're intended to basically be tiny maint tunnels. And there's nowhere to put a light, especially on the south tunnel, where the north tile has blast doors on both sides, the middle tile is fully occupied by a blast door, and the south tile's only open wall space is the one with the turret panel. They're just 3 tiles and they have a window anyway.
>sci window

The reason I suggested looking at the latest commit first. This was originally made so players could easily knock out the window and turn it into a mech bay door. I caved and just made it a garage door by default.
> disposals button

technically speaking it's named by default ("door button") and the mass driver button is already labeled. What would you suggest i rename it to to avoid confusion, if it has confused anybody? There's only one set of blast doors nearby.

**Comment by Zevotech** [comment]
could use more O2/fire lockers like the old one had.

**Comment by Apogee-dev** [comment]
> could use more O2/fire lockers like the old one had.

yeah i added a couple more O2 lockers after the test round. Fire lockers are limited to one in atmos and one in cargo though. It's got a ton of extinguishers, it's fine.

**Comment by goober3** [comment]
the First Officer doesn't have ID console access, shame!

**Comment by Apogee-dev** [comment]
> the First Officer doesn't have ID console access, shame!

Actual skill issue, works fine in local test. You're probably using the console wrong, you don't need to insert your authorization card to log in. Just press the "log in" button in plexagon and insert the ID you're trying to modify.

**Review by Erikafox — APPROVED** [review]

**Comment by Erikafox** [comment]
I am happy with this.

**Review by spockye — APPROVED** [review]

**Pull request merged**
