### PR TITLE
New Rockplanet Ruin: The Abandoned Shipping Dock (Redone Layout)

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
SDMM:
StrongDMM-2024-04-21 04 36 46
StrongDMM-2024-04-21 04 36 49

Ingame:
image

Adds a new ruin for rockplanet. Its an abandoned shipping dock previously used by traders and smugglers in the sector. It has since fallen into disrepair, forgotten by its owners. Malicious scavengers or other groups have since filled the place with devious traps, hoping to catch their competition (You) off guard.

## Why It's Good For The Game
more ruins that arent free rnd or gamer loot are good
please map more ruins

## Changelog

:cl:
add: rockplanet_shippingdock.dmm and associated code
/:cl:

### CODE REVIEW

**Review by spockye — COMMENTED** [review]
image

we have rock sidings, just saying 🥺 
looks good! will TM when possible

**Review by spockye — CHANGES_REQUESTED** [review]
image

Use turf stairs, not obj stairs

**Comment by Zevotech** [comment]
Reviews addressed and added an areas-on picture.

**Review by meemofcourse — COMMENTED** [review]
i think there's a decent amount of loot for what is not a decent amount of threat, specially around the supposedly-secure areas where someone with a toolbox can just smash the doors open, the beartraps can be just picked up by players and the landmines are blinking. i do tend to lean towards more funny kill the player ruins and this is my opinion, but try and find some more traps? i don't know, some more elaborate stuff like figuring out how to detonate a pile of IEDs

**Review by Erikafox — CHANGES_REQUESTED** [review]
Put some scattered rocks, glass shards, and debris around the broken solar arrays, get some storytelling on how they've been degraded / broken
image
Exterior areas should be using the /explored type of the planet's main area. This allows weather to happen. We like weather

image
is this a stray decal? Also please make a percent chance mech spawner so it's not always gonna be there.

image
people decay... but they might've left something... leave a hat or something funny. (Think what doesn't decay into nothing, metals usually).
image
Don't include the firing pins, in fact, I would even say to subtype the guns to not start with any. This will drive players to the outpost so they can use their cool new loot.
image
who keeps sending these empty crates, give htem something, even if it's minor.
There should be some gas masks / emergency internals scattered around the place.

Seems mostly fine but will benefit from the detail pass.

**Comment by Zevotech** [comment]
Updated.

**Comment by goober3** [comment]
i'd like to see this TM'd for a round or two more before we merge this.

**Comment by Zevotech** [comment]
TM this sometime and ping me when it is so I can test it.

**Comment by Zevotech** [comment]
drafting until #2759 is done because i really want to add those new mines to this to make it higher threat.

**Comment by thgvr** [comment]
w aw aw aw awa w a wa wa

**Comment by Zevotech** [comment]
Done !!!!!!

**Review by goober3 — DISMISSED** [review]
it's time to pull this ruin out of forever purgatory.
e0a86ede937eb0c0d18cc36f071670ed
railings are notoriously difficult to climb over from the inside. add some gaps here so players can access this spot easily. do this for the other railing enclosures too.

8c172dcab35a24eb9142229dbde9ac32
this barricade feels odd. either make it cursed and place the barricades on top of each other, or have one or the other here.

0fc6a53f1155dae1cba29511dd632b9a
this room reminds me of home.

d8107d84d4d83c63f0a08bf609b6cb07
make this windoor a regular airlock or i'll sic thgvr on you.

this doesn't seem to have any major issues. i'll try and bribe someone to get this in the TM list tonight.

**Comment by Zevotech** [comment]
image
reviews addressed

**Comment by Zevotech** [comment]
yay yay yippee!! im free !!

**Pull request merged**
