### PR TITLE
Scav tweaks and fixes

### PR DESCRIPTION
**Pull request by TheLeopold**
## About The Pull Request
Assorted tweaks and fixes of Scav:
Added windoor to medbay.
Flipped some precharger's windoors.
Plating under prechargers now have air.
Replaced watertank with fueltank. It's a salvaging ship, not firefighting.
Unslipped the oil spill to save the soul of mapper from eternity in burning hell.
изображение

Repiped and rewired to move pipes and wires from under walls.
Pipes under walls made visible.
Waste injector starts enabled.
Added vent and scrubber to main room. It's too big for just one set.
изображение

Rearranged wallmounts and lights to not be on top of eachother. (Or at least reduce it)
Nudged wallclosets to +-28
Fixed wrong orientation of one fire alarm.
изображение

Ship faces east when flying. (Ignore the wallmounts on top eachother on this slightly outdated picture)
изображение

Replaced borg sechud (bruh) with sechud sunglasses.
Added blueprints. Removed cane.
изображение

Replaced table with ~~mixed~~ grey wardrobe. (Goat plush and disk still there)
изображение

Replaced iron bottles (iron is worthless, why was it even there?) with aluminum. (Goat plush is still there)
изображение

Thank you to [spockye](https://github.com/spockye) for helping with test.

## Why It's Good For The Game
Fixes is good, ~~slippery oil is a greatest sin against humanity~~, things inside walls is bad, things that make sense is good.

## Changelog

:cl:
add: Blueprints, windoor, fueltank, grey wardrobe, proper sechud to Scav
tweak: Scav piping, wiring, rotation
/:cl:

### CODE REVIEW

**Review by spockye — COMMENTED** [review]
image

could you switch the engine windoors to be like this?

image

fire alarm is the wrong way / could you move the lockers to +-28? / see if you can re-organize the wallframes to avoid having lights infront of wallframes if possible


Think you could get a locker of spare clothes in aswell?

**Review by spockye — APPROVED** [review]
probably cut down on the clothes a bit
other then that, good work!

**Comment by TheLeopold** [comment]
> probably cut down on the clothes a bit

well, the wardrobe is just a standart closet with its regular content with added goat plush and holodisk. Tweaking it would mean changing contents of all mixed wardrobe lockers. Or removing plush and disk.
I mean I could, but should I?
P.s. Maybe there's a better type of closet to place instead?

**Comment by Erikafox** [comment]
> > probably cut down on the clothes a bit
> 
> well, the wardrobe is just a standart closet with its regular content with added goat plush and holodisk. Tweaking it would mean changing contents of all mixed wardrobe lockers. Or removing plush and disk. I mean I could, but should I? P.s. Maybe there's a better type of closet to place instead?

you could just set the populate contents var to false and give them a more narrow selection of clothing

**Comment by TheLeopold** [comment]
I have no idea what clothing exactly to put there, because I'm the most uncreative person ever.
What if instead I just replace it with a clothing vendor?

**Comment by Erikafox** [comment]
> I have no idea what clothing exactly to put there, because I'm the most uncreative person ever. What if instead I just replace it with a clothing vendor?

That's actually worse. Don't do that
firefox_fSMhio548L

Also run your cables with the pipes so they don't intersect with atmos machinery (e.g. scrubbers)

And leave the slippery oil. It's hilarious.

**Comment by TheLeopold** [comment]
cable and closet is done
I'm not bringing slippery oil back, it's hilarious only for observers, never for players.

**Review by Erikafox — CHANGES_REQUESTED** [review]
clean up your changelog. It's much too long.
Also I liked the slippery oil put it back

**Comment by Sylphily** [comment]
just some notes here the table was in the room to make it feel more lived in, so if possible please keep it, and put the clothes in a crate, but if you don't that's fine, iron is actually important its gives blood back to spessmens, and axe the rolling table because i just was informed it causes SGTs, and add the oil back, i like it here in hell for eternity.

on a side note thank you for keeping things up-to date while i am not around!

**Comment by TheLeopold** [comment]
> iron is actually important its gives blood back to spessmens

Except it's common as dirt

**Comment by Apogee-dev** [comment]
Please use bare plating under windows, not floor tiles. Also, this ship needs at least one secondary airlock and subshuttle docking ports. Those latter two issues are both mapping standards so we can't really rubber stamp it without them.

**Comment by TheLeopold** [comment]
> subshuttle docking ports

What is a subshuttle docking port and where do I copy one from?



> secondary airlock

As soon as someone tells me where to fit it, because I have no idea.

**Comment by Erikafox** [comment]
scav doesn't need a subshuttle port. it's fairly small.

**Comment by Erikafox** [comment]
Resolve your merge conflict and address reviews

**Comment by Latentish** [comment]
Author has not responded in a month. Closing this pr.

**Pull request closed without merging**
