### PR TITLE
Adds crafting recipes for crates

### PR DESCRIPTION
**Pull request by goober3**
## About The Pull Request

Crates, internal crates, engineering crates, medical crates, science crates and hydroponics crates can be constructed with 2 metal

Freezers are constructed with 2 metal and 25 ice (freezers prevent organ decay! would feel Unbalanced to be able to construct them with just 2 metal, this should limit freezers to mostly Medical Ships, hopefully.)

## Why It's Good For The Game

Hauling around Loot and Cargo in a Large Metal Closet is inconvenient. And More Storage Variety.

## Changelog

:cl:
add: Metal crafting recipes for crates.
add: Freezers can be constructed with 25 ice and 2 metal.
/:cl:

### CODE REVIEW

**Comment by Valorium-RB** [comment]
Remind me if I'm wrong, but wouldn't this be a trivially easy way to generate money for ships with sell pads?

**Comment by goober3** [comment]
> Remind me if I'm wrong, but wouldn't this be a trivially easy way to generate money for ships with sell pads?

hold on. what?

> Valorium

just checked! empty crates can't be sold on selling pads, fortunately

**Comment by goober3** [comment]
> > Remind me if I'm wrong, but wouldn't this be a trivially easy way to generate money for ships with sell pads?
> 
> hold on. what?
> 
> > Valorium
> 
> just checked! empty crates can't be sold on selling pads, fortunately

when the response is. epci fail

**Comment by goober3** [comment]
> Remind me if I'm wrong, but wouldn't this be a trivially easy way to generate money for ships with sell pads?

just checked! empty crates can't be sold on selling pads, fortunately

**Comment by Zevotech** [comment]
yeah we dont even have the cargo shuttle here so making crate returns work like that is just stupid

**Pull request merged**
