### PR TITLE
Bunch of Statpanel updates from TG

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request

Ports a bunch of statpanel-related commits from TG. This will hopefully reduce the amount of GetFlatIcon calls done by alt+clicking nearby tiles, as well as just be a smoother experience overall with it. No real functional change beyond slowing down the stat panel update time.

## Why It's Good For The Game

Smoother experience with an important part of the game window

## Changelog

:cl: Couls, Kylerace, Magatsuchi, LemonInTheDark, Fikou, Mothblocks, Stylemistake, Mark Suckerberg
admin: Reduces MC tab update time, this can be adjusted with a preference in OOC settings
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
todo: find out why the orbit menu breaks randomly

**Comment by GenericDM** [comment]
> todo: find out why the orbit menu breaks randomly

It's specifically when the two buttons in the top right are hovered over.

**Comment by thgvr** [comment]
Other than the tgui bit all's fine here.

**Comment by MarkSuckerberg** [comment]
okay it should be fixed thanks to @thgvr's investigation. thanks again
merging this as soon as checks pass

**Pull request merged**
