### PR TITLE
Lizard Comedy is Now Legal on Shiptest

### PR DESCRIPTION
**Pull request by Geoengi**
## About The Pull Request

Ports the laughing emote sound for reptilians to our Sarathi from https://github.com/space-wizards/space-station-14.
## Why It's Good For The Game
Lizards sector-wide will no longer need to suffer in silence as their human/moth compatriots laugh at them.

## Changelog

:cl:
soundadd: A laughing sound for Sarathi.
/:cl:

### CODE REVIEW

**Review by thgvr — CHANGES_REQUESTED** [review]
You'll need to find a better sound for this, it's not very good

**Comment by Geoengi** [comment]
I'll have a look through freesound and hopefully find something.

**Comment by Pumpkinoe** [comment]
sounds like a fart

**Comment by thgvr** [comment]
Feel free to ask for a re open if you find a sound.

**Pull request closed without merging**
