### PR TITLE
adds the vampire cloak

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Adds the cape used by high ranking vampires from transylvania.

image

## Why It's Good For The Game

for your high rp dracula roleplay

## Changelog
:cl:
add: vampire cloak
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
https://www.youtube.com/watch?v=h3kkbZU-JtY

**Comment by AtlasRules** [comment]
i thought it was an actual vampire cloak

8/10 this is still good (I would still like an actual vampire cloak it is high level drip)

**Comment by Fikou** [comment]
so uh how do i get it

**Review by triplezeta — APPROVED** [review]
yeah pretty much

**Pull request merged**
