### PR TITLE
You can plunge geysers with a normal plunger and removes reinforced plungers

### PR DESCRIPTION
**Pull request by Gristlebee**
## About The Pull Request
You can plunger and activate geysers with a standard plunger. 

Also removes reinforced plungers since they don't do anything anymore. and adds a normal plunger to the Schmiedeberg in it's place.

## Why It's Good For The Game
The reinforced plunger was effectively made unobtainable with #2617 removing it from the vendor stock, aside from the one ship it's currently mapped on (Schmiedeberg), with no other available sources. Geysers are basically inaccessible to the vast majority of players as a result.

Even then, having the reinforced plunger only obtainable in the medical vendor gated it behind a small subset of ships, and meant it was almost never seen anyways.

This will make geysers usable again and the increased accessibility hopefully means it will actually be interacted with.

## Changelog

:cl:
tweak: Geysers can now be plunged with a normal plunger.
tweak: Schmiedeberg's reinforced plunger replaced with a normal plunger
del: Reinforced plungers
imagedel: Reinforced plunger sprites
/:cl:

### CODE REVIEW

**Comment by Anticept** [comment]
https://github.com/shiptest-ss13/Shiptest/blob/4dbc8f4c61149e9b5d6c908beb28be2041c96965/code/game/objects/structures/lavaland/geyser.dm#L61

This comment probably shouldn't be left to mentioning geysers either.

**Comment by Gristlebee** [comment]
> This comment probably shouldn't be left to mentioning geysers either.

Comment has been edited.

**Comment by MarkSuckerberg** [comment]
does reinforced do anything besides geysers?

if not maybe we should just fully remove reinforced plungers

**Comment by Gristlebee** [comment]
> does reinforced do anything besides geysers?
> 
> if not maybe we should just fully remove reinforced plungers

Yeah, their only purpose was for geysers. I can remove then.

**Comment by MarkSuckerberg** [comment]
awesome awesome :+1:

**Comment by Gristlebee** [comment]
Reinforced plungers have been obliterated and PR has been updated to reflect.

**Comment by thgvr** [comment]
ok

**Pull request merged**
