### PR TITLE
Removes space adaptation

### PR DESCRIPTION
**Pull request by thgvr**
Nobody tell me power creep isn't real and tangible

## About The Pull Request
Removes space adaptation

## Changelog

:cl:
del: Removes space adaptation.
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
make sure to include those utterly baffling pictures of the code so people understand what a nightmare this is.

**Comment by west3436** [comment]
Why are we concerned about powergaming in a non-competitive RP game? If people aren't RPing properly then this is an administrative issue rather than a code issue.

**Comment by thestripes** [comment]
I DEMAND!!! THAT "thgvr" to be DEMOTED!!! it was the best experience being neutral geneticists built into a ship's bathroom and being the ones who rescue you in a the same methods every time and everyone saying "what the fuck? are you a changeling?" then replying "we're the good geneticists we are the hero in this story"

**Comment by MarkSuckerberg** [comment]
it's not powergaming, it's completely negating two pretty big parts of the exploration environment with relatively little consequence

**Comment by goober3** [comment]
I DEMAND!!! THAT "thgvr" to be DEMOTED!!! it was the best experience being neutral geneticists built into a ship's bathroom and being the ones who rescue you in a the same methods every time and everyone saying "what the fuck? are you a changeling?" then replying "we're the good geneticists we are the hero in this story"

**Pull request merged**
