### PR TITLE
The Great Handgun Flattening

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

Rebalances handguns across most factions and improves access to ammunition for players with non-NT equipment.
Changes are as follows:

- Buffed 9mm to perform identically to .45 and 10mm
- Added extra ammunition types for 9mm, 10mm, and .45; all three now have ball, rubbershot, AP, HP, and Incendiary types
- Added new ammo box sprites for all variants of 9mm, 10mm, and .45
- Made rubber shotshells blue to match rubber handgun ammo
- Added basic 9mm, 10mm, and .45 ammo boxes to the autolathe as default blueprints
- Replaced .38 speedloaders on the autolathe with .38 ammo boxes
- Made buckshot and beanbag slugs unlocked on the autolathe by default
- Switched all other shotshells from emag to hack on the autolathe
- Made 9mm, 10mm, and .45 in basic and rubbershot available on the seclathe by default
- Added new research node for advanced ballistic ammunition, unlocked with ballistic weapons and advanced engineering research

New ammo box sprites pictured below.
ammoboxes

this WILL mess with the balance of other 9mm guns like the APS and SABR. They'll have to get a balance pass when we work on the SMGs as a whole.

## Why It's Good For The Game

the commander is no longer almost worthless and performs the same as the other basic handguns, basic ammunition access for everything but Commanders was a major problem, ammunition access for shotguns was a huge reason they've been on the weak side

## Changelog
:cl:
add: Added new ammunition variants for 9mm, 10mm, .45, and 5.56mm HITP caseless
add: Added ammunition for all basic faction handguns to the seclathe with a new research node
add: Basic handgun and shotgun ammunition for all basic faction handguns can now be printed at the autolathe
tweak: Replaced .38 speedloaders on the autolathe with ammo boxes
balance: Buffed 9mm to do identical damage to .45 and 10mm
balance: Removed AP factor from basic 5.56mmHITP Caseless ammo to make room for AP variant
balance: Buffed improvised shotgun shells to do the same maximum damage as buckshot. Accuracy and damage falloff still limit their real damage output.
imageadd: Added new ammo box sprites for all variants of 9mm, 10mm, .45, and 5.56mm HITP caseless
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
Wow. This is lame.

🔑

**Comment by Kapu1178** [comment]
:key:

**Comment by MarkSuckerberg** [comment]
Just saying something is lame doesn't help anything, please elaborate. Also what does :key: mean?

**Comment by francinum** [comment]
@MarkSuckerberg An at-length discussion was held in gen-dev, generally revolving around this being a bandaid instead of a proper solution.

**Comment by miniusAreas** [comment]
This is okay, and hits some great points, however I do have my criticisms (some of the same that Kapu and Fran vocalized earlier)

> Making 9mm, 10mm and .45 the same statistically makes little sense. At that rate, remove two and replace with the other, as there's no real point to having three different ammo calibers that do the exact same thing (other than variety, and that's lost greatly with this change)

> Access to shotgun shells is already easy. You simply hack the lathe and whammo, shotgun shells for everyone. It's an easy process that doesn't need simplification, if you can't hack a lathe then you *probably* shouldn't be printing lethals.

> Shotshell has been green till the end of time. This is less important and more personal preference, would rather slugs be blue over shotshell (due to the frequency they are used)

> Rather than having the alternate shotshells being hack (from emag), why not make them research? Things like slugs and dragonsbreath have long been very powerful.

That's the end of my feedback, but others may have stuff I didn't tack on.

**Comment by Apogee-dev** [comment]
> Making 9mm, 10mm and .45 the same statistically makes little sense. At that rate, remove two and replace with the other, as there's no real point to having three different ammo calibers that do the exact same thing (other than variety, and that's lost greatly with this change)

Yeah, during discussion in #gen-dev I ultimately decided that this is best as only a temporary measure. .45 and 10mm were already identical in damage and seem to be in a good spot (at least for PvE) on the stechkin and m1911, so buffing 9mm up to the same level is just a good first step to make the Commander not categorically worse than all of the other handguns. We can work on giving each cartridge a little bit of flavor later.

> Access to shotgun shells is already easy. You simply hack the lathe and whammo, shotgun shells for everyone. It's an easy process that doesn't need simplification, if you can't hack a lathe then you _probably_ shouldn't be printing lethals.
> Shotshell has been green till the end of time. This is less important and more personal preference, would rather slugs be blue over shotshell (due to the frequency they are used)
> Rather than having the alternate shotshells being hack (from emag), why not make them research? Things like slugs and dragonsbreath have long been very powerful.

Pretty much all of the shotshell changes were made on zeta's suggestion, though that was also before i'd decided to add the other ammo types to the seclathe. Now that you've mentioned it, I do think the advanced shotshell types should be moved to the seclathe, probably spread between medical weapons, advanced ballistics, and exotic ammo.

As for shotshell availability, you can't actually get lethal shotshells from a hacked autolathe at all. Every type of lethal shell, including buckshot, is locked behind the emag, so unless you're flying one of the two ships that have an emag the only shotgun shells you can get from an autolathe are beanbags and rubbershot, which are fairly useless on shiptest.

Anyway I'll move most of the shotgun shells to the seclathe. Buckshot and beanbags will remain available on the autolathe without hacking. If I'm going to let players print basic handgun ammo on the autolathe there's no real reason to lock buckshot behind the hackwall.

**Comment by Apogee-dev** [comment]
had to do something fucky because my branch was being haunted by the ghost of the scrapper-b and it was preventing me from merging anything. clearly it was WAY too fucky. i'm just gonna close and open a fresh one because this is a hot mess

**Pull request closed without merging**
