### PR TITLE
Secondary Mutcolours, Synthetics, and Lizard Prosthetics (Yes, they're synths.) (Sprites by Thgvr!)

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Currently a work-in-progress, so the in-game sprites don't yet reflect what the end result will look like. (That's why there's no screenshots.)

Sprites, once again, by @thgvr !

TODO:
- [x] Find a way to have synthetic replacements for lizard external organs (frills, horns, snout)
- [x] Add synth eyes
- [x] Add parts to the protolathe design
- ~~[ ] Split the synthetic choice into being organic, a synthetic, OR a FBP.~~ no
- ~~[ ] Find a way to re-add the BP_BLOCK_CHANGE_SPECIES flag on robotic bodyparts without breaking things~~ fuk u
- ~~[ ] Make the big list of bodypart vars a list, or perhaps a struct~~ some other time
- [x] Fix FBP brains spawning in their chest, should just be normal brains probably

## Why It's Good For The Game
More customisation, a little bit more uniqueness for prosthetics, and hopefully a structure for a few things including bi-tone lizards and co., as well as POSSIBLY maybe maybe maybe possibly maybe phorids. I don't know. Depends on a lot of things.

Also it gets rid of text2path() usages that include variables linked to player input which always scare me so that's good

## Changelog

:cl: Thgvr. Halcyon, Mark Suckerberg
add: Adds new preferences to make characters fully prosthetic or a FBP (only difference being brain type)
add: Lizard prosthetic/synthetic bodyparts with absolutely wonderful sprites by <b>Thgvr</b>! It's just a visual difference, and any species can use them, but they most resemble lizards, so.
add: Adds missing robotic vox bodyparts
tweak: All species have the ability to change their two mutcolours. I don't think this is really a loss at all.
/:cl:

### CODE REVIEW

**Review by thgvr — APPROVED** [review]
True. So true. Here's my stamp.

**Comment by MarkSuckerberg** [comment]
we're so fucking back

**Comment by quadbium** [comment]
Experienced an issue where when the MMI was removed from a Rachnid FBP, the MMI could not be reinserted into the FBP or an AI core.

**Comment by MarkSuckerberg** [comment]
just one more thing and they'll be even realer

**Comment by Anderson-Cooper** [comment]
> just one more thing and they'll be even realer

holy shit

**Comment by MarkSuckerberg** [comment]
ready

**Comment by thgvr** [comment]
its time. lgtm

**Pull request merged**
