### PR TITLE
General fauna sprite update

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request

This PR updates the sprites of most fauna.
Ports https://github.com/tgstation/tgstation/pull/74299
Ports https://github.com/tgstation/tgstation/pull/64174

## Why It's Good For The Game

Better sprites make me happy :)

## Changelog

:cl:
imageadd: New fauna sprites by Sheets
/:cl:

### CODE REVIEW

**Comment by Sun-Soaked** [comment]
these are mostly amazing. My one personal gripe is with the new legion, who look kinda yucky(and are from an [earlier pr](https://github.com/tgstation/tgstation/pull/64174) by a different person btw so you might wanna get credits for that)

**Comment by thgvr** [comment]
It might not be the best but it sure as hell is better than what's there.

**Review by rye-rice — APPROVED** [review]

**Comment by Sheits** [comment]
> [earlier pr](https://github.com/tgstation/tgstation/pull/64174) by a different person

(same person)

**Comment by Sun-Soaked** [comment]
> > [earlier pr](https://github.com/tgstation/tgstation/pull/64174) by a different person
> 
> (same person)

image

ough. :mothdonk:

**Comment by Mey-Ha-Zah** [comment]
Why do you think I hired them? I might be a spriter in my own regard, but talent respects talent.

**Comment by Sylphily** [comment]
Hey i noticed that this PR doesn't have a update for the saddle sprite for the goliths, might want to get that updated to avoid jenk

**Comment by Mey-Ha-Zah** [comment]
thats because I didn't update the saddle... AND it was always janky

**Pull request merged**
