### PR TITLE
Ports /TG/ autofire and organizes guns

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request
Ports https://github.com/tgstation/tgstation/pull/57084 and all prs fixing it
and https://github.com/tgstation/tgstation/pull/56846

Reverts https://github.com/Whitesands13/Whitesands/pull/187

While porting it, I realized we have a shit-ton of guns, and decided to might as well organize it while i'm at it.

There are 3 new subtypes:

/obj/item/gun/ballistic/automatic/smg
/obj/item/gun/ballistic/automatic/assualt
/obj/item/gun/ballistic/automatic/hmg

Theres no real differences between them, just organization.
many of the file changes are repaths

## Why It's Good For The Game

The tg system is way, way less bad than the system we had before, which acted like a autoclicker, a and overall feels much nicer.
This also organizes the guns, which makes it easier to add more in the future

Also from the original PR:
image

## Changelog
:cl:
add: Full-Automatic Gun component! Your L6 Saws and Laser Gatling Guns have it now.
add: The Tesla Cannon! A fully automatic replacement to the tesla revolver, it shoots balls of shock.
code: Makes the Laser Gatling Gun less bad.
balance: due to autofire, gun fire rates may be affected slightly.
fix: Roumain winchester inhands fixed
imageadd: Roumain winchester now has a back and suit sprite
refactor: Tons of guns were repathed.
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
I would say TM this, if the TM list wasnt filled already

**Comment by MarkSuckerberg** [comment]
dear god do i not want to review this

**Review by MarkSuckerberg — CHANGES_REQUESTED** [review]
Skimmed through it, only thing I noticed was that you should update the export map buildmode submode, like the other submodes were

**Comment by rye-rice** [comment]
> Skimmed through it, only thing I noticed was that you should update the export map buildmode submode, like the other submodes were

Alright, I added it to export map, my bad

**Comment by rye-rice** [comment]
conflicts fixed

**Review by MarkSuckerberg — APPROVED** [review]
Seems fine

**Comment by MarkSuckerberg** [comment]
yolo

**Comment by TheNeoGamer42** [comment]
my crimes are undone, and thus, the L666 has perished

**Pull request merged**
