### PR TITLE
NTSV Osprey

### PR DESCRIPTION
**Pull request by Apogee-dev**
you_are_so_fucking_long

## About The Pull Request
Adds the Osprey-class Exploration Vessel, a very large Nanotrasen ship with no specific focus and a substantial crew capacity of 18. Key features include:

- abundant construction space in the science department
- fully-functioning research department, with some basic setup required
- Space to build the engine of your dreams
- extremely good looks
- a working disposals system! wow!

## Why It's Good For The Game

s hip

## Changelog
:cl:
add: Added Osprey-class exploration vessel, a very large generalist ship
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
cool ship

**Comment by HighPrincessErinys** [comment]
love this aminal

(ospay)

**Comment by Nobelium-XVIII** [comment]
> a working disposals system! wow!

Some poor soul is definitely gonna space themselves on accident

**Comment by Apogee-dev** [comment]
> Some poor soul is definitely gonna space themselves on accident

it's a feature

**Comment by Mannybrado** [comment]
ftl

**Comment by TerryTehCoder** [comment]
Doesn't the antimatter engine run exclusively on Anti-matter cartridges? I thought they had to be ordered from Cargo.

**Comment by triplezeta** [comment]
yes but a single antimatter containment jar usually lasts long enough that it wont matter. at least on a regular statio

**Comment by ghost** [comment]
Very nice

**Comment by ValoTheValo** [comment]
The dong ship

**Comment by AtlasRules** [comment]
based FTL reference

**Comment by MarkSuckerberg** [comment]
augh why did it add all of those changes, my bad

**Pull request merged**
