### PR TITLE
Computer restyle?

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request
Repalletes/resprites the computers to look like the ones @Quantum-M did
Unfortunately Quantum's got denied for being too tall and looking out of place, but they looked great
So i'm redoing the normal computers in 32x32 to look like them
These should be compatable with old screen sprites, although i want to redo all of them

Clockwork computers from bee

Very little effort was put into the modular computers
## Why It's Good For The Game

image
sleepers when

## Changelog
:cl:
imageadd: Almost every single computer sprite has been redone
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
Gonna be honest, those consoles do not look aesthetically pleasing to me at all, and they seem like a hard downgrade in the overall quality.

**Comment by ZephyrTFA** [comment]
I'm not going to outright close this as there are still two others who can override my opinion but thats my opinion

**Comment by rye-rice** [comment]
It is done

**Comment by ValoTheValo** [comment]
Theese consoles look great

**Comment by Lloserhub** [comment]
I really love how those consoles look tbh

**Comment by MarkSuckerberg** [comment]
Personally, I really like these, but I'll put it up to an in-game poll while they're testmerged so I can get an accurate read of where everyone's thoughts are on these.

**Comment by rye-rice** [comment]
@MarkSuckerberg

**Comment by MarkSuckerberg** [comment]
@triplezeta

**Comment by rye-rice** [comment]
@triplezeta

**Review by triplezeta — APPROVED** [review]
ferret

**Pull request merged**
