### PR TITLE
[RTM?] hypothetically allows planets to spawn multiple ruins

### PR DESCRIPTION
**Pull request by Moltovz**
## About The Pull Request
Separates ruins into major and minor ones, maps **should** spawn minor ruin(s) and a major ruin. I haven't been able to test this apart from compiling.

## Why It's Good For The Game
1 planet != 1 ruin.

## Changelog
:cl:
tweak: Maps (should) spawn multiple ruins now: Moltov
/:cl:

### CODE REVIEW

**Comment by Moltovz** [comment]
oopsie fucked an area. I'll fix it

**Comment by Moltovz** [comment]
should be good (tm)

**Comment by PrefabQuasar** [comment]
this doesnt seem to be working in the current TM, still only one ruin to a planet as far as i've seen

**Comment by Moltovz** [comment]
> this doesnt seem to be working in the current TM, still only one ruin to a planet as far as i've seen

I'll look into it.

**Comment by Moltovz** [comment]
This code is ugly as fuck, going to close this PR and make a new one with cleaner code (that fucking works) later today

**Pull request closed without merging**
