### PR TITLE
Round Join Soul Removal

### PR DESCRIPTION
**Pull request by Skies-Of-Blue**
## About The Pull Request

Removes the "Welcome to TG Station" audio clip from the game. Forgot to do this when doing my first pass in https://github.com/shiptest-ss13/Shiptest/pull/2837. 
## Why It's Good For The Game

We aren't /tg/, and from time to time it's healthy to remove soul from the game.
## Changelog

:cl:
del: removes the roundjoin "welcome to /tg/ station" audio clip
/:cl:

### CODE REVIEW

**Comment by FalloutFalcon** [comment]
wonder if there is any better sound we could replace it with....

**Comment by Skies-Of-Blue** [comment]
> wonder if there is any better sound we could replace it with....

We already have the cryo pod hiss sfx when you join, the /tg/ welcome message just drowned it out previously.

**Comment by FalloutFalcon** [comment]
> > wonder if there is any better sound we could replace it with....
> 
> We already have the cryo pod his sfx when you join, the /tg/ welcome message just drowned it out previously.

yea already thought about it. This is fine

**Comment by thgvr** [comment]
Better CL please

**Comment by thgvr** [comment]
Actually I'll just edit it

**Pull request merged**
