### PR TITLE
Minor Vox Sprite Addition - Basic Vests, Helmets and Skirtlenecks

### PR DESCRIPTION
**Pull request by firebudgy**
## About The Pull Request

That fleeting wave of motivation strikes again! Few more sprites down, including Inteq Skirts and Basic Armor sprites!

Security officers look nice now, with accommodations for quills in the back of the helmet.
image
Skirtleneck, Standard
image
Skirtleneck, Corpsman
image

## Why It's Good For The Game

Additional uniform support, that's quite nice. Also, vests and helmets (universally used by many people) actually have solid sprites.

You can't tell me this isn't an objective improvement.
image

## Changelog

:cl: Cloudbreak
add: Skirtleneck support for Vox
add: Improved Vox sprites for basic armor vests and helmets
/:cl:

### CODE REVIEW

**Comment by Leon9621** [comment]
LET'S FUCKING GOOOOOOOOOO

**Comment by thgvr** [comment]
Helmet's quite strange, doesn't feel like a good fit for their head.

**Comment by firebudgy** [comment]
...looking at it now, yeah, I agree
I'll see about making some changes

**Comment by goober3** [comment]
helmet wit no brim

**Comment by firebudgy** [comment]
Maybe a little better now. Honestly I just don't want to see the abysmal armor sprites they've got right now anymore

**Comment by firebudgy** [comment]
Sorry, I'm going to just close this for now as I don't quite feel confident with what I have here and I want to work on my skills further before I make anything more.

I appreciate the advice and feedback given though, it has been a significant help. I'll hopefully be back with something of better quality.

**Pull request closed without merging**
