### PR TITLE
Wallets and Bank Cards

### PR DESCRIPTION
**Pull request by FalloutFalcon**
## About The Pull Request

Makes wallets part of the outfit shit and splits money behavior of access cards into bank cards

## Changelog

:cl:
add: Bank accounts are now handled through cash cards! You now spawn with a wallet to store your extra card!
/:cl:

### CODE REVIEW

**Comment by Anticept** [comment]
I'm taking a guess here, but loadouts are currently broken and not giving us our boxes with those items, and many of us had wallets selected or have wallets that come with loadouts.

**Comment by Anticept** [comment]
Can I suggest not removing wallets from prefs for now while this is in progress? That way if it's unTM'd, we'll still have wallets if we forget to check for them.

**Comment by FalloutFalcon** [comment]
> Can I suggest not removing wallets from prefs for now while this is in progress? That way if it's unTM'd, we'll still have wallets if we forget to check for them.

its not a big enough issue. it will probally be merged soon..

**Comment by Anticept** [comment]
There is one issue: access cards have to be removed and reinserted into the wallet to display the job title properly.

**Comment by Mirag1993** [comment]
need an update method in the combined access variable in the wallet

**Pull request merged**
