### PR TITLE
beagle mug

### PR DESCRIPTION
**Pull request by Jedi-Toothpaste**
## About The Pull Request
Adds the beagle mug, sprited by ryan180602

> from pull: https://github.com/Baystation12/Baystation12/pull/32695

image

## Why It's Good For The Game
The Atlas was looking very lonely so I gave them a mug to brighten their day.

## Changelog

:cl: rye-rice, Jedi Toothpaste
add: adds Beagle Mug
add: adds Beagle Mug to Atlas Class
/:cl:

### CODE REVIEW

**Comment by meemofcourse** [comment]
🥹

**Comment by FalloutFalcon** [comment]
SPEED MERGE!!! NOW!!!

**Comment by Sun-Soaked** [comment]
I love him

**Review by rye-rice — CHANGES_REQUESTED** [review]
If I don't make a better sprite in 24 hours treat this as an approval

**Comment by Jedi-Toothpaste** [comment]
> If I don't make a better sprite in 24 hours treat this as an approval

good because I forgot to ask the original spriter for permission; if they don't allow it (though I think they would) I will obliterate this from existence unless we get a new sprite

p.s. they have been asked NOW but they are asleep

**Comment by rye-rice** [comment]
> > If I don't make a better sprite in 24 hours treat this as an approval
> 
> good because I forgot to ask the original spriter for permission; if they don't allow it (though I think they would) I will obliterate this from existence unless we get a new sprite
> 
> p.s. they have been asked NOW but they are asleep

image
L

**Comment by Jedi-Toothpaste** [comment]
> > > If I don't make a better sprite in 24 hours treat this as an approval
> > 
> > 
> > good because I forgot to ask the original spriter for permission; if they don't allow it (though I think they would) I will obliterate this from existence unless we get a new sprite
> > p.s. they have been asked NOW but they are asleep
> 
> image L

image

**Review by rye-rice — APPROVED** [review]

**Pull request merged**
