### PR TITLE
Ship joining starts on locked

### PR DESCRIPTION
**Pull request by FalloutFalcon**
## About The Pull Request
Ship's start on locked instead of open
Idea from #772

## Why It's Good For The Game
No longer can an assistant join your ship faster then you can, rejoice in time to write your memo and change your ships name.

## Changelog

:cl:
fix: ships now start closed. shiptesters be writing there memos and ship names.
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
Not very intuitive, how about requesting a memo when you attempt to spawn a ship

**Comment by Sadhorizon** [comment]
> Not very intuitive

How about setting it to apply?
Less confusing for newer captains, but still prevents people from joining from second one.

**Comment by FalloutFalcon** [comment]
> Not very intuitive, how about requesting a memo when you attempt to spawn a ship

This was so simple. I can work on this at some point but this an improvement to having people bypass your application.

**Comment by Anticept** [comment]
Keep reminding players every few minutes their ship is locked until they open the ship control interface for the first time and set a memo. That should be good enough in case someone forgets or doesn't know.

**Pull request merged**
