### PR TITLE
Mashes several of the Whitesands Survivor Camp ruins into one extra large ruin

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Combines the whitesands surface camp adobe, farm, gunslingers, survivors, hunters and saloon into one massive, 59x59 ruin. Some various extra loot and changes have been made throughout, generally to improve the experience of digging through the trash for goodies. Changes the riot shotgun in the saloon to a double barrel shotgun. Also cleans up the various issues with the ruins, like walls under doors, or area passthroughs being used excessively over the outside of the ruins, resulting in them generating in the middle of mountains buried in the rock.

"Well, why didn't you add the drugstore?" The loot in it was too good. The stuff in there can really help a ship get on its feet, and I am not gonna deprive them of that just to shove it in an already packed massive ruin area. I'm not saying it doesn't need its own remap, just that it doesn't fit well with the other camps put into this ruin.

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
"a ruin that is tiny and sucks on purpose is still bad" and holy shit did most of the camps fit this criteria. Survivor, Gunslinger, and Hunter camp variants were the smallest ruins in the game next to the one that was just a single tumor, and constantly took up entire map generations just to be a massive dissapointment to any player that came across them. Or they would spawn in the middle of an acid lake. Either way this ruin is massive and should provide a breath of fresh air for scavengers and combat hungry miners alike.

## Pics or it Didn't Happen
image
Ingame, two pics due to view range not being large enough to get the full thing at a good quality.
image
image

## Changelog

:cl:
add: whitesands_surface_camp_combination, a survivor village comprised of smaller revamped whitesands camps all packaged in one ruin. can be found in the map catalogue.
del: whitesands_surface_camp adobe, farm, gunslingers, survivors, hunters and saloon, for being tiny ruins that suck.
/:cl:

### CODE REVIEW

**Comment by Erikafox** [comment]
I like this idea but feel like it could be implemented better, right now it looks like, well. 5 smaller ruins that happen to spawn together. 
Could you maybe weave them into a proper camp? 
paintdotnet_sEWPmE0HPs
I made this very bad drawing to communicate a visual of what I'd be looking for there.

**Comment by Zevotech** [comment]
simulated ruin greebling also cool idea but im never going to finish this if i work on it for more than one day so this is the final version. Paths between the structures were an idea I had but forgot about after finishing the turfs

**Comment by Valorium-RB** [comment]
Isn't the saloon already remapped, or there's an open PR to remap it? What's the status on that vis à vis this ruin?

**Comment by Zevotech** [comment]
> Isn't the saloon already remapped, or there's an open PR to remap it? What's the status on that vis à vis this ruin?

That PR hasn't been updated in 2 months and fails checks.

**Comment by goober3** [comment]
> > Isn't the saloon already remapped, or there's an open PR to remap it? What's the status on that vis à vis this ruin?
> 
> That PR hasn't been updated in 2 months and fails checks.

looks like the only thing that needs fixing is a single stacked chair. pinging bjarl now
@Bjarl FIX THIS!!!

**Comment by Erikafox** [comment]
I was already working on fixing it


Anyways. I think this greebling and the rework are different enough that we can have both in.

**Comment by Zevotech** [comment]
isnt there also a completely different saloon ruin on a rockplanet too?

**Comment by Erikafox** [comment]
yep

**Review by ZephyrTFA — APPROVED** [review]

**Comment by Erikafox** [comment]
merge conflict fix pls

**Comment by Zevotech** [comment]
that should do it

**Comment by Zevotech** [comment]
whoopsies! space tile under a door! time to fix it.

**Pull request merged**
