### PR TITLE
Han's Ruinable Ruin Pack

### PR DESCRIPTION
**Pull request by HanSolo1519**
## About The Pull Request

Adds 'Feral Doctor', a variation of the cat butcherer with the cat butchery-ness removed as a generic medical enemy simplemob

I legit just deleted the "cat tail/cat ears" surgery aspect, it can still pacify you (and you won't be attacked by it afterwards), also gave it it's own corpse with "Medical doctor" instead of "Cat Butcherer" as the ID

Adds 3 ruins

### Abandoned thruster factory
<details>
  <summary>Map image</summary>
   
  

</details>
A small thruster factory overtaken during the great rockplanet robo-revoultion, with the help of this facility, Robonistan can into space.
 
Contains loot of
- 5 ion thruster boards (2 of which are already built), 
- 3 engine precharger boards, 
- a single oil thruster board (no heater), 
- an autolathe, 
- an industrial welding tool, 
- a couple fuel tanks, 
- a plasma tank,
- and a fax machine _(fax machine my beloved, truly the most op item of the loot)_

Hostiles include a handful of belligerent robo bois, fitting the theme of the rock planet. (2 hostile floorbots, 3 ED-209s, a hostile minebot, 6 hostiles total)
Seemed like a unique idea with a manageable amount of enemies and a simple amount of loot, good ruin to be tackled by a party of 1-2 with weapons

This ruin seems pretty standard, I'm happy with it as it is.

### Crashed research dropship
<details>
  <summary>Big map image</summary>
  

</details>
A sizable campsite built around the reminants of a crashed transport ship carrying a scientist, an engineer, a group of security reinforcements and a shipment of botanical research equipment for their pre-detour destination. It seems the group has gone insane attempting to adapt to their hostile, alien surroundings

Contains loot of

- 2 thrusters+heaters
- foldable heavy machine gun
- full R&D setup
- full Hydroponics setup
- A small assortment of civilian grade weapons not in the hands of the very unfriendly security team (1 pump action shotgun, 1 Winchester .32 repeater, 2 double barrel shotguns, 1 improvised shotgun), 2 boxes of beanbag shells and 1 box of .32 bullets (the revolver in the bottom tent is non-functional)
- 2 gray slime extracts (no console, gotta do that stuff by hand)
- Research papers worth 2.5k points
- whatever typically comes in a normal bluespace pod, a deluxe bluespace pod, and a bar bluespace pod (notably some minor medical supplies and a shitton of booze).

Hostiles include (all have edited names, descs, and factions)

- 1 NT Assult officer (wields L6 saw)
- 2 Hermit hunters (wields polymer survival rifle)
- 3 russian troopers (wields shotguns/mosins)
- 6 NT officers (wielding pistols)
- 2 NT smg officers (self explanatory)
- 1 'Feral Doctor' (Uses saw and syringe gun, (unlike the cat butcherer, this one doesn't give you a tail))
- 1 ballistic turret

16 enemies in total

This ruin is supposed to act as a gatekeeped Kickstarter to any ships research, any ship can start hydroponics, research and xenobio, given they can get through a decently sized hoard of well-armed ranged infantry. Makes good use of the bluespace survival pods, since they weren't used in many ruins in place of sandstone or wood huts.

I'm unsure of the ballencing of this map, and I plan to return and overhaul the crash when I understand how shuttles within ruins work.

### Mineral Trading Colony
<details>
  <summary>Map image</summary>

</details>

An independent ore trading colony with a small tent-town of miners. The locals are neutral unless attacked, and the machines have been bolted to the ground _really tight this time_ to prevent ne'er-do-wells from snatching all the expensive equipment form under the very noses

Contains loot of
A medibot
Food and drink
A small selection of medical supplies (And by small I mean a single advanced first aid kit)
Some minor ores
A washer machine
A fax machine
An unstealable ORM, frontier mining vender, and some provision venders. Ships without a means of acquiring mining equipment can pop on by to acquire a mining scanner and kinetic accelerator, but cannot simply steal the machines for themselves.

The locals are set to retaliate, peaceful travelers don't need to fight them to come and trade, however we all know the npcs are going to get warcrimed anyway.

(not) Hostiles:
26 Whitesands survivors
9 Russian soldiers
1 Feral doctor
An actually hostile cat surgeon locked away in the vault.

## Why It's Good For The Game

Mapman good, 

Shiptesting is boring, long live the ruintest.

## Changelog
:cl:
add: added feral doctor simplemob (catless cat butcherer)
add: Insanely hard cultified mining outpost (dust planet)
add: Easy abandoned thruster factory (rock planet)
add: Medium-hard deranged research ship crashsite/camp (Ice planet)

remove: Insanely hard cultified mining outpost (dust planet)
add: non-hostile mineral traders (jungle planet)
/:cl:
## Todo:
- [x] Add more fluff to the camp and mining colony
- [x] Playtest
- [ ] Playtest again
- [ ] actually compile the map this time
- [x] Balance it all
- [ ] Try making the crashed ship a ship

### CODE REVIEW

**Comment by HanSolo1519** [comment]
I _finally_ got back around to this project and jesus h christ having "what mobs look cool" as a primary focus is apparently bad map design, the cult mining outpost is an interesting concept but it's going to take ages of balancing in order to fix it, I'm shelving the map for sometime in the future. 
 
 In it's place I'm adding a 'Mineral trading outpost' to the jungle planet (it's basically an earthlike, close enough), a small mining town populated with _non hostile_ retaliate npcs and equipped with some non-deconstructable mining equipment. Ships without an orm and mining vender themselves can swing on by to trade, but can't take the machines with them. I was forced to go with non-deconstructable machines since the retaliate npcs apparently don't mind you stealing all their fancy-schmancy equipment from right under their noses, but don't worry, there's still provisions, a medibot, and minor supplies you can steal from the miner's homes.
 
 <details>
  <summary>Map image</summary>
  




</details>

Playtesting the crash camp turned out to be pretty okay, a single dude with a set of gamer armor and a laser gun can easily go postal around the entire ruin if he's careful. I did tone down the number of smg officers anyway. The sensible tactic is to have a friend, edge in, agro one or two guys, and run to a defendable position to pick them off with ranged weapons. Also added some fluff, like graves and littered empty bottles since it is a crazed militia ransacking a pod-bar. A pulse carbine was added to the bar-lab to give a fitting reward for out-gunning a group of gunmen.

<details>
  <summary>map image</summary>
  
  



</details>
 
 fixed the configs, I think. 
 
 Feel free to fuss at me if my mineral trader solution is just too scuffed for our use, or anything else you'll like changed.

**Comment by Zevotech** [comment]
tip for the cult mining outpost, theres a cult mob called a proteon that is fairly weak and could replace a lot of the cult mobs you have in there. a juggernaut would be fine as a final boss of the ruin as long as its fairly centralized and manageable enough to beat.

**Comment by HanSolo1519** [comment]
> tip for the cult mining outpost, theres a cult mob called a proteon that is fairly weak and could replace a lot of the cult mobs you have in there. a juggernaut would be fine as a final boss of the ruin as long as its fairly centralized and manageable enough to beat.

During the little I did playtest it before scrapping the idea, the proteons actually turned out to be very balanced for spamable swarming goons. They have low enough health to be killed with a buckshot or two and their attack pattern is to run up and melee you before running back, never overwhelming you despite you fighting 5 at once. 

My issue with it was the beefier enemy density (3 ranged and 2 melee enemies in a single room) and liberal use of blood-drunk miners (megafauna themselves) and juggernaut. The cult templar was also a tad much (2k health, spawns demons, and can see you through walls, thus removing the intended progression through the ruin). The enemies ended up exiting the ruin to go hunt the nearby local fauna to extinction.

If I do get around to redoing the enemies in the map, it'd probably be 90% proteons and wraiths instead of cult constructs + ranged humanoids + plasma skeletons + blood drunk miners

**Comment by Latentish** [comment]
I'd like to see an update on this PR, and I'd like to see some pictures of the ruins.

**Comment by HanSolo1519** [comment]
> I'd like to see an update on this PR, and I'd like to see some pictures of the ruins.

Sorry, other things popped up in my life, I'm unsure if I'll get around to playtesting and balancing these.

I included map images in the "Map Image" spoilers as to not take up room, though here they are

Thruster factory
image

Crash camp
image


Friendly mining/trading colony
image

**Comment by Latentish** [comment]
I like them so far. Can't wait to see this finished.

**Pull request closed without merging**
