### PR TITLE
[IDB IGNORE] The End. (Deatomizes everything)

### PR DESCRIPTION
**Pull request by Sun-Soaked**
## About The Pull Request
Moves all content previously in the whitesands folder to appropriate locations in our main directories.
Discards some unused content.

## Why It's Good For The Game

bossalute

You have reached the end. 

Go back to [the beginning](https://shiptest.net/wiki/Nyaru_Hopeless).

## Changelog

:cl:
soundadd: all /whitesands sounds moved to our main sound directory.
imageadd: all /whitesands images moved to our main image directory.
code: all /whitesands directory content moved or removed. Pathing appropriately altered.
/:cl:

### CODE REVIEW

**Comment by Sun-Soaked** [comment]
image
okay buddy

**Comment by Sylphily** [comment]
just some minor changes

**Comment by Yellow-Mushroom** [comment]
A hero

**Comment by triplezeta** [comment]
shut up IDB2

**Comment by triplezeta** [comment]
yeet

**Pull request merged**
