### PR TITLE
The Pillbottle, and Pill Things.

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request

dreamseeker_mMxUmMmRjx
image

Adds the Pillbottle-Class Locust Carrier, a ship that hauls around 8 Pills. It is intended as an adminspawn ship mainly for stresstesting subshuttles (and being asked for). It's fairly resource starved, and has frankly terrible engines. The expectation is that it will utilize its 8 pods to gather resources and return to the mothership. Or fly off and die horribly. It has slots for 10 prisoners (that's like 3 pills and one third of a 4th). 
This pr also edits the pill, blackpill, and superpill to be subshuttles (compatible with the subshuttle system) by cutting out most of their equipment, converting their maps to shuttle datums, and giving them docking ports. 

- [ ] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
Subshuttles are fucking awesome.

## Changelog

:cl:
add: Pillbottle-Class Locust Carrier has been added. These cramped vessels act as a mothership to a swarm of Pill-class Torture 
add: The pill and all variants are now subshuttles.
add: Bad Ion Engines, for ships that need to go slow.
/:cl:

### CODE REVIEW

**Comment by Erikafox** [comment]
Drafted for Subshuttles (#1573) but otherwise ready.

**Comment by Apogee-dev** [comment]
The pill subshuttles should use the Pill namelist if possible

**Comment by Erikafox** [comment]
I had issues getting the datums to pull from namelists, otherwise they'd already be doing it.

**Review by spockye — COMMENTED** [review]
image

cable fuckery

image

missing pipe

this is an affront to god


Scream at me if my version is out of date

**Comment by Erikafox** [comment]
>this is an affront to god

intended behavior

**Comment by meemofcourse** [comment]
drugs

**Review by spockye — APPROVED** [review]
it pains me to say this, but its... its ready for merging

**Pull request merged**
