### PR TITLE
Fixes Nomadcrash and the areas of Budgetcuts and Miningexpedition

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
https://github.com/shiptest-ss13/Shiptest/pull/2384
Fixes the areas on nomadcrash and the two other rockplanet ruins that were given areas but never had them applied.
Fixes the enemy selection on nomadcrash to better fit rockplanets mob pool.
Repaths the turfs used in nomadcrash to be properly subtyped from their actual turfs and use rockplanet atmos.

StrongDMM-2023-12-08 02 56 19
StrongDMM-2023-12-08 03 00 46

## Why It's Good For The Game
Who merged this without checking it on a testmerge thoroughly? I just want to talk.
Anyways ruins should probably use the correct areas and not have really fucky tiles.

## Changelog

:cl:
fix: rockplanet_nomadcrash now uses the correct areas.
fix: rockplanet_nomadcrash now uses correctly pathed turfs that dont break when spawned.
fix: rockplanet_budgetcuts and rockplanet_miningexpedition now use their newly added respective areas instead of ruin/powered.
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
Tm...........

**Comment by Latentish** [comment]
Please link the original pr in your description if you wouldn't mind.

**Comment by Zevotech** [comment]
> Please link the original pr in your description if you wouldn't mind.

(bites you) Okay............

**Comment by Latentish** [comment]
Could you also please provide screenshots of the area'ing of these ruins in sdmm?

**Comment by Zevotech** [comment]
> Could you also please provide screenshots of the area'ing of these ruins in sdmm?

(bites you again) Hi hiii haiiii :3

**Review by Erikafox — CHANGES_REQUESTED** [review]
image
while you're touching this can you use proper areas so i can have my fuckin weather

**Comment by Zevotech** [comment]
Updated, turfs repathed so its mergable.

**Comment by Zevotech** [comment]
Should be fixed. Please TM.

**Pull request merged**
