### PR TITLE
New Ship - Masinyane

### PR DESCRIPTION
**Pull request by Vexylius**
## About The Pull Request
It's like Rimworld Rich Explorer scenario, but instead of starting tech on start you get a possibility of having two engineer-friends!

Also, it's fast.

image

## Why It's Good For The Game
New ships to test for Shiptest

## Changelog
:cl:
add: Masinyane-Class Ship
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
why is it barely not symmetrical it triggers me

**Comment by ilikesaying** [comment]
why 9 engines

**Comment by Vexylius** [comment]
> why 9 engines

speed

**Comment by Apogee-dev** [comment]
The ship needs a holopad and the ship's wall buttons have incorrect dirs, be sure to adjust those as you would other wallmounts like fire alarms

**Comment by Vexylius** [comment]
uh-oh

**Comment by rye-rice** [comment]
Files changed 781

**Comment by Sylphily** [comment]
Some one did a fucky wucky

**Review by ZephyrTFA — APPROVED** [review]
LGTM, let's speed merge this one

**Comment by AtlasRules** [comment]
BUBBLE THREE
image

**Comment by Apogee-dev** [comment]
This ship still needs a holopad, apparently.

**Comment by Calyxman** [comment]
No holopad, can you add one in?

**Comment by Vexylius** [comment]
Fineeee, added holopad

**Comment by Latentish** [comment]
I feel like this ship and the Scav serve very similar functions. What makes this one special?

**Comment by Vexylius** [comment]
> I feel like this ship and the Scav serve very similar functions. What makes this one special?

Surviving on this one is harder, having a crew of three but usually being alone, no medics or medical equipment except for one medkit. It's not really built for doing anything too dangerous, but everything is a possibility. Thinking this ship would really shine when/if the outposts are added as it can really easily move around the overmap with it's impressive base ~9spms of thrust per click.
I think it's also good for interactions between ships, like being a vessel carrying customers for boyardee or patients for Li Teguai.

**Pull request merged**
