### PR TITLE
Puts the black duster in loadout.

### PR DESCRIPTION
**Pull request by Sadhorizon**
## About The Pull Request
- Removes armor from it. It's been used on the riggs, but like, just wear a vest pls.
- Repaths it to be a subtype of normal duster.
- Changes it's desc.
- Moves it's sprites from armor.dmi to suits.dmi.
- In loadout, replaces the leather overcoat with it (overcoat sprite sucks ass rn, and both have the same vibe).

## Why It's Good For The Game
We are lacking a good-looking black coat in the loadout.
The duster's sprite is NOT armored, thereby it shouldn't be either.

## Changelog

:cl:
add: Added the black duster to the loadout.
del: Removed black duster's armor.
del: Removed the leather overcoat from the loadout.
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
It’s a job item, keep it out of loadouts. If you want a better looking black coat in loadouts, just resprite the existing overcoat.

**Comment by Sadhorizon** [comment]
Meh. Was worth a try.

**Comment by Sadhorizon** [comment]
Okay I may have given up a bit too fast. Uh, left an argument on discord, apogee.

**Comment by Sadhorizon** [comment]
Okay, I'm done.

**Comment by Apogee-dev** [comment]
Just noting down what we’d discussed in discord, I’ll make a visually armored sprite for the current black duster and switch its current sprite to the in-game-but-looks-bad black overcoat in the same PR.

**Pull request closed without merging**
