### PR TITLE
Adds a new ruin, the abandoned ice planet maze. 

### PR DESCRIPTION
**Pull request by Draggeru**
## About The Pull Request

Adds a new ice planet ruin, a maze! 

mazefinal

I really for the life of me don't know what else to say. It's just a maze.
It has some niche not used at all xenobio extracts, such as a stabilized gold. It has completely(?) useless cult artifacts, a medibeam gun, and a syndicate borg medical model.

I guess this is cool??

shaw

## Why It's Good For The Game
More ruins mean=good! It has at LEAST two brain cells worth of effort put in.( This is a joke don't hit me.)

## Changelog
:cl:
add: Adds a new ruin to ice planets, it's a maze! No, you can't cheat and go through the walls. (I'm not sorry)
:cl:

### CODE REVIEW

**Comment by Draggeru** [comment]
Whoops I fucked shit up on vscode, to no suprise.

**Comment by Draggeru** [comment]
I have significantly unfucked everything.

**Comment by Draggeru** [comment]
It appears vscode fucked up so badly that the map for my map pr is not present.

**Comment by Latentish** [comment]
This isn't a bad starting place, but it's rather bland to start. If you expanded the maze to take up most of the space in this ruin, that'd do it a lot of justice.

- Try to remove as many 1wide hallways as possible, as they're annoying.
- Make sure the walls are invincible or packed with countermeasures for any instance of wallbreaking (the corporate_rejects map shows how I went about doing that). I think invincible walls would fit this better though.
- Make sure to clutter up all the hallways so they aren't so bland. Just a plain maze isn't super fun.
- Add a teleport or some way to get out from the maze quickly. Indestructible blast doors with a button at the center room could work for this as well.
- Remember that people can sometimes find ways to teleport across a 1wide wall.
- Add trash, decals, mobs, detailing.
- Try expanding the maze into a shape that isn't a square. Squarish is still fine.

**Pull request closed without merging**
