### PR TITLE
Restores space parallax to its former whimsical glory.

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
Reverts https://github.com/tgstation/tgstation/pull/36137
Before
image
After
image

## Changelog

:cl:
imageadd: Restored space parallax to its former whimsical glory.
/:cl:

### CODE REVIEW

**Review by Zevotech — APPROVED** [review]

**Comment by Zevotech** [comment]
Im Zevo Tech and I Approve This Message

**Comment by tmtmtl30** [comment]
reverts https://github.com/tgstation/tgstation/pull/36137

**Review by goober3 — APPROVED** [review]
i'm Goblin and i approve this message.

**Review by MarkSuckerberg — APPROVED** [review]
I'm mark and I

**Review by Imaginos16 — APPROVED** [review]
YES!

**Review by rye-rice — APPROVED** [review]
ye

**Pull request merged**
