### PR TITLE
Adds a new ruin, The Cave Crew!

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request

- [ ] get the subshuttle to work!

This PR adds a new jungle ruin called "Cave Crew". This is a hidden frontiersmen base, located within a cave. 
It also contains its very own subshuttle "Gut Combat Freighter"! it is, as the name says, a Armed freighter used by the local frontiersmen to carry out raids, and supplies

it also creates a "neutered" subtype of the frontiersmen
This type does NOT drop weapons, making the ruin a bit less of a lootbonanza

<details>
<summary>Images</summary>

Ruin
image

Subshuttle named "gut"
image

image

image

image

image

image

image

image

image

</details>

---

-THREATS-
6x turrets
2x pistol frontiersmen
1x shotgun frontiersmen
1x MINIGUN frontiersmen
1x frontiersmen officer
1x AK frontiersmen
1x Armoured mosin frontiersmen
1x mosin frontiersmen
1x venus trap
3x carps

-MISC LOOT-
3x abandoned crates
 t2 parts
2000 credits
fax machine
camera bug
different computers
kitchen supplies
Donk vendor
misc engineering supplies
1x frontiersmen hardsuit
misc frontiersmen armour
misc ammo
-MAIN LOOT-
5 telecrystals 
EMP kit
C4 satchel
2x Frag grenade
1x emp grenade
1x nagat revolver
1x combat shotgun
1x energy sword
1x AKS-74U
Misc mech weapons
-ULTRA LOOT-
Kiwi the puppy
image

"lore tidbit"
While the Minutemen wiped out most of the frontiersmen, small remnants can still be found throughout the sector. This right here is one of those remnants. The cave is a resting place for a group of raiders, calling themselves the "CaveCrew". They have remained mostly silent after the war, only partaking in the occasional plundering, and trading with other pirates. 

## Changelog

:cl:
add: Added a new jungle ruin "jungle_cavecrew"
add: Added a new subshuttle "frontiersmen_gut"
add: Added a neutered subtype of all frontiersmen (doesn't drop guns)
add: Added new areas for the ruin
add: Added a subtype of the heavy frontiersmen corpse that lacks the minigun pack
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
I dunno about map quality, but I really like how the outdoorsy areas blend in with the artificial structures, crates and fences. It's something you rarely see in SS13, even on planetary maps, most infrastructure is covered by walls.

**Review by Erikafox — APPROVED** [review]
I was happy with this but we need to make sure the subshuttle works

**Review by Latentish — COMMENTED** [review]
Get the subshuttle to work and we can merge this.

**Comment by spockye** [comment]
attempting to fix. 
. 
.
.
gwa

**Review by goober3 — CHANGES_REQUESTED** [review]
image
unrotated door

image
frontiersman simple mobs still spawn on the gut subshuttle map. if this subshuttle is to be used for events, unfaction the turrets and remove the mobs, please. also, remember to add a light switch and window shutters.

image
replace this tiny fan with a holofield.

image
unwired holofield on the subshuttle.

image
this Doggy will be murdered by turrets & pirates. give it the frontiersman faction.

please reduce the number of areas here -- four or five should do.

**Review by goober3 — CHANGES_REQUESTED** [review]
image
the gut still needs a light switch!! also, please transfer your changes here to the version in cave crew. thank you

image
there are still far too many areas here -- please reduce the areas under /cavecrew/ to ~4 to 5. indoor / cave areas should be planetoid/cave, or weather will occur inside them.

everything else looks good. thank you!!

**Review by goober3 — APPROVED** [review]

**Pull request merged**
