### PR TITLE
Food Expansion

### PR DESCRIPTION
**Pull request by MrSamu99**
## About The Pull Request

Ports ~~racial foods from TG. Tasty (not for humans)~~ more foods from TG. Tasty (for humans too)

Loredevs of all countries, unite!
https://hackmd.io/7-3btO7hTu-BS14ruc4T2w

## Why It's Good For The Game

More foods - more fun

## Changelog

:cl:
add: Added lizard foods and drinks
add: Added mothic foods and drinks
tweak: tweaked some foodtypes
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
doesn't most of the stuff in here heavily reference TG's lore which doesn't apply at all to shiptest, like, Tizira doesn't exist, and moths are actually just some human genemodded offshoot that popped up one day last I read through the lore here

**Comment by MrSamu99** [comment]
Descriptions and names can be changed though, but last time I've seen lore it wasn't that big to make a giant problem

**Comment by TheNeoGamer42** [comment]
I mean, I'm pretty sure there's atleast vague efforts being done to make the lore more proper ingame so adding a bunch of stuff that breaks that lore is probably bad. I'd atleast try to talk to them maybe, pretty sure cole does Sarathi lore so theyd probably help a little with changing stuff for lizard food. idfk who does moth foods and if they even should have wacky separate foods due to being just being heavily modified humans lorewise

**Comment by PigeonLord** [comment]
"//We don't have fishing and fish meat"
We do, can't you get fish meat from fish on Beach Planets?

**Comment by MrSamu99** [comment]
> "//We don't have fishing and fish meat" We do, can't you get fish meat from fish on Beach Planets?

It requires fish from fishing, and those fish we have contains only carp meat. But okay, i just forgot about it

**Comment by PigeonLord** [comment]
"You know, a lot of those Mothic recipes are quite similar to Italian Cooking"
"Oh ho ho, nooo, patented Mothic Cuisine, oooold family recipes!"
"For Mothic Pesto."
"Yes!"
"Yeah, so you call it Mothic Pesto despite the fact it's identical to Pesto Genovese"

**Comment by MrSamu99** [comment]
The main reason why I did it was the rootbread. Moffic food was taken to not add food for only 1 race
> "Pesto Genovese"

You have me an idea to make a referense to genessee. "Pesto Genessee"

**Comment by Zevotech** [comment]
> The main reason why I did it was the rootbread. Moffic food was taken to not add food for only 1 race
> 
> > "Pesto Genovese"
> 
> You have me an idea to make a referense to genessee. "Pesto Genessee"

just add baldium! (USER WAS REPOBANNED FOR THIS POST)

**Comment by Apogee-dev** [comment]
Not lore-friendly, obviously, but as mentioned on the discord lore channel we should focus on culture, not species. Mood buffs based on species are pretty meh considering any species could technically come from any culture, and only a couple (IPC, Elzuose) have unique needs that normal food doesn't satisfy. Some species, notably moths since they're included in this PR, don't even _have_ a culture where they're predominant.

**Comment by MrSamu99** [comment]
This PR starting to smell

**Comment by AverageUser67** [comment]
I think the things like baked cheese should be ported at least
also pesto genessee containing baldium is an award winning idea

**Comment by MrSamu99** [comment]
I'll reopen this PR when I understand how to remake conflicting items

**Comment by MrSamu99** [comment]
I close this PR because I won't have time for it for at least 3 months 
image-13

**Pull request closed without merging**
