### PR TITLE
Glowing power!!!

### PR DESCRIPTION
**Pull request by Sylphily**
## About The Pull Request
 adds the glowshrooms to the pool of plants that can over take trays

## Why It's Good For The Game

The ability to get glowshrooms, whether it be for makeshift lighting or for ghetto chems, or for botany

## Changelog
:cl:
add: glow shrooms can now be grown from the random weeds on soil and the like!!
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
this decreases the starthistle chance :sob:

**Comment by Sylphily** [comment]
> this decreases the starthistle chance 😭

only by a little bit, also what do star thistles even do?

**Comment by triplezeta** [comment]
i mean you're reducing it from a 3/18 chance to drop to a 1/18 chance to drop, and it doesn't do much by itself but it's a precursor plant to Galaxythistle, which contains a chemical that can revive livers

**Comment by Sylphily** [comment]
> i mean you're reducing it from a 3/18 chance to drop to a 1/18 chance to drop, and it doesn't do much by itself but it's a precursor plant to Galaxythistle, which contains a chemical that can revive livers

that sounds pretty big give me a few seconds to fix that

**Comment by Sylphily** [comment]
Now, to wait for a merge, hopefully tonight!

**Pull request merged**
