### PR TITLE
Moves the Brazillab ruin to Sandplanet and fixes the Trabuco's inhand sprites

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Remaps the Brazillab ruin to fit on whitesands, because on iceplanet all of the hermits in it would die to the cold and the ruin looked ugly there anyways.
Also fixes the trabuco's inhands that were apparently broken.
Ruin has been given a serious touchup, but otherwise remains similar to its iceplanet counterpart.

image

<details>
<summary>SDMM Pictures</summary>

StrongDMM-2024-11-16 00 30 10

StrongDMM-2024-11-16 00 30 13

</details>

## Why It's Good For The Game
This ruin always was a better fit for sandplanet, and now has had a serious touch-up so it better fits with our increasing quality standards.

## Changelog

:cl:
add: Remapped and moved the Brazillab ruin to Sandplanet.
fix: Fixed the Trabuco's inhand sprites.
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
@Zevotech finish this

**Comment by Zevotech** [comment]
> @Zevotech finish this

yes captain

**Review by Gristlebee — CHANGES_REQUESTED** [review]
Good removal of old cruft from the ruin.

Though there is an issue of these barricades here exposing all the turfs inside to planetary atmos. You're either gonna need to seal that up or change everything inside to planetary subtypes.
image

**Review by Gristlebee — DISMISSED** [review]
All the tiles you varedited to have whitesand atmos turned the entire ruin into vacuum and massively lagged out the game.

Please subtype the tiles properly.

**Comment by Zevotech** [comment]
> All the tiles you varedited to have whitesand atmos turned the entire ruin into vacuum and massively lagged out the game.

Fun fact! The original ruin had them all varedited to be icemoon atmos. Oh well.

**Comment by Gristlebee** [comment]
> > All the tiles you varedited to have whitesand atmos turned the entire ruin into vacuum and massively lagged out the game.
> 
> Fun fact! The original ruin had them all varedited to be icemoon atmos. Oh well.

Waugh

**Comment by Zevotech** [comment]
Fixed turfs and changed loot slightly. 
Medical locker no longer populates on init.
Added a few spare attachments to the shooting range section, and put a guaranteed hermit SKM in the gun locker and two magazines for it in the ammo locker.
Further changes pending feedback from players.

**Comment by Zevotech** [comment]
Semi final changes done. pending new review.

**Pull request merged**
