### PR TITLE
Ruin map template tags

### PR DESCRIPTION
**Pull request by FalloutFalcon**
## About The Pull Request
turns all the stuff in map_catalogue.txt into proper defines that can be used soon

## Why It's Good For The Game
this should come in useful for spawning ruins of certain qualities, scanning a planet for information about them and other use cases.

## Changelog

:cl:
code: added ruin tags to ruin map templates to be used soon for stuff.
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
@shiptest-ss13/maptainers

**Review by meemofcourse — APPROVED** [review]
i would wait on @Latentish but this seems ok

**Comment by FalloutFalcon** [comment]
This is gonna need a quick follow up pr prob done by a maptainer since some stuff grew slightly out of date since this pr has been open for a while.
The new maps will need to be converted to proper tags

**Comment by rye-rice** [comment]
@Latentish

**Review by Latentish — APPROVED** [review]
Looks good to me.

**Pull request merged**
