### PR TITLE
Justice for the Justice helmet

### PR DESCRIPTION
**Pull request by BarteG44**
## About The Pull Request
fixes the justice helmet crashing the server with the magic of ctrl+c ctrl+v from beestation

the cause of the crash:
image

## Why It's Good For The Game
usually items crashing the server with one click is not something you'd want

## Changelog

:cl:
fix: fixed the justice helmet crashing the game upon use
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
oh my GOD is that really how it used to work??? no wonder this thing crashed the server

**Comment by BarteG44** [comment]
don't merge it yet. i don't know if the sound works or not. last TM only the lights worked

**Comment by BarteG44** [comment]
dammit...
well if it doesn't work the second fix PR is on you

**Comment by MarkSuckerberg** [comment]
GWAAA

**Pull request merged**
