### PR TITLE
The SUNS Panacea-class Infirm Vessel

### PR DESCRIPTION
**Pull request by Latentish**
## About The Pull Request
Replaces the Aegis-class with the Panacea-class Infirm Vessel. A generalist with a central theme of roleplaying around inpatients.
image
image
panaceaclass
(in game screenshot is 2 changes out of date.)

## Why It's Good For The Game
Replaces an old ship and uses our new assets.

## Changelog

:cl:
add: Added the Panacea-class
del: Removed the Aegis-class
/:cl:

### CODE REVIEW

**Comment by Imaginos16** [comment]
I would affectionately chew the port nacelles, you cooked so goddamn hard girl.

**Comment by Latentish** [comment]
image
image
image

**Review by meemofcourse — CHANGES_REQUESTED** [review]
imagen
i fail to see why the panacea needs a fire axe
imagen
i think you would benefit from replacing the base airlocks with /public airlocks
imagen
please use the syndicate factional fax subtype
imagen
minor to medium gripe but it sounds awful to have to go through the context menu every single time due to the sheer amount of bottles present. give them ghettochem tools or find some other way to lower the amount of bottles in one place
imagen
there are window firelock subtypes you can use for windows. i'm not sure if standard firelocks close when there's a window on their tile
imagen
imagen
you do not need Three Laundry Carts.
imagen
i understand using the SUNS content but i think it would make sense to issue standard breath masks in emergency lockers instead of half face masks
imagen
i think this is a ridiculous amount of engineering gear

**Comment by Latentish** [comment]
> review from meem

heavily nerfed the engi gear
image

I am going to argue that these bottles aren't really a problem because I gave them a chembag which will make sorting through them much less of a headache than rightclick context menuing it.
image

In the event of a window breaking, yes these will activate. That is the only time they need to activate.
Having firelocks in this fashion means you can use them as a psuedo airlock, which is far more useful than standard window firelocks which are just emergency atmos blockers (you have shutters already) 
image

**Comment by Redrover1760** [comment]
If you give this ship a chemfridge board that'd be really helpful in keeping things sorted.

**Comment by Zevotech** [comment]
image
accidental recharger on the floor

**Review by meemofcourse — APPROVED** [review]
this ship smells of wet metal

**Pull request merged**
