### PR TITLE
Removes the .45-70 from the Nemo

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

Replaces the Nemo's .45-70 revolver with the new Contender single-shot .45-70 rifle (sprites courtesy of @TypeVar ). Also removes the third surplus rifle from the captain's locker.

## Why It's Good For The Game

Brings the nemo more in line with other ships in firepower and removes a weapon that was never intended to be directly given to ships in the first place. (as a side note, no ship should have a hunting revolver at all. if one does give me a heads up and i'll replace it.)

## Changelog
:cl:
add: Added the Contender single-shot .45-70 rifle
balance: Replaced Nemo's .45-70 revolver with a Contender
/:cl:

### CODE REVIEW

**Comment by TypeVar** [comment]
I put the hunting revolver there cause I wanted something effective against fauna with a theme for hunting big game, kinda overlooked just how broken it is in PVP. Is there any other weapon other than the colt revolver that you could replace it with? Something like a hunting rifle or some elephant gun or similar? The .38 revolver is fair, but I don't think very appropriate for hunting

**Comment by thgvr** [comment]
.38 revolver has a disk for hunting rounds. Li Tieguai uses it as a good method of killing fauna.

**Comment by TypeVar** [comment]
Hmmm. I think it would be more thematically appropriate to instead ditch the revolver and have just the surplus rifle (or something similar) in the locker with hunting ammo for it. Hey, maybe even toss in a hunting ammo disk for it, cause the nemo was intended to be a fauna hunting ship

**Comment by TypeVar** [comment]
> 

This is the main reason why I gave the miners crushers instead of PKAs because the PKAs are way too effective at PVP

**Comment by Apogee-dev** [comment]
> Hmmm. I think it would be more thematically appropriate to instead ditch the revolver and have just the surplus rifle (or something similar) in the locker with hunting ammo for it. Hey, maybe even toss in a hunting ammo disk for it, cause the nemo was intended to be a fauna hunting ship

There aren't any items in-game that would fit the "big game" theme without being terrifyingly good against humans as well. Hunting ammo only exists in .38, and it's a bit of a kludge to make up for the fact that we never fully untangled lavaland balancing. The .38 revolver with hunting ammo is perfect from a mechanical standpoint, even if thematically it's a bit meh, so it's going to have to remain for now. Maybe if something suitable is added in the future it can replace the revolver. Thanks for reminding me about the hunting ammo disk, though, I had forgotten to add that.

**Comment by TypeVar** [comment]
> > Hmmm. I think it would be more thematically appropriate to instead ditch the revolver and have just the surplus rifle (or something similar) in the locker with hunting ammo for it. Hey, maybe even toss in a hunting ammo disk for it, cause the nemo was intended to be a fauna hunting ship
> 
> There aren't any items in-game that would fit the "big game" theme without being terrifyingly good against humans as well. Hunting ammo only exists in .38, and it's a bit of a kludge to make up for the fact that we never fully untangled lavaland balancing. The .38 revolver with hunting ammo is perfect from a mechanical standpoint, even if thematically it's a bit meh, so it's going to have to remain for now. Maybe if something suitable is added in the future it can replace the revolver. Thanks for reminding me about the hunting ammo disk, though, I had forgotten to add that.

Makes sense. Maybe if something in the future comes up like and elephant gun, then perhaps it can be changed. But for now a revolver with 38 hunting rounds makes sense

**Comment by TypeVar** [comment]
Actually, wouldn't a 38 lever action make more sense than a revolver for hunting?

**Comment by Apogee-dev** [comment]
> Actually, wouldn't a 38 lever action make more sense than a revolver for hunting?

probably, but it makes less sense as a sidearm for the captain and the ship already has better long guns (surplus rifles)

**Comment by challade** [comment]
Everyone remember the Pubby? It was a nice little compact ship with an old style mining redemption machine that people would hop on and create mining colonies with the unlimited shelter pods that invited its colonizers to stay and the ship to fly out into space and bring in points/supplies and create a nice unique little mining colony world with its own economy and community that worked without research and development which invited outsiders to bring in what it lacked. It also lacked medical supplies until you got points to use its medipens, causing brain damage or, if it was here today, would need external medical surgery tools. You had to be creative and come up with clever unique solutions to problems that the Pubby had. This made it fun to play it, as opposed to playing a ship with everything on it. 

People rarely played the pubby then. And, when it was played, it was entertaining at least if people knew what they were doing. Once that old style mining redemption machine got removed and no way to get research to make a cargo board to buy more supplies, no one played it because there was nothing advantageous about it. So, the devs decided that to fix it they would make it bigger and give them a cargo lathe.

End result? No one plays Pubby, because they can just play solgov Cricket or some other ship with actual research and weaponry.

Another ship, sterilized. Another ship unplayed.

And now, a hunting ship that deals with dangerous space fauna is getting its big Magnum removed because of PVP. And, despite admins advocating for Roleplay over PVP, you're taking away a reasonable weapon that a fauna hunter would have in limited quantities to deal with giant space monsters. The gun is a point and click magnum, that could easily miss, and has a limited firing quantity because the bullets are indeed limited. There's no way to get ammo for this with research.... or anything really. And, even with it being as powerful as it is, you still need to use a substantial amount of its ammo to kill a person or a fauna, meaning you're going to go through the ammo pretty quickly, especially if you miss.

 And, even with that, let's not forget that there is a common weapon known as the shotgun who's buckshot is a net for anyone to get hit with and has near unlimited supply if you have an autolathe. So, why remove it? Roleplay is already encouraged by admins, and PVP looked down upon. So why remove the fauna hunting/research vessel's unique gun. Just to take away its flavor? To sterilize it for.... who? PVPers? Then remove grenades, and infinite ammo, and infinite... guns too, since that's what research provides with the lathes. And, they're all more effective than the magnum. 

I've been playing ss13 for almost 5 years, and a pattern I always notice is that roleplay correlates with gimmicks and fun. And, when you remove those gimmicks, and force people to interact with each other in a sterile environment, nobody wants to play with each other anymore. It's already happening, most ships on Ship test are either barren or have cliques that hunker down and avoid contact with other ships. 

It's no wonder people had fun with the pill ship, if it was just you and another, you could just hop onto a pill ship and play, and it got removed because... there were too many pill ships because... most people wanted to play by themselves? This got solved by removing pill ship, and everyone just hopping onto big ships by themselves anyways.

And now... because the unique fauna hunting vessel has a fauna hunting gun, its getting removed because for some reason a big gun for big fauna is for some reason effective on smaller intelligent fauna if it hits. Is it not logical that a hunting ship with weapons for big fauna would also be dangerous to people? People that can create grenades that activate on word commands and blow up a quarter of your ship? Or, worse, have a shotgun that they have to aim in the general direction of you to hit you. Is a big magnum with a limited amount of bullets really that scary compared to the arsenal any other player can create within minutes?

God forbid I shoot someone with a hunting mangum when they could easily have a grenade spear/shotgun/grenade/MECH and it work.

**Comment by triplezeta** [comment]
hiding that for being the longest comment ive ever seen good god

**Comment by TallDeekus** [comment]
Wew, perhaps keep constructive criticism shorter then that.

**Comment by TypeVar** [comment]
> 

I would argue the surplus rifles aren't better than the Winchester. Winchester is easier to reload and fires just as fast. I get that it isn't a sidearm, but I can't really think of anything that would be appropriate for hunting that is a sidearm other than the hunting revolver or something that looks like this
image

Actually, if I were to make something like this, would it be a good alternative to the hunting revolver?

**Comment by TypeVar** [comment]
also yes, the Contender can actually be chambered in .38 irl

**Comment by TypeVar** [comment]
I sprited and got the Contender to work properly. Should I send you the files for it or make a separate PR for it?

**Comment by TypeVar** [comment]
oh shit this is still open. I was actually thinking maybe you could move either the bow or the harpoon gun into the RDs weapon locker. The curator won't be using both the bow and the harpoon gun, and having a weapon with reusable ammunition can be nice to have when your main gun has very limited ammo

**Comment by TypeVar** [comment]
😢

**Comment by ZephyrTFA** [comment]
I removed the Stale label, but never actually reopened this. Coping

**Comment by TypeVar** [comment]
what's the merge conflict about?

**Pull request merged**
