### PR TITLE
Surplus Ammo & A Bunch of Ammo Balance Tweaks

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

Changes a variety of elements of ammunition access for regular ships, and makes some balance tweaks to ammo.

- New ammo variety: Surplus Ammo, printable at autolathes. Available for handguns, surplus ammo is lower-quality than ammunition made on specialized or commercial machinery, and does less damage. Replaces standard ammo on the autolathe.
- Standard handgun ammo is now only printable on protolathes with access to security blueprints, namely omnilathes and security lathes.
- Buckshot has also been moved from the autolathe to security protolathes. Civilian ships have to buy buckshot or use improv shells.
- Standard .38 ammo has been slightly nerfed to 20 damage, identical to surplus ammunition.
- Beanbag shotshells now have a green hull, to differentiate them from rubbershot (which now uses blue).

Many of these changes will be slightly alleviated for normal crews by making regular ammunition available on the outpost console, but that should be a separate PR.

TODO:

- Finalize surplus & .38 ammo damage (may require live testing)

## Changelog
:cl:
add: Added low-grade "surplus" ammunition for handguns to autolathes
balance: Moved standard ammo & buckshot from autolathes to sec protolathes
balance: Reduced .38 damage to match surplus ammo
imageadd: New icons for surplus ammo & beanbag shells
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
I was planning to do something similar to this if I could ever get off my ass and do something, so it's nice to see someone has decided it was also a good idea. Kinda makes sense to have there be something like ammo quality differences, in this specific setting.

**Comment by zombiemimic** [comment]
is there going to be any more surplus ammo you're planning on adding?

**Comment by Apogee-dev** [comment]
> is there going to be any more surplus ammo you're planning on adding?

No, just handgun ammo. If I expand ammo availability for other ballistics it probably won't be in the form of printable surplus but through trading instead.

**Review by MarkSuckerberg — APPROVED** [review]

**Comment by MarkSuckerberg** [comment]
@triplezeta

**Review by triplezeta — APPROVED** [review]
k

**Pull request merged**
