### PR TITLE
Adds Quirk species-locks, adds on_addiction_remove, properly handles quirk conflicts

### PR DESCRIPTION
**Pull request by Ms-Mee**
## About The Pull Request
This PR adds quirk species-locks, fixes the fact that quirk conflicts weren't functionally acccounted for in most cases(only one check during spawn for non-existant quirks being ran, as well as a blocking for acquiring the conflicting quirks but nothing for when you already had them), adds on_addiction_remove, makes quirk traits a list instead of one singular, adds a list of quirk cooldowns for possible quirk_specific abilites.

## Why It's Good For The Game
Species-locked quirks are cool, conflicts not being accounted for is bad, on_addiction_remove and quirk_cooldowns allow more room for new systems, and are necessary for the vampire quirk I will be reworking.

## Changelog

:cl:
add: Added quirk species-locks.
add: Added a proc for effects that occur when an addiction is removed.
add: Added a list for quirk cooldowns.
add: Added a sortList datum to sort quirks based on value and then alphabetical order.
fix: A few mood quirks are properly flagged as mood quirks now.
del: Navigationally challenged no longer has a treshold to forcefully be assigned to new players.
refactor: Refactored quirk conflicts, changed quirk_traits to a list, last step in quirk subsystem initialization is making all current clients have their quirklist checked for conflicts.
del: IPCs, Phorids and Jellypeople can no longer have Blood Deficiency, as the quirk does nothing to them.
/:cl:

### CODE REVIEW

**Comment by Ms-Mee** [comment]
There'll probably some problem somewhere but everything I could think of I've tested already

**Comment by Ms-Mee** [comment]
Wait a second this still fails to address mutually exclusive quirks doesn't it? Even if it doesn't I should still make it standard with the other conflicts and make them clearly unpickable instead of a not usually visible chat message since at least on my screen the character customization and quirk tabs cover the chat and makes it confusing

**Comment by Ms-Mee** [comment]
Should now be done I hope.

**Comment by Ms-Mee** [comment]
I have been tricked and backstabbed and killed and murdered

**Comment by Ms-Mee** [comment]
:SamsungSob:

**Comment by ZephyrTFA** [comment]
Sorry that was me, managed to mess up the check_regex file on master somehow and that was me fixing it

**Comment by Ms-Mee** [comment]
I know, it caused the first merge conflict as well

**Comment by Ms-Mee** [comment]
This friday and saturday I'll make some minor changes to improve the balance equalizer and I could lock the completely non-functional quirks such as blood deficiency on ipcs, jellypeople and I think phorids?
Other than that maybe I should make a visible notification for when your quirks get forcefully changed in prefs or otherwise make it a more noticeable change just in case.

**Comment by Ms-Mee** [comment]
Why me :SamSungSob:

**Comment by Ms-Mee** [comment]
I'll fix this soon alongside reestructuring a few things slightly.

**Comment by Ms-Mee** [comment]
Crashing for some reason which I'll figure out tomorrow, tired.

**Comment by Ms-Mee** [comment]
It's working again, now it takes the highest value quirks out in alphabetical order, I'll make it do the first quirk it finds that is worth as much or less than the balance difference, and if all quirks are worth more than the balance value, it'll take out the last one in the list which will be the last alphabetically among the ones of the lowest value in the list

**Comment by Ms-Mee** [comment]
Got a few runtimes that happen every now and then for whatever reason even when I localhost master but everything seems to have worked fine the 4 times I tested everything.

**Comment by Ms-Mee** [comment]
When the recently merged PR makes it break on deploy attempt and makes me question reality as I thought it somehow compiled over 40 times without issues while skipping something the many times I tested stuff

**Pull request merged**
