### PR TITLE
New Lavaland Ruin: The Nanotrasen Genetics Research Facility

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Adds the abandoned Nanotrasen Genetics Research Facility, a facility on lavaland dedicated to genetic and slime extract related experiments away from the prying eyes of the general public. My hope for this ruin is to act as a Nanotrasen counterpart to the Syndicate bioweapons facility on lavaland, allowing players from either faction to loot either facility.

The facility is equipped with a Password Locked Door separating the reception and subject area from the storage and research area, which can only be unlocked with a code found somewhere within the ruin (hint hint).

Threats:
7x Hungry Grey Slimes (3 of which are in locked rooms)
2x Powered Turrets (On stun by default, mainly to act as a stealth puzzle for players to dodge past)

Items of Value: 
3x Green Slime Extract
1x Dark Blue Slime Extract
1x Healing Extract
1x Invigorating Extract
4x Cryoxadone Beakers
2x Cryogenic Cell setup (If they even bother to deconstruct it and take it)
1x Medical Sleeper
5x RTG Generator
3x Fashionable Ties
1120 Credits
As well as whatever various plushies, junk and syringes you manage to loot from the storage and research area.

image

## Why It's Good For The Game
I was asked to make new, unique lavaland ruins due to most of them being kind of shit and soon to be deprecated. This will be the first of many new ruins for lavaland.
This is also the first non-deprecated ruin to use the password locked door, something I've been wanting to use.

## Changelog

:cl:
add: Nanotrasen Genetic Research Facility, a new Lavaland ruin
add: codelab.dm containing assets for codelab.dmm
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
<br />

**Review by Erikafox — CHANGES_REQUESTED** [review]
This ruin suffers heavily from being a giant white block and also from Dungeon Design Syndrome. 
You're gonna need to put some work in, but I'll get some immediate pointers.
StrongDMM_o9k0U3SS4w
a functioning facility on a world with a hostile atmosphere needs to have a cycling airlock for the front
image
Don't do this. I'm gonna make a pr so you don't Have to do this
StrongDMM_B0BClyXc82
This is literally a giant white floor. On white walls.
Dirt decals alone won't suffice for design, I recommend creating a pattern/method of using flooring and decals together, and being consistent with it. Look at the Ascie for an example of a more medical decal set.
StrongDMM_Yz1Gxy17Gz
White room with semi-random monotiles. Barely any decalling
Also we don't need n2o to use our cryopods. That's a tg thing.
StrongDMM_r2U6VvFYO5
If you're going to use papers to this level, you either need to;
Make it so you can pick them up and get paper scraps
Make it so you can clean them
Make it so their integrity isn't 300. 
StrongDMM_EVOPbAhTIa
This is a bit better, but it's still not great. Keep in mind that your hungry slimes may die before anyone gets in there. 
StrongDMM_szYalqOjzF
The cargo bay should probably not have to be accessed from the lobby. Think of a supermarket. Do trucks park at the front of a supermarket and just unload? No. They have a spot to park, and it's usually right into the storage. 
I would add an obvious landing pad, give it some lights, and put some turrets set to lethal out front.
I would also consider some perimeter defense turrets. A fence will not stop a Goliath
The maint is... nonsensical. There should not be a Thicket Of Grilles stopping you from getting to a machine that you need to refuel for power. If it was RTGs, and all preset, I could understand.
And there's no atmos. What happens when the Hostile Atmosphere Outside inevitably gets inside??

**Comment by Erikafox** [comment]
Also the other maptainers have Thoughts on the genetics gear, but I'll let them air it themselves.

**Comment by Zevotech** [comment]
Stop Fucking Cancelling Checks You Creature Of Code

**Comment by Zevotech** [comment]
changes addressed

**Comment by PrefabQuasar** [comment]
this looks much improved, i appreciate the effort youve put into addressing review, and i love the password puzzle element, once bjarl is satisfied, i'd love to see it TM'd

**Comment by Erikafox** [comment]
( I am satisfied with the improvements and will be tming it tomorrow )

**Review by spockye — DISMISSED** [review]
image

image

piping errors

image

a wild cable appears!

image

i'd recommend adding some damaged wood states around.

the ruin might gain from having some more threats. perhaps a couple traps around?

**Comment by spockye** [comment]
image
forgot these

**Review by Latentish — DISMISSED** [review]
It seems like you've gotten rid of the genetics equipment. I honestly would worry if I saw genetics equipment basically anywhere, given how gamer it tends to be. So that's good.
I would recommend reconsidering your slime placements. For example you have a slime in two of these sleeper rooms, but none in the cryo tube rooms, which are some of the best loot in the place.
This also just needs more decal work.
It's looking good so far keep it up!

**Comment by Zevotech** [comment]
changes addressed, updating pics now

**Review by Erikafox — CHANGES_REQUESTED** [review]
image
Subtype the pavement so it starts with proper lighting and airmix

The turrets need a turret controller set to lethal, use the /lethal subtype. 

The turrets also need to be repathed.
image
No diag wall there
image
Give this research paper a special name

The facility should have a blackbox somewhere
dreamseeker_FvlQfzmDSJ
This room is very empty.

**Comment by Zevotech** [comment]
> The turrets need a turret controller set to lethal, use the /lethal subtype.
> 
> The turrets also need to be repathed. 
was told to make the turrets their own type and all that

**Comment by Erikafox** [comment]
they're inheriting from a subtype that doesn't exist right now.

**Comment by Zevotech** [comment]
> they're inheriting from a subtype that doesn't exist right now.

weeping

**Comment by Zevotech** [comment]
updated

**Review by Erikafox — APPROVED** [review]

**Review by spockye — APPROVED** [review]

**Comment by Zevotech** [comment]
@MarkSuckerberg ITS IN LETS GO AHAHAHAHAHA!

**Pull request merged**
