### PR TITLE
Adds a ghettochem stable plasma recipe

### PR DESCRIPTION
**Pull request by Cyaneer**
## About The Pull Request

New chem recipe:
5u stable plasma from 5u plasma, 5u water and 1u stabilizing agent.

## Why It's Good For The Game

More ghettochem more good.

## Changelog
:cl:
add: Added Stable Plasma recipe for ghettochem mains.
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
By any chance do you think you can make the stablzing agent a catylst like it is in other recipies?

**Comment by Cyaneer** [comment]
> By any chance do you think you can make the stablzing agent a catylst like it is in other recipies?

Alright fair, I checked the discord and Tetra only wanted a buffer chem, give me a second.

**Comment by Cyaneer** [comment]
> 

Actually nevermind, my brainlet can't figure out how to not make recipes conflict, so stabilizer will once again become a reagent. Plasma is quite active, after all.

**Comment by Cyaneer** [comment]
Remaking as not a draft, no more merges and unmerges

**Comment by PrefabQuasar** [comment]
theres already a way to stabilize plasma, should just be micro-manipulator on a beaker of plasma

**Pull request closed without merging**
