### PR TITLE
[IDB IGNORE] refresh:clip part 2: removes the vela

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

(sorry, no quirky drawing this time, have random sketch)

image

This removes the vela blah blah balh

vela was a good ship but its better to start from the cutting room floor and all of that

it wasn't even spawnable anyways i will be amazed if people get upset

## Why It's Good For The Game

this pr also has some extremely minor sprite tweaks; apogee said they wanted to replace all the cmm shipsp with clip ones, meem had a cool one cooked

## Changelog

:cl:
del: Vela-class, is this even player facing?

add: Variants of clip outfits
del: reinforced trapper hat
add: resprites the indie sec suit and it's clip variant
tweak: Some extremely minor code tweaks
add: adds support to make adding species variants easier, jesus christ it was bad before.
add: snouted variant support for sprites

/:cl:

### CODE REVIEW

**Comment by Martinpachu** [comment]
BUT ITS THE ONLY CMM SHIP WITH AN AI.. where will i get robot now?

**Comment by rye-rice** [comment]
i will make clip ipc chasis. how about that

**Comment by Martinpachu** [comment]
YEAH!!!!!!!!

**Review by Imaginos16 — APPROVED** [review]
# I NEED TO KILL

**Pull request merged**
