### PR TITLE
Asclepius Class Hospital Ship

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request
image

image

image
(flooring and decal)

This PR adds a new Minutemen ship, The Asclepius-Class Hospital Ship. 
This ship mostly orbits around planets currently being contested by Xenohazards, Taking care of the wounded and infected, as well as dissecting, and researching fallen Xenos. 

While most of the larger Skirmishes under the Minutemen territory may be over, BARD still remains vigilant, patrolling the sector, in search of further hidden Biohazards
Crew:
1x Captain
3x Medical Doctor
2x Combat Medic
1x Minutemen Officer
3x Volunteers
1x Engineering Technician
1x Chemical Scientist

It also creates a subtype of "patterned" floor tiles, using the pre-existing "dirty_steel" tile
it ALSO adds a new Decal, The minutemen Logo. Credits to the wonderful spriter, Piper#6996

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
while we do have the Corvus and Carina, I still feel like a faction as in-depth as the Minutemen deserves more ships than just that. The Asclepius' existence in-game serves as a Reminder that BARD exists. 

## Changelog

:cl:
add: Adds the Asclepius Class
add: Adds the dirty _:blushed:_ tile
/:cl:

### CODE REVIEW

**Comment by spockye** [comment]
wh- how in gods name did I change the pubby and minerals

**Comment by spockye** [comment]
image

image

i swear to god, i will gutpunch you

**Comment by Erikafox** [comment]
If you're going to use starting markers, please include one for the captain
Airlocks need names across the entire ship

This holopad will block a room off when in use, I recommend moving it down and to the right, or finding a completely different spot for it.
StrongDMM_xdoVk5oeNF

Window needs a shutter here.
StrongDMM_pmVdp47ill

Why is there an igniter here?
StrongDMM_QXbABMdIdQ
The poster also in the room straight up says it's offensive to the faction, may not be the best lore fit there.
dreamseeker_qkbWIIPC3j
This room needs another light I'd say, maybe consider moving the chemmaster into the center isle too.
dreamseeker_Zl3b4kKYAv
Poster again
StrongDMM_VKk1fZ2PXO
Penguin event in progress here. Only mildly related.
dreamseeker_kXCsWw5K6K
Try using normal windows instead of spawners here. I have a hypothesis about spacewind and window spawners.
StrongDMM_eUAz68wcru
The jukebox in the corner feels out of place.
StrongDMM_XnH5csyxkA
Could you put these in the security room? Maybe give the sec office it's own set of shutters too?

There's not nearly enough crew space for the crew (minus cadets) of 9
StrongDMM_m5C70oJfgI
I'd put the circuits in a crate in cargo instead of having them be in a locker. Not everyone checks emergency lockers for research equipment.
StrongDMM_7eCia80ojx
Push the docking port out a tile please.
StrongDMM_DpMmPWXoKs


Overall, not a huge fan of the ship. The Minutemen don't have a medical ship but this feels like it's about on par with the indie ships for medical, without leaning far enough into the xenofauna research niche. The layout of medical also bugs me, it's a bit more spread out than I'd like. Tabbing in the Aegis, Box, and Li Tieg to try and help explain why I don't like it, but I might not be able to get my point across, sorry about that.
Equipment wise, I'd say the Li-Tieg is most similar, but the Box has a more spread out layout, like your ship (It also looks like it needs a rework A constant in all of these is keeping the entire area sorta... Visible, when you're in the medical area, you're in the medical area. The backend stuff is past that. Here it's fairly scattered, with walking space more comparable to what I'd consider an actual hospital, but it's not used space, and equipment ends up being shoved into the corners instead (Thermomachines, the IV beds, and the stasis beds.) This boofs the sightlines up a bit more than I'd like.  What I'd like to see is the empty space turned into a triage area, with the stasis beds, recovery beds, and anything else that's misc put in, the two surgical tables given their own dedicated cubbies/rooms, and the morgue turned into more of a side attraction than it currently is. 
Alternatively, lean harder into xenofauna research. I just feel like it's too scattered and that hurts the ship.

I'm gonna see if I can get another maptainer to tab in on this relatively soon, otherwise fix the immediate issues and we can see about a TM

**Comment by Erikafox** [comment]
Also please atomize the pubby fix.

**Comment by Erikafox** [comment]
Unfortunately, we are not interested in this ship, while unique to the faction, the medsci niche is already very crowded.
Next time, please run your idea by a maptainer, so you don't end up mapping an entire ship and then having the PR closed.

**Comment by Latentish** [comment]
This was closed rather quickly, I think it's better to reopen it and give it more of a chance if OP wants it.
You have a 4-2 ratio of maptainers disliking - liking it. You need to bring that up. You can do so by first addressing the before mentioned review. I'll add an additional review for the more nebulous issues.

**Review by Latentish — CHANGES_REQUESTED** [review]
First possible issue is that the overall shape is strange. The interior is also very  complicated and could end up confusing to walk through. That I'd like to test however, as you give a lot of alternative doors to rooms.

Your hallways could use more decal work..

Your medbay has a rather strange setup of fridges that could use some rearranging.

The storage room just seems out of place.  It feels like that's something that should be attached to the crewside of the ship, rather than the waiting room.

**Comment by Erikafox** [comment]
StrongDMM_418rcHhd2D
Theres. No dividers on the toilets
StrongDMM_0FVcEPDu8P
You'll probably want another one or two vents in here. Just one with such a large room will make it kinda slow.

More review when the checks pass and the code compiles. I need to look at a few things in game.

**Comment by Erikafox** [comment]
dreamseeker_LwMF6Wduow
The jukebox is still in a weird spot. I'd put it unanchored in the cargo bay or just let the crew settle for a boombox
dreamseeker_fL7V2GHMAH
The Keycard Auth still does things. You don't need to remove it but you should be aware.

**Comment by ghost** [comment]
The xeno embryo spawns completely functional and ready to insert into a host, maybe it should be decayed and require repair to make it harder to use?

**Review by Erikafox — CHANGES_REQUESTED** [review]
This needs to not have an implantable xeno embryo.

**Comment by Latentish** [comment]
> This needs to not have an implantable xeno embryo.

🚢

**Comment by Latentish** [comment]
I like this ship a lot. Remove the captain's sabre and advanced surgery tool set from the captain's locker and we can merge this.

**Comment by Derpguy3** [comment]
A few things I had noticed while testing out the ship
- The captain has a nagant revolver, but they cannot restock their ammo once they use it all. Might need the design disk for the ammo box.
- The airlock seems to drain the air pressure tank really quickly after a few uses.

Besides those minor things, I'm finding myself to be a fan of the ship!

**Comment by Erikafox** [comment]
I can't find the checkmark button so this is a checkmark comment

**Review by Erikafox — APPROVED** [review]

**Comment by Latentish** [comment]
I'd prefer you give them ammo for the nagant revolver rather than a design disk. So it's limited in use for how powerful it is.

**Comment by Latentish** [comment]
merging

**Review by Latentish — APPROVED** [review]

**Pull request merged**
