### PR TITLE
The Vela-Class, a Gold Robotics/Mining ship

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
The Vela-Class Hazardous Extraction Vessel is a mining hull currently in use by the Galactic Optimum Labor Division for orbital mining operations in the frontier, designed to leverage mechs to rapidly mine out rich ore sites, and then return to offload their ore. The Vessel's interior is highly malleable, although is currently configured in a more unofficial set up, with the fore being dedicated to the crew, and the aft including both a small science lab and vault.. This specific example hasn't seen the best of upkeep practices, but is still a massive vessel capable of projecting soft power into any sector it's deployed in.

Other examples of this hull exchange the hangar pod for something else, such as troop transports, manufacturing plants, gas harvesting machines, or external cargo bays. Once a Vela is out of dock it is unlikely to stay stock for long.

This Vela has a crew compliment of 19 crew, divided thus:
1 Captain
1 Supply Officer
1 GOLD Delegate
2 Flight Controllers, for coordinating operations of the miners.
4 Pilots
1 Mechanic
2 Engineers
2 Minutemen, assigned to guard the vessel
and 5 cadets, officially doing whatever.

Power is supplied by a quad-Pacman assembly, feeding two SMESes. The air harvester on the starboard could allow for on the go refueling, and allows the ship to endure sustained operations or resupply its atmos supply in the event of catastrophic damage.
A small shield lattice prevents collisions from and asteroids and debris, further servicing the ship's asteroid harvesting nature.
Near the front is an office installed for the GOLD Delegate, with a built in privacy shutter, secretarial desk, and fax machine for contacting home.
The cargo bay contains the crew's latest supply of food, several pizzas and a few boxes of donk pockets. It may not be up to some people's standards, but the pilots seem to enjoy it. In the event of the crew finding something edible, a kitchen has been erected in the fore hallway.
Mech 4 is currently under construction by the Mechanic, once it's ready, space will have to be made in one of the bays for it.

dreamseeker_1QTUmRyT4h
dreamseeker_AAMnigf2tb
dreamseeker_3p5OSOC8Ao
dreamseeker_Vk33GkAywz
dreamseeker_3X72hJXKVB

- [X] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

Expanding the minutemen lineup with an something that is not explicitly a warship and or security themed vessel gives more character to the faction. It also adds a physical presence to GOLD, which seems to be kinda important out in the frontier.
## Changelog

:cl:
add: A Vela-Class hull has been spotted in the region.

/:cl:

### CODE REVIEW

**Review by Latentish — CHANGES_REQUESTED** [review]
image

While I understand the air traffic control thing, I really don't think this will get much use. These comms don't connect to anything extra and don't go across ships, so it's strange for there to be 8 of them.  People could potentially set up a bunch of specific channels, but they'd have to manually switch their headsets or radio to them each time.
1. These buttons on the table have no visual change to what they're supposed to do past the name. I don't know where x place is if I don't see what's happening when I press the button.
2. You can't see out these windows when the shutters are up.
3. this is an awkward spot for this shutter button, by the door would be better.

image
This is cute but I wish it wasn't so disconnected from the lounge area. You could possibly flip this floor plan so those top two chairs are on the right side and the kitchen is with the lounge

image
double closet. Also you should throw something on that table.
Windows an issue again.
since this is the cryo and dorms room there should be some starting supplies like radios and lights.

image
this PSU doesn't charge

image
This ship can afford a surgery tool duffelbag.

image
I assume this is controlled by those buttons in the comms link room. The button should be over here next to them.

image
This button does not work

image
I just cannot find the button for the holofields or blast doors in the south half. Again buttons should be by their usage.
Also the south area started with atmos issues.
If I'm honest I'm not sure what the usage of the north mech bays are apart from their south counterpart. They seem to serve the same purpose but, again with more ripleys.

the amount of stuff you're giving this ship concerns me. 2 induces, 4 ripleys, 3 heavy duty exosuit plasma cutters, 3 m1911s, and a lot of repetitive food supplies (5 of soymilk, milk, flour, sugar, eggs, rice) you could try fewer but more varied ingredients.

**Comment by Erikafox** [comment]
>You can't see out these windows when the shutters are up.

They work, I've tested them before, space just gets very weird about rendering sometimes.
dreamseeker_wY9jizD2fr

image
I changed the ATC room so it has more granularity to the controls, the ability to see the bays (via camera), and function more as a widespread comms room

Minor equipment changes to the mechs, they get tracking beacons now, a plasma cutter was removed, and replaced one of the MK2s with a normal Ripley. The cargo hauler was downgraded to the cargo ripley. 
StrongDMM_KEwQiq3PzY
I put a little island in to make it feel like more of a "spot" than a passby. 

Not adding buttons directly to the hangar doors just yet. I wanna see if it'll work well like this, because having a proper control room is neat, and the added granularity + monitoring will make it less of a pain in the ass

>repetitive food supplies (5 of soymilk, milk, flour, sugar, eggs, rice)

This is basically just me throwing a normal kitchen cabinet into a wallmount. I added two ingredient boxes and removed some stuff

StrongDMM_TgkLT6r7kI
Also added an R&D server + Console. Not sure if it's gonna stay, but if it gives the ship more depth, then I'm happy. 

>I assume this is controlled by those buttons in the comms link room. The button should be over here next to them.

The button is right next to the engines.

Sec gets secbelts and a pepper spray kit to reinforce that they're not monster fighters, and I put 2 mech extinguishers into engineering.

**Comment by Apogee-dev** [comment]
Would you be against replacing the Ripleys with CMM ripleys? I know they're only Mk. Is, but the pilot suits are at least spaceproof. Otherwise I'll take another look at it when I work on making the CMM mechs more distinctive.

**Comment by Erikafox** [comment]
> Would you be against replacing the Ripleys with CMM ripleys? I know they're only Mk. Is, but the pilot suits are at least spaceproof. Otherwise I'll take another look at it when I work on making the CMM mechs more distinctive.

The RCS modules that work with gas don't work on mk1 ripleys because they don't have gas tanks. I'd need to give them ions which is a decent power boost.

**Comment by Apogee-dev** [comment]
> > Would you be against replacing the Ripleys with CMM ripleys? I know they're only Mk. Is, but the pilot suits are at least spaceproof. Otherwise I'll take another look at it when I work on making the CMM mechs more distinctive.
> 
> The RCS modules that work with gas don't work on mk1 ripleys because they don't have gas tanks. I'd need to give them ions which is a decent power boost.

Damn, good point. Guess I know what I'm doing with further CMM mech content.

**Comment by Latentish** [comment]
Again I don't think this needs to have 4 ripleys. You should cut it to 1, with like, stuff for 1 more maybe.

**Comment by Erikafox** [comment]
I'd be willing to tone it down to 2.5 (I haven't really been counting the cargo ripley) if they got a circuit imprinter, as it stands they can't make more without finding one.

**Comment by Latentish** [comment]
> I'd be willing to tone it down to 2.5 (I haven't really been counting the cargo ripley) if they got a circuit imprinter, as it stands they can't make more without finding one.

give them a locker of parts or something, with the circuits there, and keep only 1 of them built. But give them like 3 total.

**Comment by Erikafox** [comment]
That works, I'll make the change.

**Review by ZephyrTFA — APPROVED** [review]

**Comment by Latentish** [comment]
gabooga, another tm to make sure it runs on live.

**Review by spockye — COMMENTED** [review]
image
might be a good idea to move the Railings to layer 3.1


image
could do with some junk and decalling in here

image
pilots don't have access to the welding supplies

image
while it doesnt need one, the kitchen could definitely use a grinder. the pestle doesn't really work all that well. 
it could also use some more spare bowls, and  such.  (Please give it enzymes)

**Comment by Erikafox** [comment]
updated again.
Kinda decluttered (decalwise), addressed review, moved a few things around

**Comment by Erikafox** [comment]
I need to put a docking port on this

**Pull request closed without merging**
