### PR TITLE
Sunskipper-class Culinary Vessel - the Boyardee replacement. Also, a lot of tweaks to the booze-o-mat.

### PR DESCRIPTION
**Pull request by Sadhorizon**
## About The Pull Request

**TODO**
- [x] tweaks I noted down somewhere else
- [x] address reviews when they pop up
- [x] ~~ethics of passengers~~
- [x] cash rebalance
- [x] ~~more sofas~~ rework the main room 💀
- [x] fate of the botanist
- [x] add gravgen after that's merged
- [x] maybe add lathe
- [x] add missing regeants to the boozeomat

scrnshot1

StrongDMM-2024-05-12 20 45 19

StrongDMM-2024-04-17 16 41 07

Seeds in the locker (if something important is missing here, slap me with a large stick pls):
obraz

Meds in the locker:
obraz

Stuff in the safe:
obraz

New bottles! Absolutely not peak sprite design, but I needed _something_, alright? Lemon Juice, Triple Sec, Creme de Cacao, Creme de Menthe:
obraz

Also, as the bar doesn't have any dispensers, I have added all of dispenser reagents to the booze-o-mat instead.

Also also, wiki page (WIP): https://shiptest.net/wiki/User:Sadhorizon#Sunskipper-class_Culinary_Vessel

## Why It's Good For The 
Boyardee is old and really really bad at it's job as a restaurant ship. Sunskipper is meant to replace it.

Indie chefs loose cqc, because it's an ability fit for fending off tiders in a station environment - not on a six player ship.

Booze-o-mat full of drink-making ingredients is a large step to getting rid of bar dispensers completely.

## Changelog

:cl:
add: Added the Sunskipper-class Culinary Vessel.
add: Every drink and booze dispenser drink is in the booze-o-mat now.
add: Added bottles for triple sec, lemon juice, creme de cacao and creme de menthe.
del: Removed the Boyardee-class Entertainment Vessel.
del: Independent chefs no longer get kitchen cqc.
tweak: The "syndicate waiter's outfit" renamed to just "waiter's outfit".
tweak: Indpenedent bartenders now start with a waistcoat.
tweak: Edited waiter's outfit. Also, the role now gets kitchen access.
tweak: Independent cooks now start with laceup shoes.
/:cl:

### CODE REVIEW

**Comment by Skies-Of-Blue** [comment]
We're so fucking back

**Comment by Cadunkus** [comment]
Very classy and cool.

**Comment by Zevotech** [comment]
Very nice looking and a definite improvement over the original. Give me an @ when it's undrafted and ready for a review.

**Comment by Zevotech** [comment]
Ping me sometime this weekend if I don't review this tonight.

**Review by Zevotech — COMMENTED** [review]
The base external area makes these tiles fullbright. Use the dark subtype (/area/ship/external/dark).
image

I would add some cleanable decals throughout the ship, some cracked eggs or dust around for some roundstart cleaning. 
image

...And that is all of the changes I had to request. Yep. I am stunned at the quality of this ship. The layout is good, the decaling is amazing, they start with just the right amount of stuff, and the access restrictions are well-placed. This is an excellent ship that would make it in even if it wasn't replacing an old one. Great job! Once you fix the external areas this should be ready for TM.

**Review by Latentish — CHANGES_REQUESTED** [review]
image
There are a few things I dislike about this room. Your floor pattern is uninterrupted for this whole room, I would hihgly recommend changing up the flooring where there are impassible objects. Do not pixel shift vending machines please. Don't make scrubbers or vents inaccessible, you have a scrubber underneath a vending machine meaning that machine would need to be moved to access it. The lamp on the table is very awkward, obstructing 2 different screens on the walls. That lightswitch is behind a tile visibility muter, deprending on what tile it is actually on, the curtains could potentially hide it, put it on the other side of the door.



Your entire ship has some pretty questionable placements of wall mounts. To be fair, there are not many great examples as to what "good" wall mounts look like. But when placing wall mounts you need to think about more than wall space and room space,, you have to think about their accessibility.  And different wall mounts have different accessibility needs.

image
Emergency cabinets such as the fire extinguisher cabinet, need to be accessible on the tile in front of them as if they were a closet (because they are). There are cases to be made for wall closets to let out onto a table.

image
APC's need the tile they're on to be accessible due to spawning a terminal on it.  Machines and other structures should be avoided. Tables can sometimes be put in front of them if they aren't like, important tables.

image
image
You have an empty wall here, put the apc on it, put a cryo panel where the lightbulb or poster are, put a light behind one of the cryopods, and put the air alarm on the free wall behind the crate.

image
These bathrooms are very nice, I'm very happy you put a crew and public bathroom. Put a bar of soap in the shower.

image
This is an example of a perfectly acceptable apc location. However this closet being on the same tile as a sink is not. This air alarm is not 100% illegal but I'd definitely prefer it avoided. Here's a suggestion for a layout that could fix this issue.
image
image

image
This does not work, also please lower your buttons to somewhat rest along the floor here?
Overall give your wallmounts a good thorough sanity check.

image
apc's again.

image
I'm not entirely sure how I feel about this second airlock being right here. It feels like a strange choice.

image
Button behind canister, put it on the wall on the other side.

image
You need a stethoscope to get into this.

image
All wall lockers need to be a +/-28.

Overall I think this is a nice ship, needs a good look over its wallmounts, but otherwise you did a really solid job.

**Comment by Sadhorizon** [comment]
> I'm not entirely sure how I feel about this second airlock being right here. It feels like a strange choice.

Idea is that subshuttles can dock there without obscuring the main entrance. It's pretty much only for those, for whenever they get more used.

> You need a stethoscope to get into this

Zevo told me to hide it - look at the plant! I can make it more obvious tho xP

> This does not work

Sorry... what doesn't? Don't think I'm getting you.


Will handle rest of reviews later today!

**Comment by Latentish** [comment]
> > I'm not entirely sure how I feel about this second airlock being right here. It feels like a strange choice.
> 
> Idea is that subshuttles can dock there without obscuring the main entrance. It's pretty much only for those, for whenever they get more used.

Fair enough reason for me.


> > You need a stethoscope to get into this
> 
> Zevo told me to hide it - look at the plant! I can make it more obvious tho xP

You're fine, just didn't see one.


> > This does not work
> > Sorry... what doesn't? Don't think I'm getting you.

The way you've stacked those buttons leave them in a very strange state on the wall. Check your layering and try to avoid stacking buttons vertically like this.

**Comment by lectronyx** [comment]
really cool, but that's a lot of chairs. Major L for booth lovers

**Comment by Bimbly** [comment]
Feedback for sunskipper after playing about half a round on it because you were asking in ooc earlier :):

Games vendor and gaming table, one of the best parts of the boyardee whenever i played on it was playing blackjack and cards against spessman
Fridge in central kitchen for common items
Booze and soda dispensers, vending machine drinks are swag but you cant get all the drinks from them and also much convenience
Same for soda and tea vendors but to a lesser extent
Clothes vendors, especially the waiter bartender and cook ones but also id really like the base two 
Fishing supplies, not neccesarily thematic but good way to get unique types of food
Coooow i want a coooow moo moo
Plates and silverware (for some reason the kitchen vendor thingy doesnt have plates or spoons in it???)
Glass recylcer
Backup candles
A beaker for the biogenerator you cant put normal cups in them

Also on an unrelated note
Im SAD that the only ship in the game missing a lathe is the food ship give me my challenge ships back you heathens

**Comment by Sadhorizon** [comment]
Hey! Thanks for feedback!

> Games vendor and gaming table, one of the best parts of the boyardee whenever i played on it was playing blackjack and cards against spessman

Focus was shifted from a casino ship. Might add some cards, I guess.

> Fridge in central kitchen for common items

Will think about it.

> Booze and soda dispensers, vending machine drinks are swag but you cant get all the drinks from them and also much convenience. Same for soda and tea vendors but to a lesser extent

It was a maptainer's request to remove those. Gonna see what I can do.

> Clothes vendors, especially the waiter bartender and cook ones but also id really like the base two.

There are spare clothes in the cryo room, bartender's locker and the manager's locker.

> Fishing supplies, not neccesarily thematic but good way to get unique types of food

You can buy them, they are cheap.

> Coooow i want a coooow moo moo

You can get milk from the Biogen. Buy one from outpost or abduct one from jungle if you want fresher milk.

> Plates and silverware (for some reason the kitchen vendor thingy doesnt have plates or spoons in it???)

I can probably add those to that vendor. EDIT: That stuff is broken. I maaaaybee can rework it in a different PR, but also I'm not the best coder out there.

> Glass recylcer

Explain?

> Backup candles

You have five boxes. "Supplies" crate in the cargo hold.

> A beaker for the biogenerator you cant put normal cups in them

Buckets fit there, you start with two.

**Review by Latentish — DISMISSED** [review]
image
You have this floor lining cutting across. It's a bit awkward and I'd like you to nix it.

image
The grill needs charcoal (or coal???) to work. give that and a matchbox.

image
This table is very barren, add some clutter. Paper, pen, a bell, maybe a register.

image
I'm going ot say that I'm not really a big fan of this bridge layout. It feels strangely put together with a safe behind a long console. It feels like you had space to fill here and that space was awkward so you sorta crammed it in. There is a way to cram stuff into small spaces but it can be difficult. And I'm not sure this works. Another maptainer may have another opinion on this room.

image
The chicken with no habitat here is very strange. Especially for a restaurant ship. You can buy eggs and milk from the outpost. Give them a starting supply and don't add the animal unless it has an enclosure. (Animal cruelty speedrunning)

image
Add salt, pepper, and nutriment to these tables.

image
The table in front of the biogen is very awkward. Same with the sink behind the tray. What I would recommend is changing the window next to the  sink to a wall, putting the wall locker on it,  putting the table where the hydroponics tray is, and putting the apc where the locker was.

**Comment by Latentish** [comment]
Here is my recommendation for the botany room.
image

**Review by goober3 — DISMISSED** [review]
hi. please run 2883_wall_lockers.txt in tools/updatepaths/scripts. you've got wrongly rotated lockers.

also remove the railings here or i'm killing you
43a4fe40c88a7962603e285d4e3d47ed

**Comment by Sadhorizon** [comment]
> you've got wrongly rotated lockers.

Actually, no. Up and down sprites are the wrong way for blue locker doors.
obraz

(correct red doors for reference)
obraz

**Comment by goober3** [comment]
> > you've got wrongly rotated lockers.
> 
> Actually, no. Up and down sprites are the wrong way for blue locker doors. obraz
> 
> (correct red doors for reference) obraz

sobbign and weepi ng ! @thgvr

**Comment by Sadhorizon** [comment]
FUCK, wrong branch

**Review by Zevotech — APPROVED** [review]
Looks ready for merging.

**Comment by Sadhorizon** [comment]
O-O

**Pull request merged**
