### PR TITLE
New Waste Ruin: Abandoned Miskilamo Shipbreaking Yard

### PR DESCRIPTION
**Pull request by Thera-Pissed**
## About The Pull Request
New wasteplanet ruin, an abandoned shipbreaking yard owned by Miskilamo

yardreal4
yardreal3
image
yardmap2

## Why It's Good For The Game
Waste ruins are needed, I think!

## Changelog

:cl:
add: New wasteplanet ruin, the abandoned Miskilamo shipbreaking yard!
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
@shiptest-ss13/maptainers @Latentish @Apogee-dev @goober3

**Review by meemofcourse — CHANGES_REQUESTED** [review]
imagen
the galoshes being thrown in there unceremoniously seems wrong
imagen
imagen
replace with actual rations please, and lower the amount present
imagen
i understand that fireaxes might be flavorful but please remove this one
imagen
very funny but don't
imagen
kind of iffy on the c4 bag and emp clusterbomb
imagen
perhaps it would be clever to reflavor this

cool ruin

**Review by meemofcourse — APPROVED** [review]

**Comment by thgvr** [comment]
Fix those checks and it should be good to go

**Comment by meemofcourse** [comment]
checks please

**Comment by Thera-Pissed** [comment]
image
new hivebot spawners, basically the same spots

**Comment by Thera-Pissed** [comment]
checks passed, apologies for the delay

**Comment by Thera-Pissed** [comment]
apologies for taking so long on merge conflicts!

**Comment by Thera-Pissed** [comment]
guh

**Comment by meemofcourse** [comment]
despite all my rage

**Comment by Thera-Pissed** [comment]
surely

**Pull request merged**
