### PR TITLE
Port Request Manager / TGUI Improvements

### PR DESCRIPTION
**Pull request by ZephyrTFA**
Ports https://github.com/tgstation/tgstation/pull/60905

To do this I was required to hardset our tgui folder to tgstation's.

As such a lot of their recent improvements will also carry over!
However, this also means that stuff we might have deleted in the past has magically reappeared.

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
Seems to work, **NEEDS TESTMERGED**

**Comment by triplezeta** [comment]
Shuttle manipulator is very broken

**Comment by triplezeta** [comment]
Sleepers nonfunctional

**Comment by rye-rice** [comment]
vending machine gui is m
image

**Comment by triplezeta** [comment]
chem dispenser has fermichem features we don't use (and dont want)(PH tooltips and PH colorcoding) and the search reactions button doesnt work

**Comment by rye-rice** [comment]
image

**Comment by triplezeta** [comment]
yeah thanks retlaw

**Comment by triplezeta** [comment]
fax UI very broken

**Comment by TheNeoGamer42** [comment]
Admin supplypod manipulator menu bluescreens, manifest does also. Shuttle manipulator works for me, but I am running latest byond version

**Comment by ZephyrTFA** [comment]
> vending machine gui is m image

What does this mean

**Comment by rye-rice** [comment]
it doesnt show the stock

**Comment by ZephyrTFA** [comment]
smh bot reminding me I shouldnt have four large projects at the same time

**Pull request closed without merging**
