### PR TITLE
High class couch fix

### PR DESCRIPTION
**Pull request by CenkTheRaptor**
## About The Pull Request
Fixes the couch in the bridge so that the corners are facing the right way. I know you can just deconstruct it but it was bothering me

- [X] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
The High class looks better roundstart

## Changelog

:cl:
fix: Fixed the couch on the High-class Corporate Luxury Ship's bridge.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
why is the diff the entire file

**Comment by BarteG44** [comment]
Zased

**Comment by CenkTheRaptor** [comment]
> why is the diff the entire file

uhhhhhhhhh. that might be because its an older version of the high class i dont know fuck

**Comment by Erikafox** [comment]
Remake this pr with some sort of git control please. Map Webedits Bad.

**Pull request closed without merging**
