### PR TITLE
Removes the Combot Specialty from the Corvus-class and gives it a Combat Specialty

### PR DESCRIPTION
**Pull request by Cadunkus**
## About The Pull Request

There's a typo in the Corvus-class Response Vessel's description.

## Why It's Good For The Game

Fixes a typo in the Corvus-class Response Vessel's description.

## Changelog

:cl:
spellcheck: Fixed a single typo in the description of the Corvus-class Response Vessel.
/:cl:

### CODE REVIEW

**Comment by Galdar02** [comment]
Oh my gods girly ya gotta fix that changelog, it a spellcheck all you need is the spellcheck:

**Comment by Galdar02** [comment]
As in remove all the tags you don’t need you dork, **all you need** is the spellcheck:

**Comment by thgvr** [comment]
Your changelog needs to describe any player-facing changes of the PR, please change it.

**Comment by Cadunkus** [comment]
Okay laughs were had. Updated the CL.

**Comment by thgvr** [comment]
The changelog needs to describe your change as well

**Pull request merged**
