### PR TITLE
Changes the airlock sounds

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

So I think im going insane from the airlock sounds we have right now. They have no closing sound, and blend in constantly.

This changes them to be less monotonous.

Sounds are from [skyrat and whatever russian server they stole it from](https://github.com/Skyrat-SS13/Skyrat-tg/pull/1245)

External airlocks sounds are from [paradise, which apparently are from yogstation](https://github.com/ParadiseSS13/Paradise/pull/6761)

## Why It's Good For The Game

Sound design is usually good, despite being ignored

## Changelog

:cl:
add: Changes the airlock sounds
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
i'm not going to lie, i dislike most of these sounds. They're either too obnoxious (access denied buzz) or they sound way too similar to each other (bolts lifting/lowering sounds very similar to an airlock closing, compared to the old sound's very distinctive clunk). A lot of them also have a lot less impact (particularly blast doors, they're kind of mushy now) which makes them feel less grounded so to speak

the only ones i actually like are the external airlock sounds and the normal airlock open/close sounds.

**Comment by Erikafox** [comment]
image

**Comment by AverageUser67** [comment]
basically what apogee said

**Comment by thgvr** [comment]
Can we merge this

**Review by MarkSuckerberg — APPROVED** [review]
ok

**Pull request merged**
