### PR TITLE
Fix Design Disks

### PR DESCRIPTION
**Pull request by generalthrax**
## About The Pull Request

Design disks work again

## Why It's Good For The Game

This is probably going to die before Christmas but we should have features that work

## Changelog

:cl:
fix: Design disks work again
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
I liked rnd being broken

**Comment by generalthrax** [comment]
I did too. But fixes good.

**Review by FalloutFalcon — APPROVED** [review]

**Comment by FalloutFalcon** [comment]
broken features are not solutions for issues in the game

**Comment by rye-rice** [comment]
broken features are solutions , for example , removing rnd without actually removing it

**Pull request merged**
