### PR TITLE
Ports TG leg rendering

### PR DESCRIPTION
**Pull request by MrSamu99**
## About The Pull Request

Ports:
https://github.com/tgstation/tgstation/pull/66607
https://github.com/tgstation/tgstation/pull/71721

And changes legs path from r_leg\l_leg to legs/right \ legs/left

## Why It's Good For The Game

Spriters would like that, and everybody like spriters work (hope so)

## Changelog

:cl:
refactor: legs now have the same path as the TG legs
refactor: refactored leg render code
/:cl:

### CODE REVIEW

**Comment by Ms-Mee** [comment]
Grr I hate spriters they killed my family, raided my lands, pillaged my crops, destroyed my boats and it's their fault among us is real 😡

**Comment by TheNeoGamer42** [comment]
Zeta did make the skel- I mean shetland. Which is totally not like, the among us ship or some shit. So yeah spriters DID make among us real in shiptest.

**Comment by meemofcourse** [comment]
man this guy is sus call an emergency meeting

**Comment by Erikafox** [comment]
image
I think this is this pr's fault

**Comment by MrSamu99** [comment]
> image I think this is this pr's fault

I've found runtime, but it happened not in my code

**Comment by MrSamu99** [comment]
And it happens only with kepori and vox

**Comment by MrSamu99** [comment]
I still not understanding why I get this runtime. I didn't touch any other code, only icons. But runtime isn't connected with them... Heads are missing because proc just ends at the point of runtime

**Comment by MrSamu99** [comment]
@Bjarl seems like it doesn't break kepori anymore

**Comment by Erikafox** [comment]
neato

**Pull request merged**
