### PR TITLE
[CURSED] Storage rework: Volumetric Edition

### PR DESCRIPTION
**Pull request by Sun-Soaked**
## About The Pull Request

The time of weak, feeble tile-based storage is over(except for all the storage items that will continue to use it). This pr adds volume-based, unbound storage like that which appears on Baystation. 
A partial port of citadel's Volumetric Storage port, which can be found [here.](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11809)
Also contains a slight rework of Trashbags that increases their storage power, but locks them to only displaying the top 5 items inside them. (Found [here](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9641))

- [x] Port Volumetric Storage
- [ ] Polish up item placement in boxes, and box positioning
- [ ] Remove active box scaling
- [ ] Port CEV Eris storage accessories
- [ ] Possible rebalance of bags/duffelbags? Pending feedback

## Why It's Good For The Game
Provided I'm able to get it functioning properly, Volumetric can really give a soulful energy to the act of stuffing everything you can get your grubby spaceman mits on into your storage sacks

## Changelog
:cl:
add: A second type of storage ui, that displays items in a volume-based inventory
add: Adds an accessible storage system, allowing storage objects to display only a certain "top layer" of their inventory. Trash bags now use this.
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
AAAAAAAAAAAAAAAAAAA

**Comment by rye-rice** [comment]
when you code it

**Comment by thgvr** [comment]
Don't try me

**Comment by rye-rice** [comment]
im not trying you im asking you

**Comment by Sun-Soaked** [comment]
video games

**Pull request closed without merging**
