### PR TITLE
Craftable Towels

### PR DESCRIPTION
**Pull request by Skies-Of-Blue**
## About The Pull Request
image

## Why It's Good For The Game
Crew shouldn't have to buy a sauna kit just for some towels. 
Players are now enabled to have a spontaneous beach episode, any time, anywhere!

## Changelog

:cl:
tweak: towels can now be crafted using two cloth
/:cl:

### CODE REVIEW

**Comment by Skies-Of-Blue** [comment]
Unmarked as draft. The longer I stare at towels the more I want to change, but that's out of scope for this PR. I may get around to larger changes at a later date.

**Review by MarkSuckerberg — APPROVED** [review]
some people say it might be better off being a small crate from cargo, but I personally think this is fine-- unless you'd rather add both or switch to that

**Comment by Skies-Of-Blue** [comment]
> some people say it might be better off being a small crate from cargo, but I personally think this is fine-- unless you'd rather add both or switch to that

As silly as it is to have these craftable, I don't think it's any sillier than chopping up a jumpsuit and making a duffelbag out of it. The issue is more so our crafting system, which is out of scope of this PR. Spacemen shouldn't have to settle for blankets, and shouldn't have to pay a towel tax at the start of every round imo. 

The only current way to obtain towels in-game is to buy a sauna crate, which is iffy. Ultimately it would make more sense if ships came stocked with them, but that's once again out of scope. For the time being, this band-aid of a solution slots neatly into our existing systems. If requested I can make a crate stocked exclusively with towels in addition to this change, though.

**Comment by MarkSuckerberg** [comment]
Oh yeah I totally agree. Just figured I'd sound it out with you as well to see if you were more inclined towards the others' ideas. Towels are dead simple and probably one of the least bad offenders-to-be in the crafting system, since they're pretty much just large bolts of cloth anyway.

**Pull request merged**
