### PR TITLE
Duke's Nuclear Fashion(Formerly Voulgier Class)

### PR DESCRIPTION
**Pull request by 1glitchycent**
## About The Pull Request
~~Adds the Voulgier, an ACLF dropship with a focus on firepower and medicine, but lacking many common necessities.~~ Adds syndicate clothes for Cybersun, the ACLF and the Gorlex Marauders, as well as job formats.
image

## Why It's Good For The Game
~~A new ship with both explicit faction affiliation and scarcity which I hope will help create interesting gameplay. ~~ faction clothes good.

## Changelog
:cl:
add: ~~A new Syndicate craft, the Voulgier.~~
add: new syndicate uniforms for Cybersun, the ACLF and the Gorlex Marauders
/:cl:

### CODE REVIEW

**Comment by Valorium-RB** [comment]
Personally, an autolathe with an emag may be needed here. Otherwise, this ship ostensibly designed to be focused on firepower will run out of ammunition after killing, like, two goliaths. Once that point is reached, your fancy makarovs and shotguns will basically be fancy paperweights.

**Comment by 1glitchycent** [comment]
> Personally, an autolathe with an mag may be needed here. Otherwise, this ship ostensibly designed to be focused on firepower will run out of ammunition after killing, like, two goliaths. Once that point is reached, your fancy makarovs and shotguns will basically be fancy paperweights.

I gave some more ammo and also job uniforms which need testing.

**Comment by 1glitchycent** [comment]
does anyone know what the FUCK this means 
image

**Comment by 1glitchycent** [comment]
image
apparently I'm supposed to ignore this.
Someone tell me if I'm misinterpreting,

**Comment by 1glitchycent** [comment]
So yeah I think this is ready to merge

**Comment by Sun-Soaked** [comment]
Remember to document the clothing additions you made in this pr in the desc/changelogs

**Comment by 1glitchycent** [comment]
I consneed.

**Pull request merged**
