### PR TITLE
Unbranded Utility Covers + Miskilamo Cap

### PR DESCRIPTION
**Pull request by firebudgy**
## About The Pull Request

Adds some generic utility cover caps, after Apogee brought it up. Beige, Black, and an Olive Miskilamo Cap.

Available now at your local LOADOUT retailers and Miskilamo.nt/shop. 

image

image

image

image

Also fixes one of my sprites from way back when to have the correct states.

## Why It's Good For The Game

Additional customization for characters, and something that I believe there would be interest in. These clothing opens combine well with a number of items commonly available on ships or in loadout, such as the military jacket.

Vox sprites included.

## Changelog

:cl:
add: Four new hats for your blorbo customization! Find them in loadout. Sponsored by Miskilamo Shipbreaking.
fix: Vox Frontiersmen Officers finally stitched up their clothing.
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
Still think the olive drab one should omit the badge. It’s hardly unbranded when it has a brand on the front, is it?

**Comment by firebudgy** [comment]
> Still think the olive drab one should omit the badge. It’s hardly unbranded when it has a brand on the front, is it?

I think it looks nicer this way. Besides. Shitty shipbreaking company hat.

**Comment by Erikafox** [comment]
firefox_js4aMp4e8D
If you are going to subtype /utility, it should exist in a manner that does not throw check errors.

**Comment by firebudgy** [comment]
Sorry I don't really know what I'm doing

**Comment by thgvr** [comment]
kepori? 🥺

**Comment by firebudgy** [comment]
> kepori? 🥺


https://github.com/user-attachments/assets/b082539f-46c0-4ee0-a727-30180815233f

**Review by thgvr — APPROVED** [review]
If it looks good enough on kepori with just offsets, all good.

**Pull request merged**
