### PR TITLE
[DNM]Revert "Cabinet Refactor" to see if defibs get fixed

### PR DESCRIPTION
**Pull request by rye-rice**
Ditto

If it does it will be kept on TM 
Reverts shiptest-ss13/Shiptest#3378

### CODE REVIEW

**Comment by Erikafox** [comment]
yeah it's probably the checking for trait_wielded instead of the var or whatever in the defibs

**Comment by rye-rice** [comment]
cwan ywou fwix iwt erwika qwq

**Comment by Erikafox** [comment]
im gaming right now otherwise i would. i need to get my weekly autistic girlthing rep in.

**Comment by Erikafox** [comment]
if you want to fix it search for TRAIT_WIELDED in defib.dm

**Comment by FalloutFalcon** [comment]
> yeah it's probably the checking for trait_wielded instead of the var or whatever in the defibs

its the opposite.
its checking for the wielded var but you removed the thing that updates it
you just need to refactor the stuff to use the trait

**Comment by Erikafox** [comment]
MANY such cases of a problem just because of me being stupid

**Pull request closed without merging**
