### PR TITLE
Musicwriter

### PR DESCRIPTION
**Pull request by MrSamu99**
## About The Pull Request

Allows users to load their music via file load and run it in jukeboxes and boomboxes.
Requires coins to work.
If maintainers will agree, I will add coin press design to this PR.
Main issue: track length is cursed to be VERY long, so turn off tracks yourself.

## Why It's Good For The Game

A lot of people likes music, so I took away restrictions on it!

## Changelog

:cl:
add: Added musicwriter - machine to load music from files
/:cl:

### CODE REVIEW

**Comment by AverageUser67** [comment]
Please, please, please- I fucking need to play the blob theme and then scream and point whenever I see a jellyperson

**Comment by Ms-Mee** [comment]
Me playing Moonlight Capital (Kirby and the Rainbow Curse version) and killing you the moment you try to do that (it causes both of us to lag giving me enough time to plan a way to push you out into hyperspace making it look like an accident)

**Comment by BarteG44** [comment]
based based based based based

**Comment by Sun-Soaked** [comment]
would it be possible to do this via. space cash or swiping your ID instead of via. coins?
The currently up money rework removes the monetary value of material coins and adds a new type of coin that forms naturally from space cash itself

**Comment by MrSamu99** [comment]
> would it be possible to do this via. space cash or swiping your ID instead of via. coins?

This machine needs coins as items, not as cash

**Comment by MrSamu99** [comment]
I'll make another try porting an Eris music system

**Pull request closed without merging**
