### PR TITLE
Adds logging to the TRABUCO

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Adds logging to the TRABUCO

## Why It's Good For The Game

annoys admins when someone does the funny

## Changelog
:cl:
admin: Adds logging to the trabuco shotgun, or the brazil gun as it's better known as
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
...I'm going to level with you here, the sheer concept of this thing is a mistake. The logging helps, but the mere act of using this thing gives the user a not insubstantial chance of just killing themselves, and possibly fragging the rest of their crew from not knowing.

It's the literal definition of a noob trap.

**Comment by Zevotech** [comment]
i can tell you from experience that it doesnt matter if we know what it does and if it will kill our crew, we dont care.

**It Is A Seven Barreled Shotgun, And By Gods Light We Will Use It.**

**Comment by Kapu1178** [comment]
items that exist that can instantly kill the user without any way of them knowing thats a possibility is bad. its even worse than it can harm others too.

**Comment by Zevotech** [comment]
> items that exist that can instantly kill the user without any way of them knowing thats a possibility is bad. its even worse than it can harm others too.

ok, give me a minute

**Pull request merged**
