### PR TITLE
Adds telnet support

### PR DESCRIPTION
**Pull request by alexkar598**
Signed-off-by: alexkar598 <25136265+alexkar598@users.noreply.github.com>

## About The Pull Request
Adds support for telnet to the game

## Why It's Good For The Game
It's not, this allows admins to call any proc bypassing proccall protection

## Changelog
:cl:
add: you can now join via telnet and execute commands
/:cl:

### CODE REVIEW

**Comment by AtlasRules** [comment]
shiptest for the commodore 64

**Comment by alexkar598** [comment]
The PR noone wanted or needed

**Comment by ZephyrTFA** [comment]
LGTM, let's merge this

**Comment by TheNeoGamer42** [comment]
what the fuck does this even DO

**Comment by triplezeta** [comment]
adds telnet support

**Pull request closed without merging**
