### PR TITLE
Adds a salve that allows elzuose to change color

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
To be merged after #2993.
Adds a Kalixcian beauty product that allows Elzuose to (temporarily (for the duration of the round or until used again)) change their glow color. Available in the loadout next to hair dye.

https://github.com/shiptest-ss13/Shiptest/assets/95449138/01060ea1-4b6b-490f-9bf2-83b69cf7efd7

## Why It's Good For The Game
People wanted to keep the ability to change the glow color of an elzuose using an item. Fits better than just using a multitool without the potential for grief/shenanigans. Lore approved too!

## Changelog

:cl:
add: Adds the Elzuose color salve, a product that allows Elzuose to change their glow color upon application.
/:cl:

### CODE REVIEW

**Review by rye-rice — APPROVED** [review]
Good first sprite

**Comment by FalloutFalcon** [comment]
honestly a FIRE first sprite.

**Comment by tiramisuapimancer** [comment]
I don't really understand the point of changing Elzu recolorability to a bespoke item when the multi tool allowing one to retune frequency was already a thing.

**Comment by thgvr** [comment]
"retune frequency" doesn't make sense here, they are not made of pure energy or whatever and are organic

**Comment by tiramisuapimancer** [comment]
they don't need to be, the color of an elzu isn't a pigment, it's the color of the light their electricity emits

**Review by Sun-Soaked — APPROVED** [review]
looks good!

**Pull request merged**
