### PR TITLE
BYO-class

### PR DESCRIPTION
**Pull request by triplezeta**
## About The Pull Request

this adds the BYO-class.

buildyourowngotohell
Yes its the TG Build-your-own escape shuttle

todo:

- [x] BYO-A(verage sized)
~~- [ ]  BYO-B(ig and Breathtaking)~~ 
~~- [ ] BYO-C(ruel and Unusual Punishment)~~

due to maintainer input ive realized that making 3 of these would probably be exceedingly stupid

## Why It's Good For The Game

A niche of ship that was previously occupied by exclusively the pill, blank slate shuttles for crews to customize, is now filled once more.

## Changelog
:cl:
add: DIY Shuttle
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
Funny idea would be to make it the same size and shape as the standard cargo shuttle =)

**Comment by triplezeta** [comment]
image
🙄 fiiine I'll wire the thing roundstart

**Comment by HighPrincessErinys** [comment]
BYO-ND (Agonizing)

**Comment by triplezeta** [comment]
B on deez nuts

**Comment by triplezeta** [comment]
notes to self:

add in basic boards 
fix varedited container names

**Comment by triplezeta** [comment]
note to self: 

add imprinter RND

**Comment by triplezeta** [comment]
I'm Not Done With You

**Pull request merged**
