### PR TITLE
Disables every single CMM ship

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Disables every single CMM ship. While I wanted to do this when i was done with the CLIP resprite, after there was a particularly bad round involving the CMM I want to do this now.

This also deletes the corvus because fuck the corvus

@shiptest-ss13/maptainers please merge ASAP, preferably before next uptime
## Why It's Good For The Game

It's no secret I have not been happy with the CMM players at all, they all suck, and it hurts every day  when i see a Corvus acting like indie+. It also hurts when i can't even spawn in as a inspector or higher up because that requires the players to roleplay, they do NOT roleplaay which hurts a lot especially for a faction i helped create.

I have a grander plan which i've been working on, but this NEEDS to be done

Part 0 of the CMM refresh

## Changelog

:cl:
tweak: all CMM ships are aspawn now
del: Corvus-Class
/:cl:

### CODE REVIEW

**Review by Zevotech — APPROVED** [review]
The rebrand from "Colonial" Minutemen to CLIP Minutemen could not come soon enough.

**Review by meemofcourse — APPROVED** [review]
Is Sisyphus happy?

**Comment by Hydrosatan** [comment]
While I do agree with the reasoning ... The CMM players that are being a part of the problem will inevitably go somewhere else. Do you think this might cause other factions to get an influx of shitters?

**Comment by rye-rice** [comment]
> While I do agree with the reasoning ... The CMM players that are being a part of the problem will inevitably go somewhere else. Do you think this might cause other factions to get an influx of shitters?

there can only be one

**Comment by Zevotech** [comment]
> While I do agree with the reasoning ... The CMM players that are being a part of the problem will inevitably go somewhere else. Do you think this might cause other factions to get an influx of shitters?

A major part of the reasoning is not that shitters inhabit the ships (although that does happen occasionally), It's that the ships themselves need work in order to curate the atmosphere we want CLIP to have. The lore and sprites will get updated, then the ships will be changed to fit them and they will (hopefully) be spawnable again.

**Comment by Cadunkus** [comment]
Corvus is a good ship. Don't remove the Corvus.

**Comment by stobarico** [comment]
So you're punishing a bunch of unrelated people instead of a few problematic individuals? Seems like an interesting way of thinking

**Comment by goober3** [comment]
> So you're punishing a bunch of unrelated people instead of a few problematic individuals? Seems like an interesting way of thinking

did you. read zevo's comment.

**Comment by goober3** [comment]
I DEMAND!!! THAT "retlaw34" to be DEMOTED!!! it was the best experience being neutral colonial league of independent planets and being the ones who rescue you in a different methods and everyone saying "what the fuck? are you a frontiersman?" then replying "we're the good minuteman we are the hero in this story"

**Comment by rye-rice** [comment]
Remove not improve

**Comment by Imaginos16** [comment]
I DEMAND!!! THAT "retlaw34" to be DEMOTED!!! it was the best experience being neutral colonial league of independent planets and being the ones who rescue you in a different methods and everyone saying "what the fuck? are you a frontiersman?" then replying "we're the good minuteman we are the hero in this story"

**Comment by Hydrosatan** [comment]
I DEMAND!!! THAT "retlaw34" to be DEMOTED!!! it was the best experience being neutral colonial league of independent planets and being the ones who rescue you in a different methods and everyone saying "what the fuck? are you a frontiersman?" then replying "we're the good minuteman we are the hero in this story"

**Comment by Imaginos16** [comment]
https://www.youtube.com/watch?v=dyIilW_eBjc

**Pull request merged**
