### PR TITLE
adds fox girls

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
ports https://github.com/tgstation/tgstation/pull/65839
will improve sprites later, probably
Two variants, two has a darker tip but no wag, here's an example (whhy can't I make them stop snoring. dear god.)
image

## Why It's Good For The Game
lol

## Changelog

:cl:
add: Humans are now able to gene-mod (select in prefs) fox ears and tails.
/:cl:

### CODE REVIEW

**Comment by spockye** [comment]
E8C10442-23F2-4B28-B147-9BCB32BD9289

**Comment by rye-rice** [comment]
Is there a screenshot of these in action? This is lore friendly, by the way.

**Comment by thgvr** [comment]
ok ill make some

**Comment by thgvr** [comment]
updated pr body

**Review by rye-rice — APPROVED** [review]
foxgrils

Always appreciate more human customization

**Comment by meemofcourse** [comment]
real

**Comment by TheColorCyan** [comment]
RDT_20230423_1646143559405565758854205

**Comment by Imaginos16** [comment]
The fact that my work for an April Fools PR made it as far as here is fucking hilarious and I love it. God bless Shiptest.

**Comment by Xylarr** [comment]
now sprite her givin- ACK!

**Review by triplezeta — APPROVED** [review]
:+1:

**Review by MarkSuckerberg — APPROVED** [review]
you heard zeta, lgtm

**Pull request merged**
