### PR TITLE
Overmap Expansion 4.2

### LINKED ISSUE #1765: [BUG] Mining sand on beach worlds makes it darker
## Reproduction:

image

go to beach planet, dig holes, area dug has no natural lighting

### PR DESCRIPTION
**Pull request by Sun-Soaked**
## About The Pull Request
This content was originally intended to be merged onto Overmap 4, but then my PC exploded and Retlaw recommended I just pr it later. 
We have successfully reached Later.

- Tweaks most planetary ore pools to be more varied- planets now have significantly larger amounts of specific resources, and might be missing an ore type.

- Adds Gardens, little patches of foliage you can root through to scavenge some local flora. There are four flavors found in different environments, each with their own spawn pool of possible produce. Any pool also has a small chance to spawn a strange seed.
You can now forage the frontier for the seeds and produce you need for botany! This is intended to be a stopgap until we can make a good system for fully rng plants, like bay's.

- Ports Brimdemons, originally made by Fikou, from [This Pr.](https://github.com/tgstation/tgstation/pull/64592)
Ports TG's get_line helper to facilitate this.

- Adds driftwood and shells to the shores of Beach worlds. Sprites borrowed from the Voidcrew PR much of Overmap 4 was based on.

- sand from Rockworlds and Wasteplanets now has unique reagent composition.
Do not eat the trash sand. 

- Adds red rocks and patches of sparse, dead grass to rockworlds.

- Gruboid dens can now rarely be found on rockworlds.

- Adds a Lobstrosity crusher trophy.

- Adds some (non-spreading) glowshrooms to wasteplanets.

- Allows crystal mobs to appear on lava worlds. Having them stuck specifically on waste planets and set to the rarest possible appearance rate meant they essentially did not appear- they're still at the rarest possible spawnrate (on a planet with lots of common monster types, as well) but this might spook some tendril rusher

- Adjusts some names and descriptions for natural rock walls to be more soulful and geological

- Adjusts exactly three(3) lava world flora objects to have more interesting names and descriptions. Incredible

- Saguaro cacti on rockplanets have been re-themed into a cold-climate subspecies, because real Saguaro cannot survive outside the balmy conditions of the Arizona desert.

- Fixes the missing Chilly Pepper texture.

- Fixes the missing White Sand texture.

- Ground no longer loses natural light when dug out with a shovel. 

- Halves the power cost of the self-sustain mode on hydro trays. It was allegedly draining apc's dry with 3 or 4 trays before.

## Why It's Good For The Game
Step one in my two-step plan to make botany about exploration, rather than sitting in the ship waiting for things to grow.
Brimdemons!
Assorted planetgen stuff is always good

## Changelog

:cl: MemedHams, Fikou
add: Brimdemons have appeared! These simplemobs fire a beam of energy in a cardinal direction when disturbed.
add: Adds Gardens, harvestable patches of foliage that drop a plant randomly selected from a themed pool.
add: Driftwood and seashells now wash up on the shores of beach worlds.
add: The rocks found on rockworlds have now turned the same red hue as the ground and walls.
add: Small colonies of Glowshroom can now be found in the caves of wasteland worlds.
add: Adds a Lobstrosity crusher trophy.
tweak: Gruboids now spawn from nests in the caves of Rockworlds.
tweak: The sand found on rockworlds and wasteland planets now contains additional reagents. 
tweak: different planets now have more diverse ore pools. Some may now have significantly more of certain ores, or lack one or two ores alltogether
tweak: Rock names and examine descriptions are now more soulful.
tweak: Some trees and moss found on lava worlds now lend more insight into their molten planet.
tweak: Saguaro Cacti are now Maguaro Cacti, a cold climate suspecies.
balance: planetary ore pools are now more varied.
balance: Self-sustaining mode on hydroponics trays now draws less power.
fix: Chilly Peppers that grow on ice worlds now have an actual texture.
fix: fixes the missing "white sand" texture
fix: lit planetary tiles no longer go dark when dug out.
soundadd: Brimdemon noises.
code: adds the get_line helper.
/:cl:

### CODE REVIEW

**Review by rye-rice — APPROVED** [review]
ur awesome you know that

**Comment by Sun-Soaked** [comment]
what

**Comment by Sun-Soaked** [comment]
okay give me a hot minute to fix this

**Comment by Erikafox** [comment]
Sand is unmineable with this tm'd. I suspect it has something to do with the reagents but also I don't know how to code.

**Comment by Sun-Soaked** [comment]
whar... I'll check

**Comment by Sun-Soaked** [comment]
yeah that was pretty sloppy of me, sorry. Fixed now

**Comment by goober3** [comment]
I believe gardens are still dropping 1 plant for each harvest. shame!

**Comment by goober3** [comment]
in addition to gardens, this could perhaps do with a small Buff to the outpost seeds crate. like, reduce the cost by 500 and add more Seed Variety. for the players who want the Botany Experience without having to scavenge for seeds.

**Comment by Sun-Soaked** [comment]
3 plant dropping is definitely working on local- maybe you need to update the testmerges.

**Comment by goober3** [comment]
I would totally update the TMs if I could do that.

**Comment by PigeonLord** [comment]
"You can now forage the frontier for the seeds and produce you need for botany! "
If you're lucky that A) You find a Garden that B) Hasn't been ransacked by everyone else and C) Has seeds you actually want.
Like, I get the idea, I don't want to be dismissive of it entirely, but it's very, very luck dependant in order to interact with a basic mechanic of the game, and it's not like Botany is OP and Broken like Research - all it does is make different foods that are, functionally, identical, or make minor healing items.
If you really have to restrict something, restrict seeds that are for stuff other than food, and leave standard fruits and veggies still widely available

**Comment by ArdentSpark** [comment]
TM's are updated as of this round and work on live.
image
Triple yield from gardens is really nice. Very nice.

**Comment by Sun-Soaked** [comment]
> "You can now forage the frontier for the seeds and produce you need for botany! " If you're lucky that A) You find a Garden that B) Hasn't been ransacked by everyone else and C) Has seeds you actually want. Like, I get the idea, I don't want to be dismissive of it entirely, but it's very, very luck dependant in order to interact with a basic mechanic of the game, and it's not like Botany is OP and Broken like Research - all it does is make different foods that are, functionally, identical, or make minor healing items. If you really have to restrict something, restrict seeds that are for stuff other than food, and leave standard fruits and veggies still widely available

let's be real for a moment- if you have a dna manip, original botany can crush the reagent and weapon balance of the game. 
Worse, it encourages bot ship players to sit in their ship and spend 3 hours docked on the outpost making optimal bot mixes. 
The original plan in gen-dev, before this, was to remove mutations and the dna manip completely.
So this is, if anything, the softer punch.


The eventual thing we're gonna do is probably to set up rng bay-like seeds for planets, which is something that'll have to come in good time
I may have to give some bot-specialized ships more seeds to start, but adding this kind of push to actually go search planets and adding round variance to the kind of highs you can get from botany is important to our long term balance development

**Comment by ritorizo** [comment]
We could also add a tool that give you the choice between multiple roll when harvesting a garden to reduce rng a bit.

**Comment by Erikafox** [comment]
I would like this and the botany rebalance merged soon. It's big enough that it causes problems for basically everything else, and (imo) has been decently tested.

**Comment by tmtmtl30** [comment]
looks fine to me code-wise at least

**Pull request merged**
