### PR TITLE
AI EyeObjects are now smarter about being deleted

### LINKED ISSUE #535: [BUG] AI Full Camera Loss "Eyeobj not found"
## Round ID:
First encounter: Round 482
encountered it in a later round where I was AI as well

## Reproduction:
When on a ship as an AI core, in the AI camera view (not in a borg), the screen may go completely black upon docking the ship. This error is indicated in chat by an incessant spamming of "ERROR: Eyeobj not found, creating new eyeobj"

1. Be an AI core on any ship (Bug specifically encountered on the Osprey and Metis)
2. Dock the ship in either empty space or on a planet (Bug was encountered twice in empty space, once on a planet(
3. Either immediately or sometime after docking, your camera view will be replaced with a black void, with the AI interface still there.

what if you
wanted to play ai
but byond said
eyeobj not found

### PR DESCRIPTION
**Pull request by ZephyrTFA**
## About The Pull Request

AI eyes are supposed to be recreated when deleted, they werent getting recreated properly.
eye objects now check if they are the main eye of their AI upon being asked to destroy, and if they are, and the destroy is not being forced, will instead move back to the core of their AI. If the eye object is being force deleted it will attempt to create a new eye object for the AI on their way into nullSpace.

Resolves and closes #535 

## Changelog
:cl:
fix: AI Eyes no longer get permanently deleted by hyperspace
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
speedmerge please god

**Comment by MarkSuckerberg** [comment]
Possible cause of #743?

**Comment by ZephyrTFA** [comment]
More than likely yes, don't have time to test why ai eyes are being constantly qdel'd yet

**Comment by ZephyrTFA** [comment]
begone stale bot

**Comment by ZephyrTFA** [comment]
BEGONE

**Comment by ZephyrTFA** [comment]
wrong button

**Comment by ZephyrTFA** [comment]
Honestly, at this point I cannot be asked to keep this TM'd constantly, I'm going to call the issue where it recalls you from your shell instead of deleting your eye object entirely an improvement and deal with it later

**Pull request merged**
