### PR TITLE
adds altogether too many loadout items

### PR DESCRIPTION
**Pull request by tiramisuapimancer**
## About The Pull Request
Adds mostly some stuff from the clothesmate vendor to loadout? Mostly jumpsuit items. Open to adding more as requested, I'm just PRing because I ran out of ideas for stuff to add and the feedback would be nice

## Why It's Good For The Game
More customization, feels like this stuff was practically missing already anyways

## Changelog
:cl:
add: bunch of existing clothing items have been added to loadout
fix: capitalization on cowboy hat
fix: workboots loadout entry now  actually gives you workboots and not mining boots
/:cl:

### CODE REVIEW

**Comment by TallDeekus** [comment]
I recall the snake plushie wasn't an option in the loadout

**Comment by tiramisuapimancer** [comment]
You're so fucking right, added

**Comment by tiramisuapimancer** [comment]
remind me to move the cowboy hats out of the WS folder later

**Comment by TallDeekus** [comment]
Quick question while my brain is still mud, is hairspray in the loadout? Emergency Comfort Blankets?

**Comment by tiramisuapimancer** [comment]
Hairspray yes, blankets no, ( I didn't know we had that in the codebase? Or are you just asking blankets?)

**Pull request merged**
