### PR TITLE
The Most Serene Solar Confederation's Most Serene Solar Starship, The Chronicle

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request

It's The Solgov Ship. It uses The Solgov Content. 

More specifically it's a engineering / intelligence ship, kind of like a mildly larger kansatsu. A lot of content relating to sensors still doesn't exist, but they've got the gear and equipment to get the authentic Solgov Experience. This includes, but is not limited to: Energy halbreds, excessive amounts of blue and gold, paperwork, and holopads.

Crew consists of
1 Captain
1 Overseer
2 Field Engineers
1 Sonnensoldner
2 Ship Engineers
1 Scribe
For a total of 8 crew.

## Why It's Good For The Game
Solgov content

## Changelog

:cl:
add: table mounted intercoms now exist
add: The Chronicle Class, a Real Solgov Ship, is now in game
/:cl:

### CODE REVIEW

**Review by spockye — CHANGES_REQUESTED** [review]
image

wild wire


image

this wall is Diagonal (looks somewhat bad ingame)
also get scrubbed

image

double beds have directional sprites
also replace it with the maints version please :)

**Comment by Zevotech** [comment]
image
me in the shower of the Chronicle

**Review by Apogee-dev — DISMISSED** [review]
There is something of an excess of spare headsets here, and so far they tend to end up in the hands of the regular crew. Personally I would remove the spare bowman headsets for the officers so they just have the ones they spawn with, and just leave a bowman headset for the Sonnensoldner since they actually could use the ear protection.

Also, you may want to consider making this adminspawn only, if only for the initial faction rollout.

**Comment by spockye** [comment]
image

wuh woh

image

might want to move the APC somewhere else. it goes over the reciver, and is kinda locked away

image

lockers here on purpouse? looks a bit weird

image

diag wall

Field engineer is a "miner", which is a bit... confusing. perhaps try to rename them?

**Comment by RuneQuesteER** [comment]
Lobster ship

**Review by spockye — APPROVED** [review]
im a huge fan of this ship!
tried it ingame, and it works well

**Review by Latentish — APPROVED** [review]
Ship good moment.

**Review by Latentish — DISMISSED** [review]
You need tags and a description.

**Comment by spockye** [comment]
:3

**Pull request merged**
