### PR TITLE
Edit/rebalance beach_fishing_hut.dmm

### PR DESCRIPTION
**Pull request by CenkTheRaptor**
## About The Pull Request
Removes the Butcher, a reskinned cat surgeon, from the beach fishing hut ruin, along with the hidden floor safe and it's loot, and the dehydrated carp plushies in a crate. 

A couple extra Winchester MK.2s and a MK.1 was added to compensate, in order to change the lore purpose of the ruin to that of it being a hunting lodge with secret carpotoxin harvesting in the cold room (real carp vs the imitation carp outside the coldroom) though the fact they have guns may make it obvious anyways. 

The cat surgeon was replaced with a ranged space pirate, renamed to a pirate captain. 

The dehydrated carp plushies inside a crate were replaced with some imitation carp. Some overlapping items were shifted around just to make it look a bit better.

image

## Why It's Good For The Game
This ruin in general sucks, and I think this may make it suck a bit less. The Winchester MK.1 may be a bit much but I do not know it's stats, please tell me if it is too op.

## Changelog

:cl:
balance: Removed the Butcher (a reskinned cat surgeon) from the beach fishing hut ruin along with some of it's loot, also changing it to more of a carp hunting lodge.
/:cl:

### CODE REVIEW

**Comment by lectronyx** [comment]
HOLD ON, NOW - REMOVE THOSE FISHSTICKS!

They aren't a food item - they're a holoparasite injector that's disguised as one, granting the user a random holocarp. Not a fun surprise when you realize most holoparas are useless on Shiptest, plus they dust you on death.

**Comment by CenkTheRaptor** [comment]
> HOLD ON, NOW - REMOVE THOSE FISHSTICKS!
> 
> They aren't a food item - they're a holoparasite injector that's disguised as one, granting the user a random holocarp. Not a fun surprise when you realize most holoparas are useless on Shiptest, plus they dust you on death.

those are, in fact, normal fish sticks. /obj/item/reagent_containers/food/snacks/fishfingers versus /obj/item/guardiancreator/carp or /obj/item/guardiancreator/carp/choose.

**Comment by Zevotech** [comment]
Correct. The holocarp fishsticks dropped from the cat surgeon mob in the ruin, which was removed and replaced with a normal pirate.

**Comment by lectronyx** [comment]
Oh thank god.

**Comment by thgvr** [comment]
conflicts pls

**Comment by FalloutFalcon** [comment]
conflict plz...

**Comment by CenkTheRaptor** [comment]
ok i think its fixed

**Comment by FalloutFalcon** [comment]
looks like you need to repath the mk1

image

**Comment by FalloutFalcon** [comment]
> looks like you need to repath the mk1
> 
> image

I think its /obj/item/gun/ballistic/shotgun/flamingarrow/factory

**Comment by Imaginos16** [comment]
PR #3026 already accomplishes what this PR attempts to do. Closing it with permission from maptainer @Zevotech

**Pull request closed without merging**
