### PR TITLE
.45-70 boxes hold 18 instead of 12, .45-70 specialty ammo black market

### PR DESCRIPTION
**Pull request by generalthrax**
## About The Pull Request

Doubles the amount of rounds in .45-70

## Why It's Good For The Game

Beacon takes the cake for The Worst Ammo Efficiency In The Game By Far (500 credits for 12 bullets, you are Shooting 40 Credits Each Shot, the equivalent of shooting half a Plasteel Sheet each shot)

## Changelog

:cl:
balance: .45-70 boxes increased from 12 to 18
add: .45-70 hollow point boxes and A Singular .45-70 Explosive Round is now available in the black market
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
Just reduce the price, don't double the size of the box. Most ammo boxes are around 2 reloads for the most notable gun that uses it (the ashhand revolver in this case), so the old capacity was in line with that. Too big and it starts to mess with inventory economy. .45-70 is still tied with .300 for having the highest damage for any normally obtainable, non-HP ammo type in the game and can fit in a handgun, so it should have a per-shot price that reflects that, accounting for any reductions in .300's price.

**Comment by generalthrax** [comment]
> Most ammo boxes are around 2 reloads for the most notable gun that uses it

primary guns that have enough ammo for more than 2 reloads:

- commander
- stechkin
- skm
- illestren
- scout
- shadow
- firebrand
- hellfire / conflagration / brimstone / double barrel
- candor / cobra-20
- detective revolver / flaming arrow
- vickland / inteq dmr

so thats every gun in the cargo catalog (the Exception to Most) barring the WT-550 / SKMv and the aforementioned Ashhand with enough ammo in one box for more than one reload. i dont see your point.

**Comment by Apogee-dev** [comment]
> > Most ammo boxes are around 2 reloads for the most notable gun that uses it
> 
> primary guns that have enough ammo for more than 2 reloads:
> 
>     * commander
> 
>     * stechkin
> 
>     * skm
> 
>     * illestren
> 
>     * scout
> 
>     * shadow
> 
>     * firebrand
> 
>     * hellfire / conflagration / brimstone / double barrel
> 
>     * candor / cobra-20
> 
>     * detective revolver / flaming arrow
> 
>     * vickland / inteq dmr
> 
> 
> so thats every gun in the cargo catalog (the Exception to Most) barring the WT-550 / SKMv and the aforementioned Ashhand with enough ammo in one box for more than one reload. i dont see your point.

That's fair enough, but that's also a _lot_ of bullets that do 45 damage each in a single small slot. At least make it 18 instead of 24 if you want to increase the size, because fully doubling it is too much in my opinion.

**Comment by generalthrax** [comment]
I'll settle for that.

**Comment by generalthrax** [comment]
made a teensy tiny little change from https://github.com/shiptest-ss13/Shiptest/pull/3334

**Comment by Apogee-dev** [comment]
if you want to be REALLY funny you could add .45-70 explosive to the black market for some absolutely exorbitant price, but who knows what effect that would have on gameplay since that shit's guaranteed to blow a limb off if it hits one

**Comment by generalthrax** [comment]
im not crazy enough to add that just yet

**Comment by Apogee-dev** [comment]
think about it, black market listing for One Single Explosive Bullet. one thousand credits.

**Comment by generalthrax** [comment]
cooked

**Review by FalloutFalcon — APPROVED** [review]
This is funny and rare enough to probably not impact gameplay

**Pull request merged**
