### PR TITLE
Fashion on The Frontier: Dresses

### PR DESCRIPTION
**Pull request by MemeSnorfer**
## About The Pull Request

(PR'ing the right branch this time)
Resprites many dresses, and adds many more.
Specifically:
Resprites all the colored skirts, black tango, red evening gown, sailors dress (reflavored to be Solarian), sundress, striped dress, white dress, and some suitskirts.
Adds an extra colored skirt, a pinafore with five other variants, a one shoulder dress, and a Kalixcian dress.
image

## Why It's Good For The Game

Your branch: Crusty, crufty, ugly
image

My branch: Cute, pretty, full of beauty
image

## Changelog

:cl:
imageadd: Resprites colored skirts, black tango, red evening gown, sailors dress, sundress, white dress, and some suitskirts.
add: Six pinafore variants, white colored skirt, one shoulder dress, and iko-ikssoal dress.
/:cl:

### CODE REVIEW

**Comment by Orchidthederg** [comment]
Do Voxxy and Keppies get to play dressup too? 🥺

**Review by rye-rice — APPROVED** [review]
No. They don't

**Comment by Orchidthederg** [comment]
Screeching. Sobbing and wailing. Someday.

**Review by Imaginos16 — APPROVED** [review]
peam

**Pull request merged**
