### PR TITLE
Ports TG's Fishing and Beam Refactor

### PR DESCRIPTION
**Pull request by BogCreature**
## About The Pull Request
Adds god's most holiest of features and the refactor code needed to run it. Also adds in new missions to add even more fishing related gameplay depth. Makes beach planets no longer populated by flying fish too, god rest their souls.
image

Ports these TG Station PRs:
https://github.com/tgstation/tgstation/pull/67691
https://github.com/tgstation/tgstation/pull/56343
https://github.com/tgstation/tgstation/pull/55193
(And probably some minor bits of other ones I'm forgetting)

## Important Image
588824fad757cd7c47e56f12b604dab6119dd3815ed4843f971e725e16609cbb_1

## Why It's Good For The Game
Adds a fun yet rewarding downtime activity. Also, you look at beach planets and tell me those weren't meant to be fished on!

## Changelog

:cl:
add: TG fishing minigame
add: Aquariums
add: The ability to fish on beach, lava, and jungle planets
add: New outpost missions
add: New fishing related outpost crates
del: Removed flying fish from beach planets and made them into actual fish
tweak: Increased the amount of outpost missions that generate at once from 15 to 20
refactor: Refactored beam code to use signals
/:cl:

### CODE REVIEW

**Comment by Erikafox** [comment]
merge conflict speedrun

**Comment by BogCreature** [comment]
I am completely unsurprised by this

**Comment by thgvr** [comment]
I only say morning
If it was a good morning, I'd be fishin'

**Comment by Sun-Soaked** [comment]
It was very cool of you to do this I think

**Comment by MrSamu99** [comment]
Finally, I can leave fish in my food expansion, as it depends on fishing (I still need to complete the desc/name changes to match lore...)

**Comment by AverageUser67** [comment]
do spears work as fishing rods?

**Comment by BogCreature** [comment]
Unless there's something I'm missing there shouldn't be any outstanding conflicts with PR #1789 anymore

**Comment by BogCreature** [comment]
Alright, I'm pretty sure this should be ready to review, all the basic mechanics are in. There's more things I want to add but I'll save those for a follow up PR that doesn't touch an unhealthy amount of files.

**Comment by BarteG44** [comment]
RDT_20230530_1549244146425121141922897

**Comment by BarteG44** [comment]
RDT_20230609_1247427467447023284774894

**Comment by AverageUser67** [comment]
Kepori currently are disgusted by worms, literally unplayable

**Comment by BogCreature** [comment]
> Kepori currently are disgusted by worms, literally unplayable

Fuck, I knew I made a critical error with this, I'm gonna need to workshop a solution to this one

**Comment by Erikafox** [comment]
OUGH

**Comment by BogCreature** [comment]
The world's most merge conflicted PR

**Review by MarkSuckerberg — APPROVED** [review]
probably fine

**Pull request merged**
