### PR TITLE
Fixing CAS cards more

### PR DESCRIPTION
**Pull request by tiramisuapimancer**
## About The Pull Request
Mostly making this PR because if people don't see it to remind me if it exists it'll sit on my branches forever and never get done. Additionally to discuss what else should be done in the future with it

removes offensive content from the Cards Against Spacemen card pools, makes some of it slightly more relevant to shiptest. 

please discuss in PR body if the following should also be removed: 
- Excessively sexual content?
- Excessively /tg/station content?

funny TO DO LIST
- [ ] Determine which content should be removed
- [ ] Remove anything determined cringe by above step
- [ ] Review this document to see how much of it is still relevant to Shiptest: https://hackmd.io/NkhzhpOeTA6FHqQ8zqL_0g
- [ ] add stuff from that document

^^^^^^ YELL AT ME TO DO THIS STUFF IF I TAKE TOO LONG PLEASE

## Why It's Good For The Game
people keep trying to play CAS but finding offensive content from cringe upstreams, we can do better. also having stuff more relevant to shiptest would be nice

## Changelog
:cl:
del: cringe CAS cards with offensive content in them
/:cl:

### CODE REVIEW

**Comment by tiramisuapimancer** [comment]
FUCK I FORGOT TO MAKE IT A DRAFT

**Comment by ToasterBan** [comment]
>Excessively sexual content?

that's like half of normal cards against humanity cards

>Excessively /tg/station content?

if they still make sense/exist in-lore they can probably still exist on the cards, otherwise they probably should be removed

**Comment by mel-byond** [comment]
Aren't Cards againt Humanity supposed to be super obscene and vulgar? But eh, agree, the ones getting removed are a pretty good riddance.  Just make sure to add some good ones in place of the ones getting removed, I'd say

**Comment by tiramisuapimancer** [comment]
eh i cant be assed to do the other stuff i'll just leave this as-is, it just removes the hitler cards

**Pull request merged**
