### PR TITLE
Removes Dwarves and Squidpeople

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
We don't want either of these in the game

## Why It's Good For The Game
See above

## Changelog

:cl:
del: Dwarves, Squidpeople
/:cl:

### CODE REVIEW

**Comment by Sun-Soaked** [comment]
a single tear comes out of bjorn orebreaker's eye as he slowly turns into dust

**Comment by Sun-Soaked** [comment]
image
someone did raise a fair point in the discord.

**Comment by Erikafox** [comment]
I checked that. The species was set to dwarf, and then they were artificially shrunk.

**Comment by BarteG44** [comment]
evil

**Comment by thgvr** [comment]
sins of the father

**Comment by Latentish** [comment]
Splatoon mains stay losing.

**Comment by Zevotech** [comment]
Can we remove flypeople and just make unsynced teleportation make you vomit or something? I have never seen a non shitter flyperson.

**Comment by Erikafox** [comment]
> Can we remove flypeople and just make unsynced teleportation make you vomit or something? I have never seen a non shitter flyperson.

They're disabled as a pickable race right now. I could in another pr though.

**Comment by Anderson-Cooper** [comment]
completely unbased

rock and stone to the bone

**Pull request merged**
