### PR TITLE
NT radio reclamation lawsuit part three.

### PR DESCRIPTION
**Pull request by axelzonvolt**
## About The Pull Request
I forgot to update shaft miner outfit pathing in my last PR and they still had the NT headset.

## Why It's Good For The Game
hahahah whoops.

## Changelog

:cl:

tweak: actually adds shaft miner outfit pathing to the meta-class.json
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
better changelog please

**Comment by axelzonvolt** [comment]
fixed the change log, though I'm going to use more gifs from now on.

**Review by Erikafox — APPROVED** [review]
y'know we could probably prevent this from happening by just changing the default datums for every job to the indie variants and auditing all our ship configs but that's a solution for some other time.

**Comment by axelzonvolt** [comment]
I did in fact bring this up in the first band-aid PR and then made a bug report listing the problem I 'solved' with band-aid fixes

**Pull request merged**
