### PR TITLE
add artificer to valor

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
as title
## Why It's Good For The Game
frequent complaint about the ship. lack of essential role (engineer) does not create meaningful inter-ship interaction. just makes it less fun to play on.
## Changelog

:cl:
add: the valor now carries an artificer
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
add butterfinger to orlando

**Comment by Apogee-dev** [comment]
Can you add a screenshot of the map changes? Doesnt need to be the whole ship, it’s like one room, but still.

**Comment by Erikafox** [comment]
image

**Comment by meemofcourse** [comment]
little guy

**Pull request merged**
