### PR TITLE
Resprites most of the old soulful hardsuits

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
Removes soul. Icons, inhands, mob states included. May do digi/kepori in the future. Inspired mostly by Azlan's work and toiled by me.
Here's a preview: 
image

## Why It's Good For The Game
Less crust more good

## Changelog

:cl:
imageadd: Most of the old hardsuits have been resprited
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
My only real complaint with these sprites is the miner, engie, and CE ones having a single shade across the entire torso, barring those two little lines. Makes them seem a lot clunkier and less flexible than they quite should be, like the character's just wearing a solid box with limbs attached. Or at the very least, they have way less definition on the torso than any of the other suits in this PR.

**Comment by thgvr** [comment]
I plan on touching miner later with a new design, if you look in discord sprite channel you can see all dirs for engi suits

**Comment by genessee-forgot-his-password-again** [comment]
It should probably touch on the Scarlet Hardsuit that we added a while ago as a weaker Syndi-suit, as a bunch of Syndicate ships use that instead of the classic Blood-Red.

Missing ERT suits, which are used for that one NT ship (as well as ERTs obviously)

Also missing Security suits - I actually don't know if these are used anywhere, but I think that's more of an oversight rather than a balance decision. It'd be good to have an overhauled hardsuit for every department.

Overall, I really like these new sprites but they need to spread to a couple more hardsuits imo

**Comment by thgvr** [comment]
I will most likely not be doing any other suits at this time

**Comment by MarkSuckerberg** [comment]
@retlaw34

**Comment by rye-rice** [comment]
@MarkSuckerberg

**Review by rye-rice — APPROVED** [review]
these are better

**Review by MarkSuckerberg — APPROVED** [review]
@retlaw34 hi !

**Pull request merged**
