### PR TITLE
[DNM] Update smash.ogg

### PR DESCRIPTION
**Pull request by tiramisuapimancer**
## About The Pull Request
Replaces smash.ogg with Hollywoodedge, Bullet Impacts Metal FS013302

## Why It's Good For The Game
image

## Changelog
dont merge this

### CODE REVIEW

**Comment by rye-rice** [comment]
image

**Comment by tiramisuapimancer** [comment]
Huh?

**Comment by tiramisuapimancer** [comment]
Wait, that might be freac taking a random-ass file from my desktop as the "album art" when I converted the file?

**Comment by tiramisuapimancer** [comment]
feel free to testmerge this as a joke, though, that's why I PRed it

**Comment by MarkSuckerberg** [comment]
Got me laughing a second time when I saw this

**Pull request closed without merging**
