### PR TITLE
Finishes the energy halberd and makes rainbow energy weapon sprites follow proper rainbow order

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Does what it says on the title. Sprites are by Imaginos and TetraZeta.
image

## Why It's Good For The Game
Energy halberd sprites were actually already a thing, this just finishes them and actually makes them usable ingame.
Previously, rainbow energy weapons actually didn't use the correct order, being Red-Green-Blue-Purple-Yellow. The change to Red-Yellow-Green-Blue-Purple is barely noticable but if I didn't fix it I would never be able to use a rainbow energy weapon again.

## Changelog

:cl:
add: The energy halberd, a previously unfinished weapon. Comes in 5 colors and a hacked rainbow version.
fix: Rainbow energy weapon sprites now actually follow rainbow order
/:cl:

### CODE REVIEW

**Comment by Imaginos16** [comment]
so based

**Review by Erikafox — CHANGES_REQUESTED** [review]
You need to add new files to the .dme

**Comment by Zevotech** [comment]
> You need to add new files to the .dme

elaborate please, i am the stupid !

**Comment by Zevotech** [comment]
wait hold on why the fuck isnt the DME in here i actually did do that

**Comment by Zevotech** [comment]
fiiiixed it :]

**Review by rye-rice — APPROVED** [review]

**Review by MarkSuckerberg — APPROVED** [review]
Seems fine, all that code being duplicated is annoying but it's probably better than unneeded inheritance

**Review by Erikafox — APPROVED** [review]

**Pull request merged**
