### PR TITLE
[still cursed] Volumetric Storage

### PR DESCRIPTION
**Pull request by Sun-Soaked**
## About The Pull Request
Revival of [This PR](https://github.com/shiptest-ss13/Shiptest/pull/850)

Back storage is now organized visually using volumetric objects of different sizes, like bay. 
This will require testing and balancing, as well as potential re-weighting, since the default code allows much larger objects to  be placed in storage(albiet taking up a whole lot of space.)
So this is a draft for now

Also ports unique trash bag behavior

May implement unique behavior for different storage objects, also like on bay.

## Why It's Good For The Game
Sudie wanted me to revive this

## Changelog

:cl:
add: Volumetric storage on backpacks.
add: trash bags now have more storage space, but only make a small amount of their contents accessible at any given time.
/:cl:

### CODE REVIEW

**Comment by Sun-Soaked** [comment]
shut up linters

**Comment by tmtmtl30** [comment]
Is there much reason to make "volume" separate from "weight class"?

**Comment by thgvr** [comment]
is this in a tm ready state or is it silly

**Comment by thgvr** [comment]
ooooooo you want to worko n this

**Comment by Sun-Soaked** [comment]
> ooooooo you want to worko n this

I grab the papers in front of me with my teeth and shake them around really fast
(ughhh ouugghhh aoooouggghhh)

Okay but seriously these are the two issues:

-I wanted to do the "backpacks can only be opened inhand"/"duffels can only be opened from floor" thing, and the code I made for it is jank/doesn't work properly

-The ui is still janky and flickers/overlaps. This is how it is on Cit as well, so I need to do a deep dive into how the UI works to see even what the problem is, and then start to think of a solution

**Comment by thgvr** [comment]
I'd leave the inventory access stuff for another pr, it's important enough to warrant it

**Comment by thgvr** [comment]
Fix your lints

**Comment by rye-rice** [comment]
> Fix your lints

linters were fixed lizard boy

**Comment by thgvr** [comment]
maybe we can tm it........

**Comment by Sun-Soaked** [comment]
confetti (tired voice)

**Comment by meemofcourse** [comment]
god

**Comment by Bimbly** [comment]
Backpacks and satchels have different storage space amounts despite them having the same move speed still, which I assume is an oversight. We tested this specifically with the captains satchel and explorer bag.

**Comment by rye-rice** [comment]
Oops hand slipped and clicked merge on 20 prs my bad

**Pull request merged**
