### PR TITLE
makes bubblegum better

### PR DESCRIPTION
**Pull request by triplezeta**
## About The Pull Request

makes bubblegums description better

## Why It's Good For The Game

better things are goodder

## Changelog
:cl:
tweak: bubblegum is now a girlboss, officially.
/:cl:

### CODE REVIEW

**Comment by AtlasRules** [comment]
https://tenor.com/view/willem-dafoe-choking-angry-mentalwards-gif-20494210

**Comment by ZephyrTFA** [comment]
I understand it's a meme and quite a few people find it funny,  but why though

**Comment by AtlasRules** [comment]
funny?????????

FUNNY???????????????????????????????

all i see is TRAVESTY

**Comment by triplezeta** [comment]
> I understand it's a meme and quite a few people find it funny, but why though

i want people to do a double-take when they examine bubblegum and go "wait, what?"

**Comment by MarkSuckerberg** [comment]
you people

**Comment by rye-rice** [comment]
make it only show the girlboss description only if the ckey is tetrazeta

**Comment by AsciiSquid** [comment]
I was expecting a proper balance update to re-include megafauna missing in ruins and all I get is an unfunny meme.

**Pull request closed without merging**
