### PR TITLE
Gecko-class Salvage Runner

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request
gecko

Adds the Gecko-class Salvage Runner as a new midsize Nanotrasen salvage ship. Comparable to the Gorlex Hyena in role and crew disposition, the Gecko has somewhat superior engineering and salvage equipment, but far less combat potential. The ship also includes two notable gimmicks: 
1. There are **absolutely no tinyfans.** Both of its salvage bays can instead be sealed off and cycled using the control stations in the bays themselves and at the Operations Chief's station behind the bridge.
2. The salvage bays come with an assortment of randomized salvage that can include wrecked Ripleys, old broken machines, abandoned crates, and maint loot. It's like a rockplanet in your cargo bay! This starter salvage can dramatically change the way the Gecko plays from round to round if you get lucky with an intact Ripley, circuit boards, or useful equipment from broken machines.

Gimmicks aside, the Gecko has these key features:

- TEG engine that leaves ample room for improvement
- Abundant engineering equipment, including mesons, advanced tools (via the CE), multiple RPDs, and an RCD
- Engineering protolathe and circuit imprinter
- Enough hardsuits and space suits for the entire crew complement, as well as a number of jetpacks
- Two blastwave jackhammers for rapidly dismantling walls
- Decent speed owing to two high-efficiency ion engines and two standard ion engines
- Limited defensive equipment (two laser guns and one spare power cell)
- No combat armor
- Severely limited medical equipment (two first aid kits, some body bags, some rollerbeds, and a bottle of formaldehyde)
- A minebot named Molly

## Why It's Good For The Game

new nanotrasen ships good, especially in a new niche

## Changelog
:cl:
add: Added the Gecko-class Salvage Runner
/:cl:

### CODE REVIEW

**Comment by Sylphily** [comment]
i would love to see this TM'd fucking looks sick man

**Comment by AtlasRules** [comment]
>be me, salvaging gecko class
>”Warning. Reactor instability detected. Meltdown in progress.”
>business as usual

**Review by Latentish — APPROVED** [review]
I'd like to see this TM'd.
I like the salvageable machines, and the "classic" miner outfit.

**Comment by Latentish** [comment]
image
This is an issue.

**Comment by ZephyrTFA** [comment]
> image This is an issue.

HUMAN. Why is there an air alarm in the engine bay?

**Comment by spockye** [comment]
pretty minor thing, but could you put some more clothing into the captains/ miner lockers? getting a single jacket and a jumpsuit as a captain feels icky.

**Comment by Ragnuv** [comment]
Hey, I advise you to put some radiation protective gear, or atleast toxin medicine onboard the ship, since the TEG produces a large amount of radiation.

**Comment by Apogee-dev** [comment]
> HUMAN. Why is there an air alarm in the engine bay?

Controls the engine bay's scrubber, which filters out CO2 and can be adjusted by opening the engine bay vent and entering from outside.

**Comment by Apogee-dev** [comment]
> Hey, I advise you to put some radiation protective gear, or atleast toxin medicine onboard the ship, since the TEG produces a large amount of radiation.

TEGs only generate radiation if you're burning tritium or somehow set up a fusion reaction because you have a deathwish. Considering the ship's limited fuel supplies and modest power draw, you really shouldn't be supersaturating your burn mix in the first place until you've made some modifications and obtained better gear, because you'll blast through all of your fuel in no time and generate massive spikes of power that your two SMESes cannot soak up.

**Pull request merged**
