### PR TITLE
Adds the Condor-Class Interceptor, as a NanoTrasen admin only vessel

### PR DESCRIPTION
**Pull request by Yellow-Mushroom**
## About The Pull Request

This Pull requests adds the NTSV Condor, an historical NanoTrasen Interceptor ship based on this note in the Corporate Wars Lore:
image

This is a functional version of the crashed interceptor that is in my current jungle ruin PR #1216 

This ship starts with:
1 commander (Cap)
1 Lieutenant (HoS)
1 Chief Engineer
4 Infrantry (Sec)
1 Maintenance specialist (Engineer)
1 Scientist
1 Paramedic
1 Medical Doctor
1 Barkeep (Chef + Bartender)
5 Recruits (staffies)
1 Janitor
1 AI

If Im being honest Im not too sure on this ship fitting that many people (or maybe that few?) Its a bit hard for me to get a feel for the size of the ship when I can only test solo and there are many roles to be filled on ship and the niche of this ship is very unique.

This ships niche and why its admin only:
1) This is a historical ship, one that would be very rare to be seen across the frontier due to its lore of being an interceptor
2) Very naval/militarily themed, which with how factions and faction interactions dynamics right now, I feel like this would lead to a lot of negative interaction between ships without atleast minor admin supervision
3) Fits the niche of admin events significantly better in general (such as a ship to mass respawn dead people on to fight pirates/rogue ships)
4) Security has access to weapons, the ports have laser weapons that can do damage to ships (but cant aim), and can detonate launched explosives (also cant be aimed)

Here are some images of the ship:
condor-3
condor-2
condor-1

(in the dark in game one it looks a bit darker than it actually is cause some lights break randomly on spawn)

## Why It's Good For The Game

This adds more potential for admin events in response to pirates, along with further pushing the corporate wars lore into the game with environmental story telling. 

## Changelog
:cl: Yellow/Myco
add: Adds the Condor-Class Interceptor, a NanoTrasen remanant of the Corporate Wars, as an admin only vessel
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
Finally... a weapon to surpass twinkle-gear

I made a NT marine vendor, do you think you could use that?
If you use it as well, do you also think you could make the weapon selection larger?

**Comment by Yellow-Mushroom** [comment]
> Finally... a weapon to surpass twinkle-gear
> 
> I made a NT marine vendor, do you think you could use that? If you use it as well, do you also think you could make the weapon selection larger?

I had it in there originally but tbh, I'm a bit nervous with adding round start available weapons to a higher pop ship, if you think it would be okay I would, but right now my solution to most issues is "ask NT Central Command if you really need them" as my explosives crates for the launchers instead have an IOU basically reading that inside of them

edit: and to note, the current vendor is locked behind the HoS door, although wouldn't be hard at all for anyone to disassemble that glass to get in in case of emergency

**Comment by Yellow-Mushroom** [comment]
Hrm, seems like I have to make actual areas :pensive: Ill fix that sometime soon

**Comment by Apogee-dev** [comment]
> > Finally... a weapon to surpass twinkle-gear
> > I made a NT marine vendor, do you think you could use that? If you use it as well, do you also think you could make the weapon selection larger?
> 
> I had it in there originally but tbh, I'm a bit nervous with adding round start available weapons to a higher pop ship, if you think it would be okay I would, but right now my solution to most issues is "ask NT Central Command if you really need them" as my explosives crates for the launchers instead have an IOU basically reading that inside of them
> 
> edit: and to note, the current vendor is locked behind the HoS door, although wouldn't be hard at all for anyone to disassemble that glass to get in in case of emergency

Remember, this ship is admin spawn only. You can throw concerns about roundstart balance out the window, because nobody's ever going to see it unless an admin already has a plan for it. Think of it in terms of a Twinkleshine, which also has a very large crew and starts the round with like five marine vendors, several M14s, an esword, and a rocket launcher.

**Comment by Yellow-Mushroom** [comment]
moving back into draft until I get time n motivation overlap to fix this up

**Comment by Latentish** [comment]
Once this is ready for review and you no longer have 3 failing checks, this should be just fine balance wise. Good job! You hit the spot just right!

**Comment by Apogee-dev** [comment]
We have two competing filename prefixes for nanotrasen ships and should probably flatten that down to one. Can you change the file names to nanotrasen_condor instead?

**Pull request closed without merging**
