### PR TITLE
Smoking no longer harm the lungs.

### PR DESCRIPTION
**Pull request by PetMudstone**
## About The Pull Request
Title. Cigarettes no longer harm the lungs when smoked.

## Why It's Good For The Game
Players no longer have to deal with rapid lung damage from smoking cigarettes and can do cool smoking things in peace.

## Changelog
:cl:
del: Smoking no longer harms the lungs.
/:cl:

### CODE REVIEW

**Comment by WindowsErrors** [comment]
just vape bro its 100 times cleaner!!!

**Comment by AsciiSquid** [comment]
Skill issue, winners don't do drugs.

**Comment by WindowsErrors** [comment]
yea but in all seriousness why???

unless your ass is like, a chain smoker or youre filming a smoking commercial or some shit (which you shouldn't, that was outlawed in the 70s) lung damage should heal up quickly enough for you to get your next mood buff

**Comment by PetMudstone** [comment]
I only opened this because Tetra requested it a long time ago. However, now that Tetra has eased up on her feelings about smoking damage I will now close dis PR.

**Comment by HighPrincessErinys** [comment]
I feel like we're better without rapid lung collapse than with. I would at the very least re-open this with a change to the rate at which nicotine damages your lungs so you can actually smoke one or two cigarettes in sequence without literally keeling over from 80 lung damage and the resulting suffocation and toxin buildup

**Pull request closed without merging**
