### PR TITLE
New Beach Ruin: Crashed engineering ship

### PR DESCRIPTION
**Pull request by Thera-Pissed**
## About The Pull Request
Adds a new beach ruin, a crashed engineering ship/camp. It has 5 enemies (4 Lobstrocities and 1 Abandoned Minebot), a radioactive pond, and a shock trap in the disassembled engine. The current loot is 2 ion engines, a fireaxe (after fixing the holofield wiring or releasing a ton of plasma), a R&D console with an engineering circuit printer, and 2 plasma cans with a tile plasma tank. 

Screenshot 2022-12-10 124437
Screenshot 2022-12-10 125143

- [ X] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
Currently there are only 4 beach ruins, and this isn't strictly a combat challenge like the others currently in. More ruins = More better.

## Changelog

:cl:
add: A new beach ruin

/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
I think this would be really good if you filled it up with dangerous engineering shit. Like maybe a burn mix held back by asingle cracked pane of directional window. Or active emitters scattered around. You could add a buncha good engi gear too if you make it more dangerous than just some rads and lobstrocities.

**Comment by Thera-Pissed** [comment]
I'll see about adding more danger, but I think I'll mostly start from scratch to do that. Otherwise, any issues with the current version?

**Comment by Latentish** [comment]
Could you please upload an image preview of the areas so I can check it?

**Comment by Thera-Pissed** [comment]
image
its all just area/ruin/unpowered

**Comment by Erikafox** [comment]
I've refrained from touching this because it's a draft, but I'd like it in the game. Please undraft or close the pr.

**Review by Erikafox — APPROVED** [review]
Ship tested maptainer approved.

**Pull request merged**
