### PR TITLE
Replaces a bunch of audio files with the TikTok TTS voice

### PR DESCRIPTION
**Pull request by goober3**
## About The Pull Request

SUE me, tiktok.

## Why It's Good For The Game

I would have a harder time explaining why this ISN'T good for the game.

## Changelog

:cl:
soundadd: new and improved sounds!
sounddel: the bad sounds
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
what the fuck

**Comment by Ms-Mee** [comment]
Firstly, no
Secondly, make your changelog more descriptive

**Comment by Ms-Mee** [comment]
Thirdly, your ball permissions have been revoked

**Comment by ZephyrTFA** [comment]
I'm not about to get sued by TikTok for using their licensed material without permission

**Pull request closed without merging**
