### PR TITLE
SKM fronties drop the pirate SKM

### PR DESCRIPTION
**Pull request by Erikafox**
:cl:
balance: SKM fronties drop the pirate SKM
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
I think apogee didn't want fronties having the chopper since it was meant more for hermits/indie pirates, I could be wrong though, @Apogee-dev

**Comment by Erikafox** [comment]
i have a vague recollection of hearing that these guys should have da chopper so lets see what apogee has to say

**Comment by Apogee-dev** [comment]
Rye is correct, the chopper’s for hermits and indie pirates. Frontie guns tend to be cheap and not the best quality, but they shouldn’t be literally held together by duct tape.

**Comment by Erikafox** [comment]
okdok

**Pull request closed without merging**
