### PR TITLE
The Interrim Mining Experience

### PR DESCRIPTION
**Pull request by Sun-Soaked**
## About The Pull Request

Recycles as much of the atomized interrim mining stuff as I could conceivably salvage.
I can move on to volumetric storage and plant stuff when this curse is finally dead

## Why It's Good For The Game
Increments mining balance again
Fixes a few bugs, I guess
People were getting pretty good at gaming netheric portals, the bonus enemies might throw 'em for a loop

## Changelog

:cl:
add: THE BEST AND GOODEST TOOL (the world's shittiest item, designed to be admin spawned for memes).
add: A spellbook for The Traps.
add: A slightly better whetstone.
add: The Slime Guardian, a support guardian optimized for healing, feeding slimes, and nourishing players.
tweak: new loot spawners for random stock parts and materials.
tweak: adjusts animorph spellbook wording.
tweak: changes wording on crisis stimpack to make what it does more clear. Reduces stimulants and adds slightly more healing.
tweak: Adds a reverse necropotence bolt. Allows hostile magicarp to have considerably more random spells. 
fix: allows the Brigador-type cyborg spawner to actually be used by non-nukeops. Also adds functionality for other cyborg spawners that can do the same.
balance: fireball spellbook recoil no longer hardgibs those who are unfortunate enough to read it second.
balance: slightly reduces cursed Katana's self-damage.
balance: boosts netheric portal enemy spawning logic, adds a few new drops.
balance: increases the cost of the Heavy Mining Kit. Doubles suits gained and adds some survival pods and deepcore drill spawners.
balance: GREATLY reduces the frequency of menacing tumor spawns. Elites now drop a chest with 3 necropolis loot items and can once again drop their special loot.
balance: adds a planet atmos immune variant to wizard simplemobs, for netheric portals.
fix: fixes way too many tumors spawning. Like, wow.
fix: fixes netheric portals only spawning a single snow legion head, instead of the actual mob
fix: prevents infinite dwarf legion trophy stacking
fix: revises the shitcode I wrote for the syndie crusher to be slightly less awful
fix: fixes the normal watcher wing trophy having the crystal wing sprite
/:cl:

### CODE REVIEW

**Comment by RDS88-beeman** [comment]
If you're making a slime guardian, can you make it available with the xenobio green/rainbow crossbreed?
Please?

**Comment by Sun-Soaked** [comment]
despair

**Comment by ArdentSpark** [comment]
I've seen someone mention in general-general that the spellbook for traps is the version that requires wizard robes/hat to use, unlike the other books in loot tables currently

I'm not too familiar with the code to confirm this

**Comment by Zevotech** [comment]
Related to spellbooks, can you remove the effects that happen when someone tries to use a used up spellbook? The fireball book flat out gibs people who try to use it when it has already been used, and there is NO WAY to tell if it has already been used even when examining it, same for other spellbooks. The others are kind of annoying (Blind spellbook permanently blinds someone or at least gives 100 eye damage from what I remember) and could be removed or changed in some way.

**Comment by Zevotech** [comment]
im only mentioning this because im too lazy to do it myself right now

**Comment by Sun-Soaked** [comment]
notice how it does not unstale after behavior is seen on the PR. currently weeping and wailing

**Review by MarkSuckerberg — APPROVED** [review]
you know, this boulder isn't going to go anywhere until we push it- and yes, we could worry about picking up the pebbles for the rest of time if we wanted to, but honestly I'm sick of it and just want this boulder out of the way so we can continue down the tunnel.

**Comment by Sun-Soaked** [comment]
the serpent is defeated, undone by a cooler serpent(marg)

**Pull request merged**
