### PR TITLE
KapuLimbs v1.1: Update Icons Soft Refactor & Clockvox

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
Soft refactor to update_icons, killing sprite sheets and replacing it with a kapulimbs based system.

New species, Clockworkdoorhinge's Vox iteration. Sprites done by Drawsstuff. This PR is a draft so I can keep my sanity.
## Why It's Good For The Game
Its about damn time these sprites got used.

## Changelog
:cl: Kapu1178, E-MonaRhg, Drawsstuff
add: Vox species
refactor: Body temperature threshholds have been generalized and dumped into species vars.
refactor: Age is now freeform
/:cl:

### CODE REVIEW

**Comment by drawsstuff** [comment]
Posting a comment to watch this PR. Best of luck, and let me know if you need anything additional sprited.

**Comment by The-Moon-Itself** [comment]
I found a bug with the vox; engie vox spawns with both a regulator and messenger bag in their back spot.

<details>
<summary>image</summary>

stacked_bag


</details>

**Comment by tiramisuapimancer** [comment]
is vox tailfeather being a main quill style and not a beard style on purpose?

**Comment by drawsstuff** [comment]
> is vox tailfeather being a main quill style and not a beard style on purpose?

It should be a beard style, coming from the creator. Beard styles should also be un-gender restricted. I've held off on making more shiptest sprites until everything's implemented properly first.

**Comment by MarkSuckerberg** [comment]
Any estimate on when this'll be merge-able?

**Comment by Sylphily** [comment]
holy fuck
its merged

**Comment by drawsstuff** [comment]
holy fuck it merged. well, time to work on the rest of the clothing

**Pull request merged**
