### PR TITLE
Temperature Feedback

### PR DESCRIPTION
**Pull request by Gristlebee**
## About The Pull Request

Original code and new alert icons by Rylie, a few bug fixes and modifications by me, and PRed on behalf of her.

The sweating alert icons specifically are from Citadel Station

Adds comfortable temperature ranges for species. Instead of the temp indicator only showing up when you hit dangerous temps and start taking damage, it will now show up once you exceed your comfortable range.

Being in temperature damage is now indicated by a sweating/fan overheat alert for organics and IPCs respectively in the case of overheating, or shivering if you're too cold.

Comfortable temp ranges are provisional, and Im open to changing them.

## Why It's Good For The Game

Gives a bit more nuanced feedback on your temperature, and provides a transition state between from "you're a bit warm" to "you are now dying of heatstroke" instead of immediately going from fine to melting alive with no HUD warning.
## Changelog

:cl: Rye-Rice, Gristlebee
add: Comfortable Temperature ranges
imageadd: Temperature HUD alerts
/:cl:

### CODE REVIEW

**Comment by Orchidthederg** [comment]
I've always wanted something like this. The first sign of "you're feeling cold" was just "oh yeah i have frostbite all over my body now haha"

**Review by rye-rice — APPROVED** [review]
after 2 years of development, hopefully it has been worth the wait

**Comment by rye-rice** [comment]
this was so lovely seeing it ingame, poor sorothy were cold at room temperture
merging!

**Comment by thgvr** [comment]
Putting a winter coat on didn't make me not feel cold, I'd like stuff like that addressed so nobody feels like something is wrong/theyre going to die and the popup doesn't go away, as well as some more test merging to iron it out a bit

**Comment by Gristlebee** [comment]
> Putting a winter coat on didn't make me not feel cold, I'd like stuff like that addressed so nobody feels like something is wrong/theyre going to die and the popup doesn't go away, as well as some more test merging to iron it out a bit

The code now takes into account if you're actively heating up or your temp is stabilizing, which should address this issue. Hopefully.

**Pull request merged**
