### PR TITLE
pronounce this robot

### PR DESCRIPTION
**Pull request by Recoherent**
## About The Pull Request
removes agender from ipcs

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
we already have they/them pronouns selectable ffs
also lets people choose which set of underwear to use and not be stupid
gay robots idk

## Changelog

:cl:
tweak: IPCs can have a little pronoun choice, as a treat. Please check and tweak those for your IPC characters, and remember that you can set it to 'Other' to keep they/them.
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
What is an IPC?

**A Miserable Little Pile Of Gender.**

**Comment by TheNeoGamer42** [comment]
robor prono

**Comment by TheNeoGamer42** [comment]
i cant believe this is failing checks because of an issue with th emetis class

**Comment by Zevotech** [comment]
nobody:
agender bearing pipe manifold in the metis xenobiology lab at (6,7): you know what'd be funny

**Comment by Recoherent** [comment]
what the fuck

**Comment by Yellow-Mushroom** [comment]
This is the Literal agenda in action

**Review by ZephyrTFA — APPROVED** [review]

**Pull request merged**
