### PR TITLE
Adds a metric fuckton of pAI faces

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Adds around 32 pAI faces

## Why It's Good For The Game

image

## Changelog

:cl:
add: Adds a lot of new pAI faces! pAIs rejoice!
/:cl:

### CODE REVIEW

**Review by ZephyrTFA — DISMISSED** [review]
alphabetize

**Comment by rye-rice** [comment]
Guh I swear I'll get to this

**Comment by thgvr** [comment]
Address the review and we can merge this I believe

**Comment by MarkSuckerberg** [comment]
yeag

**Comment by rye-rice** [comment]
done

**Pull request merged**
