### PR TITLE
Tradepost expansion

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
Majorly reworks the tradepost ruin.

Needs a few things done before it's ready for anything, mainly anywalls, needing to figure out ruin shuttle spawning, and a properer area for it. Maps are mostly done though so I'm drafting.

## Why It's Good For The Game
Reworks an old shitty ruin

## Changelog

:cl:
add: Wasteplanet_tradepost has been expanded. It sucks less now.
add: A new subshuttle, the Patrician-Class Trader.
/:cl:

### CODE REVIEW

**Comment by goober3** [comment]
image
yeah i guess you could call that a door bjarl

**Comment by meemofcourse** [comment]
i think that's an airlock assembly so it looks destroyed and cool and stuff

**Comment by goober3** [comment]
> i think that's an airlock assembly so it looks destroyed and cool and stuff

shut up,,,shut up., shut up. you're not allowed to criticize my criticisms

**Comment by meemofcourse** [comment]
> > i think that's an airlock assembly so it looks destroyed and cool and stuff
> 
> shut up,,,shut up., shut up. you're not allowed to criticize my criticisms

you ungrateful bastard im going to kill you

**Pull request closed without merging**
