### PR TITLE
Midway Rework

### PR DESCRIPTION
**Pull request by Omppusolttu**
## About The Pull Request

Rework of the midway, making it a far more robust atmospherics ship, rather than a ship with an extra atmos tank

## Why It's Good For The Game

Improving some old ships

## Changelog
:cl:
add: The Midway has been reworked
/:cl:

## Picture
midway

### CODE REVIEW

**Comment by Kapu1178** [comment]
Undocumented Changes to scrapper.dm

**Comment by Omppusolttu** [comment]
> Undocumented Changes to scrapper.dm

balls, seems like I accidentally made the .json changes to the scrapper in my scrapper rework to my master branch :waa:

**Comment by Omppusolttu** [comment]
> Undocumented Changes to scrapper.dm

Fixed

**Comment by Omppusolttu** [comment]
I'mma just remake this PR to fix the merge conflicts

**Pull request closed without merging**
