### PR TITLE
Disable roundstart ships

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
This system circumvents our design as well as timelocks

## Changelog

:cl:
add: Roundstart ships no longer spawn
/:cl:

### CODE REVIEW

**Comment by Martinpachu** [comment]
might be good to clarify that its ships that are automatically spawned by the server

**Comment by thgvr** [comment]
Ship purchasing is already separate from roundstart ships

**Comment by Sun-Soaked** [comment]
> might be good to clarify that its ships that are automatically spawned by the server

I can't believe thgvr is cancelling the ship test. From now on all players will be forced to bar rp on the outpost

**Comment by MarkSuckerberg** [comment]
make sure the code can actually handle the maplist being empty, I'm pretty sure it doesn't at the moment

**Comment by thgvr** [comment]
sigh you're right, couldn't find the code though

**Comment by MarkSuckerberg** [comment]
code/controllers/subsystem/overmap.dm#L215 spawn_initial_ships()

**Comment by thgvr** [comment]
Cool I'll check it out in a bit. might even just remove it all together lol

**Review by Latentish — APPROVED** [review]
Given this doesn't bork the system, I see no issue with this.

**Comment by thgvr** [comment]
Commented out the proc, not sure of a better solution as it does runtime trying to `pick()` from an empty list

**Review by MarkSuckerberg — APPROVED** [review]

**Review by FalloutFalcon — APPROVED** [review]
This looks fine any reason not to merge? its been test merged for a week or two atleast

**Comment by thgvr** [comment]
It's not really done properly and I don't know the proper way

**Comment by MarkSuckerberg** [comment]
just fully delete the stuff you commented out, you did it right

**Pull request merged**
