### PR TITLE
NT Sprite Overhaul

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
Overhauls our Nanotrasen sprites via the work of Imaginos

This may need some work as well as descriptions.

## Changelog

:cl:
imageadd: Nanotrasen outfits have a new coat of paint
/:cl:

### CODE REVIEW

**Comment by Skies-Of-Blue** [comment]
oh hell yes

**Comment by lectronyx** [comment]
I wish we could see these new sprites...

**Comment by Imaginos16** [comment]
I need to get another PR tm'd so I am merging this. I do not care anymore this should be in the game and it never caused a problem while it was tm'd.

**Comment by goober3** [comment]
I DEMAND!! THAT ''Imaginos16'' BE DEMOTED!!!

**Pull request merged**
