### PR TITLE
Black and White Hoodie

### PR DESCRIPTION
**Pull request by TiberianErin**
## About The Pull Request
Adds a black hoodie with grey hood to the game. Very stylish. Much wow.

image

## Why It's Good For The Game
It's rather a simple addition, and won't affect the game very much, but it would help increase the diversity of hoodies available for characters to wear. Such a simple design really, don't know why it wouldn't already be here.

Due to thgvr's request, the hoodie now also fits kepori crew.

## Changelog

:cl: TiberianEuan
add: Black hoodie with grey hood.
imageadd: New hoodie icons.
/:cl:

**Do note:**
A bunch of other commits are in there because last time I tried to publish Lethal Company 13 commits to this repo they were shot down, (which made me rather upset at the time but whatever)
They have been reverted. Those commits will not be added to the game upon merging this PR. Please ignore them. I don't know how to get rid of them from the PR itself.

### CODE REVIEW

**Review by thgvr — CHANGES_REQUESTED** [review]
Kepori alts

**Comment by TiberianErin** [comment]
okie, give me a bit, i need to go do things irl.

**Comment by TiberianErin** [comment]
> Kepori alts

where are kepori icons stored

**Comment by TiberianErin** [comment]
nevermind, found them

**Comment by TiberianErin** [comment]
having dinner out, sprites for kepori (hood on and off) and the hood on sprites for humans are complete
 when i'm back i'll test and push a new commit

**Review by thgvr — APPROVED** [review]

**Comment by thgvr** [comment]
Not exactly pleased with the prospect of alts for this, but one is fine and we can make a better solution at a later date.

**Comment by TiberianErin** [comment]
YES!!!!!!!

WOO

**Pull request merged**
