### PR TITLE
Resprites the Stechkin and APS Machine Pistol

### PR DESCRIPTION
**Pull request by Draganfrukts**
## About The Pull Request

As said in the title, this PR aims to resprite two common pistols. Uses the codebase's gun palette, and comes with the toy and suppressor stuff.
image

## Why It's Good For The Game

Removes soul.

## Changelog
:cl:
imageadd: Resprited Stechkin & APS
/:cl:

### CODE REVIEW

**Comment by Draganfrukts** [comment]
Fuck you mean error generating diffs

**Review by MarkSuckerberg — APPROVED** [review]
@triplezeta

**Review by triplezeta — APPROVED** [review]
PR these to TG too they fuck hard

**Comment by Draganfrukts** [comment]
> PR these to TG too they fuck hard

no im scared

**Pull request merged**
