### PR TITLE
Safety moth posters!

### PR DESCRIPTION
**Pull request by ElorgRHG**
## About The Pull Request
Ports the safety moth posters from here
https://github.com/BeeStation/BeeStation-Hornet/pull/1747
and here
https://github.com/BeeStation/BeeStation-Hornet/pull/1982

_Also demodularises poster sprites._

<details> 
  <summary>All the permissions from all the relevant people. Thanks again!</summary>
AspEv's

AspEv

Ayy-Robotics'
Ayy-Robotics
and 
Azlanon/Azlan's
image

 
</details>

The posters themselves

image

## Why It's Good For The Game
Safety moff

## Changelog
:cl:AspEv, Ayy-Robotics, Azlan, E-MonaRhg
add: Added Safety (and Syndie) Moth posters.
imageadd: Added the sprites for Safety (and Syndie) Moth posters
tweak: Demodularised all poster sprites.
/:cl:
_I dont know if Azlan goes by that on github, if not, someone please correct me, thanks_

### CODE REVIEW

**Comment by Nobelium-XVIII** [comment]
Can moths eat the posters

**Comment by ElorgRHG** [comment]
> Can moths eat the posters

Sadly they cannot 😔

**Comment by Nobelium-XVIII** [comment]
> > Can moths eat the posters
> 
> Sadly they cannot 😔 

:waaa:

**Comment by Martinpachu** [comment]
what happens if i dont respect the posters

**Review by Kapu1178 — APPROVED** [review]

**Pull request merged**
