### PR TITLE
Removes two ruins

### PR DESCRIPTION
**Pull request by Vexylius**
## About The Pull Request
Removes two ruins:
* "Forgottenship" that had some hostile playerspawns on a space ruin, which is not a good idea. It was designed for station-based gameplay and does not work well on ship-based gameplay that we have.
* "Whiteshipruin_box" because it's old, empty and boring.

## Why It's Good For The Game
Remove, don't improve, as they say 🗿 

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Review by triplezeta — APPROVED** [review]
yeah fair enough

**Comment by MusselMain** [comment]
Honestly, while I hate seeing ruins get removed, I fully understand, the syndicate asteroid station pretty much takes over the role of the forgotten ship, but doesn't tease the players within by leaving them with a nonfunctional ship. And the whiteship is old and empty, maybe if it was updated with actual gear and was a shiptest it could stay, but otherwise it's a waste of space.

**Comment by Vexylius** [comment]
dw, I'll add some more later

**Comment by Fikou** [comment]
> Honestly, while I hate seeing ruins get removed, I fully understand, the syndicate asteroid station pretty much takes over the role of the forgotten ship, but doesn't tease the players within by leaving them with a nonfunctional ship. And the whiteship is old and empty, maybe if it was updated with actual gear and was a shiptest it could stay, but otherwise it's a waste of space.

its just an old version of the box whiteship, which is a shiptest

**Comment by Valorium-RB** [comment]
I really like the Forgotten Syndie ship actually. If it came with some kinda small ruined ship that could actually be refurbished and piloted, I think it'd actually be really great. Plus, the more ghost spawn ruins, the better in my opinion and the Syndicate spawns are kinda unique in how they work.

**Comment by Latentish** [comment]
While I think that there are a lot of ruins that need removal, I'm not really sure we should do so incrementally. Maybe talk with the maintainers and reccomend these be taken out. It'll need a proper discussion thread as well.
Zevo and I are currently overseeing ruin audit and thinning if you'd like to talk in the discord about it as well.

**Comment by Latentish** [comment]
I agree with your choice to remove the whiteship, it's empty and meant for station gameplay, it's just a lesser shiptest with nothing on it. But I don't really agree with removing the forgottenship. I might have missed it, but I don't see any hostile ghostrole spawns, could you point those out? I think that the forgottenship is at least somewhat serviceable still.
Oh and if you're going to remove the ruin, you'll need to remove its other bits as well. any areas attached to them and remove their pathways from their respective blacklist.txt file.

**Comment by Vexylius** [comment]
> I agree with your choice to remove the whiteship, it's empty and meant for station gameplay, it's just a lesser shiptest with nothing on it. But I don't really agree with removing the forgottenship. I might have missed it, but I don't see any hostile ghostrole spawns, could you point those out? I think that the forgottenship is at least somewhat serviceable still. Oh and if you're going to remove the ruin, you'll need to remove its other bits as well. any areas attached to them and remove their pathways from their respective blacklist.txt file.

Quoting from /obj/effect/mob_spawn/human/syndicatespace/captain ghostrole spawner
"Your ship is part of the infamous \"sleeper\" doctrine of syndicate strike forces, who flung unpowered vessels with cryo-frozen crew deep into Nanotransen territory, tasked to cause havoc and carry out covert reconnisance. The chill in your bones informs you that you've been asleep far longer than intended. Your vessel appears to be in a sorry state, and a tinny alarm pierces through your fugue to report unknown contacts aboard the vessel. It's going to be one of those days."

"Protect the ship and secret documents in your backpack with your own life. Secure the syndicate assets present at your covert landing site. Prevent them, your crew, and yourself from falling into corporate hands."

I was mostly concerned with "tasked to cause havoc" and "Protect the ship and secret documents in your backpack with your own life".
This is basically an encouragement for people to do hostility and there have been cases of new players joining as that ghostrole and attacking clueless people who docked and tried to scavenge.

**Pull request closed without merging**
