### PR TITLE
IPC blush screen

### PR DESCRIPTION
**Pull request by PiperDoots**
## About The Pull Request

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

Adds a blush screen with blinking animations to IPCs as requested on the discord.

## Why It's Good For The Game

More IPC customization is always good to have and it's cute :)

blushyspin
blushy2

## Changelog

:cl:
imageadd: added blush screen to IPCs
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
😳

**Review by triplezeta — APPROVED** [review]
ok

**Comment by Ketrai** [comment]
People like you-
Better spend an hour writing an essay on the scientific benefits or having a blush mode on that monitor.

**Comment by Recoherent** [comment]
essay is as follows:
"This robot is gay. Therefore, deploy blush. QED."

**Comment by PiperDoots** [comment]
> People like you- Better spend an hour writing an essay on the scientific benefits or having a blush mode on that monitor.

It's cute. Send essay.

**Pull request merged**
