### PR TITLE
MODsuits Port

### PR DESCRIPTION
**Pull request by MrSamu99**
## About The Pull Request

MODsuits. I don't know how to make beautiful descriptions with checks and other fluff. Later this will be changed

## Why It's Good For The Game

Utility and protection. Excellent.

## Changelog

:cl:
add: Added MODsuits
/:cl:

### CODE REVIEW

**Comment by genessee-forgot-his-password-again** [comment]
oh fuck yes. oh hell yes

**Comment by Calyxman** [comment]
No. Please. Please. No. I'm begging you.
Bay RIGs were cool.
TG MODs manage to feel like a worse, less useful version of RIGs.
Please.

**Comment by MrSamu99** [comment]
@Calyxman 
I'm trying to make them better. Armor module would be available for everyone after research, so protection is the same as hardsuits have. And since this PR is draft you can suggest your idea how to make them better

**Comment by Valorium-RB** [comment]
Does this remove hardsuits or simply add MODsuits as a thing you can make/find?

**Comment by Sun-Soaked** [comment]
> Does this remove hardsuits or simply add MODsuits as a thing you can make/find?

don't give me ideas, Valo 😈
(Real though: we could probably keep hardsuits as "voidsuits", like they are on bay)

**Comment by MrSamu99** [comment]
This DO not remove regular hardsuits. They have some advantages over MODs. Since if you are missing an arm or a leg, you aren't protected from space, but with hardsuit you are. This 100% bug, but we can make it a feature

**Comment by axelzonvolt** [comment]
modsuits don't have enough content AS STANDS to even be worthwhile, let alone accounting for research/material/financial costs AND how awful they are to use in a hurry.

throw it bake in the oven. it's not done being baked yet.

**Comment by thgvr** [comment]
Keep up the good work. Hope this works out well.

**Comment by MrSamu99** [comment]
Can someone explain how to fix tgui? Only it fails checks

**Comment by ZephyrTFA** [comment]
You need to run prettier

**Comment by MrSamu99** [comment]
Where I can find it?

**Comment by Calyxman** [comment]
> @Calyxman I'm trying to make them better. Armor module would be available for everyone after research, so protection is the same as hardsuits have. And since this PR is draft you can suggest your idea how to make them better

Make them more like DS13 RIGs. Simple as.
Their equip/unequip takes too long, with mediocre modules. They don't even let you wear storage on your back, and the tradeoff really just isn't worth it in general.
They feel absolutely awful to use.
Then again, my opinion means nothing since I barely play /tg/ or use the MODsuits.

**Comment by BarteG44** [comment]
> > @Calyxman I'm trying to make them better. Armor module would be available for everyone after research, so protection is the same as hardsuits have. And since this PR is draft you can suggest your idea how to make them better
> 
> Make them more like DS13 RIGs. Simple as. Their equip/unequip takes too long, with mediocre modules. They don't even let you wear storage on your back, and the tradeoff really just isn't worth it in general. They feel absolutely awful to use. Then again, my opinion means nothing since I barely play /tg/ or use the MODsuits.

i believe that the thing you wear on your back IS a backpack

**Comment by MrSamu99** [comment]
> > > @Calyxman I'm trying to make them better. Armor module would be available for everyone after research, so protection is the same as hardsuits have. And since this PR is draft you can suggest your idea how to make them better
> > 
> > 
> > Make them more like DS13 RIGs. Simple as. Their equip/unequip takes too long, with mediocre modules. They don't even let you wear storage on your back, and the tradeoff really just isn't worth it in general. They feel absolutely awful to use. Then again, my opinion means nothing since I barely play /tg/ or use the MODsuits.
> 
> i believe that the thing you wear on your back IS a backpack

If you insert storage module to the control unit it would work like backpack. Normal capacity storage smaller than the backpack, while large capacity is the same. So after researching Large capacity storage MODs can be used like normal backpack

**Comment by Sun-Soaked** [comment]
we can faff around with balance and implementation when we have The Thing-

Also note these are White Dream modsuits so the balance may be different to what you're all familiar with.
Just wait and see when they're in, I guess

**Comment by tmtmtl30** [comment]
I'd recommend against including research in this PR, since I have fairly specific but long-term preferences on how I want modsuits to be balanced. I'm fine with them hanging around in the code until then, though.

**Comment by AverageUser67** [comment]
Yeah this would be really cool if we have this alongside hardsuits. Best of both worlds and if it proves to be bad we can nuke it from orbit.

**Comment by Fikou** [comment]
@Calyxman
> Make them more like DS13 RIGs. Simple as.

So the equip/unequip taking longer, with less modules and way clunkier? I think those were the issues you wanted to avoid

**Comment by MrSamu99** [comment]
Equip speed can be easily adjusted, so this is not a problem at all

**Comment by genessee-forgot-his-password-again** [comment]
image

TGUI is in russian.

**Comment by BarteG44** [comment]
can't click on the empty spots to put shit inside the modsuit
image

**Comment by genessee-forgot-his-password-again** [comment]
image

Right-click pulls up context menu instead of retracting/deploying all of MODsuit pieces.

**Comment by genessee-forgot-his-password-again** [comment]
image

Armor booster module overlay doesn't go away when helmet is retracted.

**Comment by MrSamu99** [comment]
> can't click on the empty spots to put shit inside the modsuit image

Idk how to fix this now, storage code is scary

**Comment by MrSamu99** [comment]
> image
> 
> Armor booster module overlay doesn't go away when helmet is retracted.

Also idk how to fix. Even the latest skyrat, where i took this feature has this problem (ignore this beautiful beard)
изображение

**Review by Fikou — CHANGES_REQUESTED** [review]
1. why is there a modules.dm file with random modules in it
2. why are you porting datum storage but only making modsuits use it? port it in a separate pr (and make everything use it) or revert modsuits to use component storage
3. prototype hardsuit has to use the trait_reagent_scanner added by modsuits. delete the clothing flag it used

**Comment by MrSamu99** [comment]
> 1. why is there a modules.dm file with random modules in it
> 
>     2. why are you porting datum storage but only making modsuits use it? port it in a separate pr (and make everything use it) or revert modsuits to use component storage
> 
>     3. prototype hardsuit has to use the trait_reagent_scanner added by modsuits. delete the clothing flag it used

1. Deleted it
2. Component storage doesn't have an ability to open storage from interaction with another object. Or i didn't found it. So i ported the datum storage
3. With the last commit I made MOD reagent scanner to use old SCAN_REAGENTS clothing flag, instead of trait. Because it would be a trait only for 2 modules, while there are an existing alternative

**Comment by goober3** [comment]
I think it's fucked up how u can't transfer the contents of ur backpack to modsuits. also. I think this suggestion's been made before but. u should make modsuits be able to be activated whilst ur moving

if these are becoming standard on ships, u should do something about the charge. either, like. make cells last longer in them and add cell chargers to ships with modsuits, or remove modsuit charge entirely.

**Comment by MrSamu99** [comment]
> if these are becoming standard on ships, u should do something about the charge. either, like. make cells last longer in them and add cell chargers to ships with modsuits, or remove modsuit charge entirely.

Fun fact. MODs already have 1/5 of their initial power consumption (at least comparing with the initial codebase, where I took the code)

**Comment by meemofcourse** [comment]
right clicking with the mod paint kit only opens the context menu

**Comment by MrSamu99** [comment]
> right clicking with the mod paint kit only opens the context menu

currently we don't have MODsuit painting mechanic. Only theme changing

**Comment by githubuser4141** [comment]
> modsuits don't have enough content AS STANDS to even be worthwhile, let alone accounting for research/material/financial costs AND how awful they are to use in a hurry.
> 
> throw it bake in the oven. it's not done being baked yet.

If MODsuits don't have enough content then I hope you don't see current era Hardsuits. Aka silly clothes you take on/take off with zero consquence, as opposed to MODsuits having an unique UI, unique mechanics, sprites, etc etc. Also research/material/financial.... that's all 'value changes' that can be changed by any non-coder, at any time if needed. None of those problems are unique to MODsuits.

**Comment by spockye** [comment]
image

still some russian text around.

**Comment by thgvr** [comment]
bump ;(

**Comment by thgvr** [comment]
hello pls fix conflicts

**Comment by MrSamu99** [comment]
I close this PR because I won't have time for it for at least 3 months 
image-13

**Comment by Admiral-Gigaton** [comment]
> I close this PR because I won't have time for it for at least 3 months image-13

based but sadge

**Pull request closed without merging**
