### PR TITLE
Kilo Technical Pass 2

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
Updates the Kilo, again.

I wasn't happy with the cargo airlock and it needed a few other technical fixes.

- [x] Map loads

## Why It's Good For The Game
The inexorable march of progress continues.

## Changelog

:cl:
tweak: The Kilo has received a few technical updates, including removing the jank-ass cargo airlock for a holofield.
fix: The Kilo's fore airlock should actually work now
/:cl:

### CODE REVIEW

**Review by Apogee-dev — APPROVED** [review]
Nothing more to add, good improvements all around and it'll be nice to have the Kilo up to standards again. Also, good on you for preserving the gunk the Kilo deserves.

**Comment by Latentish** [comment]
Test marg (You know this)

**Comment by goober3** [comment]
Test marg (You know this)

**Comment by Latentish** [comment]
we're marging tonight

**Pull request merged**
