### PR TITLE
Keppification

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Finally changes your beloved dinosaur-adjacent friends to be their proper sprite!
<details>
<summary>See examples of the full new sprites here! (Many more not shown.)</summary>

</details>

### TODO
- [x] Fix bedsheet sprites (broken for some reason)
- [x] Make backbag sprites actually work

## Why It's Good For The Game
We've been wanting to make Kepori unique pretty much since we added them. This is the final piece of the puzzle, I believe, to making them entirely their own thing! It also just generally improves the sprite quality greatly both obviously of the Kepori themselves, but also their clothing.

## Changelog
:cl:
imageadd: Totally resprites Kepori!
imageadd: Totally resprites Kepori feather patterns, as well. There's a lot more than there used to be!
add: Kepori now have sprites for bedsheets and belts.
tweak: Kepori body size adjustment removed for sake of sprite clarity.
code: Added a new, better offset system copied from Baystation 12.
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
that sprite offset system is fucking genius

**Comment by PrefabQuasar** [comment]
vitally important question: do wigs still fit on the new kepori

**Comment by PiperDoots** [comment]
Yup! All hats, glasses and earpieces are just offset so they should work normally.

**Comment by PrefabQuasar** [comment]
> Yup! All hats, glasses and earpieces are just offset so they should work normally.

image
are you sure about that

**Comment by PiperDoots** [comment]
Alright apparently not, thanks for pointing it out!

**Comment by PrefabQuasar** [comment]
in good news though, my existing character translates really well into the new sprites!
image

**Comment by PiperDoots** [comment]
> in good news though, my existing character translates really well into the new 

Awesome! Glad to hear.

**Comment by DogZeroX** [comment]
I'm glad Mark is working on kepori instead of metaverses.

**Comment by TallDeekus** [comment]
Priorities


Oh also, idea, add actual code for stacking multiple Kepori and wearing a trenchcoat to look like one person.

**Comment by drawsstuff** [comment]
very nice! they look great

**Comment by francinum** [comment]
Lovely work

**Comment by MarkSuckerberg** [comment]
Both issues resolved, fully ready for a testmerge whenever Klimbs 1.1 gets in.

**Comment by PrefabQuasar** [comment]
> Both issues resolved, fully ready for a testmerge whenever Klimbs 1.1 gets in.

the wig helmet issue is still present, as are neck items being scuffed
image
image

**Comment by tiramisuapimancer** [comment]
Holding items in the mask slot tends to cause something (?) to appear over your face

**Comment by MarkSuckerberg** [comment]
image
and thus the wigpori metagang shall return

**Comment by MarkSuckerberg** [comment]
Resolved the mask bug, the wig bug, the mask-items-not-fitting-in-the-mask-slot-because-they-were-too-big bug, among other things

**Pull request merged**
