### PR TITLE
Gun rework

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request
WIP.

if it wasn't obvious, very based off tgmc 

this reworks how guns work, by making them 4x more lethal without touching a single damage value

its a bit difficult to put into words what this does, so i think these 3 gunfights i did with a good friend explains it better than i ever could

https://streamable.com/09in19
https://streamable.com/yel56o
https://streamable.com/x2a0he

if you didnt watch these videos:
- New guns sounds, TGMC as usual. but some racking sounds are from CEV eris
- guns now can be wielded, if unwielded, they may cause recoil which not only makes your shots less accurate, but 'scrolls' your screen
- new suppression effects
- getting hit hard enough scrolls your screen
- anything getting hit shakes you as feedback, not just bullets
- bullets can ricochet naturally upon hitting a surface at a step angle. does not auto aim at your target, so be careful. ricochet sfx taken from CEV eris
- new effects for bullet impacts. sound effects were taken from TGMC and https://github.com/Skyrat-SS13/Skyrat-tg/pull/11697
- adds the cattleman revolver and Himehabu 22lr pistol. sprites by yours truely

big problem is, in order for all of this to work, a certain key needs to be binded to rack the gun. by default this is SPACE, but moost already have it binded to 'hold throw mode', which is an issue. for one, not only you need to ask everyone to rebind their controls to a very important key, but also a key dedicated to just racking the gun can cause issues. im up for any solutions

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

people dont fear gunfights. they think its just a way to pvp. people should be afraid of gunfights, feel the pain OOCly when their blorbo gets hit

## Changelog

:cl:
add: 22lr and cattleman revolver
add: many gun sounds
balance: guns reworked
/:cl:

### CODE REVIEW

**Comment by murder357** [comment]
i dont feel like relearning guns or going through 90 steps during a tg fight to equip a gun

**Comment by rye-rice** [comment]
you know i forgot i even made this pr wtf

**Comment by rye-rice** [comment]
ill finish this some other day but now is not that day

**Comment by rye-rice** [comment]
told you

**Comment by thgvr** [comment]
I'm putting my thoughts here for official-ness but I believe wield should be a separate key such as Eris does, maybe even extending the behavior in the same way Eris does.

**Comment by tmtmtl30** [comment]
Yeah, IMO it makes most sense for rack to be kept on the same key and for wield to be a separate button. I'd need to look at the code, but you could theoretically link it to the twohanded component directly.

**Comment by BarteG44** [comment]
The little jiggle after getting hit looks hella goofy

**Comment by Addust** [comment]
my fucking USE INHAND key you RAT BASTARD

**Comment by Addust** [comment]
MOVE WIELDING OFF USE INHAND TO A SPECIAL WIELD KEYBIND

**Comment by Imaginos16** [comment]
Do not harass our contributors. User was temporarily blocked for needless inflammatory remarks.

**Comment by BarteG44** [comment]
The github drama is real

**Comment by rye-rice** [comment]
TMed this for a couple of rounds, very happy how it came out and changes the dyanmic of gunfights

**Comment by rye-rice** [comment]
Should be ready to review, no clue why test is failing

**Comment by Addust** [comment]
in a more polite phrasing of my previous statements,

Please do consider placing wield on a seperate key to ensure playerbase sanity. Of course, masochists will retain the option to wield with the use inhand key willingly, but allowing the players to choose between wielding with Z and wielding with literally any other key without losing Z as a use inhand key will greatly improve the gameplay experience with this PR.

**Comment by thgvr** [comment]
It will be done but not in this pr

**Comment by Addust** [comment]
> It will be done but not in this pr

ok

**Review by MarkSuckerberg — APPROVED** [review]
seems fine

**Review by thgvr — APPROVED** [review]
yeah. send it

**Comment by MarkSuckerberg** [comment]
let's fucking go

**Pull request merged**
