### PR TITLE
carrier improvements

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

tartarus is no longer a roundstart ship
tartarus now has a working camera system
tartarus now has kinda working cells
tartarus now starts without air in the external areas
tartarus now has an r&d console board in the storage
tartarus now starts with the seclathe prebuilt rather than as a board
tartarus now has a super pacman in the engine
tartarus now has air supply
tartarus now has firelocks

## Why It's Good For The Game

it needed some love

## Changelog
:cl:
tweak: the tartarus carrier has been improved a bit
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
> starts without uranium
:constipation:

**Comment by Fikou** [comment]
> > starts without uranium
> > :constipation:

troled

**Comment by Apogee-dev** [comment]
Could you add intercoms and/or roundstart pocket radios? Also the config should be updated with ship prefix, namelists, and custom outfits (unless it’s intended to be nanotrasen, it probably shouldnt use NT sec gear)

**Review by triplezeta — APPROVED** [review]
ok

**Pull request merged**
