### PR TITLE
Yard Class Ancient Cargo Ship

### PR DESCRIPTION
**Pull request by Dexxiol**
Hi, this is my first pr and actual mapping work here.
Sadly there is no screenshots due my pc's RAM issues.

UPD: fixed some issues with pc and now im able to send screenshots, here image of the ship

## About The Pull Request
Adds another tide-class-esque ship, its quite huge and offers tons of trash (actual trash).
If some stuff needs to be removed, feel free to bug me on discord or here.

## Why It's Good For The Game
I dont think it is myself, literally tide class but large and bit richer

## Changelog
:cl:
add: Yard class ship
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
Map file looks like it's corrupted or something. You might need to remake it entirely.

**Comment by Valorium-RB** [comment]
Picture of the vessel?

**Comment by Dexxiol** [comment]
> Picture of the vessel?

none because i already said why

**Comment by Dexxiol** [comment]
but if everyone really want to see, have this bad phone photo of my map


UPD: its old, look above

**Comment by Valorium-RB** [comment]
> > Picture of the vessel?
> 
> none because i already said why

I just wanted to see what arcane method would be used to depict it, glad your PC got fixed

**Comment by Dexxiol** [comment]
> > > Picture of the vessel?
> > 
> > 
> > none because i already said why
> 
> I just wanted to see what arcane method would be used to depict it, glad your PC got fixed

its not fixed, i just figured out how to make sdmm not to murder my computer this instant, but if you wondering, new pc will be somewhere mid summer

**Comment by PrefabQuasar** [comment]
personally i don't see any reason to merge this, you admit yourself that it isnt good for the game

**Comment by Dexxiol** [comment]
> personally i don't see any reason to merge this, you admit yourself that it isnt good for the game

i did thought of that, but also i think there would be people who want to build around in poor conditions, tide class simply doesn't have space and expanding the ship is painful

**Comment by PrefabQuasar** [comment]
the BYO already fills pretty much the same niche, and we really dont need more ships unless those ships are exceptionally good, we already have So Many Fucking Ships

**Comment by Dexxiol** [comment]
> the BYO already fills pretty much the same niche, and we really dont need more ships unless those ships are exceptionally good, we already have So Many Fucking Ships

byo is different, it doesn't give that tide-esque vibe

**Comment by Dexxiol** [comment]
and there is indeed many ships, but i only consider sugarcube, hightide and normal tide as poor condition ships

**Comment by Dexxiol** [comment]
but problem is, you cant build shit there without expanding the ship which may break entirety of it if you are careless

**Comment by Dexxiol** [comment]
yard class solves it, and i think it does pretty well

**Comment by PiperDoots** [comment]
Main problem I have with it is that it's literally just a retangle with a circle ontop trying to fill a niche that's already being covered by the BYO

**Comment by Apogee-dev** [comment]
agreed with most of the others here. i'm happy to help this be as good as it can be, but at the end of the day it *is* competing for a filled niche. i'd be more amenable to something designed around this kind of concept if it had a bit more interest going on at least. for example, a maint maze that you could weld down to open up into building space or a ship built into a chunk of asteroid you could mine out- in other words something that brings more interest into the building process than just availability of open space, but doesn't require wrangling with blueprints.

**Comment by Dexxiol** [comment]
> Main problem I have with it is that it's literally just a retangle with a circle ontop trying to fill a niche that's already being covered by the BYO

what would you expect, if you think about it, ship wasnt made by engineers but random greyshirts with almost no engineering skills

**Comment by PiperDoots** [comment]
You decided to start working on this after I pointed out a certain shape you should not be building ships in. And then made it that exact shape.

**Comment by Dexxiol** [comment]
either way, merge or not is up to you all, if it will actually succeed ill get working on ruins anyway

**Comment by Dexxiol** [comment]
> You decided to start working on this after I pointed out a certain shape you should not be building ships in. And then made it that exact shape.

aerodynamics is no, flying squares can exist, oh hell, have you seen the damned sugarcube? isn't it just a rectangle too

**Comment by PiperDoots** [comment]
> > You decided to start working on this after I pointed out a certain shape you should not be building ships in. And then made it that exact shape.
> 
> aerodynamics is no, flying squares can exist, oh hell, have you seen the damned sugarcube? isn't it just a rectangle too

The sugar cube is not a good example of an interesting ship. It exists specifically to replace the pill. A rectangle with a circle on top is literally the most uninspired ship design there is.

**Comment by Dexxiol** [comment]
> > > You decided to start working on this after I pointed out a certain shape you should not be building ships in. And then made it that exact shape.
> > 
> > 
> > aerodynamics is no, flying squares can exist, oh hell, have you seen the damned sugarcube? isn't it just a rectangle too
> 
> The sugar cube is not a good example of an interesting ship. It exists specifically to replace the pill. A rectangle with a circle on top is literally the most uninspired ship design there is.

thats not a circle, but lets say if i would cut some corners, would that be acceptable then?

**Comment by Apogee-dev** [comment]
Let's try to be professional here. If you're going to argue take it to #shipyard at least so the comments here don't get flooded.

**Comment by Dexxiol** [comment]
and i didnt meant my ship to be interesting in something, its purpose to hold lots of trash, crates and other useless garbage, it is cargo after all

**Comment by Zevotech** [comment]
cargonia ship

**Comment by MusselMain** [comment]
> the BYO already fills pretty much the same niche, and we really dont need more ships unless those ships are exceptionally good, we already have So Many Fucking Ships

Naw, Shithole tiderships are what sells, I'm always up for a nasty monstrosity challenge, and I really like the forced improvisation it causes their crews to do.

**Comment by Dexxiol** [comment]
ill save this class for later edits and stuff but for now it goes to land of dead

**Pull request closed without merging**
