### PR TITLE
Vox Sprite Update - Scarves and other Assorted Items

### PR DESCRIPTION
**Pull request by firebudgy**
## About The Pull Request
For some reason while watching Gundam I got the urge to sit down and start doing things, so here I am.
Creates onmob_neck_vox.dmi for Vox neck items.

Adds Vox sprites for all the striped scarves in-game to Vox, as well as Shemaghs, Cameras and the Stethoscope.
And chest-high towels.
And industrial jackets.
And updates the palette on security HUDs and medical HUDs.

image
image
image
image
image
image
image
image
image

## Why It's Good For The Game

Adds more supported items for the Vox, which is pretty cool I think. Hopefully, plenty of people will appreciate the more customization options.

## Changelog

:cl:
add: Sprites for several different kinds of scarves for Vox!
add: Additional sprites for several other items for Vox, such as chest-high towels and hazard jackets.
add: Created onmob_neck_vox.dmi file, plus enabled support for it.
/:cl:

### CODE REVIEW

**Comment by Leon9621** [comment]
I certainly will! Coulda sworn the blue striped scarf showed up... might have defaulted to something else I thought was close enough. TY, nonetheless

**Comment by firebudgy** [comment]
god I accidentally built this on my previous sprites PR. shouldn't cause any issues because it got merged already I hope

**Review by rye-rice — APPROVED** [review]
Good work, the old sprites that were converted I'm not too worried about the quality of.

As a heads up thgvr keeps repeating they will resprite vox but I wouldn't expect that in the near future

**Comment by firebudgy** [comment]
No hard feelings if these aren't ported whenever that happens, I've just kinda accepted that

**Review by thgvr — APPROVED** [review]

**Pull request merged**
