### PR TITLE
Synthetic Sarathi! (VERY MUCH A WIP)

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Adds a new race (or eventual subtype of IPC once we actually have that functionality), the Integrated Positronic Sarathi! (name subject to change)
This race is functionally similar to IPC gameplay wise, with the only exceptions being that they have tails, can speak Kalixcian Common, are digitigrade and whatever other things that are innate to sarathi that I still need to add. This PR is still a draft and a lot of the information in it is subject to change.

CHECKPOINTS:
- [x] Playable Race, prefs not required
- [ ] Playable Race with prefs and selectable in character creator
- [ ] Sprites and Species Limbs
- [ ] Playable Race with sprites and digitigrade functionality
- [ ] Bug testing and final adjustments
- [ ] Lore, probably

- [ ] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
A somewhat large amount of people expressed the desire for synthetic lizards to be playable, so me being the dumbfuck I am I decided to try coding them. Thgvr has offered to create and provide sprites, so hopefully no porting will be necessary for any code or sprites.
Any suggestions or advice are welcome to be DM'ed at zevo#5856 on discord.

## Changelog

:cl:
add: Synthetic Sarathi as a playable race (hopefully soon)
/:cl:

### CODE REVIEW

**Comment by PiperDoots** [comment]
Making this a separate species instead of adding a tail option and waiting for the language changes feels like a very weird way of doing it IMO.

**Comment by Zevotech** [comment]
> Making this a separate species instead of adding a tail option and waiting for the language changes feels like a very weird way of doing it IMO.

image

**Comment by Zevotech** [comment]
ONE CHECK DONE
image

**Comment by TallDeekus** [comment]
No way! Looks sick so far, but obligatory Digitigrade.

**Comment by Zevotech** [comment]
> No way! Looks sick so far, but obligatory Digitigrade.

They are digitigrade (I THINK?). The sprites just dont reflect that yet.

**Comment by TallDeekus** [comment]
### Yet?

This bodes well for fishing season.

**Comment by ZephyrTFA** [comment]
If possible I would prefer to make it to where being synthetic is a toggle and not a dedicated race

**Comment by ZephyrTFA** [comment]
aka you can have any race be a synthetic, and the preference modifies biotypes, bodytypes, breaths, language, blahblahblah

**Comment by Zevotech** [comment]
> aka you can have any race be a synthetic, and the preference modifies biotypes, bodytypes, breaths, language, blahblahblah

Thats awesome and really cool, but sounds way out of my scope and like something that would be better worked on by a team of competent coders. 
If it helps, I did talk with piper about potentially implementing the whole subspecies menu and all before actually undrafting this. That seems like a more logical path to follow instead of an entire refactor to how synthetic race preferences are chosen or whatever you just asked of me.

**Comment by TallDeekus** [comment]
> > aka you can have any race be a synthetic, and the preference modifies biotypes, bodytypes, breaths, language, blahblahblah
> 
> Thats awesome and really cool, but sounds way out of my scope and like something that would be better worked on by a team of competent coders. If it helps, I did talk with piper about potentially implementing the whole subspecies menu and all before actually undrafting this. That seems like a more logical path to follow instead of an entire refactor to how synthetic race preferences are chosen or whatever you just asked of me.

I'd have to agree, plus there is no harm in a temporary if experimental implementation till a more refined product is made.

**Comment by Recoherent** [comment]
> aka you can have any race be a synthetic, and the preference modifies biotypes, bodytypes, breaths, language, blahblahblah

hello `subspecies`, local shiptest codebase white whale. it's on my list of "things i want to get the ball actually rolling for" over codebreak but until that's a real thing here we are; weird implementation is fine so long as we can at least figure out how to cleanly shift it over to whatever other system happens

**Comment by Recoherent** [comment]
that'll need to happen for a bunch of other species anyways so in theory it won't add too much actual overhead (the joke is that it will inevitably add weird actual overhead)

**Comment by Ms-Mee** [comment]
Me on my way to spend the next 5 months slowly chipping away at ideas I have for a system that would allow for subspecies but it wouldn't be the system's focus (I am going beyond insane)

**Comment by ZephyrTFA** [comment]
Let me know if you're still working on this via Discord

**Comment by Zevotech** [comment]
> Let me know if you're still working on this via Discord

waiting on news regarding the sprites from thgvr, sorry

**Pull request closed without merging**
