### PR TITLE
Item size tweaks (and bonus medipen resprite)

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
Tweaks various item sizes (basically off of vibes) in order to make them more reasonable and in line with volumetric storage.

image

Also resprites medipens. They're pretty cool. Design inspired by infrared_baron.

## Changelog

:cl:
add: Allows hand radios to be held on your neck slot
balance: Adjusted the item size of various guns and misc objects, see pr #3509 for more info
imageadd: Overhauled the look of autoinjectors
/:cl:

### CODE REVIEW

**Review by rye-rice — APPROVED** [review]
this goes insanely  hard, feel free to screenshot

still wish there was like, a middle ground between small and normal, and normal and bulky, but spritewise this is amazing

**Comment by Sun-Soaked** [comment]
looms ominously

**Comment by thgvr** [comment]
code for all this is weird, it doesn't work with medkits. i'll probably save those for later.

**Comment by thgvr** [comment]
ill fix this soon

**Comment by Sun-Soaked** [comment]
> ill fix this soon

`o    o`

**Review by Sun-Soaked — APPROVED** [review]
yes

**Pull request merged**
