### PR TITLE
[WIP][DNM]Sarathi Organ Update

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
Ports https://github.com/tgstation/tgstation/pull/61440/ (slash finishes)
Ports https://github.com/tgstation/tgstation/pull/59801 (not ethereal stuff - later day)
Ports https://github.com/tgstation/tgstation/pull/56959

This pr updates Sarathi organs, as well as some unique effects similar to the original tgstation pr from Fikou.
The plan is:
Higher metabolism, with brute(maybe more?) regen that costs nutrition, I may expand this to be more bay-style with limb and organ regeneration, but have going hungry be near-lethal in effects.
Sarathi livers are worse at processing toxins and alcohol.
Sarathi will trip sometimes when running around with no tail.
Sarathi take slightly more toxin damage, and are slower to operate on with surgery.
A second heart organ that gives a slight net gain in total blood generation, with less blood generation on their normal heart.

Here's a preview of the organs, done by me, inspired by EOBGames and Fikou of tgstation:

image

## Why It's Good For The Game

More unique species things make the world go round.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by AverageUser67** [comment]
can you PLEASE swap the brains colors around so it isnt mostly blue

**Comment by thgvr** [comment]
Sprites aren't final dw

**Comment by thgvr** [comment]
I will work on this more soon

**Comment by thgvr** [comment]
by soon I mean probably after blood stuff is merged

**Comment by Sweettoothart** [comment]
>Sarathi take slightly more toxin damage, and are slower to operate on with surgery.

Sarathi do have the ability to digest welding fuel for small hand fires, I feel like they should be more resistant to the toxins you gain from that (at least specifically for welding fuel?)

**Comment by thgvr** [comment]
Yeah it's all wip. I'll work on it eventually

**Comment by thgvr** [comment]
I'll come back to you one day.

**Pull request closed without merging**
