### PR TITLE
Fixes Ship Random Namelists

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Fixes namelists... not actually working.

## Why It's Good For The Game
Flavourful names :pleading_face:

## Changelog
:cl:
fix: Ship namelists actually <i>work</i> now.
/:cl:

### CODE REVIEW

**Comment by Nobelium-XVIII** [comment]
Good PR, still gonna speedrun naming my ship "amogus"

**Comment by MarkSuckerberg** [comment]
:trollface:

**Comment by Zevotech** [comment]
Good PR, still gonna speedrun naming my ship "Fortuna"

**Comment by Nobelium-XVIII** [comment]
> Good PR, still gonna speedrun naming my ship "Fortuna"

so much soul

**Pull request merged**
