### PR TITLE
Makes powering the defibs on Geneva more obvious

### LINKED ISSUE #809: [BUG] Geneva Defibs Being Painful To Power
## Reproduction: 
Step 1: Play on a Geneva
Step 2: See that the defibs are unpowered at the start as they lack cells
Step 3: Realize there is no cell charger.
Step 4: Realize that you need to put cells in the APCs just to have functional defibs aside from le epic combat defibs.
Step 5: p a i n

### PR DESCRIPTION
**Pull request by disappointedButNotSuprised**
## About The Pull Request

This PR is ment to fix #809 that complains about the Geneva defibs not having a battery roundstart and playes not having a clue how to get them since there are no batteries there and also no battery charger.

The gimmick of the ship is that it has a full botany setup, this implies that potato cells are to be used. Since not everyone knows about potato cells, the proposed solution is to add relevant seeds and cable coil in plain sight and also a sample potato battery. The problem is that even then players will get confused because standard potato cells are rated 300kJ and a defib requires min. a 1000kJ cell, so you need to grow a somewhat good potato to make them work (potency of the plant is proportional to the max charge).

To make all of the above obvious a fluff paper instruction describing construction of the cell and also the min. rating for the defib was added as well.

## Why It's Good For The Game

Preserve the gimmick of botany powered defibs on Geneva while making it easier to get for new players.
 
## Changelog
:cl:
add: Powering the defibs on Geneva was made more obvious
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
your username fits perfectly for the tone of this PR, god bless

**Comment by Sylphily** [comment]
I would suggest instead making a paper with instructions instead, would be a lot more clearer

**Comment by disappointedButNotSuprised** [comment]
> I would suggest instead making a paper with instructions instead, would be a lot more clearer

If you read the whole descripotion of the pr, this is exactly what was done

**Comment by Sylphily** [comment]
Pain this is what I get for being lazy and not reading the all the text on shitty dirt roads lol

**Comment by Zevotech** [comment]
quick spelling correction, line 1782 change "triats" to "traits"

vscode not checking spelling is a pain sometimes

**Comment by disappointedButNotSuprised** [comment]
> Pain this is what I get for being lazy and not reading the all the text on shitty dirt roads lol

I would say that im disappointedButNotSuprised

**Pull request merged**
