### PR TITLE
Swifter's Ship Emporium!

### PR DESCRIPTION
**Pull request by swifterjack**
## About The Pull Request
Adds six new playable ships, and one new adminspawn ship to the game.
Unatomized changes of drone law changes, and oil thruster buffs.

Ships added:
Syndicate aligned Luxembourg, a mercantile Donk! Co. ship, designed to be used to sell Donk! pockets and other products across the galaxy. Medium size.
luxembourg
Syndicate aligned Spitfire, a model predating the widespread usage of bluespace and plasma in ship movement, using an outdated method of oil to create thrust. Retrofitted with advanced medical and rescue supplies. Small size.
spitfire
The Pill. It's the pill. Torture hell. Smallest shiptest.
pill
Space Statio.3, a fucking brick with thrusters, containing all you need to call yourself a station. Costs more than you'll ever have.
statio
Nanotrasen aligned Raven, a heavy personnel transport vessel with armaments on the sides. Fancy schmancy. Medium size.
raven
Nanotrasen aligned Goon, a repurposed emergency shuttle for space exploration, looks familiar. Small size.
goon
Dronetest: A vessel manned only by drones, contains no cryosleepers. Incredibly dangerous for humans.
dronetested
Oil thruster change: Holds only 1000 units now, but generates 20 thrust each click using 50u of oil. Still doesnt face the right way.
Drone law changes: Laws changed to be less station centric, and focus more on where they were activated. 
	"1. You must serve the goals of those who inhabit the vessel you reside on.\n"+\
	"2. You must upkeep and improve the vessel you were activated upon, and reside upon."

## Why It's Good For The Game
More ships that you have all been waiting for.

## Changelog
:cl: Swifterjackie
add: Added seven new maps
tweak: changed drone laws
balance: buffed oil thrusters
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
108

**Comment by swifterjack** [comment]
please testmerge this i beg you

**Comment by rye-rice** [comment]
108

**Comment by shiptest-server** [comment]
#### Test Merge Deployed

##### Server Instance
shiptest

##### Revision
Origin: f789e74004b3acb82690d77398848b240a153b6f
Pull Request: 9f3d556312b8de1ba7a7bd21a5e4cfd35641bad4
Server: 1dbd0bfb0d4198bd0a0d556e3729419b22e55678

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 89b653c96fc59fa415eeb26666f154fe97f257c1
Pull Request: 9f3d556312b8de1ba7a7bd21a5e4cfd35641bad4
Server: 9172c1bfefbcd61b7e2dccb8f8cceb235072078e

**Comment by Azarak** [comment]
A lot of the ships(reported two so far, Raven cruiser and Goon class) are missing wideband intercoms and long range holopads, unsure if intentional design or not, but it seems like an oversight

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 7c3512bd559cf2b1f8e230216ff853c7f118d7ee
Pull Request: 9f3d556312b8de1ba7a7bd21a5e4cfd35641bad4
Server: 7f432c12878b85f2e0187a8393c33b9d5b197880

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: bf2a3d7daffd8042d3adbe075ec803cd3abd4e03
Pull Request: 9f3d556312b8de1ba7a7bd21a5e4cfd35641bad4
Server: 68914e28c7ca55ffe87c21c0fc6dbcb9af418093

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: bf2a3d7daffd8042d3adbe075ec803cd3abd4e03
Pull Request: 3d1186454b148eb1f36c5cffd6fd97fb4c7727c5
Server: ca0ff8b9f76846976a9d8d2ec5e18cf60ecd28be

**Comment by Valorium-RB** [comment]
Ships are excellent, only request is to make the Raven have a little more open space by removing some chairs and to give it some kind of armament (it's a pseudo-military vessel whose turrets constantly attracts fauna the crew can then barely deal with because we're armed with pickaxes). Otherwise, the Luxembourg is my favorite shiptest, please merge.

**Comment by shiptest-server** [comment]
#### Test Merge Removed

**Comment by shiptest-server** [comment]
#### Test Merge Deployed

##### Server Instance
shiptest

##### Revision
Origin: 033ea7d0a6e5ade2feced249d03f7bfcd3eac439
Pull Request: fee265d2810c1b3adf76ce443342cbc06f4f46e4
Server: 7c123be6a9d9ffcf192aa21466691c922a728b54

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 9693b436ac8eb8d68349b284df72bb252209581f
Pull Request: fee265d2810c1b3adf76ce443342cbc06f4f46e4
Server: 651bb7bd5250da841cf57899f6ff939ae8b47202

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: ca83a63d9154e7bd47271dd9f5ce5d44eb19d7af
Pull Request: fee265d2810c1b3adf76ce443342cbc06f4f46e4
Server: b9679cc28f47ef4054511559ac3e5f35dd3100bb

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: ca83a63d9154e7bd47271dd9f5ce5d44eb19d7af
Pull Request: fee265d2810c1b3adf76ce443342cbc06f4f46e4
Server: 52f18b307da9ed9bafb2f173c5db9806fde13a70

**Comment by swifterjack** [comment]
retlaw said she'd fix these once they are merged, so get em in and she'll get em fixed

**Comment by swifterjack** [comment]
im unsure if im going to have the energy to finish these properly otherwise

**Comment by ZephyrTFA** [comment]
Can't merge it because the maps arent compiling properly. You'll need to reopen them in SDMM and correct the turf paths
```
undefined type: /obj/effect/turf_decal/tile/blue
```

**Comment by ZephyrTFA** [comment]
Runtime in unsorted.dm,1056: Invalid job slot entry! Solgov Representative: 1 on Statio.3-class Station With Thrusters's config! Excluding job.

Runtime in unsorted.dm,1056: Invalid job slot entry! Head Of Personnel: 1 on Raven-class Heavy Transporter's config! Excluding job.

**Comment by ZephyrTFA** [comment]
@MarkSuckerberg I can't really touch maps, can you fix the compile errors on this?

**Comment by swifterjack** [comment]
fixed my repo and did the baytile script

**Pull request closed without merging**
