### PR TITLE
Fixes strippers not working

### LINKED ISSUE #3536: .300 magnum stripper clips don't work on the Scout.
Issue reported from  Round ID: 2752 (Shiptest)

Reporting client version: 515.1643

It straight up doesn't let you interact with the rifle if you use a clip on it.

### LINKED ISSUE #3547: Rifle Speedloaders don't work
Issue reported from  Round ID: 2760 (Shiptest)

Reporting client version: 515.1634

 try to use stripper clip on polymer survivor rifle
 does not work
 manually feed in ammo from stripper clip
 works

### PR DESCRIPTION
**Pull request by SomeguyManperson**
## About The Pull Request

Fixes #3536
Fixes #3547

Ammo stacks added a check to prevent magazine to magazine filling which also prevented directly filling guns with anything that wasnt an ammo stack, which broke stripper clips and speedloaders. Revolvers escaped this since they handle everything related to loading completely differently.

This moves the strict ammo stack check down a bit so ammo holders that are able to instantly transfer ammo between eachother can instead of dont

## Changelog

:cl:
fix: strippers and speedloaders for rifles now work again
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
oh YEAH that's what it was. nice catch. I need to pay closer attention porting stuff

**Comment by MarkSuckerberg** [comment]
when did we add strippers??? you guys never tell me anything

**Comment by MarkSuckerberg** [comment]
also jokes aside don't forget to close #3536 and #3547 with this

**Comment by thgvr** [comment]
I've been working all week

**Comment by MarkSuckerberg** [comment]
> I've been working all week

o7

**Comment by lectronyx** [comment]
title had me excited for a moment, there

**Pull request merged**
