### PR TITLE
double beds [ported from Beestation]

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request
yea, that's right DOUBLE BEDS

image

## Why It's Good For The Game
roleplay :)

## Changelog

:cl: PigeonVerde#8826
add: Added double beds
/:cl:

### CODE REVIEW

**Comment by Erikafox** [comment]
[extremely loud incorrect buzzer]

**Comment by BarteG44** [comment]
dark days are upon us

**Review by rye-rice — APPROVED** [review]

**Comment by Latentish** [comment]
What would be great would be having the ability to construct omnibeds that connect like turf smoothing.

**Comment by Ms-Mee** [comment]
Ship that's just a HUGE bed, used for moving sleeper agents, call that the REAL Mimir

**Comment by spockye** [comment]
> What would be great would be having the ability to construct omnibeds that connect like turf smoothing.

i'll do it if you get me the needed smoothing state sprites

**Review by MarkSuckerberg — APPROVED** [review]

**Pull request merged**
