### PR TITLE
scrapmare mode

### PR DESCRIPTION
**Pull request by triplezeta**
## About the Definition of Insanity

renames the scrapper file again, adds area noops where there should have been some, moves the docking port again

## Why its good for the Game

potentially fixes CI

## Changelog

:cl:
fix: scrapper map cleaned up a bit
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
image
go to HELL

**Comment by triplezeta** [comment]
image
WHAT IS YOUR PROBLEM

**Comment by triplezeta** [comment]
yes I renamed it again. Back to the old name. I have no idea if this will permanently fix this god-forsaken issue or not but if it doesn't I am this close to completely deleting the scrapper and remaking it from scrap. Scratch.

**Comment by triplezeta** [comment]
image
die and go directly to Heck

**Comment by francinum** [comment]
It gets CI to shut up. Whatever.

**Pull request merged**
