### PR TITLE
Crafting Cruft Removal

### PR DESCRIPTION
**Pull request by Sadhorizon**
## About The Pull Request
Removes the following recipes because:

Clothing 
- Scrap Armor - it sucks, it's ugly, it's expensive and it's honestly a bait to have it craftable

Drinks
- Holy Water Flask - god died
- Nothing Bottle - mimes died

Misc
- Flashlight eyes - just why.
- Extendo-hand - TG slop
- Guillotine - meme item
- Moth Plushie - plushies are cool, but the recipe itself is a meme

Robots
- Honkbot - clowns died

Tribal
- Bonfire, Distiller, Mushroom Bowl and Charcoal Stylus moved to Misc - they are okay
- Bone Spear, Bone Axe and Bone Sword moved to Weapons - Hate to keep them, but there isn't really any other okay melee weapons available, outside of the crusher I suppose, but that one's inconsitent to get.
- Bone Armlet, Wolf Fang Necklace, Goliath Cloak, Hunters Belt and Polar Cloak moved to Clothing - they are okay
- **Everything else got removed, including the category itself** - it's about time to let ash walker gear go I think

Weapons/Ammunition
- Explosive Lance - item's definitely on the goofier side
- Teleprod - teleportation is often fucked
- Gonbola - gondolas barely exist, might as well axe it
- Flamethrower - feels like this should be locked behind more than crafting
- Chainsaw moved to Misc - it's a gardening tool, you MANIACS
- Pipe Bow and All The Arrows - bows are kinda broken rn? Commented it out cuz feels like it can be used later, but having broken stuff here is dumb.

**Note here: It's just the crafting recipes, not foods themselves. Crafting cleanup, not food cleanup.**

Breads
- Mimana Bread - mimes died

Burgers
- Ghost Burger - magic is not real
- Clown Burger - clowns died
- Mime Burger - mimes died
- Spellburger I and II - magic is not real

Cakes
- Slime Cake - you are NOT getting slime extracts for this
- Angel Food Cake's recipe was changed - god died, so it uses cream instead of holy water
- Clown Cake - clowns died

Frozen
- Honkdae - clowns died
- Mime Snowcone - mimes died
- Clown Snowcone - clowns died
- Also renamed all the cola cones according to names from the drink rename

Meats
- Meat Clown - clowns died

Pastries
- Honk-pockets - clowns died

Pies
- Mime Tart - mimes died

Salads
- Monkey's Delight - it's very questionable

Soups
- Clowns Tears - clowns died

Spaghettis
- Spesslaw - space law died

Egg-Based Foods, Pizzas, Sandwiches
- Nothing :D

Also, removes flamethrower slapcrafting for the same reason that's above.

Also removes bone clup, skull helmets and bone armor from bone construction menu.

## Why It's Good For The Game
Explained for every item individually.

## Changelog

:cl:
del: Removed a lot of cruft from the loadout.
del: Removed flamethrower slapcrafting.
del: Removed the Tribal crafting tab (some items were moved to other tabs).
del: Removed bone club, skull helmet and bone armor from the bone construction menu.
/:cl:

### CODE REVIEW

**Comment by Anticept** [comment]
Also note that the craftable flamethrower may not be the same as the chemical one. It might be an atmospheric flamethrower, uses plasma tanks. It can make brutally large fires in moments, and if it were ever used in pvp, pretty much everyone would lose especially in the hands of someone who knows to cool the tank and cram even more moles in.

You will also want to make sure it isnt also slap craftable. Its a very old item and on a lot of codebases, you can make it without a cradting menu. I think it was screwdriver on a welding tool, slap rods, slap igniter.

**Comment by Xkallubar** [comment]
Removes too much soul. If we can put our brains inside of monkeys and defib them to become monkeys with human level intelligence then there's no reason to stop me from making Monkey's Delight! What if I wanted to RP as an insane doctor who wants to give someone flashlight eyes? A lot of these items fill in a niche and it's harder to leverage the sandbox if things are being gutted more often than added. Some of your reasonings are literally just personal opinions.

Magic is real! :(

**Comment by MassiveMen** [comment]
Magic is dead and we killed it. And so help me god I'll gut monkey body swaps.

**Comment by generalthrax** [comment]
> If we can put our brains inside of monkeys and defib them to become monkeys with human level intelligence

Frankly this is abhorrent and shouldn't happen to begin with. It's like romerol'd players using it to not roleplay as a zombie and just be an immortal crewmember.

> Some of your reasonings are literally just personal opinions

Nearly everything being removed is either incompatible with our lore or useful only to hyper-gamers which have no place on Shiptest to begin with. The entire admin team and lorewriters have been excising tg cruft for years and these are no different

we should totally keep the skateboard though because unlike the scooter (SUCKS ASS) it doesnt absorb bullets from people shooting you

**Comment by Sadhorizon** [comment]
> Removes too much soul. 

Kinda true, but this is NOT a good kind of soul. This is soul that's outdated, stupid and should be buried deep.

> If we can put our brains inside of monkeys and defib them to become monkeys with human level intelligence then there's no reason to stop me from making Monkey's Delight!

Okay, why are you putting your brain in a monkey? If it's "because it's funny", then I don't think there is any argument here.

> What if I wanted to RP as an insane doctor who wants to give someone flashlight eyes?

That'll happen once in 500 rounds. Doesn't really justify keeping bloat IMO.

> A lot of these items fill in a niche and it's harder to leverage the sandbox if things are being gutted more often than added. 

Okay, examples for the "lots of items"? There is maybe two I am not sure if they deserve removal and that's it.

> Some of your reasonings are literally just personal opinions.

You BET. But it doesn't seem like people disagree with most, so I think those opinions are not just mine.

> Magic is real! :(

WRONG. Magic's been systematically removed from the setting.

**Comment by Sadhorizon** [comment]
> we should totally keep the skateboard though because unlike the scooter (SUCKS ASS) it doesnt absorb bullets from people shooting you

I think the reasoning I put is good. There's definitely good uses for both, but somehow I feel like they are usually just goofy. Do convince me otherwise though. I'd rather be wrong than axe an item that's fine.

**Comment by Aquidu** [comment]
Think we could just rename the spesslaw to "meatball spaghetti" rather than outright remove it? It fills a nice niche if you want to make spaghetti but don't have tomatoes.(which is more common than you may think if you haven't stopped at a beach or jungle recently.)

Anyway, I support this. I love playing chef and hopefully my crafting menu will be filled with a lot less useless things after this.

**Comment by thgvr** [comment]
> Removes too much soul. If we can put our brains inside of monkeys and defib them to become monkeys with human level intelligence then there's no reason to stop me from making Monkey's Delight! What if I wanted to RP as an insane doctor who wants to give someone flashlight eyes? A lot of these items fill in a niche and it's harder to leverage the sandbox if things are being gutted more often than added. Some of your reasonings are literally just personal opinions.
> 
> Magic is real! :(

this is bait

**Comment by generalthrax** [comment]
> Do convince me otherwise though. I'd rather be wrong than axe an item that's fine.

I've just never seen skateboards used in combat because they neither reduce the chance of getting hit nor speed you up, and you get knocked over if you collide with Anything. It practically just leaves it as a recreational item if a crews settling down after some work. I agree though scooters right out. It's been some Bullshit I've seen in early fights and I Dont Want To See A Repeat Of It

**Review by FalloutFalcon — APPROVED** [review]
pretty much all of this is good to remove but, i think some of it would be well suited locked behind recipe books or quirk. Mushroom bowls come to mind as something i made alot for srm ghetto chem and a "tribal book" or trait added to srm might not be a bad idea for that. I also think all the bone weapons should be locked behind something. We have glass spears for emergency weapons and you can buy combat knifes from cargo, i had a branch somewhere with new ghetto weapons i should finish at some point..

**Comment by Sadhorizon** [comment]
> Mushroom bowls

I can just bring them back. Not like they hurt anybody. Surprised I removed them.

> combat knifes

Uh, no, just survival knives actually. Hence why I'm keeping those. Don't like em but still.

**Comment by Sun-Soaked** [comment]
I can just remove scooter hardness to projectiles if it's causing issues

**Comment by goober3** [comment]
i think scooters have more issues than just combat effectiveness. they can bypass all slowdowns for no cost whatsoever. that sort of thing should be saved for ATVs i think.

**Comment by Xkallubar** [comment]
> Okay, why are you putting your brain in a monkey? If it's "because it's funny", then I don't think there is any argument here.

Yesterday someone put their brain into a monkey because their body was completely fucked up beyond repair and they had no other choice. Monkey charades is funny.

**Comment by githubuser4141** [comment]
> > Removes too much soul. If we can put our brains inside of monkeys and defib them to become monkeys with human level intelligence then there's no reason to stop me from making Monkey's Delight! What if I wanted to RP as an insane doctor who wants to give someone flashlight eyes? A lot of these items fill in a niche and it's harder to leverage the sandbox if things are being gutted more often than added. Some of your reasonings are literally just personal opinions.
> > Magic is real! :(
> 
> this is bait

it's not bait???

And yes becasue it's funny. What is wrong with funny? You can RP as "oh look at me doing this goofy thing" without it somehow detracting from the RP. Honestly why does this comment warrant such a dismissive tone?

Flashlight eyes - harmless item, used as makeshift eyes or as a shitty source of illumination

Teleprod - if people powergame using it that's what admins are for. It's mostly used for messing around because it's not that powerful

Scooter - okay make it so it occupies both hands to ride

Foods - 'clowns/mime' died doesn't make sense. Everyone dies and yet there's still cultural food invented 100's or 1000's of years ago. The concept of entertainment staff even on a military ship that's deep in space is not too bizarre and I think it's reasonable these people might have their own special recipes. Spesslaw is just spaghetti.

Holy Water flask - okay, so remove the interaction with it. No reason to not have it as a religious RP piece that does nothing.

Extendo-arm - what is 'TG slop'? It's a goofy plastic stick-arm that bored crew make to prank with or be annoying. These exist IRL as children's toys

Honkbot - Harmless light hearted bot that bored crew would definitely make

**Comment by thgvr** [comment]
I really have no idea what you are talking about, this is not normal ss13 this is Shiptest. Most of the things you're talking about don't apply here.

**Comment by FalloutFalcon** [comment]
> it's not bait???

They called it bait because it doesnt understand like, anything about our codebase, we've been actively removing magic for a long while
> And yes becasue it's funny. What is wrong with funny? You can RP as "oh look at me doing this goofy thing" without it somehow detracting from the RP. Honestly why does this comment warrant such a dismissive tone?

Its not that things aren't allowed to be funny. most of the removals simply don't fit the style, lore, or atmosphere we want. as well as a lot of them probably have been crafted mabye.. once? its junk filling up still bloated menu
> Teleprod - if people powergame using it that's what admins are for. It's mostly used for messing around because it's not that powerful

its mostly used for power gaming, are you just making things up?
> Foods - 'clowns/mime' died doesn't make sense. Everyone dies and yet there's still cultural food invented 100's or 1000's of years ago. The concept of entertainment staff even on a military ship that's deep in space is not too bizarre and I think it's reasonable these people might have their own special recipes. Spesslaw is just spaghetti.

No like, we have mostly killed them from code, you cannot craft like all of these. You will never get the ingredients ever
spesslaw is an existing recipe but double the meatballs, its not a reference that makes sense on shiptest.
> Holy Water flask - okay, so remove the interaction with it. No reason to not have it as a religious RP piece that does nothing.

Cant craft this one either, we only have one religion right now, the srm.
There is no reason to have this. Have you looked at the recipe? it does nothing, it just makes a different sprite for something we dont have.
> Extendo-arm - what is 'TG slop'? It's a goofy plastic stick-arm that bored crew make to prank with or be annoying. These exist IRL as children's toys

Another item you cannot get the items to craft.
> Honkbot - Harmless light hearted bot that bored crew would definitely make

You cannot craft this, ever
 

ok so apparently the clown-mime war never happened and that was never official so i edited that part out

**Pull request merged**
