### PR TITLE
Better metal rod throwing feedback

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Adds better feedback when metal rods are thrown
https://github.com/discordia-space/CEV-Eris/pull/8099

## Why It's Good For The Game

It's a bit difficult to use metal rods due to the lack of feedback. This helps with that issue

## Changelog

:cl:
add: Better metal rod and atmos pipe feedback
/:cl:

### CODE REVIEW

**Comment by GenericDM** [comment]
Funny, but I'm not sure it fits.

EDIT: Also, these are metal rods (rebar), not metal pipes.

**Comment by Sun-Soaked** [comment]
> EDIT: Also, these are metal rods (rebar), not metal pipes.

It's very shrimple: Modern shipbuilding works with high tolerance hollow rebar

**Comment by thgvr** [comment]
add the lead pipe from tg instead and give it this and make it in some rare spawner

**Comment by MarkSuckerberg** [comment]
we've had our fun

**Comment by rye-rice** [comment]
if only

**Pull request closed without merging**
