### PR TITLE
removes crossed

### PR DESCRIPTION
**Pull request by jupyterkat**
**please don't testmerge this with other major testmerges, it will conflict**
## About The Pull Request

they aint coming back

tgstation/tgstation#58188
tgstation/tgstation#58340
tgstation/tgstation#59299
tgstation/tgstation#59223
tgstation/tgstation#59200
tgstation/tgstation#59199
tgstation/tgstation#59196
tgstation/tgstation#59065
tgstation/tgstation#58945
tgstation/tgstation#58507
tgstation/tgstation#58276
tgstation/tgstation#58269
tgstation/tgstation#59658
tgstation/tgstation#59608
tgstation/tgstation#59010
tgstation/tgstation#59185
tgstation/tgstation#59154
tgstation/tgstation#59432
tgstation/tgstation#57773
tgstation/tgstation#59303
tgstation/tgstation#59919
tgstation/tgstation#60026
tgstation/tgstation#59894
tgstation/tgstation#60678
tgstation/tgstation#59176

makes signals synchronous also

## Why It's Good For The Game

yes

## Changelog
:cl: Mothblocks, Kylerace, ninjanomnom, LemonInTheDark, Rohesie, Wayland-Smithy, Watermelon914, CoffeeKat
refactor: movement code refactor to speed up crap
code: improves components code
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
I'll help in fixing this as it's a rather big optimization. But not this week unless I get unexpected time off

**Comment by Kapu1178** [comment]
Credit authors, not just "tgstation".

**Comment by jupyterkat** [comment]
> Credit authors, not just "tgstation".

not your problem

**Review by Kapu1178 — DISMISSED** [review]
Credit original authors in CL.

https://github.com/shiptest-ss13/Shiptest/blob/master/.github/CONTRIBUTING.md#pull-request-process

**Comment by jupyterkat** [comment]
`you must give *them* credit where it's due`. no problem with stating tgstation, since most of these prs are done by tg maints anwyays.

**Comment by jupyterkat** [comment]
:tired:

**Comment by MarkSuckerberg** [comment]
</img>

**Comment by rye-rice** [comment]
railings are fucked up and evil and if you walk into one, you get stuck forever

**Comment by rye-rice** [comment]
getting stuck extends to necroplis doors as well

**Comment by MarkSuckerberg** [comment]
Seems to work fine, now.

**Comment by ZephyrTFA** [comment]
oh no I slipped and fell on the merge button

**Pull request merged**
