### PR TITLE
Changes various prescription glasses sprites to be more transparent.

### PR DESCRIPTION
**Pull request by solwashere**
glasses

## About The Pull Request

Changes the sprites of the prescription glasses, and prescription HUD glasses, to be more transparent with less varying colors. Also a semi port of https://github.com/yogstation13/Yogstation/pull/19641

image
 

## Why It's Good For The Game

Better looking sprites are better for the game, I'd assume. It'll also help differentiate sunglasses huds from prescription huds a bit more. 

## Changelog

:cl:

imageadd: new sprite for prescription glasses, purple prescription glasses, prescription meson and sec prescription glasses.

/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
My glasses! I can't see without my glasses!

**Comment by thgvr** [comment]
Not the biggest fan of this. It doesn't really look that great, and makes the face area pretty busy especially since our eyes are different from where you grabbed this from. Also good lord please simplify that changelog. "Updated sprites for glasses."

**Comment by solwashere** [comment]
> Not the biggest fan of this. It doesn't really look that great, and makes the face area pretty busy especially since our eyes are different from where you grabbed this from. Also good lord please simplify that changelog. "Updated sprites for glasses."

I agree with you somewhat, however I think that it's going to be nearly impossible to make a good looking glasses sprite as all there is to represent the "lens" is a 2x2 square.
I feel like this is at least an improvement over the current prescription glasses sprite as the current sprites look extremely jarring and obnoxiously ugly, at least in my opinion.
I made the sprites this way as I feel it blends better when worn over the current ones, as well as being able to show off the eyes slightly and allow you to differentiate between what glasses are what.

**Comment by thgvr** [comment]
It's just hard to really even tell the glasses are there. It looks more similar to our blush effects. 

Having them be more opaque isn't a bad thing, it's pretty much impossible to have a glass-like effect on a sprite that size and just ends up being very busy.

**Review by rye-rice — CHANGES_REQUESTED** [review]
If youre making the glasses the transparent, make the 4 pixels the same color/shade, since we have 2x2 eyes it looks odd if it isn't, also make the glasses more opaque

image

opacity 150 - 190 looks good

**Comment by rye-rice** [comment]
image
OH and make sure the lens on the side state covers the sclera as well

**Comment by solwashere** [comment]
> If youre making the glasses the transparent, make the 4 pixels the same color/shade, since we have 2x2 eyes it looks odd if it isn't, also make the glasses more opaque
> 
> image
> 
> opacity 150 - 190 looks good

I'll update sometime this week whenever I find the time, thanks!

**Pull request closed without merging**
