### PR TITLE
outpost tweaks & fixes

### PR DESCRIPTION
**Pull request by goober3**
## About The Pull Request
both outposts have been passed for mistakes, such as wiring & pipe errors.

- the indie outpost no longer runs out of power immediately (the smes didn't have a terminal).
- a one-way maintenance door has been added to the indie outpost disposal room, so players aren't sealed forever.
- doors to inaccessible areas in the indie outpost are now sealed with doors + walls, rather than re-iconned walls.
___
- the ice asteroid outpost's map has been expanded, to avoid windows to void.
- some doors have been replaced, to better fit anywalls.
- freezer room floor tiles have been replaced with showroom floors.

outpost & hangar files now have unique names + their faction.
all wallmounts + doors are now fixed & use proper dirs.
the nt asteroid outpost now has a 56x40 hangar.
hangar tiles now use planetary atmos, to prevent depressurization via ship.
the floor under elevator doors on all hangars is now catwalk. 

## Why It's Good For The Game

bugfixes are good. no more floating extinguishers & unbreathable elevators.

## Changelog

:cl:
add: the nt asteroid outpost now has a 56x40 hangar.
fix: outpost hangars should no longer depressurize upon ship docking.
fix: outpost wallmounts and doors have been fixed. please report any floating extinguishers & hovering intercoms.
fix: the independent outpost should stay powered forever.
/:cl:

### CODE REVIEW

**Comment by Imaginos16** [comment]
godlike PR. Real king shit.

**Review by spockye — APPROVED** [review]
thanks a bunch for the fixes ( i never got around to doing it guhhhhhhh)

could i ask you to replace all the doors in the NT outpost with reskinned centcom doors?
(to stop people from hacking into places they shouldnt be)
(this is of course optional)

thanks for the fixes!

**Comment by goober3** [comment]
ough no mergies yet sorry. another batch of tweaks & fixes coming in soon

**Comment by goober3** [comment]
oh whagt

**Comment by spockye** [comment]
Get marged dumbass

**Comment by Erikafox** [comment]
Oh fuck me

**Pull request merged**
