### PR TITLE
Tiny Anywalls Fixes

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
Continues to fix tiny issues I spot

## Why It's Good For The Game
We like working maps 

## Changelog

:cl:
fix: Assorted floating wall mounts and other oddities have been fixed, please continue to report any you see.
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
Can you please give us a list of all the stuff you've changed and the maps you touched? These have to be checked out on live so we need to know where these changes are.

**Comment by Erikafox** [comment]
firefox_qJzIKuG4vD

**Comment by Latentish** [comment]
> firefox_qJzIKuG4vD

image
This does not tell me what you changed or how.

**Review by spockye — APPROVED** [review]
does what it says!

**Pull request merged**
