### PR TITLE
Helmet Resprites

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

sechelmet
swat_nt
swat_syndi
sechelmet-obj
swat2
swatsyndie2

Replaces the sprites for the Syndicate and Nanotrasen SWAT helmets with sprites based on Halcyon's combat helmet from #674.
Also replaces the sprites for the basic security helmet.

TODO:

- New sprites for riot, bulletproof, and solgov helmets
- Add seclite sprites to most of the combat-style helmets
- maybe: turn sec helmet visor into an attachment

## Why It's Good For The Game

the old helmets were really scuffed

## Changelog
:cl:
imageadd: Updated sprites for SWAT Helmet and Syndicate SWAT Helmet.
imageadd: Updated sprites for security helmet.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
i didnt forget this pr i just put it off for an Entire Month Oh Hell

im working on this now

**Comment by rye-rice** [comment]
:cement:

**Comment by triplezeta** [comment]
ah ah

**Comment by rye-rice** [comment]
tetra this has gone stale 2 times

**Comment by Fikou** [comment]
closing in favor of #1122

**Pull request closed without merging**
