### PR TITLE
Removes Paper Detroit from the game.

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Removes the notorious originalcontent.dmm from the game. The big fuckoff paper asteroid was removed in an event and was assumed to have been removed from the ruin rotation, which it was not. This PR removes it for good.

## Why It's Good For The Game
This ruin was basically a deathtrap for anyone who wasn't aware of its contents, and even killed prepared players with its swarms of stick figure mobs and a final boss paper wizard with some powerful abilities and strong attacks. It was also known for a lot of mediocre loot, with the better things only being dropped by the paper wizard. Several people, including me, wanted this ruin gone for these reasons and so it is being removed.

## Changelog
:cl:
del: originalcontent.dmm and originalcontent.dm have been deleted.
del: code mentions of originalcontent.dmm have been deleted.
del: removes the originalcontent items from the icemoon corporate rejects ruin
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
Why It's Good For The Game?

**Comment by Zevotech** [comment]
yeah, its good for the game. good that ill never see it again.

**Review by Fikou — CHANGES_REQUESTED** [review]
You need to provide an actual reason for the removal.

**Comment by Zevotech** [comment]
fiiine, fixed it.

**Review by Fikou — APPROVED** [review]
sure

**Pull request merged**
