### PR TITLE
Remaps the Skipper Heavy Cruiser

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
I love the Skipper a lot, but it was getting kind of outdated in terms of mapping and had a slew of issues that made it harder to enjoy as time went on. This remap changes the footprint of the Skipper to have a smaller engineering segment and more room for the crew to move about and interact.

SDMM:

The egriegious amounts of wallpipes have been removed, the internal affairs agent has their own room with privacy shutters to hold meetings, the cafeteria and crew area have been upgraded and engineering has been shrunk by about 30%.

Ingame:
image
The three engineer slots have been replaced with an atmos tech and an engineer. A cargo tech slot has been added to manage the cargo office and handle outpost purchases. There is also now a dedicated cook slot to occupy the new kitchen and bar.

## Why It's Good For The Game
Ship maintaining. Also wallpipes, wallguns, the injector under a thruster and various other things aren't good for a map.

## Changelog

:cl:
add: Remaps the Skipper Heavy Cruiser
add: Adds an Atmos Tech, Cargo Tech and Cook job slot to the skipper
del: Removes two engineer slots from the skipper.
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
Alright, I'm calling this complete. Needs reviews from maptainers now.

**Review by spockye — COMMENTED** [review]
image

try adding some wooden linings here! might look pretty.
(good work with the table populating! looks like someone actually uses the place)
also, i do think the amount of weapons could be trimmed. i'd say remove atleast one of the laser guns


image

could use some contrast in here. mabye try changing the turfs around?

image

the blue is a bit painful imo. dont have to change it, if its just me


-------------
this is for sure an improvement. good work!
i'll see about TMing this next uptime

**Comment by Zevotech** [comment]
pls tm i NEED to test this

**Comment by Apogee-dev** [comment]
You might want to mess around with the hallway outside of the kitchen a little bit more, actually. The dining table takes up a lot of space for an area that pulls double duty as a primary entrance/exit to the ship thanks to that airlock. I'd suggest giving the big table the axe and leaving it with the cafe bar and the small 2-seater table for seating options so there's a bit of room to maneuver coming out of the airlock.

**Comment by Zevotech** [comment]
> You might want to mess around with the hallway outside of the kitchen a little bit more, actually. 

Shrunk the big table so theres more space to move around it.

**Comment by Draggeru** [comment]
The bridge does not have a holopad anymore, I don't think I need to explain why such is an issue

**Comment by Zevotech** [comment]
> The bridge does not have a holopad anymore, I don't think I need to explain why such is an issue

image
KILL. (give me a minute to update the images nerd)

**Comment by Draggeru** [comment]
> > The bridge does not have a holopad anymore, I don't think I need to explain why such is an issue
> 
> image KILL. (give me a minute to update the images nerd)

I CANT READ OH GOD.

**Comment by Zevotech** [comment]
images updated smileyface

**Comment by Zevotech** [comment]
merge conflict removed, checking for corruptions then its ready for re-tm

**Comment by spockye** [comment]
Good work

**Comment by Zevotech** [comment]
> Good work

:DDDDDDDD

**Comment by goober3** [comment]
epic fail

**Pull request merged**
