### PR TITLE
Removes Metacoins/Antag Tokens, Minor Loadout Rework

### LINKED ISSUE #598: [BUG] Character gear just gets dumped on titlescreen (seriously, did nobody notice?)
## Round ID:
This bug has persisted for many rounds before this as well.

## Testmerges:
#230: '[TEMP] Disable loadout costs' by AsciiSquid at commit a7399a3607
#459: 'Interrim Research Rework: Of Departments and Trading' by MemedHams at commit f93bd19309
#522: 'Map zones and virtual levels' by Azarak at commit 2288770b08
#505: 'Vinethud vote notification' by Zevotech at commit 7daed97ea6
#521: 'Xenomorph Tweaks' by MemedHams at commit 9edf4bb03e
#530: 'Kapu's BetterLimbs port' by E-MonaRhg at commit fc5e29c468
#563: 'Kugelblitz 2: The revenge of the CE' by swifterjack at commit 3c733887ba
#572: 'The Dronetestening' by Pockets-byte at commit b1d0e2329a

## Reproduction:
1. Have any amount of loadout gear selected
2. Join
3. 
image

### LINKED ISSUE #670: [BUG] Metacoins do not Payout Every 10 Minutes
## Testmerges: 305, 230, 505, 652, 607

I've been watching my metacoin balance today.  It's increased by 200 which is consistent with it only paying out for the two round ends I was present for.  Which implies it is not paying out every 10 minutes like #616 intended.

## Reproduction:
1. Join an existing round
2. Document your metacoin balance from the gear tab in preferences
3. Complete the round
4. Check that your metacoin balance has only increased by the round end amount for being dead or alive

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Removes metacoins and antag tokens for good, as well as makes loadout based on an arbitrary config-set maximum amount of items.

Fixes: #598
Fixes: #670 (lol)

## Why It's Good For The Game
Metacoins have proven themselves to be meaningless gates blocking people from buying ships that they otherwise should have been able to play.

## Changelog
:cl:
tweak: Loadouts are now limited by a config-set number instead of the amount of metacoins you could spend.
tweak: All loadout items spawn in a box now instead of attempting to equip stuff. meh.
del: Metacoins and Antag Tokens (latter never used)
del: Custom OOC colours/extra character slots have been removed. Sorry, but they just don't work now.
server: SQL change dropping metacoins/antag tokens, updates config with max loadout items value
/:cl:

### CODE REVIEW

**Review by ZephyrTFA — COMMENTED** [review]
Can't do a full review yet, but the cursory look is good

**Review by francinum — DISMISSED** [review]
update the header of database_changelog with correct numbers. This is minor. I'll do a fuller review later as well.

**Comment by Zevotech** [comment]
No More Coins! No More Nineteen Dollar Shipcoins! You Been Blocked!

**Comment by WindowsErrors** [comment]
sneedtacoins

**Comment by Martinpachu** [comment]
No! Stop! What am i gonna flex now?!? These shipcoin,theyre my life!

**Pull request merged**
