### PR TITLE
Blacklists half the ruins

### PR DESCRIPTION
**Pull request by Latentish**
## About The Pull Request
Planets only get 1 ruin each. This takes out half the available ruins more or less. The ruins being removed are all smaller, less useful, or just not worth keeping in exchange for another ruin.

This only affects the icemoon, sand planet, lavaland planet, and space. The rock planet and the jungle planet are missing their blacklist.cfg files, which I will fix in a later pr.

## Why It's Good For The Game
Which of the two ruins would you prefer to get?
image
or
image
I'd prefer the latter, and this pr accomplishes this by blacklisting the first one from spawning.
All hermit spawns are removed, they spawn with only 4 seeds, mining equipment, and a small amount of medical supplies. They have no other ruins to scavenge from or really anything to do except hope to get picked up by a ship, if they even get found.
Repeats of ruins have been blacklisted, like all the sin repeats for the sand planet, or the second copy of the seed vault spawn.

## Changelog
:cl:Phoaly
add: Added missing commented out ruins to blacklist configs for the icemoon, sand planet, lavaland, and space.
del: Removed a lot of ruins:
_maps/RandomRuins/SandRuins/whitesands_surface_abductor_crash.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_assaultpodcrash.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_bloodrunk1.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_bloodrunk2.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_camp_adobe.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_camp_drugstore.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_camp_farm.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_camp_gunslingers.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_camp_hunters.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_camp_survivors.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_chokepoint.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_conveniencestore.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_crash_bar.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_crash_cargo.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_envy.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_hermit.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_sloth.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_solgovcrash.dmm
_maps/RandomRuins/SandRuins/whitesands_surface_youreinsane.dmm
_maps/RandomRuins/IceRuins/icemoon_underground_burnies_lair.dmm
_maps/RandomRuins/IceRuins/icemoon_underground_hermit.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_cube.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_greed.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_sloth.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_ufo_crash.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_survivalpod.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_fountain_hall.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_comm_outpost.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_pizzaparty.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_cultaltar.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_swarmer_crash.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_gaia.dmm
_maps/RandomRuins/LavaRuins/lavaland_strong_rock.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_blooddrunk1.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_blooddrunk3.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_elite_tumor.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_puzzle.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_random_ripley.dmm
_maps/RandomRuins/LavaRuins/lavaland_surface_SPOOKYCRASH.dmm
_maps/RandomRuins/SpaceRuins/cryocontainment.dmm
_maps/RandomRuins/SpaceRuins/dark_glade.dmm
_maps/RandomRuins/SpaceRuins/excavator_DK.dmm
_maps/RandomRuins/SpaceRuins/intactemptyship.dmm
_maps/RandomRuins/SpaceRuins/kinggoatarena.dmm
_maps/RandomRuins/SpaceRuins/syndicatewreck01.dmm
_maps/RandomRuins/SpaceRuins/turretedoutpost.dmm
_maps/RandomRuins/SpaceRuins/vaporwave.dmm
_maps/RandomRuins/SpaceRuins/spacegym.dmm
_maps/RandomRuins/SpaceRuins/oldteleporter.dmm
_maps/RandomRuins/SpaceRuins/onehalf.dmm
_maps/RandomRuins/SpaceRuins/oldAIsat.dmm
_maps/RandomRuins/SpaceRuins/listeningstation.dmm
_maps/RandomRuins/SpaceRuins/mechtransport.dmm
_maps/RandomRuins/SpaceRuins/derelict1.dmm
_maps/RandomRuins/SpaceRuins/derelict2.dmm
_maps/RandomRuins/SpaceRuins/derelict3.dmm
_maps/RandomRuins/SpaceRuins/derelict4.dmm
_maps/RandomRuins/SpaceRuins/derelict5.dmm
_maps/RandomRuins/SpaceRuins/derelict6.dmm
_maps/RandomRuins/SpaceRuins/djstation.dmm
_maps/RandomRuins/SpaceRuins/emptyshell.dmm
_maps/RandomRuins/SpaceRuins/crashedclownship.dmm
_maps/RandomRuins/SpaceRuins/bus.dmm
_maps/RandomRuins/SpaceRuins/abandonedteleporter.dmm
_maps/RandomRuins/SpaceRuins/abandonedzoo.dmm
_maps/RandomRuins/SpaceRuins/asteroid1.dmm
_maps/RandomRuins/SpaceRuins/asteroid2.dmm
_maps/RandomRuins/SpaceRuins/asteroid3.dmm
_maps/RandomRuins/SpaceRuins/asteroid4.dmm
_maps/RandomRuins/SpaceRuins/asteroid5.dmm
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
This leaves the sand planet with the lowest ruin count of all planets, with 7 in total.

**Comment by HighPrincessErinys** [comment]
Wow! I sure love seeing a multitude of my ruins blacklisted! Hey, instead of murdering variety, oould you maybe actually blacklist ruins that exclusively have zero point in existing like the shitty empty hunks of space metal, and NOT things with actual amounts of loot or ghost roles? Ideally, we could have all of these ruins and multiple can spawn, but as it stands I would rather have an actual amount of ruins, even if some are kinda lame, as opposed to this overzealous culling.

**Comment by HighPrincessErinys** [comment]
Furthermore are we literally not in a ship freeze right now in an attempt to direct effort towards new ruins? What's the point of REMOVING ruins now?

**Comment by Zevotech** [comment]
unblacklist hermits and any other ruins with ghostroles imo, if you didnt want to play hermit then you dont click on the spawn button. i definitely prefer a ghostrole over said hunk of fucking metal, not gonna lie.

**Comment by ZephyrTFA** [comment]
This is not the correct way to fix this. 
The correct way to fix this would be to use a weighted rarity system where certain ruins are more likely than others, (and also the ability to have more than one ruin per planet)

**Comment by Apogee-dev** [comment]
I don't think this is a good approach, honestly. Ruin variety is still lackluster and removing a ton of ruins from rotation will only make it worse. Sure, blacklist the stuff that has _no noteworthy loot whatsoever_ or is otherwise just a bit of junk floating in space, but a lot of the blacklisted ruins are still quite valuable. Cryo containment and several of the whitesands camps like assault pod, adobe and drugstore come to mind (specifically, assault pod has high end weapons in exchange for a difficult combat encounter despite its small absolute size; the larger whitesands camps have weapons and ammo or medical supplies; cryo containment contains a ton of carpotoxin via carp and a fully functioning cryo setup that can be salvaged and installed on your ship). Also the clown shuttle is one of only two or so sources of bananium on this codebase.

Planetary ruins in general should have more leeway for underwhelming loot anyway since the planet itself is a significant source of materials and loot.

>The correct way to fix this would be to use a weighted rarity system where certain ruins are more likely than others, (and also the ability to have more than one ruin per planet)

Seconding this. Weighted ruin rarity would solve a lot of issues with underwhelming ruins without completely murderizing variety; Surely we all remember early last year when jungle planets only had three ruins and you'd just get tumblr sexyman over and over every time you landed on one?

If nothing else please consider heavily revising the blacklist. While ruins should all have something worth taking and the ones that are purely just atmosphere with no reward should probably be culled, they don't all need to be massive complexes brimming with gamer gear either. Don't forget that a lot of ships lack "basic" equipment like sleepers, medicine, armor, and simple weaponry, and those alone can be extremely valuable loot for those ships.

**Comment by Latentish** [comment]
I did this as a favor to some of the project leads while the weighted system is being worked on. This does not "nuke" variety, both space and lavaland still have roughly 15-20 ruins left unblacklisted each, and the sand planet still has 7. I went through the 4 planets with blacklist configs, looked at each ruin, and either asked in chat, asked a project lead, or used what I had been told to decide.
When it comes to hermits, the reasoning that with no other ruins to plunder and very little to do, they'd be extremely boring to play.
If anyone has specific maps they'd like removed from the blacklist, I'd be more than happy to hear it. Or if the project leads have decided now that this isn't something they want, then I suppose this was fun busywork.

**Comment by Latentish** [comment]
> This is not the correct way to fix this. The correct way to fix this would be to use a weighted rarity system where certain ruins are more likely than others, (and also the ability to have more than one ruin per planet)

Like I said, this was a favor for the project leads who requested this be done until that system is put in place.

**Comment by Latentish** [comment]
> Furthermore are we literally not in a ship freeze right now in an attempt to direct effort towards new ruins? What's the point of REMOVING ruins now?

Because planets get a single ruin per planet, and getting half these ruins in place of what is not currently blacklisted for most planets can be frustrating. Especially when these drown out the new maps and ruins that mappers are making now.
And again because I was asked to.

**Comment by triplezeta** [comment]
Hi this PR was done on my behalf

> This is not the correct way to fix this.
The correct way to fix this would be to use a weighted rarity system where certain ruins are more likely than others, (and also the ability to have more than one ruin per planet)

while this would be a better approach than blacklisting most ruins it also hasn't been done yet and none of our active coders seem to be interested in working on such systems. 

This PR exists to solve two main issues:

- PoI type distribution is heavily biased against Icemoon due to large amounts of low-value ruins filling other ruin pools
- Space ruin pool being filled with dead weight ruins. As energy signals mainly rely on their ruin for content it is absolutely important that the pool is filled with at least large ruins.

With that said this probably shouldn't be merged until blacklists for jungle and rock planets exist. In the meantime I encourage calm discussion about certain controversial blacklists (or lack thereof) in the PR comments

**Comment by Zevotech** [comment]
cool once the jungleplanet gets fixed can we utterly obliterate the ruin thats just 3 monkeys around a bonfire worshipping a washing machine? i have encountered it 5 times and my sanity is dwindling

**Comment by Latentish** [comment]
> cool once the jungleplanet gets fixed can we utterly obliterate the ruin thats just 3 monkeys around a bonfire worshipping a washing machine? i have encountered it 5 times and my sanity is dwindling

Yes, once someone helps me make those blacklist configs, I can go and blacklist that one.

Mark Suckerberg, you're a giant nerd for qdding that ruin, I saw it doing preliminary skimming.

**Comment by Zevotech** [comment]
...

_**V I O L E N C E**_

**Comment by HighPrincessErinys** [comment]
if you blacklist the roommates ruin i will actually just kill you in real life

**Comment by Cenrus** [comment]
We already have an issue with a lack of content on the server, removing a huge chunk of ruins isn't helping that. Exploring ruins is a core part of the gameplay so it is important that duplicate ruins don't show up too often, or things get start getting predictable.
I'd suggest adding some treasures to the barebones structures as you can see in the top image. Even some small goods like medicine and ores can be extremely useful to certain ship types.
Last thing, not all ruins have to be loot focused ones. I made the dark glade ruin as a cozy hideout in space where you can tell campfire stories with your buddies, removing it because it has nothing materially valuable defeats the intended purpose.

**Comment by CaptainBlackswag** [comment]
Now hold on lads let's not get too heated. This is a temporary measire until planets can get more than 1 ruin. So while yes some ruins are disabled for a while they aren't deleted. If you feel a particular ruin NEEDS to be left in then please comment nicely as the list is a wip. This isnt a statement on shitting on people's maps but a pr to ensure that a heap of planets dont spawn with small or otherwise more sparse ruins.

**Comment by Latentish** [comment]
> unblacklist hermits and any other ruins with ghostroles imo, if you didnt want to play hermit then you dont click on the spawn button. i definitely prefer a ghostrole over said hunk of fucking metal, not gonna lie.

We had a discussion in chat about exactly this, where some people were more apprehensive about blacklisting hermits, like you are, but others agreed in their blacklist. The reason is, without other ruins spawning alongside them, hermits are left with 4 seeds, no circuits, no tools, and almost nothing to do with the ore they could get. They'd have to make a bonfire to smelt the ore, and after that they'd have limited use of sheets without any proper tools. It's not that I dislike hermit or ghostroles, but this ghostrole has almost nothing to do without other ruins with it.

**Comment by Latentish** [comment]
> We already have an issue with a lack of content on the server, removing a huge chunk of ruins isn't helping that. Exploring ruins is a core part of the gameplay so it is important that duplicate ruins don't show up too often, or things get start getting predictable.

You seem to misunderstand the point of this pr. This PR not only blacklists repeat ruins, but it doesn't destroy variety in any of the planets. Like at all. The sand planet being left with 7 ruins is the most extreme, but that's still 7 planets worth of spawns, and the reason for htat is because "map with funny tiling and a single bdm" is apparently a rather common design. The blacklist I made with the support of the discord chat cuts the ruin list on the sand planet down to about the same as the ice planet, which has the bet variety of all planets from prior trimming. The rest of the planets are not so lucky and I'll show you exactly why.

Of the space ruins, this is what is still left:
#_maps/RandomRuins/SpaceRuins/bigderelict1.dmm
#_maps/RandomRuins/SpaceRuins/caravanambush.dmm
#_maps/RandomRuins/SpaceRuins/clericden.dmm
#_maps/RandomRuins/SpaceRuins/cloning_facility.dmm
#_maps/RandomRuins/SpaceRuins/clownplanet.dmm
#_maps/RandomRuins/SpaceRuins/crashedship.dmm
#_maps/RandomRuins/SpaceRuins/deepstorage.dmm
#_maps/RandomRuins/SpaceRuins/Fast_Food.dmm
#_maps/RandomRuins/SpaceRuins/gasthelizards.dmm
#_maps/RandomRuins/SpaceRuins/gondolaasteroid.dmm
#_maps/RandomRuins/SpaceRuins/hilbertshoteltestingsite.dmm
#_maps/RandomRuins/SpaceRuins/intactemptyship.dmm
#_maps/RandomRuins/SpaceRuins/mrow_thats_right
#_maps/RandomRuins/SpaceRuins/oldstation.dmm
#_maps/RandomRuins/SpaceRuins/originalcontent.dmm
#_maps/RandomRuins/SpaceRuins/power_puzzle.dmm
#_maps/RandomRuins/SpaceRuins/scav_mining.dmm
#_maps/RandomRuins/SpaceRuins/shuttlerelic.dmm
#_maps/RandomRuins/SpaceRuins/spacehotel.dmm
#_maps/RandomRuins/SpaceRuins/thederelict.dmm
#_maps/RandomRuins/SpaceRuins/way_home.dmm
#_maps/RandomRuins/SpaceRuins/whiteshipdock.dmm
#_maps/RandomRuins/SpaceRuins/whiteshipruin_box.dmm
#_maps/RandomRuins/SpaceRuins/forgottenship.dmm
#_maps/RandomRuins/SpaceRuins/astraeus.dmm
#_maps/RandomRuins/SpaceRuins/dangerous_research.dmm
#_maps/RandomRuins/SpaceRuins/fueldepot.dmm
#_maps/RandomRuins/SpaceRuins/hellfactory.dmm
#_maps/RandomRuins/SpaceRuins/ntfacility.dmm
#_maps/RandomRuins/SpaceRuins/nuclear_dump.dmm
#_maps/RandomRuins/SpaceRuins/oldcodeops.dmm
#_maps/RandomRuins/SpaceRuins/transport18
On lavaland we still have these:
#_maps/RandomRuins/LavaRuins/lavaland_surface_biodome_winter.dmm
#_maps/RandomRuins/LavaRuins/lavaland_biodome_beach.dmm
#_maps/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_syndicate_base1.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_golem_ship.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_envy.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_gluttony.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_pride.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_automated_trade_outpost.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_ww_vault.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_automated_trade_outpost.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_xeno_nest.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_wwiioutpost.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_tomb.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_hierophant.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_elephant_graveyard.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_blooddrunk2.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_dwarffortress.dmm
#_maps/RandomRuins/LavaRuins/lavaland_surface_wizard.dmm

The "we have an issue with a lack of content on this server" is an inaccurate statement, there's a big problem with the more unique or more, and I hate using this terminology because I really adore a lot of the ruins that are being blacklisted, "worth it" ruins being drowned out by the insane amount of content there is for this server. Getting rid of the ruins that are only tiles or turf with no substance wouldn't make enough of a dent.

**Comment by Latentish** [comment]
If anyone has any actual suggestions, I am very willing to hear them as to what should and should not be in this blacklist. I'm not here to remove your content, I'm not here because I enjoy "murdering variety", and this pr does not "remove a chunk of what little content we have" as we have an overwhelming amount of content.
If you have a map you want added or removed from this whitelist please comment its codepath in a civil request below. I've gotten one deaththreat (joking or otherwise) in this pr already, so please try not to let emotions right high. We're all here for the same reason shipping tests.

**Comment by Fikou** [comment]
its a config why are you trying to change it codewise, either go get someone to change the config, or delete the ruins from the codebase, dont half ass it

**Comment by Latentish** [comment]
> its a config why are you trying to change it codewise, either go get someone to change the config, or delete the ruins from the codebase, dont half ass it

Did you read the Pr or its comments at all?

**Comment by triplezeta** [comment]
once #808 is merged and passes over the rockplanet and jungle pools are done this can be looked at

**Comment by ZephyrTFA** [comment]
So, this isn't really how configs work.
You cannot change them on the repo, they can only be changed locally on TGS.
This will need to be modified in TGS.

**Pull request closed without merging**
