### PR TITLE
Arrowhead-Class (for like the third time)

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request
maybe this time I'll actually keep my motivation to add it proper, eh?
Same thing as before, but this time I addressed some of the things brought up last time. Closed shutters, properly orientated buttons and such, y'know. Also moved some consoles around on the bridge and cargo bay.
arrowheadshiptested

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
I mean, it's a ship a considerable number of people liked apparently. Not sure if shiptest needs even more ships really, but I'm PRing it anyways. 

## Changelog

:cl:
add: The Arrowhead-Class Long Range Scoutship is now available.
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
That is by far the most specific whining a linter has ever done that I have seen. Sure.

**Review by Latentish — DISMISSED** [review]
I'm a bit confused on your intent with this ship. You're calling it a "long range scout ship" but I don't see how it's supposed to accomplish that. It looks like to me that it has a niche of good medical, decent botany, gas mining, and a smidge of mining. What niche do you see this filling?

What is this room for?
image

What is this room for?
image

This cycler is setup improperly. Also what are those missing texture objects?
image

I assume this is a gas miner? But please explain to me your thinking here. Also please never leave a pipe with no end, always put an end on pipes, whether it's a scrubber, vent, injector, or a cap (if we have those); this looks like a valve with nothing on the other side.
image

These double windows aren't great. Also please put down preclosed shutters on your engines.
image

**Comment by TheNeoGamer42** [comment]
> I'm a bit confused on your intent with this ship. You're calling it a "long range scout ship" but I don't see how it's supposed to accomplish that. It looks like to me that it has a niche of good medical, decent botany, gas mining, and a smidge of mining. What niche do you see this filling?
> 
> What is this room for? image
> 
> What is this room for? image
> 
> This cycler is setup improperly. Also what are those missing texture objects? image
> 
> I assume this is a gas miner? But please explain to me your thinking here. Also please never leave a pipe with no end, always put an end on pipes, whether it's a scrubber, vent, injector, or a cap (if we have those); this looks like a valve with nothing on the other side. image
> 
> These double windows aren't great. Also please put down preclosed shutters on your engines. image

I mean, I suppose it's not intended to fill any real niche I can think of that isn't filled in some way now, and it's called a long range scoutship because in theory it can self sustain itself indefinitely, given you have botany for food, a really low output but with no real fuel requirements power source, and can in theory collect oxygen needed to breath if you happen to come across any.

That room is literally just an empty room for people to shove things into, be it a small RND setup or whatever else.

THAT other room is the RTG jail. The RTGs are in there. That's all it's for.

missing texture objects there are the same as the vents on the tiles below, but on atmos layer 4 they just have missing texture for WHATEVER reason. It's kinda annoying to me too, but it's fine in all my testing. Not sure what issue there is with the cycler or how its setup incorrectly.

I copied what the solar class (used?) to have. (not sure if it has it still even, but it was supposedly for the idea of being able to refuel plasma.) I can just remove that passive valve if needed, anyways.

I'm not sure what the problem with double windows there are? And there ARE preclosed. On the heaters. They used to just be open by default.

**Comment by Yellow-Mushroom** [comment]
Im going to try and be as concise as possible with the issues related to the map, I'd be happy to elaborate on any questions you may have about this on discord though, so feel free to @ me at any time

comparison

Here is the schmeideberg (green) and the arrowhead (red) compared, with tan being overlapping areas. These two ships are of extremely similar shape, this presents itself as a strong issue when the shape of this ship is one of the key aspects of it. Also, the niche of: Independent generalist (botany, security, medical, mining, atmos (although it is minor), does pose issues due to being a very bloated niche, along with the general direction of trying to move away from independent generalizers.

To add:

image
this machine doesn't really line up with the corner wall it needs to have to look good

Im perhaps not the best person to judge balance but 2 energy guns + a winchester with 2 boxes of ammo + an m1911 and two extra mags seems like a large amount of fire power for a 7 person max ship (although someone else please correct me if I am wrong)

This locker is the wrong direction
image

it is given an organ smart fridge, hypo spray mk2, blood and surplus limbs crates, a sleeper, a wall nanomed, a toxin and firstaid kit, and full surgery tools. This feels like a major amount of medical gear for a smaller 7 person independent ship, especially when the ship having a dedicated medical bay in the first place is a bit strange. 

This room having visible pipes but also non-plating floors leads to some weird visual goop with the vents
image

Almost all specialized rooms (botany, sec, both sides of medical, the kitchen, aft hall, electrical engineering and RTG room) are composed of one wide hallways
image

This armory locker starts both unlocked, and unable to be locked by the spawning captain due to their lack of access. The doors infront of the armory and gunsafe also are not tied to any access
image

The button on this wall is the wrong direction
image

There is no volume pump between the air tanks and the distribution pipes, meaning that at round start, both these tanks drop their full contents of 20,000 mols into the pipe network
image

---

While this ship is functional par for the few atmos issues, I think it struggles from being extremely strong in many many areas and its independent identity along with sharing a shape with the schmiedeberg. I think there is an opportunity to have some specializations that then can inspire the shape a little more, and would be happy to work with you on discord to develop a more unique silhouette, niche, and identity for this ship.

**Comment by TheNeoGamer42** [comment]
I made the original version of this ship well before the Schmeideberg was made, and I kinda agree on the fact the niche its kinda going for is a bit overdone, which my first point still stands. Honestly I am PRing it because I've PRed it a few times before for it to go stale and then I loose motivation and time to work on bringing it up to date properly due to IRL happenings.

The computer having a bit of an issue lookwise is... kinda something I can't really do anything about, honestly, though maybe I could do something small like survival pod windows instead of railings there.

I will say I did never recieve proper feedback on balancing when it was originally made, but I will note that the winchester has ONLY hunting rounds supplied, meaning its kinda completely useless on shooting actual people. I can still tone the amount there down though.

Locker direction is eh, I don't really like the directional sprites for when they are on a wall like that.

The medical supplies on board are ALSO something I recieved no real feedback on at the time, I could easily nuke the nanomed wall vendor, though all it has is a fews prays and patches. The organ storage is also empty and kinda just, there to look neat.

One tile hallways are intentional.

The stuff starting unlocked and the windoors not being access locked are ALSO intentional, but every time I've tested it, the captain could lock the armory locker. The crew should be able to access the guns roundstart without the captain needing to intervene if there is an emergency, or there is no captain, was my thinking there.

fuck i forgot to directionize that button and a fire alarm I see

I kinda agree on the visual issues with the atmos room, and I could probably also put one of those on a valve, but I think there should probably be one connected at start.

I'm also not really sure what your discord is, so, I can't exactly talk to you other than through github at the moment.

**Comment by murder357** [comment]
My biggest complaint about this ship is the power system, i just think it was unnecessary and is just overall horrible for new players or people that dont have that much experience in engineering yet still wanna run a ship.

i may just be too stupid to understand most power generation in ss-13 but seriously, how are these supposed to run?
image
i know it passively generates power, but the max those give is 12.5kw, in a single SMES.

And i may just be dumb for this too, but the pipes here
image
seem to be for charging the plasma thrusters, yet it just doesnt work, at all.

Those are my only complaints, what i suggest to fix them is simply adding a pacman for power or any other easier and more known way. The layout for the RTGs is also horrible imo.

**Comment by triplezeta** [comment]
the arrowhead is supposed to only barely generate enough power to run the ship. turn off equipment, lights, or environmental equipment when it's not in use to conserve energy. (in other words; you are having a power skill issue.)

As for the plasma thrusters, iirc they need a pump in front of the heater in order for them to function efficiently.

**Comment by TheNeoGamer42** [comment]
I've had little issue with the plasma heaters, though I found they do infact take more plasma in if you alt click them, there wasn't enough space to add pumps to each plasma thruster when I first made it. also I think I might've forgot to push changes I made ages ago?
and yeah, zeta's right. you are having a power skill issue, even with the ion thrusters heaters set to take 1kw it produces just enough power to be in the positive if you haven't used said thrusters, and thus, charge really slowly over time. atleast with the base equipment installed with no additional modifications that draw more power.

adding PACMANs would defeat the whole thing with the power of this ship, too, as I personally think PACMANs are just kinda a really shit option, and someone REALLY should design an actual engine for ships instead of what we've been doing, slapping engines designed for station gameplay into ships, or running them entirely on PACMAN generators. With the RTGs, you actually need to give a shit about power, unlike PACMAN generators where, aside from maybe once, unless you completely fail to find plasma ore (impossible), you simply do not have that much of a power issue. sure, they don't have much interaction directly, but they DO force you to think about what you do and run, instead of carelessly having every machine in the known galaxy running on your spaceship with no issue on """emergency""" generators.

**Comment by Latentish** [comment]
I'd be willing to give this  a test merge.

**Comment by TheNeoGamer42** [comment]
goddamnet

**Pull request closed without merging**
