### PR TITLE
Atmos sprite update

### PR DESCRIPTION
**Pull request by SapphicOverload**
## About The Pull Request
Updates the sprites for the atmos firesuit, inhand fireaxe, and fireaxe cabinet to fit in with the rest of the engineering sprites. Also, fireaxe item sprite is no longer upside down when unwielded.
image
image

Sprites are from tgstation/tgstation#72736 and tgstation/tgstation#65199

## Why It's Good For The Game
Makes atmos firesuit and axe sprites fit in with the newer engineering sprites, also I think it looks nice.

## Changelog

:cl:
imageadd: updates some atmos sprites to fit in with the rest of engineering
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
Sorry we didn't get to your pr, can you fix the conflicts here?

**Comment by SapphicOverload** [comment]
Ah right my bad, I'll go fix that

**Comment by SapphicOverload** [comment]
Fixed the merge conflict

**Review by thgvr — APPROVED** [review]

**Comment by SapphicOverload** [comment]
Hang on just noticed the left inhand sprite is a bit weird, let me fix that real quick

**Comment by SapphicOverload** [comment]
Goddamn it, nevermind

**Pull request merged**
