### PR TITLE
Readds Explosive Decompression

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
(Please testmerge first) Enables monstermos

## About The Pull Request
~~It's a little more underwhelming than it used to be, since there's no air movement effects, but it's just like it always was~~ the baby gloves are off now

## Why It's Good For The Game
This is what shiptest was built for

## Changelog
:cl:
add: Explosive decomp is back
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
Doesn't seem to be working in production.

**Comment by MarkSuckerberg** [comment]
bluh bluh centcom is conflicting i dislike you

**Comment by TheNeoGamer42** [comment]
So a bit of a major bug, when a ship docks or undocks, atmos updates first before any directional windows rotate properly to block the intended areas, this results in Fuckery such as any atmos tanks using directionals to suddenly flood into the rooms around them, or any directional windows on the exterior that aren't 4 of them on every direction causing depressurization into space.

**Review by ZephyrTFA — APPROVED** [review]

**Comment by MarkSuckerberg** [comment]
It's passing?? Oh my god

**Comment by PrefabQuasar** [comment]
:flushed:

**Comment by Latentish** [comment]
For someone like me who isn't familiar with explosive decompression, could you provide some context about how it would look in game? Or a recording of it?

**Pull request merged**
