### PR TITLE
Dwarf Legions now drop real dwarves

### PR DESCRIPTION
**Pull request by Sun-Soaked**
## About The Dwarf Request

Title
## Why It's Good For The Dwarf

My Immersion
## Changelog

:cl:
tweak: The dwarf corpses dropped by hivelords are now dwarves by race instead of mutation
/:cl:

### CODE REVIEW

**Comment by Sylphily** [comment]
quite comedic!

**Comment by Sun-Soaked** [comment]
I forgot what they're actually called ingame, they move too fast for me to check their name

**Comment by Ms-Mee** [comment]
Finally... Instant short people... Just add bullets!

**Comment by Sun-Soaked** [comment]
this definitely isn't compatable with mining interrim, so it may be a while before it gets in

**Pull request merged**
