### PR TITLE
The Wrecked Factory Ruin

### PR DESCRIPTION
**Pull request by Gristlebee**
## About The Pull Request

<details>
<summary>The map (updated) (again) (now with buttons)</summary>
<br>

image

image

factory buttons

</details>

This PR adds a new Lavaland ruin themed around Ramzi pirates raiding a Nanotrasen factory. Also adds indestructible titanium walls, and lavaland atmos subtype tiles for plating, rusted plating, concrete, white and dark tiles for use in the ruin.

Increases the max safe temperature for the space syndicate simple mobs from 350 to 400. Turns out lavaland atmos can spawn hot enough they just start dying.

The wall locker mapping helper caught some extra lockers on the Aegis, so I guess that's in here too.

## Why It's Good For The Game

New ruins are good and hopefully this is a good ruin

## Changelog

:cl:
add: Wrecked Factory ruin
add: Indestructible titanium walls
add: Lavaland atmos subtypes for plating, rusted plating, concrete, white and dark turfs
balance: Syndicate Space Simple Mobs have their max temp increased
tweak: Wall_lockers updatepaths on the Aegis
code: Adds ruin to map_catalogue,txt, lavaland.dm and adds it to lavaland.dm areas
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
hahahaha we love acctive turfs. I'll tm this but I need to talk to you about your turf's atmos insurance before you get an approval

**Review by goober3 — DISMISSED** [review]
95c525c5fb0b52dd34a38a8511fbccbe
make the grassy area outside the ruin wider than 1 tile. this'll look Fucked Up if the passthroughs get filled with rocks.
4aeae172ed9e151cadaebd6ef692badd
c72b2ccd72012a47a8d2fa14cc24e31d
case in point.

9c8cb7837f6621c6322616afa704bb90
same goes for here. as a general rule, make rock walls around regular walls at least two or three tiles wide, or they'll look odd from the outside.

5dc6bd9e79031ecd454b11817cdca0ee
try adding some sidings along the hallway with the green border here. same goes for the catwalk path outside. would look neat, i think.

60ea3ec9c3e680326605565a14dd1daf
run 2883_wall_lockers.txt in tools/updatepaths, sire.

517f10145af8af8b1e1939c1b72e811a
these windows need to be /obj/structure/window/reinforced/fulltile/shuttle. window spawners spawn grilles automatically, which means you'd get double grilled.

12fc05d4f5f3536902bb9d4b4bf2c4ab
the floor safe in here will spawn under the carpet. if you want people to see it, add some indication that it's there. or just replace the carpet on the tile that it's on with plating. also, switch environment_smash on this guy to zero, or they will smash the window and walk into lava.

a6c31ab26adde820e85222d0868bd757
use a subtype of /firstaid here. the base subtype for medkits are empty and sad.

8059ed5a75d048d348154a4f3ca4afe2
make this a regular cabinet. personal closets have pre-spawned items and need players to assign their ID to the closet to open them.

05fbbeac5c815c6ef78d7a578aecf6ac
move this decal below the siding.

the enemy to loot ratio in this ruin feels a little off. mostly because gorlex simplemobs are terribly unbalanced, and suck to fight. try to reduce the overall enemy count. the laser sword enemies in particular are annoying to fight in excession. get rid of some of those guys.

image
i've uncovered the horrors.

**Comment by Gristlebee** [comment]
Issues should be addressed if I didnt miss anything and the screenshots have been updated

**Comment by Gristlebee** [comment]
Wagh, tests

**Review by goober3 — CHANGES_REQUESTED** [review]
hi. we tested this in-game. didn't run into any issues. good job.
though, i have a few suggestions.

can you just. remove the melee troops entirely. one of them almost solo'd an entire inteq crew. shrimply too unbalanced.
also, add a stethoscope somewhere for the office safe, if you haven't already.
i'm not so sure about having an NT boss mob in a ruin that's primarily occupied by ramzi clique members (pending actual mob sprites). maybe replace that guy with one of the elite mobs, and give them a little extra health.

**Comment by Gristlebee** [comment]
> can you just. remove the melee troops entirely. one of them almost solo'd an entire inteq crew. shrimply too unbalanced. 

Inteq krill issue, Ill get rid of them.

> also, add a stethoscope somewhere for the office safe, if you haven't already.

There's one in the medical crate in the warehouse

 > i'm not so sure about having an NT boss mob in a ruin that's primarily occupied by ramzi clique members (pending actual mob sprites). maybe replace that guy with one of the elite mobs, and give them a little extra health.

I meant to flavor it as the factory manager barricading themself in the office, and being so paranoid they're firing at anyone who enters, with the implications of the war medals and purple heart in their bedroom along with the drugs in their washroom hinting toward why they might be attacking players on sight. I'd prefer to keep the manager as a story telling element, but if they need to go, they can go.

**Comment by Gristlebee** [comment]
hmm, new issue. With the Syndicate Stormtrooper inside the office as the boss, their bullets can break the windows even with smash environment off if they aggro onto a mob outside. Would it be alright if I gave them the lavaland mob faction? I could also just extend the map a bit and add some more mountainside too so they cant see the mobs.

**Comment by Gristlebee** [comment]
Requested changes have been added. Decided to go with the mountainside anyways so I wouldnt have to worry about any aggro issues with the boss mob. Screenshots have been updated.

**Review by goober3 — DISMISSED** [review]
hi, just one last minor request before we hit merge. it seems that the enemies outside are getting killed by weather. if you could find a way to subvert that or move them into a covered area that'd be cool.

**Comment by Gristlebee** [comment]
I've made the factory a covered area, so they should stop dying now

**Review by Zevotech — DISMISSED** [review]
The whole ruin could use more signs of a fight, as well as more NT corpses to reflect the supposed staff amount. Scatter spent casings around, empty mags, blood trails and footsteps to create the effect of the aftermath of a fight. Break some of the lights and scatter some of the items around in the warehouse and dorms to better sell the effect.

Other maptainers might disagree, but I think you should edit the names and descriptions of the syndicate enemies to reflect the fact that this is a Ramzi Clique attack. Got a lot of people asking why the mobs were syndicate. Hopefully the sprites will get an update to reflect that sooner rather than later.
If you want a suggestion for more mob variety, I'd suggest experimenting with Vicerators as they're a good low-health enemy to scatter about.

This area could use some more conveyors and machines, possibly an expansion in order to show the fact that it's a factory. It isn't very apparent what the purpose of this place was.
image

Add some blood, corpses and casings out here to give the effect of a fight that happened.
image

This place is almost pristine. Add some dust and trash lying around, maybe scatter some of the things on the tables. Try to give it the feeling that it's been lived in and recently disturbed by a fight. Maybe add some overturned tables as barricades in front of the door.
image

Same as the last one. Add some dust, trash, corpses, blood, spent medipens, maybe some improvised weaponry by the workers. The lockdown shutters also need more buttons in the rooms here to prevent people from getting trapped. Not 100% sure on the presence of the Manager as it wouldn't particularly make sense for him to open fire on the people clearing out the Ramzi in the place.
image

**Comment by Gristlebee** [comment]
Factory has been expanded, added some extra blood and corpses, sprinkled some empty mags and bullets along with some extra signs of battle. Popped in some viscerators and regular knife guys for enemy variety. Descs have been adjusted to show that they're ramzi.

Screenshots have been updated

**Comment by Gristlebee** [comment]
wait goddamit, I forgot the buttons

**Comment by Imaginos16** [comment]
Sigh. Sometimes you just gotta do it yourself.

**Pull request merged**
