### PR TITLE
Ship and Shuttle duo package

### PR DESCRIPTION
**Pull request by Mannybrado**
## About The Pull Request
Adds in a new ship, and also, a new shuttle.
Introducing the NTSV Beetle. This ship has one goal in mind: renewability! Features solar power and a basic atmos recycling system. Incredible. Also, features almost every department in cramped space. Remember to turn on solars!
beetle

Also introducing the Explorer Shuttle. Its a shuttle-class ship, meaning its small and doesn't come with a whole lot. Its pretty cheap, though! In the future, I hope it can be placed into other larger carrier-type ships if that ever becomes a thing.
dropship

## Why It's Good For The Game
More ships are good. Ruins next.

## Changelog
:cl:
add: explorer shuttle-class, small cheap... shuttle
add: ntsv beetle, multi-purpose renewable-energy ship with lots of functionality
/:cl:

### CODE REVIEW

**Comment by Mannybrado** [comment]
added NT posters to the beetle

**Comment by TerryTehCoder** [comment]
Can we normalize adding All-in-One grinders to ship Medical Bays? It's tiring to grind up your exobiology plants with a Mortar and Pestle.

**Comment by Sun-Soaked** [comment]
we could, but I'd rather we just fix the stamcrit from mashing a froot for a few seconds on the pestle.

**Comment by Mannybrado** [comment]
buhh ill put one in

**Comment by Mannybrado** [comment]
yeah uhh

**Pull request closed without merging**
