### PR TITLE
Twink Tweaks: The Second

### PR DESCRIPTION
**Pull request by meemofcourse**
## About The Pull Request
imagen
Updates the armory, cryogenics, bar, bridge, and the equipment of the Twinkleshine. Eliminates the vendor and voucher system in favor of a more controlled stockpile by the Lieutenant. Crew now spawn in with barely any equipment, excluding the voicechanger mask, which now works (for real trust me), with some other stuff there and there. The Captain is now a Flotilla Admiral, to reflect the importance of a Twinkleshine. Adds the Redshield Officer.

## Why It's Good For The Game
I should be making ruins.

## Changelog

:cl:
add: Syndicate Cryopod.
tweak: The Twinkleshine has gotten a facelift.
tweak: The Syndicate has started assigning Flotilla Admirals and Redshield Officers to Twinkleshines.
tweak: Crew on the Twinkleshine now have to get their stuff from their lockers.
tweak: Modified the starting text to reflect the lack of telecomms on most ships.
fix: Access on the Twinkleshine.
fix: Syndicate jobs should show up properly on SecHUDs.
/:cl:

### CODE REVIEW

**Comment by Admiral-Gigaton** [comment]
thank god this isnt player spawnable, a dark gygax? nuke op gear? this the shit that gets pirates to SLAM the server

**Comment by goober3** [comment]
>meemofcourse commented on Nov 28, 2023

i love not doing my job!

**Review by goober3 — CHANGES_REQUESTED** [review]
f8c0fd5db9ddafbc2070c2e52c5b4452
some minor scale issues. the bar / kitchen area itself could probably stand to be a tile higher, given the scale of this ship. maybe lose the staircase, too, for extra walking space. give them a table or two as well, if it'd fit.

dfd5ce79bc1328ff7f1116701c096457
this is a minor nitpick but the scrubber and vent arent aesthetically pleasing and i will kill you if you dont fix it.

e4ebf1e6a18029812d0b4307632053b1
more scale issues. move the desk to the left one tile, and move the photocopier elsewhere to make space for the suit storage unit. maybe also remove the windoors on the inner-section of the office so the lieutenant doesn't have to open a window to access their laptop.

9ff11e6d1316bc0de688aaeb5a8f2d6a
you could probably stand to lose these jutty-out bits on both sides. makes the outline more consistent.

34ea378897ce4708911fa8f0043f829a
consider spicing up these aft-areas with things like catwalks, techfloors, and the such. monofloor plating engine rooms are evil and i think we should kill them all.

2c6c57946820e066aa8b1faabdaa8c0b
spline jumpscare under the armory door.

**Review by Latentish — APPROVED** [review]
Looked at this in round, I think this is basically good to merge

**Review by goober3 — CHANGES_REQUESTED** [review]
hi. this looks good. just some minor gripes before we hit merge.
19020fc5cfadeedfff6c033442ce625d
re-arrange the seating here, slightly. the table blocking the door isnt very aesthetically pleasing.
b66579d0a2df77f5e01e25febecadd7a
i'm not sure these grey tiles meld very well with the rest of the ship. try something else here.

**Review by goober3 — APPROVED** [review]

**Comment by goober3** [comment]
fix your conflicts and we can hit merge, i think.

**Pull request merged**
