### PR TITLE
Air alarms now have heaters

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request
Air alarms automatically heat a room if its below normal temperature.

ported from https://github.com/hrzntal/horizon/pull/61

## Why It's Good For The Game

In theory this should make hull breaches less ass to fix, and minor variations in the air shouldn't make the air alarm go ham

## Changelog

:cl:
add: Added built-in heater to air alarms
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
What the fuck why did this make it with no description

**Comment by Zevotech** [comment]
weird new github update related to commits probably.

**Comment by rye-rice** [comment]
what the hell is Prettier

**Comment by MarkSuckerberg** [comment]
> what the hell is Prettier

it reformats the JS to make sure it's as readably formatted as possible. you can use it by getting the extension which I believe is recommended but visual studio code now

**Comment by ZephyrTFA** [comment]
I've gone ahead and ran prettier on the interface file for you; which should clear up the linter failure

**Comment by MarkSuckerberg** [comment]
yeet

**Comment by rye-rice** [comment]
> I've gone ahead and ran prettier on the interface file for you; which should clear up the linter failure

thanks a lot! Can you tell me how you run it? prettier kept on saying that the workspace was outdated or something

**Comment by ZephyrTFA** [comment]
> > I've gone ahead and ran prettier on the interface file for you; which should clear up the linter failure
> 
> thanks a lot! Can you tell me how you run it? prettier kept on saying that the workspace was outdated or something

I opened the file and then saved the file.

**Pull request merged**
