### PR TITLE
The Trinea

### PR DESCRIPTION
**Pull request by Sylphily**
## About The Pull Request
adds a new cargo ship!

## Why It's Good For The Game
new cargo ship with some fun things added, has some RNG boards for to start with but nothing too strong, large cargo hold for either machines or cargo, also comes with a FREE ai because there really seems to be a bit of a command

## Changelog
:cl:
add: Trinea cargo, new cargo ship
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
The ship itself doesn't look bad, but we have the luxemburg, which is another well geared cargo ship with syndicate theming. I think you should consider theming it after another faction, and maybe rethink the departments you put in with it. Cargo ships are hard to balance because having access to a cargo console gives access to a lot more. Maybe swap out the security and mining departments for: EVA/explorer (with absolutely minimal mining gear, like just a pickaxe and no refinery), a store room, and a storefront type area. Just an idea of course, but I would like to see something with a more unique niche to fill.

Aside from all that, I do really like the shape and use of space.

**Comment by Apogee-dev** [comment]
> The ship itself doesn't look bad, but we have the luxemburg, which is another well geared cargo ship with syndicate theming. I think you should consider theming it after another faction, and maybe rethink the departments you put in with it. Cargo ships are hard to balance because having access to a cargo console gives access to a lot more. Maybe swap out the security and mining departments for: EVA/explorer (with absolutely minimal mining gear, like just a pickaxe and no refinery), a store room, and a storefront type area. Just an idea of course, but I would like to see something with a more unique niche to fill.
> 
> Aside from all that, I do really like the shape and use of space.

This one isn't a Syndie ship, it's another ISV. Which, honestly, we have something of a surplus of. My own opinions on the Luxembourg and its place on this codebase right now are probably well-known and this isn't the place to elaborate on them, but another dedicated Syndie cargo ship wouldn't necessarily be a bad thing if this ship were to be re-themed.

That being said this ship is missing a number of elements that range from essential to just encouraged. I've listed them out below in order of importance. It's a long list but around half of the issues below are fairly minor or just plain subjective.

- Overall power level seems fairly strong. This ship starts with an AI, _two_ drones, a completed Ripley, a mostly-complete botany area, _and_ a cargo terminal. Consider stripping some of these back.
- Starting medical supplies. You've added plenty of medical equipment (arguably too much), but no medicine and no formaldehyde or epipens for preventing organ rot.
- Defensive weaponry. The SecTech Lite allows redeeming a sec voucher, yes, but that's still only 1 moderately decent firearm. You might want to add one or two minor weapons like a .38 revolver, shotgun, or some mini eguns, otherwise the ship will be mostly defenseless against most threats, including fauna.
- Window shutters should be closed by default, and thrusters should also have closed shutters or blast doors.
- Fire extinguishers and emergency closets. Both are a source of critical emergency supplies.
- Cash and a selling terminal for cargo. While selling pads are heavily discouraged, the current setup allows absolutely no way to replenish cargo budget.
- Customized job outfits. This is an independent ship, but most of the jobs (specifically the engineering and cargo jobs) are using Nanotrasen uniforms.
- The SecTech Lite and SecDrobe in the security room are technically occupying the same tile. I know they're both accessible, but I'd discourage this kind of stacking where avoidable.
- You may wish to replace the clothing vendors with spare outfit lockers in a few instances, since like many objects they only come with Nanotrasen equipment by default.
- The dorms/cryo room is directly adjacent to half of the ship's main thrusters. There's nothing mechanically wrong with this, it's just weird and kind of off-putting.
- This ship's missing some final aesthetic touches that would make it feel more lived-in, especially things like posters, info/warning signs, dirt, and trash.

**Comment by Sylphily** [comment]
> The ship itself doesn't look bad, but we have the luxemburg, which is another well geared cargo ship with syndicate theming. I think you should consider theming it after another faction, and maybe rethink the departments you put in with it. Cargo ships are hard to balance because having access to a cargo console gives access to a lot more. Maybe swap out the security and mining departments for: EVA/explorer (with absolutely minimal mining gear, like just a pickaxe and no refinery), a store room, and a storefront type area. Just an idea of course, but I would like to see something with a more unique niche to fill.
> 
> Aside from all that, I do really like the shape and use of space.

the cargo console was put there with the outpost stuff in mind and not with the current system because that should *hopefully* be going ways soon, it really doesn't have mining in focus but i guess i can replace the KPA with picks and say RIP to any one trying to catch ice fauna, and the like.

**Comment by Sylphily** [comment]
about the out fits, they should all really be ISV, didn't use any fucky subtypes, also on another note, i could swap the techfab out for just the cargo lathe i guess

**Comment by Sylphily** [comment]
updated, here is the current image

**Comment by Sylphily** [comment]
also can some one tell me what is failing
please

**Comment by SweetBlueSylveon** [comment]
image
I think this is what's causing your run linter error. It's not _maps/_maps/config, it's just _maps/config.

Apogee also had very great insight on this ship. I feel that the thrusters being in that position is just somewhat awkward (even if it isn't mechanically unviable). I see that you've cut back your medical supplies a bit, so that's good. Replacing the cargo console with just the techfab is preferable. Giving them a proper gun or weapon is a good idea. Otherwise this isn't a bad ship at all.

**Comment by PrefabQuasar** [comment]
> also can some one tell me what is failing please

checks are failing because your json is pointing at "trinea.dmm", while the map file is named "Trinea.dmm", its case sensitive, and the map file name should be changed to lowercase

**Comment by Apogee-dev** [comment]
I nearly forgot to mention this earlier, but can you update the .dmm and .json names to reflect naming standards, e.g. independent_trinea

**Review by Latentish — APPROVED** [review]
I'd like to see this get TestMerged to see if there are any underlying issues that are harder to see.

**Comment by AtlasRules** [comment]
image
you forgot to set up the .json right, you want "Trinea-class"

**Comment by Zevotech** [comment]
Why are there two autolathes?

**Comment by Zevotech** [comment]
Engineer slot gets no insuls, and medical doesnt have a single spare medkit.

**Comment by Apogee-dev** [comment]
The ID variables on the cargo bay doors and button don't match or seem to otherwise be broken, according to playtesters. Give it a quick once-over, at least. Engine prechargers also appear to be on the fritz so double check your wiring.

**Comment by Zevotech** [comment]
> The ID variables on the cargo bay doors and button don't match or seem to otherwise be broken, according to playtesters. Give it a quick once-over, at least.

sometimes they work, sometimes they dont. Its weird.

**Comment by Sylphily** [comment]
> The ID variables on the cargo bay doors and button don't match or seem to otherwise be broken, according to playtesters. Give it a quick once-over, at least. Engine prechargers also appear to be on the fritz so double check your wiring.

weird worked fine for me every time?

**Comment by Recoherent** [comment]
Networked AI cores are broken at the moment, since they add latejoin AI job slots instead of polling ghosts or anything. Until that gets fixed, it's pretty much a fancy brick, unless you opt to have a core frame and a posibrain which is not ideal.

**Comment by Sylphily** [comment]
it works just fine man, just take the glass of the core
slap the brain in
recon, and done

**Comment by Roostercult** [comment]
Hello! I'm Roostercult on byond and I would like to mention that the tiles Here:
image
Are airless by default. And because they have tiny fans on them, they wont fill up. Walking in and out of the ship will always cause pressure damage and it's a bit annoying

The ai core doesn't work, that AI core opens a jobslot, and is a job spawner, something that shiptest doesn't really have. I would suggest kinda coppying what the Osprey has, with an unfinished AI core, a few law boards, and a positronic. 
I could also suggest a circuit printer if you're going to have an AI in the ship, so you can give them custom laws, a boris chasis, and an AI integrity restorer.

Another thing: the engines are directly hooked to only the pacman, not the SMES, meaning they wont charge unless you turn off the SMES and turn on the pacman. Which I didn't figure out for 3 hours, But I might just be braindead

**Comment by Roostercult** [comment]
> it works just fine man, just take the glass of the core slap the brain in recon, and done

Sorry for the double post. I was unable to take the glass off the core. I used several different tools and eventually gave up

**Comment by Sylphily** [comment]
oh thank you for mentioning that, your one of the few people that have actually given any feed back

**Comment by Latentish** [comment]
We can marge this once you address some of the other comments.
Replace the networked ai core with an incomplete core instead please.

**Review by Vexylius — CHANGES_REQUESTED** [review]
I'm sorry, but we are currently not merging any independent ships. 
Please theme it after some faction or wait until the freeze is over. 
For more info visit #dev-announce channel on Shiptest discord.

**Comment by Latentish** [comment]
> I'm sorry, but we are currently not merging any independent ships. Please theme it after some faction or wait until the freeze is over. For more info visit #dev-announce channel on Shiptest discord.

This is grandfathered from before the freeze. This one is still allowed to be independent.

**Comment by Latentish** [comment]
I haven't heard of any issues with this map. Do you want to keep this independent or faction it? You're ok to do either, though I'd prefer you faction it.

**Comment by Sylphily** [comment]
i will be working on making it a faction ship aligned with NT

**Comment by Sylphily** [comment]
Closing this because  i don't think its a good ship, just kinda shitty over all

**Pull request closed without merging**
