### PR TITLE
[IDB IGNORE]Kepori Visual Overhaul

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
KEPORI.... TWO!!

PEGGLETWO

image

This PR aims mostly for parity with existing Kepori customization. A few customization options were removed as they didn't offer much. Also adds a new "Head Feathers" sprite accessory type so it's not tied to body, as well as cleaning up existing sprite accessories.

I believe this iteration of Kepori is closer to the original vision of what they should be, and was held back for various reasons during the past iteration. I've spent a long time on this, and I think it has come out very very well. Credits to `spookypineapple` for his great help during this process.

This doesn't include everything for now. I cut out some old jumpsuits that needed updating as I'd have to fully resprite them anyways. Some of them don't even have resprited human versions, so whatever.

TODO:

Literally everything else (not in this PR)

## Changelog

:cl:
imageadd: Kepori have been given a full visual overhaul.
/:cl:

### CODE REVIEW

**Comment by Sun-Soaked** [comment]
this will be breast in 2027

**Comment by Anticept** [comment]
Wear that is not aligned that I have found so far:

- Undergarments
- Engineer scanning goggles (actually seems to be goggles in general)
- Breath masks
- boot blood

**Comment by Slim-Pickems** [comment]
FBP are, naturally, a bit bugged at the moment. I do assume this is already in the works, but are logging it for the sake of logging it.
scuffed

**Comment by thgvr** [comment]
Take note of my TODOs in the pr body

**Comment by thgvr** [comment]
Blood overlays I have no idea how to set up framework for new ones, gotta think about it

**Comment by Anticept** [comment]
Something also keeps moving my sprite down and right from time to time. 
image


Rotation, such as going horizontal or *flip, is rotating around  the far left side of the sprite for some reason.

**Comment by Redrover1760** [comment]
Welding goggles
^ Welding goggles
Kepori cursed one

Anyways outside of the memes, I love these sprites. Aaaaaa

**Comment by Redrover1760** [comment]
Kepori cursed one
Welding goggles
^ Welding goggles floating

Anyways outside the memes I love the new sprites. Voxified Kepori? Yes please.

**Comment by thgvr** [comment]
prosthetics are now "good enough"

**Comment by thgvr** [comment]
Probably go for underwear parity then call this done

**Comment by thgvr** [comment]
It's "done"

**Comment by Anticept** [comment]
Character appearance is missing the Character Adjective when kepori species is selected. Changing to another species is a workaround to get it to show and change it.

**Comment by Anticept** [comment]
All jumpsuits and outerwear is now broken (i_clothing and o_clothing slots) and are not loading kepori specific clothing.

In case it's relevant: rylie's fork as was affected too on sunday, and they still have oldkepori, so I wonder if something got pulled recently that is causing default human clothing to be used.

EDIT: Hoodies still work.

**Comment by FalloutFalcon** [comment]
I bet its this pr.
https://github.com/shiptest-ss13/Shiptest/pull/2992/files#diff-88c50a053fb66bf3d7e6bc4fb8d91156017d286ba2a66f9f4e1872a7cbc0ef24
It had a bunch of stealth changes to species rendering and it never had a test merge.

**Comment by thgvr** [comment]
lol

**Comment by Anticept** [comment]
> I bet its this pr. https://github.com/shiptest-ss13/Shiptest/pull/2992/files#diff-88c50a053fb66bf3d7e6bc4fb8d91156017d286ba2a66f9f4e1872a7cbc0ef24 It had a bunch of stealth changes to species rendering and it never had a test merge.

Good call. There's some commented kepori lines in there that states they should be uncommented with this PR.

**Comment by Anticept** [comment]
Now hats and scarfs/collars are broken hahaha

image

**Comment by Slim-Pickems** [comment]
Inteq Uniforms and Belt slots are also now broken. I am checking to see any other broken uniforms.
Pictured, Inteq Corpsman preview (Talos Class)
image

Note, the vest now works.

**Comment by Anticept** [comment]
Looks like the red beret specifically is broken. I'm looking through the recent changes and I noticed some logic was inverted. If someone doesnt beat me to this, I might take a whack at it.

Tailbags were also broken.

**Comment by Slim-Pickems** [comment]
image
Some shoes are also broken.
Shown is a preview of the Beluga's High Class Passenger.

**Comment by Slim-Pickems** [comment]
> Looks like the red beret specifically is broken. I'm looking through the recent changes and I noticed some logic was inverted. If someone doesnt beat me to this, I might take a whack at it.
> 
> Tailbags were also broken.

It seems to be a lot more than the Red Beret, judging on previews in the character screen.

**Comment by Anticept** [comment]
> > Looks like the red beret specifically is broken. I'm looking through the recent changes and I noticed some logic was inverted. If someone doesnt beat me to this, I might take a whack at it.
> > Tailbags were also broken.
> 
> It seems to be a lot more than the Red Beret, judging on previews in the character screen.

The reason I mentioned this is some hats do work, I just didn't have anything else to test with. So something weird is going on.

**Comment by rye-rice** [comment]
CHECK_USE_AUTOGEN, go fuck yourself

**Comment by Anticept** [comment]
Ok so testing those latest changes, everything looks like its working properly wear wise (well, the stuff we have sprites for anyways. underwears don't work). I didnt do a 100% every single item test, but enough to touch on many that were having issues at one point or another.

There is one more thing: This is still missing:

Elzuose character screen:

image

Kepori screen:

image

I have no way of selecting the adj while kepori species is selected, though I can work around it by selecting another species then back to kepori again.

There's also other stuff that appears in that column that is inaccessible while kepori is selected as well (like phobia quirk)

EDIT: PR up for this PR to fix the missing preferences: https://github.com/thgvr/Shiptest/pull/4

**Comment by Anticept** [comment]
Aside from the PR I linked in the previous post...

The entire /obj/item/clothing/neck/cloak typepath is not working. That includes SUNS cloaks, PGF cloaks, and NT command sashes.

image
image
image


/obj/item/clothing/neck/scarf paths ARE working however.

**Review by rye-rice — APPROVED** [review]
necks clothing work, vox still work, humans/sorothy still work, i do not care about anything anymore, it has worked in game for the past like fucking 2 weeks minus the cloaks lets just fucking merge it, its been done for a while now, i will now fucking scream into the void

**Comment by Anticept** [comment]
Honestly its better to get it merged anyways because we've been doing a lot of song and dance around it. Now everything can just be built on top of newkep. Thanks!

**Pull request merged**
