### PR TITLE
[CURSED] Kepori Collar sprite

### PR DESCRIPTION
**Pull request by Kapu1178**
## About The Pull Request
When you accept me at my best, you need to accept me at my worst.
image

## Why It's Good For The Game
More sprites for a species lacking them.

## Changelog
:cl:
imageadd: Kepori collar
/:cl:

### CODE REVIEW

**Comment by francinum** [comment]
Needs image

**Comment by ToasterBan** [comment]
what next, porting collar grabbing?

**Comment by ZephyrTFA** [comment]
> what next, porting collar grabbing?

I kindly ask you not to do this

**Comment by Zevotech** [comment]
:MENACING:

**Comment by MarkSuckerberg** [comment]
Fear

**Comment by zestybastard** [comment]
oh god hats on kepori really are offcenter

**Comment by Martinpachu** [comment]
god

**Pull request merged**
