### PR TITLE
Auxmos update

### LINKED ISSUE #2489: Saycode needs to be fixed for 515.
Currently, deadchat and saycode in general is not ready for 515. Chat is unsanitized, and ghosts speak in regular say instead of deadchat.

Image

Image

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Updates auxmos to support 515. Support for 514 is being dropped to account for this as the new auxmos version uses the ByondAPI.

Closes #2489 

## Why It's Good For The Game
Lets us use the new features provided in 515, and keep up to date.

## Changelog

:cl:
server: 515 is required to run shiptest now.
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
READY !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! probably

**Comment by thgvr** [comment]
Cut my life into pieces
This is my last resort

**Review by thgvr — APPROVED** [review]
code 👍

**Comment by MarkSuckerberg** [comment]
well. so.

Currently, there's a spurious fail on these ships in the SHIP_PLACEMENT unit test:
- Box-class (constant)
- Pillbottle (infrequent)
- Komodo (rare)

I can't troubleshoot it right now, but honestly I just want to get this in, so I'll fix it some other time. We'll just have to deal with it for the time being. Sorry maintainers.

**Comment by MarkSuckerberg** [comment]
i'm feeling a bit silly tonight

**Pull request merged**
