### PR TITLE
Compatibility fix for FastDMM2

### PR DESCRIPTION
**Pull request by martinlyra**
## About The Pull Request

Turns out this was a stupidly easy fix for this problem when using FastDMM2 (https://fastdmm2.ss13.io/):
image

The error was not on FastDMM2. Rather, unsurprisingly for all SS13 issues, it was on the codebase, not on the tools.

Feel free to compare `master @ shiptest-ss13/Shiptest` to `FastDMMcompat @ martinlyra/Shiptest`

## Why It's Good For The Game

Makes shipediting easier. Better shiptest workflow.

## Changelog
:cl:
fix: Fixed Shiptest being unable to be loaded into FastDMM2
/:cl:

### CODE REVIEW

**Comment by Sun-Soaked** [comment]
The real fix is using SDMM, but this works too

**Comment by martinlyra** [comment]
> The real fix is using SDMM, but this works too

Imagine using SDMM. 

This post was sponsored by the FastDMM2 gang.

**Comment by AtlasRules** [comment]
just you, then?

**Comment by martinlyra** [comment]
> just you, then?

Yes

**Pull request merged**
