### PR TITLE
Spooky's Objects Resprites

### PR DESCRIPTION
**Pull request by GenericDM**
## About The Pull Request
A number of assorted resprites for all sorts of objects.

I didn't test this, so I'll let tests run and ensure it compiles fine.

## Why It's Good For The Game
image
image
image
image
(Don't worry about the duplicate iconstates I fixed those in the actual DMI)
image

## Changelog

:cl: Spooky
tweak: Assorted resprites.
imageadd: A bunch of re-done sprites for various objects. Notably: Sofas, filing cabinets, reagent tanks.
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
We're back

**Comment by Sun-Soaked** [comment]
*crunching metal* 
taschty

**Review by Imaginos16 — APPROVED** [review]
Spriterbros... We're so fvcking back...

**Review by rye-rice — APPROVED** [review]
OH SHIT THIS WAS PRED???

**Pull request merged**
