### PR TITLE
Aspawns byo

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
gimmick ship that's cool but isn't what we want for standard gameplay

## Why It's Good For The Game
Remains to be seen

## Changelog

:cl:
tweak: The BYO has been made Aspawn
/:cl:

### CODE REVIEW

**Comment by ritorizo** [comment]
Why aspawn it it's an actualy a good ship which cause no balance problem and add some well needed variety to the game play loop of shiptest.

**Comment by Erikafox** [comment]
Well it does actually have some good stuff to it, but area creation is jank, and anyone can get one, so it's not something I'd like to leave to purchasing.

**Comment by ritorizo** [comment]
Well it's jank but some people know how to use it. And what do you mean by purchasing, are we bringing back shipcoins ?

**Comment by Erikafox** [comment]
Nah, just purchasing as loading in the ship.

Admin spawn isn't an infinite vault of goodies you're not allowed to touch, if you have a gimmick / idea you can totally ahelp to ask for a ship. We have the bubble in for the same reason.

**Comment by ritorizo** [comment]
The bubble was put to ahelp because it was used for powergaming and we really needed to moderate it's use. 
Of course ahelping is always an option (even more since we have a lot of admins) but I don't see why not give the agency to player to spawn it themselves.

**Comment by Erikafox** [comment]
It's one of the ships that are presented to new players when they try to purchase a ship, and the area creation jank (even if people know how to use it, it's not immediately intuitive), Compounding that in with most ship building projects getting screwed over by our lag / earlier jump, makes it a ship that's not great for free purchasing.

**Comment by ritorizo** [comment]
I guess it do sucks if you don't know what you're getting yourself into. What would you think about adding a warning popup/player age restriction ?

**Comment by Erikafox** [comment]
I'd be open to player age restrictions for a lot of ships, and maybe popups, but it'd need to be coded.

**Comment by ritorizo** [comment]
Sure I can have it coded for tomorrow (where I live), what would be the metric used for playerage ? (hours of play, day since first joined, number of round played...)

**Comment by Erikafox** [comment]
Hours of play is my vote. You may be better off pinging mark or tmt in the discord though.

**Comment by Latentish** [comment]
I don't agree with aspawning the BYO. Even if area editing is kinda janky, it still works usably with this ship.

**Comment by BarteG44** [comment]
objectively bad pr

**Comment by thgvr** [comment]
I still believe we should only offer this ship to people who expressly want it instead of clueless new people who click it looking for something cool.

**Review by Latentish — APPROVED** [review]
> I still believe we should only offer this ship to people who expressly want it instead of clueless new people who click it looking for something cool.

Kay.

**Pull request merged**
