### PR TITLE
IRMG Talos-class Command Clipper

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request
irmg_talos_ingame
irmg_talos
irmg_talos_areas

Adds the Talos-class Command Clipper, an Inteq construction and command ship. Key features include a very large hull with ample space for modification, a large crew capacity, engineering and construction supplies, well-appointed living quarters, and a pre-configured telecomms setup to facilitate communication between Inteq ships (and others, if reconfigured). Compared to other Inteq ships, however, the armory is somewhat sparse, with only pistols and pump-action shotguns, and the engineering layout is... "interesting." Resupplying atmospherics and fuel may take some creative thinking.

The Talos has a crew capacity of 15, consisting of:

- 1 Vanguard, the commanding officer of the vessel.
- 1 Master At Arms, responsible for the upkeep of the armory as well as the security of the ship itself.
- 1 Artificer Class II, responsible for the upkeep of the engine and telecomms as well as coordination of the Artificers.
- 1 Enforcer, general-purpose muscle.
- 3 Artificers, for repairs, construction, and fabrication.
- 1 Corpsman, keeping the crew mostly alive.
- 7 Recruits.

Also fixes a few issues with telecomms configuration that popped up after the faction radio channels were added. Preset telecomms equipment should function properly without as much varediting, now.

- [X] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
Inteq always needs more meat on its bones, and comms ships are under-utilized.

## Changelog

:cl:
add: Added the Talos-class Command Clipper, an Inteq construction and telecomms ship
fix: Fixed preset telecomms machines not functioning as expected
/:cl:

### CODE REVIEW

**Review by Erikafox — COMMENTED** [review]
StrongDMM_Q1bhSfHML6
I think it'd be neat if the Master At Arms had buttons to bolt and open the Armory.

image
The locker there is a smidge out of place, maybe put it at the bottom of the room?
dreamseeker_WL9KI1Jk1v
Consider changing the network var on all these machines to something special, E.G "Talos Commnet", it'll give a little more flavor to anyone who actually peeks into them.
dreamseeker_KxKujS1Q1p
The airmixer needs to be layered above the pipes
dreamseeker_UDunOMs2DL
Middle and Left scrubbers did not link to the air alarm console when the ship spawned in. 
dreamseeker_1YR9k4ps7M
The way the line runs through the tiles feels off to me. Not sure what to do
dreamseeker_loG5WOCrHf
Why are there buttons on both sides ~~and why are they not mirrored~~
dreamseeker_80cjgyA9R6
This spot could use the multi Z power thingie too, I recommend fluffing them as /structures so we don't have any weird things happening though.
image
This room feels empty compared to how textured the neighboring ones are.
KODemhUYBU
APLU \
dreamseeker_IM54DcCUFG
I'm assuming the welder is for ignition, an igniter + timer + screwdriver would be a neat alternative
4sELI2fEP7
The "Preheater" goes to zero and nothing else.
dreamseeker_UEcM7xh2oV
The black pipes (tank output to waste) should probably be visible.
dreamseeker_bZfdZoKSuA
the MOA could also MAYBE use office shutters. 
image
I'd also consider moving the poster over their false wall.
dreamseeker_VNTyU2duDo
This oilstain should be slippery.
dreamseeker_7dozlxg68O
External Air Scrubber. Try replacing with a passive vent or moving it to the atmos area
StrongDMM_w2GJ3nnrFb
This red line should be visible

**Comment by Apogee-dev** [comment]
Addressed most of the suggestions and issues Bjarl raised, with a few exceptions. Couldn't fix the pipe layering over the gas mixer without hiding the pipe entirely and hurting legibility in the process.

**Comment by Erikafox** [comment]
image
I'd put an air alarm back up here, standing in front of the holofield while the burn chamber ignited, trying to do the scrubbers was a very atmospheric experience.
StrongDMM_zLXpY57KuT
Upon more thinking, this should probably be a fairly shitty cooler.
StrongDMM_dCTy9l4dQJ
Are these engines hooked to anything? May be wise to express that they're not some how if that's intended.

Do a lightswitch check btw, I was thinking how cool it'd be to turn the lights off in engineering and subsist off the burn chamber for a few minutes and didn't see one

Doing what I call the lazy engineer way (turning all the pumps to max and sitting around for about 7-10 minutes), I think the thing could use a smidge more fuel 
image


Bonus Review 2 Screenshot:
dreamseeker_ClBWhlfQCx

**Comment by Apogee-dev** [comment]
And that's Pass 2 for review.

**Comment by Calyxman** [comment]
Pretty good ship but filing cabinet blocks the paper. Maybe move the paper and pen onto the front desk, and put the filing cabinet where the paper used to be?

**Comment by Latentish** [comment]
image
What is this airlock room for? Also he controller isn't connected and the door to the left doesn't open if approached from the right.

image
So I like this ship quite a lot, there aren't many issues with it except it's balance a like 1 door But that balance is kinda whack.
So you have a pretty good ballistics armory with 4 independent hardsuits, a fancy TEG, really decked out engineering department, a ripley, inducers, and full comms equipment. But it also completely lacks medical. No surgery room, which is extremely important for a ship as combat geared as this is.

Honestly I'd recommend you soup it up a bit more and make it our admin warship replacement.
Or cut it back quite a bit.

**Comment by Calyxman** [comment]
I don't like the idea of it being turned into an admin warship. It's a fun ship to use and I'd hate to see it become admin-locked.

**Comment by Apogee-dev** [comment]
>engineering airlock

Yeah, the engineering airlock is specifically an anti-plasmaflood measure. Pretty much every round involving a Talos has involved somebody flooding the ship by venting the burn chamber to varying degrees of destruction. The airlock was a final measure to make it functionally impossible to irrecoverably flood the majority of the ship without knocking down walls, along with other preventative measures like making the burn chamber access door only operable by the CE and Vanguard. 

The reason the airlock isn't auto-linked- and the inner door is bolted by default- is because AAC code is kind of a mess and really doesn't like auto-linking with internal areas for some reason (it does this on the fore starboard airlock too). The band-aid fix for that is just requiring players to manually link the doors, which only takes a second and can be done by anyone with engineering access (required to access the engineering compartment anyway, because the doors are access-restricted).

>balance concerns

I'd say the Talos has a respectable armory but I really wouldn't consider it _strongly_ combat-geared, especially compared to the other two Inteq ships, which have more powerful ballistic armament and the exact same lack of medical equipment to balance it out. I wouldn't be against reducing the armory somewhat, though. At present it has as many handguns as there are security jobs (three enforcers and one master-at-arms), and the three shotguns cover the remaining two officers (CE and Vanguard) with one to spare. I could probably shave it down to three handguns and two shotguns.

I'm not sure what you mean by inducers, by the way. There are none placed on the map, they shouldn't be included in any of the job outfits, and I fundamentally loathe the things. Did you find one as maintenance loot?

also the Ripley is the cargo ripley with very little HP, two equipment slots, and no drill, so it's really just a vehicle for the mech-mounted RCD.

**Comment by Calyxman** [comment]
Inducers are default as part of the electrical locker

**Comment by Apogee-dev** [comment]
> Inducers are default as part of the electrical locker

Figures. First off, they should be removed from all roundstart spawns entirely IMO, but secondly I guess I'll just manually stock it.

**Comment by Erikafox** [comment]
wait a sec, I've already got a branch up to remove the inducers. Just gotta find the fucking .dm

**Comment by Apogee-dev** [comment]
integration tests why

**Comment by Erikafox** [comment]
image
dreamseeker_rvGVuOzkvM
consider no-diagging these?

**Comment by Apogee-dev** [comment]
> image
> dreamseeker_rvGVuOzkvM
> consider no-diagging these?

Ruins the shaping of the hull itself. Without a way to just tell a diagonal wall to always display a specified floor turf underneath it this is just kind of a problem suffered by most ships.

**Comment by Apogee-dev** [comment]
Implemented some general nerfs by reducing the number of security jobs on the ship as well as the armory loadout, and nerfing some of the unique gear the MAA and Artificer Class II get.

**Review by Erikafox — APPROVED** [review]

**Comment by Latentish** [comment]
Add a page of instructions on that center airlock, and this is good for merge.

**Pull request merged**
