### PR TITLE
Configurable Overmap Size

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Moves the overmap into a virtual z-level, allowing you to specify in the config what size you want the overmap to be. Also makes the virtual z-level self-looping so that it appears to smoothly loop.

## Why It's Good For The Game
Smaller or bigger maps, no more relying on centcom/z1 and the absolute position

## Changelog
:cl:
tweak: The overmap now appears to smoothly loop
tweak: The overmap is now stored in a virtual z-level
server: Overmap size is now configurable
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
woop

**Review by ZephyrTFA — APPROVED** [review]
Looks good, test merge first

**Comment by MarkSuckerberg** [comment]
Overmap border turfs don't spawn numbers anymore for some reason, hold off on merge

**Comment by UltraNumeron** [comment]
Yeah saw the  comment above, the borders are quite a problem gets really hard to navigate when you dont know that youre wraping round.

**Comment by MarkSuckerberg** [comment]
Numbers issue fixed in [77b7630](https://github.com/shiptest-ss13/Shiptest/pull/723/commits/77b76309f6dd6d9573830dd4fb05191ef51c4f76)

**Comment by ZephyrTFA** [comment]
If this was testmerged and didnt break things LGTM

**Pull request merged**
