### PR TITLE
New Ruin: Frost Bar

### PR DESCRIPTION
**Pull request by theXDkidoflol**
## About The Pull Request
Adds a new ruin to ice planets, the Frost Bar; a bar shot up by the syndicate over just some skub! Now, though, they've been abandoned, and they're not taking any chances on getting off the planet...
image

The loot is primarily a minibomb, a tommy gun and a spare magazine for it, and a stetchkin with two spare magazines. Also adds areas and a datum for said ruin.
Oh! This is also my first time mapping, or doing anything related to BYOND, so I'm open to criticism.

## Why It's Good For The Game
It's another ruin! More ruins mean more content, which can greatly expand the longevity of the game. Plus, it adds another way to get illegal tech, and some stronger enemies for those up to the challenge, while still providing the option to retreat if it gets too dangerous.

## Changelog
:cl: Grey
add: Adds a new ruin, the Frost Bar, with some deadly enemies and a trivial matter to fight over! It does have fitting rewards for those up to the task...
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
I think you want a different subtype of the wide glass door.

**Comment by theXDkidoflol** [comment]
> I think you want a different subtype of the wide glass door.

Doesn't seem to be any other subtypes available; that's the only two-wide door I can find. What's the problem with it, anyway?

**Comment by theXDkidoflol** [comment]
changed format to TGM + added two tiles above one of the drop pods

**Comment by UltraNumeron** [comment]
is that a gibber or food processor in the kitchen, whatever it is maybe add the other one too for a full kitchen setup.

**Pull request closed without merging**
