### PR TITLE
The Drinkening

### PR DESCRIPTION
**Pull request by GenericDM**
## About The Pull Request
This pull request contains an incredible number of changes to item names and descriptions regarding everything drinkable.
This has been a long time coming, and was put off for quite a while due to my own procrastination.

This is almost certainly going to have mapping errors, but I'm not checking them all myself. I'll let the tests figure it out for me.

- Space Mountain Wind changed to Comet Trail
- Dr. Gibb changed to Tadrixx
- Starkist changed to Lunapunch
- PWR Game changed to Pacfuel
- Lemon Lime changed to Orange Soda
- Nuka Cola removed
- Thirteen Loko changed to Vimukti
- Fetching Fizz removed
- Manhattan Project removed
- Narsour removed
- Monkey Energy changed to Xeno Energy
- unbranded water bottle changed to Ryuunosuke Reserve
- space beer changed to Bizircan Brewery GDM
- Magm-Ale changed to RHIMBASA TAP
- Space Cola reflavored
- Tonic water reflavored
- Soda water reflavored
- Grey Bull changed to Crosstalk
- E-Fuel removed
- Canned Air reflavored
- Molten Bubbles reflavored and refactored
- Plasma Fizz reflavored and refactored
- Gin reflavored
- Whiskey reflavored
- Vodka reflavored
- Tequila reflavored
- Patron reflavored
- Rum reflavored
- Holy water reflavored
- Vermouth reflavored
- Kahlua reflavored
- Goldschlager reflavored
- Cognac reflavored
- Wine reflavored
- Absinthe reflavored, randomization removed
- Premium Absinthe reflavored
- Lizard Wine reflavored, again
- Hard Cider reflavored
- Amaretto reflavored
- Grappa reflavored
- Sake reflavored, as well as random reskins
- Fernet reflavored
- Orange Juice reflavored
- Cream reflavored
- Tomato Juice reflavored
- Lime Juice reflavored
- Grenadine reflavored
- Applejack reflavored
- Champagne reflavored
- Blazaam reflavored to Hyperspace Highball(I've never even heard of this?)
- Trappist Bleu reflavored
- Hooch reflavored
- Moonshine reflavored
- Creme de Coconut reflavored
- Cuba Libre reflavored to Frontier Libre
- White Russian reflavored to White Gezenan
- Irish Cream reflavored to Zohil Cream
- Manly Dorf reflavored to Shortstop
- B-52 reflavored to AM-G
- Irish Coffee reflavored to Gezenan Coffee
- Black Russian reflavored to Black Rachnid
- Manhattan reflavored to Twelve Crossings
- Red Mead reflavored to Drop-pod
- Allies Cocktail reflavored to Canton Cocktail
- Acid Spit reflavored to Cracked Moon
- Amasec reflavored to Ren Kirsi
- Irish Car Bomb reflavored to Lightspeed
- Syndicate Bomb reflavored to Gorlex Surprise
- Hivemind Eraser reflavored to Hivemind
- Erika Surprise reflavored to Terraformer Surprise
- Driest Martini reflavored to Saltflat
- Banana Honk reflavored to Creamtruck
- Silencer reflavored to Choker
- Hippie's Delight reflavored to Between the Mandibles
- Alexander reflavored to Ash-Shield
- Amaretto Alexander reflavored to Happy Huntsman
- Sidecar reflavored to Bridge Bunny
- Kamikaze reflavored to Mothball
- Moscow Mule reflavored to Gorlex Gator
- Fernet Cola reflavored to Weldline
- Branca Menta reflavored to Mirage
- Bug Spray reflavored to Stunball
- Jack Rose reflavored to Jackalope
- Duplex reflavored to North-South
- Mauna Loa reflavored to Inner Fire
- Mudder's Milk reflavored to Miner's Milk
- Freezer Burn reflavored to Hullbreach
- Archmagus' brew removed
- Cogchamp removed
- Shambler's Juice reflavored to Shoal Punch
- Gibb Floats reflavored to Tadrixx Float

Vending machines reflavored

Good lord I hope I didn't miss anything.

Immense thanks to Stripes for doing all of the writing for this, with some help from our lore team. We miss you. I hope you're doing well.

## Why It's Good For The Game
Distances us from TG, and helps build our setting.

## Changelog

:cl: @thestripes, @meemofcourse , @GenericDM 
tweak: reflavors nearly every drink ingame
/:cl:

### CODE REVIEW

**Comment by meemofcourse** [comment]
one must imagine sisyphus happy

**Review by FalloutFalcon — APPROVED** [review]
Looks good. You could create a regex for any mapping thats not yet merged but its not that bad to do by hand.

**Comment by thgvr** [comment]
No updatepaths? Its over

**Comment by thgvr** [comment]
no react andies allowed

**Comment by Imaginos16** [comment]
TM requested by PR author.

**Comment by Hlscientist** [comment]
image

**Comment by Hlscientist** [comment]
Im like, 99% sure tequila isnt in the vendors, neither is absethine

**Pull request merged**
