### PR TITLE
Removes away missions

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
old and unmaintained

## Why It's Good For The Game
has anyone on this codebase used them

## Changelog

:cl:
del: away mission templates
/:cl:

### CODE REVIEW

**Comment by goober3** [comment]
wow! these sure were maps that existed

**Comment by BarteG44** [comment]
i mean it would be pretty awesome of mins used these

**Comment by thgvr** [comment]
i dont even think we can load them

**Review by MarkSuckerberg — APPROVED** [review]
gonna be real the maps suck anyway even if we could load them. goodbye

**Pull request merged**
