### PR TITLE
New Beachplanet Sandcastle Ruin

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
hey its me zevo back again with another night of no sleep and a brand new ruin for beachplanet

image

## Why It's Good For The Game
One new ruin of many to come. Had this idea for a while and finally decided to add it.

## Changelog

:cl:
add: Beachplanet Sandcastle Ruin
/:cl:

### CODE REVIEW

**Review by Erikafox — CHANGES_REQUESTED** [review]
I'm not sold on the idea of a giant sand castle

Please remove the water loop around the ruin, I'd replace it with more sand, and add some variety to the sand that's there. Rarely is sand Just Sand. Small plants growing, driftwood, shellfish, those kinds of things will make it Alive.

Replace the sand doors with sand airlocks and just make the ruin powered. Or get better sprites. Door sprites are seriously awful.
firefox_WVqLoATQVl
why bother with a gate if you can just weld the wall next to it down. Also missing corners
Lots of missing corners
firefox_sgM5AMJldX
this is a room filled with traps. I'm not sure the bear traps are even armed.

**Review by Latentish — CHANGES_REQUESTED** [review]
This is four circles and a square of sandstone walls. A sand castle ruin idea is cool but it needs more detail and attention than this. Like, a lot more.

**Comment by Zevotech** [comment]
ehhh yeah its a cool idea but i dont really feel like putting more work into it if its going to be denied anyways. That and the layout sucked. maybe another time.

**Comment by BarteG44** [comment]
i actually really liked the look of this one. ruins are not ships and imo shouldn't be held to the same quality standards anyways especially since we need way more of them than ships

**Pull request closed without merging**
