### PR TITLE
Adds(ports?) lizard screams.

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request
Ports(is it even porting if its mine?) PR from bee (https://github.com/BeeStation/BeeStation-Hornet/pull/2407) adding 4 new *scream sounds for lizards.

## Why It's Good For The Game
Lizards need to be heard

## Changelog
:cl:
soundadd: Lizards now have a sound when screaming.
/:cl:

### CODE REVIEW

**Comment by zestybastard** [comment]
Heartfelt: We Taught Every Lizard How To Feel Suffering

**Comment by super12pl** [comment]
> Heartfelt: We Taught Every Lizard How To Feel Suffering

You need to first know suffering to feel happiness 😔

**Comment by zestybastard** [comment]
> 
> 
> > Heartfelt: We Taught Every Lizard How To Feel Suffering
> 
> You need to first know suffering to feel happiness 😔

you're telling me the lizards werent happy before ??????? :samsungsob:

**Comment by terg-but-ius** [comment]
> > > Heartfelt: We Taught Every Lizard How To Feel Suffering
> > 
> > 
> > You need to first know suffering to feel happiness 😔
> 
> you're telling me the lizards werent happy before ??????? :samsungsob:

real suffering is not known

**Comment by rye-rice** [comment]
While you're at it could you also add ethereal screams?

**Comment by super12pl** [comment]
> While you're at it could you also add ethereal screams?

I can include the sound of a lightbulb burning out if you wish

**Comment by ToasterBan** [comment]
now port toe stubbing so I could hear this more often :trollface:

**Review by MarkSuckerberg — APPROVED** [review]
So powerful

**Pull request merged**
