### PR TITLE
New Jungle Ruin: Abandoned Garden

### PR DESCRIPTION
**Pull request by Aquidu**
Hello! This is my very first PR, please be patient with me if I missed things.

## About The Pull Request
Adds my ruin, the Abandoned Garden! A small crashed shuttle made into a makeshift domicile by an unknown person. It's unclear how long ago they were last here, as well as it's unclear if they were present at the actual crash event. A small, non-hostile ruin containing hydroponics equipment, seeds, a medkit, and some wooden tools.

StrongDMM With Areas
StrongDMM-2024-09-04 02 05 42
StrongDMM WIthout Areas
StrongDMM-2024-09-04 02 04 52
In-Game
Orobas Omicron 2024-08-08 231739

## Why It's Good For The Game
From my understanding, a lot of people want new ruins. Since I'm an absolute beginner at this, I thought it would be best to make a small, passive ruin on one of the easier planets. This ruin, while not possessing any rare or powerful gear, can give a ship the potential to start up a ghetto botany setup, as well as a few misc items to make it worth their while. The cozy layout is also meant to give players a comfortable space for roleplay, perhaps discussing the nature of the ruin while waiting out a rainstorm.

## Changelog

:cl: Aquidu
add: Map jungle_abandoned_garden.dmm
add: 4 new areas for jungle_abandoned_garden.dmm
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
@shiptest-ss13/maptainers

**Review by meemofcourse — CHANGES_REQUESTED** [review]
imagen
please use fake lattices (/obj/effect/decal/fakelattice)
imagen
perhaps don't have these two just strewn around? add a cabinet, or something, to store these in. maybe a candle or torch by the bed, and somewhere to leave clothing.
imagen
you can't seem to interact with these curtains on the corner
imagen
railings for the bonfire, mayhaps
imagen
i looked into the code for this spawner and it seems it can have cherry bombs. i wish to ask for you to remove it from the list of possible lootdrops. if you don't know how to do this, ask for help in the discord
imagen
imagen
i don't know how i feel about there being a grand total of four-five external airlocks. maybe you could make these into torn off rooms instead of a Ship with Five Exits?

considering this is where someone lived, and since there won't be much of a threat, it does lack some Stuff for being a flavor focus ruin - things like living amenities or staying sane until rescue(?). things like sewn plushies, writing implements for a diary, an outhouse in the back of the ship, or just leftover items from the ship like emergency cabinets and empty rations could be nice. and instead of a baseball bat, it could make more sense to leave a hatchet as a weapon.

cool first ruin, my only major gripe with this map is that it is on the smaller side of things, and it is important to consider it will be (for a while, at least, until we get subruins and whatnot) the biggest landmark that attracts people, but it's ultimately a flavorful ruin, and we do need ruins

**Comment by Aquidu** [comment]
-fake lattices
sure thing, i'll get right on that. if you don't mind me asking, what's the difference between them and why do we use the fake ones instead?
-baseball bat and buckler on the floor, curtains
i think i can knock these out in one fell swoop if i move the dresser down and left one tile and put a cabinet right next to the bed, the idea i was going for was that the bat and buckler would be right next to the bed so whoever lived there would immediately equip them after getting out of bed, but i do agree it looks weird on the floor.
-bonfire railings
easy, yeah i can do that
-cherry bombs
think i can do that too, if i lose my way i'll ask for help on discord
-external airlocks
so basically the vibe i was going for with this ship was sort of like a civilian transport, almost like a train similar to the pubby station emergency shuttle if you've seen that, sort of inspired off of like a subway or tram car. the exits aren't meant to be functional, hence why they're boarded and welded, but if you think it'd fit better without them or changing them to a different door type like the regular shuttle doors i can do that too. but yeah the purpose of there being so many would be for people disembarking. i'm not too sure about adding more rooms above and below, mostly cause that would kinda kill the whole "train" aesthetic i was going for, but if you do insist it looks too weird i'll change it up. 
-needs more flavor
think i can do this, i did try to put a fair amount in like the makeshift wooden kitchen, loom, the garbage patch out back, etc. but i can certainly do more, i mostly wanted to use wooden objects to give the impression that most of it was built by the person there, and there's only so many wooden objects to use, but i think i can do some more stuff for that. also, i did try to have an "outhouse" in the cockpit with that wooden toilet you can see in the thumbnail images but i couldn't code it right so i ended up removing it
-small ruin
yeah that was the main thing i was worried about, this is my very first ruin so i was kinda worried about making something that would feel too bloated, i'll be making some bigger ones after i can get this one perfected, this is mostly just kind of a "test run" for me.

**Review by meemofcourse — APPROVED** [review]
yea

**Comment by rye-rice** [comment]
@Zevotech

**Comment by Latentish** [comment]
This just doesn't makes the cut, apologies.

**Pull request closed without merging**
