### PR TITLE
Removes the Metis

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

Removes the Metis from the game.

## Why It's Good For The Game

The Metis has been slated for removal for months now, pending a replacement. A replacement has not been forthcoming, and, in the meanwhile, the Metis continues to cause problems. If nothing else, removing it should hopefully encourage a prompt replacement.

## Changelog

:cl:
del: Removed the Metis
/:cl:

### CODE REVIEW

**Comment by goober3** [comment]
metis??? more like meh-tis!

**Comment by rye-rice** [comment]
more like, a year of looking for an replacement

**Comment by thgvr** [comment]
good

**Review by spockye — APPROVED** [review]
go crazy
go wild
go crazy
go wild!

**Review by Erikafox — APPROVED** [review]

**Pull request merged**
