### PR TITLE
Dwayne Mark.II

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Finishes the dwayne update started in the any% walls pr. I never finished it there because there were 100+ maps to deal with so this could wait.

Also adds the Mark.I, certain reptils might recognize it

Screenshot_6705

Screenshot_6704

## Why It's Good For The Game

I fucking love this ship, it needs love, ship #1 should live

## Changelog

:cl:
add: Dwayne MK.I
tweak: The Dwayne Mark.II has been updated
/:cl:

### CODE REVIEW

**Comment by goober3** [comment]
no!!! my dwayne shrinklet PR!!!

**Comment by MarkSuckerberg** [comment]
subshuttles are stored in the dwayne <3333

**Review by spockye — CHANGES_REQUESTED** [review]
image

wire fuckies

image

while creative, DONT do the bunk beds without proper sprites for it (and the code necessary)
players wont really be able to use it well. (also light on poster)

image

this is quirky (not asking you to change anything)

image

please add some blast doors for the engines!

image

poster light

**Comment by rye-rice** [comment]
@spockye, adressed requests, the posters were on the other side of the walls, but i changed their position anyways

**Comment by spockye** [comment]
> @spockye, adressed requests, the posters were on the other side of the walls, but i changed their position anyways

always good to leave some open wallspace in any case! (for players to add posters and whatnot, and to show off out beautiful walls)

i'll give you a new review once i've seen the ship in action. Good work with it!

**Comment by spockye** [comment]
get checks to pass, and i'll TM this

**Comment by rye-rice** [comment]
ough

**Comment by rye-rice** [comment]
checks pass, yayay @spockye

**Comment by spockye** [comment]
> checks pass, yayay @spockye

*un-passes your checks

Remember, no ship versions. Remove the Alt!

**Review by Latentish — CHANGES_REQUESTED** [review]
It looks like you might have doubled your atmos piping. Please fix your atmosery.

**Comment by rye-rice** [comment]
updating this to master corrupts the map, ah well

**Pull request closed without merging**
