### PR TITLE
[IDB IGNORE] Demodularize all whitesands sounds and icons.

### PR DESCRIPTION
**Pull request by ZephyrTFA**
Does what the title says.
Regexes used:
```/'whitesands\/([^']*ogg)'/'$1'```
```/'whitesands\/([^']*dmi)'/'$1'```

Also adds a new unit test ensuring atoms have a proper icon_state that actually exists.

### CODE REVIEW

**Comment by rye-rice** [comment]
the great demargulization continues

**Comment by rye-rice** [comment]
also i think a [IDB IGNORE] would be good for this

**Comment by tiramisuapimancer** [comment]
bless

**Comment by ZephyrTFA** [comment]
DNM this by the way, I still need to progressively go through all the icon_states to copy/replace them over. This will take a while to do so just DNM.

**Comment by ZephyrTFA** [comment]
(If you want to help me with this you can PR to my branch btw 👀 )

**Comment by Kapu1178** [comment]
Re-request when it's ready.

**Comment by MarkSuckerberg** [comment]
image
😓

**Comment by Kapu1178** [comment]
~~what if we just yolo merge it and fix whats broken after~~

**Comment by ZephyrTFA** [comment]
haha, more conflicts than github can even show, new PR time

**Pull request closed without merging**
