### PR TITLE
Scrapper-A Tweaks

### PR DESCRIPTION
**Pull request by Omppusolttu**
## About The Pull Request

A rework of the scrapper-a, fully replacing hydroponics with an autolathe and engineering + cargo protolathe.
Other changes are either minor or visual.

## Why It's Good For The Game

Ship better

## Changelog
:cl:
balance: Reworked the Scrapper-A
/:cl:

## Picture
scrapper

### CODE REVIEW

**Comment by sunofang** [comment]
This would turn the scrapper into a god-tier ship. Might want to consider increasing cost a lil.

**Comment by Omppusolttu** [comment]
> This would turn the scrapper into a god-tier ship. Might want to consider increasing cost a lil.

Cost increased to 1k

**Comment by Omppusolttu** [comment]
> This would turn the scrapper into a god-tier ship. Might want to consider increasing cost a lil.

Fucked up increasing cost by merging to master instead of scrapper branch. **Actually** increased cost

**Review by jupyterkat — CHANGES_REQUESTED** [review]
get your line endings straight

**Comment by triplezeta** [comment]
oh you're not going to like what i did to your map spycrab

**Comment by Firefox13** [comment]
~~fans instead of an airlock that noone actually uses maybe?~~

**Pull request closed without merging**
