### PR TITLE
Sleeper Sprites by Yours Truly

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does what it says on the tin, updating the sleeper sprites! Here's me hoping there's nothing wack about this PR, since I nuke Cryogenics2, which seems to have been entirely unused save for the cryopod.
image

## Why It's Good For The Game
Better sprites!

## Changelog
:cl: PositiveEntropy
imageadd: Resprites the normal and syndicate sleepers!
imagedel: Erases Cryogenics2.dmi from existence.
/:cl:

### CODE REVIEW

**Review by triplezeta — APPROVED** [review]
😀

**Comment by rye-rice** [comment]
😃

**Comment by MarkSuckerberg** [comment]
image

The `bscanner` icons are used in a map file's varedits (this is why you use subtypes smh), can you transfer these three from the old cryogenics2.dmi?

**Comment by Imaginos16** [comment]
> image
> 
> The `bscanner` icons are used in a map file's varedits (this is why you use subtypes smh), can you transfer these three from the old cryogenics2.dmi?

Thanks VSCode, sure!

**Review by MarkSuckerberg — APPROVED** [review]

**Pull request merged**
