### PR TITLE
Adds more items to loadout/gear

### PR DESCRIPTION
**Pull request by super12pl**
## About The Pull Request
Adds a bunch of items to be used as loadout, including whole new footwear category.
Also moves loadout out of whitesands folder.

## Why It's Good For The Game
More customization options is good

## Changelog
:cl:
add: More items in loadout
code: Moves loadouts out of whitesands folder
/:cl:

### CODE REVIEW

**Comment by super12pl** [comment]
I refuse to acknowledge Integration Test's verdict

**Comment by ZephyrTFA** [comment]
Whitesands folder is deprecated, move it to a dedicated module folder, or make one if there isn't an applicable one

**Comment by super12pl** [comment]
Should be ready to merge now

**Comment by super12pl** [comment]
> Should be ready to merge now

Merge my fucking PR

**Comment by ZephyrTFA** [comment]
make me, oh shit wait

**Comment by super12pl** [comment]
> make me, oh shit wait

:trold:

**Pull request merged**
