### PR TITLE
Komodo boot and baggage update.

### PR DESCRIPTION
**Pull request by axelzonvolt**
## About The Pull Request
This started as an effort to address the over abundance of jackboots (a filthy nanotrasen product!) in place of the faction neutral combat boot on the syndicate warship.

And then I noticed a misplaced fire extinguisher cabinet in the bar. A broken icon state in the captain's locker. a light tube placed ON a defibrillator wallmount...

## Why It's Good For The Game
misplaced, broken or even mispathed objects are awful. This PR addresses quite a lot of that and provides numerous SMALL adjustments to the komodo-class vessel.

for example, this is the armory before I addressed it.

komodobefore

and this is after.

komodoafter

## Changelog

:cl:
tweak: komodo medbay had the actual and useless cyborg limbs replaced with prosthetics
tweak: light tubes, fire extinguisher cabinets, apc/air alarm placement and light switches have had their relative positioning across the komodo changed for a consistent look and to reduce floating/mapping sins.
fix: armor/vest/security/hos was missing an icon_state path. 
fix: changed shoes/jackboot with shoes/combat in the job_types\captain.dm file for the gorlex, cybersun and aclf command subtypes.
tweak: the fax machine on the komodo bridge was switched with the neighboring desk tile and objects that it was preventing easy access to.
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
Can you please clean up the changelog, it doesn't make much sense as is

**Comment by axelzonvolt** [comment]
I... listed what was changed and where.

**Comment by Zevotech** [comment]
> I... listed what was changed and where.

what they mean is to specify the changes are to the komodo map. in the big changelog they'll end up looking like general changes.

**Comment by axelzonvolt** [comment]
right. cleaned up the change log and someone pointed out an issue with the fax machine placement. This SHOULD be the final revision for now.

**Comment by spockye** [comment]
fix checks please!

**Comment by axelzonvolt** [comment]
all checks green across the board after severe prodding.

**Review by goober3 — APPROVED** [review]
yeah. sorry for the wait. i'll get this TM'd next uptime.

**Comment by Latentish** [comment]
Please fix your merge conflicts so we can tm this.

**Comment by axelzonvolt** [comment]
I am honestly at a loss as to why the github action bot gave it the merge conflict label. [1c94f92](https://github.com/shiptest-ss13/Shiptest/pull/2375/commits/1c94f92bb3fc89a6c666132315168afd7439ffe0) was completely fine. I don't have write access to resolve the conflict and there are no problems on my end when launching it via a private server. VSC and github desktop aren't reporting issues either.

I'm KIND of stuck now...

**Comment by thgvr** [comment]
Hi there,

Your merge conflicts are because the `syndicate_gorlex_komodo.dmm` file was moved to `shuttles/syndicate/syndicate_gorlex_komodo.dmm` from `shuttles/shiptest/syndicate_gorlex_komodo.dmm`. This was done in https://github.com/shiptest-ss13/Shiptest/pull/2378. If you move it there and commit, it should resolve. It can be confusing because I am almost certain vscode will not alert to this.

**Comment by axelzonvolt** [comment]
green across the board once more.

**Pull request closed without merging**
