### PR TITLE
Buildmode & Supply Pod Ports

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
Ports admin improvements/qol for tools from tgstation
### Buildmode stuff
- [x] https://github.com/tgstation/tgstation/pull/52249
- [x] https://github.com/tgstation/tgstation/pull/57457
- [x] https://github.com/tgstation/tgstation/pull/58715
- [x] https://github.com/tgstation/tgstation/pull/69428
- [x] https://github.com/tgstation/tgstation/pull/76095
### Supply pod stuff
- [x] https://github.com/BeeStation/BeeStation-Hornet/pull/3837

## Why It's Good For The Game
wa

## Changelog

:cl:
admin: Improved admin build mode menu and Drop pods from tgstation
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
Can't test pods in local host because it doesn't load centcom :(

**Review by rye-rice — APPROVED** [review]
yes

**Comment by rye-rice** [comment]
image
fix linters

**Comment by thgvr** [comment]
I have no idea what that lint error means

**Comment by rye-rice** [comment]
remove "var/" from the procs

**Pull request merged**
