### PR TITLE
Removes departmental budget cards from Department Head Locker item pools.

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Removes departmental cards from department head locker pools.

## Why It's Good For The Game
upwards of 80k credits being accesable to crews this easily aint good, especially if they can make cargo.

## Changelog
:cl:
del: removes deparmental cards from the head locker item pools.
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
please dont bully me for backspace coding again im just trying to work on outposts

**Review by ZephyrTFA — CHANGES_REQUESTED** [review]
Instead of commenting stuff out, just delete the offending lines.

**Comment by Zevotech** [comment]
last time i did that i got yelled at for removing coder culture so i decided to err on the side of caution. my pain truly is endless.

**Review by Zevotech — COMMENTED** [review]
fair enough, though

**Review by Kapu1178 — CHANGES_REQUESTED** [review]
Just delete them, no need to comment out.

**Comment by ZephyrTFA** [comment]
@Zevotech

**Comment by Zevotech** [comment]
yeah

**Review by ZephyrTFA — APPROVED** [review]

**Review by Kapu1178 — APPROVED** [review]

**Pull request merged**
