### PR TITLE
Flower go in hair

### PR DESCRIPTION
**Pull request by RDS88-beeman**
## About The Pull Request
This PR allows you to wear fireblossoms on your head, and makes a sprite for them.

image
image
image

## Why It's Good For The Game
Gives people a flower to wear so they can be in touch with nature without having to cultivate flowers for twelve years. Also ultra lowtech head mounted lightsource.

## Changelog
:cl:
add: Lets you put fireblossoms in your hair.
/:cl:

### CODE REVIEW

**Comment by RDS88-beeman** [comment]
god i fucking hope this works

**Comment by triplezeta** [comment]
add screenshot of sprites to pr please

**Review by triplezeta — CHANGES_REQUESTED** [review]
I think we could do better than a recolored poppy, however I have no issues with the concept of this PR (actually it's something i've wanted to do myself for quite some time)

**Comment by RDS88-beeman** [comment]
oh no we absolutely could but the rest of the flowers are also recoloured poppies, and could probably do with a resprite as a whole

**Comment by ZephyrTFA** [comment]
I'm like 80% certain there is a var you need to set for items to use when equipped. I could be, and usually am, incorrect however.

**Comment by RDS88-beeman** [comment]
i dont fucking know how this works but poppies just have this code and they work so

**Comment by triplezeta** [comment]
i was asked to open a new version of this PR

**Pull request closed without merging**
