### PR TITLE
(Hopefully) Final jungle ruin adjustments and remaps

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
What will hopefully be the end of my purging and cleaning up of the jungle ruin list. If you believe I may have missed a ruin or dislike a ruin not mentioned in this PR, feel free to bring it up in the comments.

Currently, this PR:
Remaps Jungle_Syndicate to be a little more expansive and loot filled. Main challenge is now four syndicate simplemobs and two turrets, with a c20r and two spare magazines as well as a syndicate hardsuit for the main loot of the base. Expanded to meet my 15x15 ruin standard.
Adds two claymores and a heroine bud to jungle_roomates. Someone complained about it lacking any loot, like the uneducated gamer they were, so I gave the lesbians swords.
Adds some junk to the coffins in surface_coffinpirate, like various bone items and a skeleton.
Adds boards for a DNA scanner and cloning console to go with the previously useless cloning machine (not sure why they would make that the item of value without the two other machines it needs to function but go off i guess) and places the alien organ in a freezer to prevent it from rotting before players can get to it. Also places some spider popsicles into said freezer as a fun treat for the players after the several dosages of spider poison.
Removes not one, but two immovable rods that were being used as supports for a bunk bed in the weed shack. Love the dedication to detail but immovable rods are not the way to do it.
Expands and improves the jungle wizard shack (AKA jungle_witch) to meet my 15x15 ruin standards and adds some finer touches. The main reward is now a wizard hardsuit, behind two dark wizard enemies (really not as threatening as they sound). 
Removes the impassable lattices from the hangar with the functioning ripley and also removes some pointless indestructible reinforced walls.
Adds a bit more various junk to surface_ninjashrine like rice, throwing stars and a lesser smoke spell named Ninja Vanish.
And finally, completely remaps and renames the Unabomber cabin to the Bombmaker's cabin. No more syndicate macrobomb, but you at least get some high-tech grenade equipment, research notes and corn for nitroglycerin.

## Why It's Good For The Game
Jungle ruins were a constant source of complaints, dissapointment, and general displeasure, to the point of spurring me into ruin maptaining out of sheer spite. With a few more adjustments and hopefully some new ruins submitted sooner or later, we can leave these maps alone and let the player be happy that the single currently entertaining thing to find on a jungleplanet wont just be monkeys sitting around a washing machine.

## Changelog
:cl:
add: Bombmaker's cabin, a far more tasteful remake of the unabomber cabin ruin
add: Two claymores and a heroine bud to jungle_roomates
add: Adds some extra loot to jungle_surface_ninjashrine like throwing stars and a lesser smoke spell
add: Adds some extra various junk to the coffins on jungle_surface_coffinpirate to make it a bit more worthwile compared to the other ruins.
add: Adds some extra loot to jungle_spider.dmm, mainly the DNA scanner and cloning console boards needed to make the cloning pod function and a toxins medkit
del: Unabomber cabin ruin
tweak: Remapped and expanded Jungle_witch.dmm, including now a wizard hardsuit as final loot
tweak: Remapped and expanded Jungle_syndicate.dmm, with final loot now being a c20r and syndicate hardsuit
fix: Removed the two immovable rods from jungle_surface_weed_shack.dmm
fix: Removed impassable lattices and pointless indestructible walls from jungle_hangar.dmm
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
another map fixed, the jungle hangar with the ripley in it had impassable and indestructible fake lattices as well as pointless indestructible rwalls

**Comment by Zevotech** [comment]
aaaaand now i remapped jungle_witch.dmm. help.

**Comment by Zevotech** [comment]
I Have Now Added Claymores To Jungle Roomates Lesbian Shack. The Lesbians Deserve Swords.

**Comment by tiramisuapimancer** [comment]
can we promote this user to project lead immediately

**Comment by Zevotech** [comment]
please just make me a maptainer so i can officially go fucking nuts on our ruin lists. also teach me more sdmm shortcuts cause i am currently a Fucking Ape Smashing The Mouse Buttons And Making It Work.

**Comment by tiramisuapimancer** [comment]
alt f4 makes the map for you

**Comment by Zevotech** [comment]
I Am Going To Explode.

**Comment by PiperDoots** [comment]
> please just make me a maptainer so i can officially go fucking nuts on our ruin lists. also teach me more sdmm shortcuts cause i am currently a Fucking Ape Smashing The Mouse Buttons And Making It Work.

ctrl +q closes SDMM and I keep hitting on accident!

**Comment by SweetBlueSylveon** [comment]
I'd like to see an update on this so we can get it reviewed properly, and testmerged.

**Comment by Latentish** [comment]
I am an uneducated gamer, and I think this should get TM'd.

**Comment by Latentish** [comment]
This was TM'd already, did any issues come up from it?

**Comment by Zevotech** [comment]
also i might not be done with this because there are still a lot of jungle maps that arent up to my standards. im looking at jungle syndicate warily and loading a glock. jungle village could use some touch ups. the coffin pirate map could do with a bit more greebling. jungle spider could use a bit of fun stuff and ninjashrine really dissapoints me in general.

**Comment by Zevotech** [comment]
okay, PR should be done and ready for merging.

**Review by Latentish — APPROVED** [review]
Approved for marg.

**Pull request merged**
