### PR TITLE
Ports MC initialization refactor

### PR DESCRIPTION
**Pull request by Vexylius**
## About The Pull Request
i've mindlessly slapped this https://github.com/tgstation/tgstation/pull/66473 on shiptest and it works lol

It makes master controller initialise in "stages" - early, main and max. If you want more details you can read the original PR or the code.

## Why It's Good For The Game
you can see some text faster so you dont get bored waiting 3 seconds for the game to start

## Changelog
:cl:
tweak: statpanel appears faster
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
This needs to be test merged to ensure stability

**Comment by Vexylius** [comment]
After reviewing my own PR I come to a conclusion that this PR is quite useless as the game loads before I even get to have a chance to rejoin after a restart, but I'm gonna keep it anyway.

**Review by ZephyrTFA — APPROVED** [review]
Didn't break shit

**Comment by Vexylius** [comment]
...yet ;)

**Comment by ZephyrTFA** [comment]
Still hasn't broken shit

**Pull request merged**
