### PR TITLE
TG style stasis beds

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

image

Adds stasis beds based on the TG ones

The TG ones are based on their surgery tables. Since we use goon surgery tables, the goon ones have been modified to match

## Why It's Good For The Game

resprites and 3/4

## Changelog
:cl:
imageadd: Stasis beds have been modified to match TG's
/:cl:

### CODE REVIEW

**Comment by swifterjack** [comment]
can they rotate

**Comment by ZephyrTFA** [comment]
> can they rotate

Nope, but neither could the old variants

**Comment by swifterjack** [comment]
Sad!
> > can they rotate
> 
> Nope, but neither could the old variants

**Comment by Kurgis** [comment]
> Sad!

That doesn't make sense, Human mobs don't rotate, so neither should the close-fitting structures.

**Comment by MarkSuckerberg** [comment]
@triplezeta

**Review by triplezeta — APPROVED** [review]
squid games:bangbang:

**Pull request merged**
