### PR TITLE
New Beach Ruin: Pirate Village

### PR DESCRIPTION
**Pull request by goober3**
## About The Pull Request

Adds a small outpost, formed from the remains of a wrecked shuttle. Occupied by three space pirates.

## Screemshot

image

crash1

crash2

## Loot!!!

-x1 Laser gun, x2 Energy cutlasses, from pirates. 
-x1 Scalpel, hemostat, cautery
-x1 Brute patch, x1 burn patch
-x1 Rare circuit board, x1 common circuit board
-A small amount of gold, silver and plasma
-x2 money bags, x3 gold coins

## Changelog

:cl:
add: The Pirate Village, a new beach ruin.
/:cl:

### CODE REVIEW

**Comment by goober3** [comment]
test.

**Comment by goober3** [comment]
> test.

so true!

**Review by ZephyrTFA — APPROVED** [review]

**Review by spockye — APPROVED** [review]
image
Grilles aren't powered, if you intended for them to be

Perhaps add some dust around the place?

other than that, it looks good!

**Review by Erikafox — APPROVED** [review]

**Comment by Erikafox** [comment]
unfuck your lints and it's ready for merge

**Comment by Erikafox** [comment]
fix your linters

**Comment by goober3** [comment]
maybe you should fix YOUR linters

**Pull request merged**
