### PR TITLE
Laser Misc Changes

### LINKED ISSUE #3790: [BUG]the NT-LS-1013 has no sprite
## Round ID: 
2867

## Testmerges:
[#3753: '[DNM] ports Bungalow-13#204 "You can stand in sofcrit, but not for long before colapsing if you take more damage" ' by rye-rice at commit a36a24f9b9](https://github.com/Shiptest-SS13/Shiptest/pull/3753)
[#3764: 'Auxmos update and potential fix (DO NOT MERGE)' by MarkSuckerberg at commit abb0e4e609](https://github.com/Shiptest-SS13/Shiptest/pull/3764)
[#3323: 'Remaps the Kansatsu-class Scout Courier.' by Sadhorizon at commit 69391c7f49](https://github.com/Shiptest-SS13/Shiptest/pull/3323)
[#3730: 'Gun Tweaks' by Erikafox at commit 967ca9f321](https://github.com/Shiptest-SS13/Shiptest/pull/3730)
[#3375: 'Moves the Brazillab ruin to Sandplanet and fixes the Trabuco's inhand sprites' by Zevotech at commit 34037fd165](https://github.com/Shiptest-SS13/Shiptest/pull/3375)
[#3512: 'Attempts to Fix Temperature + Makes It More Realistic in the Face of Extreme Temperatures' by rye-rice at commit 6b1056455e](https://github.com/Shiptest-SS13/Shiptest/pull/3512)
[#3694: 'Ammo Antics' by Erikafox at commit 5745544395](https://github.com/Shiptest-SS13/Shiptest/pull/3694)
[#3693: 'Replaces the Hyena with the Derecho' by Apogee-dev at commit 411423645f](https://github.com/Shiptest-SS13/Shiptest/pull/3693)
[#3711: 'Succumb Code Touchup' by MarkSuckerberg at commit d668253c64](https://github.com/Shiptest-SS13/Shiptest/pull/3711)
[#3519: 'Electric Welder & Cell Component' by thgvr at commit 58e05f3731](https://github.com/Shiptest-SS13/Shiptest/pull/3519)
[#3016: 'Tegu-class Communications Freighter' by goober3 at commit b808ed78b9](https://github.com/Shiptest-SS13/Shiptest/pull/3016)
[#3758: 'Factional Cargo, done in a day' by rye-rice at commit 7841d118ee](https://github.com/Shiptest-SS13/Shiptest/pull/3758)

## Reproduction:
Find an NT-LS-1013. 
It has no sprite.
Or inhand.

### PR DESCRIPTION
**Pull request by generalthrax**
## About The Pull Request

Makes ordinary lasers / eguns normal sized instead of bulky, and lets you add both them and weapon cells to holsters. Also fixes a singular weapon sprite on Singulo Lab.

Fixes https://github.com/shiptest-ss13/Shiptest/issues/3790

## Why It's Good For The Game

They look like they're handguns and they should fit in holsters too

## Changelog

:cl:
balance: Lasers / Eguns are now normal-sized
add: Lasers / Eguns now fit in holsters
fix: Sprite issue on Singulo Lab lasercannons

/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
yeahh to be honest

lasers are pretty bad at the moment so this seems fine in the meantime until someone rebalances them

**Comment by Martinpachu** [comment]
> yeahh to be honest
> 
> lasers are pretty bad at the moment so this seems fine in the meantime until someone rebalances them

sharplite rework

**Comment by generalthrax** [comment]
I'll do some other stuff like add them to holsters and stuff later

**Comment by SomeguyManperson** [comment]
Needs to account for laser variants that used to be bulky bc a normal sized hades sounds too funny

**Comment by Apogee-dev** [comment]
Make sure this doesnt affect previously bulky variants (e-shotgun, hades) or variants by other manufacturers like the eoehomas (which im pretty sure didnt get factionpathed, but if they did there’s certainly others that werent)

**Comment by generalthrax** [comment]
I probably should have mentioned I was planning on getting to that, I didn't finish the pr all the way as I was in round. I'll do that sometime this weekend along with some other convenience things like aforementioned holsters.

**Pull request merged**
