### PR TITLE
Updates and slightly changes the Bubble

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request

This pull request slightly changes the bubble to make it "work" better
changes:
adds a microwave, and two boxes of donk pockets
changes the oxygen tank holder to contain plasma as well (for the poor poor plasmamen)
changes the EVA type to NT mining from independent mining(which seems to be broken)
makes the bridge shutters work, and gives it a button (you can now close them. amazing!)
gives the thrusters blast doors
fixes the airlock (for whatever reason it currently goes into the wall, and uses two-layer adaptors)
adds a medical aid kit 
adds a locker for sci storage
gives the captain a locker, with clothing and a commander pistol. 
adds an external toilet and shower (i need not explain myself)
rotates misplaced wall-mounts
gives the airlocks correct names

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
the current bubble is a tad out-dated and is missing some pretty important stuff. 

## Changelog

:cl:
tweak: tweaked and changed some things on the bubble class
/:cl:

### CODE REVIEW

**Comment by Valorium-RB** [comment]
Where is the toilet (as in, if we're updating it, we may as well add the maptainer-mandated restroom).

**Comment by spockye** [comment]
image

image

**Comment by Zevotech** [comment]
janky toilet perspective makes this look like the toilet is mounted on the outside wall like some kind of hunting trophy. or youre meant to use it in zero g in the vacuum of space.

**Comment by TallDeekus** [comment]
> janky toilet perspective makes this look like the toilet is mounted on the outside wall like some kind of hunting trophy. or youre meant to use it in zero g in the vacuum of space.

You are saying that like that is a problem.

**Comment by Zevotech** [comment]
> > janky toilet perspective makes this look like the toilet is mounted on the outside wall like some kind of hunting trophy. or youre meant to use it in zero g in the vacuum of space.
> 
> You are saying that like that is a problem.

ULTIMATE MANUVER, **HYPERSPACE SHITTING!**

**Comment by Latentish** [comment]
The space toilet is funny. Please give the ship a proper restroom.

**Comment by unit0016** [comment]
Hi there,
As the original designer of the Bubble, ~~and despite the fact I haven't touched shiptest in over a year~~ - I'd like to state that I purposefully avoided adding blast doors because they're (when I was around, at least) impossible to construct/deconstruct as a player, thus making the ship less malleable. (Is ship expansion still a thing, anyways?)

It partly saddens me that it's getting creature comforts, too, considering the mindset I made it with. Mayhaps I should rejoin just to observe the mechanics that've come to be and try to recapture the magic of working with less than the bare essentials for a godly payout.

Also, wait, is that plush supposed to be my static?

Good work regardless of my melancholic feelings though, love the mobile shitter.

**Review by Latentish — CHANGES_REQUESTED** [review]
The space toilet is funny. Please give the ship a proper restroom.

**Pull request closed without merging**
