### PR TITLE
Ray cats!

### PR DESCRIPTION
**Pull request by FalloutFalcon**
## About The Pull Request
Cats now act like fuzzy Geiger counters!

https://github.com/user-attachments/assets/77a0cdbf-51e9-420d-afad-998e46b69343

## Why It's Good For The Game
Imagine your own deep lore regarding the NOF here
image

## Changelog

:cl:
add: Cats have been genetically engineered to detect radiation
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
wat

**Comment by Erikafox** [comment]
I think this'd be better as a type of cat rather than all cats.

**Comment by FalloutFalcon** [comment]
> I think this'd be better as a type of cat rather than all cats.

no its all cats.

**Comment by AverageUser67** [comment]
Yeah, I expected purple cat-subtypes and not EVERY cat

**Comment by FalloutFalcon** [comment]
> Yeah, I expected purple cat-subtypes and not EVERY cat

every cat.

**Review by rye-rice — APPROVED** [review]
fucking peak pr

**Pull request merged**
