### PR TITLE
capsaicin no longer straight up kills you

### PR DESCRIPTION
**Pull request by generalthrax**
## About The Pull Request

removes the body temperature increase from capsaicin

## Why It's Good For The Game

>eats two chili peppers
>starts running a fever 30C over the boiling point of water

nacho

## Changelog

:cl:
del: Capsaicin no longer Boils you
/:cl:

### CODE REVIEW

**Comment by FalloutFalcon** [comment]
just give it the coffee heat amount.. that one seems fine
```
/datum/reagent/consumable/coffee/on_mob_life(mob/living/carbon/M)
	M.dizziness = max(0,M.dizziness-5)
	M.drowsyness = max(0,M.drowsyness-3)
	M.AdjustSleeping(-40)
	//310.15 is the normal bodytemp.
	M.adjust_bodytemperature(25 * TEMPERATURE_DAMAGE_COEFFICIENT, 0, M.get_body_temp_normal())
	if(holder.has_reagent(/datum/reagent/consumable/frostoil))
		holder.remove_reagent(/datum/reagent/consumable/frostoil, 5)
	..()
	. = 1
```

**Comment by generalthrax** [comment]
> just give it the coffee heat amount.. that one seems fine
> 
> ```
> /datum/reagent/consumable/coffee/on_mob_life(mob/living/carbon/M)
> 	M.dizziness = max(0,M.dizziness-5)
> 	M.drowsyness = max(0,M.drowsyness-3)
> 	M.AdjustSleeping(-40)
> 	//310.15 is the normal bodytemp.
> 	M.adjust_bodytemperature(25 * TEMPERATURE_DAMAGE_COEFFICIENT, 0, M.get_body_temp_normal())
> 	if(holder.has_reagent(/datum/reagent/consumable/frostoil))
> 		holder.remove_reagent(/datum/reagent/consumable/frostoil, 5)
> 	..()
> 	. = 1
> ```

This doesn't really do much besides heat you up when you're already cold. Which spicy food doesn't even do. I just didn't like the implication that it is physically heating up your body when that just isn't the case.

**Comment by Latentish** [comment]
https://youtube.com/clip/Ugkxvp-LgV271a8aplEk0ZzbQu2A4aMDuiJP?si=Fgq63JkcTvJA0uty

**Comment by Imaginos16** [comment]
LGTM

**Pull request merged**
