### PR TITLE
Enigma-class Plasma Locomotive

### PR DESCRIPTION
**Pull request by ForestCranked**
## About The Pull Request

Adds a remade version of the Enigma-Class, now a plasma-based locomotive!

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

I just think a train would be cool.

## Changelog

:cl:
add: A new indy ship. (sorry if the indy ban is still up)
/:cl:

### CODE REVIEW

**Comment by conk444** [comment]
Does it go choo choo

**Comment by ForestCranked** [comment]
> Does it go choo choo

i wish i could make it go choo choo mate

**Comment by Sun-Soaked** [comment]
just scream train noises while you're moving

**Comment by ForestCranked** [comment]
> just scream train noises while you're moving

this tbh

**Comment by Latentish** [comment]
This is what I see when I look at this.
image
A lot of very simple squares that are misalligned in a row. I also did tell you that this was something another person had been doing in the past. You could probably dig up that old pr and ask the creator for permission to finish it if you'd like. But last I recalled they planned to do so when they were less flooded by school.

This is not air tight.
image
image

Why is the shower curtain around the toilet? And why is the shower embedded into the wall like this?
image

We're not big fans of tegs here on the maptainer team. You need a good reason to have one pre set up even remotely well prior. This isn't really a tanker, and "Plasma locomotive" doesn't really mean much? What are they doing with this nigh unlimited power, there's very little machinery on this ship to begin with. Also why in gods name did you put plastic flaps as the seal to the burn chamber, for what purpose does this person need to laydown and crawl into a teg burn chamber through a material that should very well melt the moment its started.
image

**Comment by Latentish** [comment]
https://github.com/shiptest-ss13/Shiptest/pull/1153

**Comment by ForestCranked** [comment]
> This is what I see when I look at this. image A lot of very simple squares that are misalligned in a row. I also did tell you that this was something another person had been doing in the past. You could probably dig up that old pr and ask the creator for permission to finish it if you'd like. But last I recalled they planned to do so when they were less flooded by school.
> 
> This is not air tight. image image
> 
> Why is the shower curtain around the toilet? And why is the shower embedded into the wall like this? image
> 
> We're not big fans of tegs here on the maptainer team. You need a good reason to have one pre set up even remotely well prior. This isn't really a tanker, and "Plasma locomotive" doesn't really mean much? What are they doing with this nigh unlimited power, there's very little machinery on this ship to begin with. Also why in gods name did you put plastic flaps as the seal to the burn chamber, for what purpose does this person need to laydown and crawl into a teg burn chamber through a material that should very well melt the moment its started. image

The windows are actually airtight (confirmed while i was testing out the TEG), If i remember correctly, someone told me that holofans would be eventually removed, you are overestimating the TEG, and how could i add more machinery and make this more train-like

**Comment by Latentish** [comment]
I'm not overestimating the TEG. Our most power heavy ship runs at about .7MW. The TEG due to being suited to a station was nerfed simply by capping its power to 2MW. 2MW is more than twice as heavy a supply as our most hungry boats, and 2MW is extremely easy to get. The TEG in general needs to be readjusted.  Moreover it _is_ basically free unlimited energy that almost no ship can actually make use of.

At this point I'm not sure what to say. The point of these PR's is for you to be able to give us as code and map maintainers something that you think is worth getting added.. If you need advice _fixing_ something check or codewise, that's one thing to ask for advice in on your pr. But even still, it's ill advised to ask for advise on how to make a _good_ ship in your PR. In the end what you put up in the PR is your attempt to convince us. Ask for help in the discord if you need it.

I generally don't think this ship meets up to standards. Apologies. Again I suggest you look at the other PR I linked and maybe even contact them.

**Comment by Latentish** [comment]
I apologize but this is simply too flawed in its current state. I'll be closing this PR.
I very heavily recommend you get a ruin in before continuing to work on ships.

**Pull request closed without merging**
