### PR TITLE
FOXALIVE - Disables Nanites

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

Removes nanite research from the tech web pending a more extensive rework. Does not touch any pre-placed nanite equipment or disks in ruins and on ships.

## Why It's Good For The Game

nanites are kind of a nightmare for balance, frankly. While they offer some great potential, a lot of the more Gamerly programs need to be reworked or axed and that will take time to do.

## Changelog

:cl:
del: Disabled research nodes for nanites
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
1, WOO YEAH NANITES ARE GONE
2, I think theres more than just the three nanite techs? but it probably doesn't matter too much as I think you need the three removed to even get them

**Comment by Apogee-dev** [comment]
> 1, WOO YEAH NANITES ARE GONE 2, I think theres more than just the three nanite techs? but it probably doesn't matter too much as I think you need the three removed to even get them

I commented out the entire nanite block in the techweb file. If there's more techs somebody hid them somewhere and that's terrible practice.

**Comment by TheNeoGamer42** [comment]
ok no actually github was fooling me 10 different nanite techs seems about right and when I was looking at the changed files it only showed three despite me trying to click to reveal more of the changes??? either way death of nanites

**Comment by Arturlang** [comment]
Why is your PR title completely unrelated? It should be obvious so people can see how important this change is and about what it is, hiding controversial changes is no good.

**Comment by Apogee-dev** [comment]
> Why is your PR title completely unrelated? It should be obvious so people can see how important this change is and about what it is, hiding controversial changes is no good.

It's not actually completely unrelated, but you're right, it isn't completely transparent either.

**Pull request merged**
