### PR TITLE
Ports changes from modern TG Hydro

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Draft for a port of some changes from modern TG hydroponics. 
1. Ports modular hydro chemistry
2. Ports instability
3. Ports random chem/trait adding for seeds with high instability
I need to check Shiptest's design docs to see if I can do this, but this isn't a big change. Maybe around 300 lines of code in total. 

## Why It's Good For The Game
Makes it easier for players to get access to xenobio, and so on. Some players exclusively play hydro on TG. So, I would imagine that it'd give people something to do.

## Changelog
:cl:
add: Ports changes from modern TG hydroponics
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
This would also remove a bad word

**Comment by rye-rice** [comment]
see https://github.com/shiptest-ss13/Shiptest/pull/918, i havent worked on it recently though

**Comment by ghost** [comment]
> see #918, i havent worked on it recently though

Didn't notice. Not sure how to say this in a non-rude way, but it'd be cool to see it get finished. My byond username is CocaColaTastesBetterWithMyName if you need any low iq code-monkey work done on it.

**Comment by rye-rice** [comment]
oh no, its alright, you can make a fork of my branch and finish it from there

**Pull request closed without merging**
