### PR TITLE
Poster Printer

### PR DESCRIPTION
**Pull request by VernaSaurus**
## About The Pull Request

Adds poster printers. Currently unmapped, so there's no way to get them at the moment, and I recommend one gets added to the outpost.
HOW TO USE:
get a sheet of paper and a printer
image
put the paper in the printer
image
click on the printer and select the kind of poster you want to print
image
print the poster, and then remove it
image
tada! free* poster!
image

*actually uses some toner with each use, as well as a sheet of paper

## Why It's Good For The Game

A lot of people were complaining about how there's no easy way to get posters at the moment, so I made a convenient printing device.

## Changelog

🆑
add: Added a poster printer. Please map this later, I didn't want to mess with mapping for now so
/🆑

### CODE REVIEW

**Comment by meemofcourse** [comment]
you might want to remove the ability to create posters out of thin air on the library computer

**Comment by VernaSaurus** [comment]
> you might want to remove the ability to create posters out of thin air on the library computer

YOU CAN DO THAT???????

**Comment by VernaSaurus** [comment]
god fucking damn it
image

**Review by MarkSuckerberg — APPROVED** [review]
looks good looks good, let's get it testmerged

**Review by rye-rice — APPROVED** [review]
printer sprite is alright? wish it was more distinct from the fax machine though

**Pull request merged**
