### PR TITLE
Spooky Sprites batch 2

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
New coat of paint for some various items from Spooky and Imaginos
New janitorial stuff from Myself

## Small previews
image
image
image

## Changelog

:cl: Spookypineapple, Imaginos, Thgvr
add: New sofa and comfy chair variants, both are craftable with metal
imageadd: Sofas, Comfy chairs, and some atmos equipment have a new coat of paint
imageadd: Janitorial equipment has a new coat of paint
/:cl:

### CODE REVIEW

**Comment by goober3** [comment]
AAAAHH!!!!

**Comment by thgvr** [comment]
👻

**Review by Imaginos16 — APPROVED** [review]
I would eat them

**Comment by Martinpachu** [comment]
wtf you can't eat ouches

**Comment by tiramisuapimancer** [comment]
Can you make the couches edible?

**Pull request closed without merging**
