### PR TITLE
Removes mutation chemicals

### PR DESCRIPTION
**Pull request by Sylphily**
## About The Pull Request
makes most mutation chemicals unable to be gotten by players, still able to be used by abus for admin tho!

## Why It's Good For The Game
magic LRP chems bad, oh and 
image

## Changelog

:cl:
del: Removed the recipes for the race changes, some stuff still obtainable from xeno
/:cl:

### CODE REVIEW

**Comment by Sylphily** [comment]
-69 lines removed, nice

**Comment by Ketrai** [comment]
Arent most of these restricted by needing green and black slimes?

Either way not a fan. It's always nice to see a weird species amongst the crew for a change. Or when people feel like making something odd like a full kobold crew withour admin aid. 

Them being just chems that do it instantly is somewhat silly yes. But if it's not getting replaced in some way this feels like a loss for player autonomy.

**Comment by Sylphily** [comment]
> Arent most of these restricted by needing green and black slimes?
> 
> Either way not a fan. It's always nice to see a weird species amongst the crew for a change. Or when people feel like making something odd like a full kobold crew withour admin aid.
> 
> Them being just chems that do it instantly is somewhat silly yes. But if it's not getting replaced in some way this feels like a loss for player autonomy.

it was removed because its makes being a species weigh less, and because its the kinda bullshit magic that makes no logic to keep around.

**Comment by Ketrai** [comment]
Eh. Could always make the transformation take longer. Feel more like an impactful experience. In terms of scifi mutations and alterations are a pretty fun trope for storytelling and such as it generally alters the way a character experiences their body and the world around them gradually. Make Kafka proud!

**Comment by Sylphily** [comment]
still able to be used for admin stuff, but in general it just does not fit with the vibe and get abused a lot

**Comment by triplezeta** [comment]
thsi isnt relevant but mutation chems are actually supposed to have a delay, the code just doesnt work bc ?? i fucked up the port i think

**Comment by PiperDoots** [comment]
Still doesn't fix the core of the issue though I think.

**Comment by Sun-Soaked** [comment]
I feel like we'd be better suited to convert existing mutation toxins into transformation disease granters- this would make their affects more in-sync with an RP environment, and make them extremely counterable via. disease cures as opposed to 
plasmaman mutation syringe(piercing) 
kind of events

**Comment by Zevotech** [comment]
> I feel like we'd be better suited to convert existing mutation toxins into transformation disease granters

this is good, it lines up with the roburger as well. Preventable and also makes a lot more sense than instantly popping into a different species.

Also, xenobio just sucks. So many cool effects and items that SHOULD be available as rewards or ruin loot, but are instead locked behind a time consuming, RNG slime farming simulator that is mind numbingly boring.

**Comment by tiramisuapimancer** [comment]
if there isn't an IC way to convey that mutation toxins are temporary then they're just a lore issue straight up

**Comment by Ketrai** [comment]
> Also, xenobio just sucks. So many cool effects and items that SHOULD be available as rewards or ruin loot, but are instead locked behind a time consuming, RNG slime farming simulator that is mind numbingly boring.

I'm hoping to fix xenobio once I get a good bit of freetime to work on it. Make it accesible more easily and a good deal less boring. As well as needing more outside factors for progression.

**Comment by TallDeekus** [comment]
> if there isn't an IC way to convey that mutation toxins are temporary then they're just a lore issue straight up

Here is an idea, make an annoying text or moodlet pop up sometimes that so signs it is temporary, such as:

> "Your scales feel flaky."

> "You feel uncomfortable all over."

> "Your muscles twitch."

> "Your lights flicker ominously."

> "Your feathers feel loose."

**Comment by TallDeekus** [comment]
> > if there isn't an IC way to convey that mutation toxins are temporary then they're just a lore issue straight up
> 
> Here is an idea, make an annoying text or moodlet pop up sometimes that so signs it is temporary, such as:
> 
> > "Your scales feel flaky."
> 
> > "You feel uncomfortable all over."
> 
> > "Your muscles twitch."
> 
> > "Your lights flicker ominously."
> 
> > "Your feathers feel loose."

Have said effects be easily silenced by coffee or actual medicine, or just good eating.

They exist as a reminder, nothing more.

**Comment by TallDeekus** [comment]
Just realized all the symptoms I typed out are the same as Shiptest Withdrawal... Wack.

**Pull request merged**
