### PR TITLE
Adds color to VV

### PR DESCRIPTION
**Pull request by cuddleandtea**
## About The Pull Request
Hello dear comrades! I represent to you a more convenient way to change color of anything through View Variables.  

## Why It's Good For The Game
Before you was forced to search or remember colors code to apply it to light or obj color. And now it's more easy to use. Just like in character creation. 
1. Select VV of anything and go to color
image
2. Press C to change type of var
image
3. Select color
image
4. Apply changes and be happy
image

## Changelog

:cl:
admin: adds color type to variables
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
Seems fine

**Comment by cuddleandtea** [comment]
This is the _HELPERS/unsorted.dm 
```
1125:  //gives us the stack trace from CRASH() without ending the current proc.
1126: /proc/stack_trace(msg)
1127:	CRASH(msg)
```
I should do something to fix this error, right? Never had this issue before @thgvr

**Comment by cuddleandtea** [comment]
@thgvr I can try to fix this but it will look ugly

**Comment by thgvr** [comment]
> @thgvr I can try to fix this but it will look ugly

If you're worried about the CI/merge failure it's not your fault.

**Comment by thgvr** [comment]
> This is the _HELPERS/unsorted.dm
> 
> ```
> 1125:  //gives us the stack trace from CRASH() without ending the current proc.
> 1126: /proc/stack_trace(msg)
> 1127:	CRASH(msg)
> ```
> 
> I should do something to fix this error, right? Never had this issue before @thgvr

This means there is a runtime, and this error itself isn't helpful

**Comment by cuddleandtea** [comment]
@thgvr oh...so I shouldn't do any fixes from my side?

**Comment by thgvr** [comment]
Yep, don't worry about it

**Comment by cuddleandtea** [comment]
> Yep, don't worry about it

Thanks! Than I should revert 2 new commits

**Comment by cuddleandtea** [comment]
@thgvr Done. And I squashed all in just one commit so there is no confusion

**Comment by thgvr** [comment]
No need to worry about squashing here it's done on merge, but sure

**Pull request merged**
