### PR TITLE
unfunny drinks adjustment update.

### PR DESCRIPTION
**Pull request by axelzonvolt**
## About The Pull Request
Taking an axe to planetcracker and adjusting lizard wine to improve palpability and retain the neat sprite. (you need a cactus flower now instead of a tail)

## Why It's Good For The Game
less "hahaha racism", more potential space for "DEAR GOD WHY"

## Changelog

:cl:

del: planet cracker begone!
tweak: lizard wine is now kalixcis wine and requires cactus fruit to make.

/:cl:

### CODE REVIEW

**Comment by AverageUser67** [comment]
should have made planet cracker a dead space reference

**Comment by axelzonvolt** [comment]
if you want it so bad, adjust it to remove dependency on lizard wine and give it a recipe.

**Comment by AverageUser67** [comment]
holy fuck it was just a comment
search up planet cracker
i think the desc could be retooled

**Comment by AverageUser67** [comment]
this is the first time I've disagreed with a PR, but that's besides the point

**Pull request merged**
