### PR TITLE
Lizard stretcher

### PR DESCRIPTION
**Pull request by VernaSaurus**
## About The Pull Request

adds the fucking. lizard stretcher
video proof: https://github.com/shiptest-ss13/Shiptest/assets/64121399/151bc57d-5fdf-4192-a8f7-154b1796470e

## Why It's Good For The Game

see the changelog

## Changelog

:cl:
add:lizstretch
/:cl:

### CODE REVIEW

**Comment by GenericDM** [comment]
I dislike this for a number of reasons.

1. it makes me uncomfortable
2. it makes me uncomfortable
3. it makes me uncomfortable
4. it serves no gameplay purpose other than shitposting
5. it makes me uncomfortable
6. adminspawn only
7. it makes me uncomfortable

**Comment by VernaSaurus** [comment]
> I dislike this for a number of reasons.
> 
>     1. it makes me uncomfortable
> 
>     2. it makes me uncomfortable
> 
>     3. it makes me uncomfortable
> 
>     4. it serves no gameplay purpose other than shitposting
> 
>     5. it makes me uncomfortable
> 
>     6. adminspawn only
> 
>     7. it makes me uncomfortable

understandable, I highly doubt this is going to be added anyway and I only made it for the meme

**Review by meemofcourse — APPROVED** [review]

**Comment by VernaSaurus** [comment]
if three people tell me to delete this I will, the last thing I want to do is make people really uncomfortable

**Comment by ritorizo** [comment]
I like that we keep stretching that joke

**Comment by thgvr** [comment]
pretty funny

**Comment by Sun-Soaked** [comment]
I have got to get longer

**Comment by thgvr** [comment]
Ultimately I don't think an admin only item for a joke really has a place. It's funny, but out of place.

**Pull request closed without merging**
