### PR TITLE
standardizes map naming syntaxes and fixes non-matching ship names

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
reorganizes the map files and sorts them based on their displayed class name and their appropriate faction

also need to PR to force checks to run :+)
- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

cleaning up
helps people going forward to find specific maps easier
fixes some naming errors, like the bubble being an ntsv

## Changelog

:cl:
fix: map file names now include the ship class and the faction; related configuration files have names to match their associated mapfiles for ease of use
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
going to re-pr

**Comment by Zevotech** [comment]
seems to be failing on the bulletproof armor on the twinkleshine of all things, which is weird. Removing the offending items may fix it.

**Comment by ghost** [comment]
> seems to be failing on the bulletproof armor on the twinkleshine of all things, which is weird. Removing the offending items may fix it.

yea, i think the object path must've changed?

**Comment by MarkSuckerberg** [comment]
Been waiting for this for a long time, thank youuuu

**Pull request merged**
