### PR TITLE
Arrowhead-Class Long Range Scout Ship

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request
Adds in the newest version of a ship I made quite some time ago.
arrowheadshiptested

## Why It's Good For The Game
Alot of people asked for it to be here too, so here's the PR.
## Changelog
:cl:
add: the Arrowhead-Class Long Range Scout Ship
/:cl:

### CODE REVIEW

**Comment by TypeVar** [comment]
I've always wanted to see this ship merged but it was marked as stale the last time for some reason :(
How does the RTG work btw?

**Comment by TheNeoGamer42** [comment]
> I've always wanted to see this ship merged but it was marked as stale the last time for some reason :( How does the RTG work btw?

It went stale because there for awhile it still had the autopilot console, since it was made shortly before the overmap rework that removed them. RTGs work by simply sitting there providing a little bit of power. Also, something I've noticed in testing is that we also increaseed the power draw of the helm by a fucking metric ton (seriously why does the bridge pull like 10kW still with all other consoles dismantled) resulting in you needing to turn it off on the APC unless you feel like draining your batteries. I think it still creates for some nice gameplay on power management that's not really available on shiptest otherwise

**Comment by Apogee-dev** [comment]
> RTGs work by simply sitting there providing a little bit of power. Also, something I've noticed in testing is that we also increaseed the power draw of the helm by a fucking metric ton (seriously why does the bridge pull like 10kW still with all other consoles dismantled) resulting in you needing to turn it off on the APC unless you feel like draining your batteries. I think it still creates for some nice gameplay on power management that's not really available on shiptest otherwise

the problem with turning the helm console off on the APC is you also disable the wideband and holopad in the process, cutting off all your communication with the rest of the sector.

Other than that, this ship would really benefit from standard intercoms so crew members can communicate when aboard the ship without carrying an SBR everywhere (some jobs don't even spawn with an SBR anyway, such as secoff), and you need to update the dirs on several wall-mounted objects, some of which didn't have dir states when this map was initially created or just had bad ones. This includes shutter buttons, fire alarms, intercoms, and light switches.

**Comment by Apogee-dev** [comment]
Could you make sure the window and engine shutters start out closed? Players frequently forget shutters even exist and get goliath.com'd the instant they land. If the shutters are closed by default we can at least call it a skill issue.

**Comment by TheNeoGamer42** [comment]
> > RTGs work by simply sitting there providing a little bit of power. Also, something I've noticed in testing is that we also increaseed the power draw of the helm by a fucking metric ton (seriously why does the bridge pull like 10kW still with all other consoles dismantled) resulting in you needing to turn it off on the APC unless you feel like draining your batteries. I think it still creates for some nice gameplay on power management that's not really available on shiptest otherwise
> 
> the problem with turning the helm console off on the APC is you also disable the wideband and holopad in the process, cutting off all your communication with the rest of the sector.
> 
> Other than that, this ship would really benefit from standard intercoms so crew members can communicate when aboard the ship without carrying an SBR everywhere (some jobs don't even spawn with an SBR anyway, such as secoff), and you need to update the dirs on several wall-mounted objects, some of which didn't have dir states when this map was initially created or just had bad ones. This includes shutter buttons, fire alarms, intercoms, and light switches.

The power issue with needing to shut off the helm isn't much of an issue anymore since I PRed a fix for it that's merged, as for SBRs, there's an autolathe capable of printing them supplied with materials to do so. As for the wall mount orientation, I'm not really sure how tod that and this map was made well before people tried to standardize that in any way. As for the window and engine shutters, well, skill issue. Also you kinda need the engine shutters open to setup the ion thrusters, and if you can't see that your WINDOW shutters are open, you are uh... Very blind, and there's an easy button on the bridge to close them. I could do the wall mounts if you told me the "standard" or generally accepted way to do them now is.

**Comment by Apogee-dev** [comment]
> The power issue with needing to shut off the helm isn't much of an issue anymore since I PRed a fix for it that's merged, as for SBRs, there's an autolathe capable of printing them supplied with materials to do so. As for the wall mount orientation, I'm not really sure how tod that and this map was made well before people tried to standardize that in any way. As for the window and engine shutters, well, skill issue. Also you kinda need the engine shutters open to setup the ion thrusters, and if you can't see that your WINDOW shutters are open, you are uh... Very blind, and there's an easy button on the bridge to close them. I could do the wall mounts if you told me the "standard" or generally accepted way to do them now is.

Players tend to miss the existence of the window shutter button very frequently (especially since there’s still a few ships that don’t even have one) and engine shutters typically just have a button in the engine bay to open them on ships that have those. Making players interact with them to finish setup is a good way of forcing newcomers to familiarize themselves with important elements of the ship and can make part of a nice roundstart routine for more experienced players.

I’m well aware that you can just print SBRs, but the point of having intercoms is so players can at least communicate a little if they lose theirs or spawn without one and haven’t been able to print one yet for whatever reason. Not strictly necessary but highly convenient and found on most ships at this point.

Wallmount directions are set the exact same way you’d set the direction of any other item that has directional sprites. SDMM should show a slider when you select the item that lets you adust it. Which direction is which should be pretty self-explanatory since they’re labeled in the UI. If things are still unclear you could open up a more recent map in sdmm to see how it was done there.

**Comment by Latentish** [comment]
I like this ship . But have you put any thought into what this ship will do with all that ore once they mine it?

**Comment by PrefabQuasar** [comment]
i like the aesthetic of this ship, really captures the submarine vibes, picture does show the light switches and fire alarms and buttons all at their default rotations, they should be rotated to fit the walls, if you've already addressed that, ignore this

**Comment by Latentish** [comment]
Could we please get a response from the author on this one to the last few comments?

**Comment by TheNeoGamer42** [comment]
I don't really have the time to actually update this for now. I'll reopen it later, or something.

**Pull request closed without merging**
