### PR TITLE
2 new ruins for whitesands made mainly by Erin

### PR DESCRIPTION
**Pull request by TheNeoGamer42**
## About The Pull Request
adds more ruin to whotesands planets
## Why It's Good For The Game
more ruin is good right
## Changelog 
:cl: erin, neo, retlaw
add: crashed syndicate assault pod ruin on whitesand planets
add: abandoned convenience store conveniently on whitesand planets
/:cl:

### CODE REVIEW

**Comment by TheNeoGamer42** [comment]
feature

**Comment by TheNeoGamer42** [comment]
sus

**Comment by rye-rice** [comment]
amog

**Comment by TheNeoGamer42** [comment]
there may or may not be a amoug on here now

**Pull request merged**
