### PR TITLE
Vela Industrial Cruiser

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request

The Vela-class is a large industrial cruiser based off a semi modular hull design, originally designed for mining out asteroid belts with an entourage of mechs, it is now seeing action in the frontier, extracting resources from any planetoid that crosses its way. This specific model also includes a science lab, for extracting information from any curiousities the Vela may encounter along the way.

## Why It's Good For The Game
GOLD Faction presence

## Changelog

:cl:
add: Vela-Class Industrial Cruiser, a large CMM Ship built around mechs and mining
/:cl:

### CODE REVIEW

**Comment by meemofcourse** [comment]
there it is! there it is!

**Comment by PrefabQuasar** [comment]
when you get a moment, which boards does the science setup have?

**Comment by Erikafox** [comment]
1x rd server
1x rd console
1x sci protolathe
1x sci circuit imprinter

**Comment by PrefabQuasar** [comment]
to be honest, that. kind of feels like a lot, for a ship thats already so well equipped

**Comment by Erikafox** [comment]
The previous iteration didn't have the equipment, and it kinda ran like ass. I think it's mildly balanced out by the fact that it's a huge ship. You don't see people picking the osprey for the protolathe, for example.

**Comment by PrefabQuasar** [comment]
i suppose, i'll have to take a look at it in action tomorrow though

**Review by Latentish — DISMISSED** [review]
I'm fairly certain we agreed that we wanted to phase out rnd. I don't like that you're adding rnd to a new ship. If they need to be able to research new mech parts, you should make a mech node instead. But I definitely do not want to see an RD proto and circuit printer on a new ship.

**Comment by Erikafox** [comment]
We're removing R&D on ships that don't need it.
This is a ship where it is needed and relevant.

**Comment by Latentish** [comment]
> We're removing R&D on ships that don't need it. This is a ship where it is needed and relevant.

RnD is something that has been on the chopping block for ages. We have been trying to phase it off of ships entirely. If you really need it, please make or use a mech node.

**Review by Apogee-dev — APPROVED** [review]
I see no issues with the science setup. If it proves to be a problem in the future we can always fix it then.

**Pull request merged**
