### PR TITLE
Adds asteroid siding, whitesands siding, rock siding and Corners your weather sprites

### PR DESCRIPTION
**Pull request by goober3**
## SCREENSHOTS

sprites

whitesands

rocksidingnew
wow! those sure are Adds asteroid siding, whitesands siding, rock siding and Corners your weather sprites

image
image
in-game demonstrations. of the Sidings. It is worth noting that space Deletes all decals, the asteroid sidings, unfortunately, cannot be placed on space!

image

image

Existing maps now possess the Corner. Beach maps have been updated with the /asteroid version of sand.

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

All siding and no corner makes decals.dmi a dull sprite

## Changelog

:cl:
add: Asteroid Siding, for asteroids!
add: Salted Sand Siding
add: Iron Sand Siding
add: Weather sidings have corners now
tweak: Updated existing maps to feature weather corner sprites
tweak: Beach ruins now use the /asteroid variant of sand
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
The beach tiles used in the ruins are wrong btw. The ones that should be getting used are the asteroid versions actually used for the beach planet. I'd ask you base them off those rather than the buggy biodome beach tiles.

**Comment by goober3** [comment]
> The beach tiles used in the ruins are wrong btw. The ones that should be getting used are the asteroid versions actually used for the beach planet. I'd ask you base them off those rather than the buggy biodome beach tiles.

Done!!!!!!!!!!!!! should I fix the sand tiles for the rest of the beach ruins, too?

**Comment by Latentish** [comment]
That'd be pretty rad honestly.

**Comment by goober3** [comment]
totally forgot to Mention this Yesterday! this PR now includes Whitesands Siding, too.

**Comment by goober3** [comment]
added Iron Sand siding. would appreciate it if this PR could get a Review and / or a Test Merge and / or a Full Merge Thank You Very Much!

**Review by ZephyrTFA — APPROVED** [review]

**Comment by Erikafox** [comment]
I haven't been touching this because it's a bunch of sprites but if no one weighs in on them I'm just gonna tm it on friday.

**Review by Erikafox — APPROVED** [review]

**Pull request merged**
