### PR TITLE
Tweaks vox tail directional sprites

### PR DESCRIPTION
**Pull request by kestoloppu**
## About The Pull Request
Swaps all current vox sprites to have the tail on the right side when facing south. (original sprites by drawsstuff)
This PR also includes vox sprites for the Swat MkII hardsuit and helmet (left tail version will be included if this is closed)
This PR also corrects the coloring for the Orange Syndicate Spacesuit vox sprite (left tail version will be included if this is closed). (original sprites by drawsstuff)

Old:
old vox
Proposed:
killer suits
killer suit no helmet
orange
orange no helmet

flip

This may conflict with #1086 since both change vox_quills.dmi
This may conflict with #1087 since both change vox.dmi
## Why It's Good For The Game
The gyroscopically stabilized tail is a little disorienting. Now you can tell what direction the sprite is facing at a glance and changing directions looks more natural.
old
right

## Changelog
:cl:
add: Added vox sprites for the MK.II SWAT hardsuit and helmet.
tweak: Vox tails are now on opposite sides for north/south directional sprites.
fix: The vox sprite for the orange syndicate spacesuit is now orange instead of black.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
going to mark this as DNM while vox aesthetics are discussed with the spritetainer team (by which i mean any% and tira. hi you two!)

**Comment by zestybastard** [comment]
Making this PR seems a little irresponsible if you don't have the resprites for affected items (most Vox clothing) ready. I'd like for you to change affected sprites first so we know that this won't be half-baked.

**Comment by zestybastard** [comment]
> Making this PR seems a little irresponsible if you don't have the resprites for affected items (most Vox clothing) ready. I'd like for you to change affected sprites first so we know that this won't be half-baked.

For the record, this sprite is also multi-server meaning you'd probably want to redo a lot of things like blood overlays and server-by-server items to keep it all consistent with the original project.

**Comment by kestoloppu** [comment]
> Making this PR seems a little irresponsible if you don't have the resprites for affected items (most Vox clothing) ready. I'd like for you to change affected sprites first so we know that this won't be half-baked.

All affected sprites were also adjusted. Please let me know if there are any I missed.
suits

**Comment by zestybastard** [comment]
> > Making this PR seems a little irresponsible if you don't have the resprites for affected items (most Vox clothing) ready. I'd like for you to change affected sprites first so we know that this won't be half-baked.
> 
> All affected sprites were also adjusted. Please let me know if there are any I missed. suits

We'd need you to resprite the changes this would make to Vox related sprites on other servers as well, since the current spriter for Vox has expressed no desire to maintain two distinct models. if we accept this without full compatibility we'd be opting out of future changes by that spriter, so we'd prefer you go the extra mile and make sure that changes for other servers' clothing, overlays and items are supported.

**Comment by Fikou** [comment]
you put your changes from https://github.com/shiptest-ss13/Shiptest/pull/1088 in this pr

**Pull request closed without merging**
