### PR TITLE
New crate sprites

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request
New crate sprites, taken from Skyrat, but were orignally from Tau Ceti
https://github.com/Skyrat-SS13/Skyrat-tg/pull/1245 This seems to be the PR that added them

## Why It's Good For The Game

image

## Changelog
:cl:
imageadd: New crate sprites, open them all!
/:cl:

### CODE REVIEW

**Comment by TallDeekus** [comment]
Saying where you got the sprites and stuff is hot, don't @ me otherwise.

**Comment by rye-rice** [comment]
@TallDeekus

**Comment by TallDeekus** [comment]
I have been @ but I don't see any counter points.

**Comment by rye-rice** [comment]
yeah no

**Pull request closed without merging**
