### PR TITLE
I Left My Heart In Kalixcis [PGF] Crying Sun-Class Light Frigate

### PR DESCRIPTION
**Pull request by Latentish**
## About The Pull Request
Adds the PGF's first ship. The Crying Sun-class Light Frigate. It also adds some sprite....
<details>
<summary>In Game</summary>

</details>
<details>
<summary>Areas</summary>

</details>
<details>
<summary>No Areas</summary>

</details>
<details>
<summary>Icons</summary>

Mission Accomplished Poster by Retlaw34

Etherbor Logo by Coleminerman
</details>
Thanks to MeeMofCourse for the book formatting.

## Why It's Good For The Game
Represents a previously unplayable faction with a new ship.

Todo:

- [x] Add Sergeant Clothes. 
- [x] Describe her.
- [x] Add fluff notes
- [x] Add Mission Accomplished poster set
- [x] Change the name
- [x] Add new sidearm when it's merged.

## Changelog

:cl:phoaly, coleminerman, MeeMofCourse, Retlaw34
add: Added the Crying Sun-class
add: Added PGF comms
icon: Added PGF sprites
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
image

Remind me to update the kalixcis laser gun balance in a bit @coleminerman

**Comment by Latentish** [comment]
This PR is waiting on some assets and should not be full-merged until they are ready.

**Comment by Latentish** [comment]
I will update images after I get more assets to put in. For now here is the ship and subshuttle.
image
image

**Review by Zevotech — CHANGES_REQUESTED** [review]
## Patches
Sabre sheathe populates with a sabre already in it.
image

Captains room has Syndicate secret documents.
image

Jumbo's bed needs to be anchored or it can just be moved around by him.
image

Bridge needs access restrictions.
image

Make the helm a metal console like the rest of them.
image

Crates do not map onto crate shelves. Change the layout and remove some of the empty/useless crates as it is annoying to move every crate in order to stack them onto the shelves. Give the airlock in this room an SSU and an oxygen closet. It doesn't function without the distro pump on.
image

This pump needs to be on for the airlocks to function.
image

Typo.
image

Relay doesn't seem to be working. Might be an issue on my end.
image

It's standard practice to include directional windows between the thruster and precharger/preheater. It looks weird without them.
image

What is the purpose of this pipe contraption? And why is this room's area "Electrical" despite being an engine? I seriously reccomend replacing this... contraption with just a straight plasma pipe into the engine and use the space for other things.
image

Use the /inherit type of SSU to have suits start inside them (do this in the armory as well). I am not sure why you have a wrench on top of the engine that already starts as anchored. I am also not sure if a single plasma engine will be able to support the power demands of this ship (update, it cant. 14kw passive draw and ~35kw active draw).
image

Umm. I think this may have the wrong icon state.
image

I take back what I said about putting the toy gun vendor in the armory. It looks extremely out of place and I don't want marines thinking that they're supposed to use these as weapons. Maybe just move it behind the sergeants desk.
image

Put some glass and a windoor up so marines can't just hop the table. Sergeant and Marine lockers are missing capes, unsure if its intentional.
image

Exterior hull platings start airless and cause spacewind when the hall doors open. They also will cause pressure issues when the ship docks due to them carrying the vacuum with them when they dock.
image

Nail is missing an air alarm. Put something on those empty spaces where the terminals to the prechargers go, SSUs or crates/lockers or something.
image

This room feels like it could use *more*. Maybe add some trays/trash/kitchenware. Needs a salt and pepper shaker so they can actually make eggs. By the way, that fridge subtype stocks itself with a lot of eggs and milk on in it, maybe replace it with a meat-freezer type. If this isn't intentional then give them WAY more rations because 3 is not enough for the entire crew.
image

## Notes
The ship feels very overstocked. Having spare equipment for *every single crewmember and then some* is excessive. Like holy fucking shit excessive.
image
*"Spare"* EVA Closet with SIX SETS OF SUITS
image
Dial it back. You at most need 2 *maybe* 3 spares for any role with more than 3 people.
The armory has ~8 spare sets of armor (coated vests+normal vests and helmets+caps) for THREE MARINES.

On a different note, this vessel could use some direction, as people likely won't know how to play PGF well for a while. I'd make it adminspawn (for admin-curated testing) as well as having a lore writer draft you up some documents to place onto the vessel for players to read. Perhaps something regarding the capes being an essential rank display, potential missions for the crew to seek out, or just something to promote roleplaying as a marine/navy unit.

## Good Things
I love the color palette of the vessel. The teals and greens really make it feel unique compared to any other factions. 

Look at this team of kobolds I've hired to kill you. PGF drip is splendid.
image
image

I love this. Beautiful work making wall lockers as not-shit as you can.
image
image

Finally, Synthetic inclusion bunks.
image

He Will Watch Over Us.
image

Fix as many of the most pressing issues you can and we can TM this on Wednesday or Friday.

**Comment by Latentish** [comment]
image
last change did this

**Review by Zevotech — APPROVED** [review]
I can't wait to kiss lizards on this ship

**Pull request merged**
