### PR TITLE
Ports Whitesands13/Whitesands#766 "No More Chemspam: Redux" 2

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request
Adds requested changes for #918
Any work done outside of the original ported material was done by Retlaw34.

## Why It's Good For The Game
Botany as is can be a little boring.

## Changelog
🆑 ArcaneMusic with tweaks from The0bserver
add: Adds and modifies fertilizers, as well as a new stat, Instability.
add: Strange seeds are now always obtainable from black market uplinks.
add: Upgrades plant guns to have two new functions. Revolution and Mutation Lock.
del: Removes the rather disused functionality of irrigation hoses.
tweak: Plant Analyzer have been upgraded. Using one in hand will now switch between a stat view of your plant, and a chemical view of your plant.
tweak: Trays now accept and store reagents, as well as coming with an autogrow mode. However, these upgrades came at the cost of old self sufficiency, meaning you must attend to your plants a bit more often.
tweak: Earthsblood, while not being able to gild trays anymore, has been found to still be quite powerful as a fertilizer.
/🆑

### CODE REVIEW

**Comment by rye-rice** [comment]
Ayyy, thank you!

**Comment by ghost** [comment]
Not quite sure what else needs to be done. I'll go over the requests again, and check indentation tomorrow. Everything seems functional in game.

**Comment by ghost** [comment]
why

**Comment by Latentish** [comment]
Good PR. It'd be nice to have more attention to Botany.

**Comment by ghost** [comment]
ignore the inactivity, still going to finish it, just a bit stumped on the icon conflict.

**Comment by ghost** [comment]
Should be ready now.

**Comment by Roostercult** [comment]
Hey! I think this is the port, I have a tiny bug report
Everytime that a plant has fully mutated, twice now, It will appear as ready to harvest but will be unharvestable.

**Comment by ghost** [comment]
> Hey! I think this is the port, I have a tiny bug report Everytime that a plant has fully mutated, twice now, It will appear as ready to harvest but will be unharvestable.

Github never notifies me. Is this still an issue?

**Pull request merged**
