### PR TITLE
Overmap 4.5: Wasteplanet Expansion

### PR DESCRIPTION
**Pull request by Erikafox**
that is to say creates biomes for waste planets

## About The Pull Request

dreamseeker_3fbK5Yfp2k

dreamseeker_KHidB6LdRo

https://cdn.discordapp.com/attachments/881319909991260180/1104612113634308217/dreamseeker_Bx4rB7Eq45.mp4

Moves waste planets over to multibiome planet generation while keeping most of their charm intact. It's not "complete" but that's because the hivebot stuff is lacking (which I plan on addressing next), and didn't really put much thought into swarmers.
Also I'm not a spriter
## Why It's Good For The Game
Standardizes waste planets with the rest of our planets while keeping their character.

## Changelog

:cl:
add: Waste planets now generate with biomes, please report any weirdness.
/:cl:

### CODE REVIEW

**Comment by axelzonvolt** [comment]
shiptest now sponsored by vlambeer...

**Comment by Erikafox** [comment]
image

**Comment by AverageUser67** [comment]
i don't know, the masses of plating look really weird
maybe tone it down

**Comment by AverageUser67** [comment]
destroy the plating fields please

**Comment by spockye** [comment]
the plating fields are radical, do NOT

**Comment by Zevotech** [comment]
this looks badass

**Comment by Sun-Soaked** [comment]
https://www.youtube.com/watch?v=NuF6aiWmLF0

**Comment by Erikafox** [comment]
> i don't know, the masses of plating look really weird maybe tone it down

After it gets tested I'll consider it. Still balancing numbers.

**Comment by BarteG44** [comment]
epic fail

image

**Comment by goober3** [comment]
bluespace beacons for spawning bots seems out of place tbh. try replacing their sprites with enabled drone dispensers or heavy lathes on their working loop from icons/obj/machinery.

**Comment by Erikafox** [comment]
need to:

-  convert tile paths to revised scheme 
-  change air mix
-  better / different sprite for hivebot spawner
- experiment with lighting

**Comment by Zevotech** [comment]
Beacons could use some dialing back in both how much health they have and how many hivebots they spawn, considering they tend to generate in groups.

**Comment by Zevotech** [comment]
also, tritium and pluoxium canisters just sitting about seems a little bit much

**Comment by Erikafox** [comment]
I'll touch up beacons and adjust the numbers more when I get the next commit in.

**Comment by goober3** [comment]
if waste planets are going to be More Radioactive, now maybe, like. add a few radiation suits to dedicated scavenging ships. so they can Scavenge without Perishing

**Comment by Erikafox** [comment]
Good idea. I will do that in a seperate PR

I will also give the public info: Geiger counters are free at your autolathe

**Comment by Erikafox** [comment]
image
Whoops

**Comment by Zevotech** [comment]
what an oxygen rich atmosphere does to a mf

**Comment by Erikafox** [comment]
I'll be presenting Infinite Tritfire: The Gas Giant, next month

**Review by MarkSuckerberg — APPROVED** [review]

**Pull request merged**
