### PR TITLE
Clears up the graffiti list, adds hobocode graffiti.

### PR DESCRIPTION
**Pull request by goober3**
## About The Pull Request
This PR:
Removes these graffiti sprites.
73a8f5806f023f6444d442b37162fced

Adds a new set of codersprite graffiti, which is based on hobo symbols. 
74bd1076299c63cafd7822ced40010e5
image

## Why It's Good For The Game
We've got a bunch of cruft in spraycan graffiti, including a ton of weird anti-furry stuff, and references that don't make sense in our setting. This PR removes the bad stuff, and adds some new graffiti to fill the space.

## Changelog

🆑
add: A new graffiti section for code symbols has been added.
del: Some graffiti has been removed from the spraycan list.
/🆑

### CODE REVIEW

**Comment by Sadhorizon** [comment]
The Revolution one kinda looks like the GEC poster. I think it'd be a neat factional grafitti, after some minor adjustments. Up to you ofc, I'm just sharing some thoughts.
obraz

**Comment by goober3** [comment]
c23b29df5b3ad1b104e9027b8d99abfa
why don't you fight me, pal. why don't we take this outside, huh??

**Comment by goober3** [comment]
> The Revolution one kinda looks like the GEC poster. I think it'd be a neat factional grafitti, after some minor adjustments. Up to you ofc, I'm just sharing some thoughts. obraz

yeah, that's a good point. maybe.

**Comment by Hlscientist** [comment]
> The Revolution one kinda looks like the GEC poster. I think it'd be a neat factional grafitti, after some minor adjustments. Up to you ofc, I'm just sharing some thoughts. obraz

Seconded, GEC needs some love!

**Comment by Valorium-RB** [comment]
Reason for getting rid of the star graffiti? That seems like a pretty standard icon.

**Comment by goober3** [comment]
> Reason for getting rid of the star graffiti? That seems like a pretty standard icon.

oh honestly i just didn't want people seeing it and thinking like. pentagrams??? satan real???? truthfullly it doesn't make much of a difference either way.

**Comment by Valorium-RB** [comment]
> > Reason for getting rid of the star graffiti? That seems like a pretty standard icon.
> 
> oh honestly i just didn't want people seeing it and thinking like. pentagrams??? satan real???? truthfullly it doesn't make much of a difference either way.

Fair enough.

**Pull request merged**
