### PR TITLE
CDN Mega Ultra Mk8

### PR DESCRIPTION
**Pull request by ZephyrTFA**
:cl:
server: CDN fully operational again after noticing an incorrectly absolute relative path
/:cl:

### CODE REVIEW

**Comment by goober3** [comment]
maybe? possibly?

**Comment by Galdar02** [comment]
**Definitely**

**Comment by MarkSuckerberg** [comment]
can you give it a proper title and description :pleading_face:

**Comment by FalloutFalcon** [comment]
can you give it a proper title and description 🥺

**Pull request merged**
