### PR TITLE
Add capybaras

### LINKED ISSUE #377: [FEATURE] capybara
## Name of feature:
capybaras!! on jungleplanets!!

### Related Pull Request on other codebase:
https://github.com/vgstation-coders/vgstation13/pull/28618

### Additional Info:
hello please add capybaras and put them on jungleplanets jungleplanets could probably use some mobs. like capybaras!! or monkeys i guess if you're super lame

### PR DESCRIPTION
**Pull request by martinlyra**
## About The Pull Request

```
For God has not given us capybaras of fear, but of power and of love and of a sound mind.
## 2 Timothy 1:7
```
- Adds capybaras, as a subtype of corgi to allow backpacks and head items to be put on
- Adds an unique capybara named Caspar, spawns with Captain's spiky hat by default

Ports sprites from https://github.com/vgstation-coders/vgstation13/pull/28618

## Why It's Good For The Game

Fixes #377 - forfeit all of your possessions to the capybara

```
We love Capybaras because They first loved us.
## 1 John 4:19
```

There are no other god. Only Capybaras.

## Changelog
:cl:
add: Added capybaras, a subtype of corgi
add: Added Caspar the Capybara Captain
imageadd: Stole capybara icons from /vg/ by Kurfursten (vgstation-coders/vgstation13 #28618)
/:cl:

### CODE REVIEW

**Comment by martinlyra** [comment]
Not 100% tested because I need to downgrade my Byond. Any help is appreciated

**Comment by HighPrincessErinys** [comment]
is there any chance you could make them spawn on jungle planets

**Comment by martinlyra** [comment]
I need to figure it out. Or have someone shed some wisdom for me. 

Then I can make it happen.

**Comment by HighPrincessErinys** [comment]
just ask rylie how to fuck with planetgen so we can have monkes and capys on jungles to make them a little bit less boring

**Comment by rye-rice** [comment]
the real solution would be to make the jungle megafauna spawn normally

**Comment by AtlasRules** [comment]
REMEMBER 

make them neutral to all mobs because that’s how it be in Real

**Comment by martinlyra** [comment]
Tested the code. They seem to work pretty nicely, despite being subtypes of corgi. This code may require more work in the future.

All is left now is add the ship-pet version to a ship. But I have no idea which one, so I could use some public advice.
And then make sure that they spawn in jungle biome/ruins

**Comment by Martinpachu** [comment]
he LOVED to eat cement when he was 6

**Pull request merged**
