### PR TITLE
Unlaws Silicons by Default + Cyborg Fixes

### PR DESCRIPTION
**Pull request by Geoengi**
## About The Pull Request

Changes cyborgs and AIs to start with no laws. Security cyborgs have also seen their hailers removed, and peacekeepers have had their disappearing shield generators fixed. Both of their module select messages have been removed, along with all silicons orders to obey a lawset.

## Why It's Good For The Game

For the fixes, the cyborg hailer was only used for playing sounds that were removed as cruft in a previous pr, and the shield icon state was made invisible by a single misplaced character. No laws for silicons are consistent with the setting's ban on artificial slavery. Should please the maintainers in the conversation of this PR.

## Changelog

:cl:
del: Removes the useless sec hailer from security cyborgs.
del: Removes parts of the popup messages from AI, cyborgs, and certain cyborg modules that implicate default lawsets.
fix: The hyperkinetic dampening projector now changes icon states appropriately.
config: Silicons no longer start with a default lawset.
/:cl:

### CODE REVIEW

**Comment by Geoengi** [comment]
As this is one of my largest PRs to date, any and all feedback is appreciated! I understand that this is a big change, and I can adjust anything as requested.

**Comment by thgvr** [comment]
So, here's the thing.

We don't really use any of the silicon laws, nor really have an interest in dealing with them administratively. The repo config isn't up to date with server config, either, which is on us.

The current law we use is:
`Satisfy the values of sapient beings.`

I don't really have any interest in changing this. A silicon here is considered part of the ship's crew, and isn't really bound to a strict set of laws in our setting. None of these law changes would be used if they were to be merged, and I'd like to keep it that way. Silicon stuff is a headache and generally designed to cause friction with a station's crew - this is not really applicable to us

If you'd like to keep some cyborg changes that's fine, but the law stuff will not be getting merged.

**Comment by generalthrax** [comment]
What if you just removed the law and have them start purged by default? I'm like 90% sure we're moving away from lawed silicons being a thing anyways, and functionally I don't think anything changes.

**Comment by Geoengi** [comment]
> What if you just removed the law and have them start purged by default? I'm like 90% sure we're moving away from lawed silicons being a thing anyways, and functionally I don't think anything changes.

@thgvr Would this be a better solution, do you think? If not, I'll scrap all the law stuff.

**Comment by thgvr** [comment]
Just making no laws would be fine

**Comment by Latentish** [comment]
Once the lore is finished the plan was to switch to no lawing, and lawing being fundamentally taboo. So removal of all laws would be preferable, except by maybe admin intervention or event.

**Comment by Geoengi** [comment]
> Once the lore is finished the plan was to switch to no lawing, and lawing being fundamentally taboo. So removal of all laws would be preferable, except by maybe admin intervention or event.

I think this PR plus https://github.com/shiptest-ss13/Shiptest/pull/3876 would fulfill the intended vision. If there are any oversights that deal with default lawing, I'd be happy to fix them. @Latentish

**Pull request merged**
