### PR TITLE
New snow planet ruin: Derelict cargo port

### PR DESCRIPTION
**Pull request by Draggeru**
## About The Pull Request

Adds a new ruin that contains:
Mining loot
A protolathe board
Misc loot such as basic seeds
Some abandoned crates
Syndicate loot such as an illegal borg moduel

## Why It's Good For The Game

More ruins for ship test to test their ships to test....something means good.

## Changelog
:cl:
add: New ice planet ruin
/:cl:

cargoruin

### CODE REVIEW

**Comment by Draggeru** [comment]
I am not sure why Run Linter is failing, if someone could point out what I'm not seeing that'd be great

**Comment by Yellow-Mushroom** [comment]
> I am not sure why Run Linter is failing, if someone could point out what I'm not seeing that'd be great

From what I’m seeing, you didn’t use the TGM map format

**Comment by Draggeru** [comment]
I love formatting!!

**Review by Latentish — CHANGES_REQUESTED** [review]
There are a lot of things that I both dislike about this ruin, and are just not done correctly.
- This pr only adds a .dmm, it is missing the datum required to spawn it.
- The map has only area/space, the default area, which will give serious issues if this were to actually spawn.
- This ruin is essentially a big lootbox. The puzzle aspects can be skipped simply by breaking down a reinforced wall here and there, then bam you have a nearly free protolathe.
- The enemies are scattered in seemingly random places that don't really support any sort of direction or structured challenge for a player to go through. They're also all rather weak melee mobs with the exception of a snowman (reskinned legion) and ice watcher. For the reward and openness of this ruin, I'd expect both different enemies and placement.
- This attempts to be a puzzle ruin, but only uses buttons and shutters to do so, with destructible walls that can easily be broken down to bypass the puzzle aspect.
- The large open snowy area feels extremely superfluous to this ruin, it has very little effect on the level and doesn't do much storytelling otherwise. It has a button to get in, but that could be accomplished with much less (mostly) empty space used.

**Comment by Zevotech** [comment]
will the shutters even work with area/space? wouldnt it have to be a powered unexplored area?

**Comment by Draggeru** [comment]
I have a lot of changes planned to take the feedback into consideration, however, it's going to require starting from scratch. For now, I am going to close this PR.

**Pull request closed without merging**
