### PR TITLE
Adds a new ruin to rockplanets, the Northwind Shipping Cargo Storage Facility

### PR DESCRIPTION
**Pull request by AtlasRules**
## About The Pull Request
Adds a new ruin to rockplanets, a Northwind cargo facility that was attacked by pirates. Featuring lots of general amenities, firearms, and even CE magboots and power tools! Image: warehousewip
Specific loot list:
- Phazon bits, not all are there
- Ripley, with a diamond drill and KILL CLAMP (not the real one), along with a charger.
- Whatever you can salvage from the salvage bay
- A laser, a few Commanders with ammo, two WTs with ammo, some shotgun ammo and two E-cutlasses, and whatever you can get from pirates idk if they even drop weapons lol
- Full surgical tools, handful of first aid kits
- Radiation suit
- Autolathe
- General engineering equipment, including regular toolbelts, a CE toolbelt and magboots, and engineering scanner goggles.
- EXOCON mining gear, along with a meson and a speed upgrade for the PKA, also a diamond drill, adv. scanner and adv plasma cutter in the toolshed.
- Guerilla gloves, because tackling is a funny mechanic.
- Some other bits

## Why It's Good For The Game
Rock planets need more ruins, especially when it's current ruins get split between rock and waste planets.

## Changelog
:cl:
add: New rock planet ruin, the Northwind Shipping Cargo Storage Facility 
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
This looks nice, I like the level design and use of sandbags. But it seems like a deathtrap. That's a lot of syndies to throw in that small a space. Even with the spacing it seems a bit much.  If you've tested this (which you need to do at some point for any pr), have you found that this enemy placement doesn't become overwhelming?

**Comment by AtlasRules** [comment]
i have repeatedly forgotten to start testing this because i have just been mentally fucked for the past like 3 weeks

testing and balance update soon:tm:

**Comment by AtlasRules** [comment]
@Apogee-dev seeing as sylv is on leave, can you slap on a stale exempt? this is waiting on overmap 4 for rockplanets to become a thing

**Comment by Apogee-dev** [comment]
> @Apogee-dev seeing as sylv is on leave, can you slap on a stale exempt? this is waiting on overmap 4 for rockplanets to become a thing

Done and done

**Comment by Latentish** [comment]
This ruin is missing a datum, so it won't spawn.

Also please add a picture from SDMM or whatever editor you use that shows the areas so I can better see how you're doing with this.

**Review by Latentish — CHANGES_REQUESTED** [review]
You are still missing a datum. Please fix that before this stales out as it will close automatically afterwards.

**Comment by ZephyrTFA** [comment]
Address the review.

**Comment by AtlasRules** [comment]
guugughh sorry for not touching this for ages, kinda just lost interest

I'll have a look over the reviews and such tonight and get this heading towards completion

**Pull request closed without merging**
