### PR TITLE
Lil things

### PR DESCRIPTION
**Pull request by BarteG44**
## About The Pull Request
maintainer's hell

adds, changes and tweaks a lot of small things that i don't think are worth a separate PR
-adds black and purple office chairs
-adds pizza cutter
-fixes up the modern railings
-adds armbands to wardrobe vendors
-makes racks stack items in 6 spots rather than just in the middle
-makes tool belts hold more tools like the decal painter and chisel
-fixes up some tiles on the box and li tieguai class
-fixes a typo on the box class engine shutter and reworks it's bathroom
-adds a little more variety to the chem table
-makes the decal painter's decals more consistent with mapping decals by making you unable to clean them with soap
-(hopefully) fixes the justice helmet once and for all

## Why It's Good For The Game
a whole lotta new stuffs
image
image
Zrzut ekranu 2023-06-01 183319
image
image
image

(i can separate some of the features if it's deemed necessary) 

## Changelog

:cl:
add: Added Pizza cutters
add: Added black and purple office chairs
tweak: tweaked how racks stack items 
tweak: renames armbands from departments to their colors and adds them to clothes vendors
tweak: made utility belts able to hold decal painters and etc.
tweak: adds a little more variety to the chem table sprite
tweak: makes the decal painter's decals more resistant to cleaning
fix: fixed being unable to make and color modern railings
fix: fixed up some tiles on the box and li tieguai class
fix: fixes a typo on the box class engine shutter and reworks it's bathroom
fix: fixes the justice helmet at last. rejoice!
/:cl:

### CODE REVIEW

**Comment by BarteG44** [comment]
i'll try to fit the justice helmet final fix into here too but i _cannot_ code so no promises

**Comment by TheNeoGamer42** [comment]
based not modularizing features into multiple PRs

**Review by rye-rice — CHANGES_REQUESTED** [review]
pizza cutter sprite needs outlines  and better shading

**Comment by BarteG44** [comment]
> pizza cutter sprite needs outlines and better shading

image
image


hopefully this is better?

**Comment by Imaginos16** [comment]
Rylie's review was kind of weak so I'll explain in more detail why the sprite could be better.

- Color Selection

The current version of it is too muddy and lacks the vibrancy we expect from sprites these days. You would benefit a lot with more contrast and better hueshifting.

- Shading

The shading is also a problem, as its rather simplistic, and falls into the trap of using too many shades for a single color. You'd benefit a lot more with merely using four shades, rather than the six you used. A pizza cutter wouldn't have many differing tones anyway.

Here's a suggested change you could make:

image

**Comment by BarteG44** [comment]
This should be all for this PR.

>Here's a suggested change you could make:

i basically copied what you suggested for the pizza cutter so yeah
image

**Review by rye-rice — APPROVED** [review]

**Review by MarkSuckerberg — APPROVED** [review]
I will say that while inconvenient, making multiple PRs with stuff seperately is generally the better option when getting your PR reviewed and merged. I won't stop this though, just consider it when making more PRs. I'm a lot less hesitant to quickly merge a PR that changes 20 lines than one that changes 500.

**Pull request merged**
