### PR TITLE
Billboards

### PR DESCRIPTION
**Pull request by EEASAS**
yeah

## About The Pull Request
adds billboards, there are 20 variants that can be used by mappers
also this is a port from tg

## Why It's Good For The Game
i see a lack of them in ruins
also you see them everyday

## Changelog

:cl:
add: Billboards! They cannot be constructed but mappers can use them.
imageadd: Billboard icons
:cl:

### CODE REVIEW

**Comment by EEASAS** [comment]
i dont know why there are so many changes in the fucking DME

**Comment by ZephyrTFA** [comment]
Fix your dme file.

**Comment by zestybastard** [comment]
these sprites are bad
image
this sprite is bad. why would you do this? we have rules against this

**Review by thgvr — CHANGES_REQUESTED** [review]
None of these sprites fit our server in regards to lore or quality. If you plan on remaking them and collaborating with the lore team to do so, it will be considered

**Comment by EEASAS** [comment]
alright i'll take a shot at respriting these, meanwhile keep this draft...

**Comment by EEASAS** [comment]
on second though i may do this like in 6 months because i barely know how to sprite

**Pull request closed without merging**
