### PR TITLE
(DNM)Adds the Voulgier-Class Troopship 

### PR DESCRIPTION
**Pull request by 1glitchycent**
## About The Pull Request
Adds a new vessel, the Voulgier Class, a dropship of the former(missing, presumed lost) 2nd Fleet of the Gorlex Marauders. It's equipped with a top-of the line medical bay, and combat equipment. It should be noted that this vessel was designed to be supplied by a proper logistics chain, and thus, lacks equipment for independent operation.
image

## Why It's Good For The Game
Adds a hyper-specialized ship that could create new gameplay scenarios

## Changelog
:cl:
add: Added Voulgier class troopship
/:cl:

### CODE REVIEW

**Comment by Pontenerd** [comment]
The bedrooms seem very nice for a troop ship, maybe use bunk beds instead? Also perhaps a solid wall between the medbay and EVA?

**Comment by Apogee-dev** [comment]
Seems pretty large for its purpose, with a lot of open space. Low-traffic areas like dorms and the bridge don't necessarily need the double doors, while a single door on the cargo bay and leading into medbay / the launch bay is probably going to restrict flow pretty severely.

**Comment by 1glitchycent** [comment]
The Voulgier now has a bulldog instead of a Tec 9, with 2 extra magazines. Also, the EBR magazines have been reduced from 8 to 2.

**Comment by 1glitchycent** [comment]
Gonna be out of town for about a week, will re-open when  I get back.

**Pull request closed without merging**
