### PR TITLE
Remaps the Lavaland Winter Biodome

### PR DESCRIPTION
**Pull request by Zevotech**
### Extrasolar Biodome Project

The Most Serene Solar and Intersolar Confederation welcomes you to one of our many experimental biodomes out in the frontier.
These facilities are developed and built as a collaboration with the Pionierskompanien and are to serve as extrasolar research bases for our most accomplished scientists and scribes. These facilities utilize breakthroughs in terraforming technology to create a comfortable, habitable environment in even the harshest of locales. Your purpose here is to research and report on the effectiveness of the technology utilized within the central dome, as well as maintain and protect the facility.

This PR remaps the lavaland winter biodome into a facility used by the Pionierskompanien to field-test terraforming and environmental regulation technologies. Unfortunately for the occupants, it seems the local fauna had other ideas.

The main loot of this ruin is: 5 Plasma sheets, a small sum of credits, a Pistole C and a Claris in the display case.

### Pictures

StrongDMM-2024-03-23 21 57 03
StrongDMM-2024-03-23 21 57 04
image

## Why It's Good For The Game

Fixes yet another crufty TG ruin that had some ever-so-racially-insensitive mobs within it. Those have been removed, by the way.
This also places SolCon into the ruin pool, hopefully allowing for me to make a series out of similar projects like this on other planets.

## Changelog

:cl:
add: Remaps lavaland_surface_biodome_winter.dmm
del: Removes the "Undead Eskimo" mob
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
Approving as the SolGov lorewriter for concept. Excellent work!

**Comment by Apogee-dev** [comment]
The biodome crew had no bathroom… truly, the legions were a mercy

**Comment by Latentish** [comment]
image
This building is strange. The restroom being access from outside, and this pesudo air cycler are a bit out of place.
Other than that this is a phenomenal rework. Will test on live.

**Review by meemofcourse — CHANGES_REQUESTED** [review]
imagen
this gun should probably be unloaded, or at least have some casings
imagen
this hallway is pretty lame. i get it being unlit, which is pretty cool, but it doesn't have much. maybe you could add some filing cabinets, or dropped papers around, like if the person in there was carrying paperwork, perhaps.

i will mention that i tried to run this ruin with a cybersun commando uni and i slipped on the ice, then got skill issued by the legate. good ruin

**Comment by Zevotech** [comment]
> This building is strange. The restroom being access from outside, and this pesudo air cycler are a bit out of place. Other than that this is a phenomenal rework. Will test on live.

1. The toilet functions as an outhouse (and i forgot to put it in until the last second)
2. The air cycler is needed to prevent the water vapor from the sauna from leaking out and freezing every single floor.

> this gun should probably be unloaded, or at least have some casings

The Pistole C fires caseless ammunition and has no unloaded subtype. Added an empty(?) magazine besides it.

>this hallway is pretty lame. i get it being unlit, which is pretty cool, but it doesn't have much. maybe you could add some filing cabinets, or dropped papers around, like if the person in there was carrying paperwork, perhaps.

Filing cabinets and dropped papers are a great idea. Added.

**Comment by Latentish** [comment]
cool i'm satisfied. tm'ing and making sure it do gooder

**Review by meemofcourse — APPROVED** [review]
solgov kill

**Comment by goober3** [comment]
when you the ships Ruin. Despair.

**Pull request merged**
