### PR TITLE
Very minor medkit resprite, resprites medal boxes and makes the beer crate that appears on some sand ruins 3/4

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request
While making the defib sprite some time ago I was told the handle was "banded," but i stole the handle from the medkit sprites. This makes the medkits follow that advice and hopefully look better
This also redoes the medal box since it was in the same file

## Why It's Good For The Game
image

## Changelog
:cl:
imageadd: medkit sprites have been tweak very slighlty
imageadd: beer crates are now 3/4
imageadd: medal boxes no longer soulful
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
@triplezeta

**Comment by rye-rice** [comment]
updated pr

**Comment by MarkSuckerberg** [comment]
@triplezeta review it !!!!!!!

**Review by triplezeta — APPROVED** [review]
these are indeed boxes

**Pull request merged**
