### PR TITLE
Total harddel audit + far more thorough unit testing

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request

Ports a bunch of harddel fixes from /tg/ + improved reftracking + create & destroy testing, plus adds many harddel fixes of my own from said testing both locally and on live

Port list:
tgstation/tgstation#57728
tgstation/tgstation#58972
tgstation/tgstation#59371
tgstation/tgstation#59612 (only the test, most harddel fixes I ignored)
tgstation/tgstation#62725
tgstation/tgstation#63877
tgstation/tgstation#51544
tgstation/tgstation#59804
tgstation/tgstation#63276
tgstation/tgstation#62755
tgstation/tgstation#66649
tgstation/tgstation#72401
tgstation/tgstation#53816
tgstation/tgstation#73261 (just a few tweaks from this)
tgstation/tgstation#73037

## Why It's Good For The Game

Hard deletes are the largest source of overtime currently, and it's becoming a problem now that we're approaching 60pop on the regular. For the sake of playability, drastic action needs to be taken, and this is that drastic action. 

I hate how big this PR is, it's one of my biggest mistakes so far.

## Changelog

:cl:
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
me when mixed indentation

**Comment by FlufflesTheDog** [comment]
The canPass refactor (tgstation/#59804) included in this messes with pixel shifting (stops people from walking past others that have shifted out of the way), needs a get_dir removed now that we're passing around directions instead of turfs
https://github.com/shiptest-ss13/Shiptest/blob/98751b40e9902deb13febcbdfb6507ef2e856c1f/code/modules/pixelshifting/pixelshift.dm#L66

Let me know if you need any more details

**Comment by thgvr** [comment]
That would explain what brokei t

**Comment by MarkSuckerberg** [comment]
Oooooop, I didn't even think of that, thank you for noticing, I'll get that tweaked as soon as I can, good catch

also reminds me that I need to actually make a PR body for this that lists all the stuff I grabbed in a place that isn't the depths of commits so we can catch any breaking changes like that

**Comment by MarkSuckerberg** [comment]
Walking through pixelshifted people should be fixed now

oh boy time to make a PR description

**Comment by ZephyrTFA** [comment]
what's this button do

**Comment by meemofcourse** [comment]
blame zephyr

**Comment by ZephyrTFA** [comment]
oops I slipped and fell on the big red button

**Pull request merged**
