### PR TITLE
Remaps the Kilo

### PR DESCRIPTION
**Pull request by Sadhorizon**
## About The Pull Request
This remaps the Kilo.
**TODO:**
- [x] ship desc
- [x] wiki page
- [x] Maurice
- [x] processing console directionals

Hull is now made from metal instead of titanium. The manufacturer was swapped from NT to Miskilamo. Crew areas were expanded. KA and Egun were swapped for two DBs - have fun with this one. Wires got a tiny bit messier. Starting cash was nerfed from 5500 to 3500. ORM was replaced with a smelter setup.

scrnshot1

StrongDMM-2024-07-19 13 24 26

StrongDMM-2024-07-14 01 21 13

**JOB SLOT CHANGES:**
- No doctor - There never was a medical. Why were they here?
- One more deckhand - Apogee requested the ship to stay at 5 crew members.

## Why It's Good For The Game
Kilo's ancient. This modernizes it.

## Changelog

:cl:
tweak: Remapped the Kilo-class Mining Ship
/:cl:

### CODE REVIEW

**Comment by generalthrax** [comment]
I mentioned this already to you in general but I'll put this here to be more accessible:

1. That airlock is Not going to last more than a few cycles with just two air canisters
2. I'm not even sure if its enough to fill distro
3. You might be able to filter the airlock air back into distro around here

as

**Comment by Sadhorizon** [comment]
You'd be surprised, actually. From testing, distro isn't that much of a problem. With three cans, you can cycle the airlock ~9 times. Which... yeah. I think the canister idea is just a bad idea and I'm gonna use a pressure tank.

**Comment by thgvr** [comment]
It's over...

**Comment by axelzonvolt** [comment]
completely and utterly deranged soul removal.
#mauricedidnothingwrong

**Comment by Sadhorizon** [comment]
I have made a great mistake. He is back now though.

**Comment by Martinpachu** [comment]
i fucking hate maurice

**Comment by thgvr** [comment]
maurice

**Review by thgvr — APPROVED** [review]
maurice

**Review by Apogee-dev — APPROVED** [review]
maurice

**Comment by Anticept** [comment]
Missing a cryo console.

**Comment by Sadhorizon** [comment]
Yep, noticed.

**Pull request merged**
