### PR TITLE
Adds the Nanotrasen Turing-Class Synthetics Vessel, an ship of only silicons

### PR DESCRIPTION
**Pull request by Yellow-Mushroom**
## About The Pull Request

Pictures of ship here:

turing3
turing2

Notice: 

Remaining issues:
-AI's starting laws cannot be set
-The non-initializing AI (the latejoin one) creates a runtime

This ship fits 2 AI's as the left and right brain of the ship, (left brain being the initialization job for the ship), and 5 cyborgs that humorously pop out of cryo when people join into the job but are entirely functional.

The AI's also each start with 1 cyborg they can deploy themselves into to function.

There is also a drone printer on board, and the AI's are intended to have a custom NT lawset to facilitate fun and between both this intrafaction and interfaction interaction. Ill add it here later.

Total crew:
2 AI's
5 Cyborgs

that is it, more can be built as needed but the 2 ai's start on ship, and the 5 borgs come out of cryo. No carbon lifeforms start on ship

## Why It's Good For The Game

This is one of the only ships of its kind, shapewise, nichewise, and playstyle wise

## Changelog
:cl: Myco/Yellow
add: Adds the Nanotrasen Turing-Class Synthetics Vessel
add: Adds a new lawset for Nanotrasen Ships
fix: fixed a few things
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
Very pretty ship.
And while I kniw its an AI and borg ship, if it is supposed to be habitable by non silicons, then you need a bathroom with a sink.
My recommendation is making a shoilet, since they're silicons who don't have a lot of use for it, you could shove the sink/shower/toilet in a 1x1 restroom.

**Comment by Yellow-Mushroom** [comment]
> And while I kniw its an AI and borg ship, if it is supposed to be habitable by non silicons, then you need a bathroom with a sink.

It was a purposeful choice to design this ship without a bathroom + airpipes/repressurization facilities. It does start pressurized, and has two airtanks for the crew to repressurize if they ever need to, but its not designed for carbon life forms to stay on this vessel without having to suffer some

**Comment by Zevotech** [comment]
Isn't AI control for the helm console off by default?

**Comment by Yellow-Mushroom** [comment]
> Isn't AI control for the helm console off by default?

Correct, this is another one of the issues I’m going to be attempting to fix by having an edited helms console that has it on from round start

**Comment by MusselMain** [comment]
> > And while I kniw its an AI and borg ship, if it is supposed to be habitable by non silicons, then you need a bathroom with a sink.
> 
> It was a purposeful choice to design this ship without a bathroom + airpipes/repressurization facilities. It does start pressurized, and has two airtanks for the crew to repressurize if they ever need to, but its not designed for carbon life forms to stay on this vessel without having to suffer some

I think they're trying to suggest that you add a tiny livable room (containing a toilet, bed, and sustenance vendor) as a In-Lore bit to show where a human could stay if they had to preform routine maintenance.

**Comment by Yellow-Mushroom** [comment]
added a human "food" crate, along with a sink inside the human holding chamber

**Comment by SupernovaXTS** [comment]
Borgs cannot pick up things if i am correct, Replace cyborg slot with IPC with access to binary?

**Comment by MitztheKat** [comment]
This actually looks pretty cool

**Pull request closed without merging**
