### PR TITLE
Removes tiny fans from (almost) every ship.

### PR DESCRIPTION
**Pull request by goober3**
## About The Pull Request
Tiny fans on every ship in shuttles/shiptest have been replaced with holofields. 

## Why It's Good For The Game
holofields are the standard for ships. tiny fans shouldn't be used at all on ships. god! 

## Changelog

:cl:
tweak: Tiny fans on the Meta and Lagoon have been replaced with holofields.
/:cl:

### CODE REVIEW

**Comment by Pumpkinoe** [comment]
there are some on the boyardee as well

**Review by spockye — APPROVED** [review]
another pr's up fixing the boyardee so its fine ig

**Comment by Latentish** [comment]
Please fix your merge conflict so we can TM this and then merge it.

**Comment by meemofcourse** [comment]
fix your conflicts ! ! !

**Comment by thgvr** [comment]
um........... ship?

**Pull request closed without merging**
