### PR TITLE
Luxembegone

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

Donk Co. has had it too good for too long.

- Removes the luxembourg.

## Why It's Good For The Game

I have seen this ship used by a non-powergamer crew less than five times over a period of multiple years. Multiple tweaks and nerfs have not changed this.

## Changelog

:cl:
del: Removed the Luxembourg.
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
~~salt pr~~

this ship aged like fucking milk, and if im not mistaken, the last of the map emporium ships. it needs to be killed off

**Comment by Zevotech** [comment]
The note that says "Sell your wares instead of using them to powergame" hardly seems to stop people anyways. We will get better ships in time.

**Review by Zevotech — APPROVED** [review]
Rot.

**Comment by CenkTheRaptor** [comment]
honestly that nt ship with the subshuttle did a better job at this anyways (i think it was nt? i forget it mightve been removed actually)

**Comment by Geoengi** [comment]
> honestly that nt ship with the subshuttle did a better job at this anyways (i think it was nt? i forget it mightve been removed actually)

You're thinking about the NT Borea and it never got merged. The author, Bjarl, doesn't contribute anymore either iirc.

**Pull request merged**
