### PR TITLE
The Tidal Barrier

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

Removes the HighTide and TrunkTide. The original flavor of Tide remains, for now, until its replacement is done.

## Why It's Good For The Game

i am getting very, very tired of manifests with three or more hightides on them. even with proper ship limits, these ships were all on the cutting board in the first place due to their lackluster design and the playstyles they tended to encourage.

## Changelog

:cl:
del: Removed the HighTide and TrunkTide
del: deprecated the Tide
/:cl:

### CODE REVIEW

**Comment by MusselMain** [comment]
i understand why, but it's a bit unfortunate that most of the challenge ships have been removed for easier options, although i guess it's easier for new players

**Comment by thgvr** [comment]
Won't be sad to see them go.

**Comment by BarteG44** [comment]
I knew this day would come at some point

**Comment by Apogee-dev** [comment]
Fixed merge conflicts. Also deprecates the Tide.

**Review by Erikafox — APPROVED** [review]
i merge-a the pull request

**Pull request merged**
