### PR TITLE
Updates Paperwork Code

### LINKED ISSUE #1658: [BUG] Fax Machine GUIs are broken
## Round ID:
N/A. Discovered on a local build.

## Reproduction:
Interact with a fax machine (long-range or not), cry at the blank page.
imagen
imagen

### PR DESCRIPTION
**Pull request by meemofcourse**
I'm shamelessly using [this port](https://github.com/BeeStation/BeeStation-Hornet/pull/8821) as a guide. Credit to them for their great work. This PR constantly reminds me to work on it.

## About The Pull Request

Fixes #1658.
Updates the papercode to be somewhat more in-line with TG's own. Objective is to port the following pull requests:

* [x] Papercode 
* * [x] https://github.com/tgstation/tgstation/pull/68612
* * [x] https://github.com/tgstation/tgstation/pull/69071
* * [x] https://github.com/tgstation/tgstation/pull/63879 (a small part of it. i'm not doing this)
* * [x] https://github.com/tgstation/tgstation/pull/73628
* * [x] https://github.com/tgstation/tgstation/pull/72367
* * [x] https://github.com/tgstation/tgstation/pull/73633
* [x] Photocopier Improvements (we already have this ported, we just need to get it up to date)
* * [x] https://github.com/tgstation/tgstation/pull/61323
* * [x] https://github.com/tgstation/tgstation/pull/63287
* * [x] https://github.com/tgstation/tgstation/pull/69198
* * [x] https://github.com/tgstation/tgstation/pull/69005
* * ~~custom shiptest forms~~ going to be put into a different pr
* [x] Fax Machines
* * [x] figure out why it's broken (it's a whitesands system from oracle. i'm replacing it entirely)
* * [x] https://github.com/tgstation/tgstation/pull/69397
* * [x] https://github.com/tgstation/tgstation/pull/69554
* * [x] https://github.com/tgstation/tgstation/pull/69651
* * [x] https://github.com/tgstation/tgstation/pull/70072
* * [x] https://github.com/tgstation/tgstation/pull/71262
* * [x] fix issues with logging and following
* * [x] make fax machines be properly named
* * [x] custom admin fax recipients

* [x] make it not break interviews

## Why It's Good For The Game

Fax machines have been broken for a good while. Recent re-introduction of SolGov into the game, a very bureaucratic entity, demands better paperwork. Annoy admins, send threats, shurikens and pizza through fax. Admins don't have to use NanoPrayer:tm: anymore. Kansatsu funnies. Inteq binding contracts. Send pictures of your ass to everyone in the sector. Get hunted down by the paperwork police for sending pictures of your ass to everyone in the sector.

## Changelog

:cl: Bobbanz1, Timberpoes, SteelSlayer, twilightwanderer, ShizCalev, timothymtorres, Imaginos16, dragomagol, Jacquerel, Mothblocks, ThePotato97, LemonInTheDark, ported by MeeMOfCourse
qol: AIs now see the full paper interface when players show them papers through the camera, exactly what's written on the paper, fully rendered.
refactor: Paper code has been completely refactored.
fix: Fixes signatures not working at all. Signatures now only work when %s or %sign is put into an [___] input field.
fix: Input fields are now fixed and also work again.
fix: Fixes markdown paragraphing not working in paper code.
tweak: You can insert any type of toner cartridge into photocopiers, and regardless of the currently inserted toner's charge level.
tweak: Toner cartridges can be ejected from photocopiers at any time
add: Added a system of forms and the ability to print them
fix: Hints in bureaucracy forms
add: Added new VOID stamp
tweak: switches old oracle fax machine with tg's fax machine system
fix: Fixes faxes playing the "fax_contain" animation and makes it actually use the "fax_receive" animation when receiving.
imageadd: Resprites fax machines!
admin: fax messages and book printings are now logged in paper.log
admin: renaming fax machines is logged in game log
add: You can now send photos or trading cards through the fax machine.
add: You can now hack the wires of a fax machine to have it throw items harder or accept additional flat input items such as material sheets, ID cards, and pizza slices.
add: Ability to send and receive administrator fax messages.
admin: Panel for easy viewing and sending messages to faxes.
fix: Fixes a crash of TGUI fax panel when there is no fax in the network
fix: Fixes a crash of the Fax Manager panel when there is no fax machines in the network.
fix: You can no longer remove the toner cartridge from a printer while it's busy printing.
/:cl:

### CODE REVIEW

**Review by Imaginos16 — APPROVED** [review]
I love how my sprites went full circle to here. Very funny.

**Comment by meemofcourse** [comment]
i am going to punch someone

**Comment by thgvr** [comment]
Couple notes:
You cannot write in fields on copied papers.
Performance is *awful*, and can crash your game when you're typing quickly on papers.

**Comment by meemofcourse** [comment]
> Couple notes: You cannot write in fields on copied papers. Performance is _awful_, and can crash your game when you're typing quickly on papers.

fixed. somewhat
imagen

**Review by MarkSuckerberg — APPROVED** [review]
Yeah

**Pull request merged**
