### PR TITLE
[TESTMERGE REQUIRED] Fix various runtimes, enables Initialize SHOULD_NOT_SLEEP

### PR DESCRIPTION
**Pull request by noelle-lavenza**
## About The Pull Request
- Fixes a runtime with a Hierophant attack's armor checks.
- Fixes two runtimes where fingerprints were added to qdeleted items.
- Stops blood from spawning in groundless turfs. TODO: Support bleeding onto a Z-level below
- Port some fixes to stacks and Initialize from TG.
- Re-enables SHOULD_NOT_SLEEP in Initialize.

## Why It's Good For The Game
- Runtimes bad.

### CODE REVIEW

**Comment by antropod** [comment]
#1310 is caused by this PR, tested on local server - all current TM's without this - stacking working, with this - not working

**Comment by MarkSuckerberg** [comment]
RIght, probably ready for merge tbqh

**Comment by ZephyrTFA** [comment]
Can't merge until you fix checks

**Comment by MarkSuckerberg** [comment]
LGTM

**Pull request merged**
