### PR TITLE
Makes Plastic Flaps no longer airtight

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
# You cannot tell me these fucking things are blocking the vacuum of space.
Baggage-Claim-Strip-Curtain-Kit-Shop-All-StripCurtaincom_500__00450
(Makes plastic flaps no longer block atmos and changes the name and desc to match.)

## Why It's Good For The Game
Players should not be able to construct a budget-tinyfan for 5 plastic with only the caveat of having to crawl under it. Using these to cover bay doors has been frowned upon for a while and it should have been fixed when tinyfans were phased out.

## Changelog

:cl:
del: Plastic flaps no longer block atmos
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
if any ships break its your problem

**Comment by goober3** [comment]
> if any ships break its your problem

looks at the delta.

**Comment by Zevotech** [comment]
delta adjusted

**Comment by Apogee-dev** [comment]
> delta adjusted

#2967 already accounts for this

**Pull request merged**
