### PR TITLE
Adds an addiction threshold to cement

### PR DESCRIPTION
**Pull request by goober3**
## About The Pull Request

Cement is now addictive.

## Changelog

:cl:
tweak: Cement now has a 25 unit addiction threshold
/:cl:

### CODE REVIEW

**Comment by Erikafox** [comment]
not while cement drinking is logged

**Comment by meemofcourse** [comment]
no fun allowed

**Comment by BarteG44** [comment]
> not while cement drinking is logged

literally 1984

**Comment by Ms-Mee** [comment]
Beauty

**Comment by Erikafox** [comment]
re-open if you're serious about this

**Comment by goober3** [comment]
image

**Comment by meemofcourse** [comment]
literally

**Pull request closed without merging**
