### PR TITLE
Komodo Tweaks

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

Limits the Komodo to 1 ship per round, renames some airlocks and areas so they properly auto-name, and replaces blood-red suits with scarlet suits. Also used some black magic to make the turrets actually function with the turret controller on the bridge.

## Why It's Good For The Game

Komodo needed a little love and an actual limit appropriate to its power and intended use-case as a ship comparable to the Ranger.

## Changelog
:cl:
tweak: Adjusted Komodo airlocks to auto-name appropriately
tweak: Removed sleeper from Komodo medbay, added medic space suit.
tweak: Replaces catwalk turfs on the Komodo with plated catwalks
balance: Limited Komodo to 1 per round.
balance: Replaced blood-red hardsuits on Komodo with 3 scarlet hardsuits.
fix: Komodo turrets now respond to turret controller on bridge
fix: Komodo now has the correct circuit imprinter board
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
regex why.

**Comment by Yellow-Mushroom** [comment]
Whoops, ignore that

**Review by Yellow-Mushroom — APPROVED** [review]
Everything is tested and works fine, I love holofans so much

**Comment by spockye** [comment]
Quick note, but please dont replace all the hardsuits with scarlets. Atleast let it keep one blood red, so its atleast comparable to the hyenas

**Comment by Apogee-dev** [comment]
> Quick note, but please dont replace all the hardsuits with scarlets. Atleast let it keep one blood red, so its atleast comparable to the hyenas

Komodo has more armored suits and way more guns than the hyena (it’s just a revolver a stechkin and a shotgun now), a blood-red would push it over the edge imo. Even the dedicated combat ships (inteq, minutemen) don’t have anything better than security hardsuits and bulletproof vests.

**Pull request merged**
