### PR TITLE
Removes the Blood Cult from Maps

### PR DESCRIPTION
**Pull request by goober3**
## About The Pull Request
This PR:
- Mass-replaces Cult mobs, turfs, items & structures. 
- Reworks onehalf.dmm & rockplanet_crash_cult.dmm (now rockplanet_crash.dmm) to feature hivebots instead of cult constructs.
- Removes jungle_demon.dmm, jungle_witch.dmm, lavaland_surface_cultaltar.dmm, lavaland_surface_fuckedupandevilclub.dmm, and rockplanet_cult.dmm due overall lack of quality.
- The 'village elder' boss in icemoon_underground_abandoned_village.dmm has been replaced by a frontiersman with a shotgun & a box of slugs. 

## Why It's Good For The Game
We changed our lore and cultists aren't canon anymore. Nor is magic. Half of these ruins are god awful, also. Take the fucked up and evil club, for instance:

image

Now, behold, a lore-friendly onehalf.dmm:

image

## Changelog

:cl:
tweak: Blood Cult content has been removed from all maps.
del: Jungle_demon.dmm, jungle_witch.dmm, lavaland_surface_cultaltar.dmm, lavaland_surface_fuckedupandevilclub.dmm, clericden.dmm, and rockplanet_cult.dmm have been removed.
tweak: Onehalf.dmm, rockplanet_crash_cult.dmm & icemoon_underground_abandoned_village.dmm have been reworked slightly, to feature no more magic.
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
Very epic and cool, we can tm this once it's no longer merge conflicting

**Review by Latentish — CHANGES_REQUESTED** [review]
image
Kill or change cleric den please.

**Comment by goober3** [comment]
> image Kill or change cleric den please.

oh, woops. totally forgot about that one.

**Review by Latentish — APPROVED** [review]
Merging this is a sort of gambit we play. There's no way know for sure whether or not you removed all the peripheral code bullshit. So we're going to play a game.

Yeah this is good, tested on live. you did the correct stuff with the catalogue, and you seem to have hunted down areas. You've almost certainly missed a couple things. But that's just the world we live in. Marge time.

**Pull request merged**
