### PR TITLE
Osprey Tweaks

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

Several tweaks intended to improve quality of life on the Osprey and to rein in some of its more outsized capabilities.

- switched sci from omnilathe to scilathe
- removed cargo selling pad (you can still make orders and recharge the selling console with holochips and space cash, which you get a bonus 500 of to start with)
- added CMC and crew pinpointer for medbay
- expanded kitchen, added food processor, and stocked fridge with milk flour and sugar
- converted engine room rear walls to standard titanium
- limited Osprey-class to 1 per round

## Why It's Good For The Game

QoL is good and the Osprey was a little bit too stronk.

## Changelog
:cl:
add: Added CMC and crew pinpointer to Osprey
add: Added food processor and improved ingredient stock to Osprey kitchen
tweak: Switched Osprey's RnD kit to science lathe instead of omnilathe
tweak: Replaced Osprey engine room's exterior wall with standard titanium, enabling possible expansion
tweak: Limited Osprey to 1 ship per round
del: Removed cargo selling pad from Osprey and gave QM bonus $500 for the selling console
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
big glooba, very based

**Comment by Dimasw99** [comment]
While you are at it. The engine room in the back has walls that cannot be deconstructed. It would be a significant QoL if you can change them to something that can be deconstructed.

**Comment by Zevotech** [comment]
m yeah pics would be appreciated, i wanna see the kitchen

**Comment by Apogee-dev** [comment]
> While you are at it. The engine room in the back has walls that cannot be deconstructed. It would be a significant QoL if you can change them to something that can be deconstructed.

They're reinforced walls, primarily to prevent radiation from leaking into the halls or the exterior. I can't change them without that becoming an issue.

**Comment by Dimasw99** [comment]
> They're reinforced walls, primarily to prevent radiation from leaking into the halls or the exterior. I can't change them without that becoming an issue.

The interior walls facing the hallway are fine. I am talking about these that face sideways or the back of it. I personally would enjoy it if I can for example expand the engine room to build more unga engines. Rad shielding itself is also an akward story since the best you have are rad collectors or diamond doors with their 50% absorption meanwhile rwalls have 40% compared to normal walls having 30%. With our current code there is very little you can do about rads sadly.

**Comment by Apogee-dev** [comment]
> The interior walls facing the hallway are fine. I am talking about these that face sideways or the back of it. I personally would enjoy it if I can for example expand the engine room to build more unga engines. Rad shielding itself is also an akward story since the best you have are rad collectors or diamond doors with their 50% absorption meanwhile rwalls have 40% compared to normal walls having 30%. With our current code there is very little you can do about rads sadly.

Part of the intended challenge with the osprey to balance out its other strengths was having that limited engine space to work with, and an overall janky engineering situation (you can indeed fit an SME in there apparently) but I see your point, I'll make the back walls standard titanium again.

**Comment by UltraNumeron** [comment]
Honestly i am not a fan of the cargo hold pad being removed here, it feels really half baked  as our economy system is unpolished and as jobs mean really nothing here it just encourages people to take high paying jobs and add more slots of em, you really should fix how money is gained before removing a hold pad from a ship without much reason.

**Comment by Valorium-RB** [comment]
Keep the cargo hold pad. Having a high-pop ship actually be powerful encourages people to play together, so nerfing the crap out of it directly discourages such. We've had a really good thing going here by almost always having an Osprey with many crew members to get people working together. We just wholesale removed a ship and blocked the merging of at least one new ship because we wanted to discourage single-player, why would we nerf the most popular high-pop ship and inhibit that vision?

**Comment by Apogee-dev** [comment]
> We just wholesale removed a ship and blocked the merging of at least one new ship because we wanted to discourage single-player, why would we nerf the most popular high-pop ship and inhibit that vision?

Because overemphasizing large ships with giant crews and such an abundance of resources and equipment that you don't usually need to worry about your supply also isn't really in line with what we're going for, to my understanding; the point's largely to encourage play of small to mid size ships, and a concept that's been underpinning shiptest from the start has been scarcity and needing to work around it creatively. Capping the Osprey to one per round will of course help a lot with the population of other ships but it's still a fact that an Osprey can completely steamroll pretty much anything else if it needs to and thanks to having both cargo and unrestricted RnD could access basically any equipment it wanted. Switching RnD to a science focus and putting a moderate limit on cargo by nixing the selling pad means cargo still has something to do but needs to think hard about budget before buying out the entire catalogue, and RnD can't just gear the entire ship up with top-end equipment in every department given enough time. It also gives the Osprey a reason to trade with other ships, since now there's a good chance they'll actually have something you don't.

That, and I really want to see how the no-selling-pad experiment pans out, because afaik it hasn't been tried before on any other ship. I'll put the selling pad back if it doesn't work well after being TMed for a while, but for now I've given the QM significantly more money to work with (just enough to cover the purchase of an AME setup, or buy deep core drills if you don't feel like having an engine).

**Comment by Zevotech** [comment]
ah yes, the singular superpacman in the engine room, the bane of a clueless crew

**Comment by UltraNumeron** [comment]
> > We just wholesale removed a ship and blocked the merging of at least one new ship because we wanted to discourage single-player, why would we nerf the most popular high-pop ship and inhibit that vision?
> 
> Because overemphasizing large ships with giant crews and such an abundance of resources and equipment that you don't usually need to worry about your supply also isn't really in line with what we're going for, to my understanding; the point's largely to encourage play of small to mid size ships, and a concept that's been underpinning shiptest from the start has been scarcity and needing to work around it creatively. Capping the Osprey to one per round will of course help a lot with the population of other ships but it's still a fact that an Osprey can completely steamroll pretty much anything else if it needs to and thanks to having both cargo and unrestricted RnD could access basically any equipment it wanted. Switching RnD to a science focus and putting a moderate limit on cargo by nixing the selling pad means cargo still has something to do but needs to think hard about budget before buying out the entire catalogue, and RnD can't just gear the entire ship up with top-end equipment in every department given enough time. It also gives the Osprey a reason to trade with other ships, since now there's a good chance they'll actually have something you don't.
> 
> That, and I really want to see how the no-selling-pad experiment pans out, because afaik it hasn't been tried before on any other ship. I'll put the selling pad back if it doesn't work well after being TMed for a while, but for now I've given the QM significantly more money to work with (just enough to cover the purchase of an AME setup, or buy deep core drills if you don't feel like having an engine).

 I really aint a fan of this yet as  it heavily nerfs a big beloved ship in an unpolished and untested way, which i dont think is a good way to test new things if this does end up getting merged though i hope its at least thoroughly testmerged first and decided on if its good.

**Comment by Apogee-dev** [comment]
> i hope its at least thoroughly testmerged first and decided on if its good.

Yeah, that's the plan. I don't want this merged until it's been tested extensively and I have plenty of in-game feedback to work with, at which point i'll either leave it in its current state (if that worked out during the TM period) or put the cargo pad back.

**Comment by UltraNumeron** [comment]
Yeah either way i think this would honestly be better to be better tested as a concept in a new ship rather then taking one of the biggest and most played ships and  driving a nerf rocket through it full of untested, unpolished concepts.

**Pull request merged**
