### PR TITLE
re:re:Materials

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Resprites materials yet again

Sprites are by Imaginos and a few others with a few adjustments

https://github.com/tgstation/tgstation/pull/72652 Ported from here

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

image

image
image

I also think colors are prettier than mine anyhow

## Changelog

:cl: PestoVerde, Imaginos, Wallem
add: one more material resprite couldnt hurt
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
A real wizbanger with thjs one.

**Review by Imaginos16 — APPROVED** [review]
Explicitly consented to it before, I'll make it clear as well that I approve.

**Comment by Martinpachu** [comment]
image
this happened when i dug up some white sand in a sand planet

**Comment by ghost** [comment]
Coal also does not have a sprite.

**Comment by rye-rice** [comment]
Above have been fixed

**Comment by BarteG44** [comment]
Iron, titanium and titanium glass are way too simmilar to eachother. They're the exact same texture with a slightly diffrent shade making them really hard to distinguish at a glance without having the other ones around as a reference

**Comment by ghost** [comment]
Silver, plasma, uranium, iron ores have no sprites.

**Comment by Calyxman** [comment]
All raw ores don't have a sprite with this being TMed.

**Comment by rye-rice** [comment]
Fixed the ores because i missed a single line. Also made the metal and titanium sprites resemble their older sprite and have their older pallete which should help distinguishing them i think.

**Comment by ZephyrTFA** [comment]
The uranium is a downgrade imo, but everything else is an objective upgrade

**Pull request merged**
