### PR TITLE
Blank Forms: For Real This Time

### PR DESCRIPTION
**Pull request by meemofcourse**
Have I ever told you the definition of insanity?
## About The Pull Request
TODO:
* [ ] Figure out how to print img content stored locally
* [ ] Independent
* [ ] CLIP
* [ ] Inteq
* [ ] PGF
* [ ] SUNS
* [ ] SolCon
* [ ] Cybersun
* [ ] Nanotrasen

## Why It's Good For The Game
If people are to engage with the paperwork system, the effort required to do so should not require you to learn markup website coding.

## Changelog

:cl:
add: Photocopiers now have free-to-use forms for multiple factions. Sapient-kind is subservient to checkboxes.
code: SVGs icons for most of the playable factions.
/:cl:

### CODE REVIEW

**Comment by Anticept** [comment]
This would also be handy as hell to have as a template program in NTOS.

**Comment by goober3** [comment]
blank forms coming 2021

**Comment by meemofcourse** [comment]
> blank forms coming 2021

i am a slave to markdown ink slingers

**Comment by Sun-Soaked** [comment]
poke poke

**Comment by meemofcourse** [comment]
i will kill you

**Comment by thgvr** [comment]
Running on a year old, reopen this if you want to continue it

**Pull request closed without merging**
