### PR TITLE
Updates the Syndicate maid costume color palette and adds a shemagh to the loadout.

### PR DESCRIPTION
**Pull request by Ebin-Halcyon**
## About The Pull Request
What it says on the tin, I redid the old syndicate maid sprites when I was a less experienced spriter, now I am slightly better.
Also adds a shemagh sprite I had lying in my sprites folder into the game, was originally for the IRMG, but I thought "Hey why not." and made it available in the loadout.

Spin around

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

Updated color palettes that look nicer :]

## Changelog

:cl:
imageadd: The Syndicate maid outfit has been given a nicer color palette
imageadd: A shemagh has been added to the loadout for those tactical operators.
/:cl:

### CODE REVIEW

**Comment by Calyxman** [comment]
Speedmerge immediately.
Also tacticool ''operator'' IRMG gear when

**Comment by ZephyrTFA** [comment]
Will merge once conflicts are resolved

**Comment by Ebin-Halcyon** [comment]
I think something fucked up my side, hold off for now.

**Comment by Ebin-Halcyon** [comment]
Indeed it did fuck up catastrophically. I'll re-pr it in a minute.

**Comment by Ebin-Halcyon** [comment]
Seems the jungle paradise DMM has cursed me and won't let me do anything. I'll open this again once it's resolved.

**Pull request closed without merging**
