### PR TITLE
Going Green: Lifebringers & More!

### PR DESCRIPTION
**Pull request by Sun-Soaked**
## About The Pull Request
An ongoing rework of lifebringers, alongside some general plant-related tweaks and changes.

- Adds Genesis serum, a lively and expensive chemical that creates plant life when splashed onto flat, nonabsorbent surfaces! Turn your ship into a garden, or finally do some real terraforming as the Lifebringer pod. 
- Adjusts the lifebringer vault slightly, adding a bit of flavoring, mushrooman spawns, and the new Vault Biogenerator.
- Adds several new surface plants, many of which contain highly useful chemicals.
- Adds harvestable plants to jungle worlds. Forgive me for the spammy implementation.
- Adds the vault biocultivator, a powerful biogenerator which contains additional recipes that allow for generation of random seeds and synthesis of Genesis serum.
- Slightly reworks the Mushrooman species: 
       -Mushroomen now begin rapidly dying when they are starving and become hungry more quickly, but heal rapidly when overfed.
       -Mushroomen are resilient to pressure and stamina, and slightly resilient to brute.
       -Mushroomen are now significantly weaker to fire and burn damage.
       -Mushroomen can now have variable cap color. Rejoice!
       -Mushroomen can now wear masks. 
- Slightly reduces the Mushroom Punch windup, it was almost impossible to hit on moving targets before.
- Adds random flora and seed spawners, used by Genesis serum and the Biocultivator.
- Adds a fungal lifebringer spawner, implements it in the tweaked lifebringer ruin.
- Allows several base-emagged drink/chem dispenser varieties seen in ruins to drop their boards- they were completely useless before, as they were in hard-unpowered areas and would be destroyed completely when deconstructed.
- Allows Snail and Robot mutation toxin to appear in game. Beware the taste of Agent S.
- Slightly alters the flavor text of Wittel, making it more apparent that it's a liquid mineral solution.
- Adjusts the name of ferns to "royal ferns", referencing their rich purple color, as their cave fern title made no sense without being hardlocked to lavaland.

I'm hoping to eventually set up a full-sized ruin containing the podpeople as an endpoint, which is the main reason this is still a draft.

## Why It's Good For The Game
Plant good, taste like fun

## Changelog
:cl:
add: Adds Genesis Serum, a plant-creating chemical and powerful fertilizer.
add: Reworks Mushroomen into gluttonous, tanky boxers who are charged to protect their podperson brethren.
add: Several new surface plants, containing a variety of useful substances. Implements them across existing planets.
add: An extremely janky harvestable plant implementation on jungles.
add: Random flora and seed spawners, used in Genesis and the Biocultivator.
add: A fungal Lifebringer spawn, implemented in the altered Lifebringer ruin.
tweak: alters the Lifebringer ruin slightly to fit with the new biogenerator-based progression chain.
tweak: Corpse Flowers now once again contain formaldehyde, and also now contain liquid gibs and zombie powder.
tweak: Jupiter Cup also now contains telsium. The gods demand, and I comply.
tweak: Genesis Serum can now be found in World Peas.
tweak: slightly alters the Flavour text of wittel.
tweak: slightly alters ground sprites of ferns, and renames their formal classification to "royal fern"
tweak: allows snail and robot mutation toxin to appear ingame.
tweak: adds a little more to puce's desc text.
tweak: specifies what skeleton's Boon protects against in it's chemical desc.
balance: allows several alternate versions of chem and drink dispensers to be deconstructed.
balance: eliminates unextractable chems from Spaceman's Trumpet and Jupiter Cup, making them extractable reagent genes instead.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
genesus serum

**Comment by Sun-Soaked** [comment]
this is ready for testmerge btw, it'll stay drafted till I finish the podperson ruin, but I made a slightly altered one in the meantime

**Comment by Sun-Soaked** [comment]
git, could you chill a bit, it's a preliminary draft

**Comment by sunofang** [comment]
Thumbs up. Very good. Cant wait to turn an ice planet into a jungle one.

**Pull request closed without merging**
