### PR TITLE
Should fix infinite ion storms

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
as title

## Why It's Good For The Game
bugfix

## Changelog

:cl:
fix: Ion storms are no longer infinitely firing once you fly through them
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
Wait, doesn't this already get done by this? https://github.com/shiptest-ss13/Shiptest/blob/98751b40e9902deb13febcbdfb6507ef2e856c1f/code/modules/overmap/objects/event_datum.dm#L28-L31

**Comment by Erikafox** [comment]
> Wait, doesn't this already get done by this?
> 
> https://github.com/shiptest-ss13/Shiptest/blob/98751b40e9902deb13febcbdfb6507ef2e856c1f/code/modules/overmap/objects/event_datum.dm#L28-L31

well I guess I found the real issue. The fucking proc wasn't inheriting properly (it was using S instead of Ship). Will update tmmrw

**Comment by MarkSuckerberg** [comment]
gotchya gotchya, take your time

**Comment by MarkSuckerberg** [comment]
bump

**Pull request closed without merging**
