### PR TITLE
Updates the SM sprite to the modern one

### PR DESCRIPTION
**Pull request by Moltovz**
## About The Pull Request
just updates the supermatter sprite to the most up to date one.
image

## Why It's Good For The Game
ugly sprite go byebye

## Changelog
:cl:
tweak: changes the SM sprite: Moltov
Sm sprite by: azlan
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
this is technically the modern BEE sprite :trold:

**Comment by Moltovz** [comment]
> this is technically the modern BEE sprite :trold:

Bee did have it first didn't they

**Comment by Moltovz** [comment]
PR name changed, now nobody wins!

**Comment by ToasterBan** [comment]
oh you also should probably credit azlan for actually making the sprites in the changeling

**Review by triplezeta — APPROVED** [review]
i wish i got to do my own take on the sm sprite but azlan's is excellent and i dont have time.

**Pull request merged**
