### PR TITLE
Adds the Nomad crash site to the rockplanet

### PR DESCRIPTION
**Pull request by Zytolg**
Is the nomad a ship or a faction? I'll leave it to the lore junkies to decide down the line. 

## About The Pull Request

Adds the Nomad Wreck to the ruin lineup of the Rock Planet. 

CrashedShiphehe

Also repaths area/mine/rockplanet to area/ruin/rockplanet. The areas in this file weren't even being used so I might go back and actually make all the rockplanet ruin areas use this file later. All rockplanet ruins bar this new one currently use area/ruin/powered and area/overmap_encounter/planetoid/rockplanet for their areas. Using the default case of ruin/powered for all of your ruins isn't good practice. 

Finally adds a new ship manufacturer decal. I've been _illegally_ having fun brainstorming up an entire new lineup of ships. Furthermore, they = have garnered positive feedback from project managers in the official discord, so I'm confident in doing this here. This ruin is the first in a series of ruin addition that feature these vessels in an unflyable state. Be they wrecks, conversions, legitimate salvage, or otherwise. Introducing **Arrow & Axe** and their Dockyard subdivision. Hopefully a striking addition to the Shiptest universe!

More Arrow More Axe

I have been mapping for Shiptest all week, and my head is still full of a great deal many ideas! This is only the start so be on the lookout for more!

Shoutout to @Imaginos16 for actually spriting out the crappy MSPAINT rendition of the logo. Excellent work as always!

## Why It's Good For The Game

-Ruins are requested, so ruins shall be received. 
-New 7th ship manufacturer to add even more diversity to the game. This one is Military, so expect even more Spartan Vessels. 
---Hammerhead vessel design, Flat-Bow profiles. Prominent nacelles and fishtale sterns. Interiors are asym. and biased port or stbd. (You'll see a complete one that's been converted into a salvage depot for my next PR). 
-New Ship manufacturer decal courtesy of @Imaginos16 to really drive that home.
-Repathing the rockplanet.dmm areas out from under ../mine (and they were unused!) into ../ruin to bring it in line with everything else. 

## Changelog

:cl:
add: New Rockplanet Ruin
add: New ship manufacturer sprites. 
code: Repaths areas in rockplanet.dmm to be in line with other ruins. Starts using rockplanet.dmm.
code: Code support for Arrow & Axe Dockyard sprites. 
/:cl:

### CODE REVIEW

**Review by spockye — CHANGES_REQUESTED** [review]
image

These are OBJ stairs, not turf stairs. they're used for Multi-z, and dont worm normally. 


image

get what your going for, but im not sure it's such a good idea. i'll come back to you on this later.


image

WE HAVE PEBBLES?



image

(ULTRA NITPICK) Missing corner decal :)


image

mabye make a couple of the walls Rusted? just to spice it up

image

try to not leave corners like this. looks a bit off with out walls

------

this is a pretty ruin. good work!

**Review by spockye — COMMENTED** [review]
i'll give this a TM next uptime. if everythings fine i'll merge

(shout at me if i forget- actually just shout at me before next uptime)

**Review by spockye — CHANGES_REQUESTED** [review]
image

dont do this. it doesnt work!
everything reverts back to the original icon state on loading.

**Review by spockye — APPROVED** [review]

**Review by Latentish — DISMISSED** [review]
You need to add this ruin to the RuinCatalogue

**Comment by Latentish** [comment]
Ruin does look cool though.

**Pull request merged**
