### PR TITLE
remaps the geneva-class rescue vessel ship

### PR DESCRIPTION
**Pull request by ghost**
## About The Pull Request

remaps the geneva-class rescue ship to fix issues with it and re-balance

- removes chemistry dispenser, adds a chemistry dispenser board
- removes oil engines, adds two oil engine boards; replaced engines with ion thrusters
- removes two normal medkits, one combat medkit (two normal), one oxygen depravation medkit; one toxin medkit; three defibrillators (one normal, one wall-mounted left); one surgical duffel bag (one advanced, one normal left)
- removes the ore silo
- removes the command spacesuit and one of the normal spacesuits (two left)
- swaps mining to the left and crew use to the right 
- moves crew quarters more towards the back so it's out of the way
- swaps walls and windows for plastitanium stuff
- more misc sitting areas since people said that geneva wasn't facilitating a lot of RP

genevaimg2
genevaimgareas

- [x] I affirm that I have tested all of my proposed changes and that any issues found during testing have been addressed.

## Why It's Good For The Game

ultimately fixes the oil thrusters breaking all the time; fixes issues where the built ion thrusters would fail to re-scan at the helm console; rotates the engines in the right direction

removes bunch of duplicate lockers

re-balances the abundance of medical supplies the ship gets for a 7 person ship

more room to handle more patients and visitors

match aesthetic of other syndicate vessels

## Changelog

:cl:
tweak: the geneva-class has been remapped and slightly expanded.
balance: rebalanced the geneva-class rescue ship's on-board medical supplies stock
fix: fixes the geneva-class rescue ship's engines
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
not sure what the regex failure is 🤷‍♀️ going to move this to ready for review and if someone cleverer than i knows, i can re-run the checks to try and fix the issue

**Comment by Erikafox** [comment]
firefox_0KabiVrVLO
check the door to the crew quarters for doubled firelocks. 
You might also want to swap the airlocks out for a different path, the airlock/centcom ones apparently have phobia effects, try airlock/hatch

**Comment by ghost** [comment]
> firefox_0KabiVrVLO check the door to the crew quarters for doubled firelocks. You might also want to swap the airlocks out for a different path, the airlock/centcom ones apparently have phobia effects, try airlock/hatch

thank you!!!

**Comment by Latentish** [comment]
image

**Comment by ghost** [comment]
> image

i used the little half-tile firelocks and did two per tile since the old geneva had those, which i think is what's causing the error; is there a different way i should be applying them/just use the full-tile firelocks instead?

**Comment by ghost** [comment]
nevermind, i am stupid and just found the offending firelock lol

**Comment by Latentish** [comment]
This looks good I'd like to see it TM'd.
I don't have any issues with it and the Geneva looks nicer than before.

**Review by Latentish — CHANGES_REQUESTED** [review]
image
This decal needs to be fixed.

image
Please don't use these curtains, they look like something went wrong rendering them.

image
Please replace your tinyfans with atmos holoprojectors.

image
Lifeform stasis units are incredibly powerful, please limit this to the singular on in the medbay. The sleepers could also be nerfed to only one.

image
I don't know that this ship needs and emag. Let alone an infinite emag.

image
This gives the ship 2 combat defibs and an advanced health analyzer which tells you exactly where all the fractures are. While I get this is the funny med ship, it also has a syndicate duffelbag with advanced surgery tools in it, and c4 charges.

image
image
image
Overall the gear on this ship is overtuned to a very extreme degree. You need to cut it back by like half.

image
This bathroom could be made to be a bit prettier.

image
This could as well.

image
More clutter and machines would do well overall, especially here.

**Comment by SweetBlueSylveon** [comment]
image

**Comment by Latentish** [comment]
THAT CLOSE WAS A MISCLICK I SWEAR ON GOD.

**Comment by ghost** [comment]
top image in sdmm is the most recent changes

gear list:
- 1 tox medkit, 1 normal medkit, 2 oxy deprivation medkits
- 1 normal surgery tool bag, 1 syndicate surgery tool bag
- 1 wall-mounted defib, 1 defib
- 1 sleeper
- 1 lifeform stasis unit
- 2 operating tables
- 1 hypo mk 2 kit
- 1 autosurgeon
- 1 chemmaster
- 1 RPD

circuitboards:
- 2 oil thruster boards
- 1 medical protolathe
- 1 all-in-one grinder
- 1 chemical heater
- 1 RnD console
- 1 limb grower
- 1 biogenerator

removed:
- 2 pod people seeds
- 1 chem dispenser
- 1 advanced mining scanner
- 1 bag of rescue charges (it's just c4)
- 1 set of science goggles
- 1 cryptographic sequencer
- 1 sleeper
- 2 lifeform stasis units
- 1 combat medkit
- 1 combat defib
- 2 EVA hardsuits, swapped with the scarlet ones
- spare headsets

**Comment by Latentish** [comment]
We can TM this one again, but please update the image.

**Comment by Latentish** [comment]
image
The blood packs are not accessible from inside the OR. But otherwise much better.

You also need to give them space suits and probably a jetpack or two (not attachable) so they can actually do rescues. and leave their ship.

**Comment by Zevotech** [comment]
we have scarlet hardsuits now, which are weaker versions of the bloodreds. Could use those.

**Comment by BarteG44** [comment]
The holofields do not work.
image
(image related)

**Comment by ghost** [comment]
fixed the holoshields; double-checked that the hardsuits available are scarlet subtypes + added 2 harness jetpacks into the suit storage units. let me know if there's a better suit/jetpack subtype for use here

**Comment by BarteG44** [comment]
the professor's office looks pretty bland still. i'd add some siding to the floor at least

**Comment by Latentish** [comment]
I'm very sorry, you've put in a lot of good work for this ship and made it considerably better than it was before. However we voted as maptainers to remove the geneva as a whole regardless of updates. I apologize for this happening so late in the development process.

**Pull request closed without merging**
