### PR TITLE
Gun DealerShip - An Admin-Only Event Ship

### PR DESCRIPTION
**Pull request by coleminerman**
## About The Pull Request

This is a new ship, a variant of the Li-Teg heavily modified to be a mobile arms dealer storefront. Only possible to be spawned by admins since it's so loaded with arms and ammunition that anyone spawning one would just be able to completely steamroll anyone and anything else on the server. Designed for admin events, for the admin spawning the ship in question to roam the system selling guns. This ship was requested to be made for exactly that purpose by fellow admin @Valorium#3022.

## Why It's Good For The Game

Mostly summarized above. Admin-only event ship for admin events, specifically events in which the admin in question or a trusted player chosen by them RPs as a travelling weapons dealer selling their wares, both lethal and nonlethal, throughout the system. Nothing more, nothing less.

## Changelog
:cl:
add: Added the creatively named "Admin Gun Dealer Ship"
add: Added a json that actually makes it function
/:cl:

Screenshot 2022-05-17 203743

### CODE REVIEW

**Comment by coleminerman** [comment]
Seems I may have accidentally @ed a random from somewhere else in github while trying to credit the idea. I hope that doesn't become an issue.

**Comment by ZephyrTFA** [comment]
local lizard fails at github

**Comment by ilikesaying** [comment]
man's gonna get turned into boots

**Comment by Apogee-dev** [comment]
Given it's an admin spawn ship this isn't as strictly necessary as for normal ships, but you might still want to add a prefix and namelists to the config. Also, please add a screenshot of the map to your PR.

**Comment by Apogee-dev** [comment]
Map looks good in the preview, however you might want to take a second look at your areas, the central hallway doesn’t have any fire alarms or air alarms in it so those firelocks behind the office will never actually trigger. I’d just make both halves of the hallway the same area or merge the central portion with the armory area. The armory also does not have an APC and you have some redundant air & fire alarms on the starboard side of the armory.

One last note is that you're using the default HoS and Security Officer job titles with Inteq outfits, but Inteq doesn't use those titles in the lore. You should ask Halcyon or Joe on the discord about Inteq ranks- these two are Vanguard and Enforcer respectively, though there may be lore reasons not to have a Vanguard on a ship operated by someone else.

**Comment by coleminerman** [comment]
New update should fix all issues listed in the comments by @Apogee-dev, as well as a few that I noticed on my own while going back over this, more specifically a few missing firelocks. Will update image in a moment to reflect the changes.

**Comment by Apogee-dev** [comment]
Looks good. My only remaining note is that you have a few instances of overlapping wallmounts (usually tube lights on the same tile as an air or fire alarm). These aren't all avoidable but it'd be ideal if you could avoid having multiple wallmounts on the same wall face as much as possible.

**Comment by Fikou** [comment]
sure

**Pull request merged**
