### PR TITLE
The CentCom-ening: Shiptest Edition

### PR DESCRIPTION
**Pull request by meemofcourse**
## About The Pull Request

imagen
Ports the following pull requests:
* https://github.com/tgstation/tgstation/pull/57023
* https://github.com/tgstation/tgstation/pull/60414
* https://github.com/tgstation/tgstation/pull/63029
* https://github.com/tgstation/tgstation/pull/65794
* https://github.com/tgstation/tgstation/pull/70226

This takes out the wintercoats out of misc.dm into their own file, and adds a CentCom Wardrobe into the CentCom map.

## Why It's Good For The Game
Adminbus. Some minor clean up is always appreciated.

## Changelog

:cl: PositiveEntropy, tf-4
add: Adds the CentVend inside Central Command! You're now able to vend Central Command clothing items for all your commanding needs!
add: Nanotrasen has added a new outfit for Special Ops Officers to enjoy, instead of a simple leather jacket: The CentCom Officer's Coat!
add: Re-adds the CentCom Official's suit, making it the default clothing option for CentCom Officials! The turtlenecks have instead been made to be the standard ERT uniform.
imageadd: Thanks to a collaboration between the frontier sector and the core sector, the parade jackets now boast new and varied apperances for all to enjoy, with a new parade jacket releasing for the Head of Security!
imageadd: In no short effort than the finest of tailors, the captain's hat, the centcom hat, the captain's jumpsuit and the captain's carapace now have finer gold trims and the finest quality leather available, making them more vibrant for all!
expansion: To utilize the new variants, simply alt-click a parade jacket, or a centcom commander coat. You can also obtain a Head of Security parade jacket by simply accessing the Head of Security's closet!
imageadd: In no short effort of our best tailors, every Central Command outfit have been either redesigned or reshaded! All of them!
/:cl:

### CODE REVIEW

**Review by rye-rice — APPROVED** [review]
https://www.youtube.com/watch?v=W_HUdf89hI8

**Comment by spockye** [comment]
hot

**Review by rye-rice — DISMISSED** [review]
Hold on, on a second look:

Some of these look like the old Imaginos ones instead of the colorful 5th iteration ones, are you sure you ported this in order?

Also, it seems like you copied some redundant sprites, like the captains formal uniform and marine uniforms, which we have already

**Comment by meemofcourse** [comment]
i plead silly to all charges. you're right though. i'll fix it later

**Review by Imaginos16 — CHANGES_REQUESTED** [review]
You didn't port my PR correctly. Several of the sprites are the unupdated versions of what they should be.

Check solely what has been included in

https://github.com/tgstation/tgstation/pull/70226

**Review by MarkSuckerberg — APPROVED** [review]
so fucking real

**Review by Imaginos16 — APPROVED** [review]
Better

**Pull request merged**
