### PR TITLE
Updates EVA suit sprites.

### PR DESCRIPTION
**Pull request by zestybastard**
## About The Pull Request

Resprites the basic EVA space suit to have a little more purpose and clarity.

## Why It's Good For The Game

One of the game's more popular hardsuits now looks better.

## Changelog
:cl:

imageadd: New sprites for the EVA suit.

/:cl:

image

### CODE REVIEW

**Comment by Zevotech** [comment]
:videogames:

**Comment by zestybastard** [comment]
> :videogames:

hardsuit games ! !

**Comment by ToasterBan** [comment]
uhmmm AKSHUALLY it's a SOFTSUIT anmd not a HARDsuit

**Comment by MarkSuckerberg** [comment]
@triplezeta

**Review by triplezeta — APPROVED** [review]
still unsure about how this will look ingame but if it looks off i can just redo all of your work again :trollface:

**Review by Kapu1178 — APPROVED** [review]

**Pull request merged**
