### PR TITLE
Ports 'Ports 'Pointing at something on yourself now shows the item''

### PR DESCRIPTION
**Pull request by Skies-Of-Blue**
## About The Pull Request

Ports https://github.com/BeeStation/BeeStation-Hornet/pull/8553, which is in turn a port of https://github.com/tgstation/tgstation/pull/68642

## Why It's Good For The Game

Good for rp, allows you to visually show off items without relying on chat. Previous to this, it visually looked like you were pointing to yourself, which could very easily lead to confusion.

## Changelog

:cl:
add: pointing at something on yourself now shows the item
/:cl:

### CODE REVIEW

**Comment by BarteG44** [comment]
i'm not a fan of how the thought bubble looks but the feature's neat

**Review by Imaginos16 — CHANGES_REQUESTED** [review]
you fucked up the holofield animations with an accidental paste

**Review by Imaginos16 — APPROVED** [review]
lol nevermind

**Review by MarkSuckerberg — APPROVED** [review]
seems good! would like a testmerge first but the code seems good

**Comment by goober3** [comment]
image
hello!! hi!! i believe this PR might be breaking item highlights in backpacks. please test this on a local

**Comment by Skies-Of-Blue** [comment]
Whoops, let me fix that up real quick

**Comment by Skies-Of-Blue** [comment]
That should resolve it!

**Review by rye-rice — APPROVED** [review]
Was this testmerged?

**Comment by Skies-Of-Blue** [comment]
I believe it's been testmerged for the past two weeks now, maybe a little under.

**Pull request merged**
