### PR TITLE
[MDB Ignore] Convert all `/turf/open/space/basic` to `/turf/open/space`

### PR DESCRIPTION
**Pull request by martinlyra**
## About The Pull Request

Apparently the existence of `/turf/open/space/basic` is a bit unintended and causes improper initialization. Possibly causing some issues related to the turfs being initialized improperly.

Since there were some interest in addressing this, so I did a draft PR meant to address this possibly-but-also-possibly-not-a-problem.

## Why It's Good For The Game

See @tmtmtl30's assertion down below: https://github.com/shiptest-ss13/Shiptest/pull/1262#issuecomment-1166377753

## Changelog
:cl:
tweak: Addressed improper use of a space turf type on some maps
/:cl:

### CODE REVIEW

**Comment by martinlyra** [comment]
In case anyone wants to know more of how the map-merge went, here is the mapmerge2 log:
```Powershell
PS D:\Shiptest\tools\mapmerge2> & '.\Run Before Committing.bat'
Converting map: _maps/map_files/generic/CentCom.dmm
Converting map: _maps/RandomRuins/RockRuins/rockplanet_cult.dmm
Converting map: _maps/RandomRuins/SpaceRuins/astraeus.dmm
Converting map: _maps/RandomRuins/SpaceRuins/corporate_mining.dmm
Converting map: _maps/RandomRuins/SpaceRuins/cryocontainment.dmm
Converting map: _maps/RandomRuins/SpaceRuins/dangerous_research.dmm
Converting map: _maps/RandomRuins/SpaceRuins/excavator_DK.dmm
Converting map: _maps/RandomRuins/SpaceRuins/Fast_Food.dmm
Converting map: _maps/RandomRuins/SpaceRuins/forgottenship.dmm
Converting map: _maps/RandomRuins/SpaceRuins/hellfactory.dmm
Converting map: _maps/RandomRuins/SpaceRuins/lab4071.dmm
Converting map: _maps/RandomRuins/SpaceRuins/oldstation.dmm
Converting map: _maps/RandomRuins/SpaceRuins/power_puzzle.dmm
Converting map: _maps/RandomRuins/SpaceRuins/provinggrounds.dmm
Converting map: _maps/RandomRuins/SpaceRuins/scav_mining.dmm
Converting map: _maps/RandomRuins/SpaceRuins/spacegym.dmm
Converting map: _maps/RandomRuins/SpaceRuins/whiteshipdock.dmm
Converting map: _maps/RandomZLevels/snowdin.dmm
Converting map: _maps/RandomZLevels/speedway.dmm
Warning: key 'ld' is missing either a turf or area
Warning: key 'rA' is missing either a turf or area
Warning: key 'Az' is missing either a turf or area
Warning: key 'ld' is missing either a turf or area
Warning: key 'rA' is missing either a turf or area
Warning: key 'Az' is missing either a turf or area
Converting map: _maps/shuttles/shiptest/chapel.dmm
Converting map: _maps/shuttles/shiptest/engineeringmess.dmm
Converting map: _maps/shuttles/shiptest/radio_funny.dmm
Press any key to continue . . .
```

**Comment by Ebin-Halcyon** [comment]
Might wanna put MDB ignore.

**Comment by tmtmtl30** [comment]
So -- /turf/open/space/basic is a space subtype that's set as the world default turf type. This means it's what new z-levels are automatically filled with. It intentionally does nothing in New(), so that things init faster.

However, you can't actually normally change turfs to /turf/open/space/basic in normal gameplay. This is because you (are supposed to) change turfs using the proc ChangeTurf(). ChangeTurf() has an explicit check that prevents you from changing turfs to /turf/open/space/basic -- it changes them to /turf/open/space instead. This means that maps that contain /turf/open/space/basic actually end up containing /turf/open/space when they're loaded in. I still don't want maps to use /turf/open/space/basic, because it's strange and confusing to have some maps using /turf/open/space and other maps using /turf/open/space/basic. I'd rather everything just use /turf/open/space, since that's what actually gets instantiated in practice.

**Comment by tmtmtl30** [comment]
Looking into it some more, I think you want to keep /turf/open/space/basic on Centcomm, since it gets loaded in differently. Also, wait, this might have an impact on ruin integration test run times..? I'll have to look into this a bit more.

**Comment by martinlyra** [comment]
Currently busy with life and family, so my correspondence will be slower than usual. But when I get the energy and chance to, I'll address these merge conflicts and revert the changes to CentCom.

**Pull request merged**
