### PR TITLE
The Lizardening Part One (And Friends)

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
This PR changes a lot of sprites. It's honestly too much. Namely:

- Explorer Equipment + Prototype
- Syndicate clothing
- Digitigrade lizard legs
- A new tail from Halcyon.
- Magboots from Zeta. Originally PR'd to tgstation.
- Colored (not greyscale! Ha Ha!) jumpsuits from Imaginos.

Heavy inspiration from the work of Imaginos, Halcyon, Mqiib, and 2cents#8442 for the original leg-work. (Haha, get it?)
The new digitigrade sprites started as a twinkle in the eye of Mqiib, for yogstation(?) After myself and Halcyon saw those, an epihpany struck. Perspective makes things cool and digitigrade perspective was BAD.

I'll include a collage image of the new sprites if it's needed later.
Preview below:

image
## Why It's Good For The Game
lizard,
Death of Codersprites
## Changelog

:cl:
add: New Digitigrade lizard sprites.
add: Various syndicate and mining clothing resprites.
add: Sarathi can now have an incredibly large tail.
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
lizard :lizard::+1:

**Comment by SapphicOverload** [comment]
lizar

**Comment by Mqiib** [comment]
Original spriter of the first iteration of the new legs before I and then halcyon messed with then was 2cents#8442 on discord.

**Comment by Moltijoe** [comment]
God bless replacing codersprites. Would be interested to see a screenshot of the new legs and how the jumpsuits look

**Comment by thgvr** [comment]
PR Body updated with an image.

**Pull request merged**
