### PR TITLE
SEV Lugol-class GEC Engineering Project

### PR DESCRIPTION
**Pull request by goober3**
## About The Pull Request

1400gecs

400realgecs

300areagecs

Adds a new GEC ship, designed for facilitating questionably safety-dubious engineering projects. Features a full atmospherics department (piped by @BarteG44!) and a large, depressurized construction area, separated from the rest of the ship via two AACs. The secure storage room within the construction area contains various gas tanks, a crate of materials, a supermatter shard, a crate containing thermomachine boards, tesla coil boards, rad collector boards, grounding rod boards, emitter boards and SMES boards, four field generators, a tesla generator, and a full singularity generator. 

Other gear includes an RCD crate in cargo, containing three industrial RCDs, a mining crate, radiation healing supplies, and engineering RND.

This PR also adds airless techfloor tiles.

## Why It's Good For The Game

This ship replaces the Rube Goldberg and Kugelblitz's gimmicks, two ships that were Eradicated and Deleted and Removed without a replacement.

## Changelog

:cl:
add: The SEV Lugol-class GEC Engineering Project, a large engineering vessel.
add: Airless techfloor tiles
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
cant wait for the Teslamatter 2 Electric Boogaloo

**Comment by goober3** [comment]
not sure why the compile check is failing. epic fail!

**Comment by Erikafox** [comment]
` _maps/shuttles/shiptest/syndicate_gec_lugol.dmm:5362:error: expected }
_maps/shuttles/shiptest/syndicate_gec_lugol.dmm:5362:error: expected )`

You probably accidentally did a s var

**Comment by Erikafox** [comment]
image
random d

**Comment by meemofcourse** [comment]
singular typo, entire pr is ruined

**Comment by Erikafox** [comment]
firefox_3WOUsD8HUo
unplayable

**Comment by BarteG44** [comment]
> firefox_3WOUsD8HUo unplayable

Wonder if that was me lol

**Comment by goober3** [comment]
> image random d

epic,m fail

**Review by Erikafox — CHANGES_REQUESTED** [review]
StrongDMM_Dw8Vj225O4
Leave a note warning about setting singularities up on ships
StrongDMM_yhkfk15XBO
render the terminal under the catwalk or remove the catwalk
StrongDMM_UQNikrRZVe
layering issues with railings and chairs
StrongDMM_GS1xfSWjrE
replace the pizza with pineapple and give them a few boxes of it
StrongDMM_6Win3ViqPN
bar needs an windoor
StrongDMM_e3KPzzfVdH
these need to have 2 vents in them to cycle at a passable speed.

The bridge needs a holopad, the emergency bar holopad needs to be closer to the bar, replace the one in it's current spot with a normal holopad for calls. 
image
Make sure ALL of these meters target the right pipe layer.
StrongDMM_dUnOcPBt9m
Rename this to something because I don't think booze is a condiment.
StrongDMM_gPVEPKWkzB
Terminal Layering
Consider adding a secure safe (/obj/item/storage/secure/safe/intel) to the CE's room.
StrongDMM_IlAUPbm2zx
These lockers will automatically populate, check your item list to make sure you don't have an absurd amount of something now. Or just use a varedited secure closet.
image
Add another catwalk so the three way is visible.
image
This would be better in the engineering storage.

The ship could also use some conveyor belts in a crate. That'd be funny.

**Comment by goober3** [comment]
> These lockers will automatically populate, check your item list to make sure you don't have an absurd amount of something now. Or just use a varedited secure closet.

they're all set to Populate 0, I was having issues with Var Edited Secure Closets starting unlocked, for whatever reason.

**Comment by Erikafox** [comment]
Oh cool. Okay

**Comment by goober3** [comment]
I think I addressed everything I could in the Review. cannot find a way to make terminals (nor layer adapters!) layer under catwalks. not sure what's up with that! I don't see the issue with the Bridge Chairs, please elaborate on that. I would add a secure safe to the CE office if wall safes weren't missing an Icon, for whatever reason. secure safes are invisible in-game. odd!

**Comment by Erikafox** [comment]
> terminals (nor layer adapters!) layer under catwalks. 

try setting the layer of the specific tiles to higher than what the terminal should spawn in as

>I would add a secure safe to the CE office if wall safes weren't missing an Icon, for whatever reason. secure safes are invisible in-game. odd!

Add one anyways, bitches love the invisible safe (and I don't think patching it in later will be painless) ((You could also try manually setting it's iconstate))

> I don't see the issue with the Bridge Chairs, please elaborate on that.

They clip slightly OVER the railings, but you want them layered UNDER for the vertical effect

**Comment by goober3** [comment]
> try setting the layer of the specific tiles to higher than what the terminal should spawn in as

tried this. didn't work! unfortunately.

> Add one anyways, bitches love the invisible safe (and I don't think patching it in later will be painless) ((You could also try manually setting it's iconstate))

done. I tried setting its iconstate already, couldn't find the wall safe sprite, anywhere! might've been removed in #1630. or I might just be blind.

> They clip slightly OVER the railings, but you want them layered UNDER for the vertical effect

ooh, right. I see. the chair layering is intentional, the bridge is supposed to be Above, not Below. though I see how you could interpret it as Sunk.

**Comment by BarteG44** [comment]
>Make sure ALL of these meters target the right pipe layer.

I did that part and I'm pretty sure that i set the proper layer for all of them. At worst maybe the waste and fuel meters may be still on layer 3 as i did those last

**Review by spockye — COMMENTED** [review]
image
flying light. The linings also look a bit weird

image
please try to avoid overlapping wallmounts (even if they are on opposite sides)

**Comment by Erikafox** [comment]
dreamseeker_u4ZU0ieiIt
You're using inconsistent wall types. If you want plastit reinforced please make a proper construction - deconstruction cycle + type for them.

**Comment by BarteG44** [comment]
I suggest adding a tool vendor and perhaps engi and atmos wardrobes

**Review by Erikafox — APPROVED** [review]

**Pull request merged**
