### PR TITLE
Pixel shift 2

### PR DESCRIPTION
**Pull request by ritorizo**
## About The Pull Request

This PR allow you to pixel-shift all pulled object/mobs (/atom/movable instances to be exact).
It also allow you to unpixel-shift object (everything not mob) by slapping them with the "*slap" emote.

Cool things to note : 
 - The shifting stays between construction stages of machine (for most machine but there could be exceptions).
 - Also works on mobs (including humans)
 - Everything that is not a mob stay shifted when moving. 

## Why It's Good For The Game

Ultra high level RP of moving stuff around and also better building capabilities.

## Changelog

:cl:
add: Pixel-shifting while pulling anything will pixel shift the thing you are pulling instead.
add: You can unpixel-shift stuff stuff by slapping them with the "*slap" emote.
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
I'm not certain I want to see machines pixel shifted into walls and such.

**Comment by Zevotech** [comment]
> I'm not certain I want to see machines pixel shifted into walls and such.

people already build machines on top of walls.

**Comment by thgvr** [comment]
And that's not good either. Something like this means you could make "invisible" movement blockers by shifting machines far over.

**Comment by ritorizo** [comment]
Right now the shifting limit for everything is 16 pixel but we could make it smaller for dense object.

**Comment by BarteG44** [comment]
Man i REALLY want this to be merged already

**Comment by MarkSuckerberg** [comment]
Yes, can you do that? I think eight pixels for dense objects gives a bit of wiggle room while making it obvious that it's blocking the way.

**Comment by ritorizo** [comment]
And done dense object can't pixel shift futher than the passtrough limit (8 pixel).
Sorry it took a while I was on shipbreak.

**Comment by thgvr** [comment]
Literally anything other than slap, please
Ctrl shift
Ctrl alt
I don't care, but slap emote is awful UX.

**Comment by BarteG44** [comment]
> Literally anything other than slap, please Ctrl shift Ctrl alt I don't care, but slap emote is awful UX.

Crowbar on push intent

**Comment by ritorizo** [comment]
I moved it from the slapper to pixelshift+click keybind.

**Comment by thgvr** [comment]
Maintainer team has had some discussions about a bunch of open prs recently, and we decided this change isn't something that we want.

**Comment by BarteG44** [comment]
Let me pixelshift my god damn plant pots onto my god damn tables god damn

**Pull request closed without merging**
