### PR TITLE
Lethal Company 13 - Patch 0.1

### PR DESCRIPTION
**Pull request by TiberianErin**
## About The Pull Request

Changed the statue's AI so it will now move if your character faces away
Created a coilhead (reskin of the statue with sounds included)
Added lethal company suit and helmet with custom sprites

## Why It's Good For The Game

This is the first of many lethal-company inspired changes that will gradually increase in size until we have created the lethal company planet and ship where all of these changes are going to truly come to light.

## Changelog

:cl: TiberianEuan and Ceph
add: Coilhead
add: Lethal Company suit and helmet
tweak: Statue now moves if nobody is facing it
soundadd: Coilhead sproing and attack sound.
imageadd: Lethal Company Suit Sprites
imageadd: Coilhead sprites
/:cl:

credit to my girlfriend for making most of the new sprites and helping me test, i love you lots :D

### CODE REVIEW

**Comment by Martinpachu** [comment]
but why

**Comment by thgvr** [comment]
?

**Comment by thgvr** [comment]
Think you got the wrong repo brother

**Comment by TiberianErin** [comment]
> Think you got the wrong repo brother

no no im not mistaken

this is the shiptest repo

**Comment by Sweettoothart** [comment]
I think what thvgr was trying to say this is an LRP change and wouldn't be accepted because its based on a meme (of lethal company)

**Comment by TiberianErin** [comment]
it's based off of lethal company, not a meme. lethal company is a horror game

**Comment by TiberianErin** [comment]
> I think what thvgr was trying to say this is an LRP change and wouldn't be accepted because its based on a meme (of lethal company)

the only meme items and mobs purely exist in the code as stupid shit for admins to spawn

everything else is planned on spawning like the Coilhead

**Comment by thgvr** [comment]
We're not adding lethal company references

**Pull request closed without merging**
