### PR TITLE
Adds generic RND to all - Testing

### PR DESCRIPTION
**Pull request by Jackriip**
## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
*speen

**Comment by Ms-Mee** [comment]
What in the bloody hell even is this

**Comment by Zevotech** [comment]
the owner of the LRP branch presumably trying to fix RND

**Comment by Zevotech** [comment]
which is pretty based

**Comment by Ms-Mee** [comment]
I suggest you actually read the PR properly

**Comment by ZephyrTFA** [comment]
This changes so many things not related to the title and doesnt even have an actual PR description that I'm closing this.

**Pull request closed without merging**
