### PR TITLE
strong bones for the skeleton army

### PR DESCRIPTION
**Pull request by tiramisuapimancer**
## About The Pull Request
makes plasmemes and skeletons  like milk

i didnt test this but it should work

## Why It's Good For The Game
they are skeletons it makes sense

## Changelog
:cl:
tweak: phorids and skeletons like food with the DAIRY tag now
/:cl:

### CODE REVIEW

**Comment by ToasterBan** [comment]
don't neither of these require food

**Comment by Sylphily** [comment]
the problem?

**Comment by tiramisuapimancer** [comment]
they don't need food no but they can still eat it if they want to

**Comment by ilikesaying** [comment]
plasmamen can't take off their helmets in normal atmosphere else they combust and that's the only barrier

**Comment by MusselMain** [comment]
> plasmamen can't take off their helmets in normal atmosphere else they combust and that's the only barrier

that's why drinking milk isn't essential, also most ships have showers where you can eat/drink/get revived as a plasmaman (the only issue is you cannot breathe, but it's still possible)

**Comment by Sylphily** [comment]
I mean, all this pr does is pretty much make them be able to get a small mood buff?

**Comment by ilikesaying** [comment]
plasmamen can't get fat

**Pull request merged**
