### PR TITLE
click cooldown hud

### PR DESCRIPTION
**Pull request by FalloutFalcon**
## About The Pull Request

A port of this pr
https://github.com/DaedalusDock/daedalusdock/pull/732

Adds a bar to the bottom of the screen that shows click cooldown

https://github.com/user-attachments/assets/8824ba1a-2596-4dcf-ae16-2dafdd380666

## Why It's Good For The Game
I can tell when i can attack next

## Changelog

:cl: FalloutFalcon, Kapu1178
add: New bar above your items to show your attack cooldown
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
credit? https://github.com/DaedalusDock/daedalusdock/pull/732

**Comment by FalloutFalcon** [comment]
oops my bad it needs a real desc as well..

**Review by rye-rice — DISMISSED** [review]
seeing this in game i dont think its the play to have even more shit on the hud, not to mention its kind of out of place, im not sure if players would need to have this information as well?

**Comment by FalloutFalcon** [comment]
> seeing this in game i dont think its the play to have even more shit on the hud, not to mention its kind of out of place, im not sure if players would need to have this information as well?

I think the first part is a little opinion based however its useful for anything that sets a strange cool-down, like a lot of resist style acts use a click cool-down of up to 10 seconds. However the real reason for this is for variable cool-down of melee weapons, think of it as a pre-req

**Comment by generalthrax** [comment]
Pulling activates a cooldown, preventing you from clicking soon after. I'm not sure if this is new or not or if I'm just stupid.

**Comment by FalloutFalcon** [comment]
> Pulling activates a cooldown, preventing you from clicking soon after. I'm not sure if this is new or not or if I'm just stupid.

your silly. this is exactly the type of thing i want this for tho

**Comment by Sun-Soaked** [comment]
> Pulling activates a cooldown, preventing you from clicking soon after. I'm not sure if this is new or not or if I'm just stupid.

this is kind of indicative of why we need this feature, I think @rye-rice

**Review by Sun-Soaked — APPROVED** [review]
code looks good. waiting for rye to respond before merging

**Comment by Sun-Soaked** [comment]
We should make this feature optional, but it feels important enough to merge until someone makes that happen
considering how many players seemed to have 0 idea of how many click cooldowns worked until they saw them visualized

**Comment by thgvr** [comment]
I dunno about optional. It needs better integration into HUD elements which we can't really do right now. Having this is actually a great QOL.

**Comment by Sun-Soaked** [comment]
> I dunno about optional. It needs better integration into HUD elements which we can't really do right now. Having this is actually a great QOL.

a new sprite would help, but till then.

**Comment by FalloutFalcon** [comment]
rye requsted drafting it till i make it a toggle and add alternative sprites.

**Comment by FalloutFalcon** [comment]
i forgot to do that.

**Comment by thgvr** [comment]
something like this definitely shouldn't be a toggle - it's pretty core to how you interact with the game

**Comment by thgvr** [comment]
We can come up with a new asset later as we rework hud elements, this is fine as is and a toggle isn't necessary (we talked about it)

**Pull request merged**
