### PR TITLE
removes red armband from loadout

### PR DESCRIPTION
**Pull request by tiramisuapimancer**
## About The Pull Request
so why exactly did WS have this in loadout when they added it?

## Why It's Good For The Game
we've had exactly one extremely comedic individual use this for exactly what you think and that is one extremely comedic individual too many

## Changelog
:cl:
del: red armband gone from loadout
/:cl:

### CODE REVIEW

**Comment by Sylphily** [comment]
Oh dear, that was horrible planning on ws part

**Comment by Latentish** [comment]
Yikes. Yeah probably a good idea.

**Comment by ValoTheValo** [comment]
literally 1994 by gorg orwells

**Comment by Ms-Mee** [comment]
I am Random Politician and I approve this message

**Pull request merged**
