### PR TITLE
Does Penance So The Ghosts Go Away

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request

"This is AI c-Caldwell - Reporting return of essential station functions to Minya League Installation 'Trifuge' following pirate attack - **///far too long ago///** - All vessels are invited to dock and partake of our services, including an active Ore Refinery, world class bar, and purchasable storefronts **//please come, I'm so lonely///** The Minya League, and myself, would like to extend our gratitude to **///-who else but me?///**. Installation 'Trifuge' is located in orbit of the Star 'Anselhome', at the L5 point of Anselhome and habitable world, 'Hofud'. Noting active travel advisory - Hofud is currently **///nothing but ash left by monsters///**. Independent Vessels are advised to avoid landing until Minya League Ships can deliver disaster relief to the planet **///not that they'll be coming....///**"

 "This message will repeat in approximately 20 galactic standard minutes"

Remaps the shitty outpost 1 (indie space) outpost that I made like 6 months ago. it sucks. Anyone who doesn't think it sucks probably has stockholm symdromed themselves into liking it. Also this one has lore and room for expansion.
It's main features are: 
- Decent amount of maint for outpost antics
- REASONABLE amount of storefronts
-abandoned feel
- bar
- Ore refinery so my holy mandate can be implemented when I decide I'm done with my break.

There are your screenshots.

## Why It's Good For The Game
I'd like the voices in my walls to stop whispering to me about the horrific mistakes I've made. They seem pretty upset about this one.

## Changelog

:cl: Erika Fox
add: Outpost 1 has been remapped into something fathomably less ass. It's a bit smaller, probably, but I'm going to call that a good thing.
add: random number spawner. It's good for hull numbers that shouldn't be static.
imageadd: a really bad sprite for a service directions sign.
add: Another elevator template (coincidentally demonstrating how that system works in code)

/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
:3

**Comment by PrefabQuasar** [comment]
yayyyy :D <the happy smiler

**Comment by meemofcourse** [comment]
stockholm symdromed

**Comment by Valorium-RB** [comment]
Good to hear from you, Erika!

**Comment by Sun-Soaked** [comment]
good :)

**Review by spockye — DISMISSED** [review]
image

 Atmos fuckies

image

unconnected disposals

image

im slaying you

-----

a definite improvement! i'll write you a more in-debth review later on.

**Comment by Latentish** [comment]
A new outpost... Just what I asked for....

**Review by Imaginos16 — APPROVED** [review]
Cute sprite, felt like throwing a token approval for it :3c

**Comment by thgvr** [comment]
I would love to TM this.

**Comment by spockye** [comment]
Will Testmerge this week

**Review by Latentish — CHANGES_REQUESTED** [review]
image
This doesn't look right. IT's hard to tell what you're looking at. I'd say just remove the table.

image
Rename this please.

image
image
These consoles are not linked to the machines at start. You should either pre-link them or leave a multitool for players.

That's all I have for you really. You have some wires to the magical smes under some walls but eeehhhhh. It's the outpost and we don't want players fuckin with it.
This is really clean. Once again you make a good map Erika.

**Review by Latentish — APPROVED** [review]

**Pull request merged**
