### PR TITLE
Kill Xenobio Stuff

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
Removes Xenobiology (minus slimes since they're good fluffmobs sometimes).

## Why It's Good For The Game
cruft. thgvr said they'd get me a therapist if I did this.

## Changelog

:cl:
del: Xenobiology (minus slimes)
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
we outta therapy

**Comment by Xkallubar** [comment]
soul removal team back at it again... It's so OVER!!

**Comment by Erikafox** [comment]
you know it random github user

**Comment by rye-rice** [comment]
YOLO

**Comment by Latentish** [comment]
Let's get this bread.

**Pull request merged**
