### PR TITLE
Adds Outpost Communication consoles to a number of ships

### PR DESCRIPTION
**Pull request by theXDkidoflol**
## About The Pull Request
Adds Express Cargo consoles to a number of ships, which with the outpost TM, will correlate to Outpost Communications consoles. Also gives the Raven a wideband.

## Why It's Good For The Game
Allowing more vessels to interact with outposts should allow not only for those vessels to have more alternatives to R&D, but to allow outposts to have more thorough usage and testing.

## Changelog
:cl:Grey
add: Added Outpost Communication consoles to a number of ships
fix: Gave the Raven-class a wideband radio
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
This is a good pr, but I would like to see pictures of the placements of these consoles. I know it's a lot of them, but could you please add them to a spoiler in your description so we TM it?

**Comment by Sylphily** [comment]
if something breaks, uh blame me

**Comment by theXDkidoflol** [comment]
Should be good now; not sure why it says it's removing the rigger, when it was just renamed in a different PR.

**Comment by Fikou** [comment]
it's not good until it stops removing the rigger

**Comment by theXDkidoflol** [comment]
Unable to continue work on this after being banned from the discord. Apologies.

**Pull request closed without merging**
