### PR TITLE
Ship gravity generator

### PR DESCRIPTION
**Pull request by SomeguyManperson**
## About The Pull Request

Adds support for ship-based gravity generators, ships no longer have gravity by default and need to have an active generator. Currently haven't had it added to maps, but the board is printable at an autolathe.

Planets & the outpost now have a virtual z-wide gravity, allowing landed ships to inherit planetary gravity.

https://github.com/shiptest-ss13/Shiptest/assets/24857008/a6ee357e-265b-4d1f-9602-7d11d81ca0ea

## Why It's Good For The Game

Dev wishlist, ships being effected by planetary gravity feels cool

## Changelog

:cl:
tweak: ships no longer have intrinsic gravity
add: new gravity generator machine for ships
tweak: planetary gravity is now stored level-wide, a ship landing at a planet will be effected by the planet's gravity
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
respect

**Comment by Sweettoothart** [comment]
will astroids, strange signals, and docking in empty space work with the gen? will they not have gravity anymore?

**Comment by SomeguyManperson** [comment]
> will astroids, strange signals, and docking in empty space work with the gen? will they not have gravity anymore?

I haven't touched pre-existing area gravity outside of ships, so asteroids and strange signal ruins will still have gravity. Docking at an asteroid, signal or empty space will not provide a ship with gravity however.

**Comment by west3436** [comment]
Are gravity generators even fun at all? They're purely the stick with no carrot. You HAVE to have the generator or the game isn't fun to play; meaning the generator exists purely for antags (which don't even exist on this server) to vandalize to make the game less fun for everyone else

**Comment by Zevotech** [comment]
> Are gravity generators even fun at all? They're purely the stick with no carrot. You HAVE to have the generator or the game isn't fun to play; meaning the generator exists purely for antags (which don't even exist on this server) to vandalize to make the game less fun for everyone else

no offense but who the hell are you lol

**Comment by west3436** [comment]
> > Are gravity generators even fun at all? They're purely the stick with no carrot. You HAVE to have the generator or the game isn't fun to play; meaning the generator exists purely for antags (which don't even exist on this server) to vandalize to make the game less fun for everyone else
> 
> no offense but who the hell are you lol

A shiptest player? Are players not allowed to provide input on PRs beyond code review? Genuinely asking

**Comment by immortalartisan** [comment]
I like it provides a nice bit of immersion and realism... i now want to make ships designed for no grav gen

**Comment by Apogee-dev** [comment]
> > will astroids, strange signals, and docking in empty space work with the gen? will they not have gravity anymore?
> 
> I haven't touched pre-existing area gravity outside of ships, so asteroids and strange signal ruins will still have gravity. Docking at an asteroid, signal or empty space will not provide a ship with gravity however.

Could be worth retouching those ruins to play around with gravity (or add in gravity generators, powered or unpowered, to the ones that are ships/stations) in the future, but that's out of scope for this PR.

Speaking of power, though, I almost want to say the gravity generator should draw power directly from the grid rather than an APC since it's heavy ship infrastructure, similar to the atmos shield generators used on cargo doors (just, uh, give it a power buffer so it doesn't have the same random shutdown issues if you decide to do that)

**Comment by SomeguyManperson** [comment]
> Speaking of power, though, I almost want to say the gravity generator should draw power directly from the grid rather than an APC since it's heavy ship infrastructure, similar to the atmos shield generators used on cargo doors (just, uh, give it a power buffer so it doesn't have the same random shutdown issues if you decide to do that)

Already has both, currently manual shutoff instantly disables it but it does have a buffer if it loses power. The demo video doesn't make it explicit but it's using the same wire node the APC is on to connect to the powernet.

**Comment by Apogee-dev** [comment]
> > Speaking of power, though, I almost want to say the gravity generator should draw power directly from the grid rather than an APC since it's heavy ship infrastructure, similar to the atmos shield generators used on cargo doors (just, uh, give it a power buffer so it doesn't have the same random shutdown issues if you decide to do that)
> 
> Already has both, currently manual shutoff instantly disables it but it does have a buffer if it loses power. The demo video doesn't make it explicit but it's using the same wire node the APC is on to connect to the powernet.

Okay, great! Must have missed it when I took a cursory glance at the code. I'll update shield generators with a buffer one of these days...

**Review by thgvr — CHANGES_REQUESTED** [review]
A request, add a cargo pack for 2000 credits that ships you a fully built unanchored gravity generator.

**Review by thgvr — APPROVED** [review]

**Comment by thgvr** [comment]
lgtm

**Pull request merged**
