### PR TITLE
Massively rebalances combat exosuit durability

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

Numbers are very, VERY subject to change as this gets tested. In fact, they’re almost guaranteed to need tuning.

### Combat exos have dramatically buffed armor across the board. 
Gygax now has armor equivalent to a bulletproof vest; Durand has armor comparable to a marine vest.
In general, this means that weapons with neutral or higher AP are necessary to deal more than chip damage to either exosuit, especially the Durand, but high-penetrating weapons such as DMRs or hard counters like EMPs and explosions are still just as effective as before.
### To compensate, repairs are now less efficient and slower.
Repairs for all exosuits, when using a welder, now take a short do_after to complete, meaning you can't mash LMB to repair. Combat exos additionally have a repair multiplier that means repairs of all sorts heal less damage while still consuming the same amount of fuel or battery and time. Gygaxes have a 25% penalty to repair value and Durands have a 50% penalty.
### Civilian exo durability is unchanged.
Outside of the slower welder repairs, civilian exos haven't been touched; Combat Ripleys are just as useful as before, they just shouldn't feel more durable than a Gygax anymore.

Also I gave the Paladin higher melee armor and lower bullet armor so it isn't just a palette-swapped Durand.

## Why It's Good For The Game

The fact that the most efficient way to kill combat exos is buckshot is just plain silly; Exosuits aren't tanks, but they're still supposed to be heavily armored and require bigger guns to crack. This change hopefully makes that the case without making exos too much harder to kill when you have the right tools. Pretty much everybody has access to a decent anti-exo weapon at low cost in the form of the Illestren, and bomb damage such as that dealt by a KA is still as efficient as it used to be, so even the poorest crews shouldn't be completely bereft of tools to deal with them.

## Changelog

:cl:
balance: Massively buffed combat exosuit armor
balance: Made repairing exosuits with a welder a do_after
balance: Combat exosuits get less healing from repairs
balance: The Paladin now has higher melee armor and lower bullet armor than the Durand
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
Do mechs care about AP damage here? On TG armor penetration isn't calculated when hitting mechs, so a bullet doing 15 damage at 50 AP is outright worse in every way compared to a bullet doing 20 damage at 0 AP.

**Comment by Apogee-dev** [comment]
> Do mechs care about AP damage here? On TG armor penetration isn't calculated when hitting mechs, so a bullet doing 15 damage at 50 AP is outright worse in every way compared to a bullet doing 20 damage at 0 AP.

I actually test my code, so yes, they do care. A Gygax takes about 80 damage (out of 300) from a point blank Mongrel magdump (that’s about 24 shots of 10mm) while a Ripley is completely destroyed (over 150 damage dealt) with these changes applied, as of the current commit.

**Comment by Martinpachu** [comment]
i thhought you wanted the civilian mechs to have at least a bit of armor too? what changed your mind?

**Comment by Apogee-dev** [comment]
> i thhought you wanted the civilian mechs to have at least a bit of armor too? what changed your mind?

Yeah I changed my mind on that one. Depending on how things pan out I _might_ come back and give them all 40 armor to hit the breakpoint for hollowpoint or something, but i want to leave the relative durability of stuff like combat ripleys unchanged for the time being. basically the “armor” on civilian exosuits is more like the outer skin of your car than actual armor and that’s fine

**Comment by generalthrax** [comment]
We could use a repeating do_after for repairing. My fingers are in agony after individually clicking 50 times for a Durand.

**Review by rye-rice — CHANGES_REQUESTED** [review]
this is good, make sure to make the welding do_after repeat itself to save poor fingers

**Comment by rye-rice** [comment]
poke about repeating do-after

**Comment by rye-rice** [comment]
poke

**Comment by Sun-Soaked** [comment]
ooo you want to finish this pr ooo

**Review by rye-rice — APPROVED** [review]

**Review by Sun-Soaked — APPROVED** [review]
yes

**Pull request merged**
