### PR TITLE
Enigma-Class Mining Ship

### PR DESCRIPTION
**Pull request by ForestCranked**
## About The Pull Request
This adds a ship i've worked on (with the help of the shiptest community) for a bit, the Enigma-Class Mining Ship (Prefix ISV i guess since having an entire prefix [ESV, Enigma Space Vessel] for one ship is kind of dumb. Namelists are Pills and General.)

## Why It's Good For The Game
Like with the Courage, I don't think this'll really benefit anything besides having another ship, which we already kinda have a bit much of. Also like with the Courage, i won't be surprised if this is denied.

## Changelog
:cl:
add: Enigma-Class Mining Ship. Filename is an artifact title.
add: Enigma-Class Config. the name is an artifact title, like with the map file's name.

del: Wrong Enigma-Class File.
add: The right one.
add: some miscellaneous stuff to Wheatley and turf/area passthroughs.
del: the transit tube. I will miss you, toob.
add: an actually good(?) hydroponics setup. Also moved the suit storages to the back end and gave the miners actual scanners.
add: outlining!!!
add: dirt, grime, and construction stuff.
/:cl:

### CODE REVIEW

**Comment by Sylphily** [comment]
there are a lot of problems here

**Comment by Ebin-Halcyon** [comment]
> cl
>imageadd: entire picture of ship

You uh, wanna put the image of the ship in the about section, imageadd is for sprites and the such.

**Comment by ForestCranked** [comment]
> > cl
> > imageadd: entire picture of ship
> 
> You uh, wanna put the image of the ship in the about section, imageadd is for sprites and the such.

Now fixed. Thanks for noting that.

**Comment by Apogee-dev** [comment]
You can leave the areas out of the ship image. Also, use the terrain pass-through turf instead of space.

**Comment by PiperDoots** [comment]
Why is there a swarmer and a borg in the cargobay? 
What niche does this ship fill?
Also I think the logo is oriented the wrong way

**Comment by ForestCranked** [comment]
> 

swarmer is friendly, borg... fuck. and i have no idea.

**Comment by ForestCranked** [comment]
> > 
> 
> swarmer is friendly, borg... fuck. and i have no idea.

also, the logo is oriented right.

**Comment by Latentish** [comment]
I'm not really sure what niche you're trying to fill here. The overall shape is nice, but the use of space is kinda overspacious. You say you want a mining ship, but you have a very simplistic bedroom with little in it, and a lackluster botany setup taking up half the space on the ship.I'm also not sure why you'd put the eva suit storage units in that hallway.
This ship just seems a bit half baked, like you kind of know what you want out of it, but aren't sure how all the parts fit together.

Also the transit tubes do not work. They might seem like they work a bit? But they have so many problems that it's just not a good idea to use them at the moment.

**Comment by Apogee-dev** [comment]
As Sylv said, the ship’s got a lot of empty space and a lot of that space is allocated pretty strangely (for example, generators and the SMES in dorms? Beds on opposite ends of the room, placed directly adjacent to thrusters?). On top of that it’s missing some essential equipment (holopad, wideband intercom, engine blast doors) and, also as sylv said, doesn’t really seem like it’s filling a niche, since the equipment spread is pretty generic and there aren’t any roleplay gimmicks going on here.

**Comment by PiperDoots** [comment]
Additionally, some ways you can improve mostly on other ships you may make.

- Decals, you have one here in the middle but a huge part of the ship is just empty flooring without them, a common technique is outlining rooms with a trim to have a decent looking effect. Look at how other ships do it and try to copy the idea, then expand on it.
- Room layout, as mentioned before it's nonsensical here. Internal walls are just as important as your external ones and trying to get those figured out before you start making anything else on the ship is usually a pretty good idea, mostly so you don't end up with engines and an airlock in dorms. I do like some stuff you did here, specifically the plasma thrusters being fully encased.
- Gear, as mentioned before it's a bit all over the place with some essentials missing whilst you have some stuff laying around like a bluespace rped, something that usually requires a lot of research. Try making a list in the decorating phase of which jobs you want on your ship and what the minimum amount of items they'll need is. Then put those in and see how you can lean them more towards your niche.

Overall this is an improvement on your previous work but needed a lot more time in the oven before the PR, looking at other ships isn't a sin and I personally think you could learn a lot by comparing what you have here to what they did and seeing what they did differently to you and how you can improve what you have.

**Comment by ForestCranked** [comment]
Disregard this. i'm turning this into a ruin.

**Pull request closed without merging**
