### PR TITLE
ACTUALLY makes showers and IV drips buildable, because i fucked up the commit somehow and it got merged anyway

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Showers can now be built with 3 metal.
IV Drips can now be built with 5 plastic.

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
Showers are necessary for a functioning bathroom and even more necessary for doing surgery on a plasmaman.
IV drips are now available to medical ships that happen to lack an IV drip roundstart or for ships in dire need of blood transfusion that have blood bags but no IV. They are made with plastic, like other medical things, and shouldn't be that hard to make as long as you have a chem dispenser or a decent ghetto chemist on the ship.

## Changelog

:cl:
add: stack_recipes for showers and IV drips
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
okay, what the fuck? I commit the changes and they just vanish into the ether?

**Comment by Zevotech** [comment]
image
im actually losing my goddamn mind arent i

**Comment by Zevotech** [comment]
i think i am genuinely going insane. I did not make this on my master branch. help.

**Comment by Ms-Mee** [comment]
Common symptons of overexposure to code include: Paranoia, hallucinations, grass deficiency, reducive cognitive functions, eye damage, insomnia and a weird urge to code nonsense

**Pull request closed without merging**
