### PR TITLE
The Great Handgun Re-Flattening

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request

Re-creating this because the original PR was fucking haunted.

Rebalances handguns across most factions and improves access to ammunition for players with non-NT equipment.
Changes are as follows:

- Buffed 9mm to perform identically to .45 and 10mm (temporary balance: cartridges will be better distinguished later)
- Added extra ammunition types for 9mm, 10mm, .45, and 5.56mm HITP; all four now have ball, rubbershot, AP, and HP, and 9mm and .45 now have incendiary.
- Added new ammo box sprites for all standard handgun cartridges
- Made rubber shotshells blue to match rubber handgun ammo
- Added basic handgun ammo boxes to the autolathe as default blueprints
- Replaced .38 speedloaders on the autolathe with .38 ammo boxes
- Made buckshot and beanbag slugs unlocked on the autolathe by default
- Moved advanced shotshells to the protolathe, available with Ballistic Weapons, Medical Weapons, and Exotic Ammunition
- Made 9mm, 10mm, and .45 in basic and rubbershot available on the seclathe by default
- Made buckshot, rubbershot, and beanbag slugs available on the seclathe by default
- Added new research node for advanced ballistic ammunition, unlocked with ballistic weapons and advanced engineering research

New ammo box sprites pictured below.
ammoboxes

this WILL mess with the balance of other 9mm guns like the APS and SABR. They'll have to get a balance pass when we work on the SMGs as a class, but the focus is on pistols right now since they're the most common type.

## Why It's Good For The Game

the commander is nearly worthless and is a downgrade from every other handgun in almost every way, basic ammunition access for everything but Commanders is a major problem, and ammunition access for shotguns has been a major contributing factor to their overall lack of utility on shiptest. Security lathes are now actually useful since they can print basic handgun ammunition without research.

## Changelog
:cl:
add: Added new ammunition variants for 9mm, 10mm, .45, and 5.56mm HITP caseless
add: Added ammunition for all basic faction handguns to the seclathe with a new research node
add: Basic handgun and shotgun ammunition for all basic faction handguns can now be printed at the autolathe
tweak: Replaced .38 speedloaders on the autolathe with ammo boxes
balance: Nerfed 10mm and .45 to do slightly more damage than 9mm
balance: Improved Commander magazine capacity
balance: Removed AP factor and nerfed base damage for 5.56mm HITP Caseless ammo
balance: Buffed improvised shotgun shells to do the same maximum damage as buckshot. Accuracy and damage falloff still limit their real damage output.
imageadd: Added new ammo box sprites for all variants of 9mm, 10mm, .45, and 5.56mm HITP caseless
/:cl:

### CODE REVIEW

**Review by francinum — CHANGES_REQUESTED** [review]
```
## WARNING: Invalid research design with ID hp45 detected in node Advanced Ballistics[adv_ballistics] removed. in code/controllers/subsystem/research.dm at line 152 src: Research usr: .
[00:25:35] Runtime in unsorted.dm,1056: Invalid techweb nodes detected
  proc name: stack trace (/datum/proc/stack_trace)
  src: Research (/datum/controller/subsystem/research)
  call stack:
  Research (/datum/controller/subsystem/research): stack trace("Invalid techweb nodes detected")
  Research (/datum/controller/subsystem/research): initialize all techweb nodes(0)
  Research (/datum/controller/subsystem/research): Initialize(15354)
  Master (/datum/controller/master): Initialize(10, 0, 1)
```

**Review by francinum — APPROVED** [review]

**Comment by Apogee-dev** [comment]
Don't fullmerge this yet, I want the opportunity to test and tune a bit... and ideally give SMGs a pass here instead of breaking things hard for a while after this is merged until those can get a separate balance pass.

**Comment by UltraNumeron** [comment]
Ight so recently loaded up some 9mm in the vector smg secofficers can get and damn that shit is good, its not ak level good cause the firerate while good isnt ridicilous it stilll four shots people with a fast rate of fire.

**Comment by Apogee-dev** [comment]
> Ight so recently loaded up some 9mm in the vector smg secofficers can get and damn that shit is good, its not ak level good cause the firerate while good isnt ridicilous it stilll four shots people with a fast rate of fire.

Yeah, I knew going in that SMGs were going to be busted until I give them a balance pass. I'm thinking of nerfing all of the handgun rounds for the sake of making the SMGs not absolute murder while still making them a substantial upgrade over a pistol. Also indirectly makes shotguns suck less by comparison.

The problem really is that people are using handguns to engage fauna, so tuning their balance for that makes them disgustingly overtuned against humans. We need a fauna nerf.

**Comment by Apogee-dev** [comment]
Update: Changed base damage for handgun cartridges again. 9mm and 5.56mm HITP Caseless do 20 base damage (the same as 9mm did before this PR) while .45 and 10mm have been nerfed to 25 damage. The magazine size for the Commander has been buffed accordingly, giving it identical damage per magazine as the stechkin and M1911. The M9C gets two extra shots and higher damage per mag, but given its comparative rarity I think this is fine. The cartridge nerfs have by extension nerfed the .45 SMGs like the Uzi and C20-r to be more comparable to the Vector in damage output, but I haven't fine-tuned their performance yet so they may need another pass to tweak fire rate and the like.

**Comment by MarkSuckerberg** [comment]
This going well in-game?

**Comment by Apogee-dev** [comment]
> This going well in-game?

Feedback has been pretty sparse but I'm not hearing any complaints about the basic handguns anymore. It's actually turned into a 10mm and .45 nerf, so I'd hope nobody thinks they're OP. The only thing I'm really missing is feedback on how the Uzi and C20-r hold up compared to the vector and sabr after their ammo got nerfed.

**Pull request merged**
