### PR TITLE
High-Vis IPC Frame by Roostercult

### PR DESCRIPTION
**Pull request by tiramisuapimancer**
## About The Pull Request
image

New IPC chassis type. It's orange. Made by Roostercult, I'm just PRing it for them

## Why It's Good For The Game
More character stuff. More engineer gaming. More orange. Let's go!

## Changelog
:cl: Roostercult
add: Bajaran Blasting Co. High-Vis IPC frame, a new IPC body sprite to pick from
/:cl:

### CODE REVIEW

**Comment by tiramisuapimancer** [comment]
Hold on, I need to fix a few misalignments

**Comment by tiramisuapimancer** [comment]
There, should be fixed

**Comment by triplezeta** [comment]
this ipc chassis looks cursed to me for reasons that are hard to articulate immediately

**Comment by tiramisuapimancer** [comment]
i already have a blorbo that uses this chassis

**Review by triplezeta — CHANGES_REQUESTED** [review]
weird colors and fucky shape

**Comment by AtlasRules** [comment]
love the built-in RIG back

**Comment by Valorium-RB** [comment]
**Baja**ran **Blast**ing?

lmao

**Comment by Roostercult** [comment]
> weird colors and fucky shape

Hi!! Is there anything I could do to make the chasis better? If so let me know and I'll get on it when I can. 
Also this is my first time ever doing any sprite work, so please be very clear about what needs changing

And yes i couldnt come up with a name so i named it off of the joke "bajan blast powered" cus of the rig lights

**Comment by triplezeta** [comment]
> And yes i couldnt come up with a name so i named it off of the joke "bajan blast powered" cus of the rig lights

king shit

As for the sprite itself I think my issues are mainly in regards to the sidestates which look like they are leaning backwards due to the torso bulging outwards, and the front/back also look odd, mainly in the shoulder/armsocket and elbow areas. Generally it could stand to look more flexible, with sections of the arm looking like they are separate parts designed to move.

I'll provide more active feedback on discord later

**Comment by tiramisuapimancer** [comment]
hold on, let me change the picture to be the one with fixed aligments

**Comment by tiramisuapimancer** [comment]
there

**Comment by triplezeta** [comment]
ok that is better

**Comment by Roostercult** [comment]
> > And yes i couldnt come up with a name so i named it off of the joke "bajan blast powered" cus of the rig lights
> 
> king shit
> 
> As for the sprite itself I think my issues are mainly in regards to the sidestates which look like they are leaning backwards due to the torso bulging outwards, and the front/back also look odd, mainly in the shoulder/armsocket and elbow areas. Generally it could stand to look more flexible, with sections of the arm looking like they are separate parts designed to move.
> 
> I'll provide more active feedback on discord later

Alright, I'll look into it more in like two days. Currently moving across state

**Comment by Roostercult** [comment]
yo! I'm working on the sprite tonight. Had to take a big break cus moving is hell. Is there anyway that the stale timer can be reset?

**Comment by triplezeta** [comment]
sure

**Pull request closed without merging**
