### PR TITLE
the lizdate (lizards. REMASTERED)

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
Updates lizard bodyparts
Redesigns lizard heads
Kills off snout overlays, replaces them with Facial Markings
Adds a few new horn styles, Ram and Brimstone are mostly from Bay
Fixes up light belly overlay
Adds a buncha new frills. Frillhawk is heavily inspired from Bay's
Adds a smaller tail (animation WIP)
Here's some examples
image
image
image

## Why It's Good For The Game
dragons

## Changelog

:cl:
add: Some new lizard horns
add: Some new lizard frills
add: Lizard facial markings
add: Lizard Light Belly is now better
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
interior crocodile alligator, i drive a chevrolet movie the-ay-tur

**Comment by rye-rice** [comment]
Wow you work really fucking fast if it's about lizards Jesus christ

**Comment by thgvr** [comment]
argh

**Review by Imaginos16 — APPROVED** [review]
Nice sprites love the lizms.

**Pull request merged**
