### PR TITLE
Atoll-Class Hospital Ship

### PR DESCRIPTION
**Pull request by MemeSnorfer**
## About The Pull Request

Brings in a new independent medship, meant to be the successor of the box-class. Made by Ihejirika Civ. Manufacturing, this vessel is popular among small medical companies and charity organizations.

image

Also adds a preloaded subtype of the organ smartfridge.

<details>
<summary>More images of various areas of the ship</summary>

Lobby & Reception
image

Medical Center & Morgue
image

Crew Area
image

Engineering
image

Office & Bridge
image
</details>
<details>
<summary>SDMM screenshots</summary>

</details>

## Why It's Good For The Game

The Box-Class is outdated, and was made for a different time. This new ship should hopefully bring independent medships back into the scene.

## Changelog

:cl: MemeSnorfer and Moffball
add: Atoll-Class Hospital Ship
add: Preloaded organ smartfridge
del: Disabled the Box-Class
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
Could use some hand rails, especially in rooms without any seating like most of medbay. You might want to use a blue command airlock for the officers’ quarters to distinguish it a bit from the crew dorms. And it needs a ship pet! I wonder who I’d have to bribe to get a possum coded so we could put it in the morgue…

**Comment by MemeSnorfer** [comment]
> Could use some hand rails, especially in rooms without any seating like most of medbay. You might want to use a blue command airlock for the officers’ quarters to distinguish it a bit from the crew dorms. And it needs a ship pet! I wonder who I’d have to bribe to get a possum coded so we could put it in the morgue…

Placed a couple handrails around the ship. Officer quarters now have a blue airlock.
AAAaaaand as for the ship pet, I've got nothing. One *could* technically consider the fish in the aquarium to be the ship pet...

if it really needs an actual pet though, there's this iguana I've been eyeing that I don't think is used anywhere else,
image

**Comment by Apogee-dev** [comment]
The iguana would be a good pick and shouldn't require any unique code, go for that! we don't have enough variety in pet mobs anyway.


i'm still gonna find someone to bug about a possum pet though

**Comment by Jedi-Toothpaste** [comment]
hi meme, there is a missing pipe under this airlock here, see image, i'll update this more as I see issues, also, it would be nice for all the airlocks to be named but it is not important

image

edit: I typed the wrong meme, meem, sorry

**Comment by meemofcourse** [comment]
what

**Review by Latentish — DISMISSED** [review]
The box class is going to be getting cut regardless, you might as well just outright remove it in your PR.
Aside from that this ship is very well decorated and decalled. I think my biggest worry is that the layout may confuse some people, however I don't think that's a big enough or significant enough of a worry to bar this or make a request about it. I could see this being TM'd.

**Comment by Gristlebee** [comment]
LETS GO GAMBLING

**Comment by Gristlebee** [comment]
Aw dangit

**Pull request merged**
