### PR TITLE
Replaced borg hud with regular one in Riggs MD closet

### PR DESCRIPTION
**Pull request by Vexylius**
## About The Pull Request
A super tiny fix before I forget to do it

## Why It's Good For The Game
you are not a robot, stop trying to act like one

### CODE REVIEW

**Comment by Ms-Mee** [comment]
Oh yeah? Well all my friends are robots what about them huh ???

**Comment by ZephyrTFA** [comment]
Can we not self merge without approval from another maintainer, especially before the 24hr period

**Comment by Sylphily** [comment]
I mean it's a one line big fix

**Comment by ZephyrTFA** [comment]
kinro-rules

**Pull request merged**
