### PR TITLE
Finishes The Ballistic Rework

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
Finishes #1493 
From the previous PR:
HOW CARTRIDGES ARE BALANCED:

Lower-velocity cartridges like pistol and shotgun rounds now have a default penalty to AP power. As velocity increases, AP increases substantially and damage increases slightly. Hollowpoint and AP round variants modify that base AP further, with AP handgun bullets having lower AP than AP rifle bullets.

    Shotgun & Handgun: -20 AP
    PDW: 0 AP
    Assault Rifle, LMG: 20 AP
    Rifle: 40 AP
    Shotgun: -35 AP pellets, -10 AP slugs

## Why It's Good For The Game
Also from the previous PR:
Ballistic cartridges should be distinguished by traits other than just raw damage. By using AP to distinguish ballistic weapon classes, they now have more distinct use cases. Additionally, low-AP weapons like handguns and shotguns remain useful against simple mobs but drop off significantly in effectiveness against well-armored players, meaning there's more reason to seek out specialized ammo types or higher-caliber weapons than just damage output. The lower raw damage of rifle-caliber weapons also means they are a much more viable choice for roundstart placement in ships, leading to more loadout diversity.

## Changelog

:cl: Apogee, Erika, Imaginos
add: transferring bullets from magazine to magazine now has a do_after and loops.
add: Ammo magazines are now purchasable at the outpost
add: P16s, SVG-whatevers, Bolt-Action Rifles, and .357 revolvers are now available for purchase at the outpost
del: Removed paywall and clown firing pins from purchase.
balance: AP Values have been tweaked across the board (On guns at least), smaller cartridges tend to penetrate less, while larger ones penetrate more.
imageadd: New bullet sprites (I believe they're apogee's), and new ammo box sprites by Imaginos
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
Remember to add the hunting .38 removal to the CL

**Review by rye-rice — APPROVED** [review]
made the ammo sprites, thank you imaginos for touching them up

i thought we were calling the ak47 the SKM? also ak47 being buyable flashbacks

**Comment by Apogee-dev** [comment]
Can you review the per-unit prices for magazines? They should always cost more per bullet than bulk ammo (by a good margin), otherwise people will just buy magazines in bulk and toss the empty ones like trash

**Comment by Imaginos16** [comment]
> Can you review the per-unit prices for magazines? They should always cost more per bullet than bulk ammo (by a good margin), otherwise people will just buy magazines in bulk and toss the empty ones like trash

While I wholeheartedly agree with that the idea was to later make a category where you could buy ammo packs and have magazines cost more as a result in comparison to the raw ammunition packages.

**Review by MarkSuckerberg — APPROVED** [review]

**Pull request merged**
