### PR TITLE
Adds a fax machine to the Dwayne.

### PR DESCRIPTION
**Pull request by Sadhorizon**
## About The Pull Request

obraz

## Why It's Good For The Game
- Communication with the outpost is fun.
- NT is like, THE tcomm company, even if the ship is meant to be their civ market garbage, it should still get one.

## Changelog

:cl:
add: Added a fax machine to the Dwayne-class.
/:cl:

### CODE REVIEW

**Comment by meemofcourse** [comment]
there should be a paper bin and pen in close proximity to the fax machine

**Comment by Sadhorizon** [comment]
argh, you are right

**Comment by Sadhorizon** [comment]
okay done

**Comment by Apogee-dev** [comment]
Indie ships don’t get faxes. This has been coming up off and on for around a year now, but it’s still a thing- even huge ones like the Shetland and the Riggs don’t get a fax (and I was told to remove the fax back when i remapped them, even), so the Dwayne shouldnt either.

**Comment by Sadhorizon** [comment]
> Shetland [...] don’t get a fax 

obraz

> and the Riggs

obraz

**Comment by Apogee-dev** [comment]
> Indie ships don’t get faxes. This has been coming up off and on for around a year now, but it’s still a thing- even huge ones like the Shetland and the Riggs don’t get a fax (and I was told to remove the fax back when i remapped them, even), so the Dwayne shouldnt either.

Misremembered an outdated standard, you’re good.

**Pull request merged**
