### PR TITLE
[READY] Icewhelps are no longer absolutely busted (aka blatant icewhelp nerf)

### PR DESCRIPTION
**Pull request by Nobelium-XVIII**
## About The Pull Request
icewhelp
icewhelp2
single icewhelp annihilates entire ship crew with no hesitation
certified skill issue but still malding
I am going to do a grudgecode

## Why It's Good For The Game
Icewhelps originally had a massive 300 health and a vision range above that of the player, which obviously isn't all that balanced. Additionally, their firebreath outraged that of a stock PKA. Yeah...

## Changelog
:cl:
balance: Ice whelp vision reduced to 7, originally 8.
balance: Max health reduced to 250, originally 300.
balance: Melee damage reduced to 15, originally 20.
balance: Firebreath damage reduced to 10, originally 15.
balance: Firebreath range reduced to 3, originally 5.
balance: Firebreath attack delay increased to 3 seconds, originally 2 seconds.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
ship tested

**Comment by Sun-Soaked** [comment]
the skull tissue is on the floor. I don't have vsc on this pc(yet), so while you're at it, could you please boost the cooldown on wolf lunges by a factor of 1.5, reduce wolf speed, and reduce alpha wolf health to 150?

**Comment by Sun-Soaked** [comment]
disregard, my emergency changes are fixing wolves

**Comment by ZephyrTFA** [comment]
Ice whelps are intended to be a mini-boss.
The issue is that they for some reason have damage resistances to anything that isnt mining gear.
Instead of doing this just strip their questionable resistances.

**Comment by Sun-Soaked** [comment]
so I actually checked and this isn't the case anymore- icewhelps no longer have any special armor treatment or resistance values beyond what's common to default hostile simplemobs. Whatever allowed a single one to solo wipe a team of players with heavy armor and AK47's is just their moxy, I guess

**Comment by Nobelium-XVIII** [comment]
Certified zephyr moment

**Comment by Nobelium-XVIII** [comment]
Anyways I should probably close this since #348 exists

**Pull request closed without merging**
