### PR TITLE
SolGov Liberty-class Interceptor

### PR DESCRIPTION
**Pull request by Apogee-dev**
## About The Pull Request
liberty

A SolGov refit of the popular civilian Libertatia-class Hauler, the Liberty is a small, fast interceptor ship. With an armory comparable to the much larger Carina but very limited endurance, ships like the Liberty are generally only deployed in direct response to reports of trouble (read: this ship can only be spawned by admins). Features include a well-stocked armory, a small medbay with enough supplies and equipment to render limited medical assistance to other ships, and a small warden's office and holding cell in the cargo bay.

## Why It's Good For The Game

adminbus response ship for pirates that go a little too hard

## Changelog
:cl:
add: Added the Liberty-Class Interceptor, a bus-only SolGov interceptor ship.
/:cl:

### CODE REVIEW

**Comment by Valorium-RB** [comment]
Is there any particular reason why this can't be a conventionally available ship?

**Comment by Apogee-dev** [comment]
> 
> 
> Is there any particular reason why this can't be a conventionally available ship?

I don't want to spam too many variations on a single ship (the Libertatia is already a frequently-played ship as it is). Additionally I've actually been debating increasing the armor/armament available to the crew even more to make it better suited for the admin response role. This is basically ERT: The Ship.

**Comment by HighPrincessErinys** [comment]
> Additionally I've actually been debating increasing the armor/armament available to the crew even more to make it better suited for the admin response role.

SolGov AR :)

**Comment by shiptest-server** [comment]
#### Test Merge Removed

**Comment by MarkSuckerberg** [comment]
not stale

**Pull request merged**
