### PR TITLE
Shipdate 1: Kugelblitz

### PR DESCRIPTION
**Pull request by ToasterBan**
## About The Pull Request
Shipdate is a small project I am doing to update the less used, older ships

this one is for the Kugelblitz

the only changes are that the firefighter is no longer scattered around the ship, supermatter should not delaminate shipstart

this is WIP and I HEAVILY wish that you send feedback or requests

## Why It's Good For The Game
old bad ship (hopefully) turned into good updated ship

## Changelog
:cl:
tweak: Updated Kugekblitz
/:cl:

### CODE REVIEW

**Comment by MusselMain** [comment]
Although I don't see these often, it's nice to see the oldies get some love (especially when it's a function issue).

**Comment by swifterjack** [comment]
it doesnt delaminate roundstart, you need to wrench one thing and it works

**Comment by swifterjack** [comment]
also its the kugelblitz, not the blitzkrieg

**Comment by ToasterBan** [comment]
> also its the kugelblitz, not the blitzkrieg

I am what you call tired and stupid

**Comment by ToasterBan** [comment]
> it doesnt delaminate roundstart, you need to wrench one thing and it works

almost every supermatter I saw regardless of codebase would slowly delaminate if it wasn't mapped onto vacumm tiles and people didn't set it up quick it enough

**Comment by tiramisuapimancer** [comment]
it definitely does not delam roundstart unprompted.

**Comment by PrefabQuasar** [comment]
yeah, can confirm, the kugel doesnt delam roundstart, and actually received a full remap relatively recently

**Comment by PrefabQuasar** [comment]
A: please show a picture of the updated version of the map for this map change PR, and 
B: 

> > it doesnt delaminate roundstart, you need to wrench one thing and it works
> 
> almost every supermatter I saw regardless of codebase would slowly delaminate if it wasn't mapped onto vacumm tiles and people didn't set it up quick it enough

Supermatters on most codebases are entirely inert unless they are activated by dusting, getting shot, or substantial atmos changes

**Comment by ToasterBan** [comment]
Closing because I dislike these changes and might make a different PR to fix some other issues I had with the Kugelblitz

**Comment by AtlasRules** [comment]
frankly if you want some older ships to do up? look at the Meta-class and Delta-class, they could use some love

**Pull request closed without merging**
