### PR TITLE
Ruins Tide's aesthetic to fix Shuttle Permit issues

### PR DESCRIPTION
**Pull request by Kurgis**
## About The Pull Request
Much of the Tide does not count as a valid area for the shuttle permit, this resolves the issue making all areas start off as valid rooms.

imageimage

## Why It's Good For The Game
Should, allegedly, cut down on Ship-Cutting Syndrome the Tide frequently suffers from due to the shuttle permit acting wacky.

## Changelog
:cl:
tweak: Added a few corner walls to the Tide-class so its areas counts as valid rooms at roundstart.
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
images pls

**Comment by Kurgis** [comment]
> images pls

Images attached.

**Review by MarkSuckerberg — APPROVED** [review]

**Comment by PrefabQuasar** [comment]
m

**Comment by PrefabQuasar** [comment]
this has already been merged, but jesus CHRIST
why in the name of god did you put a WINDOW THERE
image
WHY

**Comment by AtlasRules** [comment]
even more tidier than you could've ever done

**Comment by PrefabQuasar** [comment]
> even more tidier than you could've ever done
funny as it is it does also totally conflict with the changes being made to the tide at the same time in a currently open PR, i've edited my version of the tide to also fix the zoning issues though

**Comment by Kurgis** [comment]
> WHY

I know no masters.

**Pull request merged**
