### PR TITLE
Some gun resprites, adds the Cobra 20

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Resprites the bulldog and c20r, adds the Cobra 20 for mappers

## Why It's Good For The Game

Screenshot_3478

Screenshot_3487

## Changelog
:cl:
add: Cobra 20

imageadd: The bulldog and C20r have been resprited
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
Not sure on the theming of the Cobra-20 as a civilianized variant of the C20r, given its design and appearance. Might make more sense to say it's an obsolete predecessor to the C20r instead? Would fit in line with most of the other indie guns being antiques or otherwise old guns that aren't in military use anymore, especially for something more military in nature like a submachine gun. I have concerns about it being too powerful, but SMG balance in general is pretty out of whack at the moment and deserves its own PR eventually.

**Comment by Apogee-dev** [comment]
also i know the sprites have been around for a while but looking at them here, the magazine on the Bulldog looks pretty small. Shotgun mags can get pretty huge, given how thick shotshells are. I'd extend the magazine down to at least be level with the bottom of the pistol grip.

**Comment by rye-rice** [comment]
Screenshot_3487

Cobra's description was changed, the bulldog mag was made bigger

**Review by triplezeta — APPROVED** [review]

**Comment by Valorium-RB** [comment]
May be out of scope, but remember to update that one contraband poster with the C20r on it to reflect the new look.

**Comment by rye-rice** [comment]
It isnt but im lazy

i might do a pr looking at posters down the line

**Pull request merged**
