### PR TITLE
scrapper go away

### PR DESCRIPTION
**Pull request by ZephyrTFA**
Removes the scrapper due to spurious CI failures.
If you can get the map to not constantly cause CI to fail you can readd it.

### CODE REVIEW

**Comment by Kapu1178** [comment]
Scrapper no scrapping
Scrapper no scrapping
Scrapper no scrapping

**Comment by triplezeta** [comment]
inb4 integration checks fail

**Comment by francinum** [comment]
scrapper is scrapped

**Comment by ZephyrTFA** [comment]
> inb4 integration checks fail

🤡

**Review by francinum — APPROVED** [review]

**Pull request merged**
