### PR TITLE
Assorted Small Schmeid Fixes 

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
The Schmeidberg is apparently an older ship, as I opened the file up and to my horror, discovered that it had no fire extinguishers, some weird wallframe placement, and like 4 layer manifolds just. Under walls. For no reason. I don't know why. I also discovered something I am taking to calling the "Wallofield Projector". The server's not ready for that yet.

Seriously I went and redid a few decals, removed wallpipes, moved some wallmounts around, and added extinguisher cabinets.

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
Ship subject to quality standards

## Changelog

:cl:

tweak: The Schmeid has gotten a bit of an update. It has luxuries like fire extinguishers now.
fix: removed a few wallpipes on the schmeid. 
/:cl:

### CODE REVIEW

**Comment by Ms-Mee** [comment]
> The Schmeidberg is apparently an older ship

#982 and #1481, to clarify

**Comment by Sun-Soaked** [comment]
This is actually my rework from a few months ago, uh
 something odd happened with the file during a conversion across mapping programs and a bunch of floor turfs and objects got scrambled around. 
 I fixed what I found but clearly I wasn't careful enough.

The lack of extinguishers is fully on me, though

**Comment by Apogee-dev** [comment]
While you’re adding emergency gear, it could probably use one or two emergency O2 closets. Other than that I don’t see anything else in need of tweaking

**Comment by Latentish** [comment]
Test marg (You know this)

**Comment by Latentish** [comment]
Pretty Much.

**Pull request merged**
