### PR TITLE
Gunsmithing!

### PR DESCRIPTION
**Pull request by FalloutFalcon**
## About The Pull Request

OK extreme work in progress but I want checks to run. Will iron out the pr description when I have some more to show.
Prone to change https://hackmd.io/@FalloutFalcon/HkX_Wqc9p
https://discord.com/channels/837744059291533392/1195492151967100988/1195494569421324319

https://github.com/shiptest-ss13/Shiptest/assets/86381784/8468a454-598c-4d68-ab67-3f3e49fe9b22

## Changelog

:cl:
add: Gunsmithing!
/:cl:

### CODE REVIEW

**Comment by Zorazi-Teo-Daedalus** [comment]
I want this to exist so badly, in part because it would lay the groundwork for a Hunter's Pride ship for SRM so they can finally have more than one ship.

Would it also be possible as a later goal, maybe even a separate PR, to make the manufacture of ammunition also a thing? It feels like something that would go hand in hand with gunsmithing to also produce gunpowder and craft ammunition instead of say, buying it from cargo or printing it from a lathe.

**Comment by FalloutFalcon** [comment]
> I want this to exist so badly, in part because it would lay the groundwork for a Hunter's Pride ship for SRM so they can finally have more than one ship.
> 
> Would it also be possible as a later goal, maybe even a separate PR, to make the manufacture of ammunition also a thing? It feels like something that would go hand in hand with gunsmithing to also produce gunpowder and craft ammunition instead of say, buying it from cargo or printing it from a lathe.

Ammo crafting is a planned part of this pr

**Comment by Zorazi-Teo-Daedalus** [comment]
> > I want this to exist so badly, in part because it would lay the groundwork for a Hunter's Pride ship for SRM so they can finally have more than one ship.
> > Would it also be possible as a later goal, maybe even a separate PR, to make the manufacture of ammunition also a thing? It feels like something that would go hand in hand with gunsmithing to also produce gunpowder and craft ammunition instead of say, buying it from cargo or printing it from a lathe.
> 
> Ammo crafting is a planned part of this pr

That awkward moment when someone is a dumbass and doesn't read the design document before commenting. (It's me, I'm the dumbass.)

Can't wait for people to start making like, Metro 2033 abominations.

**Comment by FalloutFalcon** [comment]
> > > I want this to exist so badly, in part because it would lay the groundwork for a Hunter's Pride ship for SRM so they can finally have more than one ship.
> 
> > > Would it also be possible as a later goal, maybe even a separate PR, to make the manufacture of ammunition also a thing? It feels like something that would go hand in hand with gunsmithing to also produce gunpowder and craft ammunition instead of say, buying it from cargo or printing it from a lathe.
> 
> > 
> 
> > Ammo crafting is a planned part of this pr
> 
> 
> 
> That awkward moment when someone is a dumbass and doesn't read the design document before commenting. (It's me, I'm the dumbass.)
> 
> 
> 
> Can't wait for people to start making like, Metro 2033 abominations.

I think i'm going to scale back customization aloft for this pr
I might have a later pr for custom guns but they will prob be there own thing

**Comment by FalloutFalcon** [comment]
Gonna close this. I plan on rewriting, alot of it, gonna wait till some other gun stuff happens

**Pull request closed without merging**
