### PR TITLE
Adds the Inkwell-class Supply Freighter

### PR DESCRIPTION
**Pull request by Imaginos16**
## Wait, isn't there a freeze right now?
Correct, there is a ship freeze currently, but I have received permission from @Apogee-dev to create the PR for this vessel, as it was a ship I've been working on since at least early-to-mid August.
image

If any other maptainer would like to overrule Apogee, I'd be more than happy to temporarily close the PR. Until then, here it is!
## About The Pull Request
Hello everyone! Mr. SolGov here again to add yet another ship to be tested!

This PR adds a completely new vessel, that being the **Inkwell-class Supply Freighter**, a ship known for its vast cargo space!

With extra starter money, three sonnensöldners, and three miners, players can enjoy completing bounties like no tomorrow, have drinks with their crewmates in peace, and supply other SolGov vessels with much needed equipment in less time than you can say "I ran out of ammo!"

Notable things in this ship include:
- Turrets (with IFF!)
- A bar!
- A full-blown cafeteria with a small kitchen and lounge!
- An office space for bureaucrats and scribes!
- Decently-sized quarters for the Logistics Deck Officer and Captain!
- A massive cargo bay with pre-existing supplies!
- A secret compartment for private storage!

And finally, as for jobs, there are:
- 1 Captain
- 1 Logistics Deck Officer
- 3 Sonnensöldneren
- 2 Space Engineers
- 3 Field Engineers
- 2 Bureaucrats
- 6 Scribes

## Why It's Good For The Game
More SolGov content is nice! Especially when it comes to ships, for a faction that only has two existing at the moment, haha.

## Changelog

:cl: PositiveEntropy
add: The Solarian Port Authority Has Now Permitted Inkwell-class Vessels To Explore The Stars!
/:cl:

### CODE REVIEW

**Review by goober3 — CHANGES_REQUESTED** [review]
image
exterior signs / decals must be placed directly on the hull -- anything placed on a turf passthrough is dropped when a ship loads. also, please avoid wallmounts stacking like this. (even if they're on opposite sides of a wall!)

image
this is Bad!! please shift all of your posters 32 pixels into walls, for consistency's sake.

image
these spawners create abandoned crates, not crate loot! maintenance spawners can be used, if you want your crates to be filled with random junk.

image
make this area a storage bay, perhaps. this room does not look external to me!

image
move these satchels into the mining prep room, and make sure there's enough for each field engineer. you could probably put an ore box down here.

image
give them some Fruit and Veggies. moths cannot eat this!!

awesome ship!! I look forward to seeing it in-game.

**Review by goober3 — APPROVED** [review]
image
doubled up areas. change the second starboard maint area to a storage room. 

i'll be away from my computer for a few days after this review. so consider this an approval in advance. good job.

**Comment by Zevotech** [comment]
not sure if it was due to some fuckery but the bottom left ion thruster seemed to have a light fixture hanging off of it. might have gotten put there by mistake.

**Review by spockye — CHANGES_REQUESTED** [review]
image

unconnected pipe ( ARMOURY )

image

i'd say replace these with the vaccum suit type. these ones are a bit stronk for a cargo ship.

**Review by spockye — APPROVED** [review]

**Review by goober3 — APPROVED** [review]

**Pull request merged**
