### PR TITLE
Berbs

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
I'm not calling them biddle verbs.

Basically, adds verbs to a queue so that they won't be run if the MC is overtiming since by default BYOND will just run them even if it means the MC won't get much/any time. tl;dr possible lag/overtime reduction from verbs like input

Ports:
tgstation/tgstation#65589
tgstation/tgstation#68990
tgstation/tgstation#70647
tgstation/tgstation#71520

## Why It's Good For The Game
Overtime bad

## Changelog

:cl:
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
Urge to rename to biddle verbs overwhelming

**Comment by MarkSuckerberg** [comment]
I will kill you

**Comment by goober3** [comment]
biddle verbs

**Comment by MarkSuckerberg** [comment]
\>:C

**Comment by axelzonvolt** [comment]
just... meet in the middle
and call them

berbs

**Comment by thgvr** [comment]
birbs...

**Pull request merged**
