### PR TITLE
the great underwear purge

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
sprites from tg, skyrat, and my aseprite file
Done by me, various others I can't count, Halcyon, Onule
Medical clothes sprites from TG

Organizes sprite_accessories.dm into sane files

## Why It's Good For The Game
look good = better
better = good

## Changelog

:cl:
add: Resprites underwear/socks/undershirts, adds a bunch of new ones, greyscales some
add: Redesigns athletic shorts
add: Resprites the basic pants in loadouts
add: Hoodies, they're in loadouts. Couple colors selectable
add: Resprites organs, by Onule
add: Support for Kepori underwear/socks/undershirt
del: Some underwear/shirts were removed
del: Medical job alt outfits
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
i'll update pr body when im done. so far the scope has changed from just underwear

**Comment by MarkSuckerberg** [comment]
Ough!

**Comment by thgvr** [comment]
mother fuckeer

**Review by MarkSuckerberg — APPROVED** [review]
we're so fucking back

**Pull request merged**
