### PR TITLE
Re-adds Random Diseases

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
Ports <https://github.com/tgstation/tgstation/pull/57957>.
Walking over dried gibs will now have a chance to give you a randomgen disease, which is usually Bad.
Also ports assorted signals and small things needed to make Rot work.

## Why It's Good For The Game
I'd like to see people putting an effort into keeping areas cleaned.

## Changelog

:cl:
add: Walking on dried gibs will now have a chance to give you a disease
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
How do you treat diseases with this?

**Comment by Erikafox** [comment]
ghettochem or callling a medical ship

**Comment by thgvr** [comment]
I am really not sure about this. Original PR was barely even fun on stations.

**Comment by Erikafox** [comment]
> I am really not sure about this. Original PR was barely even fun on stations.

Could always give it a list - trim advanced symptoms (not like we use that system anyways) - increase time to gib drying

**Comment by Latentish** [comment]
Especially without viro around to vaccinate diseases, I don't really know how adding disease is going to make our gameplay loop more fun. I do think that giving incentive to clean up gibs and other messes is a good idea, but like, how debilitating can these diseases get? How easily can they spread? If they're normal tg diseases, I'm not super sure about this.

**Comment by Erikafox** [comment]
> Especially without viro around to vaccinate diseases, I don't really know how adding disease is going to make our gameplay loop more fun. I do think that giving incentive to clean up gibs and other messes is a good idea, but like, how debilitating can these diseases get? How easily can they spread? If they're normal tg diseases, I'm not super sure about this.

well it's advanced diseases so it varies

**Comment by rye-rice** [comment]
As of right now, this is probably not the best idea. Not because of the concept, but of how diseases work right now, where you need a random Chem to cure it.

**Comment by Erikafox** [comment]
yeah alright, I'll add some viro prevention stuff as outpost crates and trim the symptoms down.

**Comment by Zevotech** [comment]
once again the synthetic mains stay winning

**Comment by Latentish** [comment]
That's really kind of bandaid. I don't rally like the idea of this merging unless diseases fundamentally change. Like having a lifespan and not having a random chem be the cure.

**Comment by thgvr** [comment]
I had an idea floating around for a """"miasma"""" system that'd use pollution - but you could repurpose this rot component, and say, add like some purple-colored transparent smoke that increases disgust or something

**Comment by Zevotech** [comment]
> I had an idea floating around for a """"miasma"""" system that'd use pollution - but you could repurpose this rot component, and say, add like some purple-colored transparent smoke that increases disgust or something

im going to bring back the shetland corpse chamber specifically to chuck you into it

**Comment by rye-rice** [comment]
> > I had an idea floating around for a """"miasma"""" system that'd use pollution - but you could repurpose this rot component, and say, add like some purple-colored transparent smoke that increases disgust or something
> 
> im going to bring back the shetland corpse chamber specifically to chuck you into it

Have a corpse cannon to shoot at other ships like a bioweapon

**Comment by Zevotech** [comment]
> Have a corpse cannon to shoot at other ships like a bioweapon
the mongols did this. reinventing biological warfare.

**Comment by TypeVar** [comment]
With so little emphasis for viro on a lot of medical ships, I feel like this wouldn't be a fun or fair addition. If anything, it will just be a mild annoyance at best or an unfair crew-destroying event at worst

**Comment by axelzonvolt** [comment]
> With so little emphasis for viro on a lot of medical ships, I feel like this wouldn't be a fun or fair addition. If anything, it will just be a mild annoyance at best or an unfair crew-destroying event at worst

fun fact. 75% of the problems caused by a disease can be entirely solved with chemistry. the last 25% is only required for making a vaccine. which is also the only part that actually interacts with virology.

**Comment by BarteG44** [comment]
>fun fact. 75% of the problems caused by a disease can be entirely solved with chemistry. the last 25% is only required for making a vaccine. which is also the only part that actually interacts with virology.

good design 👍

**Comment by Erikafox** [comment]
meh

**Pull request closed without merging**
