### PR TITLE
Adds crop turtleneck

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
Keep scrolling

## Why It's Good For The Game
image

## Changelog

:cl:
add: Crop turtleneck undershirt
/:cl:

### CODE REVIEW

**Comment by meemofcourse** [comment]
THESE LIZARDS ARE GAY!!!! good for them. good for them

**Comment by BarteG44** [comment]
Do we have non crop ones? If not then they'd be a nice thing to bundle with this

**Comment by MarkSuckerberg** [comment]
image

**Comment by BarteG44** [comment]
And i haven't noticed them? Gawd daym

**Comment by Martinpachu** [comment]
YEAAAHHH WOOOOO YEAAAAHHH YEAAAAHHH!!!! WOOOOO!!!

**Pull request merged**
