### PR TITLE
Adds crate colors 

### PR DESCRIPTION
**Pull request by forg-man**
## About The Pull Request
adds six different crate colors to help players to keep cargobays organized

## Why It's Good For The Game

This PR adds more crate options to cargo and makes everything look nicer, especially on crate shelves.
## Changelog

:cl:
add: 6 new crates
imageadd: added 12 new crate icons
/:cl:

### CODE REVIEW

**Comment by forg-man** [comment]
clowncrate

**Comment by rye-rice** [comment]
Can't you already spray paint the crates?

**Comment by forg-man** [comment]
Yes, I made sure to choose different colors from the spray painted crates. and you can also combine colors with spraypaint to get even more results.
This also makes life easier for mappers

image
The ones on the left are spray painted color crates, the ones in middle are spray painted normal crates and the ones on the right are normal color crates.

**Comment by thgvr** [comment]
Can't say I'm convinced

**Comment by rye-rice** [comment]
Not very impressed either.  A system to change a crate into the crate variants or even making the other crate variants craftable would be cool and useful however, but this just seems, redundant at best

**Comment by forg-man** [comment]
Ok, Ill open another pr with that in mind

**Pull request closed without merging**
