### PR TITLE
Additional sprites for Vox - Inteq and NGR

### PR DESCRIPTION
**Pull request by firebudgy**
## About The Pull Request

Added Vox Variations for the HV outfit, the Blood-Red Hazard Vest and two NGR hard hats. Also resprites the Vox Vanguard Battlecoat to closer match the current iteration with significant help from Rylie/Retlaw34/Ryerice.

- Honorable Vanguard Beret
- Honorable Vanguard Battlecoat
- Vanguard Battlecoat
- Leather Satchel
- Blood Red Hazard Vest
- NGR Hard Hat
- NGR Foreman Hard Hat

image
image
image
image
(honestly this satchel looks pretty bad in general but I figured i'd get it out of the way)
image

## Why It's Good For The Game

Some of these sprites were some I saw people sad about lacking, and I figured that I might as well get off my lazy ass and do something about it. Knocked the HV gear out of the way and did a bit of a resprite for the Vanguard Battlecoat after being suggested to do it by a few people.

## Changelog

:cl:
add: New sprites for Vox! Vanguard and Honorable Vanguard Battlecoat sprite changes, NGR hard hats, and hazard vests!
/:cl:

### CODE REVIEW

**Comment by firebudgy** [comment]
I forgot to set the dirs on one of the sprite states, don't merge this yet

**Comment by firebudgy** [comment]
couple other things actually i'll need a moment to fix the rest

**Comment by firebudgy** [comment]
fixed everything

**Comment by meemofcourse** [comment]
we got vox honorable vanguard before we got vox frontie admiral it's fucking over

**Comment by firebudgy** [comment]
sigh. why do merge checks fail on every single one of my PRs?

**Comment by Leon9621** [comment]
> sigh. why do merge checks fail on every single one of my PRs?

Because of atmos...

**Comment by thgvr** [comment]
because nobody knows how to fix it

**Pull request merged**
