### PR TITLE
Tweaked Meta-Class

### PR DESCRIPTION
**Pull request by TypeVar**
## About The Pull Request
image

image

Reworks the Meta-Class to be more spacious, less underpowered, and generally kept up to date with current Shiptest standards.

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.
Unless..? 😳 
## Why It's Good For The Game
This adds:
~~-A selling pad~~
-1911 in weapon crate
-Lights! It is no longer pitch black
-Biogenerator in botany
-More supplies in crates, such as medkits, engineering equipment, toys, valuables, etc.
-Cook role

This changes:
-Dorms, botany, airlock and kitchen architecture
-some parts of engineering, mostly atmospherics
-Tiny fans to holofield (now with firelocks)
-Changes assistants to cargo techs
-Station engineer to ship engineer
-Quartermaster to Supply Officer (cooler QM)

This removes:
-MD role
-Captain role
-~~Laser guns in dorms~~ Now in weapon crate

~~A selling pad was added due to the fact that the ship's main function is cargo. Like other cargo ships such as the Luxembourg, I believe it is appropriate for this independent cargo ship to have a selling pad.~~

As for ballistic guns, they are an upgrade to the mini e-guns, while also being appropriate for an independent ship.

## Changelog

:cl:
tweak: the Meta-Class Freighter has been updated to fit modern standards better
/:cl:

### CODE REVIEW

**Comment by TypeVar** [comment]
oops ignore this for now

**Comment by Ebin-Halcyon** [comment]
dsakflsd;klfgd

**Comment by TypeVar** [comment]
shush it was meant to be a test

**Comment by Latentish** [comment]
Please change your changelog to actually reflect your changes as its the in game changelog. "Tweaked Meta Class" should be enough
If you're going to tweak this ship, please replace the tinyfans with proper holofields.
Please revert your engineer name change. "Engiqueer" funny as it is, is not an appropriate job name.
Why did you add a selling pad?
Why'd you swap out the lasers for ballistics?
I don't think you added them, but please cut down on the turrets by quite a lot.

**Comment by TypeVar** [comment]
> Please change your changelog to actually reflect your changes as its the in game changelog. "Tweaked Meta Class" should be enough If you're going to tweak this ship, please replace the tinyfans with proper holofields. Please revert your engineer name change. "Engiqueer" funny as it is, is not an appropriate job name. Why did you add a selling pad? Why'd you swap out the lasers for ballistics? I don't think you added them, but please cut down on the turrets by quite a lot.

The turrets were already there to begin with. I can cut them down, but from my experience they barely do anything in the first place. I added a selling pad because other cargo focused ships (such as the Luxembourg) has one.

I think the lack of RND, firepower, mining gear, engineering and medical equipment warrants it having a selling pad like the Luxembourg.

I swapped out lasers for ballistics because Apogee stated that it would be a good alternative to the mini e-guns. I also made sure that the ballistic guns I gave the ship are appropriate for an independent ship (that being a 1911 and a derringer). Besides, there are still laser guns on the ship, just in the weapons crate (as it did have before).

**Comment by TypeVar** [comment]
> Please change your changelog to actually reflect your changes as its the in game changelog. "Tweaked Meta Class" should be enough If you're going to tweak this ship, please replace the tinyfans with proper holofields. Please revert your engineer name change. "Engiqueer" funny as it is, is not an appropriate job name. Why did you add a selling pad? Why'd you swap out the lasers for ballistics? I don't think you added them, but please cut down on the turrets by quite a lot.

Do Holofields work? If so, what is a good ship to use as an example to set it up?

**Comment by Erikafox** [comment]
the delta rework has functioning holofields

**Comment by TypeVar** [comment]
image

Right that's done, how many turrets should I remove?

**Comment by TypeVar** [comment]
OK so I discovered that it is extremely easy to fuck up by forgetting to turn on holofields

**Comment by ZephyrTFA** [comment]
> OK so I discovered that it is extremely easy to fuck up by forgetting to turn on holofields

sounds like a skill issue to me

**Comment by TypeVar** [comment]
> > OK so I discovered that it is extremely easy to fuck up by forgetting to turn on holofields
> 
> sounds like a skill issue to me

A skill issue, yes. But a ship-ruining issue, considering that the ENTIRETY of cargo gets depressurized if one (1) silly cargo tech presses the wrong button

**Comment by Erikafox** [comment]
maybe toss some directional firelocks down next to the blast doors, so they close if someone does that.

**Comment by TypeVar** [comment]
> maybe toss some directional firelocks down next to the blast doors, so they close if someone does that.

that's actually a really good idea. I'll do that

**Comment by TypeVar** [comment]
Alrighty this is just about done I think. Anything else need changing?

**Comment by TypeVar** [comment]
When a maptainer is available, can someone review this?

**Comment by TypeVar** [comment]
Are the maptainers still on break? 🥺

**Comment by TypeVar** [comment]
Can someone take a look at this?

**Comment by TypeVar** [comment]
cooltext421874534514018

**Comment by Latentish** [comment]
I'm gonna say remove the sell pad and we can tm this.

**Comment by TypeVar** [comment]
> I'm gonna say remove the sell pad and we can tm this.

Ok I will in a bit

**Comment by Yellow-Mushroom** [comment]
Gave a full review for this in the disc starting here: https://discord.com/channels/837744059291533392/852010121080471583/1042621896119820358

A quick few fixes then hopefully this can get TM'd

**Comment by TypeVar** [comment]
Is this good to TM?

**Comment by TypeVar** [comment]
Did someone forget to TM this?

**Comment by Erikafox** [comment]
It's finals season, everyone has been busy.
You also need to properly fill in your changelog.

**Comment by TypeVar** [comment]
I changed dorms back to the original. I've uploaded an updated pic of the ship, then I'll do the changelogs

**Comment by TypeVar** [comment]
Uh oh

**Comment by Latentish** [comment]
If you get these checks cleared we can do a review for Tm.

**Comment by Erikafox** [comment]
Merge Conflict Resolution Reminder

**Comment by TypeVar** [comment]
Guh I forgot about this. Sorry, got busy with classes. I'll see about fixing this soon

**Comment by Latentish** [comment]
I'm going to draft this.

**Comment by Latentish** [comment]
Please update this pr soon, or close it.

**Comment by TypeVar** [comment]
Ah there we go. I think this is for the best. Been extremely busy with classes so I haven't really had the time to work on this, and probably will continue not to. Besides, the changes I made were minor so it's nothing really to be bummed about

**Pull request closed without merging**
