### PR TITLE
Donk co clothing

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

# As swifter said she would like to redo the luxemborg herself, the map changes were reverted and it's just the outfits / code now

image

Donk co clothing!

Right is Donk! Co. Customer Service Representative
Middle is Donk! Co. Manager

This also adds a limited use emag, was for the luxemborg to sell, but thats up to swifter to add now

## Why It's Good For The Game

Luxemberg was old, outdated, and wasn't played how it was supposed to be.
Hopefully this makes people want to play it like a merchant

## Changelog
:cl:
add: Limited use Emags
add: Donk co drip
fix: blue wall locker now has the correct texture
/:cl:

### CODE REVIEW

**Comment by UltraNumeron** [comment]
mostly a fan of this getting made a bit less focused towards being a powergamer miner ship but not much of the new color scheme compared to the old one, and maybe pre setup  the store area a bit with some display cases and racks  such  as while its a nice idea in theory to give the trading ship room to set up their own thing  in practice it will likely result in  being a bleak empty space that no one does that with. Otherwise like the new balance just not a fan of the new layout and aesthetic

**Comment by UltraNumeron** [comment]
Said this before in the discord but saying it in here again as its probably a better place, should replace the gpses  with crew pinpointers, as that would replace gamer loot finders that can ocasionally be used to find a ship if it on the off chance has a gps with a device that tells you the direction of a consenting trade partner. Thats as much as ic an say from just looking at it, if this gets tmd ill  provide more feedback when testing.

**Review by MarkSuckerberg — APPROVED** [review]
Looks good to me, haven't looked over map but the code/json is sound

**Comment by rye-rice** [comment]
At long last, conflicts fixed

**Comment by rye-rice** [comment]
As swifter said she would like to redo the luxemborg herself, the map changes were reverted and it's just the outfits / code now

**Comment by MarkSuckerberg** [comment]
@triplezeta

**Review by triplezeta — APPROVED** [review]
squid games

**Pull request merged**
