### PR TITLE
Adds bodysize options to all species

### PR DESCRIPTION
**Pull request by Recoherent**
## About The Pull Request
All roundstart species now have the bodysize preference shown in the editor. This means that, instead of needing to worry about sanitization and switching species to get it right, you can just change it for whoever directly.

## Why It's Good For The Game
now people can actually fix their scrungled birds

## Changelog

:cl:
tweak: All roundstart species have a bodysize option in character prefs now. Gone are the days of switching to human, setting your size to Normal, then switching back.
/:cl:

### CODE REVIEW

**Comment by Recoherent** [comment]
linter i added two sets of parenthesis and they are decidedly unpadded what are you on

**Comment by Recoherent** [comment]
been informed by a maint that one of the leads doesn't want this implemented. goodnight

**Comment by Recoherent** [comment]
on second thoughts, may as well keep it open for now until i recieve actual direct feedback

**Comment by Recoherent** [comment]
on third thought and some discussion, to make this functional but much less like, "debate required", i'm just going to rework this to add a bodysize option to every species' features, so that you may still be able to scrungle kepori, but at least you know WHY your kepori is scrungled when you do that to them, and it's an actual conscious decision

**Comment by Latentish** [comment]
Smallvox?

**Comment by Recoherent** [comment]
smallvox are already possible, this just makes it so that changing BACK from smallvox isn't stupid, and doesn't require a new player who just wanted to play one to try to figure out why their charslot is inexplicably fucked

**Pull request merged**
