### PR TITLE
Fixes Transport18 so you can take its beer engines. Adds a disclaimer to liquid engine code.

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
Subtypes the beer engines on Transport 18 so they can be disassembled and moved. Adds a disclaimer to prevent people from making the same mistake again. 
Beer engines have comically low thrust and take beer as fuel.  If you want to construct them yourself, you need beer bottles and microlasers.

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
You can now disassemble a ruin and take bits of it for yourself. This is good for immersion. The code disclaimer should prevent anyone else from making var-edited liquid engines that you sadly cannot steal for your own use.

## Changelog

:cl:
add: beer engine subtype
add: disclaimer for people seeking to use liquid engines
fix: transport 18's engines can now be salvaged. People remain amazed how the transport could fly on such a material.
/:cl:

### CODE REVIEW

**Comment by Calyxman** [comment]
Why not make it a whole ship

**Comment by Erikafox** [comment]
It's well. A ruin. Ruined.

**Comment by Calyxman** [comment]
no reason why we can't have transport 18 ship either

**Comment by MusselMain** [comment]
> no reason why we can't have transport 18 ship either

We already have far too many ships in code, adding another transport isn't a great idea.

**Comment by Latentish** [comment]
Extremely funny add.

**Comment by triplezeta** [comment]
> no reason why we can't have transport 18 ship either

out of scope

**Comment by Latentish** [comment]
hahah cool tming this if the checkers swag on that daddy

**Pull request merged**
