### PR TITLE
Removes the Autodoc

### PR DESCRIPTION
**Pull request by atteria**
## About The Pull Request
Removes the autodoc and all references to it.

Tested locally.

## Why It's Good For The Game
The autodoc is an anti-interaction feature. Everyone seems to hate it, even those that use it.

## Changelog
:cl:
del: Removed the autodoc.
/:cl:

### CODE REVIEW

**Comment by Sylphily** [comment]
Instead of removing the autodoc code, just removed from the tech web, it could be reused as a ruin reward

**Comment by atteria** [comment]
@someguyjust 
A bad feature is a bad feature, even if you make it uncommon.

Adding an autodoc as a ruin reward won't make it's existence on a ship detract from the point of the game, which is player interaction.

**Comment by TallDeekus** [comment]
At the very least it could be adminspawn only, as a possible reward or if a ship doesn't have anyone in particular who specializes in medical, it doesn't need to be outright removed.

**Comment by Latentish** [comment]
The only real use for the autodoc is implants, because there are a million implants and getting a person to put you under and implant them all is time consuming qnd annoying.

**Comment by Latentish** [comment]
Actually I would be perfectly fine with this pr if there was something to go with it that made it more convenient for one surgeon to implant a large amount of implants.

**Comment by zestybastard** [comment]
> Actually I would be perfectly fine with this pr if there was something to go with it that made it more convenient for one surgeon to implant a large amount of implants.

it's not actually that time-consuming for a surgeon considering you can just do steps simultaneously when it comes to organ manipulation on multiple body parts

**Comment by Latentish** [comment]
> > Actually I would be perfectly fine with this pr if there was something to go with it that made it more convenient for one surgeon to implant a large amount of implants.
> 
> it's not actually that time-consuming for a surgeon considering you can just do steps simultaneously when it comes to organ manipulation on multiple body parts

That only works when you aren't doing both extensive amounts of implants, and most organs. It's also not well supported to show what dtep you're at on every single operation you're doing, when it's several on every part of the body.
Autodoc is a saving grace when you have upwards of 20 implant and replacements. But again, if any change were made to make that process less messy and more convenient, this PR would be fine. But there isn't.

**Comment by Kapu1178** [comment]
a large amount of implants should take a large amount of time.

**Comment by Latentish** [comment]
> a large amount of implants should take a large amount of time.

Why? You already pay for that in mats, research points, and time to get both the implants and the autodoc. It's already a good amount of work just to prep for it, why should the process have to take excessive amounts of time? That seems counterintuitive to this pr, given that's time without player interaction, as one of them will certainly be under anesthetics..
I don't see why the prep and the operation should both take a boatload of time. And making one player be unconscious for more time than is  neccessary is both unfun and puts more pressure on docs to speedrun surgery.

**Comment by atteria** [comment]
Of the codebases I have played, surgery is the most quick and simple here.

Surgery does not even require anesthetics here.

**Comment by Latentish** [comment]
> Of the codebases I have played, surgery is the most quick and simple here.
> 
> Surgery does not even require anesthetics here.

Anastherics are technically not required on most stations with the sleep verb or just being in an emergency or rushed medbay. And I can name faster surgery systems. My other point was that it's messy to keep track of without taking more than 10 minutes.

**Comment by Latentish** [comment]
Instead of just removing the autodoc, maybe add an additional upgrade to the optable table or computer to track all operations as well, that also takes those research levels. Because the autodoc is the only way to do so cleanly. It's asking for a replacement feature to go with the feature cut.
Edit: they do, and my point is moot.

**Comment by Valorium-RB** [comment]
> > > Actually I would be perfectly fine with this pr if there was something to go with it that made it more convenient for one surgeon to implant a large amount of implants.
> > 
> > 
> > it's not actually that time-consuming for a surgeon considering you can just do steps simultaneously when it comes to organ manipulation on multiple body parts
> 
> That only works when you aren't doing both extensive amounts of implants, and most organs. It's also not well supported to show what dtep you're at on every single operation you're doing, when it's several on every part of the body. Autodoc is a saving grace when you have upwards of 20 implant and replacements. But again, if any change were made to make that process less messy and more convenient, this PR would be fine. But there isn't.

The point of this PR is that people are just powergaming getting every single implant and becoming a technopriest's wet dream, which isn't something we as an admin team (and many members of the player base, evidentially from the conversation in #general that prompted this PR) really want. Half the reason there are so many implants is so you actually have to choose how long you wanna spend under the knife vs. how much extra utility you want to have. Plus, the research and materials sink is moot: by the time you have hyper advanced implants, you probably have literally everything else in the tech tree, it's not hard. Materials are ridiculously abundant and the amount of time it takes to build an autodoc and shove implants in it is approximately nil. We're not interested in having the autodoc any longer.

**Comment by Latentish** [comment]
> > > > Actually I would be perfectly fine with this pr if there was something to go with it that made it more convenient for one surgeon to implant a large amount of implants.
> > > 
> > > 
> > > it's not actually that time-consuming for a surgeon considering you can just do steps simultaneously when it comes to organ manipulation on multiple body parts
> > 
> > 
> > That only works when you aren't doing both extensive amounts of implants, and most organs. It's also not well supported to show what dtep you're at on every single operation you're doing, when it's several on every part of the body. Autodoc is a saving grace when you have upwards of 20 implant and replacements. But again, if any change were made to make that process less messy and more convenient, this PR would be fine. But there isn't.
> 
> The point of this PR is that people are just powergaming getting every single implant and becoming a technopriest's wet dream, which isn't something we as an admin team (and many members of the player base, evidentially from the conversation in #general that prompted this PR) really want. Half the reason there are so many implants is so you actually have to choose how long you wanna spend under the knife vs. how much extra utility you want to have. Plus, the research and materials sink is moot: by the time you have hyper advanced implants, you probably have literally everything else in the tech tree, it's not hard. Materials are ridiculously abundant and the amount of time it takes to build an autodoc and shove implants in it is approximately nil. We're not interested in having the autodoc any longer.

Yes, I've conceded this point in gen-dev already, and have retracted my prior points.

**Comment by Latentish** [comment]
image
image

**Comment by jupyterkat** [comment]
bikeshedtest bikeshedtest

**Comment by MarkSuckerberg** [comment]
Seems that this is generally agreed to be for the best. I'm sure someone could make a better version in a similar vein that's more complex (and actually complete, including a proper icon).

**Pull request merged**
