### PR TITLE
Icemoon icecropolis

### PR DESCRIPTION
**Pull request by Latentish**
## About The Pull Request
While the necropolis as other servers know it may never see its completion, or a real place on shiptest (IE the giant skull with an inaccessible city behind it); this PR adds what I call the Icecropolis. This adds a new ruin to the Ice Planet called the "Bloody Hallow", inside are a number of minibosses, an Ashdrake named "The Priest", plenty of places to visit, mobs, tendrils, loot, and Ashwalkers! Come pay a visit to the Bloody Hallow  or live there as a funny lizard.
image
image
image
image
image
image
image
image
image
image

There are 2 tendril chests on the map to start (some chests are not filled).
There are 5 mid tier dungeon loot spawns.

A lot of loot lies behind doors that are locked until their respective bosses are killed. Some of this loot includes:
Legionnaire: Tarot card deck and a midloot spawn
Legate: Meat hook and a midloot spawner
BDM: An ATV, KA with trigger guard mod, and a load of others
Herald: diamond tipped drill, ashwalker transformation serum, adamantine gear
Ash drake: teleporter boards, ash drake chest, dragon's blood, staff of healing, spell blade

Bosses are not as strong as their naturally spawning counterparts.
Ashwalkers start with a bit more equipment than their traditional cousins due to the increased difficulty.

## Why It's Good For The Game
This pr adds another map to the ice planet, which only has so many ruins at the moment. This also adds another spawn for Ashwalkers, with more challenging and compact content to access.

## Changelog
:cl:Phoaly
add: Adds A new ruin to the Icemoon, the Bloody Hallow.
code: Adds areas and a datum for the Icecropolis (Bloody Hallow) map.
refactor: Refactors a death proc making a specific set of doors open into a mapper helper object anyone can use.
tweak: tweaked icemoon ashdrake map to use new code refactor.
add: Adds new component file to the DME for the refactor to work.
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
This map is at the testing and tweaking stage. More updates to come!

**Comment by Latentish** [comment]
I'll run another test later.

**Comment by NiftyRyanyan** [comment]
Looks cool, but why add it to the ice planet instead of lava planet?

**Comment by Latentish** [comment]
> Looks cool, but why add it to the ice planet instead of lava planet?

Because the ice planet has the least number of ruins, and the lavaland planet has like 40

**Comment by Sun-Soaked** [comment]
a few things:
-The goliath broodmother doesn't drop any implicit loot (this is handled by the tumor) and is *incredibly, lethally dangerous* in tight corridors, especially when surrounded by indestructible walls. This is ditto for the legionnaire, but it's less of a threat to the point of being more handle-able.

-I'd recommend faffing about a bit more with the brick patterns and necro walls and enriching/expanding the cavern sections, especially in the ashwalker section. 

-Considering that it currently doesn't have an effective spawn ingame, you might want to consider adding a Legion(megafauna) spawn as the final challenge within the ruin.

-Possibly throw a bit of necropool loot around? Considering the gauntlet of 3 rewardless elites, a bunch of carp-type simplemobs with relatively high health, two megafauna I can see, and a lot of pitfalls and spawners, the loot onsite is looking a little anemic.

**Comment by Latentish** [comment]
This is good feedback, and while I added some loot and mixed up enemies in the last patch, I can see your concern. I'll look into this, thanks =)

**Comment by Latentish** [comment]
I think this is pretty much ready for a testmerge, unless there's any last minute catches someone finds!
Time to work on the next one =)

**Comment by UltraNumeron** [comment]
Played this today as a hyena captain, was hard but manageable difficulty wise and i loved the design however there are some pretty big issues.

- You probably should not hide loot behind rusted walls  that leave no indication anything is there that are meant to be rewards for bosses, itd probably be a better idea to make them reinforced windows so you can see whats there and still gotta fight the boss.

-Some of the bosses wander around naturlaly quite ab it making it pretty trivial to grab the loot without fighting them in some cases like with the herald and the drake, making it so theres not much reason to fight em, and ones like the broodmother despite being a gatekeeper is trivially easy to run around.

Dunno whats up with the disciple, weird red lad in a room with chests ibehind reinforced windows that dont have anything in em but metal rods.

-The entrance romos a bit iffy too cause the crystal goliath gets a bit wacky and opened cryo pods appear to clip in there somehow?

-Loot pool could be varied up a little definetly one of the better ruins alot of it just feels like very generic lavaland stuff though as alot of it is just the regular tendril pool, could maybe vary it up a bit and give the elites roooms their unique boss drops or such, alot of it feels like if you got to this point you probably dont need it but yeah.

good ruin from playing it justh as some big flaws

**Comment by Latentish** [comment]
2 more planned updates before this is finished:
1. Rethink and rebalance the loot to make some fights more interesting
2. Make a new turf subtype for every turf that clashes with the environment
    2.a. Rip out every single fucking turf and replace them with the new turf subtypes

**Comment by Latentish** [comment]
Ash drake now needs a new subtype that only retaliates when attacked. God knows how that's supposed to happen.

**Comment by Latentish** [comment]
Funny dragon room
image

**Comment by Latentish** [comment]
An update to the pictures and loot list soon, but otherwise (hopefully) ready for testmerge.

**Comment by Latentish** [comment]
Pictures and loot pool updated to reflect most recent changes, and now seeds have some extra progression.

**Comment by Latentish** [comment]
I might be biased in this opinion, but I think the live test for this map went really well and I think this is ready for a proper review.

**Comment by MarkSuckerberg** [comment]
I can dig it, I think we let the test today finish and let people give their feedback if they have any, and I'll merge it tomorrow morning if it's all good (and it probably will be).

**Comment by Latentish** [comment]
> I can dig it, I think we let the test today finish and let people give their feedback if they have any, and I'll merge it tomorrow morning if it's all good (and it probably will be).

That sounds nice to me! I hope everyone likes it!

**Comment by Latentish** [comment]
This needs further testmerge testing to make sure the injectors  actually do their job. If not it'll need a code touchup.

**Comment by Ketrai** [comment]
It's still a bit weird that this spawns on ice planet. Fine once you get in. But feels out of place otherwise.

**Pull request merged**
