### PR TITLE
Galaxy-Class Exploratory Vessel

### PR DESCRIPTION
**Pull request by coleminerman**
## About The Pull Request

The Galaxy-Class Exploratory Vessel is a new model of ship recently designed and put into service by Nanotrasen. It is designed as an extremely cheap (though still effective) surveying vessel, with the purpose of travelling to as-of-yet unexplored systems, mapping them out, surveying the mineral wealth of each celestial body, and reporting this data back to Nanotrasen. They were designed to be as cheap, quick to produce, and carry as little crew as possible so that Nanotrasen can send them out in massive numbers to survey and map out the frontier as quickly and cost-effectively as possible for potential future development. These ships are designed to be expendable, though of course the crews are never told that part.

Along with the standard planetary survey and communications gear, the Galaxy-Class comes with a cryo sleeper, four hardsuits, a microwave, two day's worth of rations, enough mining equipment to outfit two crewmembers, a basic medical setup including four blood packs, a simple surgical suite, and an oxygen damage treatment kit, an autolathe, an R&D board, an ORM board, and enough oxygen to last the usual trip length these ships are sent out on. This is considered to be the essential "bare minimum" planetary survival package, along with additional gear that NT determines the crew may need on their mission. Due to the design of the wings on the ship, the ship is capable of gliding through the air without the power of engines while within an atmosphere.

The design of this ship is based off of Lego's Set 497 Galaxy Explorer (1979) and Set 10497 Galaxy Explorer (2022 reboot), the latter of which I actually have and used as a model while designing the outline of this ship. Special thanks to Martinpachu for helping me with the name, and Piper for helping me with the decals and making the shape look natural.

## Why It's Good For The Game

We've got a bit of a lack of NT ships, and I have had this idea for a ship since the Lego set it's based on came out. On top of that, it is a faction-aligned building-focused ship for all your building and testing needs, and I honestly haven't seen many of those either.

## Changelog

:cl:
add: Added the Galaxy-Class Exploratory Vessel
/:cl:

galaxyexplorer
10497_alt1

### CODE REVIEW

**Comment by Valorium-RB** [comment]
Oh! My dad had one of these as a kid, and gave them to me. I think I still have it lying around, semi-assembled.

**Comment by Latentish** [comment]
This vessel honestly feels like a sugarcube successor, and I'm not too fond of pill successors in general.

Those engines in the back also don't work.

**Comment by coleminerman** [comment]
> This vessel honestly feels like a sugarcube successor, and I'm not too fond of pill successors in general.
> 
> Those engines in the back also don't work.

The two engines in the back are not meant to work. They're for decoration purposes since we do not currently have functioning large thrusters. If those ever get added, I'll probably go back to this ship and update it with them. For now, though, they're decorative.

As for the sugarcube successor thing, it was certainly not meant as that though I do see what you mean. It _is_ meant to be cramped, undersupplied, small, and cheap, though, so I think that actually does fit what I was going for.

**Comment by Latentish** [comment]
The Maptainers have voted to deny this PR. Apologies.

**Pull request closed without merging**
