### PR TITLE
Removes nagivationally challenged

### PR DESCRIPTION
**Pull request by tiramisuapimancer**
## About The Pull Request
Removes the Navigationally Challenged quirk and everything that comes with it

## Why It's Good For The Game
Shiptests are way too tiny for the quirk to ever have any use, even the shiptests that have nav beacons at all (some of them do, but not most) and it just leads to pinpointers everywhere because new players are forced to having the quirk and can't even redeem it for a costume

## Changelog
:cl:
del: Navigationally Challenged quirk
/:cl:

### CODE REVIEW

**Comment by tiramisuapimancer** [comment]
OKAY, so apparently some of these maps are actually set up for wayfinding to work on them. I'll leave this up so I can gather opinions on if I should: 
1. Close this PR entirely
2. Change the scale of the PR so that it doesn't enforce navigationally challenged on new players, but keeps it overall
3. Continue removing Nav. Challenged by removing the wayfinding variants of navbeacons from shiptests that had the care put into them to have them in the first place

**Comment by AsciiSquid** [comment]
3. Ships are too small for its intended purpose. The few that support it really just get used to track the general position of the ship when off planet.

**Comment by ZephyrTFA** [comment]
You need to remove the wayfinders from the ships that have them for the checks to be happy

**Comment by tiramisuapimancer** [comment]
I'm aware, it's just that I have no idea if I should or not without more people's opinions

**Comment by tiramisuapimancer** [comment]
Well I got no other opinions besides Squid's but I agree with him so I'm gonna go ahead and correct the wayfinder beacons

**Pull request closed without merging**
