### PR TITLE
Goggle resprite

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Resprites most "goggles" in the game

Huds are untouched.

## Why It's Good For The Game

image
Screenshot_3485

## Changelog
:cl:
imageadd: resprites goggles
/:cl:

### CODE REVIEW

**Comment by Ebin-Halcyon** [comment]
Woo yeah!!

**Comment by Apogee-dev** [comment]
Can you also add a preview of the on-mob sprites to your PR?

**Comment by rye-rice** [comment]
> Can you also add a preview of the on-mob sprites to your PR?

ye, done

**Comment by Apogee-dev** [comment]
Looks good, ship it

**Review by triplezeta — APPROVED** [review]

**Comment by Fikou** [comment]
approved by sprite people

**Pull request merged**
