### PR TITLE
renames the cybersun raincoat to the cybersun labcoat

### PR DESCRIPTION
**Pull request by triplezeta**
## About The Pull Request

you're pretty sure this is just a raincoat

## Why It's Good For The Game

its a labcoat!!

## Changelog
:cl:
spellcheck: renames the cybersun raincoat to the cybersun labcoat
/:cl:

### CODE REVIEW

**Comment by Valorium-RB** [comment]
Isn't it, like, a see-through plastic slicker, though?

**Comment by triplezeta** [comment]
yes and it's sold (and labelled in the loadout) as a labcoat

**Comment by Valorium-RB** [comment]
Ah, very silly of me

**Comment by MarkSuckerberg** [comment]
nice

**Pull request merged**
