### PR TITLE
Changes the Kansatsu-class to Aspawn

### PR DESCRIPTION
**Pull request by firebudgy**
## About The Pull Request

Changes the Kansatsu-class to be aspawned. Contact an admin if you would like to have it spawned in.

## Why It's Good For The Game

Maptainer request.

## Changelog

:cl:
balance: Kansatsu has been removed from the player-accessible ship pool.
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
Rest in shit, oldsyndie scum.

**Comment by firebudgy** [comment]
Another ship sterilized. Another ship unplayed.

**Comment by Madtankdriver** [comment]
I think they are remapping it so that's why they made it aspawn? I'm not sure.

**Comment by Apogee-dev** [comment]
The remap will also be aspawn. This is a permanent change.

**Pull request merged**
