### PR TITLE
Valor-Class Field Care Crusier

### PR DESCRIPTION
**Pull request by meemofcourse**
## About The Pull Request
valor3

Did something go terribly wrong? Do you have wounded? Are _you_  wounded? Do you have money? You're in luck! The Valor-Class is Inteq's medical component of their fleet, and provides a great service for a meager* fee! Armed with a tiny patient recovery vessel and spacious medical facilities, this flying field hospital is ready to provide rapid tactical care for all that ails you (beyond the mental scarring of losing all your friends). This comes at the expense of relying on other ships for food, research or armaments.

It is staffed by:
* 1 Vanguard
* 1 Honorable Corpsman
* 3 Corpsmen
* 2 Enforcers
* 2 Recruits

## Why It's Good For The Game

it's the inteq medical ship it uses the inteq content

## Changelog

:cl:
add: Valor-Class Field Care Crusier
add: Haste-Class Ambulance
/:cl:

### CODE REVIEW

**Review by spockye — CHANGES_REQUESTED** [review]
image

wild decal

image

unconnected atmos. Scrubbers need a exhaust 

image

holofields need to be connected to the powernet

image

airlocks dont work if you dont give them a way to cycle air

image

a lot of rooms are missing air alarms

image

a lot of doors seem to be missing firelocks
ALSO not seeing any fire alarms!

image

flooring under window

image

two helmets
one suit 

image

accidental glass? (already a full stack under the metal)

image

i'd say make these walls non-diagonal

image

missing corner decal (also that wall is also diagonal. wont really fit with the decalling)

**Review by Erikafox — CHANGES_REQUESTED** [review]
StrongDMM_487dSP5iRP
If you're putting the /loaded mount type, they don't need a second defib.
StrongDMM_KXe9xIudZq
clean your wires up here, make it more organic

**Review by Apogee-dev — CHANGES_REQUESTED** [review]
Please just replace all of your walls except for external ones that you specifically want angled with the nodiag variant. It'll save a lot of headaches.

**Review by Erikafox — CHANGES_REQUESTED** [review]
The docking port on the lower half means that the subshuttle will not land in the bay.

I've heard issues about the prechargers on the subshuttle, make sure they're wired properly

**Review by Apogee-dev — CHANGES_REQUESTED** [review]
-The holofields and blast door on the ambulance need to be at the edge of the ship so patients don't need to cross a tile of exposed space to board it when it's docked to the exterior of a ship.

-Please replace the "public" airlocks with the public/glass variant, or use green airlocks for rooms like dorms and cryo.

-Just use grunge airlocks or other variants instead of hatch airlocks inside the nacelles; it doesn't make sense for crew to have to crawl through hatches when moving e.g. from the medical treatment center to the recovery room. The same applies for the main hallways into the nacelles; they're presumably high-traffic areas. You can use maint hatches instead of yellow engineering airlocks for the thruster rooms.

-All of the hallways into the wings are only 1 tile wide. This can cause traffic jams, especially when dragging bulky objects. Either make both 2 tiles wide or make the larger ones 3 passable tiles wide. Yes, this will mean eliminating the lattices over elevator floors that you like, but there's no real way around that.

-You can probably use white tiles in the medical wing where you currently have grey ones. Both dark and white work for medical areas imo but grey ones really don't.

-Remember to give the med beds medical bedsheets.

**Review by Apogee-dev — DISMISSED** [review]
Remember to replace all of the walls except the exterior corners you actually want smoothed with the nodiag variant. You have a few weird internal corners that end up smoothing when they should not, like at the security desk.

You have some misplaced corner decals in the cargo loading areas.

Remember to check the floor tiles under your doors and give them a good texture and potentially decals (see Colossus and Talos for reference), a few doors still have default grey tiles and they look more than a little off.

Consider varying the floor tiles in cargo. Note how both the Colossus and Talos use a different floor texture in the "walkable" parts of cargo compared to the cargo storage areas.

Also please edit the ambulance as mentioned in the previous review and depicted in the image below:
example

**Review by spockye — CHANGES_REQUESTED** [review]
image

injector is piping_layer 3, make it 4!

image

think it might look better if you move this one elsewhere

**Comment by Latentish** [comment]
Poking maptainers to update reviews. Please fix your merge conflict and integration test errors.

**Comment by meemofcourse** [comment]
> Poking maptainers to update reviews. Please fix your merge conflict and integration test errors.

there aren't any merge conflicts and i can't fix the int checks because it's a subshuttle ship

**Comment by Latentish** [comment]
> > Poking maptainers to update reviews. Please fix your merge conflict and integration test errors.
> 
> there aren't any merge conflicts and i can't fix the int checks because it's a subshuttle ship

You're entirely correct and I need glasses.

**Review by Zevotech — CHANGES_REQUESTED** [review]
## General fixes needed
Both engine rooms, the bathroom, custodial room and the EVA storage room lack lightswitches. I'd make the custodial room and/or the bathroom use the canteen areas to reduce APC bloat. This ship has major power issues which ill bring up later in the PR.

The "Surgical Bay" has a lightswitch in both surgery rooms despite them having no lights in them. I'd just wrap the two rooms into the main medical area or expand the area into the hallway.

Security Office has no access restrictions. Please make it so the vanguard and enforcers (and maybe Hon. Corpsman) are the only ones able to access it.

Remove the shuttle expansion permit from the vanguards locker. As far as I know it is no longer mandatory for ships and using it will only break the many shutters and blast doors on this ship. A medical ship of this size should not need to expand anyways.

Sign overlap.
image

The paramedic medical webbings come pre-stocked with crew monitors and prox-crew pinpointers. Either remove the upgraded pinpointers or give them empty webbings to stock themselves.
image

## Now onto the power issues.
Take a look at the power usage.
image
This is a fairly large ship with **lots** of rooms having to supply itself off of 20-60 kW of power using plasma they have to buy or mine and refine themselves. It also has 6 ion engines (30kW draw when charging them on 5kW each) and a massive holofield in the cargo bay that guzzles power and has to also charge the subshuttle. 

You can either give them uranium pacmans for better fuel efficiency, or what I would do is add an artificer slot and put some spots for solar panels in the unused space outside the ship. This way you could have some of the solar panels start missing or broken and give the artificer/recruits something to do by fixing them. I'd also recommend merging areas of small rooms to reduce on the amount of APC's to manage by combining the areas of places like the dorms and "crew quarters" laundry room to use the same APC on one area. Rooms like the custodial closet or EVA/Supply storage really do not need to have their own entire area and APC with the power issues this ship is bound to run into.

The subshuttle itself cannot power its own holofields unless you maybe do some jank to wire them to the prechargers. As much as I love the tiny form factor, I'd expand it to a 5x5 to give it room for an SMES or generator and maybe some more room for the medical crew. Making it a 5x5 and adjusting the cargo bay dock to fit it as such would also make it symmetrical.
When the subshuttle docks to the ship while the ships holofield is on, it shuts it off due to the powernet updating. I sadly see no way to fix this besides moving the shuttle dock out of the cargo bay, so just keep it in mind, no change needed for this unless you want to try it.
image

**Comment by Zevotech** [comment]
image
oh and theres a lightposter i missed

**Comment by Zevotech** [comment]
image
airlock also has no lightswitch and has its own apc, merge it into the infirmary area.

**Comment by meemofcourse** [comment]
can you do these in one post instead of just p.s. (p.s.) ((p.s.))

**Comment by Zevotech** [comment]
I Tried im Sorry i only just noticed these after making it

**Review by Zevotech — APPROVED** [review]
You Have Passed The Test! This should be TM'ed at least once for player feedback and then merged. Good Ship.

**Comment by Apogee-dev** [comment]
You should probably put a comms relay on this thing like the one the Colossus has, so it'll link up to a Talos if one is present. Past experience with other comms ships (the Ranger) indicated that relying on the ship to install comms on friendlies means comms will either never get set up or just get set up for everybody regardless of faction.

**Comment by Zorazi-Teo-Daedalus** [comment]
I'm not sure what the point of giving a medical techfab without an RND console is but I'm not a fan of it given most other medical ships have it save for like the Paracelsus. Aside from that, no rezadone feels weird on a hospital ship, not that rezadone is hard to acquire anyway, but rather it just feels like something a hospital craft should start with.

**Comment by Apogee-dev** [comment]
> I'm not sure what the point of giving a medical techfab without an RND console is but I'm not a fan of it given most other medical ships have it save for like the Paracelsus. Aside from that, no rezadone feels weird on a hospital ship, not that rezadone is hard to acquire anyway, but rather it just feels like something a hospital craft should start with.

aegis, asclepius, and li tieguai- in other words, every medship except the box and paracelsus- also don't come with rezadone. and that's because they're both meant to start with an excellent stock of medicine.

**Comment by thgvr** [comment]
ship ?

**Pull request merged**
