### PR TITLE
Removes edgy joke

### PR DESCRIPTION
**Pull request by tiramisuapimancer**
## About The Pull Request
Removes the edgy human trafficking joke poster. It was originally my addition and I will politely request that I would prefer to not have it exist in the codebase anymore if it is somehow deemed that this removal is otherwise inappropriate.

## Why It's Good For The Game
It was never that funny actually.

## Changelog

:cl:
del: Removed the edgy human trafficking/SGT joke poster
/:cl:

### CODE REVIEW

**Review by rye-rice — APPROVED** [review]

**Comment by thgvr** [comment]
soulless....

**Review by rye-rice — CHANGES_REQUESTED** [review]
some maps apparently use this poster, can you change the instances used in maps to something else so it doesn't error?

**Comment by tiramisuapimancer** [comment]
on it

**Comment by tiramisuapimancer** [comment]
did this in VSC and not through SDMM but hopefully doesnt break anythng

**Review by rye-rice — APPROVED** [review]

**Comment by FalloutFalcon** [comment]
Could you put up an image of it just for clarity of what your removing? I don't think i have ever seen it in game? icon_diff is unreadable

**Comment by rye-rice** [comment]
image

this is the poster in question

**Pull request merged**
