### PR TITLE
SSlag_switch from /tg/

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request

Ports:
- tgstation/tgstation#62999
- tgstation/tgstation#59717

and adds a few shiptest-specific toggles as well to better take advantage of the system.

## Why It's Good For The Game

Recently lag has become a bit more of an issue here, and I think I would rather we be able to play than force ourselves to suffer while we slowly work on perf improvements.

## Changelog

:cl:
admin: Adds lag switch toggles from /tg/, ONLY use them when the lag becomes unbearable!
/:cl:

### CODE REVIEW

**Comment by Erikafox** [comment]
lag is solved forever

**Comment by MarkSuckerberg** [comment]
so true

**Comment by Sun-Soaked** [comment]
image
no way I just saw this one while looking for atom comsigs

**Comment by MarkSuckerberg** [comment]
we do a little lag mitigation

**Pull request merged**
