### PR TITLE
PGF Content Part One

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
The lizards are here
Sprites are all done by me, guns by Rye, except for the beam projectiles, those are from Eris and I'm fairly sure INFRARED_BARON made them.
TODO:
- [x] Finish up all current sprites
- [x] Godforsaken Inhands
- [x] Icons
- [x] Firearms/other weapons

## Why It's Good For The Game
I like lizards

## Changelog

:cl:
add: Pan-Gezenan Federation Asset Pack (Part One)
/:cl:

### CODE REVIEW

**Comment by Imaginos16** [comment]
We're so back bros we're so back.

**Comment by Geoengi** [comment]
Lizards. Stay. Winning.

**Comment by thgvr** [comment]
soon

**Comment by thgvr** [comment]
integration failure is not my fault i swear

**Comment by thgvr** [comment]
godd

**Comment by Zevotech** [comment]
what if you wanted to get ints to pass but check said [WOLF COULD NOT BE DELETED. FAIL.]

**Comment by MarkSuckerberg** [comment]
that just happens sometimes okay

**Comment by thgvr** [comment]
im having a break down

**Comment by thgvr** [comment]
Guns and stuff done (read: need balancing, but probably fine), all the icons should work, see you when I get the motivation to do inhands and more sprites.

**Comment by Imaginos16** [comment]
go lizard boy go

**Comment by thgvr** [comment]
AAAAAAAAAAAAAAA

**Comment by thgvr** [comment]
soon. classes alsmot done

**Comment by MarkSuckerberg** [comment]
Lizsaderd

**Review by Imaginos16 — APPROVED** [review]
Fire

**Comment by Imaginos16** [comment]
*thump

**Comment by Imaginos16** [comment]
attempt numero dos

**Pull request merged**
