### PR TITLE
Adjusts vending machine stocks to reflect ship populations and various other changes to vendors

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
1. This PR lowers the amount of loot in gameplay item vendors such as the YouTool, NanoMed, and Frontier Equipment Vendor to better fit the amount of people on ships. The NanoMed was the worst offender, carrying enough medical supplies to stock an entire ship for the round for free.
2. Removes the Magivend, because it doesn't have a purpose anymore. Wizards aren't real and you will never encounter this vendor outside of the centcomm wizard location.
3. Removes the mining point card and mining access card because they are both mostly useless and are no longer in the mining vendor.
4. Removes the unused Pubbystation vendors.
5. Fixes the weapon selection on the NT marine vendor to have energy weapons and removes the eswords from all 3 marine vendors.
6. Reflavors the Dutch hot coco to "Pearl Hot Chocolate" to fit in with the lore. Also adds the Cafe Latte and Soy Latte to the coffee vendor.

<details><summary>Images of affected vendor stocks.</summary>

coffeev
toolv
image
image

</details>

## TODO: Reflavor equipment vendors as bulk specialized storage instead of commercial vending stations
Vendors suck! I hate them! They're all free! They shouldn't have that much stuff! 
Vendors like the NanoMed just had too many things in them for a ship to reasonably have. 
On a different note, the changes to the mining vendor now should make it more acceptable in terms of balance. Mining points are still a pain in the ass and I might change it to just use cash so miners can use a portion of the credits they find.

## Changelog

:cl:
del: Some vendors now have far less stock and a smaller variety of items to compensate for being free and not on a station
del: Removed Magivend vendor
del: Removed Mining points cards and mining access cards
del: Removed Unused Pubbystation vendors
del: Removed eswords from marine vendors
add: NT marine vendor now gives energy guns for coupons and stocks energy gun cells
add: Cafe and Soy Lattes are now available in the coffee vendor
fix: Dutch Hot Coco is now Pearl Hot Chocolate to be lore compliant
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
Give me feedback on these and suggest other vendors that need changes.

**Comment by meemofcourse** [comment]
can you add moth vendor

**Comment by Zevotech** [comment]
okay

**Comment by Zevotech** [comment]
mothvendor (joke)

https://github.com/shiptest-ss13/Shiptest/assets/95449138/521ad8bc-41f7-4bf1-9482-877ba3ca546f

**Review by MarkSuckerberg — APPROVED** [review]
very nice

**Pull request merged**
