### PR TITLE
Syndicate Maid Uniform

### PR DESCRIPTION
**Pull request by YewYew**
## About The Pull Request

Implements a new clothing item known as the Syndicate Maid Uniform obtainable via the contraband lists in Clothesmate and Autodrobe vending machines akin to other syndicate drip.

## Why It's Good For The Game

The syndicate maid uniform will increase the amount of options players have in dressing up their character, most notably filling the void of janitorial syndicate clothing.

Nyaa :3
image

## Changelog
:cl:
add: Syndicate Maid Uniform
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
eh

in the future you should make your PRs with a branch that isn't your master branch, as that will cause issues for you in the future

aside from that the pink color on the regular syndie maid uniform here doesn't quite scream "Syndicate" to me. the x variant looks good though

**Comment by YewYew** [comment]
> eh
> 
> in the future you should make your PRs with a branch that isn't your master branch, as that will cause issues for you in the future
> 
> aside from that the pink color on the regular syndie maid uniform here doesn't quite scream "Syndicate" to me. the x variant looks good though

I also thought it was too pink but a friend kept telling me it looked like a chef's uniform

**Comment by triplezeta** [comment]
??

**Comment by YewYew** [comment]
Made the maid uniform the redder one instead of the pinkish one now.

**Comment by atteria** [comment]
The current sprite in this PR looks like the existing maid uniform colored with a red slime potion imo.

**Comment by swifterjack** [comment]
please include images of the uniform in the pr

**Comment by ValoTheValo** [comment]
god has abandoned us

**Comment by YewYew** [comment]
> please include images of the uniform in the pr.

image
dfasadsdfgsfag

**Comment by HighPrincessErinys** [comment]
now make a syndicate maid _costume_

**Comment by Bokkiewokkie** [comment]
Time to port this to NSV so we can have Syndicate janitors during PVP

**Review by genessee-forgot-his-password-again — APPROVED** [review]
life is pain i hate

**Comment by MarkSuckerberg** [comment]
@triplezeta

**Comment by YewYew** [comment]
Ah yeah I'm gonna do a couple more changes soon. Just been to busy to do it lately.

**Comment by MarkSuckerberg** [comment]
Gotchya, just let us know when you get back around to it. Switching your PR to a draft in the meantime so we don't merge it before then.

**Pull request closed without merging**
