### PR TITLE
Fixes Ghosts Haunting People's Bags

### PR DESCRIPTION
**Pull request by BogCreature**
## About The Pull Request
Should fix issue #2417 and the related issue of opening sounds playing twice when alt + clicking them.

## Why It's Good For The Game
As incredibly funny as it is to haunt people as a ghost, it's probably not overall good for the dead to be able to interact with the living.

## Changelog

:cl:
fix: ghosts playing container sounds
fix: some container sounds playing twice
/:cl:

### CODE REVIEW

**Comment by rye-rice** [comment]
Flashbacks to ghosts spamming APC sounds

**Comment by tiramisuapimancer** [comment]
rember when ghosts could drop circle hands?

**Review by thgvr — APPROVED** [review]

**Comment by MarkSuckerberg** [comment]
remember when ghosts would drop circle hands into the supermatter and cause it to delam

**Comment by Sun-Soaked** [comment]
> remember when ghosts would drop circle hands into the supermatter and cause it to delam

got em

**Pull request merged**
