### PR TITLE
fix grammatical stuff with elzuose

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
Elzuose singular
Elzuosa plural.

## Why It's Good For The Game
consistency and grammar

## Changelog

:cl:
spellcheck: Fixed some grammar inconsistencies with Elzuosa/Elzuose
/:cl:

### CODE REVIEW

**Comment by Ms-Mee** [comment]
Sorry but elzuosa is singular and elzuose is plural, you will not convince me otherwise, I reject your grammar and substitute my own

**Comment by thgvr** [comment]
its leviosa

**Comment by Ms-Mee** [comment]
Leviosa your balls

**Comment by Ms-Mee** [comment]
See ya on the moon

**Review by MarkSuckerberg — APPROVED** [review]

**Pull request merged**
