### PR TITLE
resprites medical and utility belts

### PR DESCRIPTION
**Pull request by BarteG44**
## About The Pull Request
Aims to displace the very soulful sprites with slightly less soulful sprites. I did my best with these but if everything goes according to plan, some better spriter will find these so awful that they'll make better ones out of spite

image
298284453-5857e3b8-a207-4516-a395-4df766ac0491
image

## Why It's Good For The Game

man...
image

## Changelog

:cl:
tweak: resprited the medical and utility belts
/:cl:

### CODE REVIEW

**Review by rye-rice — CHANGES_REQUESTED** [review]
augugha, sorry for not getting to this sooner

the onmobs are okay, just kill the 'old' sprites

image

the obj state has a ton of banding on the back of the belt,

x1SVec4-2156615795

if you removed the staircasing it would make it a lot better and probably would be mergable then. Once again, i'm sorry for taking forever to get to this

**Comment by BarteG44** [comment]
something like this?
image

image

**Comment by rye-rice** [comment]
Yeah, something like that.

Make the the parts that are closer to the camera lighter, and the parts furthest darker

**Comment by BarteG44** [comment]
> Make the the parts that are closer to the camera lighter, and the parts furthest darker

 shouldn't the surfaces facing away from the camera be the darkest tho

**Comment by thgvr** [comment]
Please go ahead with the requested changes

**Comment by BarteG44** [comment]
I would if i knew what the request meant cause surely it doesn't mean something like this 
Screenshot_20240205-083454_Pixel Studio

**Comment by BarteG44** [comment]
github is hard

**Comment by BarteG44** [comment]
fuckin dme what

**Comment by goober3** [comment]
> fuckin dme what

i recommend taking whatever sprites you added / modified in this PR and transferring it to a different branch that's been updated from master. dme conflicts are a pain.

**Comment by BarteG44** [comment]
we'll see

**Review by rye-rice — APPROVED** [review]
its alright

**Pull request merged**
