### PR TITLE
Adds integrated NTNET relays for just about any machine, and adds it to the helm console

### PR DESCRIPTION
**Pull request by IndusRobot**
## About The Pull Request

Adds integrated NTNET relays for just about any machine, and adds it to the helm console. Useful for downloading programs to tablets. Modular consoles were unaffected by no accessible relays as they have an ethernet component installed 

## Why It's Good For The Game

Modular computer programs are more accessible. Also adds a method ship to ship communication by use of the chat client program

## Changelog
:cl:
add: Adds integrated NTNET relays for just about any machine, and adds it to the helm console
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
Thats an incredibly hacky way of getting it to work, but at the same time it is also the easiest way of getting it to work

**Review by ZephyrTFA — APPROVED** [review]

**Comment by MarkSuckerberg** [comment]
birbpensive

**Comment by PrefabQuasar** [comment]
this is comically broken FYI. deconstructing a helm console will cause the relay in its contents to spit out onto the tile its on. this can be repeated infinitely with just a screwdriver.

**Comment by PrefabQuasar** [comment]
this is comically broken FYI. deconstructing a helm console will cause the relay in its contents to spit out onto the tile its on. this can be repeated infinitely with just a screwdriver.

**Pull request merged**
