### PR TITLE
[IDB IGNORE] Ports walls from Connorstation

### PR DESCRIPTION
**Pull request by zestybastard**
## About The Pull Request

hghghghh walls

image
image

## Why It's Good For The Game

see above

## Changelog

:cl:
del: the voices
/:cl:

todo: 
add windows + their connectors
address edge cases with mining turf connectors
add girders/grilles
wallmount changes (likely different PR)
airlock changes (likely different PR)

### CODE REVIEW

**Comment by PrefabQuasar** [comment]
oh god is this whole thing stacked on top of my scuffed ass testing branch
cursed

**Comment by PrefabQuasar** [comment]
anyway could you attach some pictures to this PR to show the masses 🥺

**Comment by Zevotech** [comment]
> anyway could you attach some pictures to this PR to show the masses 🥺

okay heres a picture of my cat
cat

**Comment by rye-rice** [comment]
No way Any% and Connor same person!??!?!

**Comment by zestybastard** [comment]
> anyway could you attach some pictures to this PR to show the masses 🥺

when my build works

**Comment by Calyxman** [comment]
screenshots of the added content please

**Comment by zestybastard** [comment]
> screenshots of the added content please

see above

**Comment by Calyxman** [comment]
bruh

**Comment by zestybastard** [comment]
> bruh

it is done

**Comment by ZephyrTFA** [comment]
Dont link to a different site to show images of the content you are adding or changing. Add it to the PR body directly.

**Comment by dwasint** [comment]
I am a big fan of  slanted walls, but not the biggest fan of how the walls don't seamlessly blend with one another.

**Comment by dwasint** [comment]
also no idea on this projects stance on attribution but linking the source pr would be great :)

**Comment by PiperDoots** [comment]
> I am a big fan of slanted walls, but not the biggest fan of how the walls don't seamlessly blend with one another, and the apparent lack of a 90 degree corner, but thats a nitpick at best.

90 degree corners do exist actually! You can see them in the first image.
image

**Comment by dwasint** [comment]
> > I am a big fan of slanted walls, but not the biggest fan of how the walls don't seamlessly blend with one another, and the apparent lack of a 90 degree corner, but thats a nitpick at best.
> 
> 90 degree corners do exist actually! You can see them in the first image. image

yea i noticed that right after lol edited my comment accordingly

**Comment by dwasint** [comment]
i personally like horizon walls more simply because muh customization, but they lack corners so things look boxy. Overall i think this sprites are really nice. Also one of the bigger issue that arises from slanted walls or the likes is that alot of things start to look weird like mineral walls and such being flat

**Comment by zestybastard** [comment]
> i personally like horizon walls more simply because muh customization, but they lack corners so things look boxy. Overall i think this sprites are really nice. Also one of the bigger issue that arises from slanted walls or the likes is that alot of things start to look weird like mineral walls and such being flat

mineral walls have actually been redone also
image

**Comment by dwasint** [comment]
> > i personally like horizon walls more simply because muh customization, but they lack corners so things look boxy. Overall i think this sprites are really nice. Also one of the bigger issue that arises from slanted walls or the likes is that alot of things start to look weird like mineral walls and such being flat
> 
> mineral walls have actually been redone also image

hngh, i'd add that to the pr body as thats a pretty nice change, in fact i might yoink that sprite for another pr. Also if you wanna resprite i think walls would look a billion times cooler if the like inner girders smoothed while keeping the rest the same as they kinda currently look like they are just slotted into place instead of connected together

**Comment by PiperDoots** [comment]
> hngh, i'd add that to the pr body as thats a pretty nice change, in fact i might yoink that sprite for another pr. Also if you wanna resprite i think walls would look a billion times cooler if the like inner girders smoothed while keeping the rest the same as they kinda currently look like they are just slotted into place instead of connected together

These are actually part of a different pr reworking the overmap! #1205

**Comment by dwasint** [comment]
> > hngh, i'd add that to the pr body as thats a pretty nice change, in fact i might yoink that sprite for another pr. Also if you wanna resprite i think walls would look a billion times cooler if the like inner girders smoothed while keeping the rest the same as they kinda currently look like they are just slotted into place instead of connected together
> 
> These are actually part of a different pr reworking the overmap! #1205

i dont see the new smoothrocks in there but i do see the smooth rock file in this pr?

**Comment by PiperDoots** [comment]
> i dont see the new smoothrocks in there but i do see the smooth rock file in this pr?

They're in there the preview pictures are just a bit outdated. But it's been TMed for a bit.

image

**Comment by ZephyrTFA** [comment]
It's been three months

**Pull request closed without merging**
