### PR TITLE
NTSV Contact Dark ruin

### PR DESCRIPTION
**Pull request by Fikou**
## About The Pull Request

Adds a new ruin, the NTSV Contact Dark (any name similarity is accidental), a cargo ship crashed into the rock planet.
Featuring:
a lot of cargo!
a new hardsuit!
a new weapon!
a strange beacon! (not finished!)
nonsensical chest loot!
image
image

## Why It's Good For The Game

We need more unique ruins, I think this is pretty nice.

## Changelog
:cl: Fikou, TripleZeta, Ketrai
add: NTSV Contact Dark has recently crashed on the Rock Planet.
imageadd: new sprites for the guitar
/:cl:

### CODE REVIEW

**Comment by Fikou** [comment]
Whore

**Comment by Apogee-dev** [comment]
Be sure to include some images in the PR, such as the ruin itself and the new sprites.

**Comment by Zevotech** [comment]
genuinely a step beyond what was expected, especially given that youre adding an entire themed loot pool and new items for this. cant wait for the finished project, good work.

**Review by triplezeta — APPROVED** [review]
suit's nice, guitar's mine

**Comment by Zevotech** [comment]
Just a heads up, the crystal legion is extremely lethal and is best saved for use as a boss enemy. You may want to replace it with something else.

**Comment by AtlasRules** [comment]
> Just a heads up, the crystal legion is extremely lethal and is best saved for use as a boss enemy. You may want to replace it with something else.

yeah, they're really fucking nutty

 just do a regular legion, or legate if you want something a bit harder

**Comment by Latentish** [comment]
This is a pretty solid ruin! Just a few things to note.
image
I'm a bit worried about how most of these are just normal filled crates. Could you reduce the number of actual filled crates? It doesn't quite fit the challenge level.

image
You should never use generic areas. You'll need to make your own.

Other than that this is pretty solid. Good job!

**Comment by SweetBlueSylveon** [comment]
On second review and being poked by Fikou, I've realized most of those crates are unfilled, which is me being stupid.
With the generic areas, a generic powered area is ok? Because it is powered by default means it's not going to randomly power another ruin due to player activity. But for all unpowered areas, you should make new areas.

**Comment by SweetBlueSylveon** [comment]
Wait this is fimou's pr. What is my malfunction.

**Comment by Latentish** [comment]
Well if making a new area to replace ruin/powered isn't going to cause issues (it shouldn't), then this ruin should be fine otherwise. I will always prefer a new area be used instead, but if it won't interact with other instances of the same area, then I don't particularly have a problem with it.
My only other question is, did you finish the strange beacon? It says unfinished in your description.

**Review by MarkSuckerberg — APPROVED** [review]
So good, I haven't reviewed the map but the code looks fully sound :+1: (love the ukulele)

**Review by Apogee-dev — APPROVED** [review]

**Review by Latentish — APPROVED** [review]
Looks good to me.

**Comment by Latentish** [comment]
> This pull request has conflicts, please resolve those before we can evaluate the pull request.

die

**Comment by triplezeta** [comment]
Gone

**Pull request closed without merging**
