### PR TITLE
NTSV Ancon-Class Command Ship

### PR DESCRIPTION
**Pull request by meemofcourse**
## About The Pull Request

ancon5

In the endless bureaucratic search for order in NanoTrasen's Central Command, sometimes, five lucky interns are chosen to be the crew of an Ancon-Class, a small vessel destined towards minor work such as the transport of officials through sectors, or the inspection of colonies/ships to revise that they are up to standards. The green uniforms command authority (or ridicule), and the direct ties to CentCom are sure to bring some attention to this craft.

This pull request adds the Ancon-Class, meant to be an adminspawn subshuttle for mostly CentCom inspection shenanigans. It's essentially a glorified office on thrusters.

It is staffed by:

- 1 Head Intern
- 4 Interns

## Why It's Good For The Game

A CentCom gimmick subshuttle might be useful to some admin. Maybe someone really wants to wear the intern jorts. Who knows!

## Changelog

:cl:
add: NanoTrasen Ancon-Class Command Shuttle
/:cl:

### CODE REVIEW

**Comment by Erikafox** [comment]
image
Nodiag wall above the toilet. Also pixelshift the toilet.
I'd also recommend adding a button to bolt the bathroom.
StrongDMM_jL6xABqWLz
reduce the integrity on the paper strctures. They have 300 by default and can't be cleaned without destroying them.
image
Simplify. Use an all in one mainframe varedited to use the relay iconstate. Use the space you've freed up as a proper medical spot, instead of having medkits-r-us.

Your doors need to have access requirements set.

image
use /grunge instead of /centcom. /centcom has special properties.
Put a ghost starter mark if you feel like it.
Still not entirely sold on the shape either, but it's forming up to be decent.

**Review by spockye — CHANGES_REQUESTED** [review]
image

OXY tank is on the wrong dir, and piping layer. Set the piping layer to 2, and set the dir to 8

image

missing pipes

image

stacked decals (under both)

image

Rotate the comms unit!

image

why have the glass here? (its also going into the wall)

image

Might look better with just one door here.

image
i'd recommend setting the railings to layer 3.1, so they load above the microwave ingame (if that's the effect yer going for)

**Comment by meemofcourse** [comment]
> why have the glass here? (its also going into the wall)

as it turns out every window was shifted two pixels upwards. whoops! also, i thought it'd look cool like a glass encasing of sorts

**Review by spockye — APPROVED** [review]

**Comment by Latentish** [comment]
I want to ask you this. What are the people going to do on this ship? what is their purpose? What is their gameplay loop?

**Comment by meemofcourse** [comment]
> What are the people going to do on this ship? what is their purpose?

you know how some admins send interns to inspect stations? it's supposed to fill that gimmick, to inspect other ships and whatnot.

> What is their gameplay loop?

my very bad response to this would be inspecting ships, investigating things centcom might be curious about, or doing what the admin told them to do. being a centcom ship, it holds pseudo-authority over nt vessels and might prove a valuable target for non-nt ships.

**Comment by Latentish** [comment]
> > What are the people going to do on this ship? what is their purpose?
> 
> you know how some admins send interns to inspect stations? it's supposed to fill that gimmick, to inspect other ships and whatnot.
> 
> > What is their gameplay loop?
> 
> my very bad response to this would be inspecting ships, investigating things centcom might be curious about, or doing what the admin told them to do. being a centcom ship, it holds pseudo-authority over nt vessels and might prove a valuable target for non-nt ships.

I just don't see this as an event being run. And overall the decalwork makes it kind of hard to look at.

**Comment by meemofcourse** [comment]
might need to think this one over

**Pull request closed without merging**
