### PR TITLE
fixes some of the do afters working

### PR DESCRIPTION
**Pull request by FalloutFalcon**
## About The Pull Request
some of the so_afters args were scrambled causing the target to be bad

## Why It's Good For The Game
the do_after pr did not receive and test merge and caused a few bugs to slip through. fixing bugs is good!

## Changelog

:cl:
fix: fixed multiple of the do_afters not working due to misplaced args
/:cl:

### CODE REVIEW

**Comment by Anticept** [comment]
Survey scanners are not working either.

Some creatures will not gib and drop their resources either. It can even be the same mob type and some gib, some dont.

Baby gruboids are sometimes not exploding, not sure if this is related.

**Comment by Anticept** [comment]
firelocks cannot be interacted with using crowbars or manual operation either.

**Comment by rye-rice** [comment]
unscrewdrivering gun cells is broke, but you likely knew this by now, putting it here as a reminder

**Comment by Chorkes** [comment]
pAIs are unable to request carrier DNA sample nor do a host health scan

**Review by Sun-Soaked — APPROVED** [review]
yup!

**Pull request merged**
