### PR TITLE
The Unatomized General Cleanuping (Part 1?)

### LINKED ISSUE #1405: [BUG] Bank account manager
## Round ID:
[1049](https://shiptest.ga/stats/rounds/1049)

## Testmerges:
N/A

## Reproduction:
Spawn in on osprey/ Other ships that have command console,Open the bank account manager, Be on a server with multiple people/ships, Have ids,
You can find peoples account ids and drain their money. This is powerful b/c of the ability to use money in the osprey

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Kills off a few unnecessary variables in the job datums, they really don't need to consist of that much.

Fixes: #1405 

## Why It's Good For The Game
Reduces complexity for messing with jobcode

## Changelog

:cl:
del: Antag Rep, did this even work?
del: Paychecks, these barely worked.
del: Job preferences, these did nothing but allowed you to preview outfits.
add: Preview outfit selection! Allows you to select a job from any ship to preview your character as in the prefs screen.
del: Removes "enforce human authority" flag. Fite me.
fix: ID overlays and secHUD icons should now work for all custom jobs!
del: Alt/senior titles, they were fun, but... they didn't work.
del: The accounts manager, this doesn't make any sense.
/:cl:

### CODE REVIEW

**Comment by MarkSuckerberg** [comment]
this has rapidly progressed to an unatomised general cleanup of everything from IDs to gamemode code. if this wasn't productive I'd be yelling at myself

**Comment by MarkSuckerberg** [comment]
gonna stop myself here before I go any further and therefore say that "this is probably good enough to be undrafted"

**Comment by triplezeta** [comment]
if its good enough to be undrafted is it good enough to be speedmerged

**Comment by Latentish** [comment]
JOBCODE SUCKS ASS
Thank you for this cleanup mark

**Comment by MarkSuckerberg** [comment]
<:thepleadster:879392908485218304>

**Comment by ZephyrTFA** [comment]
@Fikou hey there buddy

**Comment by MarkSuckerberg** [comment]
how did I open this almost a month ago. I swear I did this like yesterday

**Comment by MarkSuckerberg** [comment]
only the one who is god's strongest write access holder can merge this PR

**Comment by ZephyrTFA** [comment]
Fuck it

**Pull request merged**
