### PR TITLE
Adds craftable showers and IV drips hopefully for the last time

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Showers can be built in the direction you are facing with three metal sheets.
IV Drips can be built with five plastic sheets.

- [x] I affirm that I have tested all of my proposed changes and that if this pr fucks up again im giving up and asking someone else to do it

## Why It's Good For The Game
Showers are important and useful, same with IV drips. Since you cannot draw blood from a bag using a syringe, not having an IV drip means your blood bags would be effectively useless until you get to an outpost. Showers are useful for washing off blood, acid and doing surgery on plasmamen.

## Changelog

:cl:
add: stack_recipes for showers and IV drips
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
yippee! my changes are ACTUALLY IN THE PR this time!

**Comment by Apogee-dev** [comment]
We probably should code in drawing blood from bags using a syringe anyway, to be honest.

**Comment by Zevotech** [comment]
> We probably should code in drawing blood from bags using a syringe anyway, to be honest.

and yet, for some unknowable reason, nobody has.

**Comment by BarteG44** [comment]
> We probably should code in drawing blood from bags using a syringe anyway, to be honest.

Goon lets you slice a pack open with a knife to let you pour in and out of it which i prefer tbh

**Comment by MarkSuckerberg** [comment]
FIiiiiiinally

**Pull request merged**
