### PR TITLE
Goliath Gupdate

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
Changes goliath tentacle behavior, see below
ezgif com-optimize

## Why It's Good For The Game
more good fairer i  think

## Changelog

:cl:
balance: Goliaths no longer stun you, instead they apply a bear-trap like mass of tentacles that slows you. Resist to break them off.
/:cl:

### CODE REVIEW

**Comment by Xylarr** [comment]
i love you

**Comment by tmtmtl30** [comment]
seems like tentacle damage should be increased substantially, this is a pretty huge nerf otherwise

**Comment by Sun-Soaked** [comment]
This is very swag but I'd boost the slow a bit- getting hit by the tentacle should definitely be 'dangerous' instead of 'death sentence', but this downgrades it to 'annoying'

**Comment by PrefabQuasar** [comment]
maybe have it still drop your held items?

**Comment by thgvr** [comment]
Yeah I'll be tweaking it

**Comment by BarteG44** [comment]
getting caught twice should stun you like it does currently

**Comment by MarkSuckerberg** [comment]
oh sweet

**Comment by thgvr** [comment]
Will patch this more later. Also github changed the fucking comment box

**Comment by githubuser4141** [comment]
This also seems to buff the tentacle's damage to 20 or 30 which is significantly higher then it was previously and means being ensnared at 30% health will actually just crit you on the spot with no chance of escaping.

**Comment by thgvr** [comment]
I'd say being hard stunned for like 10 seconds was more dangerous before

**Review by rye-rice — APPROVED** [review]

**Pull request merged**
