### PR TITLE
Improved weapon menus

### PR DESCRIPTION
**Pull request by FalloutFalcon**
## About The Pull Request

Uses radial menus to let you better pick what attachments/modkits/trophies you want to remove
image
image

https://github.com/shiptest-ss13/Shiptest/assets/86381784/cc0d7d4b-0c40-4c8e-bb30-debc15b422fb

## Why It's Good For The Game

I have always hated when I want to remove a trophies and it dumps everything onto the floor. Input menus are also unappealing to look at and it will make it easier to add other removable attachments

## Changelog

:cl:
add: improved radial menu for mining tools
tweak: menus for removing attachments
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
If its not too much to ask, could you make it so that you can use this on energy guns with seclights or bayonets attached so I dont have to remove the seclight to pull the cell out? Or just make the seclight removed with a crowbar for an easy solution.

**Comment by FalloutFalcon** [comment]
> If its not too much to ask, could you make it so that you can use this on energy guns with seclights or bayonets attached so I dont have to remove the seclight to pull the cell out? Or just make the seclight removed with a crowbar for an easy solution.

I think i already did this. I can probably add the battery to the radial honestly

**Comment by FalloutFalcon** [comment]
> If its not too much to ask, could you make it so that you can use this on energy guns with seclights or bayonets attached so I dont have to remove the seclight to pull the cell out? Or just make the seclight removed with a crowbar for an easy solution.

A easy mechanic in theory. I wanted the code to be not terrible so it took a while
image

**Review by MarkSuckerberg — APPROVED** [review]
Neat. Definitely need to port the radial menu updates from TG at some point

**Pull request merged**
