### PR TITLE
The Darkening

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
May my eternal darkness reign forever

also audits turrets

## Why It's Good For The Game
feature? Feature.

## Changelog

:cl:
add: Lights will now start off on your ship. Find the light switches and turn them on. It's good for the environment at least.
/:cl:

### CODE REVIEW

**Comment by Sly9sky** [comment]
Couple questions- first, is having the lights off for freshly spawned ships primarily to make the process of starting up a ship be more akin to a cold start, akin to how lights, panels, and power have to be turned on in real life aircraft? Secondly, would multiple ships spawning in close time proximity to each other having to turn on their lights possibly contribute to lag?

**Comment by goober3** [comment]
make lamps start disabled too.

**Comment by Apogee-dev** [comment]
This PR disables lights even in rooms that don't have a light switch at all (which is frequently the case for public areas like hallways). I'd make it check to see if an area has a light switch before turning the lights out.

**Review by spockye — COMMENTED** [review]
a INSANE amount of changes, dear god.
i approb :)
Get this tm'd once Conflicts are fixed

**Comment by MarkSuckerberg** [comment]
> Couple questions- first, is having the lights off for freshly spawned ships primarily to make the process of starting up a ship be more akin to a cold start, akin to how lights, panels, and power have to be turned on in real life aircraft? Secondly, would multiple ships spawning in close time proximity to each other having to turn on their lights possibly contribute to lag?

Yeah, that's sort of the idea. You start with a lot less power draw, plus the atmosphere of waking up in a dark ship is just far more awesome in my opinion. Second, there shouldn't be significant lag from it, and if there is, that's a completely different beast of a problem.

**Pull request merged**
