### PR TITLE
Revert "Removes Antimatter Engines. (x2)"

### PR DESCRIPTION
**Pull request by ZephyrTFA**
Reverts shiptest-ss13/Shiptest#857

Muh baby

### CODE REVIEW

**Review by rye-rice — CHANGES_REQUESTED** [review]
Add logging to this piece of ship and then ill be neutral towards this PR

**Comment by Ms-Mee** [comment]
War, war never changes

**Comment by TheNeoGamer42** [comment]
add logging or im breaking into your shiptest and uninstalling all the pipes, walls, and uh, machines idfk

**Comment by ZephyrTFA** [comment]
> Add logging to this piece of ship and then ill be neutral towards this PR

This is a joke PR, but also I think the AMR would be better if it was slightly more interactive

**Comment by rye-rice** [comment]
> add logging or im breaking into your shiptest and uninstalling all the pipes, walls, and uh, machines idfk

cats going to steal your fucking ship-catalytic converter

**Comment by TheNeoGamer42** [comment]
> > Add logging to this piece of ship and then ill be neutral towards this PR
> 
> This is a joke PR, but also I think the AMR would be better if it was slightly more interactive

:waa:

**Comment by rye-rice** [comment]
Another issue with it is it doesn't even use the new, sort-of-fancy html the pda currently uses, just the plain white html background

**Comment by TheNeoGamer42** [comment]
> Another issue with it is it doesn't even use the new, sort-of-fancy html the pda currently uses, just the plain white html background

also its fukkin modularizes and stinks, i dont think there's a ship-catalytic converter to steal out of AMEs even

**Comment by MarkSuckerberg** [comment]
literally 1997

**Pull request closed without merging**
