### PR TITLE
Starwalker 2.0 (now with more colours!)

### PR DESCRIPTION
**Pull request by spockye**
## About The Pull Request

this pr adds a new ship, called the Starwalker class! this ship's purpose is as a small carrier used for piracy. it comes equipped with a small hangar, two emitter bays, a well-stocked medbay, and a decently filled armoury.

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
we currently only have ONE pirate ship, and i want to change that!

## Changelog

:cl:
add: a new pirate ship, the Starwalker class
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
image

**Comment by Erikafox** [comment]
pods have like less than week for someone to overhaul them before they get the boot so you may want to have a podless version ready (I've found subshuttles and mechs are good replacements)

**Comment by spockye** [comment]
> pods have like less than week for someone to overhaul them before they get the boot so you may want to have a podless version ready (I've found subshuttles and mechs are good replacements)

I sadly fully designed and intended this ship to be used with pods (hoping that someone would make the effort to fix them) 
I'd rather not repurpose it, so I'll close it when/if that happens

**Comment by spockye** [comment]
the coders hath spoketh

**Pull request closed without merging**
