### PR TITLE
Changes Phanic to Weasel Kid

### PR DESCRIPTION
**Pull request by tiramisuapimancer**
## About The Pull Request
Changes the "gamer shirt" from "Phanic the Weasel" to Weasel Kid from the fictional Super Weasel Kid videogame series from the very real videogame The Hex. 
image
I just think The Hex is a cool game and through staff bias I am enforcing adding more references to it to the codebase. Play The Hex.

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
It's not something anybody really asked for or needed but I think getting more people to play The Hex (ten dollars on Steam) is an improvement over such a low effort reference to real-life acclaimed platformer series "Sonar the Porcupine"

## Changelog

:cl:
tweak: gamer shirt now depicts Super Weasel Kid
/:cl:

### CODE REVIEW

**Review by triplezeta — APPROVED** [review]

**Comment by triplezeta** [comment]
im pretty sure this pr means that lionel was a real living person at some point in the past. oh well

**Comment by ZephyrTFA** [comment]
PRs that are not a critical bug fix should not be merged until at minimum 23 hours from being opened

**Comment by ZephyrTFA** [comment]
(I know you know this)

**Comment by triplezeta** [comment]
gwa

**Pull request merged**
