### PR TITLE
Ports TGUI select equpiment

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request
Ports
https://github.com/tgstation/tgstation/pull/57794
https://github.com/tgstation/tgstation/pull/57673
https://github.com/tgstation/tgstation/pull/58125
https://github.com/tgstation/tgstation/pull/58366
https://github.com/tgstation/tgstation/pull/58597
https://github.com/tgstation/tgstation/pull/60287

## Why It's Good For The Game
Screenshot_2358

Did you know there was a outfit manager? I didn't! It was burried under so much dust I don't think anyone knew

## Changelog
:cl:
admin: Adds a new select equipment menu
admin: Makes the outfit manager tgui. You probably didn't even know this existed did you?
/:cl:

### CODE REVIEW

**Comment by swifterjack** [comment]
fuck yes

**Comment by francinum** [comment]
Does this retain the simplified version in the right click menu or completely replace it?

**Review by ZephyrTFA — APPROVED** [review]
wish you still had the option to use the old menu in case of tgui error, but thats a personal gripe and not needed

**Comment by francinum** [comment]
...It really kinda is, because of the way TGUI states work.

**Pull request merged**
