### PR TITLE
ERT Subshuttles

### PR DESCRIPTION
**Pull request by meemofcourse**
## About The Pull Request

At the request of maptainers, I've moved ERT subshuttles to a separate pull request.

Includes:
* Ancon-Class Internship Ship, for Central Command Inspectors and Interns
imagen
* Crux-Class Dropship, for Colonial Minutemen response teams
imagen
* Runner-Class Ambulance, for Cybersun Trauma Teams
imagen

* Anvil-Class Dropship, for Inteq Management response teams
imagen

## Why It's Good For The Game

what's the fuckin point of adding support for ert subshuttles if all we get is a kunai

## Changelog

:cl:
add: Crux-Class Dropship
add: Ancon-Class Internship Ship
add: Runner-Class Ambulance
add: Anvil-Class Dropship
fix: ERTs can now actually spawn at outposts
/:cl:

### CODE REVIEW

**Review by Erikafox — APPROVED** [review]
we can just add more subshuttles later

**Comment by MarkSuckerberg** [comment]
is this ready?

**Comment by meemofcourse** [comment]
no

**Comment by thgvr** [comment]
haha

**Comment by meemofcourse** [comment]
throws a lizard at you

**Comment by Latentish** [comment]
Tming and testing this.

**Review by Latentish — APPROVED** [review]
Looks good to me.

**Pull request merged**
