### PR TITLE
Disable Events

### PR DESCRIPTION
**Pull request by ZephyrTFA**
## About The Pull Request

Disables the event subsystem.

## Why It's Good For The Game

We don't have a station for the events to interact with and as such they are just random annoying popups.

## Changelog
:cl:
del: Disabled event subsystem; can still be manually reenabled if desired, for now.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
its probably better to just remove the events that arent relevant to shiptest since the events that do work help to spice up rounds just a bit

**Comment by shiptest-server** [comment]
#### Test Merge Removed

**Comment by shiptest-server** [comment]
#### Test Merge Deployed

##### Server Instance
shiptest

##### Revision
Origin: aabc6f1b144d0c36cf9f9f5d49313c6586ec6706
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: 4a612b6abc77d3aaae270b65dc4c94667e4d6be2

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 293bad3e54aa3f26644d5d871baee9eda36057ca
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: 2c17e761a3dbe846412b0eb5224178d8c7dfc1e4

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: d79659920aec58007df63d3e9b96cb0fe1a16353
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: 72d94bef2620899bd315f660ccb547df14ffc328

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: dd854e7386a7a9a664d6357aab6213b032e1817b
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: d097fa6e32a13458e756307a43c1764f99b243bc

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 4d98cdcea7b4591b94a06237309039f4980217fa
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: 9a29cfa82da92d64f18a8f8bcd69d3ea934be1ac

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: f789e74004b3acb82690d77398848b240a153b6f
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: fec71ade6e716fb63d267abca95b86e22f5eb182

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: f789e74004b3acb82690d77398848b240a153b6f
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: 1dbd0bfb0d4198bd0a0d556e3729419b22e55678

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 89b653c96fc59fa415eeb26666f154fe97f257c1
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: 9172c1bfefbcd61b7e2dccb8f8cceb235072078e

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 7c3512bd559cf2b1f8e230216ff853c7f118d7ee
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: 7f432c12878b85f2e0187a8393c33b9d5b197880

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: bf2a3d7daffd8042d3adbe075ec803cd3abd4e03
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: 68914e28c7ca55ffe87c21c0fc6dbcb9af418093

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: bf2a3d7daffd8042d3adbe075ec803cd3abd4e03
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: ca0ff8b9f76846976a9d8d2ec5e18cf60ecd28be

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 033ea7d0a6e5ade2feced249d03f7bfcd3eac439
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: dd05c1250d57bfccc2a44d8462a4c502f044d617

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 033ea7d0a6e5ade2feced249d03f7bfcd3eac439
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: 7c123be6a9d9ffcf192aa21466691c922a728b54

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 9693b436ac8eb8d68349b284df72bb252209581f
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: 651bb7bd5250da841cf57899f6ff939ae8b47202

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: ca83a63d9154e7bd47271dd9f5ce5d44eb19d7af
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: b9679cc28f47ef4054511559ac3e5f35dd3100bb

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: ca83a63d9154e7bd47271dd9f5ce5d44eb19d7af
Pull Request: f821d7d77e02280348d69c5edfdb506095a8f217
Server: 52f18b307da9ed9bafb2f173c5db9806fde13a70

**Comment by ZephyrTFA** [comment]
I'm fine with this being merged, if and when events get overhauled this can just be reverted

**Pull request merged**
