### PR TITLE
Adds A New Hair Gradient!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
Does exactly what it says on the tin, adding a new hair gradient called splotches!
image

image

## Why It's Good For The Game
I think it looks cute!

## Changelog

:cl: PositiveEntropy
imageadd: Adds a new hair gradient: Splotches!
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
i got that dawg in me

**Comment by Imaginos16** [comment]
> i got that dawg in me

I got that mrow in me :3c

**Comment by Erikafox** [comment]
that hair color is like. severely garfield coded

**Comment by Maksoplo** [comment]
So splochful

**Pull request merged**
