### PR TITLE
[Needs TM] The Accelerataning

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Gone are the days of spam clicking buttons to move faster in a direction, with this PR, ships now accelerate constantly (as long as you have fuel and don't touch the throttle) in a direction you set, leading to a much smoother flight experience. I imagine it's going to be a bit tougher to thread gaps, but flying a spaceship *is* quite literally rocket science. So.

Also actually makes the minimum and maximum speed work, and adjusts them to a more tolerable level.

## Why It's Good For The Game
Eliminates the ability to cheese high speeds by spamming the accelerate button, and also makes the flight experience much more pleasant as you don't have to spam click to move a decent speed.

## Changelog

:cl:
add: A new system for ship flight, where you only point a direction and set the throttle to change your speed, reducing the need for spam-clicking.
fix: There's now a maximum and minimum speed, 600spm and 0.01spm, respectively. The limits have been broken all this time.
/:cl:

### CODE REVIEW

**Comment by Erikafox** [comment]
STOP STOP STOP THE SHIP YOU'RE GONNA ACCELERATE US RIGHT INTO A SPACEBERG

**Comment by MarkSuckerberg** [comment]
hi I'm mark spaceberg

**Comment by githubuser4141** [comment]
Is there a way to set cruise control, or a way to stop thrusting, but keep moving from inertia mode? Or do you just keep accelerating forever?

**Comment by BarteG44** [comment]
> Is there a way to set cruise control, or a way to stop thrusting, but keep moving from inertia mode? Or do you just keep accelerating forever?

Pressing a direction button accelerates you in that direction. clicking on the middle button once stops the acceleration and again starts to slow you down

**Comment by MarkSuckerberg** [comment]
Todo:
- [ ] Cruise control (set a speed you want to get up to and automatically burn to that speed)
- [x] Make throttle be "I want X speed per tick" instead of just vague 1-100%
- [ ] Slow down ion engine usage?

**Comment by MarkSuckerberg** [comment]
About as done as it'll ever be in this PR, I'll add more in a different PR when I get around to it

**Comment by TheLeopold** [comment]
This is agony. I lost so much ships to these controls.

**Comment by tmtmtl30** [comment]
margable

**Pull request merged**
