### PR TITLE
Removes the S.W.A.T. Suit from cargo.

### PR DESCRIPTION
**Pull request by Martinpachu**
## About The Pull Request

Removes the cargo listing for the S.W.A.T. Suit, The item has not removed due to concerns regarding subtyping.
## Why It's Good For The Game

This might be a little controversial, but it's what has to be done, and the marine armor is already here to replace it. I hate the swat suit so much, i have been getting constant requests every single fucking day to remove it, so here it is. Good thing too, this thing is so repulsive i can't look at it for two seconds without throwing up over my monitor. One time i was playing a medship and one of my patients had the fucking gall to be wearing one. I shot his ass thrice and got banned for two months. Worth it.

## Changelog

:cl:

del: The cargo listing for the SWAT suit.
/:cl:

### CODE REVIEW

**Comment by Martinpachu** [comment]
the description is fake and satire i cannot be held accountable for it in court of law

**Comment by Burning02** [comment]
I don't mind the swat crate being obliterated (The sprite sucked ass), but could you potentially add the belt to cargo by itself? Or even combat rigging or should I potentially do that myself?

**Comment by Hlscientist** [comment]
> I don't mind the swat crate being obliterated (The sprite sucked ass), but could you potentially add the belt to cargo by itself? Or even combat rigging or should I potentially do that myself?

this

**Comment by Martinpachu** [comment]
idk maybe after this gets merged. or maybe you should do it. separate pr though

**Comment by Burning02** [comment]
Good point, I'll probably do it in a little bit.

**Pull request merged**
