### PR TITLE
Removes some player facing clown stuff

### PR DESCRIPTION
**Pull request by thgvr**
## About The Pull Request
a

## Why It's Good For The Game
a

## Changelog

:cl:
del: Clown cargo crate
del: Clown stuff in costume vendors
/:cl:

### CODE REVIEW

**Comment by BarteG44** [comment]
Why do yall hate clowns so much anyways

**Comment by meemofcourse** [comment]
letting people run around dressed up as clowns in the years following the rebuilding of a major defining conflict seems like a take that doesn't fit in with the setting

**Comment by Zevotech** [comment]
We should probably rewrite the descs for some clown and mime stuff to better reflect how the Entertainers Union is seen after the ICW. Would help with the assumptions people tend to make about that sort of stuff.

**Comment by ritorizo** [comment]
I feel like just removing clown stuff would undermine a part of the response to horror some people can have. And I'm all for letting people have props to make interesting oc's. 
image

**Comment by thgvr** [comment]
clown stuff isnt removed, its removed from cargo crate and vendors.

**Comment by ophaq** [comment]
Can someone please tell me why this is even here? Are clowns bad or something because I found no lore on the wiki relating to that so this must be something either hard to find or not written yet or I'm just blind and ill informed. I would really prefer dressing as a good clown if possible but I guess some people just hate clowns. ¯\_(ツ)_/¯

Seems kinda lame to stop people from playing something they want to play if they so happen to want to play it. The clown is seen as an iconic ss13 symbol.

**Comment by meemofcourse** [comment]
In lore, clowns are vilified for their participation in the corporate wars. Clowns draw in shitters and poor players. They do not fit into the frontier setting of shiptest.

**Comment by ophaq** [comment]
> In lore, clowns are vilified for their participation in the corporate wars. Clowns draw in shitters and poor players. They do not fit into the frontier setting of shiptest.

So if they're a character born after the corporate wars, they just face the stigma and are innocent. And while I agree that clowns _can_ draw in shitters and poor players, that isn't always the case either. They can make the game more fun if the person is, well, not a shitter.

**Comment by Apogee-dev** [comment]
> So if they're a character born after the corporate wars, they just face the stigma and are innocent. And while I agree that clowns _can_ draw in shitters and poor players, that isn't always the case either. They can make the game more fun if the person is, well, not a shitter.

A character born after the ICW would be no more than seven years old my man. this is very recent cultural trauma. literally every single character seen in game would have been alive to see the reports about clowns and mimes exterminating entire colonies in especially cruel and unusual ways.
also, clowns just do not fit in with the type of feel we are going for here. we annihilated wizards, and the wizard ship, for exactly the same reason.

**Pull request merged**
