### PR TITLE
Adds 14 new, non-referential hair styles.

### PR DESCRIPTION
**Pull request by tmtmtl30**
## About The Pull Request

adds some nice, new, non-referential hairs, originally from tgstation/tgstation#70222 , courtesy of Shadyyy66. See the linked PR for images.

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

funny hair :)

## Changelog

:cl: tmtmtl30, Shadyyy66
add: Frontier hairstylists have added 14 new hairstyles to their repertoire. Check them out now!
/:cl:

### CODE REVIEW

**Comment by tmtmtl30** [comment]
fuck you and die shit-eating maggot bot

**Review by triplezeta — APPROVED** [review]
I see nothing wrong with these.

**Comment by thgvr** [comment]
couple sclera/emote sprites deleted according to IDB

**Comment by tmtmtl30** [comment]
yeah that was the merge conflict

**Comment by sensebucket** [comment]
you did it.

**Pull request merged**
