### PR TITLE
a ship dedicated entirely for bartender mains

### PR DESCRIPTION
**Pull request by triplezeta**
## About The Pull Request

I'm just calling this the Diner ship for now. It has a hydroponics bay and a fully equipped and stocked kitchen and bar. However, certain amenities were cheaped out on, most notably: Medical supplies, an Autolathe, Power Generation... 

image

## Why It's Good For The Game

This is mostly for testing if a map with different starting equipment can function well (as well as having a map with actual things to do on it, even if it is literally just the service department on a ship). 

In terms of actually being good for the game, it's a modestly sized ship (a bit smaller than the skeld) with plenty of room to build if the main room is emptied out. Hopefully people will enjoy it.

## Changelog
:cl:
add: Diner ship, for the unironic bartender mains out there.
/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
This might be good to merge, I need to run through it ingame first.

**Comment by triplezeta** [comment]
ok no hold on

**Comment by MarkSuckerberg** [comment]
screenshots pls

**Comment by triplezeta** [comment]
i will i will hold on

**Comment by triplezeta** [comment]
ok we're good now

**Comment by triplezeta** [comment]
fire extinguishers added, intercomms added, shuttle displays added, DNA manip added (lol!), EVA suits replaced with proper mining hardsuits

**Pull request merged**
