### PR TITLE
Fixes Minor Bug With ModComp Arcade Minigame

### PR DESCRIPTION
**Pull request by BogCreature**
## About The Pull Request
Fixes an extremely minor and inconsequential bug where the modcomp arcade minigame wouldn't give you gaming XP when you played it.

## Why It's Good For The Game
Shiptest will never be complete so long as I can't grind out that sweet, sweet gaming cape from anywhere at any time.

## Changelog

:cl:
fix: The modcomp arcade minigame now properly gives gaming XP
/:cl:

### CODE REVIEW

**Comment by AverageUser67** [comment]
Damn you, why couldn't this have been a removal/balance PR? This is a good feature.

**Comment by Zevotech** [comment]
congrats on being PR #1984 btw

**Comment by Latentish** [comment]
Quite literally 1984

**Comment by BogCreature** [comment]
> congrats on being PR #1984 btw

It's truly an honor

**Comment by MarkSuckerberg** [comment]
That works, but maybe you can just change https://github.com/BogCreature/Shiptest/blob/06f00009e652bbb213e2c3ceeddb3f1f6f62150a/code/modules/modular_computers/file_system/programs/arcade.dm#L115-116 and all other calls to game_check() and enemy_check() to game_check(usr) and such? It's just usually a common practice to limit usage of `usr` to topic procs, nothing big.

**Comment by Anderson-Cooper** [comment]
making a change that most users won't even bother making, just as exadv1 intended.

god bless ss13

**Pull request merged**
