### PR TITLE
Raleigh-Class Mercenary Corvette

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
StrongDMM-2024-10-06 19 02 02
StrongDMM-2024-10-06 19 02 03

dreamseeker_qhkyYgbpdx
dreamseeker_8jf3u0ZlwA
dreamseeker_jJx71tKdzb

Adds the Raleigh Class Corvette - a century old design manufactured by Kasagi-Fischer for yuppie solarians, and now retooled for usage as a mercenary vessel. 

Originally sold as a 'Safari Ship', or a 'Yacht' in some markets, the strange shape and relative quality of the design made it very appealing for usage by unaligned mercenaries forces, with the vessel capable of carrying a small complement of supposedly professional soldiers. 

The Raleigh supports a crew of:
1 - Captain
1 - Lieutenant
1 - Engineer
3 - Troopers
1 - Recruit (random guy we found)

The Raleigh's gear includes:
1 - E40
1 - Cobra-20
2 - Ringnecks
Assorted Machetes
The Yuri Room
The Gambling Room
The Emergency Medical Hologram

## Why It's Good For The Game

Adds a combat/rp focused ship for mercenaries that's |not| inteq. Think of all the possibilities.

## Changelog

:cl:
add: Kasagi-Fischer has begun a new production run of the venerable Raleigh-class Corvette. See your purchaser's manual for more information!
/:cl:

### CODE REVIEW

**Comment by Apogee-dev** [comment]
I feel like the XO could use a different job title that feels a little less professional and a little more mercenary, and that leans more into a “lead the squad” type of playstyle than a “sit on the ship” style. Lieutenant might actually fit the bill here- it’s pretty frequently used to refer to a second-in-command or other lower “officer” of a gang, merc company, or paramilitary in real life.

Also, can you include a screenshot of the outfits, since most of them are new?

**Comment by Erikafox** [comment]
dreamseeker_dxpPGoMlY0

There you go

**Comment by meemofcourse** [comment]
now we will have inteq mercenaries AND indie mercenaries. genius

**Comment by Erikafox** [comment]
im thinking about adding syndicate mercenaries next

**Review by Gristlebee — COMMENTED** [review]
Really pretty looking ship you've made and I love what you're cooking, but there's a few issues here and there.
___

- The PR is missing a screenshot of the ship spawned ingame, please add one.

- The gravity generator isn't ontop of a wire node, so it can't be powered. I do notice you have a free node nearby where the gravity generator can be moved, so I assume this is intentional. I'd prefer though the gravity generator to be pre-wired.
image


- The blackbox section in the engineering wing overlays oddly when spawned ingame. I'd suggest removing the side windows and keeping only the windoor.
image

- The atmos pipes overlay on top of the pumps when spawned ingame, which looks odd. I'd recommend either changing the pipe layers, or the layout.
image
image

- You're missing a wire here between the generators and the SMES.
image

- The ship starts with a 50 stack of plasma, which is a lot of fuel. Cut it down to 20 please.
image

- What purpose does the diskette box serve in the common area? These disks are used for genetics.
image
 
- The random small cash spawners can represent a decent amount of extra cash for an already well geared ship on a good roll. Change them to pocket cash spawners. I'd also recommend reducing the starting funds to 1500 in the JSON.

- The machetes are 20 force (22 if two handed) weapons with 25% block chance. They're quite strong, so you should reduce the amount on the ship to one.

**Comment by Erikafox** [comment]
>grav gen

I forgot those needed to be wired tbh
>diskette box

I forgot those weren't holopad disks

>machetes

Not sure I agree given the ongoing discussion around melee. I'll remove the one that's just sitting around near the Chair though.

**Comment by Sadhorizon** [comment]
My turn! My turn! My turn!
Honestly, great job. I can only be a bitch about minor things unfortunately.

Splines render under the techfloors
obraz

Just two rations on a seven player ship? They WILL starve.
obraz

You can rotate the cabinets now FYI.
obraz

Uhm actshually this poster is 2 pixels too high, making it float. Awful mapper, ban :3
obraz

Unrotated object again. EVERYONE knows that a north-facing chemsink has the tap on the left side!!!
obraz

Personally would anchor the cutting board. Up to you though.
obraz

This is right next to a window, just make it see-through.
obraz

The right one isn't access-locked.
obraz

Wrong area.
obraz

Paintings need at least X/Y 30 not to stick out after generating.
obraz

I may just be a hater, but I think the cosmic blankets REALLY stick out more than they should.
obraz

Fix this dude's layer.
obraz

Think sidings and brown should layer the other way here.
obraz

Jani closet also sticks out more than it should. Suggestion to make it a standard grey one instead.
obraz

No button?
obraz

This is so sad. I suggest making these nodiags.
obraz

Because of the hull plating, whenever shutters are opened, air gets a bit sucked from the room.
obraz

Do these two *really* need to be secure?
obraz

**Comment by Erikafox** [comment]
> My turn! My turn! My turn! Honestly, great job. I can only be a bitch about minor things unfortunately.

you give good feedback but the way some of it's delivered makes me want to disregard all of it

**Comment by Erikafox** [comment]
reviews addressed.

**Comment by Apogee-dev** [comment]
Those command lockers do actually need to be secure btw, sadhorizon. The fact that they’re already in a secure area doesnt matter, always put locks on job equipment lockers. One of them has a gun in it for pete’s sake.
Actually, on that note, can you put the Viper in a pistol case rather than have it spawn loose in the locker? I recall we were trying to move towards making that standard practice.

**Comment by Erikafox** [comment]
done

**Comment by meemofcourse** [comment]
dude this is just like michael brown

**Review by Gristlebee — COMMENTED** [review]
Feedback after testing on live:
---
There's still two small cash spawners in the LT's and captain's office. Replace those with pocket cash spawners as well please.

Add a weapon power cell to the armory, so the powercell on the e-40 can be swapped out if needed.

The ship has only one EVA suit. I'd suggest adding two more suits, so the troopers have enough suits to head out together.

Players testing the Raleigh noted while playing the ship the cargo bay felt cramped. I think taking this dividing wall and door here and making it into one room could help alleviate it. Try it out and see how you feel about it.
image

~~Also please remove the Hammer from the armory for now, since it's apparently crashing the server?~~

nevermind, turns out it was gibbing killing the server

**Comment by DrCrawler** [comment]
The ship has no viewscreens, which is pretty sad.

**Pull request merged**
