### PR TITLE
Updates TGUI and adds bin folder for .bat scripts

### PR DESCRIPTION
**Pull request by Arturlang**
## About The Pull Request
Updates TGUI and build tools and .vscode files to what TG has.
Does not actually update UI's, but does have fixes for a couple including the join game UI's tabs not working.

## Why It's Good For The Game
Not needing to have a local installation of yarn to run dev-mode is nice.
Updating TGUI is a annoying chore that helps in the future when porting more interfaces

## Changelog

:cl:
code: Adds a bin folder with dev scripts, updates TGUI, .vscode folder to what TG has.
fix: Fixes the input in the bottom right being white in darkmode, no more unreadable text
fix: You can now use the tab buttons in the join ship menu.
qol: The outpost mission menu now looks a whole lot better
fix: The input bar no longer randomly becomes white and unreadable on darkmode
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
Dude actually fucking did it.

**Comment by Arturlang** [comment]
Not ready yet, don't test merge

**Comment by Arturlang** [comment]
All ready!

**Comment by Arturlang** [comment]
I had to check that this PR didn't fuck the outpost comms console but no, it's like that normally, please, someone do something about that my PR's big enough already as is.

**Review by MarkSuckerberg — APPROVED** [review]
I guess this looks okay, but I can't confirm the absence of bugs in-game

**Comment by Arturlang** [comment]
@MarkSuckerberg It was testmerged a couple of times and I was informed of a few bugs that I fixed

**Comment by tmtmtl30** [comment]
let's go

**Pull request merged**
