### PR TITLE
[DNM] Adds Snails People, a Gene mod from humans!

### PR DESCRIPTION
**Pull request by Sylphily**
## About The Pull Request
Ports parts of some snail stuff from [here](https://github.com/Skyrat-SS13/Skyrat-tg/pull/12800/files) along with make some edits to the snail, this includes the sprites for the cute snail shells. it also makes snails a round start race, and also makes them more balanced, also removed the triple text from them because it's quite annoying in game.

Auth for PR here on [discord](https://discord.com/channels/837744059291533392/837744059291533395/971500132518477835) 

I am completely open to any suggested (or required) changes.

About the lore for these guys, none officially they are from the genetic meltdowns from gene addict, and just slowly multiplied.

This is gonna be based on the kapulimbs pr so that it is able to be test merged if it does go through, also because the branch has seen no updates in about a month now.

I am also fulling willing to maintain this race
dreamseeker_6X9f7ufEDp
PSX0S40cud

To Do:

- [ ]  Get approval from those in power
- [ ]  Get the lore approved

## Why It's Good For The Game
A new cool Snail race, it was already in the code so it seemed like a cool thing to add and to spice up some gameplay

## Changelog
:cl:
add: Added snails as a round start race
del: Disabled the snail slurring
tweak: Edited a bunch of snail study
imageadd: Ports some more snail shells
code: Added a var to eyes for what layer to show on
/:cl:

### CODE REVIEW

**Comment by Sylphily** [comment]
totaly did not link a meme snail video in the desc by accident!

**Comment by Vexylius** [comment]
not a fan of that personally.

**Comment by Sylphily** [comment]
If I may ask why?

**Comment by Vexylius** [comment]
> If I may ask why?

Alright.
First question I would ask is "What makes this race unique?". It's a humanoid with an undroppable backpack that leaves a trail of slime then they crawl, correct me if I'm wrong, but crawling for them is faster than walking so in order to move at a reasonable speed they make the floor slippery, annoying everyone around.
On a station, especially TG station (where it was added), that would make sense gameplaywise, given their more arcade nature and their weird affection for light griefing (clowns). Let's say some new player assistant that doesn't know what's going on goes a bit far with genes and gets turned into this. Sure, cool, has some advantage over security, can do "the funny" until the round resets. It was originally not intended to be used as an actual race that people play as from roundstart, instead it was a sort of punishment for failing at genetics. Thankfully however, that happened so rarely that many people don't even know that this race exists in the code. Now here we are on Shiptest that tries to be RP with leftover code from TG that is meant for station gameplay and low to none roleplay in mind.
A good new race would introduce something new to the game. Some new mechanic, like IPCs have - charging from the APCs, unique robotic bodies making them more vulnerable but easier to revive... That changes the gameplay, making things interesting for a player playing that race and IPCs look cool. As for the snails, I do not see any of that incentive to play as that race, unfortunately.  

Another thing would be "Why snails exactly?". Realistically if someone were to go overboard with gene modification they would end up as a shapeless blob of flesh and pain, if they're even lucky enough (or unlucky) to be alive. Having them actually look like a snail would imply that someone specifically tried to take some snail genes, assuming that snails have some genetic advantages over humans (can't think of anything myself) and they were too careless when doing so, becoming this hybrid creature in the process. Lore isn't really extensive, assuming that all there is is what you've written in the PR...

> About the lore for these guys, none officially they are from the genetic meltdowns from gene addict, and just slowly multiplied.

That's a one sentence describing how you can become one IG and that they just multiplied. 
It's not much, and it's not very... entertaining or interesting.

Last but not least - visuals. For me personally this race is just not visually appealing. It does look like "what if snail, but human" as it should, but that does not very cool in my opinion.

But that's just my opinion, I'm open for feedback from other maintainers/leads on this.

**Pull request closed without merging**
