### PR TITLE
Adds Vergil chair to the game

### PR DESCRIPTION
**Pull request by ChesterTheCheesy**
obraz

## About The Pull Request
Adds a classic type of plastic chair.
obraz

Craftable with 5 sheets of plastic, functionally the same as comfy chairs.

- [X] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
Might motivate some people.

## Changelog
:cl:
add: Adds vergil chair (new type of plastic chair)
imageadd: added sprites for classic plastic chair
/:cl:

### CODE REVIEW

**Comment by ChesterTheCheesy** [comment]
https://user-images.githubusercontent.com/71487903/186501643-cb687781-f35f-4db4-b44b-8bb86d0f8533.mp4

**Comment by Latentish** [comment]
THE THRONE.

**Comment by ChesterTheCheesy** [comment]
not sure why but ok

**Comment by zestybastard** [comment]
> not sure why but ok

dont see a real reason for this to exist tbh

**Pull request closed without merging**
