### PR TITLE
Deletes the Synapse-Class Viral Study Vessel

### PR DESCRIPTION
**Pull request by Yellow-Mushroom**
## About The Pull Request

This PR deletes the Synapse class, both the map and the .json, not too much more too it

- [X] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game

With viro being in a very unstable place development wise, along with the general niche of the ship being entirely at risk, along with shipside errors, we think its the best to delete the synapse-class

## Changelog

:cl:
del: The NT Synapse-Class has been deleted
/:cl:

### CODE REVIEW

**Comment by Latentish** [comment]
Please fully remove it, and not just disable it.

**Review by PrefabQuasar — APPROVED** [review]
this change has been discussed and approved among the maptainers

**Comment by PrefabQuasar** [comment]
although yeah maybe fullremove

**Review by Latentish — APPROVED** [review]

**Comment by Latentish** [comment]
Spynapple.

**Comment by ForestCranked** [comment]
:(

**Comment by Ratvarr** [comment]
boss, it's been 9 years.

**Pull request merged**
