### PR TITLE
fixes some issues on the box and li tieguai class ships

### PR DESCRIPTION
**Pull request by BarteG44**
## About The Pull Request

-fixed misplaced light switches
-fixed misplaced fire extinguisher cabinets
-got rid of the errors from the li tieg's intern closet
-fixed some areas on both ships
-fixed some aesthetics that got messed up when the floor sprites got changed
-gave the li tieg an anesthetic closet 
-changed the box bathroom layout for like the 4th time
## Why It's Good For The Game

ship maintenance is good i think
## Changelog

:cl:
fix: fixed a few issues with the Box class
fix: fixed a few issues with the Li-tieguai class
/:cl:

### CODE REVIEW

**Review by goober3 — CHANGES_REQUESTED** [review]
image
this should be an air canister.

image
why is this scrubber connected to a plasma tank!

image
move this light fixture to the opposite wall and replace the walls over the layer adapters with windows. wall pipes should be avoided wherever possible.

image
image
light fixtures shouldnt be placed over posters!!

image
and posters should be pixel shifted onto walls, like wallmounts. 

image
as a general rule. try to place wallmounts, like light switches, in places where they could feasibly be reached without much effort. here, just move your light switch over to the right, if you want to keep the theme with APC-adjacent light switches.

image
get this Got Damn plant out of the way. or move the air alarm

image
move this light switch down 2 pixels.

li-tieguai review. Coming Soon

**Review by goober3 — CHANGES_REQUESTED** [review]
image
move the fire alarm here to the south wall, next to the techfab.

image
light fixtures on posters!!!!

image
move all of these north-facing light switches up 3 pixels.

guod job!!!

**Comment by BarteG44** [comment]
> why is this scrubber connected to a plasma tank!

the scrubber is clearly connected to a red pipe and the tank to an orange one 

>and posters should be pixel shifted onto walls, like wallmounts.

this was a conscious choice from before the wallening - fixed 

>move this light fixture to the opposite wall and replace the walls over the layer adapters with windows. wall pipes should be avoided wherever possible.

this got approved by erica before (most of these were actually approved by them since i pretty much only touched the switches)

>light fixtures shouldnt be placed over posters!!

that first poster is on the opposite side of the wall

>move this light switch down 2 pixels.

check it in game. APCs for whatever reason get shifted a few pixels in game from where they are in mapping

fixed the rest

**Comment by BarteG44** [comment]
>move the fire alarm here to the south wall, next to the techfab.

that wall's already crowded with the light switch and APC

>light fixtures on posters!!!!
 
those are ancient - fixed

**Comment by goober3** [comment]
> the scrubber is clearly connected to a red pipe and the tank to an orange one

image

>

> this got approved by erica before (most of these were actually approved by them since i pretty much only touched the switches)

and wallpipes are banned now! go fix it mapper boy

> that wall's already crowded with the light switch and APC

i mean!! next to the APC, not on the same part of the wall as the APC. better than under the wall locker.

**Comment by BarteG44** [comment]
TM this NOW
i've adressed the requests long ago

**Review by goober3 — APPROVED** [review]

**Comment by BarteG44** [comment]
would be nice if this got TMd this year

**Comment by spockye** [comment]
> would be nice if this got TMd this year

unfuck your tests and I'll CONSIDER tm'ing this next year

**Comment by BarteG44** [comment]
>unfuck your tests and I'll CONSIDER tm'ing this next year

image

the two month anniversary's coming

**Pull request merged**
