### PR TITLE
Removes the Pill

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Removes the Pill

## Why It's Good For The Game

image

## Changelog
:cl:
fix: pill and pill b were buyable
fix: they are still admin only

/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
NONONONONONONONOONONOO PLEASE NOT THE PILL ANYTHING BUT THAT PLEASE :WAA:

**Review by ZephyrTFA — APPROVED** [review]

**Comment by Zevotech** [comment]
image

**Comment by TallDeekus** [comment]
Had to do it to em, I am sorry little ones.

**Comment by Oscari-pog** [comment]
The end of a era

**Pull request merged**
