### PR TITLE
The Borea-Class Merchant Cruiser, an NT trade ship.

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
The Borea-Class Merchant Cruiser is a trade ship designed for the Nanotrasen faction with a vague Northwind shipping influence (if there are ways I could-should make this more obvious, please hit me up). It is designed around a large cargo area combined with a floor space for filling with goods. 
The Borea includes a delivery pod (The Zetes) for delivering goods to purchasers. Running it is typically the duty of the cargo techs
The crew is typically sized around 8, but can support up to 15.

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
It's a niche that NT apparently hasn't filled (aside from the Meta, which is barely NT), and a rather big ship. You could park this at an outpost and trade, you could ply the starlanes, you could get attacked by a pirate ship. Overall, fairly cool.

## Changelog

:cl:
add: The Borea-Class Merchant Cruiser can now be spawned in. It is a Nanotrasen oriented freighter. Take one for a ride and see the power of a dedicated trading vessel.
/:cl:

### CODE REVIEW

**Review by Latentish — CHANGES_REQUESTED** [review]
- All your airlocks use unneccessary helpers, and don't use high valume dualport air vents. Fix this please.
image

- You can remove these buttons.
image

- Missed a corner decal here.
image

- Move the docking port helper to the nose please.
image

- This ship is HUGE, you have plenty of space to make your bathroom large enough to have the sink, shower, and toilet all on different tiles.
image

- You could do a bit better on this barroom, it's a bit plain.
image

**Comment by Latentish** [comment]
In general, I really like this ship, it feels like I'm walking into a costco.
Just need to fix some things.

**Comment by Erikafox** [comment]
>This ship is HUGE, you have plenty of space to make your bathroom large enough to have the sink, shower, and toilet all on different tiles.

There's an actual bathroom in the staff area. I figured a department store-esque ship should have a bathroom, but probably wouldn't need a public shower. If someone really needs it they can ask the crew.

**Comment by Erikafox** [comment]
I've gone and redone the core shopping space, and to a lesser extent the front of the ship. The change is fairly significant and screenshots have been updated to reflect this.

**Comment by BarteG44** [comment]
the bathroom carpet is making me uncomfortable
obraz

**Comment by Erikafox** [comment]
honestly I stopped thinking it was funny so I'm just gonna patch that out.

**Comment by sensebucket** [comment]
1984 no shitter carpet

**Comment by Ms-Mee** [comment]
Weaklings, all of you, can't handle a single carpented shinklet!

**Comment by Erikafox** [comment]
Drafting pr until subshuttles get merged. This ship is perfect for one, and helping test them with it has reinforced my views on that. 

Just look at that funky dude. They're so much groovier than spacepods. You can actually live out your Nanotrasen Truck Driver Fantasies with it. 
image
dreamseeker_HbVKT489aZ
Goddamn is that cool and worth waiting for or what?

**Comment by Latentish** [comment]
Subshuttles don't actually have the systems in place properly yet. Also your checks say you got a lot of fucked up atmos pipes or something. I think that may be related but I'm unsure.

**Comment by Erikafox** [comment]
Fairly sure it's related. I was happy with how it performed during the subshuttle test. Aside from the whole front fall off thing.

**Comment by Zevotech** [comment]
image
1. Going to assume that the captain and bridge officer had a wardrobe mixup with the closets.
image
2. Crate full of... default circuit boards? They dont even work and cant be put into a frame. Not to mention this crate and the one opposite to it block the windoors.
image
3. Cloning and prototype cloning boards. While this is hilarious, I would create a new loot pool object to use instead of the current one.
image
image
4. These are not handheld radios. You cannot move these.
image
5. Front airlocks never open. They dont refill properly I think.
image
6. hnnnnnngh lopsided. uneven. painful.
Not pictured, but all of the airlocks have no access restrictions. I doubt you'd want people walking into the bridge or the security door areas freely.

**Comment by Latentish** [comment]
Pwease fix merge confwict

**Review by spockye — COMMENTED** [review]
image

missing wires

image

only place with a non-plat corner. unsure if intentional

image

zone error

image

unconnected disposals

image

unconnected disposal. Are these meant to be unconnected to the rest?

**Comment by Erikafox** [comment]
everything there fixed in latest, the two obviously connected ones are supposed to be a seperate thing yes.

**Comment by AverageUser67** [comment]
space walmart

**Comment by AverageUser67** [comment]
or nanomart idk what NT calls it

**Pull request closed without merging**
