### PR TITLE
Removes all uses of the broken get_station_level() helper

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
Removes all uses of the broken get_station_level() helper

## Why It's Good For The Game
Better for the code

## Changelog
:cl:
code: Removes all uses of get_station_level(). This may have ingame consequences but I don't know what to prod to make it flip off at the moment so I'll let you figure it out
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
This requires a TM because it touches some high priority files.

**Comment by shiptest-server** [comment]
#### Test Merge Deployed

##### Server Instance
shiptest

##### Revision
Origin: f789e74004b3acb82690d77398848b240a153b6f
Pull Request: 5d86cb061ad512d82c188a37d04e3fb257039611
Server: 1dbd0bfb0d4198bd0a0d556e3729419b22e55678

**Comment by shiptest-server** [comment]
#### Test Merge Updated

##### Server Instance
shiptest

##### Revision
Origin: 89b653c96fc59fa415eeb26666f154fe97f257c1
Pull Request: 5d86cb061ad512d82c188a37d04e3fb257039611
Server: 9172c1bfefbcd61b7e2dccb8f8cceb235072078e

**Comment by shiptest-server** [comment]
#### Test Merge Removed

**Pull request merged**
