### PR TITLE
handrails

### PR DESCRIPTION
**Pull request by fighterslam**
## About The Pull Request
This adds handrails, from Baystation - original PR that added them is [here](https://github.com/Baystation12/Baystation12/pull/18474). This doesn't actually add anything to any maps, but adds it as a structure for mappers to use.  I did a little bit of work by adding a crafting recipe, and simplifying things by making it a chair subtype. 

## Why It's Good For The Game
It's like. You can grab onto them. Makes Zero-G ships better, helps with transits so people don't go awkwardly rushing to chairs or just flop to the floor. 

## Changelog

:cl: fighterslam, comma
add: Handrails, rails on the wall that you can grab/buckle yourself to. (*Not included in any maps with this PR, but craftable with 4 iron rods.)
:cl:

### CODE REVIEW

**Comment by FalloutFalcon** [comment]
An image of them in game would be nice!

**Review by FalloutFalcon — CHANGES_REQUESTED** [review]
The concept is fine however the sprites could REALLY use some work, someone pointed out they would go well in sub shuttles. The sprites If you intend for it to be wall mounted it also needs offset sprites!
Make sure they have a material cost that matches the recipe since /chair/ has stuff related to it.
Chairs can also be rotated so take that into account.

**Comment by fighterslam** [comment]
The sprite is 7+ years old and not something I made. It's just a rip from baystation. The price is 4 iron rods, which is 2 sheets. Deconstructing a chair only gives you 1 metal sheet, so it's not a perfect conversion - I don't think this is a problem, but if you want me to change it, I could. Being able to rotate it shouldn't be that big of an issue, people might place them wrong and need to rotate it. As far as the subshuttle comment, again, this hasn't been mapped in anywhere in this PR, and at the moment I don't have plans to go around adding it to people's maps. 

If there's something you actually need me to change, please let me know, and please understand I am not an experienced coder and not a spriter. This is just a port of a feature that I want and a few other people have requested.

**Comment by fighterslam** [comment]
@FalloutFalcon

**Comment by fighterslam** [comment]
Here's some examples of the sprites ingame. Against walls, rails, any structure, really. (Subshuttles.)

image
image

**Comment by fighterslam** [comment]
In the Hyena-Class, it could fit in the airlock, or the hallways. This isn't part of the PR, just an example of how it could maybe be used.
image 

Vaquero-Class. 
image

**Comment by FalloutFalcon** [comment]
Use buildstacktype from chair. make it give back what you put in

**Comment by FalloutFalcon** [comment]
thgvr requested to make them wall mounts,
use a /obj/item/wallframe to craft and place it.

**Comment by fighterslam** [comment]
Thgvr retracted their statement about the wallmounts, is there anything else that needs doing @FalloutFalcon ?

**Review by FalloutFalcon — APPROVED** [review]

**Pull request merged**
