### PR TITLE
Speartip Transport 12c

### PR DESCRIPTION
**Pull request by Sparks3301**
## About The Pull Request
image

Long lad, made for scrapping and salvaging the various planets, and using that scrap to make big death machines.
Features
- 4 cabins for four crew, Scrapper, Mech Tech, Field Medic, and Pilot
- Each cabin has items suited to each role, a gun, and a modified sledge hammer (crowbar)
- Side ship guns so the planet doesn't spawn kill you
- A full robotics, including a special conceded weapon bay to outfit something like a Ripley. Also, 40k points and some survey devices because i don't know how to make tech disks work (if someone knows how to do it please contact me asap)
- A medbay, 4 first aid kits
- A crate with extra ammo, a mining rewards board and restock, and tools
- Cana, the void dog
## Task list

- [x] Make it pass all the checks
- [ ] Balance
- [x] remap it

## Changelog
:cl:
Adds: Speartip Transport 12c and its config
/:cl:

### CODE REVIEW

**Comment by Sparks3301** [comment]
image

**Comment by Zevotech** [comment]
dont worry about mapbot 2, its on drugs right now. ignore its check.

**Comment by Ketrai** [comment]
You mapped.. the ship backwards?

**Comment by Sparks3301** [comment]
> You mapped.. the ship backwards?

pardon?

**Comment by Yellow-Mushroom** [comment]
> > You mapped.. the ship backwards?
> 
> pardon?

not sure if this is true, but most ships are facing a certain direction so when they move in space, it appears like they are moving forward against the background. It appears like your ship will be moving backwards against the background but like, im not very versed in this area.

**Comment by Sparks3301** [comment]
> 

ah, great, i might fix that, but that would mean i remap the entire thing

**Comment by Fikou** [comment]
the ship is mapped correctly. as long as your docking port is set up correctly it will fly the right way. see https://wombat.platymuus.com/ss13/shuttles.html

**Comment by Fikou** [comment]
also why the hell are you webediting a map

**Comment by Sparks3301** [comment]
> also why the hell are you webediting a map

there is another way?

**Comment by Sparks3301** [comment]
> as long as your docking port is set up correctly it will fly the right way

it really doesn't want to fly west and not turn at the same time, I can make it fly west, but it turns messing up doors and signs. I can make it fly east and not turn when landing, I've looked at all the ships I could think that do this but none do, the closest is kilo which is like this but fly's east, might just have to bite the bullet and remap it

**Comment by Latentish** [comment]
I really like the design of this ship, but I do feel like we have a good few ships for this niche already. What makes your ship special or apart from something like the dwayne or the li tegual?

**Comment by Sparks3301** [comment]
> What makes your ship special

Well, this is a cargo ship that is tailored for hash enviroments, meant to be a group of salvagers hopping from planet to planet and scrapping parts and finding ruins, stuff like that. And if I'm mistaken i dont think we have a ship that uses the pod walls, nor is just long. But yeah, it can be a bit similar to something like the lux but less op

**Comment by Latentish** [comment]
> > What makes your ship special
> 
> Well, this is a cargo ship that is tailored for hash enviroments, meant to be a group of salvagers hopping from planet to planet and scrapping parts and finding ruins, stuff like that. And if I'm mistaken i dont think we have a ship that uses the pod walls, nor is just long. But yeah, it can be a bit similar to something like the lux but less op

- On one hand, I feel like there are several.ahips that do a very similar job to this ship. On the other hand, I really like this ship. It's cramped, but super comfy.
- i'd just test to make sure those wide blast doors actually work. Last time I tested them, they just didn't show up.

**Comment by Sparks3301** [comment]
>I feel like there are several ships that do a very similar job to this ship

Is there any suggestions to make it more unique and set it apart?
>i'd just test to make sure those wide blast doors actually work

just did and they work, but there is a visual bug where you can see through it until you open and close it, then its not see through

**Comment by Latentish** [comment]
> Is there any suggestions to make it more unique and set it apart?

- Unique equipment scattered throughout it, maybe swap cargo and all its equipment with another, non-mining/cargo department. If it's salvaging, maybe a small engineering or just workshop area would work. Maybe some robotics stuff and engi stuff slapped into one role (you can make unique roles relatively easily). So you could have one part mining/salvaging team, and one part redeemer/mechanic/repurposer. That'd really make it fit this niche of rugged salvager ship. Without the lextreme uxury of cargo.

> just did and they work, but there is a visual bug where you can see through it until you open and close it, then its not see through

- You may want to test how those doors act when your ship turns as well, because I velieve it's one of those objects that hates turning under any circumstances.

**Comment by Sparks3301** [comment]
> test how those doors act when your ship turns

My ship doesn't turn and yeah they really hate it, its the reason I remapped it to face east
> robotics stuff

this is a great idea, although I wouldn't know how to give robotics without having to give science to unlock the stuff first, is there a way to have a circuit imprinter only be able to print mech boards? as well as a unlocked mech printer, because both of these would make it possible

**Comment by Latentish** [comment]
> I wouldn't know how to give robotics without having to give science to unlock the stuff first, is there a way to have a circuit imprinter only be able to print mech boards? as well as a unlocked mech printer, because both of these would make it possible

- You could either make the job that uses that area have access to it (like robotics and engineering accesses), or make subtypes of the machines with different access. Or both.


Also your remap looks solid, I like the workshop room. Though maybe remove a pair of turrets.

**Comment by Latentish** [comment]
I'd like to see an update on this. Seeing those turrets moved and this get marked as ready for review would be nice. Please update the branch and space those turrets out a bit better, and we can see about getting this TM'd.

**Comment by Sparks3301** [comment]
god I am so sorry, just graduated high-school and currently learning a new job, but I'm back and I have removed the front turrets, removed a bunch of useless Var-edits, removed 2 of the poly-rifles, and currently looking into making a completely unlocked mech fab so I can cut R&D out completely

**Comment by Sparks3301** [comment]
honestly, i would rather something else get in, this ship is just filling an already filled niche, I also want to not make more independents as there are so many already. I might try again when there are more non-independent ships

**Pull request closed without merging**
