### PR TITLE
Adds The Solarian Paracelsus-class Medical Corvette!

### PR DESCRIPTION
**Pull request by Imaginos16**
## About The Pull Request
YOU! YES, **YOU**.

As a diligent citizen of the Most Serene Solar And Intersolar Confederation, I'm sure you've had a situation where you needed to visit a doctor! Perhaps you had a scraped knee? Some problem with your vision, even? Or maybe, just *maybe*, you stumbled into a nuclear dump site in some waste planet and you *foolishly* walked inside said site without a hazmat suit on?

Well lucky for you, the Paracelsus-class Medical Corvette is here to assist you JUST for this most-convenient occasion!

Boasting a crew composed of:

- One Captain
- One Bureaucrat
- Three Medical Doctors
- One Ship Engineer
- One Field Engineer
- Three Scribes

These most wonderful adventurers shall assist you in restoring your physique to its natural state, before it was completely dashed by a frontiersmen who was too smart with a combat shotgun! The ship's faculties are also spacious, and made to encourage discourse and camaraderie between fellow crewmembers! Dedicated rooms for medical professionals to practice their specialties also exist, so they can bring their full potential, in privacy or otherwise!

Now go out there, and help as many people as you can!*

(*Premiums may be liberally applied to non-solarian citizens)
 

## Why It's Good For The Game
This is my first ship ever and I've done it with an extreme amount of love, not just for this server, but also because I fucking love SolGov and they desperately need more ships that aren't just the Chronicle. Hopefully having an RP-oriented medical ship will encourage others to read up on SolGov lore and have fun times there!

## Changelog

:cl: PositiveEntropy
add: Adds a SolGov medical ship, the Paracelsus-class!
/:cl:

### CODE REVIEW

**Review by Erikafox — CHANGES_REQUESTED** [review]
image
Make sure you're aware of what the closet populates with before you put more in.
StrongDMM_g7cdTk2Csm
pixelshift the laptop up onto the table
StrongDMM_Wtb4kq8HiO
top and bottom should be facing north-south
StrongDMM_fJIiYo7AgD
hardsuit and plant should swap spots, their spot on the floor should be differentiated somehow. As an aside the lightswitch in the bottom left needs to be shifted to the left 3 pixels
StrongDMM_sPOat0N7xd
StrongDMM_Ga9SgFxSeQ
give these two areas their own ID tags for the windows. You *might* be able to make the ID a list (and thus attach it to multiple buttons), but I'm not sure.
StrongDMM_1PuI1nq6aa
check this locker's populate too
image
de-capitalize
StrongDMM_0fbR41T97d
I don't care for holopad on carpet, but it's not a showstopper here.
StrongDMM_HpcyBHLZmy
doublebeds have directions
StrongDMM_Rl5haVdQqe
icky perspectiving here. Move the lower seal up a few pixels
StrongDMM_w8h53bYBOJ
shift that microwave up 5 pixels
image
You are going to need at least 3 high capacity dual port vents for an airlock this size (/dp_vent_pump/high_volume/). Look at how the vela does it's cycling airlock for an example on how to properly layer and connect them in a denser fashion.
image
Captain should get a bolt button (use a /door button, set the id var on it to match the id_tag var on the door, set the button's special function var to 3). The surgery rooms and Walter White Chamber could also use them.

bad
image
Your engines need to be linked by cable to their prechargers. Being adjacent is not enough
StrongDMM_Oh3jH3fMUy
bad
StrongDMM_ySToqdoPDX
bad

Needs more intercoms scattered around the ship, a spot for a telecomms relay somewhere, and a pass for walls that shouldn't be diagonal (put /nodiag walls where you decide they shouldn't curve)

**Comment by Imaginos16** [comment]
Recent commit addresses most of the criticism, big one still missing is adding a relay (waiting on the chronicle to get merged to do that properly), and for some reason the bolt buttons do not work. If someone can figure out what's up, that'd be great!

**Review by Erikafox — APPROVED** [review]

**Comment by thgvr** [comment]
fugue in D minor

**Comment by Zevotech** [comment]
Medbay could use some pre-placed medhuds and some nitrile gloves. I know the vendor has them but its nicer to have them already stocked.

**Pull request merged**
