### PR TITLE
Removes the "When you code it!!" event from the nanite programmer. (not clickbait)

### PR DESCRIPTION
**Pull request by Zevotech**
## About The Pull Request
Makes it so the nanite programmer doesn't lose its shit when it hears the word "when" and proceed to tank the server.

## Why It's Good For The Game
The server will no longer eat shit due to funny code.

## Changelog
:cl:
del: forgor'd the nanite programmer losing its shit upon hearing the word "when"
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
and yeah it actually works this time, im just a fuckin moron

**Comment by Ms-Mee** [comment]
> and yeah it actually works this time, im just a fuckin moron

Why make a new PR though

**Comment by Zevotech** [comment]
> > and yeah it actually works this time, im just a fuckin moron
> 
> Why make a new PR though

see: im a fuckin moron

**Comment by Nobelium-XVIII** [comment]
The soul...

**Comment by jupyterkat** [comment]
why not port the fix for this from bee that fixed this feature instead of just straight up removing it

**Comment by Zevotech** [comment]
> why not port the fix for this from bee that fixed this feature instead of just straight up removing it

1. "feature" my ass.

2. why bother? why even let this exist?

**Comment by jupyterkat** [comment]
> > why not port the fix for this from bee that fixed this feature instead of just straight up removing it
> 
> 1. "feature" my ass.
> 2. why bother? why even let this exist?

it’s funny, duh

**Comment by Zevotech** [comment]
making the server shit itself via the same method becomes unfunny after like, the 5th time.

**Comment by jupyterkat** [comment]
make it not shit itself by fixing it. removing it just makes you a lazy shit

**Comment by Zevotech** [comment]
you want to fix it? then move it onto something besides the nanite programmer.
When you code it!

**Comment by jupyterkat** [comment]
it's a nanite *programmer* why do you not get it

**Comment by AtlasRules** [comment]
ladies ladies

you're both stupid, but this event is stupider

**Comment by Ms-Mee** [comment]
> ladies ladies
> 
> you're both stupid, but this event is stupider

No, this is coder culture and very important

**Comment by Zevotech** [comment]
> ladies ladies
> 
> you're both stupid, but this event is stupider

sigma grindset over here has a point

**Comment by martinlyra** [comment]
I do not understand. Why do you want to keep this "when you code it" joke in the game? It is old and so overused, not even Reddit would upvote this anymore. It can come off as condescending to both coders and not coders alike.

At least acknowledge that there exist people who do not understand or share your sense of humour.

Besides, it is just easier to delete this.

**Comment by jupyterkat** [comment]
coders aren't supposed to have jokes now huh

**Comment by Kapu1178** [comment]
> coders aren't supposed to have jokes now huh

When you code it.

**Comment by ZephyrTFA** [comment]
This is essential coder culture. Just make it have a five second cooldown

**Comment by Zevotech** [comment]
image

**Comment by AtlasRules** [comment]
freakin schweet lois

**Pull request closed without merging**
