### PR TITLE
Decal Fixes/Updates [MDB IGNORE]

### LINKED ISSUE #370: [BUG] many decals are still missing a sprite
## Reproduction:
Open SDMM, search by /turf_decal, cry

As seen in ships nobody bothered to fix (poor, poor delta)
image

And in this sobering image
image

Baytiles are a blessing and a curse

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request
PROBABLY Fixes: #370

Updates a lot of the new bay decals that didn't work quite right to do as they were supposed to, condensed any duplicate decals, and updated a few icons.

Updated baytile conversion script, so map conflicts can be resolved by simply resetting and re-converting.

## Why It's Good For The Game
Mappers can pull their hair out a little bit less after this.

## Changelog
:cl:
fix: All sorts of decal bugs/duplicates/&c.
/:cl:

### CODE REVIEW

**Comment by ZephyrTFA** [comment]
@MarkSuckerberg you have conflicts and I have zero mapping knowledge

**Comment by MarkSuckerberg** [comment]
I'm waiting for every map PR to get in, so I can just hard reset _maps to master and then re-run the conversion script

**Comment by Sun-Soaked** [comment]
no more spung bob

**Comment by MarkSuckerberg** [comment]
bite me

**Pull request merged**
