### PR TITLE
Replaces Slimerancher.dmm with Slimelab.dmm 

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request

This pull request completely removes the problematic (but apparently popular) Slime Rancher ruin and replaces it with a Slime Research Laboratory. While the lab has some issues, may be causing global warming by means of TEG, and seems to have an issue with the lab proper's condition, it has the ability to communicate with ships and lure people in to trade for slimely goodies. 

dreamseeker_6vFSImNmmJ
dreamseeker_YPOuNxMRhY

- [ ] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.
- [x] I affirm that I got the ruin to spawn in game and flew around a bit as a ghost, popped in as one of the roles, and ran through it in a rather meta fashion, fixing the broken things I saw.
## Why It's Good For The Game
It fills Slime Rancher's niche without having a gas chamber.

## Changelog

:cl:
add: Slime Lab. A replacement for Slime Rancher. Don't worry, there's still ghost roles.
add: "Geothermal" RTGs, for the mapper who just wants a ruin to have a power supply.

/:cl:

### CODE REVIEW

**Comment by Erikafox** [comment]
The current special name list for this ruin is a bit sparse.
That is to say this is it 
"Maroon", "Funky", "Squishy", "Bubblegum", "Gummy", "Pinkie Pie", "Rainbow Dash", "Beatrix LeBeau", "Chartreuse", "Chocolate"

If you'd like more slime names while this is on my mind dm them to me on discord or just comment them here.

**Comment by Calyxman** [comment]
I dislike the MLP names being in the list (pinkie pie? rainbow dash?!). Other than that good names, could use a little more slime pun
Pretty good ruin

**Comment by Ms-Mee** [comment]
Slimes AND global warming? :flushed:

**Comment by Valorium-RB** [comment]
As far as names:
"Goobert", "Blorbo", "Creeper", "Leaper" (both references to that "Beware the Blob" song people like to play during Blob events), "Pyro", "Monk", "Slim", "Malice" (a reference to an exceptionally popular Binding of Isaac mod featuring a slimy protagonist), "Moldova" (get it? slime mold-ova?), "Sloshy", "Slick", "Emil", "Poison", "Grey", "The Specimen", and "Clotty" are my suggestions. For now, at least.

**Comment by Erikafox** [comment]
Fairly decent changes to the lab and surrounding area, screenshots have been updated to reflect it.

**Comment by Latentish** [comment]
This is a good rework. Let's tm if the checks smack that caddy just right

**Comment by ZephyrTFA** [comment]
APC pixel offset needs to be a multiple of 25, that is why your lints are failing

**Comment by Erikafox** [comment]
let me fix that quickly.

**Pull request merged**
