### PR TITLE
Adds Kepori variation to some Syndicate & Faction suits

### PR DESCRIPTION
**Pull request by HometownFunky**
## About The Pull Request

We have all these cool suit sprites that Kepori players should also be able to enjoy. 
This PR adds a bunch of Kepori variants of the Syndicate, Inteq and faction suits.

Syndicate & Faction suits:
Syndicate Side

Syndicate

Inteq suits:
Inteq Side

Inteq

## Why It's Good For The Game

Visually distinct sprites for distinct suits.

## Changelog
:cl:
add: Added a new flag for kepori clothing
imageadd: added some icons and images

/:cl:

### CODE REVIEW

**Comment by triplezeta** [comment]
@PiperDoots

**Comment by thgvr** [comment]
Sprites for the sprite god.

**Comment by PiperDoots** [comment]
These are overall really nice!! Though you lose some perspective on the pants by making them flat.

**Comment by PiperDoots** [comment]
Specifically in the front state at least, should probably clarify that. The line here is used to insinuate that they go back a bit. Other than that don't be afraid to cover up more of the arms in the front state, the way you do it here works well if you make shorter sleeve clothing though! Really like the skirts you did here btw
image

**Comment by PiperDoots** [comment]
Shoulderblade position in the sidestates is also a bit off as their arms are more in the middle of the body though that's easily fixable by removing some of the darker pixels at the top. Also maybe just a general thing but try covering up the gap between the arms and the hands in the sidestates as well, Kepori clothes are meant to be looser fitting in general, both culturally and because most of the stuff is too big for them. 

So yeah overall superb work but needs some slight touchup! Can't wait to see them in game!

**Comment by HometownFunky** [comment]
Thanks! I'll work on the changes and I'll post an update!

**Comment by PiperDoots** [comment]
Oh and one last thing you forgot to cover part of the arm here! If you need help with anything feel free to reach out I know how annoying they can be to work with sometimes!
image

**Comment by HometownFunky** [comment]
Worked on the shading of the pants here
Bloodred_front

Cybersun_front

Pants 2!

Pants

(Bloodred PJs have that arm pixel now)
Bloodred_side

Tried to make the arm gap less noticeable
Arm Gap

Here's my attempt at lowering the shoulderblades (should I push them lower?)
Shoulderblade

As for the gap between the arms and the hands in the sidestates, you meant this, right?
Gap

**Comment by PiperDoots** [comment]
> Worked on the shading of the pants here

Way better already! Could go a bit more overboard on the tan pants.

> (Bloodred PJs have that arm pixel now) 

Sweet! Just now noticed that the pixel I was referring to is actually part of the suit and your model was just similarly colored.

> Tried to make the arm gap less noticeable

This is a bit hard to see without the actual sprite over it, checked one of them and it looked fine but if you could send an image with all of it that'd be grand!

> Here's my attempt at lowering the shoulderblades (should I push them lower?) 

Removing the "divider" pixel on some of these could really help on these I think. Make it feel less like the arm was attached to the jumpsuit later and does wonders with making it feel lower. 
image

> As for the gap between the arms and the hands in the sidestates, you meant this, right?

Yeah! Best to fill it up when making clothing as it makes it feel less tight.

Overall great progress already and definitely in the right direction! Some small fixes here and there and you should be golden! Good thing to keep in mind is that most of this stuff is meant to feel too big on them. As both a cultural thing (feather care and tight clothing really don't fit well together) And human clothing generally not being fit for Kepori either way. Leaning into that helped my mindset a lot when working on them originally.  This is the main reference I've been using for cultural clothing, might help you out here too!
zomg journey from journey

**Comment by HometownFunky** [comment]
I've tried to extend the sleeve over part of the hand, like this
Sleeves 1
or this
Sleeve 2
Is it better?

**Comment by PiperDoots** [comment]
Actually not 100% sure if this will work in game or nor due to the way the hands are set up. Though this is something we could technically change. Sleeves in general do look good though!

**Comment by PiperDoots** [comment]
If I did change it it would require cutting out parts of clothes but it is technically possible.

**Comment by HometownFunky** [comment]
Did some tweaks and updated some stuff, here's what I got. (Also forgot the cybersun surgeon suit in the first preview)
Factions:
Factions Updated
Factions Updated Side
Factions Updated Back

Inteq
Inteq Updated
Inteq Updated Side
Inteq Updated Back

Syndicate
Syndicate Updated
Syndicate Updated Side
Syndicate Updated Back

Also yeah I think the hand sprite covers a bit of the sleeve when facing sideways & I have honestly no idea on how to fix that.

**Comment by PiperDoots** [comment]
I could do it if you want me to

**Comment by PiperDoots** [comment]
There we go, made a fix that should allow sleeves and such to work better. 
[#1333](https://github.com/shiptest-ss13/Shiptest/pull/1333)

**Comment by HometownFunky** [comment]
In game Syndie & Factions suits, now with sleeves
Front Updated
Side Updated
Back Updated

And inteq
Inteq Bird Front
Inteq Bird Side
Inteq Bird Back

Close up of some of the sprites
Examples so far
Examples so far 2
Examples so far 3
Examples so far 4

Thoughs?

**Comment by PiperDoots** [comment]
Looks good to me! The one complaint I have left here is that the flow on the back of the skirts is a bit off, should probably put a connecting pixel there.
image

Great work!

**Comment by HometownFunky** [comment]
Updated skirts
Skirts

**Comment by PiperDoots** [comment]
Much better! Looking good!

**Review by triplezeta — APPROVED** [review]
looks good to me

**Comment by triplezeta** [comment]
oh right. the digitigrade PR

**Comment by Ebin-Halcyon** [comment]
VERY cute Inteq stuff for them! Was planning to do it for them someday as well.

**Comment by triplezeta** [comment]
!remindme 2h

**Pull request merged**
