### PR TITLE
Removes ORM from non-mining/salvage ships.

### PR DESCRIPTION
**Pull request by Sadhorizon**
## About The Pull Request
Removes the ORM from Beluga, Box, Schmiedeberg, Colossus, Skipper and Kansatsu.

Aspawn ships, Hyena and Gecko still have it, because:
- Hyena is a mining/salvage ship, so it needs it.
- Gecko is a salvage ship, so it needs it.
- I've been told not to touch aspawn ships.

## Why It's Good For The Game
They have no reason to have an ORM! They are not mining/salvage-centered ships, so they can totally go to the outpost to refine their ore!
(it's a Dwayne buff in disguise :3)

## Changelog

:cl:
del: Beluga-class, Box-class, Schmiedeberg-class, Colossus-class, Skipper-class and Kansatsu-class lost their Ore Redemption Machines.
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
This needs to come after improvements to the UI and usability of furnace setups

**Comment by Sadhorizon** [comment]
> This needs to come after improvements to the UI and usability of furnace setups

Those ships shouldn't have furnaces/ORMs in the first place. The only reason they do is because they are old.

**Comment by thgvr** [comment]
The outpost one also sucks to use.

**Comment by Apogee-dev** [comment]
> This needs to come after improvements to the UI and usability of furnace setups

This is only removing ORMs from ships that shouldn’t have had them to begin with. Existing mining specialists keep their current equipment. 
> The outpost one also sucks to use.

That the outpost furnace sucks to use isn’t really relevant to the fact that a hospital ship shouldn’t have its own refining machine, for example- if the issue’s bad enough, just put an ORM on the outpost and call it a day until furnaces get touched up.

**Review by Latentish — DISMISSED** [review]
I would like to clarify something. No map should have an ORM. Some maps get a smeltery like on the outpost or the Delta. Please remove it from _all_ ships if you are doing an orm removal.

**Comment by Apogee-dev** [comment]
> I would like to clarify something. No map should have an ORM. Some maps get a smeltery like on the outpost or the Delta. Please remove it from _all_ ships if you are doing an orm removal.

The only reason I didn't suggest replacing it on the mining ships that still have one is because that usually necessitates at least a partial remap. But if we're going for a hard removal, then yeah, some minor remapping on the Gecko and Hyena will be necessary. They'll get more polished remaps in the next month or two anyway.

**Comment by Sadhorizon** [comment]
> I would like to clarify something. No map should have an ORM. Some maps get a smeltery like on the outpost or the Delta. Please remove it from _all_ ships if you are doing an orm removal.

Point of the PR is to remove ore smelting from non-mining/salvage ships. Not really interested in remapping gecko and hyena rn, I'm sure they will be handled at some point.

Also, I've been told not to touch aspawn ships, if that's what you mean. Though I can, if you want me to.

**Comment by rye-rice** [comment]
@Sadhorizon do you think you could remake this sometime?

**Comment by Sadhorizon** [comment]
I guess?

**Comment by thgvr** [comment]
im releasing this from purgatory

**Pull request merged**
