### PR TITLE
[FOOLSTEST][DNM] removes humans

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
## About The Pull Request

removes humans

## Why It's Good For The Game

uh

## Changelog

:cl:
del: humans
/:cl:

### CODE REVIEW

**Comment by thgvr** [comment]
mods merge this

**Comment by Sun-Soaked** [comment]
bloatcode removal

**Comment by meemofcourse** [comment]
speedmerge

**Comment by TheNeoGamer42** [comment]
what about felinids?

**Comment by Sun-Soaked** [comment]
> what about felinids?

they will replace humans as our core setting species

**Comment by ZephyrTFA** [comment]
> > what about felinids?
> 
> they will replace humans as our core setting species

nope nope nope NO

**Comment by thgvr** [comment]
we dont even HAVE felinids

**Comment by ZephyrTFA** [comment]
vox become the default species or no game

**Comment by thgvr** [comment]
OK but you have to fix the sprites

**Comment by ZephyrTFA** [comment]
💢

**Comment by TheNeoGamer42** [comment]
> we dont even HAVE felinids

ill fucking readd them and make them the default species

**Comment by MarkSuckerberg** [comment]
:(

**Pull request closed without merging**
