### PR TITLE
Ports the Requests Manager, Minor Fax QOL, Adds factional offices to CentCom

### PR DESCRIPTION
**Pull request by meemofcourse**
## About The Pull Request
This pull requests ports:
* https://github.com/BeeStation/BeeStation-Hornet/pull/9408
* https://github.com/BeeStation/BeeStation-Hornet/pull/9236
This pull request reverts:
* https://github.com/tgstation/tgstation/pull/70072

The requests manager is now a thing.
264860380-6d27a710-8ac1-4864-9abe-4c13f4885cba

It also adds little offices with fax machines for factions to CentCom, which recieve the physical paper and can send faxes back (though admins can still make use of the fax panel). 
imagen
They can also fax each other, if ever needed.
imagen

## Why It's Good For The Game
* Gives admins the ability to see a very easy to use recap of all requests that occur in a round. This system is readily extendible to support other types of requests, should someone care to add it.
* Better admin tools, admins can now send faxes directly via the new Fax Manager verb, and faxes are show in the request panel instead of its own panel.
* You can now LARP as a Cybersun minimum wage intern handling faxes.

## Changelog

:cl: bobbahbrown, itsmeow, meemofcourse
add: CentCom now has some small offices, which recieve physical faxes.
add: Fax machines now announce that they have received a fax over radio.
add: Fax machines announce important faxes VERY LOUDLY.
balance: Faxes no longer require a subspace ansible crystal.
code: Faxes now use typepath instead of varedit.
tweak: Changed how special/faction faxes work. Login is no longer required to use special faxes.
admin: Add Requests Manager to view all fax messages/prayers/centcom and syndicate requests/and nuke code requests within a round.
admin: Removed old fax manager in favor of Requests Manager, added "Send Fax Message" verb to send admin faxes via a menu.
fix: Fixed runtime when ghosts tried to view paper.
/:cl:

### CODE REVIEW

**Review by MarkSuckerberg — APPROVED** [review]
very very nice

**Comment by thgvr** [comment]
Planning on any more changes?

**Comment by meemofcourse** [comment]
there's an issue that paper written in the fax manager has advanced_html properly applied, but not when it's sent to other faxes. also the colors in the admin fax list are a bit wonky

**Comment by meemofcourse** [comment]
nvm i figured it out

**Comment by thgvr** [comment]
We're so back

**Pull request merged**
