### PR TITLE
Fixes indestructible doors & puts them on outposts

### PR DESCRIPTION
**Pull request by Sun-Soaked**
## About The Pull Request

Fixes the missing sprite indestructible door, adds 2 new subtypes(external airlock and blast door)
Implements these on outpost 1 and 2, replacing the slightly silly "wall under a door" situation, and the missing texture map varedit walls

Also moves a poster that was occupying the same space on a wall as a fire extinguisher in outpost 2 cargo

## Why It's Good For The Game
doormf

## Changelog

:cl:
add: Fixes the texture on indestructible doors and adds 2 new variants
tweak: A poster on outpost 2 that was occupying the same space as a fire extinguisher has been moved

### CODE REVIEW

**Comment by goober3** [comment]
hey!! sorry!!! this is already covered in #2250

**Comment by BarteG44** [comment]
Merge both so the fix is twice as good

**Review by PrefabQuasar — APPROVED** [review]

**Comment by Sun-Soaked** [comment]
> hey!! sorry!!! this is already covered in #2250

indestrucftible door sprite fix thoughghgh

**Comment by goober3** [comment]
> > hey!! sorry!!! this is already covered in #2250
> 
> indestrucftible door sprite fix thoughghgh

that's also included!

**Comment by Sun-Soaked** [comment]
> > > hey!! sorry!!! this is already covered in #2250
> > 
> > 
> > indestrucftible door sprite fix thoughghgh
> 
> that's also included!

gugh.

**Pull request closed without merging**
