### PR TITLE
add bad apple to ipc screen types

### PR DESCRIPTION
**Pull request by VernaSaurus**
## About The Pull Request

adds the entirety of bad apple to the selectable IPC screens

## Why It's Good For The Game

because it's very funny

## Changelog

:cl:
add:ba da pple
/:cl:

### CODE REVIEW

**Comment by VernaSaurus** [comment]
okay I was requested to add a video so

https://github.com/shiptest-ss13/Shiptest/assets/64121399/b8f7e832-9d88-41f2-8dda-7e8e39676f83

**Comment by tmtmtl30** [comment]
name it something like "animation"

**Comment by VernaSaurus** [comment]
> name it something like "animation"

sure, I'll call it "Old Animation"

**Comment by ZephyrTFA** [comment]
I imagined the song in my head as I watched

**Review by ZephyrTFA — APPROVED** [review]

**Comment by ZephyrTFA** [comment]
the only reason I'm not instant merging this is because Mark would unironically kill me

**Comment by thgvr** [comment]
yknow ok

**Comment by Admiral-Gigaton** [comment]
> okay I was requested to add a video so
> 
>  bab.able.mp4

STAHP MOVIN REEEEEE (is good, keep up the good work)

**Pull request merged**
