### PR TITLE
New Ruin: Crashed Research Pinnance

### PR DESCRIPTION
**Pull request by Erikafox**
## About The Pull Request
Adds a new lavaland ruin to the game, the crashed research pinnance. The Crashed Pinnance was formerly a 1 man science vessel, before lawndarting into a lavaworld, fracturing the hull and killing its occupant. It is now a monument to vacations better left unplanned.

dreamseeker_SanGXF9s5e

Contained within this ruin is:
2 premium ion engines, and prechargers.
1 elite survey handheld
2 advanced survey handhelds
1 PACMAN
1 Science Goggles
Fake sunglasses
Purple Shorts
A research director bedsheet
assorted salvage.

- [x] I affirm that I have tested all of my proposed changes and that any issues found during tested have been addressed.

## Why It's Good For The Game
More ruin variety is good I think.

## Changelog

:cl:
add: The Crashed Pinnance Ruin, it can be found on lavaland and contains the unfortunate remains of a vacation gone wrong....
config: Pinnance Ruin will spawn.
/:cl:

### CODE REVIEW

**Comment by Erikafox** [comment]
I would not be against adding a monster - trimming the loot.

**Comment by Zevotech** [comment]
this looks pretty fuckin great

**Comment by Latentish** [comment]
Please add an image showing your areas.

**Comment by Erikafox** [comment]
Done.

**Comment by Latentish** [comment]
Honestly I just don't feel like this ruin is very worth going to. As a greeble (a supporting small submap) it'd be fine if it were smaller, but then it'll need to be disabled until that system gets made.
This isn't to say there isn't enough gamer loot. It's more that there's not enough ship for salvaging to really be worth the effort. You can look at the interceptor ruin for one of our strongest crashed ship ruins.

**Comment by Erikafox** [comment]
Imo not every ruin needs to be some majestic complex of loot and salvage. They can just be interesting setpieces, so I think this is fine.

**Comment by Latentish** [comment]
I'd be up to test merge this one. If the rerun of checks passes.

**Comment by Latentish** [comment]
This is pretty aight. Marg approval from me.

**Review by Latentish — APPROVED** [review]

**Pull request merged**
