### PR TITLE
Deletes DJstation.dmm

### PR DESCRIPTION
**Pull request by rye-rice**
## About The Pull Request

Apparently this was causing empty space ruins lmao

## Why It's Good For The Game

Bugfix

## Changelog

:cl:
del: A broken ruin was deleted
/:cl:

### CODE REVIEW

**Review by Latentish — CHANGES_REQUESTED** [review]
I don't want this ruin showing up. Please make this a removal.

**Comment by rye-rice** [comment]
easffwedawafweaf

**Review by Latentish — CHANGES_REQUESTED** [review]
image
This is the DJstation entry, I don't know why it's incomplete, but this is definitely the entry for dj station. Remove it please.

**Comment by Latentish** [comment]
Please PLEASE please
update your pr

**Pull request closed without merging**
