### PR TITLE
[READY][TM-REQ] Ports the CBT and TGUI refactors from /TG/

### PR DESCRIPTION
**Pull request by ZephyrTFA**
## About The Pull Request

Ports a lot of shit from /TG/station regarding the CBT and TGUI
__I did this EXPLICITLY so that I can use the tgui-dev-server__

## Why It's Good For The Game

Better build tools and debugging framework

## Changelog
No player-facing changes

:cl:
/:cl:

### CODE REVIEW

**Comment by Zevotech** [comment]
I think you deserve choccy milk for this one boss

**Comment by Ebin-Halcyon** [comment]
[Giggling can be heard]

**Comment by ZephyrTFA** [comment]
> [Giggling can be heard]

The only CBT in this port is happening to me

**Comment by martinlyra** [comment]
> Not sure why the regex pattern (the last element) uses doubles instead of single quotes compared to the others. Just in case if it was not intentional.

Okay, Github did a bit funny. Here is where the line in ´check_regex.yaml` I was trying to single out. 
bild

**Comment by ZephyrTFA** [comment]
After what I can only describe as pure and unadulterated agony this is ready for TM.

**Comment by AtlasRules** [comment]
> [Giggling can be heard]

Huhuhuhuh... Beavis... The PR says CBT... huhuhuhuh...

image

**Comment by The-Moon-Itself** [comment]
There's a bug where sometimes when you open an UI, it closes about a second later without any player input.

**Comment by CursedBirb** [comment]
Sometimes UI comes back to previous one. Like when i choose join and decide to buy ship it will close and open previous window so i have only few sec to look for ship to buy

**Comment by Auris456852** [comment]
It doesn't necessarily seem to just close a second later, either. It just seems to close randomly, with no reliable way to replicate it. Experienced it primarily with the orbit menu, if only because that is all I used.

**Comment by Recoherent** [comment]
The admin gamepanel spawn menus are broken; searching for a term just doesn't pull up a list of results.

**Comment by ZephyrTFA** [comment]
> There's a bug where sometimes when you open an UI, it closes about a second later without any player input.

> It doesn't necessarily seem to just close a second later, either. It just seems to close randomly, with no reliable way to replicate it. Experienced it primarily with the orbit menu, if only because that is all I used.

This has been resolved, I forgot to verify TGUI initializations were being handled by the middleware correctly

**Comment by ZephyrTFA** [comment]
> The admin gamepanel spawn menus are broken; searching for a term just doesn't pull up a list of results.

Resolved, I forget a semi-colon

**Comment by The-Moon-Itself** [comment]
also selecting the buying tab on the outpost console completely breaks the console.

**Comment by Sun-Soaked** [comment]
the crafting tab periodically disappears while you're interacting with it. The detection of "you have the resources to complete this recipe" also seems to be buggy and delayed

**Comment by Sun-Soaked** [comment]
The engine's SMES GUI seems to not update when settings such as output/input are changed- it only visually changes when you exit and re-enter

**Comment by tiramisuapimancer** [comment]
image
Font color changed on verb bar and now I can't see what I'm typing

edit: fixes itself after switching to light mode and back to dark?

**Comment by tiramisuapimancer** [comment]
LOOC was uncolored also.

**Comment by ZephyrTFA** [comment]
Last commit also fixed verb panel coloring being reset unintentionally;
all reported bugs are as of now fixed.

**Comment by Sweettoothart** [comment]
Writing on paper does NOT WORK at ALL. Erases the text when you click save therefore unable to actually write.

**Comment by Vexylius** [comment]
whoops

**Pull request merged**
