### PR TITLE
Removes oldcodeops.dmm

### PR DESCRIPTION
**Pull request by goober3**
## About The Pull Request
Removes the Strange Infiltrator Shuttle because it sucks, the loot's overpowered and it's utterly immersion-breaking.

This PR also removes the 'old' turfs, and chair.

## Why It's Good For The Game
look at it.

e6dacd7a6aee8c203537f1ced1eb7d8e-1

## Changelog

🆑
del: Removed oldcodeops.dmm (The 'old' nukeops ship ruin)
del: Removed 'old' turfs & old chair object.
/🆑

### CODE REVIEW

**Comment by rye-rice** [comment]
image
ellen rosales

**Comment by goober3** [comment]
ellen rosales

**Comment by Cadunkus** [comment]
ellen rosales
fen2

**Comment by CenkTheRaptor** [comment]
ellen rosales

**Comment by MemeSnorfer** [comment]
ellen rosales

**Comment by Hydrosatan** [comment]
Holy shit Ellen Rosales

**Pull request merged**
