### PR TITLE
Ports mothroaches + Moth emotes

### PR DESCRIPTION
**Pull request by meemofcourse**
## About The Pull Request
Can you guess what this PR does? If you answered that it ports [this pull request](https://github.com/tgstation/tgstation/pull/68763), [this pull request](https://github.com/tgstation/tgstation/pull/71784), and [a partial part of this one too](https://github.com/BeeStation/BeeStation-Hornet/pull/7645/), then you're right!
imagen
imagen

You can also craft moth plushies now. You just need some cloth, mothroach hide, and a heart!

## Why It's Good For The Game

silly little moth roaches and emotes, who wouldn't want them in the game?

## Changelog

:cl:
add: Mothroaches are now a thing
add: Moth laughter, chittering and squeaking
/:cl:

### CODE REVIEW

**Comment by AverageUser67** [comment]
Merge it
Mothroach fur sandbags (good)

**Comment by goober3** [comment]
awful. u should steal whatever the mouse code does to allow mothroaches to eat clothes

**Comment by BarteG44** [comment]
also let people poses them like mice

**Comment by AverageUser67** [comment]
theres no on-head sprite

**Comment by meemofcourse** [comment]
oh my god why is there no sprite it works on local

**Comment by goober3** [comment]
can u make a Mothroach Crate? to order from Cargo. for real!

**Comment by AverageUser67** [comment]
Infestation crate - Heavily locked crate that requires HoS/Captain access to open. It contains 20 mothroaches

**Comment by goober3** [comment]
moth rocket.

**Comment by meemofcourse** [comment]
those DAMN lizards are creating MERGE CONFLICTS in MY PULL REQUESTS! THIS IS THE FUTURE THE INTEQ WANTS

**Pull request merged**
