### PR TITLE
removes the atmospherics hardsuit from the cargo

### PR DESCRIPTION
**Pull request by Martinpachu**
## About The Pull Request

no

## Why It's Good For The Game

its faction gear!!!!!!!!!! you're not getting that
## Changelog

:cl:

del: The outpost has received a cease and desist letter originating from Nanotrasen, and no longer offer their iconic atmospherics hardsuits.
/:cl:

### CODE REVIEW

**Comment by SomeguyManperson** [comment]
Just change the description if its that dissonant

**Comment by Martinpachu** [comment]
> Just change the description if its that dissonant

its supposed to be used on NT ships though. other ships are supposed to use their own hardsuits on the independant engineering spacesuits which are already on the outpost

**Comment by generalthrax** [comment]
> its supposed to be used on NT ships though

image

This could easily be solved by simply adding a NT atmos hardsuit instead of removing a supposedly NT hardsuit that isn't even on NT ships that could easily be rebranded in this PR.

**Comment by FalloutFalcon** [comment]
imma close this since i dont think this change makes sense as explained by the comments.

**Pull request closed without merging**
